### ISSUE TITLE
Validating a JWT with a certificate thumbprint

### ISSUE THREAD

**Issue by solidstore** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#100]
The code in JwtHeader.SigningKeyIdentifier seems to create a X509ThumbprintKeyIdentifierClause using base64 urldecoded value from the x5t standard claim, but this clause does not match against another instance created using its other constructor which takes the X509 certificate as a parameter. The thumbprint values seem to be incorrect when using the Base64UrlEncoder.DecodeBytes method.
X509ThumbprintKeyIdentifierClause is used in the ResolveIssuerSigningKey method of the JwtSecurityTokenHandler class and tries to compare IssuerSigningKey (which is loaded from the certificate store using the same thumbnail) and doesnt match as the hash value is different.

**Comment by brentschmaltz** [comment]
thanks.
Looking into this.

**Comment by brentschmaltz** [comment]
@solidstore  not sure I understand your issue.

Can you have a look these tests at this commit: https://github.com/brentschmaltz/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/26245b87a0d77125b4a3dc9c21e56b2b4e5bf678

**Comment by solidstore** [comment]
@brentschmaltz I've taken your test and changed it slightly to use the jwt string I'm recieving as I only have the public key for the certificate. The validation fails. I believe the issue lies in the different way the certifcate thumbprint is interpreted in the various contructor of the X509ThumbprintKeyIdentifierClause  class.

Here's more details:
http://stackoverflow.com/q/29082734/487411

Here's my test again: and below that is the exception text - note the X509ThumbprintKeyIdentifierClause hash looks wrong.

            const string thumbPrint = "6bf8e136eb36d4a56ea05c7ae4b9a45b63bf975d"; // correct thumbprint of certificate
            var cert = X509CertificateHelper.FindByThumbprint(StoreName.My, StoreLocation.LocalMachine, thumbPrint).First();

            var handler = new JwtSecurityTokenHandler();

            var signedJwt =
                "eyJ0eXAiOiJKV1QiLCJhbGciOiJTSEEyNTZ3aXRoUlNBIiwieDV0IjoiTm1KbU9HVXhNelpsWWpNMlpEUmhOVFpsWVRBMVl6ZGhaVFJpT1dFME5XSTJNMkptT1RjMVpBIn0.eyJpc3MiOiJodHRwOi8vd3NvMi5vcmcvZ2F0ZXdheSIsImV4cCI6MTQyNjI1OTE5MTg1OCwiaHR0cDovL3dzbzIub3JnL2dhdGV3YXkvc3Vic2NyaWJlciI6ImFkbWluIiwiaHR0cDovL3dzbzIub3JnL2dhdGV3YXkvYXBwbGljYXRpb25uYW1lIjoiQXNwTmV0RGVtbyIsImh0dHA6Ly93c28yLm9yZy9nYXRld2F5L2VuZHVzZXIiOiJyeWFuQGNhcmJvbi5zdXBlciIsICJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL2Z1bGxuYW1lIjoicnlhbiIsICJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL2xhc3RuYW1lIjoicnlhbiIsICJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL3JvbGUiOiJhZG1pbixJbnRlcm5hbC9ldmVyeW9uZSJ9.f6KtZOVcKefVILZJPcru4-50ZaepzV9z24MSozXzjK-LQ_msSGa38SsV97wObDIoJTrEva2y_EWJl4inwcZ1wCGoD2GyIqOGOzgw05vgpMa6eNdDr0EyFytJxhn9MSDe1P5TqFOwWV0QjG-gVJfaTNb1sNo-jLfne2cBaYHHUtU";
            SecurityToken token = null;
            var validationParameters =
                new TokenValidationParameters
                {
                    IssuerSigningToken = new X509SecurityToken(cert),
                    ValidateAudience = false,
                    ValidateIssuer = false,
                    ValidateLifetime = false,
                };

            handler.ValidateToken(signedJwt, validationParameters, out token); // <-- this fails

Exception:

IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier

    (

    IsReadOnly = False,

    Count = 1,

    Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0x36626638653133366562333664346135366561303563376165346239613435623633626639373564)

    )

', 

token: '{"typ":"JWT","alg":"SHA256withRSA","x5t":"NmJmOGUxMzZlYjM2ZDRhNTZlYTA1YzdhZTRiOWE0NWI2M2JmOTc1ZA"}.{"iss":"http://wso2.org/gateway","exp":1426259191858,"http://wso2.org/gateway/subscriber":"admin","http://wso2.org/gateway/applicationname":"AspNetDemo","http://wso2.org/gateway/enduser":"ryan@carbon.super","http://wso2.org/claims/fullname":"ryan","http://wso2.org/claims/lastname":"ryan","http://wso2.org/claims/role":"admin,Internal/everyone"}

RawData: eyJ0eXAiOiJKV1QiLCJhbGciOiJTSEEyNTZ3aXRoUlNBIiwieDV0IjoiTm1KbU9HVXhNelpsWWpNMlpEUmhOVFpsWVRBMVl6ZGhaVFJpT1dFME5XSTJNMkptT1RjMVpBIn0.eyJpc3MiOiJodHRwOi8vd3NvMi5vcmcvZ2F0ZXdheSIsImV4cCI6MTQyNjI1OTE5MTg1OCwiaHR0cDovL3dzbzIub3JnL2dhdGV3YXkvc3Vic2NyaWJlciI6ImFkbWluIiwiaHR0cDovL3dzbzIub3JnL2dhdGV3YXkvYXBwbGljYXRpb25uYW1lIjoiQXNwTmV0RGVtbyIsImh0dHA6Ly93c28yLm9yZy9nYXRld2F5L2VuZHVzZXIiOiJyeWFuQGNhcmJvbi5zdXBlciIsICJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL2Z1bGxuYW1lIjoicnlhbiIsICJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL2xhc3RuYW1lIjoicnlhbiIsICJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL3JvbGUiOiJhZG1pbixJbnRlcm5hbC9ldmVyeW9uZSJ9.f6KtZOVcKefVILZJPcru4-50ZaepzV9z24MSozXzjK-LQ_msSGa38SsV97wObDIoJTrEva2y_EWJl4inwcZ1wCGoD2GyIqOGOzgw05vgpMa6eNdDr0EyFytJxhn9MSDe1P5TqFOwWV0QjG-gVJfaTNb1sNo-jLfne2cBaYHHUtU'.

**Comment by solidstore** [comment]
In the JwtHeader class, SigningKeyIdentifier property:

   public virtual SecurityKeyIdentifier SigningKeyIdentifier
   {
    get
    {
        SecurityKeyIdentifier ski = new SecurityKeyIdentifier();
        if (base.ContainsKey("x5t"))
        {
            try
            {
                ski.Add(new X509ThumbprintKeyIdentifierClause(Base64UrlEncoder.DecodeBytes(this.GetStandardClaim("x5t"))));
            }
            catch (Exception ex)
            {
            }
        }

I believe Base64UrlEncoder.DecodeBytes is not creating the correct binary thumbprint. The x5t is a base64url encoding string, that hex string then needs to be converted to binary in order to create the correct thumbprint.

**Comment by brentschmaltz** [comment]
Can you post the X509Data?
I am puzzled because other certs work.

**Comment by solidstore** [comment]
Here's the certificate that signed the JWT in my example:

-----BEGIN CERTIFICATE-----
MIICNTCCAZ6gAwIBAgIES343gjANBgkqhkiG9w0BAQUFADBVMQswCQYDVQQGEwJV
UzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDTALBgNVBAoM
BFdTTzIxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0xMDAyMTkwNzAyMjZaFw0zNTAy
MTMwNzAyMjZaMFUxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJDQTEWMBQGA1UEBwwN
TW91bnRhaW4gVmlldzENMAsGA1UECgwEV1NPMjESMBAGA1UEAwwJbG9jYWxob3N0
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUp/oV1vWc8/TkQSiAvTousMzO
M4asB2iltr2QKozni5aVFu818MpOLZIr8LMnTzWllJvvaA5RAAdpbECb+48FjbBe
0hseUdN5HpwvnH/DW8ZccGvk53I6Orq7hLCv1ZHtuOCokghz/ATrhyPq+QktMfXn
RS4HrKGJTzxaCcU7OQIDAQABoxIwEDAOBgNVHQ8BAf8EBAMCBPAwDQYJKoZIhvcN
AQEFBQADgYEAW5wPR7cr1LAdq+IrR44iQlRG5ITCZXY9hI0PygLP2rHANh+PYfTm
xbuOnykNGyhM6FjFLbW2uZHQTY1jMrPprjOrmyK5sjJRO4d1DeGHT/YnIjs9JogR
Kv4XHECwLtIVdAbIdWHEtVZJyMSktcyysFcvuhPQK8Qc/E/Wq8uHSCo=
-----END CERTIFICATE-----

**Comment by solidstore** [comment]
The code can be fixed to get the thumbprint using an internal class System.Security.Cryptography.X509Certificates.X509Utils from System assembly


            byte[] bytes = X509Utils.DecodeHexString(Base64UrlEncoder.Decode(X5T));
            var clause3 = new X509ThumbprintKeyIdentifierClause(bytes); // <--- this give correct hash

**Comment by brentschmaltz** [comment]
One thing confuses me. The value in the jwt.header["x5t"] is supposed to be the encoding of SHA-1of the thumbprint, according to https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-40 Section 4.1.7.
in this token, the value is: NmJmOGUxMzZlYjM2ZDRhNTZlYTA1YzdhZTRiOWE0NWI2M2JmOTc1ZA
Decoded is 40 bytes. SHA-1 is 20 bytes.

**Comment by ironicLemon** [comment]
Is this due to the jwt.header["x5t"] being set incorrectly in JwtHeader.cs

X509SigningCredentials x509SigningCredentials = signingCredentials as X509SigningCredentials;
                if (x509SigningCredentials != null && x509SigningCredentials.Certificate != null)
                {
                    this[JwtHeaderParameterNames.X5t] = Base64UrlEncoder.Encode(x509SigningCredentials.Certificate.GetCertHash());
                }

Should this not be this[JwtHeaderParameterNames.X5t] = Base64UrlEncoder.Encode(x509SigningCredentials.Certificate.Thumbprint);

I'm having a similar issues verifiying the signature of a JWT and getting the 
IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
exception

**Comment by solidstore** [comment]
The example JWT token was generated from a java open source product called WSO2 Identity Server. (http://wso2.com/products/identity-server/)

I'm fairly convinced that both the encoding and decoding in JwtHeader.cs isnt correct, especially when using token generated from other sources.

Take a look at how the thumbprint is used in other .net classes, e.g. X509Certificate2Collection.Find, which internally uses  X509Utils.DecodeHexString. This looks correct and works

**Comment by solidstore** [comment]
@brentschmaltz If you run the x5t string through a base64url decoder (http://kjur.github.io/jsjws/tool_b64udec.html)

input- NmJmOGUxMzZlYjM2ZDRhNTZlYTA1YzdhZTRiOWE0NWI2M2JmOTc1ZA
result- 6bf8e136eb36d4a56ea05c7ae4b9a45b63bf975d

This is the SHA-1 thumbprint of the X509 certificate.

Take a look at this snippet:

    const string thumbPrint = "6bf8e136eb36d4a56ea05c7ae4b9a45b63bf975d"; // correct thumbprint of certificate
    var clause1 = new X509ThumbprintKeyIdentifierClause(cert1);

    var hash = Base64UrlEncoder.DecodeBytes(thumbPrintBase64);  // <--- this is how JwtHeader decodes in get_SigningKeyIdentifier()
    var clause2 = new X509ThumbprintKeyIdentifierClause(hash);    // <----- broken

clause1 and clause2 should be equal but they arent!

**Comment by brentschmaltz** [comment]
I agree there is an issue, I am trying to ensure the spec is followed correctly. This is important with interrop issues.

Can we discuss two things:
1. the length of the 'x5t', the spec requires a SHA-1 hash, which is 20 bytes. The 'xt5' in this token is 40 bytes.
2. what does the spec define as input to base64Url to create the 'x5t'?
   a. A hex string representing the thumbprint.
   b. The digest of the certificate.

https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-40

**Comment by solidstore** [comment]
@brentschmaltz Agreed. 

Looks like the java server I'm working with has interpreted the spec differently. Looks like it comes down to which is correct for x5t?

            var thumbprint = Base64UrlEncoder.Encode(cert.GetCertHash());
            var thumbprint2 = Base64UrlEncoder.Encode(cert.Thumbprint);

**Comment by brentschmaltz** [comment]
I think that is it. 
I am going to contact Mike Jones who is an editor on the spec.  I see if he has time to comment on this thread.

**Comment by brentschmaltz** [comment]
As a workaround, TokenValidationParameters.IssuerSigningKeyResolver delegate can be used to return the key to use when checking the signature.

**Comment by selfissued** [comment]
The value is the one described at https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificate2.thumbprint(v=vs.110).aspx (the X509Certificate2.Thumbprint Property) and https://msdn.microsoft.com/en-us/library/ms734695(v=vs.110).aspx.

**Comment by brentschmaltz** [comment]
Digging a bit deeper, I believe the input to Base64UrlEncoder should be the output of SHA1 which is a bytearray.

**Comment by brentschmaltz** [comment]
I would like to close this issue.
Any concerns that the input should be a byte array?

**Comment by solidstore** [comment]
No issue, provided that ultimately during validation the X509ThumbprintKeyIdentifierClause ctor using a byte array is equal to the clause using the certificate ctor.

**Comment by brentschmaltz** [comment]
We should add a test for that what would that test look like?

**Comment by solidstore** [comment]
I am still having this issue, but now with JWT signed by ADFS 3.0
