### ISSUE TITLE
Feature Request: Please add a virtual function to allow for an easier time in extending onetime use Saml Tokens

### ISSUE THREAD

**Issue by Tarig0** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1005]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e9fe530ed023a1566c51567b4f91b88c59b35509/src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs#L909

It would nice if we didn't have to handle validating all of the conditions to add support for onetime use tokens.

**Comment by brentschmaltz** [comment]
@Tarig0 we will try and get this into 5.3.1
