### ISSUE TITLE
SAML2 Subjectconfirmation data lifetime check should be optional

### ISSUE THREAD

**Issue by Tarig0** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1006]
Currently if there is a subject confirmation node in the SAML2 token it will check the lifetime even if there is no lifetime information in the subject data node. This will in turn throw an error since the expire and notbefore arguments will be null.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e9fe530ed023a1566c51567b4f91b88c59b35509/src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs#L279-L288

**Comment by brentschmaltz** [comment]
@Tarig0	will get this in 5.3.1
