### ISSUE TITLE
Create KeyVaultSigningCredentials class to simplify instantiation of SigningCredentials 

### ISSUE THREAD

**Issue by GeoK** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1009]
Related to: #984 

It might be a good idea to create *KeyVaultSigningCredentials* class, similar to *X509SigningCredentials* class. Doing that, instantiation of *CryptoProviderFactory/CustomCryptoProvider* could be abstracted out and moved into to a *KeyVaultSigningCredentials* constructor.

So, instead of this call:
 
```C# 
var signingCredentials = new SigningCredentials(new KeyVaultSecurityKey(keyIdentifier, GetAccessToken), SecurityAlgorithms.RsaSha256)
            {
                CryptoProviderFactory = new CryptoProviderFactory
                {
                    CustomCryptoProvider = new KeyVaultCryptoProvider()
                }
            };
```
, a call would look like this:
 ```C#
 var signingCredentials = new KeyVaultSigningCredentials(new KeyVaultSecurityKey(keyIdentifier, GetAccessToken), SecurityAlgorithms.RsaSha256);
```

Same principle could later apply for *KeyVaultEncryptingCredentials* class.

**Comment by jennyf19** [comment]
closing as won't fix.
