### ISSUE TITLE
Error in DLL Version number included in nuget package System.IdentityModel.Tokens.Jwt v. 4.0.2.202250711

### ISSUE THREAD

**Issue by mschmeller** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#101]
The previous Version had the following version numbers 
System.IdentityModel.Tokens.Jwt         v. 4.0.1 
DLL: System.IdentityModel.Tokens.Jwt.dll 4.0.11102.1637 

The current Version 
System.IdentityModel.Tokens.Jwt        v. 4.0.2.202250711 
DLL: System.IdentityModel.Tokens.Jwt.dll 4.0.2.28 

Since the Version number of the DLL is now smaller than before (4.0.2.28 < 4.0.11102.1637) Installation Engines such as Install Shield will not replace the DLL in the installation directories.

**Comment by brentschmaltz** [comment]
I think I have to bump it to 4.1.0.xxxxx

**Comment by brentschmaltz** [comment]
this will be fixed in the next release

**Comment by tushargupta51** [comment]
@mschmeller Updated packages are pushed to nuget.org: 4.0.2.205111437

**Comment by tushargupta51** [comment]
@mschmeller Closing the issue. The new packages on nuget.org should have the versions fixed. Please let me know if that's not the case. Thanks!
