### ISSUE TITLE
[SAML2] Null pointer error if using the IssuerSigningKeyResolver

### ISSUE THREAD

**Issue by Tarig0** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1026]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs#L336

If you use a custom issuersigningkeyresolver there is no way for the token.Signingkey to be set

**Comment by brentschmaltz** [comment]
@Tarig0 sorry to miss this.
We will get this into 5.3.1.
