### ISSUE TITLE
OpenIdConnectProtocolException: IDX21345

### ISSUE THREAD

**Issue by RubenDelange** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1031]
I'm using a OpenID Connect user info endpoint which returns a JWT that does not contain a sub claim.

This triggers the following exception:
```
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: IDX21345: OpenIdConnectProtocolValidationContext.UserInfoEndpointResponse does not contain a 'sub' claim, cannot validate.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateUserInfoResponse(OpenIdConnectProtocolValidationContext validationContext)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<GetUserInformationAsync>d__23.MoveNext()
```
I can read the user profile properties via the OnUserInformationReceived event (context.User property), so I'm guessing the JWT itself is fine.

However, I can't change the behavior of the user info endpoint, so is there a way I can safely skip the userinfo response validation or disable the "check for the sub claim in the userinfo response"-behavior?

Using this doesn't help:
```
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();
```

Thanks in advance

**Comment by brentschmaltz** [comment]
@RubenDelange what provider are you using?
While the requires a 'sub' claim, 
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

The value from the UserInfoEndpoint is supposed to have the same 'sub' as the original id_token.

OpenIdConnectProtocolValidator is extensible and you can plug a custom OpenIdConnectProtocolValidator and override ValidateUserInfoResponse.

In asp.net, OpenIdConnectOptions.ProtocolValidator is a hook to set a custom OpenIdConnectProtocolValidator

**Comment by RubenDelange** [comment]
Hi @brentschmaltz , you are right stating that the sub claim MUST always be returned in the UserInfo Response - cfr. https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse
I filed a bug for the provider I'm integrating with.

In the meantime, I'll look into the ProtocolValidator hook. Thank you!

**Comment by brentschmaltz** [comment]
@RubenDelange if you could share the provider, that would help us in guiding others.
If not possible, that's fine.

**Comment by RubenDelange** [comment]
Provider I'm integrating with is a federal service of the Belgian government

**Comment by brentschmaltz** [comment]
@RubenDelange 	
Thanks. I will close this for now, please reopen if needed.

**Comment by RubenDelange** [comment]
FYI: apparently ForgeRock OpenAM is used for the underlying implementation
