### ISSUE TITLE
Feature: encrypt-then-sign JWT

### ISSUE THREAD

**Issue by StevenLiekens** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1032]
Please support creating JWTs that are first encrypted and then signed.

**Package**:  System.IdentityModel.Tokens.Jwt version 5.3.0
**Class**: System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler

Right now it's hardcoded to always sign first and encrypt last.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/43f840f3628dcb2dabb1003b9e8ab2e752b20ee5/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L480-L512

**Extra info**

It's recommended to first sign and then encrypt tokens (i.e. the current behavior) but it's not invalid to do it in reverse order according to [RFC 7519 (JSON Web Token) section 11.2](https://tools.ietf.org/html/rfc7519#section-11.2).

I'm requesting this feature because I'm authenticating with a server that expects tokens that were encrypted first and signed last.

**Comment by henrik-me** [comment]
@StevenLiekens : The library uses authenticated encryption. Currently we don't do separate steps.

**Comment by StevenLiekens** [comment]
I ended up switching to [jose-jwt](https://www.nuget.org/packages/jose-jwt/) for generating tokens. Their API allows signing and encrypting in any order since they're separate methods.

You can close this if you want.

**Comment by brentschmaltz** [comment]
@StevenLiekens curious. You are asking for the payload to be a JWE of a JWS right?
Why is that?

**Comment by StevenLiekens** [comment]
Correct, but in the end that's not what I really needed. In the end I went back to generating JWS tokens with JWE payloads, which is already supported by this library. So this is really a non-issue at this point and you can close it if you want.

With that said, I prefer jose-jwt now because their API is _nicer_ (personal opinion) and because they do enable generating JWE tokens with JWS payloads, which I might need one day (but probably not).

**Comment by brentschmaltz** [comment]
@StevenLiekens we are open to making changes if customers ask for them. We only support Authenticated encryption, so putting a JWE as the payload of a JWS seems redundant. 
Are you suggesting that the JWE (encoded) would not use a tamper proof encryption algorithm?

**Comment by StevenLiekens** [comment]
I'm not sure anymore. 🤔 I didn't know authenticated encryption is a thing.

> Are you suggesting that the JWE (encoded) would not use a tamper proof encryption algorithm?

I think so. The encryption key in my scenario is a public key so it would be pretty easy for anybody to generate tokens that are encrypted with the same key.

The thing that makes this tamper proof is the JWS that is signed with a private key.

**Comment by brentschmaltz** [comment]
@StevenLiekens a new design of encryption algorithms have arrived that incorporate tamper detection. GCM and some Aes variants.

We have support for Aes128CbcHmacSha256, Aes192CbcHmacSha384, Aes256CbcHmacSha512 here: 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/Encryption/AuthenticatedEncryptionProvider.cs

GCM has been promised in .NET Core, but I am unaware of the delivery date.

You are totally correct that encryption needs to be wrapped with a signature. There are a set of attacks (oral padding attack one) that are mitigated by the signing. This is what led to the authenticated class of encryption algorithms.

You can get some context from the JWE spec here: https://tools.ietf.org/html/rfc7516

Please feel free to contact us if you need more info.
