### ISSUE TITLE
Add symbols to microsoft's public symbol server

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1036]
For all IdentityModel assemblies the retail pdb's need to be added to microsoft's symbol servers so debuggers such as WinDbg can find the symbols.

**Comment by GeoK** [comment]
@brentschmaltz - We upload symbols to the NuGet.org symbol server (SourceLink enabled) and to symweb.
Is there still a requirement to upload symbols to Microsoft Symbol Servers?

**Comment by brentschmaltz** [comment]
@GeoK since the goal is for users to be able to get symbols, closing this issue.
