### ISSUE TITLE
Missing SAML message digest verification

### ISSUE THREAD

**Issue by sanjaysingh** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1039]
I am using Saml2SecurityTokenHandler to validate a SAML2 token and find that there is no message digest verification as was available in Windows Identity Foundation. This seems important to me because changing the SAML token will still pass the validation and generate a Principal. 

Is this by design? If yes then can you point to a any link on how it is supposed to be used. I am porting an application to .Net Core and using this Microsoft.IdentityModel package to validate incoming SAML token in the header. It fails with Windows Identity Foundation as it should in my opinion if token is altered but works with this  Microsoft.IdentityModel package.

**Comment by sanjaysingh** [comment]
I noticed that passing the cert in IssuerSigningKey of TokenValidationParameters does the job but then how do i get the cert without requiring for me to have it installed. Previously it used to do the validation by just having the thumbprint in the config file for a list of known issuers but i don't see anyway to specify thumbprint anymore. One option i have tried is extracting the cert from the token itself as follows-

Saml2SecurityTokenHandler handler = new Saml2SecurityTokenHandler2();
            var saml2Token = handler.ReadSaml2Token(plainSaml);
            X509Certificate2 cert = new X509Certificate2(Encoding.UTF8.GetBytes(saml2Token.Assertion.Signature.KeyInfo.X509Data.First().Certificates.First()));
            var signingKey = new X509SecurityKey(cert);
            var validator = new TokenValidationParameters
            {
                IssuerSigningKey = signingKey,
            };
            var principal = handler.ValidateToken(plainSaml, validator, out var secToken);

I think there has to be an easy way to validate it than what i am doing. Looking for guidance.

**Comment by brentschmaltz** [comment]
@sanjaysing yes, as you see you need to validate the token. Reading does not validate.
However, if you use the key inside the SAML2 token, then you must validate that you trust that key is owned by a trusted authority.

Our model is to obtain metadata from a trusted location, then set TokenValidationParameters with the key and issuer returned from metadata.
You will also need to set the ValidAudience property to ensure the token was meant for your application.

Our Wiki has additional info on how we think about validation.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/ValidatingTokens

**Comment by sanjaysingh** [comment]
Thank you @brentschmaltz for quick response. My question is around how to go about validating that the token is from an issuer with certificate whose thumbprint i know and also that the token has not been tampered. With the System.IdentityModel we had following sample configuration take care of it. Nothing else was required.

``` XML
  <system.identityModel>
    <identityConfiguration saveBootstrapContext="true">
      <audienceUris>
        <add value="http://nonproductionidentity.mycompany.com/application1" />
      </audienceUris>
      <certificateValidation certificateValidationMode="None" />
      <issuerNameRegistry type="System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
        <trustedIssuers>
          <add thumbprint ="022d5e4993a87c2d693bf01912a8333d5ff58df8" name="identityserver1.mycompany.net"/>
          <add thumbprint = "c58a90087a548d4c1bc1e609a9caa658e916ca83" name ="identityserver2.mycompany.net"/>
        </trustedIssuers>
      </issuerNameRegistry>
    </identityConfiguration>
  </system.identityModel>
```

Audience URI is working fine when i feed in the parameter. I removed that code because it was not the issue i wanted to highlight here. The question is - given that i know the thumbprint of the issue how can i validate the token to ensure that it has been issued by the right ASFS and that token is not tampered. Both of these guarantees were being met with the System.IdentityModel approach so i am guessing the same would be possible with the Microsoft.IdentityModel approach as well. I can do the same by reading the cert from the token and doing manual thumprint match but i am not sure if that is the right approach and it works fine with the same guarantees.

Here is the complete code that works but seems too complicated

``` C#
Saml2SecurityTokenHandler handler = new Saml2SecurityTokenHandler2();
var saml2Token = handler.ReadSaml2Token(plainSaml);
X509Certificate2 cert = new X509Certificate2(Encoding.UTF8.GetBytes(saml2Token.Assertion.Signature.KeyInfo.X509Data.First().Certificates.First()));
var signingKey = new X509SecurityKey(cert);
var validator = new TokenValidationParameters
{

           IssuerSigningKey = signingKey,
           IssuerValidator = (issuer, token, parameters) => cert.Thumbprint.Equals("022d5e4993a87c2d693bf01912a8333d5ff58df8", StringComparison.OrdinalIgnoreCase) ? issuer : throw new SecurityTokenInvalidIssuerException("Invalid issuer")
                    { InvalidIssuer = issuer },
                ValidAudiences = new string[] { "http://nonproductionidentity.mycompany.com/application1" }
};

var principal = handler.ValidateToken(plainSaml, validator, out var secToken);
```

**Comment by brentschmaltz** [comment]
@sanjaysingh your code will work if the token is valid.

You may want to consider obtaining the metadata from a trusted authority using ConfigurationManager and WsFederation as below. This is the best way to go. You can hook the delegate: TokenValidationParameters.IssuerSigningKeyValidator to validate the key that signed the token.

We don't have a config solution for this version of IdentityModel.
The asp.net has been designed to do most of this work for you.

```
var clientId = "<put clientid here>";
var configurationManager = new ConfigurationManager<WsFederationConfiguration>(
                "https://login.microsoftonline.com/common/FederationMetadata/2007-06/FederationMetadata.xml",
                new WsFederationConfigurationRetriever());

var wsFedConfiguration = configurationManager.GetConfigurationAsync().GetAwaiter().GetResult();
var validationParameters = new TokenValidationParameters
{
    IssuerSigningKeys = wsFedConfiguration.SigningKeys,
    IssuerSigningKeyValidator = IssuerSigningKeyValidator,
    ValidAudience = clientId,
    ValidIssuer = wsFedConfiguration.Issuer
};

var samlToken = "<put saml token here>";
var samlTokenHandler = new SamlSecurityTokenHandler();
var claimsPrincipal = samlTokenHandler.ValidateToken(
                                    samlToken,
                                    validationParameters, 
                                    out SecurityToken samlSecurityToken);

```

I pushed the code here:
https://github.com/brentschmaltz/IdentityModel/tree/master/WsFederationMetadata

**Comment by sanjaysingh** [comment]
Thank you for the detailed explanation.
This is a a great workaround but i will still not be able to easily port my application because this approach is adding runtime dependency on the ADFS server to retrieve the metadata. As a downstream system, the only thing i needed was to be able to validate the token being passed.

I have Audience and Thumbrint in the config file and hoped that this would be enough to validate the token with all the guarantees that the code you provides gives after adding this dependency to download the federation metadata at runtime.

One question for you. Does providing the IssuerSigningKeys from federation metadata give additional security over what was being done in System.IdentityModel world? It worked on Thumbprint and AudeienceUri and for the all the attack use cases i have tried it worked really well as well. In short i want to avoid adding this runtime dependency for validation if there is no additional security benefit i can explain.

Thank you for bearing with me on this.

**Comment by brentschmaltz** [comment]
@sanjaysingh obtaining the keys from metadata is preferred as it provides the current status of the keys. In the case a key is compromised, the key could be quickly removed.
It also provides a pattern of key-rollover where two keys are in the metadata but only one is current.

I am curious why obtaining metadata is a blocker? Is the ADFS server not addressable from the workload?

**Comment by sanjaysingh** [comment]
Thank you @brentschmaltz for the answer. The downstream service in my case is in a differrent Network Security Zone where outbound is blocked - including the one to ADFS. Since previous it was only validating the token using System.Identity by using AudienceURI and Thumbprint of the cert, it was working all good offline. That is why i was interested in the getting this migration working with as little infrastructural changes as possible - Mainly if i did not see any issues with existing mechanism. For the cert scenario, If ADFS cert to be compromised then they can change the cert which would change the thumbprint and so would fail the validation at the downstream service unless we update the thumbprint in the configuration of downstream service.

I am currently thinking to use the approach that i sent above to have the similar behavior as before and plan to see if can switch to obtaining metadata from ADFS as a future strategy. Since all the validation is configuration i still believe a clear cut path to do the offline validation like System.identityModel with minimal code on the dev side would benefit.

Thank you for help. I for sure learnt something from this.

**Comment by mafurman** [comment]
@sanjaysingh Closing this issue, if you have any other questions feel free to ask.
