### ISSUE TITLE
Add overload to Saml2SecurityTokenHandler to consume a token from an XmlReader

### ISSUE THREAD

**Issue by AndersAbel** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1042]
When working with the SAML2P protocol, the token (assertion in Saml2 terms) is embedded inside a larger piece of XML, the SamlResponse - or inside an artifact resolution response message. Code supporting Saml2P will typically already have an open XmlReader to the data. Add overloads to be able to hand in an XmlReader instead of a string to the token validation API.

This was discussed in #759, but is really an own separate task that is for SAML2P support rather than metadata support. So it should have it's own issue.

**Comment by AndersAbel** [comment]
Have started looking at this and found out that the `SaveSigninToken` flag is a challenge, as it expects the entire token to be present in string format.

I first considered just not supporting `SaveSigninToken` when using an Xml Reader, but I do see some use cases ahead where I will need that, so this must be solved.

My first idea was to just fall back to extract the OuterXml of the Assertion node in a Saml Response message and store it. However, that might not work if the namespace declarations are placed on the enclosing Response node. This is a well-known problem with signatures over part of XML Documents and that is why a canonicalization transform is always used.

I'm considering trying to get the output of the canonicalization transform (based on the recorded TokenStream) and write that out to a string representation that can be saved. It should keep the semantics of the assertion and make it possible to validate the standalone string representation.

Any thoughts @brentschmaltz @GeoK?

**Comment by brentschmaltz** [comment]
@AndersAbel I have had issues with OuterXml and xml that contains '/r/n'. I have found that normalization will replace to '/n' and then signatures start failing. See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1029

I believe you will need the canonicalized string representation of the SAML token.

**Comment by brentschmaltz** [comment]
Will also add to SamlSecurityTokenHandler

**Comment by brentschmaltz** [comment]
@AndersAbel I think we can get the canonical stream as we have collected all the nodes.

**Comment by brentschmaltz** [comment]
Added with:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1181
