### ISSUE TITLE
Upgrading Microsoft.IdentityModel.Protocol.Extensions from 1.0.2.206221351 to 1.0.4.403061554 breaks MSI upgrade

### ISSUE THREAD

**Issue by staylr** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1043]
File version of Microsoft.IdentityModel.Protocol.Extensions.dll:
In 1.0.2.206221351: 1.0.**20622**.1351
In 1.0.4.403061554: 1.0.**4**.54

A major upgrade will not replace this file.

**Comment by staylr** [comment]
Same issue with System.IdentityModel.Tokens.Jwt.dll: 
In 4.0.2.206221351: 4.0.20622.1351
In 4.0.4.403061554: 4.0.4.54

**Comment by henrik-me** [comment]
@staylr : Can you please provide additional information on the error you are seeing. Please describe the repro steps.

**Comment by staylr** [comment]
There's no error. Because the file version of the newer DLL is lower than the file version of the older DLL (4 < 20622) a major upgrade will not replace it.

**Comment by brentschmaltz** [comment]
@staylr is your issue the assembly version in the dll?
Are your builds using the assembly version?

**Comment by staylr** [comment]
When performing an upgrade Windows Installer uses the file version (not the assembly version) to work out whether a file in the installer is newer than the existing one. Because later versions of these DLLs have lower file versions because you changed your version numbering scheme the file doesn't get replaced, leaving the old version installed.

**Comment by brentschmaltz** [comment]
@staylr I see. 
I think we addressed this in our 5.x builds.
Do you have to stay with our 4.x version?
Is so, we will have to push out a new assemblies to address this.

**Comment by brentschmaltz** [comment]
@staylr we upgraded Katana to use 5.x of IdentityModel.
So if you upgrade Katana 4.0, you should be able to use 5.x

https://github.com/aspnet/AspNetKatana/

**Comment by brentschmaltz** [comment]
@staylr are you able to upgrade to Katana 4.x?

**Comment by staylr** [comment]
I think I managed to juggle dependencies so I could avoid upgrading any of these components for now. If I need to upgrade in future I'll try that. Thanks.

**Comment by brentschmaltz** [comment]
@staylr again, sorry for the hassle.
