### ISSUE TITLE
System.IdentityModel.Tokens.ISecurityTokenValidator could not be loaded

### ISSUE THREAD

**Issue by hannespreishuber** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1049]
Visual Studio 2017 Web Site (not solution) VB.NET Webforms
Schweregrad Code Beschreibung Projekt Datei Zeile Unterdrückungszustand
Fehler Reference.svcmap: Der Typ "System.IdentityModel.Tokens.ISecurityTokenValidator" in der Assembly "System.IdentityModel.Tokens.Jwt, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" konnte nicht geladen werden. App_WebReferences/CheckVatServiceReference1/

this comes after stuck in nuget packaged Versionen (removing, adding ….)
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="bootstrap" version="4.1.3" targetFramework="net462" />
  <package id="EntityFramework" version="6.2.0" targetFramework="net462" />
  <package id="EntityFramework.de" version="6.2.0" targetFramework="net462" />
  <package id="FontAwesome" version="4.7.0" targetFramework="net462" />
  <package id="jQuery" version="3.3.1" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.Core.de" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.de" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb.de" version="2.3.0" targetFramework="net462" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net462" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net462" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net462" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.1" targetFramework="net462" />
  <package id="Microsoft.Graph" version="1.12.0" targetFramework="net462" />
  <package id="Microsoft.Graph.Core" version="1.12.0" targetFramework="net462" />
  <package id="Microsoft.Identity.Client" version="2.4.0-preview" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Logging" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols.WsFederation" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Tokens.Saml" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Xml" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.de" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.SystemWeb.de" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.ReportingServices.ReportViewerControl.WebForms" version="150.900.148" targetFramework="net462" />
  <package id="Microsoft.SqlServer.Types" version="14.0.1016.290" targetFramework="net462" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net462" />
  <package id="Owin" version="1.0" targetFramework="net462" />
  <package id="popper.js" version="1.14.3" targetFramework="net462" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.3.0" targetFramework="net462" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net462" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net462" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net462" />
</packages>`

**Comment by GeoK** [comment]
Hi @hannespreishuber 

`<package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net462" />`  looks out of place in that list. Try removing it.

For more information, check out Katana (OWIN) migration process on our [wiki](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Migrating-from-Katana-(OWIN)-3.x-to-4.x#when-upgrading-to-katana-40-it-is-important-to-remove-all-references-to-identitymodel-4x-in-your-project-file-listed-below).

**Comment by hannespreishuber** [comment]
ok, thats sounds reasonable. I have setup a new blank identitcal website without any the logic, same packages (also extensions) and got no error. I see thats kind of mystical bug searching
