### ISSUE TITLE
Wrong claim type "name" after successful authentication

### ISSUE THREAD

**Issue by bjthomson** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1051]
Hopefully this is the right place, have been sent off with a flea in my ear for posting in OpenIDConnect.
Noted the issue using version 5.3.0, in a webforms project, prior to installing in an existing webforms project.

I initially raised a documentation issue, then investigated further.
Details here: MicrosoftDocs/azure-docs# 18110

tldr; The OpenIDConnect middleware is adding the users name with a claim type of **name**, but the ClaimsIdentity.Name  property is looking for a type of **http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name**

Update: I found an answer in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/899

I added this and now the ClaimsIdentity does have the Name set.
` // Specify the claims to **validate**
`		TokenValidationParameters = new TokenValidationParameters
`		{
`			**NameClaimType = "name"**
`		},

So I have to override the default behaviour because the name didn't get added with the right namespace prefix?

That was not obvious. I hope this fix wont break when the internal code changes, per @brentschmaltz comment.

**Comment by brentschmaltz** [comment]
@bjthomson different IdentityProviders have the ability to specify the 'claim' that represents the 'user name'. The [Jwt specifies the 'sub'](https://tools.ietf.org/html/rfc7519#section-4.1) but 'sub' is optional. 

It may be simpler to set the NameClaimTypeRetriever, which will get called just before the ClaimsIdentity is being created AFTER the token has been validated.

You will have the ability to review the token (issuer, etc) before making a decision on the proper value for 'name'.

**Comment by brockallen** [comment]
In the older way of thinking these values are often conflated, and is why the claim types are so confused and misused in ASP.NET [Core]. In the world of SSO and OIDC:

The `sub` claim is the user's unique id (e.g. "4834934jh34uiy8s9sdio4"). This is what a consuming app or API should depend upon for correlation of the user's login (think of it as the user's foreign key issued by the SSO server).

The `name` claim is the user's display name (e.g. "Brock Allen").

The concept of username is what the user enters into the login page of the identity provider (e.g. "fluffybunny9"). IMO this is a detail between the user and the identity provider and is not important or interesting for the consuming apps or API. The OIDC spec does have a claim type for it though, which is the `preferred_username` claim if the token server were to pass it along.

**Comment by brentschmaltz** [comment]
@brockallen that is an excellent way to think about the different claims. Do you know if most / any IDP's set the `preferred_username` claim?

**Comment by bjthomson** [comment]
Some good background here, thank you gentlemen. My use case is I want users to authenticate via their windows live account, and we'll use 
**http://schemas.microsoft.com/identity/claims/objectidentifier**
as a key for our "shopping basket" - its not a shop, BTW.
My confusion arose because I was using a Microsoft platform to log in to a Microsoft IDP, and a Microsoft webforms object to display "the username". I figured they should all tie up. Mea culpa.

I'm not too bothered about using other IDPs - In the current climate I'm not sure everyone is comfortable "logging in via Facebook/twitter/google" - I see no reason for Zuck, Dorsey or Page to know what I'm doing every time I authenticate somewhere. At least with Live.com I can go into the GDPR page and delete my activity / location tracking / purchases. 

I think its too easy for us to get sucked into the technical challenge and forget about the end-user experience, I'm constantly struggling to explain the difference between an email address and an account login to my family. 

Looking at a claims dump after I've logged in to live.com via OIDC, I see the claim **name** is my name (**Brian Thomson**) and the claim **preferred_username** is my Hotmail address - which is the "user name" I use to log in to visual studio, MSDN, azure portal etc. 

Its also the primary email address/account name on my Lumia 920 (and I'm not replacing that until the battery finally expires).

**Comment by GeoK** [comment]
@bjthomson We are closing for now. Please re-open it if you need anything else from us.

**Comment by bjthomson** [comment]
Hmmm, OK, but where do we stand in terms of the code? If you read the original post, the issue is: The OpenIDConnect middleware is adding the users name with a claim type of **name**, but the ClaimsIdentity.Name property is looking for a type of **http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name**

The result is that an <asp:LoginName control displays blank if the user is logged in via OIDC, but it shows his preferred_name when logged in via Forms or Windows auth. (Of course, Windows Auth doesn't work with Edge - I guess that's another battle to fight.)
I think the various modes of authentication should have consistent behaviour (and work).
Either that or add some documentation to explain how to work around it.
Just MHO.

**Comment by jimitndiaye** [comment]
Just run into this same issue. Azure AD v1.0 uses the old `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` wheres v2.0 uses `preferred_username`. I just wish there was a way of snooping which is which in maybe NameClaimRetriever - I don't see an obvious way of doing that without hard-coding it to specific issues.

**Comment by bjthomson** [comment]
@jimitndiaye if you want anyone to respond to this, you probably need to reopen the issue. I suspect they have filters looking an issue != closed.

**Comment by brentschmaltz** [comment]
@bjthomson @jimitndiaye this is a thorny issue as the value you want to display is related to the identityprovider. 
The NameClaimRetriever in conjunction with the claimtype that ClaimsIdentity.Name resolved to were designed to help you handle this issue. 
NameClaimTypeRetreiver will return the claimtype that ClaimsIdentity will use when returning the value for 'Name'.

**Comment by bjthomson** [comment]
Lost the pitch for the customer who wanted this when I raised the ticket.

Just to summarise (again) The OpenIDConnect middleware is adding the users name with a claim type of **"name"**, but the ClaimsIdentity.Name property is looking for a type of **"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"**

Between Azure AD 1.0 and 2.0 it would seem MS made a breaking change, which I was unaware of. Maybe that's why we couldn't get it working reliably. I'm not sure what other IDPs do, but surely it should not be the job of each individual web site to work out what the IDP is doing?

When MS changed all the identity components in the 4.5 framework to derive from ClaimsPrincipal etc, it was fairly painless to start using the new functionality (glossing over the confusion between System.Security.Claims vs System.IdentityModel.Claims ). Oh except for ADFS when you dropped FedUtil, and we had to start munging about in web.config with notepad...

Ultimately, whether I query 

- Environment.UserName 
- HttpContext.Current.User.Identity.Name 
- slap an asp:loginName control on a webform 
- get SystemInformation.UserName on a Winform,  
-  etc

I should get the user's human name, whether she logged on via Forms Authentication, Windows Authentication, ADFS, AAD, OIDC, Knuclebone casting. 

Just MHO. 

I'll explore authentication in .Net core some time. I anticipate another adventure.

(BTW good to see that Edge Chromium works with Windows Authentication. Yay!)

**Comment by brentschmaltz** [comment]
@bjthomson it would be hard for me to commit to all the above scenarios are covered. However, Azure AD 1.0 and 2.0 should just work w.r.t. User.Identity.Name should be the same, that is something we are working on.

**Comment by jimitndiaye** [comment]
@brentschmaltz , @bjthomson I worked around the issue by automatically mapping the preferred_username claim to the name claim via the JwtSecurityTokenHandler settings:
```
// Map 'preferred_username' to Name claim if available.
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap["preferred_username"] = ClaimTypes.Name;
```
This automatically converts the claims when necessary allowing both Azure AD 1.0 and 2.0 to work.

**Comment by brentschmaltz** [comment]
Excellent idea.
