### ISSUE TITLE
OpenIdConnectConnect should not serialize SecurityKeys

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1053]
Calling: JsonConvert.SerializeObject(new OpenIdConnectConfiguration()) results in JSON that contains entries for the SecurityKeys collection. This makes it difficult to use the serialization for generating metadata for discovery.

**Comment by mafurman** [comment]
@brentschmaltz Should JsonWebKeySet still be serialized if it's null?
