### ISSUE TITLE
Replace the dependency on Newtonsoft.Json with new .NET Json APIs

### ISSUE THREAD

**Issue by natemcmaster** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1060]
As recently announced, the .NET team is adding new APIs for JSON parsing. IdentityModel currently relies on Newtonsoft.Json for JSON parsing. This often causes problems for customers who want to use a different version of Newtonsoft.Json. It also makes it more difficult to enable complete customer support for products like ASP.NET Core because Microsoft does not have ownership of Newtonsoft.Json.

I believe these problems will be resolved by replacing the Newtonsoft.Json dependency with the new JSON APIs announced in https://github.com/dotnet/announcements/issues/90

This will unblock https://github.com/aspnet/AspNetCore/issues/4260.

**Comment by brentschmaltz** [comment]
we need the 3.0 api's

**Comment by Seyden** [comment]
Whats the status? As far as i know, the 3.0 APIs are already released, i would like to remove my Newtonsoft.JSON references.. i only need it right now for the identityModel

**Comment by brentschmaltz** [comment]
@Seyden in our 6.x release, we have removed our references to Newtonsoft.
We plan on releasing a 6.x in the .NET 3.0 timeline.

**Comment by OliverRC** [comment]
We've began moving all our stuff over to System.Text.Json in .NET Core 3.1.
Would be great to fully drop Newtonsoft, this library is one of the last few which still has a Newtonsoft dependency 👍

**Comment by brentschmaltz** [comment]
@OliverRC we are figuring that out.
It's a bit more complicated than just removal as some types used by asp.net and other runtimes depend on our types that have newtonsoft dependencies.

**Comment by kevinchalet** [comment]
@brentschmaltz you mentioned in https://github.com/dotnet/aspnetcore/issues/36175#issuecomment-1012326509 you were making good progress on that. Could you please tell us more about your plans? E.g what does that mean for the older TFMs that can't reference STJ? Will they keep using the internal JSON.NET copy or will they be removed?

**Comment by lechu445** [comment]
@kevinchalet https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1768#issuecomment-965666920 of @brentschmaltz says that you can track progress on Json.NET in branch https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/brentsch/SystemTextJson

**Comment by brentschmaltz** [comment]
@kevinchalet we are shooting for an April release.

**Comment by cakescience** [comment]
Any news about the migration to STJ?

**Comment by brentschmaltz** [comment]
@cakescience it looks like a june / july release.

**Comment by jennyf19** [comment]
Included in IdentityModel7x.
