### ISSUE TITLE
When creating a ClaimsIdentity, there should be a way of providing a different value for ClaimTypes.Actor

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1061]
The CreateClaimsIdentity() method in JwtSecurityTokenHandler always assumes that the value of the actor claim is present under ClaimTypes.Actor. It should be possible to change this default value in the case of the JsonWebTokenHandler.

**Comment by brentschmaltz** [comment]
should be fixed with:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1840
