### ISSUE TITLE
JWT signature validation fails on iOS starting 5.3.0

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1067]
I get a CryptographicException with "keyset not found" in 5.3.0 - same code works fine with 5.2.4.

**Comment by GeoK** [comment]
Hi @leastprivilege  - we need additional information on this.
Please provide stack trace and runtime/target framework version.

**Comment by leastprivilege** [comment]
**Library**
https://github.com/IdentityModel/IdentityModel.OidcClient2

**Repro**
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/iOS11Client

**Exception***
IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: 8ad1760832d419352845575d62a19a40\n'. \nkid: '8ad1760832d419352845575d62a19a40'. \nExceptions caught:\n 'System.Security.Cryptography.CryptographicException: Keyset does not exist\n  at System.Security.Cryptography.RSACryptoServiceProvider.Common (System.Security.Cryptography.CspParameters p) [0x00039] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/corlib/System.Security.Cryptography/RSACryptoServiceProvider.cs:117 \n  at System.Security.Cryptography.RSACryptoServiceProvider..ctor (System.Int32 dwKeySize, System.Security.Cryptography.CspParameters parameters) [0x0001d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/corlib/System.Security.Cryptography/RSACryptoServiceProvider.cs:84 \n  at System.Security.Cryptography.RSACryptoServiceProvider..ctor (System.Security.Cryptography.CspParameters parameters) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/corlib/System.Security.Cryptography/RSACryptoServiceProvider.cs:67 \n  at Microsoft.IdentityModel.Tokens.RSACryptoServiceProviderProxy..ctor (System.Security.Cryptography.RSACryptoServiceProvider rsa) [0x00090] in C:\\agent2\\_work\\56\\s\\src\\Microsoft.IdentityModel.Tokens\\RsaCryptoServiceProviderProxy.cs:93 \n  at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.Initialize (System.Security.Cryptography.RSA rsa, System.String algorithm) [0x0002d] in C:\\agent2\\_work\\56\\s\\src\\Microsoft.IdentityModel.Tokens\\AsymmetricAdapter.cs:305 \n  at Microsoft.IdentityModel.Tokens.AsymmetricAdapter..ctor (Microsoft.IdentityModel.Tokens.SecurityKey key, System.String algorithm, System.Security.Cryptography.HashAlgorithm hashAlgorithm, System.Security.Cryptography.HashAlgorithmName hashAlgorithmName, System.Boolean requirePrivateKey) [0x00047] in C:\\agent2\\_work\\56\\s\\src\\Microsoft.IdentityModel.Tokens\\AsymmetricAdapter.cs:92 \n  at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.ResolveAsymmetricAdapter (Microsoft.IdentityModel.Tokens.SecurityKey key, System.String algorithm, System.Boolean requirePrivateKey) [0x00008] in C:\\agent2\\_work\\56\\s\\src\\Microsoft.IdentityModel.Tokens\\AsymmetricSignatureProvider.cs:207 \n  at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor (Microsoft.IdentityModel.Tokens.SecurityKey key, System.String algorithm, System.Boolean willCreateSignatures) [0x000a4] in C:\\agent2\\_work\\56\\s\\src\\Microsoft.IdentityModel.Tokens\\AsymmetricSignatureProvider.cs:134 \n  at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider (Microsoft.IdentityModel.Tokens.SecurityKey key, System.String algorithm, System.Boolean willCreateSignatures) [0x00253] in C:\\agent2\\_work\\56\\s\\src\\Microsoft.IdentityModel.Tokens\\CryptoProviderFactory.cs:442 \n  at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying (Microsoft.IdentityModel.Tokens.SecurityKey key, System.String algorithm) [0x00000] in C:\\agent2\\_work\\56\\s\\src\\Microsoft.IdentityModel.Tokens\\CryptoProviderFactory.cs:249 \n  at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.Byte[] encodedBytes, System.Byte[] signature, Microsoft.IdentityModel.Tokens.SecurityKey key, System.String algorithm, Microsoft.IdentityModel.Tokens.TokenValidationParameters validationParameters) [0x00012] in C:\\agent2\\_work\\56\\s\\src\\System.IdentityModel.Tokens.Jwt\\JwtSecurityTokenHandler.cs:824 \n  at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.String token, Microsoft.IdentityModel.Tokens.TokenValidationParameters validationParameters) [0x00233] in C:\\agent2\\_work\\56\\s\\src\\System.IdentityModel.Tokens.Jwt\\JwtSecurityTokenHandler.cs:943 \n'.\ntoken: '{\"alg\":\"RS256\",\"kid\":\"8ad1760832d419352845575d62a19a40\",\"typ\":\"JWT\"}.{\"nbf\":1543993466,\"exp\":1543993766,\"iss\":\"https://demo.identityserver.io\",\"aud\":\"native.hybrid\",\"nonce\":\"077cd0404eb18b4c9fd4dbe344a3a64c\",\"iat\":1543993466,\"c_hash\":\"1cOaEuJrk4JbFWaIl_0bvg\",\"sid\":\"70be7ea7ed2476a6157b40673765400c\",\"sub\":\"7dc004799c2a70216c18c989824820f9be50a84ff032f2b68d3d2c5f50e1539b\",\"auth_time\":1543993465,\"idp\":\"Google\",\"amr\":[\"external\"]}'.\n  at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.String token, Microsoft.IdentityModel.Tokens.TokenValidationParameters validationParameters) [0x002ff] in C:\\agent2\\_work\\56\\s\\src\\System.IdentityModel.Tokens.Jwt\\JwtSecurityTokenHandler.cs:966 \n  at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken (System.String token, Microsoft.IdentityModel.Tokens.TokenValidationParameters validationParameters, Microsoft.IdentityModel.Tokens.SecurityToken& validatedToken) [0x000d7] in C:\\agent2\\_work\\56\\s\\src\\System.IdentityModel.Tokens.Jwt\\JwtSecurityTokenHandler.cs:718 \n  at IdentityModel.OidcClient.IdentityTokenValidator.ValidateSignature (System.String identityToken, System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler handler, Microsoft.IdentityModel.Tokens.TokenValidationParameters parameters) [0x0013f] in C:\\local\\identity\\model\\OidcClient2\\src\\IdentityTokenValidator.cs:189 \n  at IdentityModel.OidcClient.IdentityTokenValidator+<ValidateAsync>d__4.MoveNext () [0x0019a] in C:\\local\\identity\\model\\OidcClient2\\src\\IdentityTokenValidator.cs:98 "

**VS Mac Details**
Visual Studio Enterprise 2017 for Mac
Version 7.6.11 (build 9)
Installation UUID: 7156b7c9-680b-4862-8b3d-2fa7165dda75
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.6
	2.1.5
	2.1.3
	2.1.1
	2.1.0
	2.0.5
	2.0.4
	2.0.0
	1.1.2
	1.1.1
	1.0.5
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.500/Sdks
SDK Versions:
	2.1.500
	2.1.403
	2.1.401
	2.1.301
	2.1.300
	2.1.4
	2.1.3
	2.0.2
	2.0.0
	1.0.4
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.0.0.0 (Visual Studio Enterprise)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

Xamarin.iOS
Version: 12.1.0.15 (Visual Studio Enterprise)
Hash: cbfb047a
Branch: xcode10.1
Build date: 2018-10-30 22:57:23-0400

Xamarin.Android
Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/dominick/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.1.2
SDK Platform Tools Version: 24.0.0
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

Operating System
Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

**Comment by GeoK** [comment]
@leastprivilege - Can you try out 5.3.1-preview-51205194400 from [the nightly feed](https://www.myget.org/feed/azureadwebstacknightly/package/nuget/System.IdentityModel.Tokens.Jwt/5.3.1-preview-51205194400) and let us know if you are still facing the issue?

**Comment by fileman** [comment]
Similar issue on Android/iOS too with 5.3.0, but work well with 5.2.4!

Windows 10 17763.134
VisualStudio.15.Release/15.9.3+28307.145
Xamarin   4.12.3.73 (d15-9@20b35b881)
Xamarin.Android SDK   9.1.0.38 (HEAD/61d16aa23)
Xamarin.iOS and Xamarin.Mac SDK   12.2.1.11 (5ef73d3)

I'm going to try nightly

**Comment by fileman** [comment]
@GeoK in my case nightly version work well in both platform, thanks

**Comment by GeoK** [comment]
@fileman - Great, thanks for trying it out!

**Comment by GeoK** [comment]
@leastprivilege - Could you please verify if 5.3.1-preview-51205194400, from [the nightly feed](https://www.myget.org/feed/azureadwebstacknightly/package/nuget/System.IdentityModel.Tokens.Jwt/5.3.1-preview-51205194400),  fixes the issue?

**Comment by eltonlika** [comment]
Could it be the same case as in this issue [#1037](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1037)? It was caused by a leading '0' byte in the modulus of the certificate's public key.

**Comment by leastprivilege** [comment]
I can try it next week.

**Comment by brentschmaltz** [comment]
@leastprivilege we are dropping 5.4.0 today and believe this has been fixed.
Please reopen if the issue still exists.

**Comment by PejmanNik** [comment]
It is work now 👍 
Thank you so much @brentschmaltz
