### ISSUE TITLE
MapInboundClaims condition inside constructor

### ISSUE THREAD

**Issue by NinoFloris** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1070]
How can this condition ever be hit now that it's not static anymore?

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/90ba8e281362191673c77b153639bd30cc390ae4/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L107

**Comment by brentschmaltz** [comment]
@NinoFloris we have been using a model of having a Default static, then an instance property.
In this case, when a new JwtSecurityTokenHandler is instantiated _mapInboundClaims has been set to DefaultMapInboundClaims.
If you set DefaultMapInboundClaims = false, then a new instance of JwtSecurityTokenHandler will be created with _mapInboundClaims = false.

**Comment by NinoFloris** [comment]
Clear, overlooked that line completely on github's code view, so silly oversight on my side.

Extra thanks to you for taking the time to reply.
