### ISSUE TITLE
How are you getting the strings stored in KeyingMaterial.cs?

### ISSUE THREAD

**Issue by iwaldman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1080]
for example, SelfSigned2048_SHA256 and SelfSigned2048_SHA256_Public

**Comment by GeoK** [comment]
Hi @iwaldman, KeyingMaterial.cs is a test utility class which contains reference data.

To get base64 encoded string from a certificate (e.g. _SelfSigned2048_SHA256_Public_ string from the [SelfSigned2048_SHA256.pfx](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/test/Certs/SelfSigned2048_SHA256.pfx) cert) you can use the following code:

```csharp            
X509Certificate2 cert = new X509Certificate2("SelfSigned2048_SHA256.pfx", "SelfSigned2048_SHA256");
string SelfSigned2048_SHA256_Public = Convert.ToBase64String(cert.Export(X509ContentType.Cert));
```

**Comment by iwaldman** [comment]
So you probably have a console app to do this.  Cool, thanks!
