### ISSUE TITLE
Exception in EnvelopedSignatureWriter when Signature element is first child of element

### ISSUE THREAD

**Issue by Tragedian** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1083]
In trying to create a SAML Federation Metadata document, there appears to be a bug/unsupported scenario in the `EnvelopedSignatureWriter` when the Signature element is the first child:

```
var credentials = new SigningCredentials(...);
var settings = new XmlWriterSettings
{
    Encoding = new UTF8Encoding(false)
};
var buffer = new MemoryStream();
var writer = new EnvelopedSignatureWriter(XmlWriter.Create(buffer, settings), credentials, "_id");

writer.WriteStartElement("EntityDescriptor", "urn:oasis:names:tc:SAML:2.0:metadata");

writer.WriteSignature();

writer.WriteEndElement();
```

When the writer tries to emit the signature after the root element is written, the following exception is thrown:

```
System.Xml.XmlException: Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 1, position 18.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Xml.XmlUTF8TextReader.VerifyNCName(String s)
   at System.Xml.XmlUTF8TextReader.ReadQualifiedName(PrefixHandle prefix, StringHandle localName)
   at System.Xml.XmlUTF8TextReader.ReadAttributes()
   at System.Xml.XmlUTF8TextReader.ReadStartElement()
   at System.Xml.XmlUTF8TextReader.Read()
   at System.Xml.XmlBaseReader.MoveToContent()
   at Microsoft.IdentityModel.Xml.EnvelopedSignatureWriter.OnEndRootElement() in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.Xml\EnvelopedSignatureWriter.cs:line 139
```

This appears to be because the inner writer is still positioned inside the unfinished start element when the `EnvelopedSignatureWriter` captures the signature position in its internal buffer.

I would expect the behaviour to be the same as calling `WriteStartElement`, `WriteElementString` or `WriteValue`, which will "finish" the started element before proceeding to start writing the next node as content of the element.

As a workaround, you can call `WriteComment` to finish the started element, but that does emit an unwanted comment before the signature.

**Comment by Tragedian** [comment]
A possible fix is to check the current write state, and if the state isn't within content, call `WriteWhitespace(" ")` on the `InnerWriter` to force it to transition to the content element, then manipulate the buffer to remove the single character that was added before taking the position of the signature.

It feels pretty hacky, but I haven't been able to find a clean way to trigger the `XmlWriter` to complete the element.

**Comment by brentschmaltz** [comment]
@Tragedian you are right in suspecting that our scenario was focused on Reading not Writing.
We will see when we can fit this in.

**Comment by Tragedian** [comment]
If you'd be interested, I'm open to submitting a pull request for this issue.

**Comment by brentschmaltz** [comment]
@Tragedian we just got back from the holidays.
PR's are always welcome.

**Comment by brentschmaltz** [comment]
Set to P1 to match the EnvelopedSignatureReader in this release would provide a nice round trip experience.

**Comment by GeoK** [comment]
Fixed with: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1195
