### ISSUE TITLE
JwtHeader default constructor doesn't set the Alg = None

### ISSUE THREAD

**Issue by CameronWills** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1092]
The default constructor for `JwtHeader`, which is called from `JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate` here:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/45dfc2866d1d9dca1c25a25b152d48e46348a52c/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L501

Does not set the `JwtHeader.Alg` value to "none", as is done when calling the other constructors on `JwtHeader`, such as this one:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/45dfc2866d1d9dca1c25a25b152d48e46348a52c/src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs#L85

I assume this is not intentional to leave alg blank? The missing `alg` in the header is causing issues with our OpenId connect server, returning a JWT that has an empty header.

**Comment by davesmith9088** [comment]
This is happening again with the latest version 6.7.1
