### ISSUE TITLE
 JwtSecurityTokenHandler should have safer defaults

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1097]
_From @DalSoft on Wednesday, 16 January 2019 16:38:54_

### Describe the bug
 JwtSecurityTokenHandler used by ASP.NET Core JwtBearerHandler has unsafe defaults.

DefaultTokenLifetimeInMinutes = 60
MaximumTokenSizeInBytes = 2097152 (~2.09MB)

### To Reproduce
New up JwtSecurityTokenHandler with defaults

### Expected behavior
I understand there is some inheritance going on here but for JwtSecurityTokenHandler  I would suggest:

DefaultTokenLifetimeInMinutes should have a safe default 5 minutes 
MaximumTokenSizeInBytes should have a safe default 250000

Or at least a warning in the documentation with some best practice guidelines.

_Copied from original issue: aspnet/AspNetCore#6745_

**Comment by brentschmaltz** [comment]
@Tratcher we will consider this for 5.4.1.
Thanks.

**Comment by mafurman** [comment]
Change DefaultTokenLifetimeInMinutes to 5 minutes and MaximumTokenSizeInBytes to 250000 (investigate if these are the appropriate defaults).

**Comment by GeoK** [comment]
Investigation results: Reduce MaximumTokenSizeInBytes to 256000, but keep 60 minutes as DefaultTokenLifetimeInMinutes.

**Comment by brockallen** [comment]
You guys recently made "none" the default signing algorithm. I can't for the internals of what's going on, but is that change in line with the motivation of this issue to make the defaults safer? None is not really safe.

**Comment by brentschmaltz** [comment]
@brockallen how is that. I know that some runtimes are attackable with 'none' in the header. Is that what you are referring to? If there is no algorithm, what would you suggest?

**Comment by brockallen** [comment]
> If there is no algorithm, what would you suggest?

As I said, I don't know the internals of how the JwtSecurityTokenHandler does its job. I'm just asking to make sure there's no issue here.

**Comment by brentschmaltz** [comment]
@brockallen our product has not seen any issues with 'alg=none'. As that is not an 'algorithm' we support. Other libraries have had issues with this and key type switching {tricking RSA keys from discovery to use users HMAC}. We haven't seen any issues with these two attacks.

However, anytime anyone is suspects any vulnerability, please let us know. It's our #1 priority.
