### ISSUE TITLE
ValidateSignature is not present in Microsoft.IdentityModel.Tokens/Validators.cs

### ISSUE THREAD

**Issue by mcetkovsky** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1099]
[Validating Tokens Wiki page](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/ValidatingTokens) states that [Microsoft.IdentityModel.Tokens/Validators.cs](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/Validators.cs) contains a `ValidateSignature` validator. However, the method does not seem to be present in the file.

**Comment by brentschmaltz** [comment]
@mcetkovsky we removed that text.
