### ISSUE TITLE
Saml2SecurityTokenHandler.ValidateAudience is never called

### ISSUE THREAD

**Issue by explunit** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1104]
`Saml2SecurityTokenHandler.ValidateAudience` is never called. Thus it's not possible to override this logic like it is with other `protected` methods in the same class, e.g. `ValidateIssuer`.

I am aware of the ability to provide an `TokenValidationParameters.AudienceValidator` delegate, but the class should be consistent across methods. For example, it's possible to provide an `IssuerValidator` **or** to override `ValidateIssuer`

**Comment by brentschmaltz** [comment]
@explunit it is a bit confusing, sorry for the this. We'll try and clean it up for 5.4.1.

We call Validators.ValidateAudience in ValidateConditions.
It may be better to the virtual ValidateAudience from ValidateToken, which would call
Validators.ValidateAudience.

We will put in the other fix where 'audience' is required.

**Comment by mafurman** [comment]
This should be fixed in the SamlSecurityTokenHandler as well.
