### ISSUE TITLE
Saml2SecurityTokenHandler.ValidateConditions does not check for missing audience

### ISSUE THREAD

**Issue by explunit** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1105]
`Saml2SecurityTokenHandler.ValidateConditions` simply iterates over the inbound `samlToken.Assertion.Conditions.AudienceRestrictions`. It does not check for the case where TokenValidationParameters.ValidateAudience is true but no AudienceRestrictions were found in the inbound token.

**Comment by explunit** [comment]
To ask it a different way: this was checked in the old codebase: https://github.com/Microsoft/referencesource/blob/60a4f8b853f60a424e36c7bf60f9b5b5f1973ed1/System.IdentityModel/System/IdentityModel/Tokens/SamlSecurityTokenHandler.cs#L939-L942

But not the new? Why?

**Comment by brentschmaltz** [comment]
@explunit we need to add this flag: enforceAudienceRestriction.
This should be similar to TokenValidationParameters.RequireSignedTokens

How about RequireAudience, default true.
