### ISSUE TITLE
Access Token is null when using Azure Bot for Skype for Business

### ISSUE THREAD

**Issue by jhallal** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1106]
I have implemented an azure chatbot which consume the Graph API to get logged user meetings through the chat dialog. The code is working well on iOS and Android. But when I integrated the bot with Skype for Business, I found out that the Access Token is always null or empty when trying to access it from the BootstrapConext: ClaimsPrincipal.Current.Identities.First().BootstrapContext
I need to get the access token for the chatbot from within Skype for Business in order to consuming the Graph API. Please advise how to solve this issue.

**Comment by GeoK** [comment]
Hi @jhallal, we totally missed this, sorry.
Are you still facing this issue?

From the limited context that you provided a possible solution could be to set _TokenValidationParameters.SaveSigninToken_ to **true**.

**Comment by jhallal** [comment]
> Hi @jhallal, we totally missed this, sorry.
> Are you still facing this issue?
> 
> From the limited context that you provided a possible solution could be to set _TokenValidationParameters.SaveSigninToken_ to **true**.

Hi GeoK, I will try it and get back to you. Thx

**Comment by GeoK** [comment]
Hi @jhallal, did you get a chance to try it?

**Comment by mafurman** [comment]
@jhallal Closing this, please reopen if you experience this issue again.
