### ISSUE TITLE
JwtSecurityTokenHandler can't be used with WsFederation middleware

### ISSUE THREAD

**Issue by explunit** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1107]
Looks like a regression of #18.

The 5.x version of JwtSecurityTokenHandler has only a `CanReadToken( string token )` and thus rejects things like `<wsse:BinarySecurityToken ValueType="urn:ietf:params:oauth:token-type:jwt"...` when used with the WsFederationMiddleware in Katana 4.0.

Previous version (when it lived in System.IdentityModel.Tokens.JwtSecurityTokenHandler) also had a `CanReadToken( XmlReader reader )`

**Comment by brentschmaltz** [comment]
@explunit Yes, we removed support in 5.x when we added support for WsFederation and SamlTokens. It seemed reasonable at the time as WsFed messages tend to use SamlTokens.

I modified the tile of this issue slightly to ask to add this feature back.

**Comment by MauroMS** [comment]
Oh wow, seems at this point that nothing is going to happen about this issue.

**Comment by solidstore** [comment]
This is causing a great deal of headaches in my project.

**Comment by brentschmaltz** [comment]
@solidstore @MauroMS we need to support read / write with XmlReader / XmlWriters.
Also we will need to define attached / unattached references.

We can get this in.

**Comment by brentschmaltz** [comment]
@solidstore @MauroMS this work is stacked behind a public release of 6.4.2 where we have made several changes that were used and tested inside microsoft.
Expect this work in an up-coming 6.4.2+ version.

**Comment by brentschmaltz** [comment]
This is will help users that want to use JWT's and WCF or other SOAP messaging.

**Comment by brentschmaltz** [comment]
@solidstore unfortunately we are unable to support this.
