### ISSUE TITLE
Base64UrlEncoder providing erroneous output for a case

### ISSUE THREAD

**Issue by livanov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1116]
When running

    Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode("\"a?")

the result is `ImE_` and this cannot be parsed by quite a number of base64 decoder I tried out there, except for the `Decode` method in the same class . My client is javascript and this is wrongly parsed to `"a` (`?` is missing).

The expected value is `ImE/` (https://en.wikipedia.org/wiki/Base64#Base64_table). I can see the comment on the [`Encode` method](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6e7a53e241e4566998d3bf365f03acd0da699a31/src/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.cs#L47-L49). 

Not sure, if this lib can create the `/` and `+` base64 encoding, so that older decoders can decode it?

**Comment by brentschmaltz** [comment]
@livanov totally missed this, sorry.
We will look into it.

**Comment by mafurman** [comment]
@livanov Base64Url encoding treats slashes as special characters and it's not backwardly compatible with Base64 encoding.
