### ISSUE TITLE
jwtHandler.ReadJwtToken still looking for NewtonSoft.json

### ISSUE THREAD

**Issue by pailyn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1118]
Hello,
I have an application using the jwtHandler application running .NET Framework 4.7.2
after updating my nuget package for NewtonSoft.JSON i started getting errors when trying to run.
`jwtHandler.ReadJwtToken()`

I started getting the following error:
```
IDX12729: Unable to decode the header '[PII is hidden]' as Base64Url encoded string. jwtEncodedString: '[PII is hidden]'. ---> System.TypeInitializationException: The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.Js
```

I updated my System.IdentityModel.Tokens.Jwt but i still get the same error.
I noticed in the latest commit, all references to NewtonSoft.Json was replaced with Microsoft.IdentityModel.Json, However when attempting to run
`JsonExtensions.DeserializeJwtHeader()` it attempts to initialize the deserializer. I can't help notice the deserializer uses `JsonConvert.DeserializeObject`. I know JsonConvert is a NewtonSoft.JSON method, but is there a Microsoft.IdentityModel.Json analogue? Also is there a Nuget package or reference for Microsoft.IdentityModel.Json? I can't seem to find it.

Paily

**Comment by brentschmaltz** [comment]
@pailyn at startup write: IdentityModelEventSource = true; to see full details of exception.
It looks like you are using IdentityModel 6.x, is that true?

The support for a Microsoft JSON parser is arriving in .NET Core 3.0.

**Comment by GeoK** [comment]
@pailyn Microsoft.IdentityModel.Json is internal and we haven't shipped 6x yet.
