### ISSUE TITLE
WSUtilityConstants wrong Namespace

### ISSUE THREAD

**Issue by 616b2f** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1119]
Hi,

I think this is an copy paste failure:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b152f463d910230859ec67705f11e51af4db4217/src/Microsoft.IdentityModel.Protocols.WsFederation/WsUtilityConstants.cs#L37

this should be Namespace should be "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" (see http://docs.oasis-open.org/ws-sx/ws-trust/200512/ws-trust-1.3-os.html)

Thanks @Mich-B to pointing that out. Reference IdentityServer/IdentityServer4.WsFederation#12

I will provide a PR with a fix for that.

**Comment by brentschmaltz** [comment]
@616b2f It looks like we made an error here.
Looks like we copied over the WS-Addressing class and didn't change the values.
In reviewing the WS-Addressing class, the comment refers to WS-Trust.
We will fix both.

We are running a bit behind on 5.4.1 release, but we should be able to get this in.

**Comment by 616b2f** [comment]
@brentschmaltz you are right didn't saw them. Should I also fix the comments from WS-Addressing in the same PR?

This would be awesome if it gets into 5.4.1 :)

**Comment by brentschmaltz** [comment]
@616b2f we have two branches we are working out of. dev5x is where we will ship 5.4.1 from. Our dev branch is for 6.0.

**Comment by 616b2f** [comment]
@616b2f so what should I do? Should I create a new PR for dev5x and close the #1120 or do you cherry pick from dev after it is merged? Could you guide me please :)

**Comment by brentschmaltz** [comment]
@616b2f I think cherry picking will be fine. You can leave the PR against dev.
Thanks again for your help.
