### ISSUE TITLE
Add information on how to include details in exceptions to Wiki and bug template

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1121]
Currently the user sees: '[PII is hidden]'.
We should add text something like: '[PII is hidden] at startup write: IdentityModelEventSource = true; to see full details'.

**Comment by henrik-me** [comment]
@mafurman 
Additional asks for the wiki extracted from [Azure DevOps](https://identitydivision.visualstudio.com/DevEx/_workitems/edit/357565)

IdentityModel logs contain PII this needs to be explained to developers so they can understand their responsibility for GDPR.

_This documentation will have these parts:_

- Comments in the library logging code

- Notes on the repo (wiki)

**Comment by mafurman** [comment]
@brentschmaltz What is meant here by "comments in the library logging code"? We do already have some comments related to PII filtering in IdentityModelEventSource.

**Comment by brentschmaltz** [comment]
@mafurman I want it to be obovious for users to know what to do to get more info. A link to our wiki [PII is hidden see: https://aks.ms/identitymodel/pii ]. On that page we will explain why we did what we did and how to show all details.
