### ISSUE TITLE
Error validating identity token : IDX10511

### ISSUE THREAD

**Issue by sylvainonweb** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1122]
When I try to validate the identity token using the following code on .NET Framework (4.6.1, 4.7.2), an exception is thrown. The same source code on .NET Core 1.0 is OK. Can you help me?

**Source code**
```
     private static void ValidateIdentityToken()
        {
            string identityToken = "????????????????????";

            var handler = new JwtSecurityTokenHandler();
            handler.InboundClaimTypeMap.Clear();

            TokenValidationParameters parameters = GetParameters();

            SecurityToken token;
            IdentityModelEventSource.ShowPII = true;
            var user = handler.ValidateToken(identityToken, parameters, out token);
        }

        private static TokenValidationParameters GetParameters()
        {
            var parameters = new TokenValidationParameters
            {
                ValidIssuer = "https://test-websso-gardian.edf.fr:443/gardianwebsso/oauth2/sesame",
                ValidAudience = "??????",
                ValidateIssuer = true,
                NameClaimType = JwtClaimTypes.Name,
                RoleClaimType = JwtClaimTypes.Role,
                ClockSkew = new TimeSpan(0, 5, 0)
            };

            // read keys from provider information
            var keys = new List<SecurityKey>();

            var keySet = GetKeySet();
            foreach (var webKey in keySet.Keys)
            {
                // todo: only supports RSA keys right now
                if (!string.IsNullOrWhiteSpace(webKey.E) && !string.IsNullOrWhiteSpace(webKey.N))
                {
                    // only add keys used for signatures
                    if (webKey.Use == "sig" || webKey.Use == null)
                    {
                        var e = Base64Url.Decode(webKey.E);
                        var n = Base64Url.Decode(webKey.N);

                        var key = new RsaSecurityKey(new RSAParameters { Exponent = e, Modulus = n });
                        key.KeyId = webKey.Kid;

                        keys.Add(key);
                    }
                }
            }

            parameters.IssuerSigningKeys = keys;

            return parameters;
        }

        private static JsonWebKeySet GetKeySet()
        {
            string certificateAsJson = "{\"keys\":[{\"kty\":\"RSA\",\"kid\":\"6g3X80imLE+Xet1NAeus9AnDSLg=\",\"use\":\"sig\",\"alg\":\"RS256\",\"n\":\"?????????????????????????????????\",\"e\":\"AQAB\"}]}";
            JsonWebKeySet keySet = new JsonWebKeySet(certificateAsJson);
            return keySet;
        }
```

**Exception**
```
IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: 6g3X80imLE+Xet1NAeus9AnDSLg=
'. 
kid: '6g3X80imLE+Xet1NAeus9AnDSLg='. 
Exceptions caught:
 ''.
token: '{"typ":"JWT","alg":"RS256","kid":"6g3X80imLE+Xet1NAeus9AnDSLg="}.{"tokenName":"id_token","azp":"????","sub":"????","scope":{"sub":"????","updated_at":"0"},"at_hash":"Ot4JxYeQKIplN4nULDiCuw","iss":"https://test-websso-gardian.edf.fr:443/gardianwebsso/oauth2/sesame","iat":1551708176,"auth_time":1551708176,"exp":1551744176,"tokenType":"JWTToken","nonce":"3c6e3070234c4b88186078c6ff5a2540","realm":"/sesame","aud":["????"],"amr":["sesame"],"c_hash":"Vhdwi-EK2KO2wEsJbspyDQ","ops":"4cdf1cdb-9354-4da0-ba21-5dfda7214c4d"}'.

```

**Comment by sylvainonweb** [comment]
This is the JwtSecurityTokenHandler.ValidateSignature method that returns true on .net core and false on .net framework.

**Comment by sylvainonweb** [comment]
**JwtSecurityTokenHandler**
On .net framework, ValidateSignature returns false 
On .net Core, ValidateSignature returns true 

```
if (ValidateSignature(encodedBytes, signatureBytes, key, jwtToken.Header.Alg, validationParameters))
{
	LogHelper.LogInformation(TokenLogMessages.IDX10242, token);
	jwtToken.SigningKey = key;
	return jwtToken;
}
```

**AsymetricAdapter**
On .net framework, VerifyFunction = VerifyWithRsaCryptoServiceProviderProxy which calls System.Security.Cryptography.RSACryptoServiceProvider.VerifyData
On .net Core, VerifyFunction = VerifyWithRsa

**Comment by sylvainonweb** [comment]
Please help !!!

**Comment by sylvainonweb** [comment]
Is there anybody?

**Comment by henrik-me** [comment]
@sylvainonweb : we will take a look and get back

**Comment by sylvainonweb** [comment]
Thanks because it"s really important for me. I'm unable to put application in production because of this point.

**Comment by GeoK** [comment]
@sylvainonweb - Which version of IdentityModel are you using?
Also, which IdentityModel target are you using when running your app, netstandard2.0 or net461?

**Comment by GeoK** [comment]
We made some fixes to the RsaCryptoServiceProviderProxy in v5.4.0.
Please try using the latest IdentityModel version with your repro and let us know the results.

**Comment by sylvainonweb** [comment]
I use 
* IdentityModel 3.10.6
* Microsoft.IdentityModel.Tokens 5.4.0
* NET Framework (4.5.2 / 4.6.1 / 4.7.2)
=> it crashes.

If I try the same source code in .NET Core 1.0, it's OK

**Comment by GeoK** [comment]
Two more questions:

1) Can you share the exception you are getting with the log message (_Exceptions caught:_)?
2) Can you check if the first byte of modulus of your key is zero?

**Comment by sylvainonweb** [comment]
1. The log :

Exception thrown: 'Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException' in System.IdentityModel.Tokens.Jwt.dll
An unhandled exception of type 'Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException' occurred in System.IdentityModel.Tokens.Jwt.dll
IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: 6g3X80imLE+Xet1NAeus9AnDSLg=
'. 
kid: '6g3X80imLE+Xet1NAeus9AnDSLg='. 
Exceptions caught:
 ''.
token: '{"typ":"JWT","alg":"RS256","kid":"6g3X80imLE+Xet1NAeus9AnDSLg="}.{"tokenName":"id_token","azp":"?","sub":"?","scope":{"sub":"?","updated_at":"0"},"at_hash":"fg5LmSZyg3OMrqKAQaIb9g","iss":"?","iat":1551780058,"auth_time":1551780058,"exp":1551816058,"tokenType":"JWTToken","nonce":"92a16c99eec6079b4657a1618dbc3e20","realm":"/sesame","aud":["?"],"amr":["sesame"],"c_hash":"HT0Lu3pCFmYroLk3-voAJw","ops":"2f64b124-6a8c-4678-80f7-b986d694a4c9"}'.


Exception non gérée : Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: 6g3X80imLE+Xet1NAeus9AnDSLg=
'. 
kid: '6g3X80imLE+Xet1NAeus9AnDSLg='. 
Exceptions caught:
 ''.
token: '{"typ":"JWT","alg":"RS256","kid":"6g3X80imLE+Xet1NAeus9AnDSLg="}.{"tokenName":"id_token","azp":"?","sub":"?","scope":{"sub":"?","updated_at":"0"},"at_hash":"fg5LmSZyg3OMrqKAQaIb9g","iss":"?","iat":1551780058,"auth_time":1551780058,"exp":1551816058,"tokenType":"JWTToken","nonce":"92a16c99eec6079b4657a1618dbc3e20","realm":"/sesame","aud":["?"],"amr":["sesame"],"c_hash":"HT0Lu3pCFmYroLk3-voAJw","ops":"2f64b124-6a8c-4678-80f7-b986d694a4c9"}'.
   à System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) dans D:\Tests\Open ID Connect\Enedis.Tests\Enedis.Tests_Microsoft.IdentityModel.Tokens\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:ligne 976
   à System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken) dans D:\Tests\Open ID Connect\Enedis.Tests\Enedis.Tests_Microsoft.IdentityModel.Tokens\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:ligne 722

2. Yes, the first byte of modulus of my key is 0

**Comment by GeoK** [comment]
The issue you are facing is caused by the null first byte.
This is contrary to the [JWA](https://tools.ietf.org/html/rfc7518#section-6.3.1.1).

.NET Core will account for the null byte and .NET framework, apparently, won't.

Try following [this workaround](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/877#issuecomment-431113178) and let us know the results.

**Comment by sylvainonweb** [comment]
YES, now that works. Great job.
Thanks

**Comment by huismansander** [comment]
> The issue you are facing is caused by the null first byte.
> This is contrary to the [JWA](https://tools.ietf.org/html/rfc7518#section-6.3.1.1).
> 
> .NET Core will account for the null byte and .NET framework, apparently, won't.
> 
> Try following [this workaround](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/877#issuecomment-431113178) and let us know the results.

I had to refine this workround as follows in case of validating the token with a VmWare IDPVMware Workspace ONE Access v20.01:

if (modulus.Length == 129 && modulus[0] == 0)
{
            // Prevent Modules in the security key from starting with value 0
            var newModulus = new byte[128];
            Array.Copy(modulus, 1, newModulus, 0, 128);
            webKey.N = Base64UrlEncoder.Encode(newModulus);

            return new RsaSecurityKey(new RSAParameters { Exponent = exponent, Modulus = newModulus })
            {
                KeyId = webKey.Kid
            };
}
