### ISSUE TITLE
Cannot parse JwtSecurityToken with detached content

### ISSUE THREAD

**Issue by luber** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1123]
According to RFC 7515, Appendix F:
Sometimes it is useful to create JWS with Detached Content. This can be achieved by replacing the payload part of JWS with an empty string. So resulting JWS will look like 
**header**..**signature**

But when I try to create an instance of JwtSecurityToken class with such JWS an Exception is thrown b/c 
`private void DecodeJws(string[] tokenParts)` doesn't take into account the possibility of having payload part as an empty string. Probably it can be fixed as:
`if (string.IsNullOrEmpty(tokenParts[1]))
{
  Payload = new JwtPayload();
} else {
  Payload = JwtPayload.Base64UrlDeserialize(tokenParts[1]);
}`

**Comment by brentschmaltz** [comment]
@luber I agree with you that we don't support this.
If we were to put in support, it would be in the JsonWebToken.

**Comment by brentschmaltz** [comment]
@luber we are closing as the JsonWebTokenHandler should allow this.
Please reopen if this fails.
