### ISSUE TITLE
OpenIdConnectConfiguration doesn't map id_token_signing_alg_values_supported collection

### ISSUE THREAD

**Issue by underscoreHao** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1124]
Hi,

I've been using the ConfigurationManager to get and map data from a discovery endpoint to an OpenIdConnectConfiguration object. I use fields like **TokenEndpoint**, **AuthorizationEndpoint** and **Issuer**. They map correctly every time. However the **IdTokenSigningAlgValuesSupported** which should map from **id_token_signing_alg_values_supported** is always returning an empty collection.

I think there's something wrong in the JSON deserializer settings you employ in [OpenIdConfigurationRetreiver.cs:92](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b0867057c1b98ead823eed37869b5656ed2ba695/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs#L92).

I'm confident that the data I get from the discovery endpoint is valid for the **id_token_signing_alg_values_supported** field.

Here's a small test using this piece of code

I used this JSON to illustrate:
```json
{
    "issuer":"http://acmepaymentscorp",
    "authorization_endpoint":"http://acmepaymentscorp/oauth/auz/authorize",
    "token_endpoint":"http://acmepaymentscorp/oauth/oauth20/token",
    "userinfo_endpoint":"http://acmepaymentscorp/oauth/userinfo",
    "jwks_uri":"http://acmepaymentscorp/oauth/jwks",
    "scopes_supported":[
        "READ",
        "WRITE",
        "DELETE",
        "openid",
        "scope",
        "profile",
        "email",
        "address",
        "phone"
    ],
    "response_types_supported":[
        "code",
        "code id_token",
        "code token",
        "code id_token token",
        "token",
        "id_token",
        "id_token token"
    ],
    "grant_types_supported":[
        "authorization_code",
        "implicit",
        "password",
        "client_credentials",
        "urn:ietf:params:oauth:grant-type:jwt-bearer"
    ],
    "subject_types_supported":[
        "public"
    ],
    "id_token_signing_alg_values_supported":[
        "HS256",
        "HS384",
        "HS512",
        "RS256",
        "RS384",
        "RS512",
        "ES256",
        "ES384",
        "ES512",
        "PS256",
        "PS384",
        "PS512"
    ],
    "id_token_encryption_alg_values_supported":[
        "RSA1_5",
        "RSA-OAEP",
        "RSA-OAEP-256",
        "A128KW",
        "A192KW",
        "A256KW",
        "A128GCMKW",
        "A192GCMKW",
        "A256GCMKW",
        "dir"
    ],
    "id_token_encryption_enc_values_supported":[
        "A128CBC-HS256",
        "A192CBC-HS384",
        "A256CBC-HS512",
        "A128GCM",
        "A192GCM",
        "A256GCM"
    ],
    "token_endpoint_auth_methods_supported":[
        "client_secret_post",
        "client_secret_basic",
        "client_secret_jwt",
        "private_key_jwt"
    ],
    "token_endpoint_auth_signing_alg_values_supported":[
        "HS256",
        "RS256"
    ],
    "claims_parameter_supported":false,
    "request_parameter_supported":false,
    "request_uri_parameter_supported":false
}
```

And the code:

```csharp
    string json = "{\r\n  \"issuer\":\"http://acmepaymentscorp\",\r\n  \"authorization_endpoint\":\"http://acmepaymentscorp/oauth/auz/authorize\",\r\n  \"token_endpoint\":\"http://acmepaymentscorp/oauth/oauth20/token\",\r\n  \"userinfo_endpoint\":\"http://acmepaymentscorp/oauth/userinfo\",\r\n  \"jwks_uri\":\"http://acmepaymentscorp/oauth/jwks\",\r\n  \"scopes_supported\":[\r\n    \"READ\",\r\n    \"WRITE\",\r\n    \"DELETE\",\r\n    \"openid\",\r\n    \"scope\",\r\n    \"profile\",\r\n    \"email\",\r\n    \"address\",\r\n    \"phone\"\r\n  ],\r\n  \"response_types_supported\":[\r\n    \"code\",\r\n    \"code id_token\",\r\n    \"code token\",\r\n    \"code id_token token\",\r\n    \"token\",\r\n    \"id_token\",\r\n    \"id_token token\"\r\n  ],\r\n  \"grant_types_supported\":[\r\n    \"authorization_code\",\r\n    \"implicit\",\r\n    \"password\",\r\n    \"client_credentials\",\r\n    \"urn:ietf:params:oauth:grant-type:jwt-bearer\"\r\n  ],\r\n  \"subject_types_supported\":[\r\n    \"public\"\r\n  ],\r\n  \"id_token_signing_alg_values_supported\":[\r\n    \"HS256\",\r\n    \"HS384\",\r\n    \"HS512\",\r\n    \"RS256\",\r\n    \"RS384\",\r\n    \"RS512\",\r\n    \"ES256\",\r\n    \"ES384\",\r\n    \"ES512\",\r\n    \"PS256\",\r\n    \"PS384\",\r\n    \"PS512\"\r\n  ],\r\n  \"id_token_encryption_alg_values_supported\":[\r\n    \"RSA1_5\",\r\n    \"RSA-OAEP\",\r\n    \"RSA-OAEP-256\",\r\n    \"A128KW\",\r\n    \"A192KW\",\r\n    \"A256KW\",\r\n    \"A128GCMKW\",\r\n    \"A192GCMKW\",\r\n    \"A256GCMKW\",\r\n    \"dir\"\r\n  ],\r\n  \"id_token_encryption_enc_values_supported\":[\r\n    \"A128CBC-HS256\",\r\n    \"A192CBC-HS384\",\r\n    \"A256CBC-HS512\",\r\n    \"A128GCM\",\r\n    \"A192GCM\",\r\n    \"A256GCM\"\r\n  ],\r\n  \"token_endpoint_auth_methods_supported\":[\r\n    \"client_secret_post\",\r\n    \"client_secret_basic\",\r\n    \"client_secret_jwt\",\r\n    \"private_key_jwt\"\r\n  ],\r\n  \"token_endpoint_auth_signing_alg_values_supported\":[\r\n    \"HS256\",\r\n    \"RS256\"\r\n  ],\r\n  \"claims_parameter_supported\":false,\r\n  \"request_parameter_supported\":false,\r\n  \"request_uri_parameter_supported\":false\r\n}";
    
    // My actual use case uses the ConfigurationManager, but for simplicity I'm calling the constructor of OpenIdConnectConfiguration here
    OpenIdConnectConfiguration openIdConfig = new OpenIdConnectConfiguration(json)
```

And the **openIdConfig** is the following:

![image](https://user-images.githubusercontent.com/5088351/54283160-5a5d0500-4595-11e9-8258-cac4b115e7b4.png)

As you can see the collections are empty. Some clarification on this will be appreciated.

Thanks!

**Comment by brentschmaltz** [comment]
@underscoreHao can you remove the \r\n.
Our test: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/7c7c7e13968e6656e67eb43938d4da136336049c/test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectConfigurationTests.cs#L50 

Data is here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/7c7c7e13968e6656e67eb43938d4da136336049c/test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConfigData.cs#L84

**Comment by underscoreHao** [comment]
@brentschmaltz I've modified my JSON, but the result is the same.

```csharp
string json = @"{""issuer"":""http://acmepaymentscorp"",""authorization_endpoint"":""http://acmepaymentscorp/oauth/auz/authorize"",""token_endpoint"":""http://acmepaymentscorp/oauth/oauth20/token"",""userinfo_endpoint"":""http://acmepaymentscorp/oauth/userinfo"",""jwks_uri"":""http://acmepaymentscorp/oauth/jwks"",""scopes_supported"":[""READ"",""WRITE"",""DELETE"",""openid"",""scope"",""profile"",""email"",""address"",""phone""],""response_types_supported"":[""code"",""code id_token"",""code token"",""code id_token token"",""token"",""id_token"",""id_token token""],""grant_types_supported"":[""authorization_code"",""implicit"",""password"",""client_credentials"",""urn:ietf:params:oauth:grant-type:jwt-bearer""],""subject_types_supported"":[""public""],""id_token_signing_alg_values_supported"":[""HS256"",""HS384"",""HS512"",""RS256"",""RS384"",""RS512"",""ES256"",""ES384"",""ES512"",""PS256"",""PS384"",""PS512""],""id_token_encryption_alg_values_supported"":[""RSA1_5"",""RSA-OAEP"",""RSA-OAEP-256"",""A128KW"",""A192KW"",""A256KW"",""A128GCMKW"",""A192GCMKW"",""A256GCMKW"",""dir""],""id_token_encryption_enc_values_supported"":[""A128CBC-HS256"",""A192CBC-HS384"",""A256CBC-HS512"",""A128GCM"",""A192GCM"",""A256GCM""],""token_endpoint_auth_methods_supported"":[""client_secret_post"",""client_secret_basic"",""client_secret_jwt"",""private_key_jwt""],""token_endpoint_auth_signing_alg_values_supported"":[""HS256"",""RS256""],""claims_parameter_supported"":false,""request_parameter_supported"":false,""request_uri_parameter_supported"":false}";
```

**Comment by brentschmaltz** [comment]
@underscoreHao I tested out your json in our dev branch, which is our 6.x version.
Seems to work fine there.
To help understand what is going on here.
What version of IdentityModel are you using?
Are you including Newtonsoft as a package reference, if so what version?

**Comment by underscoreHao** [comment]
@brentschmaltz I'm using 5.4.0 for both **Microsoft.IdentityModel.Tokens** and **System.IdentityModel.Tokens.Jwt**, 10.0.1 for **Newtonsoft.Json**

**Comment by brentschmaltz** [comment]
@underscoreHao can you send me the source you are using. I can't seem to repo your issue.

**Comment by mafurman** [comment]
@underscoreHao If this is still a problem please attach the code you're using.

**Comment by adeshtc** [comment]
HI Guys,

When i use ConfigManager.GetConfigurationAsync().Result by passing the metdataUrl i will be getting the securityTokens
But when i using the OpenIdConnectConfiguration(string json) by passing metadatstring then the securitytokens count will be 0.

i dont want want to use metdata url. 

Please help me . Thanks in advance

(https://user-images.githubusercontent.com/10420328/80786047-039efa00-8ba0-11ea-849e-3c519749c948.PNG)

**Comment by brentschmaltz** [comment]
@adeshtc when [OpenIdConnectConfigurationRetriever.GetAsync](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/bd742d4d4730cfab4905e3a77fc6539965b54839/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs#L79) called from [ConfigurationManager.GetConfigurationAsync](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/bd742d4d4730cfab4905e3a77fc6539965b54839/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs#L79) calls out to the JwksUri endpoint to obtain the keys. When you use this constructor [OpenIdConnectConfiguration(string json)](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/bd742d4d4730cfab4905e3a77fc6539965b54839/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs#L51) that call is not made.

If you have json representing the keys you can use this constructor [JsonWebKeySet(string json)](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/bd742d4d4730cfab4905e3a77fc6539965b54839/src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs#L71) then set the property [OpenIdConnectConfiguration.JsonWebKeySet](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/bd742d4d4730cfab4905e3a77fc6539965b54839/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs#L220) after constructing OpenIdConnectConfiguration.
