### ISSUE TITLE
Support for encrypting existing JWTs

### ISSUE THREAD

**Issue by scottbrady91** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1130]
When using JWE identity tokens in OpenID Connect and calling the end session endpoint with an `id_token_hint`, the spec suggests re-encrypting the inner JWS identity token using the OpenID Provider's encryption key.

Is there a way to encrypt an existing JWT using the current APIs? If not, can one be added?

**Comment by brentschmaltz** [comment]
@scottbrady91 are you asking for given a JWS, translate that to a JWE?

**Comment by scottbrady91** [comment]
Yes, exactly that

**Comment by brentschmaltz** [comment]
@scottbrady91 ok, i think that is a good feature. We will make that into our next release.
5.4.1 had to be put on hold for a few weeks. We are able to make some progress now.

**Comment by scottbrady91** [comment]
Awesome. Thanks, all!
