### ISSUE TITLE
Accessing custom claims in JwtSecurityToken 

### ISSUE THREAD

**Issue by AdamUCF** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1131]
I'm using the OpenID Connect middleware and attempting to access custom claims sent by my Authorization Server, namely the scope claim. How can I retrieve the value of custom claims? It seems only the predefined claims are available. Would I need to get the raw token and parse it myself or is there some other way to access them?

**Comment by GeoK** [comment]
Hi @AdamUCF - Can you share your startup code?

**Comment by AdamUCF** [comment]
Here's what the JWT looks like just to help clarify.
`
{
  "scope": [
    "openid",
    "profile",
    "email"
  ],
  "client_id": "my_client_id",
  "credential_authenticator": "my authenticator",
  "aud": "my_client_id",
  "credential_strength": "20",
  "iss": "https://my.auth.server.internal",
  "location_of_authentication": "INTERNAL",
  "exp": 1554858653
}
`

And here's what's in my Startup.cs. I've tried accessing the scope claim (and others) in the OnTokenValidated event but they're not there. The best idea I can come up with would be to re-decode the raw token and parse the json that way.

`
 public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            // Load the Federation configuration section from app settings
            var federationConfig = Configuration.GetSection("Federation");

            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddCookie(options =>
            {
                options.ExpireTimeSpan = TimeSpan.FromHours(2); //default is 14days
                options.SlidingExpiration = true; // default
                options.AccessDeniedPath = "/Error/403"; // set a custom error access denied error page. this would need to be created/handled in your app.

            })
            .AddOpenIdConnect(options =>
            {
                options.Authority = federationConfig["Authority"]; // get the url for the federation environment to use for authentication
                options.ClientId = federationConfig["ClientId"]; // the client id for this application
                options.ClientSecret = federationConfig["ClientSecret"]; // the client secret created for this application
                options.GetClaimsFromUserInfoEndpoint = true; // have the application get additional claims from the user info endpoint when the user logs in
                options.Scope.Add("email"); // request the user's email address
                options.Scope.Add("profile"); // request the user's basic profile attributes

                options.ClaimActions.MapJsonKey("scope", "scope");

                options.ResponseType = OpenIdConnectResponseType.Code; // request the code response type from Federation

                options.TokenValidationParameters = new TokenValidationParameters() { NameClaimType = ClaimTypes.NameIdentifier }; // set the sub to be the primary name in the identity

                //optional customizations to the auth and failure events
                options.Events = new OpenIdConnectEvents()
                {
                    
                    OnRemoteFailure = context =>
                    {
                        // handle an error response from Federation and redirect the user to a custom error page instead
                        context.Response.Redirect("/Error/401");
                        context.HandleResponse();
                        return Task.CompletedTask;
                    },
                    OnTokenValidated = context =>
                    {
                        var claims = context.SecurityToken.Claims;
                        return Task.CompletedTask;
                    }

                };

            });



            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseAuthentication();
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseMvc(routes =>
            {
                routes.MapRoute("Error", "Error/{id?}",
                    defaults: new { controller = "Error", action = "Index" });
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
`

**Comment by brentschmaltz** [comment]
@AdamUCF you shouldn't have to recode anything. At the application layer, does the 'User' have multiple 'scope' claims?

**Comment by GeoK** [comment]
Where would you get the "raw token" from? I initially suspected that you were missing: 
`options.ClaimActions.MapJsonKey("scope", "scope");`, but that's clearly not the case.

**Comment by AdamUCF** [comment]
@brentschmaltz nope. It only has the claims from the userinfo endpoint -- not the claims from the access token. 

@GeoK I thought context.SecurityToken.RawData would have it but even that appears to be the processed version that removes the unknown claim types (and not the... raw data). context.TokenEndpointResponse.AccessToken does have the actual JWT though.

**Comment by GeoK** [comment]
@AdamUCF  `context.SecurityToken` that you are seeing is an Id Token, and the same goes for the claims.

**Comment by AdamUCF** [comment]
@GeoK that makes sense but is there any way to populate the User claims with the values in the access token?

**Comment by brentschmaltz** [comment]
@Tratcher how do claims from the UserInfoEndpoint get merged into the User? see @AdamUCF startup code above.

`options.GetClaimsFromUserInfoEndpoint = true;`

**Comment by AdamUCF** [comment]
The claims in the UserInfo endpoint are getting merged into the User but the claims in the access token are not.

**Comment by brentschmaltz** [comment]
@AdamUCF I see, the code flow does not add claims to the identity. This makes sense as OIDC is about identity. The access_token is presented to a resource server and in this case it appears the access_token presented to the userinfo_endpoint.

I think your original assumption that you will have to add them yourself is correct.

**Comment by brentschmaltz** [comment]
@AdamUCF closing this. It would be up to asp.net to take a work items here.
You will need to save the token and add the claims.
