### ISSUE TITLE
JwtSecurityTokenHandler.ValidateToken is failing with IDX10511; exception message needs to be improved

### ISSUE THREAD

**Issue by shitada** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1132]
JwtSecurityTokenHandler.ValidateToken is failed as IDX10511 even though Graph API call is succeeded by using the token.
But the validation of the token of Azure AD Graph is succeeded. 
Are there any improvements in code to resolve the problem? Or does the problem relies on Azure AD side?

using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Protocols;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ValidateToken
{
    class Program
    {
        static void Main(string[] args)
        {
            //aquire token
            var tenantId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
            var clientId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
            var clientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            var aadInstance = "https://login.microsoftonline.com/";
            var graphResourceID = "https://graph.microsoft.com";
            //var graphResourceID = "https://graph.windows.net";

            UserCredential userCredential = new UserCredential("xxxxx@xxxxx.onmicrosoft.com");
            UserIdentifier userIdentifier = new UserIdentifier("xxxxx@xxxxx.onmicrosoft.com", UserIdentifierType.RequiredDisplayableId);
            ClientCredential clientcred = new ClientCredential(clientId, clientSecret);
            AuthenticationContext authenticationContext = new AuthenticationContext(aadInstance + tenantId);
            AuthenticationResult authenticationResult = authenticationContext.AcquireTokenAsync(graphResourceID, clientId, new Uri("http://localhost"), new PlatformParameters(PromptBehavior.Always)).Result;

            Console.WriteLine(authenticationResult.AccessToken);

            //call Graph API, the request is succeeded.
            using (var client = new HttpClient())
            {
                var url = "https://graph.microsoft.com/v1.0/me";
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + authenticationResult.AccessToken);
                var response = client.GetStringAsync(url).Result;
                JObject json = JObject.Parse(response);

                Console.WriteLine(json);
            }

            //call Azure AD Graph API, I can get correct data without errors.
            //using (var client = new HttpClient())
            //{
            //    var url = "https://graph.windows.net/xxxxxxx.onmicrosoft.com/users?api-version=1.6";
            //    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + authenticationResult.AccessToken);
            //    var response = client.GetStringAsync(url).Result;
            //    JObject json = JObject.Parse(response);

            //    Console.WriteLine(json);
            //}

            //valid token
            IdentityModelEventSource.ShowPII = true;
            var tokenString = authenticationResult.AccessToken;

            var configRetriever = new OpenIdConnectConfigurationRetriever();
            var docRetriever = new HttpDocumentRetriever();
            var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>("https://login.microsoftonline.com/xxxxxx.onmicrosoft.com/.well-known/openid-configuration", configRetriever, docRetriever)
            {
                AutomaticRefreshInterval = TimeSpan.FromHours(1),
                RefreshInterval = TimeSpan.FromMinutes(5)
            };

            var config = configurationManager.GetConfigurationAsync().Result;

            var validationParameters = new TokenValidationParameters();
            validationParameters.ValidateIssuer = false;
            validationParameters.IssuerSigningKeys = config.SigningKeys;
            validationParameters.ValidAudience = "https://graph.microsoft.com";
            //validationParameters.ValidAudience = "https://graph.windows.net"; //Validation is succeeded when using https://graph.windows.net.

            var tokenHandler = new JwtSecurityTokenHandler();
            var result = tokenHandler.ValidateToken(tokenString, validationParameters, out var token); // invalid excetion occurs when using https://graph.microsoft.com.

            Console.WriteLine(result);
        }
    }
}

Package version is here.
![image](https://user-images.githubusercontent.com/32670892/56198010-01d9c580-6075-11e9-87dd-fc04b59fa8c1.png)

**Comment by GeoK** [comment]
Hi @shitada - `SecurityTokenInvalidSignatureException (IDX10511)` can happen if the first byte of modulus of your key is zero. Can you check if that's the case?


https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1122#issuecomment-475805665
[wiki](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/SecurityTokenInvalidSignatureException:-IDX10511)

**Comment by brentschmaltz** [comment]
@shitada i suspect that your token is in a format that needs to be transformed before signature validation will succeed.

see: https://stackoverflow.com/questions/55247157/unable-to-validate-access-token-signature-obtained-from-azure-ad-in-order-to-sec

**Comment by shitada** [comment]
Hi, @GeoK thanks for workaround. But unfortunately the workaround doesn't work.

            IdentityModelEventSource.ShowPII = true;
            var tokenString = authenticationResult.AccessToken;

            var configRetriever = new OpenIdConnectConfigurationRetriever();
            var docRetriever = new HttpDocumentRetriever();
            var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>("https://login.microsoftonline.com/xxxxxxx.onmicrosoft.com/.well-known/openid-configuration", configRetriever, docRetriever)
            {
                AutomaticRefreshInterval = TimeSpan.FromHours(1),
                RefreshInterval = TimeSpan.FromMinutes(5)
            };

            var config = configurationManager.GetConfigurationAsync().Result;

            var N = "ALq7LDOgZRirsfc308DI_hSwSRZsYpPhiD69WyA65s-wRpG276x5SoWeyMOZJMi4qz2CG6K51_mHov0ZFmdN3sXARQPOgvepwQ1hY2OPRVmWzitdAP3b_UDuJR_rBIsSXVjnaDOdF_y9vefmVWanDh3Aef5Dk_0TzPexMod_WbEgcnibIgg4aZMSUeFsAViYkYSfgXrF16nZm2A3QJTbSuFTGpr9VPVLdD7mRvBgNXhm117OTg5OIBzRUnLrKlcqIg41uPdFHxNCJI3ukfyw9hvoHb1qCdAO3I9L66ZXdXTjY6uhoqgP_OGo6ze3BpQtIcECInNU7qkNd8CJ_MMRqgE";
            var modulus = Base64UrlEncoder.DecodeBytes(N);
            if (modulus.Length == 257 && modulus[0] == 0)
            {
                var newModulus = new byte[256];
                Array.Copy(modulus, 1, newModulus, 0, 256);
                N = Base64UrlEncoder.Encode(newModulus);
            }

            var jsonWebKey = new JsonWebKey
            {
                KeyId = "xneUh4tPkUPsVH/okK+VMrXirVA=",
                Kid = "xneUh4tPkUPsVH/okK+VMrXirVA=",
                N = N,
                Alg = "RS256",
                E = "AQAB",
                Kty = "RSA",
                Use = "sig"
            };

            var validationParameters = new TokenValidationParameters {
                IssuerSigningKey = jsonWebKey,
                RequireExpirationTime = false,
                ValidateLifetime = false,
                ValidateAudience = false,
                ValidateIssuer = false,
                ValidAudience = "https://graph.microsoft.com"
            };
           
            //validationParameters.ValidAudience = "https://graph.windows.net"; //Validation is succeeded when using https://graph.windows.net.

            var tokenHandler = new JwtSecurityTokenHandler();
            var result = tokenHandler.ValidateToken(tokenString, validationParameters, out var token); // invalid excetion occurs when using https://graph.microsoft.com.


The error message changed a little bit here.

 Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: 'IDX10501: Signature validation failed. Unable to match keys: 
kid: 'HBxl9mAe6gxavCkcoOU2THsDNa0', 
token: '{"typ":"JWT","nonce":"AQABAAAAAADCoMpjJXrxTq9VG9te-7FXx3H8MejywK30fxxyn1RzJRbpTTVjG9z2r3X1_0iFTgshyuL2JqXpUkVt8eg21VhR0ESiudNWfQat4tI1Dfp49SAA","alg":"RS256","x5t":"HBxl9mAe6gxavCkcoOU2THsDNa0","kid":"HBxl9mAe6gxavCkcoOU2THsDNa0"}.


@brentschmaltz 
Thanks,
I'll try to use ADALv2 to get token. But I think token generated by ADALv1 should be validated.

**Comment by akartynnik** [comment]
I have the same issue in .net core api

**Comment by brentschmaltz** [comment]
@shitada @akartynnik it looks like we have a slight logic in our reporting when failing that is throwing us off. For some reason we were unable to match the key, don't know why. We then don't add the exception string to the exception thrown so we are probably hitting invalid signature. But it is hidden.

Notice above the kid in the JsonWebKey is "xneUh4tPkUPsVH/okK+VMrXirVA=". This will not match and you will hit the regression case where we try all keys.

The token has been crafted for graph and needs special processing to validate the signature.

**Comment by brentschmaltz** [comment]
@akartynnik I will fix the exception message.
