### ISSUE TITLE
Fix dependency graph for netstandard 2.0 

### ISSUE THREAD

**Issue by davidfowl** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1134]
The .NET Standard 2.0 packages bring in way too many dependencies. One of the purposes of NS 2.0 was to reduce the needed packages to avoid the granular dependencies by building more functionality into the core. While these packages added support for the ns2.0 target framework, they've kept the same dependencies resulting in a large download when installing the packages here.

For e.g. When I install the newest version of **System.IdentityModel.Tokens.Jwt**, it shows me these dependencies:

![image](https://user-images.githubusercontent.com/95136/56491102-377b1600-649c-11e9-9d6a-615c300230ef.png)

If you'd like I can send a PR to trim out these dependencies.

cc @brentschmaltz

**Comment by brentschmaltz** [comment]
@davidfowl thanks, we will get on it and get it into 5.4.1.
If you have a PR that would be nice :-)

**Comment by GeoK** [comment]
@davidfowl Thank you for adding this, we merged in your PR.

**Comment by davidfowl** [comment]
Let me know when you have a package on myget that I can use to verify the changes end to end.

**Comment by damieng** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1138
