### ISSUE TITLE
Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by SaeidSabzalizadeh** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1135]
Adding System.IdentityModel.Tokens.Jwt (5.4.0) nuget package in .NetStandard 2.0 class library project. Referencing this class library in ASP.NET API .NETFramework 4.7.2 I got an error:

`Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
`
I have to mention no problem in ASP.NET Core API, I just got the error in .NETFramework API.
 And the code throw the error:

```
public ClaimsPrincipal ValidateSignedToken(string rawJwtToken)
{
    var validationParameters = GetTokenValidationParameters();
    var securityTokenHandler = new JwtSecurityTokenHandler();

    var claimPrincipal = securityTokenHandler.ValidateToken(rawJwtToken, validationParameters, out _);
    return claimPrincipal;
}
```

**Comment by SaeidSabzalizadeh** [comment]
I add <TargetFrameworks>netstandard2.0;net461</TargetFrameworks> in the csproj file. and solved

**Comment by quasarea** [comment]
This is not a proper fix, took me some time to track it down.

Proper will be to adjust/expand project nuspect to cover 4.7 dependencies
