### ISSUE TITLE
Make the public JwtHeader default constructor internal

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1144]
The 'alg' (algorithm) header parameter must be present (according to the [JWS RFC](https://tools.ietf.org/html/rfc7515#section-4.1.1)), so we should not allow an empty JwtHeader object to be created.

However, this constructor should not be completely removed as it needs to be available for use by JsonConvert.DeserializeObject.

This is basically the same as issue #1092, which we are planning on addressing for the 5.5.0 release. However, as removing a constructor is a breaking change, the 5.5.0 fix will need to address this problem differently.

**Comment by brentschmaltz** [comment]
@henrik-me this would be a breaking change, no real good reason to do it.
