### ISSUE TITLE
JwtSecurityToken DateTime

### ISSUE THREAD

**Issue by khteh** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1149]
Does the constructor expect paramater of type DateTime to be local time or UTC? I use UTC but it still does the conversion *again* and result in the JWT always expires!!!

**Comment by brentschmaltz** [comment]
@khteh can you share your code.
The payload shows we convert to UTC.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/72f03a9c62215688b759ea180263db8b498280ea/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L105

**Comment by khteh** [comment]
Why convert again when the input parameter is already in UTC?

**Comment by khteh** [comment]
Why not use DateTimeOffset instead?

**Comment by brentschmaltz** [comment]
@khteh ToUniversalTime is a no-op if Kind is Utc.
We started with DateTime and have it in multiple api's.

**Comment by khteh** [comment]
My application uses DateTimeOffset and I assign the DateTime property of the variable which has Unspecified Kind. Switch to UtcDateTime and it works now.
