### ISSUE TITLE
JsonWebKey representing X509 certificate has a KeySize of 0

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1150]
...which throws when trying to validate a signature.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/72f03a9c62215688b759ea180263db8b498280ea/src/Microsoft.IdentityModel.Tokens/JsonWebKey.cs#L254-L267

any workaround for that?

**Comment by brentschmaltz** [comment]
@leastprivilege not without writing some code. 
Is this affecting existing customers?
Or can you wait till 5.5.0?

**Comment by brockallen** [comment]
Yes, we can wait. Thanks.

**Comment by brentschmaltz** [comment]
@leastprivilege @brockallen I am assuming the fault is in the AsymmetricSignatureProvider. I believe a solution would be to check the key size after a SecurityKey is created from the the JsonWebKey.

**Comment by leastprivilege** [comment]
OK - then please fix it ;)

**Comment by brentschmaltz** [comment]
@leastprivilege I am curious how are you creating these keys?

**Comment by leastprivilege** [comment]
IIRC I was using JsonWebKeyConverter

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1206
