### ISSUE TITLE
Provide partitioning for TokenValidationParameters.PropertyBag

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1152]
There should be a way of determining which properties where set by us (to avoid potential collisions). 

Related issue: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1030

**Comment by brentschmaltz** [comment]
@mafurman @henrik-me 
I think we can follow the pattern of using fully qualified namespace names.
For example, we can use "Microsoft.IdentityModel.Tokens.MyPropertyBagItem", this seems reasonable.
