### ISSUE TITLE
Documentation: Explain different middlewares

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1153]
**The following should be explained:**
- UseWindowsAzureActiveDirectoryBearerAuthentication is used in ASP.NET Web API samples, using V1.

- UseJwtBearerAuthentication is used in ASP.NET Core Web API samples (5)

- UseOpenIdConnectAuthentication is used in ASP.NET Web Apps (37)
We don’t seem to use UseOAuth2Authentication in our samples.

_Should be explained in the following two docs:_

- https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries

- https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-libraries#microsoft-supported-server-middleware-libraries

**Comment by jennyf19** [comment]
won't fix.
