### ISSUE TITLE
M.IM.Protocols.OpenIdConnect needs to support JsonWebTokens

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1160]
We are moving away from using System.IdentityModel.Tokens.Jwt, so we should have support for Microsoft.IdentityModel.JsonWebTokens in our OpenIdConnect assembly.

OpenIdConnectProtocolValidationContext should have another property on it (either a SecurityToken or simply json or a new interface) that will allow the OpenIdConnectProtocolValidator to use JsonWebToken rather than JwtSecurityToken.

**Comment by jennyf19** [comment]
done in identitymodel 7
