### ISSUE TITLE
TokenValidationResult.IsValid should be based off of the Exception property

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1161]
Currently, we are setting TokenValidationResult.IsValid to 'false' every time we set the Exception property to a non-null value.

Since the Exception property is guaranteed to be set whenever the IsValid property is 'false', we should change 'IsValid' to be get only and simply return 'Exception == null'.

**Comment by brentschmaltz** [comment]
Removing the 'set' would be breaking.
We should ensure every time we set IsValid appropriately.

**Comment by brentschmaltz** [comment]
Fixed in: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1473
