### ISSUE TITLE
JsonWebToken, Getting values from header and payload needs to consider when types don't match

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1169]
If a JsonWebToken has the json { "number", 12345 }. TryGetPayloadValue("number", out string number) will return true and number == "12345" a string.
It will be tricky when the value is 'nil' and the type passed in is not nullable.

**Comment by brentschmaltz** [comment]
If a JsonWebToken has the json { "number", 12345 }. TryGetPayloadValue("number", out string number) will return true and number == "12345" a string.
It will be trick when the value is 'nil' and the type passed in is not nullable.

**Comment by brentschmaltz** [comment]
We should review how we return all values.

**Comment by mafurman** [comment]
If a user passes in a Claim as T, we should return a populated Claim object. If they pass in IList<Claim> or ICollection<Claim> we should follow the same behavior as the Claims property (only go one deep).

**Comment by mafurman** [comment]
We should also add "Claim GetClaim(string jsonKeyName)" method that will allow the user to query for a specific Claim directly. If the type of the Claim is JArray or JObject we should return that as the type and return the value as a string.

This should return the same value that passing Claim as T returns (more explanation above).

**Comment by mafurman** [comment]
Since we agreed that this issue only relates to the payload (values returned by the Claims property), I created a separate issue to implement similar functionality for header claims: #1188.
