### ISSUE TITLE
System.Runtime.Serialization.Xml.dll conflict

### ISSUE THREAD

**Issue by festivus** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1177]
I'm targeting netcoreapp2.1 and when I add the System.IdentityModel.Tokens.Jwt nuget pkg I start getting warnings that there is a conflict with System.Runtime.Serialization.Xml

NETSDK1033: Choosing 'Reference:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Serialization.Xml.dll' becaus
e AssemblyVersion '4.1.4.0' is greater than '4.1.1.0'.

**Comment by brentschmaltz** [comment]
@festivus thanks for pointing this out. We will investigate.

**Comment by festivus** [comment]
> @festivus thanks for pointing this out. We will investigate.
> Are you able to build and run?

Yes, it builds and runs.

**Comment by GeoK** [comment]
Hi @festivus - Which version of IdentityModel are you using?

**Comment by festivus** [comment]
> Hi @festivus - Which version of IdentityModel are you using?

5.4.0

**Comment by brentschmaltz** [comment]
@GeoK we should review what versions we are setting for targets.

**Comment by GeoK** [comment]
@festivus Can you enter the following command into the Package Management Console and let us know if the warning is still there?
`Update-Package -reinstall -ProjectName <yourproject>`

**Comment by GeoK** [comment]
Hi @festivus, did you get a chance to check if reinstalling the package resolves your issue?

**Comment by GeoK** [comment]
@festivus - I'm closing this issue for now, but feel free to re-open it if you have any updates.
