### ISSUE TITLE
AuthenticationProtocolMessage.BuildFormPost script tag CSP nonce

### ISSUE THREAD

**Issue by huan086** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1178]
### Is your feature request related to a problem? Please describe.
It is not recommended to enable `unsafe-inline` in content security policy (CSP), as it would allow JavaScript to run without any additional validation. In the event of cross site scripting, CSP would no longer be able to protect the user. It is recommended to instead use CSP nonce and remove `unsafe-inline`.

In AuthenticationProtocolMessage.BuildFormPost, there is no way to customize the JavaScript script tag to emit the CSP nonce.

### Describe the solution you'd like
Provide an overload in AuthenticationProtocolMessage.BuildFormPost that accepts CSP nonce.

### Additional context
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

**Comment by brentschmaltz** [comment]
@huan086 am I understanding correctly that our script would not run unless 'unsafe-inline' is set. Since there are different forms of the 'nonce', would a parameter (string scriptSecurityPolicy) make sense? The value would be added after '<script '.

**Comment by huan086** [comment]
Correct, the script will not run unless unsafe-inline is set.

I would name the parameter `contentSecurityPolicyNonce`, since in the header, the nonce can appear in default-src or in script-src, thus I would avoid `script` in the name.

The line
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6e7a53e241e4566998d3bf365f03acd0da699a31/src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs#L82

would become

```cs
if (string.IsNullOrEmpty(contentSecurityPolicyNonce)) {
    strBuilder.Append("</form><script>window.setTimeout(function(){document.forms[0].submit()}, 0);</script></body></html>");
} else {
    strBuilder.Append("</form><script nonce=\"").Append(contentSecurityPolicyNonce).Append("\">window.setTimeout(function(){document.forms[0].submit()}, 0);</script></body></html>");
}
```

**Comment by brentschmaltz** [comment]
@huan086 I was wondering if the addition would always be of the form 'nonce="12345"'. In this case passing in "12345" would set this. Is the key word 'nonce' always used?
I am asking should the user pass
1. "12345"
OR
2. "nonce=12345"

**Comment by huan086** [comment]
User should pass "12345". The nonce attribute name won't change

I just realize using hash in the csp is an alternative way to solve the problem without changes in the source code 

https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/

**Comment by mafurman** [comment]
Since it seems like using a hash in the CSP provides the same functionality as using a nonce, we've decided to add a property that returns the string value of the script so that it is easier for users to calculate the hash (for our 5.5.0 release). We plan on adding an overloaded method that allows users to specify a nonce in our 6.x release (tracked in this issue: #1199).
