### ISSUE TITLE
Provide migration aid for breaking changes in 6x

### ISSUE THREAD

**Issue by GeoK** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1183]
Breaking changes in 6x: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/Tools/apiCompat/baseline/ApiCompatBaseline.netstandard2.0.txt

**Comment by brentschmaltz** [comment]
@GeoK @henrik-me we have had very little feedback that anyone has been broken. The number of breaking changes are small, I have closed this.
We can reopen or handle issues as they arise.
