### ISSUE TITLE
SamlSecurityToken protected constructor should create a new SamlAssertion.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1185]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityToken.cs#L41
With this constructor, SamlSecurityToken.Assertion can be null. This is a difference between the Saml and Saml2 SecurityTokens. This constructor is not very helpful as the Assertion property can not be set.

Have the constructor set a new SamlAssertion.

**Comment by mafurman** [comment]
@brentschmaltz Having the empty constructor for SamlSecurityToken set the Assertion property would require us to use the following constructor, as SamlAssertion does not have an empty constructor. 

`public SamlAssertion(
            string assertionId,
            string issuer,
            DateTime issueInstant,
            SamlConditions samlConditions,
            SamlAdvice samlAdvice,
            IEnumerable<SamlStatement> samlStatements
            )`

As DateTime cannot be null, what should be passed in? Or does it make sense to add an empty protected constructor for SamlAssertion as well?

**Comment by brentschmaltz** [comment]
I wonder how anyone could have used this constructor? I really would like to remove it, but back compat blocks us. These parameters can not be null or empty { assertionId, issuer, samlStatements } and code may depend on that. So defaults would be needed also for assertionId, issuer.

To answer your question: UTC.now for issueInstance.

**Comment by mafurman** [comment]
@brentschmaltz I agree; it's unfortunate that we can't remove it.

I'm not sure what the appropriate default value for `issuer` would be... it is a settable property so a user will be able to change it if necessary, but I'm not sure if there's any default value that would necessarily make sense here.

**Comment by brentschmaltz** [comment]
Perhaps ClaimsIdentity.DefaultIssuer would be a choice.
