### ISSUE TITLE
We should have a way of retrieving Claim values from a JWT header

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1188]
Since this issue (#1169) only relates to the JWT payload, we should implement similar functionality for the JWT header.

We should be able to return a Claim representing a {key, value} pair from the Header from the GetHeaderValue() and TryGetHeaderValue() methods.

We should also add a "Claim GetHeaderClaim(string jsonKeyName)" method that will allow the user to query for a specific Claim directly from the header.

**Comment by brentschmaltz** [comment]
We need to duplicate the functionality that we associated with Payload. We currently have GetClaim that assumes we are getting the System.Security.Claims.Claim from the payload.
We will probably need a new api: GetHeaderClaim, TryGetHeaderClaim.

**Comment by brentschmaltz** [comment]
We added these api's to JsonWebTokenHandler
