### ISSUE TITLE
Regex timeout in JwtTokenUtilities with long jwt

### ISSUE THREAD

**Issue by Riff451** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1191]
Hi, I've got this basic code to read a quite big jwt (9MB). I've tried the same code in different machines. It's working well in most of them, but it's failing in two and there's now way to make it works.

The error message is `The RegEx engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors.`

I've checked the source code and the reason for this is in the class `JwtTokenUtilities`.
In [this line](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6c94a28fb638c118c10e020d63ef5c6782d80a7d/src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs#L50) there's an hardcoded 100ms timeout. I think that this was changed from 2s [in 2015](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/262) and the decision was to make it not configurable.

Is there any other way or any other configuration (maybe in the os level... win10) to check/change in order to make this work?

Here is the test code:

`var jwtHandler = new JwtSecurityTokenHandler { MaximumTokenSizeInBytes = 20000000 };`
`string text = System.IO.File.ReadAllText(@"long_jwt.txt");`
`var jwt = jwtHandler.ReadJwtToken(text);    // throws regex timeout exception`

Thanks for your help.

**Comment by Riff451** [comment]
I tried in another machine with visual studio enterprise 2019 16.0.1 and it worked.
I then tried to update VS to 16.1.1 and now I've got the same exception, so the new version of VS has installed/changed something that it's now preventing this code to work properly. The interesting thing is that I tried to uninstall completely all VS versions (from Programs and Features in control panel) that I had in the pc and then just installed VS 2017, but now it's not working in VS 2017 too.

**Comment by Riff451** [comment]
It turned out that updating the project from .net core 2.1 to 2.2 fixes the issue.

**Comment by Riff451** [comment]
I've got more info for this. The issue is caused by some change made in the runtime not the sdk.
I've just tried the following combinations:

- sdk 2.1, runtime 2.1.11 --> KO
- sdk 2.1, runtime 2.1.9 --> OK

- sdk 2.2, runtime 2.2.5 --> KO
- sdk 2.2, runtime 2.2.4 --> OK

I've checked the releases notes for both runtimes (2.1.11 and 2.2.5) and they both have [this change in System.Text.RegularExpressions.dll](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.11/2.1.11.md#changes-in-2111)
I wasn't able to find more information about the specific changes made.

Thanks.

**Comment by brentschmaltz** [comment]
@Riff451 as you noticed, most likely the 100ms is too small for processing a string of this size through RegEx. 

As you mentioned there is no way to set the timeout, the only workaround I can see is to override ReadToken. 

Why do you need such large token?

**Comment by Riff451** [comment]
@brentschmaltz Thanks for the response.

I'm working on a project that for the moment, by design, needs to read such large token for a particular operation. So I think that for my situation I'll need to follow your workaround.

Maybe it's worth considering a couple of options ( just my 2 cent :) ):

- given that it's possible to specify any value for MaximumTokenSizeInBytes in the JwtSecurityTokenHandler, considering adding another parameter to make the regex timeout configurable as well,
OR
- Define a max acceptable value for MaximumTokenSizeInBytes,
OR
- further investigations on the reason why there are these little degradations in terms of performance in the new runtime versions (2.1.11 and 2.2.5 in System.Text.RegularExpressions.dll). But I think this would be something that belongs to another repo :).

**Comment by brentschmaltz** [comment]
@Riff451 If this is related to ValidateToken, you can use [TokenValidationParameters.TokenReader](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6d32e26999b851c5cdcf43c9d2e2f1724d7d913a/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L236) to read the token.
The type of the delegate [ is] (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6d32e26999b851c5cdcf43c9d2e2f1724d7d913a/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L103)

If you just need access to the internals of the token, you can write
`var jsonWebToken = new JsonWebToken(token)`

You can also use JsonWebTokenHandler to validate the token. 

RegEx is not used by the JsonWebToken or Handler.

**Comment by Riff451** [comment]
@brentschmaltz Thank you very much. I used both JsonWebToken and JsonWebTokenHandler. That solved my problems.

**Comment by brentschmaltz** [comment]
@Riff451 good to hear. Sorry for the hassle.
