### ISSUE TITLE
Add property bag to TokenValidationResult

### ISSUE THREAD

**Issue by kevinchalet** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1194]
In the new world, it seems `ClaimsIdentity` is no longer king, as `JsonWebTokenHandler` exclusively uses `SecurityTokenDescriptor.Claims` (an "untyped" dictionary) instead of `SecurityTokenDescriptor.Subject`.

Would it make sense to have a property in `TokenValidationResult` exposing an equivalent to `SecurityTokenDescriptor.Claims`?

**Comment by brentschmaltz** [comment]
@PinpointTownes not sure I would go so far as that  

> is no longer king

 :-), but for the JsonWebToken/Handler our design principals were to make things simpler, remove claim type mapping, work independent of System.Security.Claim, more naturally with Json, prepare for async and an API that doesn't throw.

The token that is returned inside TokenValidationResult is a JsonWebToken, can TryGetPayloadValue<T> meet that need?

**Comment by PinpointTownes** [comment]
> not sure I would go so far as that

Well, using `ClaimsPrincipal` with `JsonWebTokenHandler` has no effect when creating a token (which is a bad surprise), so I think it's fair to say it's no longer king 😄 

> The token that is returned inside TokenValidationResult is a JsonWebToken, can TryGetPayloadValue meet that need?

Is there a way to retrieve the JWT payload as a whole and not just a single property?

**Comment by brentschmaltz** [comment]
> Is there a way to retrieve the JWT payload as a whole and not just a single property?

Not in this release. For .Net Core 3.0, when the new Json replacement is available we plan on adding in support for native json objects.

**Comment by brentschmaltz** [comment]
@PinpointTownes do you still want this feature.
It's simple enough. We have found property bags helpful.

**Comment by PinpointTownes** [comment]
I've decided to stay with `ClaimsIdentity` as the source of truth for both generation and validation as I needed something that was already supported, but yeah, it would be nice to have.

**Comment by brentschmaltz** [comment]
@PinpointTownes ok, will fit it into the release with the Core 3.0 target.
