### ISSUE TITLE
Add an overloaded method for BuildFormPost() that takes in a nonce

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1199]
Providing a nonce value will give users an alternate way to specify that our script is trusted in their CSP (rather than using the hash value of the script).

**Parent issue:**
#1178

**Additional context:**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/

**Comment by jennyf19** [comment]
closing as won't fix.
