### ISSUE TITLE
Suggestion: Improvement to exception message for base64 tokens

### ISSUE THREAD

**Issue by cardinal252** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#120]
As a developer, it would be really great if the exceptions around raw Jwt Token values could be improved slightly by attempting to check for base64 encoded strings and displaying an appropriate error to guide the developer to using base64UrlEncoded strings.

**Comment by cardinal252** [comment]
It would also (as a helper) be great if there was a method to allow converting between base64Encoding and base64UrlEncoding that could be pointed to from the exception.

**Comment by brentschmaltz** [comment]
thanks!
It would not be spec compliant to accept base64Encoding :-(

**Comment by brentschmaltz** [comment]
We will improve the exception message.
