### ISSUE TITLE
Add ability to convert ECDsaSecurityKey to JsonWebKey in JsonWebKeyConverter.

### ISSUE THREAD

**Issue by GeoK** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1208]
JsonWebKeyConverter is missing a method that coverts ECDsaSecurityKey into a JsonWebKey.

**Comment by brentschmaltz** [comment]
Closing as we have https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1317 .
