### ISSUE TITLE
OpenIdConnectConfiguration doesn't have TokenIntrospectionEndpoint

### ISSUE THREAD

**Issue by snoward** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1209]
OpenIdConnectConfiguration doesn't have TokenIntrospectionEndpoint property.

It is very useful property in access token introspection scenario. 

```
var response = await client.IntrospectTokenAsync(new TokenIntrospectionRequest {
    Address = "https://demo.identityserver.io/connect/introspect", // <- here
    ClientId = "id",
    ClientSecret = "secret",
    Token = accessToken
});
```

**Comment by GeoK** [comment]
Hi @snoward, TokenIntrospectionEndpoint is currently not a first class property in OpenIdConnectConfiguration, but you should be able to access it using [AdditionalData](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.protocols.openidconnect.openidconnectconfiguration.additionaldata?view=azure-dotnet#Microsoft_IdentityModel_Protocols_OpenIdConnect_OpenIdConnectConfiguration_AdditionalData):
`openIdConnectConfiguration.AdditionalData["introspection_endpoint"]`

**Comment by brentschmaltz** [comment]
@snoward i think this meets the bar for the next release.
the spec for how this is used is here: https://tools.ietf.org/html/rfc7662

**Comment by snoward** [comment]
@brentschmaltz, good news! Thanks! :)

**Comment by brentschmaltz** [comment]
@snoward , @kevinchalet coded this up and it should be in our 6.6.0 release coming up within a week.

@kevinchalet thanks!

**Comment by kevinchalet** [comment]
My pleasure 😃

**Comment by brentschmaltz** [comment]
@kevinchalet @snoward 6.6.0 has been pushed to nuget.org

**Comment by kevinchalet** [comment]
Awesome, thanks! :clap:
