### ISSUE TITLE
Allow creation of a customized header using JsonWebTokenHandler

### ISSUE THREAD

**Issue by GeoK** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1210]
Some customers have expressed the need for a facility that allows setting custom attributes in the header part, during token creation.

**Comment by steveoshima** [comment]
Hi, when will this be release? Is there a way to get the dev branch build through nuget?

**Comment by steveoshima** [comment]
You will see the testin is missing additonal header setup, if this is added im sure the error will occur. - https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/1c16adc2910c5265f42d007c065def83f20ae00a/test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs#L1347

**Comment by GeoK** [comment]
Hi @steveoshima - There is support for additional header claims, in both dev5x and dev branches.

I wasn't able to reproduce the issue you are facing, both on Windows and Mac, using different .net frameworks, even when changing the test as suggested here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1223#issuecomment-542819363.

Please provide us with more information. What exactly is not working? Are you not seeing the additional header claims when you use RSA-PSS claim, or are you unable to create/sign a token?
Code sample and/or a repro project would be very helpful, together with the full stack trace.

**Comment by steveoshima** [comment]
Hi, when using dev branch, building using build.sh then updating my project the new built nupkg from artifact folder. The dev branch does not allow 
`CreateToken(jwt.Payload, new SigningCredentials(key, SecurityAlgorithms.RsaSsaPssSha256), new Dictionary<string, object>());`
With a branch such as mafurman/customJwtHeader which does allow the above I find SecurityAlgorithms.RsaSsaPssSha256 is not supported when attempting to generate the signed JWT.

**Comment by GeoK** [comment]
Correct, support for additional header claims is coming in v5.6.0.
How are you creating a SecurityKey ("key")?

Is your _key_ an [RSAOpenSsl](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md#native-interop) object?

**Comment by steveoshima** [comment]
I'm using nuget packge PemUtils to read in a private key.
e.g.
`              using (var stream = new MemoryStream(Encoding.UTF8.GetBytes("PrivateKeyHere")))
                {
                    using (var reader = new PemReader(stream))
                    {
                        var key = new RsaSecurityKey(RSA.Create(reader.ReadRsaKey()));
                        key.KeyId = "KidHere";
                        var handler = new JsonWebTokenHandler();
                        handler.SetDefaultTimesOnTokenCreation = false;

                        return handler.CreateToken(jwt.Payload,
                            new SigningCredentials(key, SecurityAlgorithms.RsaSsaPssSha256));
                    }
                }`

When is 5.6.0  due for release. would be useful to get asap. Thanks and good work.

**Comment by GeoK** [comment]
We will release 5.6.0 on Friday or early next week.

Can you check if your _key_ is an RSACryptoServiceProvider or an [RSAOpenSsl](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md#native-interop) object?
[RSACryptoServiceProvider doesn't support PSS](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Supported-Algorithms#---supported-only-by-windows-cng-rsacryptoserviceprovider-doesnt-support-pss).

**Comment by steveoshima** [comment]
The private key is generated from RSAOpenSsl object yes.
