### ISSUE TITLE
Nuget install isn't working

### ISSUE THREAD

**Issue by MCFHTAGENTS** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1212]
Hi,
I am trying to both upgrade and clean install these packages via Nuget and it is not working:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception 'System.AggregateException' thrown when trying to add source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json'. Please verify all your online package sources are available.
One or more errors occurred.
Unable to load the service index for source https://www.myget.org/F/aspnet-contrib/api/v3/index.json.
An error occurred while sending the request.
Unable to connect to the remote server
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 137.116.207.86:443

I am having no issues with other packages over the same route
Thanks
Mark

**Comment by GeoK** [comment]
Hi @MCFHTAGENTS, our nightlies are available on https://www.myget.org/F/azureadwebstacknightly/api/v3/index.json and our release packages are available on [Nuget](https://www.nuget.org/packages/Microsoft.IdentityModel.JsonWebTokens).

**Comment by MCFHTAGENTS** [comment]
Hi this was a nugget outage over the weekend now resolved 
Please close
Thanks
Mark
