### ISSUE TITLE
JwtSecurityTokenHandler mapping should map 'roles' to ClaimTypes.Role 

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#122]
Currently 'role' is mapped to ClaimTypes.Role, also include 'roles'

**Comment by brentschmaltz** [comment]
Fixed in 4.x

**Comment by brentschmaltz** [comment]
We need to update release 5.x

**Comment by brentschmaltz** [comment]
Fixed in 5.x, needs to be pushed to Release 5.x

**Comment by tushargupta51** [comment]
Fixed in Release 5.x. Closing the issue.
