### ISSUE TITLE
Add validation for JWT type

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1220]
According to the latest JWT BCP - different types of JWTs should use different values for the `typ` header field.

https://tools.ietf.org/html/draft-ietf-oauth-jwt-bcp-06#section-3.11

It would be useful to have a `ValidType` property on the `TokenValidationParameters` to be able to easily add this validation check.

**Comment by brentschmaltz** [comment]
After investigating, we will probably want to make this change in 5.x and 6.x

**Comment by brentschmaltz** [comment]
This is a bit involved as we should enable a rule set based on type as covered in 3.12

**Comment by leastprivilege** [comment]
I am think for now it would be totally sufficient to check the typ value.

**Comment by brentschmaltz** [comment]
@leastprivilege agreed.
We can think about the future so we don't box ourselves in.

**Comment by mafurman** [comment]
@leastprivilege We will add a 'ValidTypes' property on the TokenValidationParameters that will be a collection of strings. Matching will be case-sensitive. By default, we will accept all types, but if the property is set we will only allow those types.

**Comment by leastprivilege** [comment]
sounds good- thanks!
