### ISSUE TITLE
Introduce API's to allow user to restrict cryptographic algorithms.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1224]
Best practice suggests users should be able to easily control acceptable algorithms.
While users can use extensibility, it should designed as an inbound policy.

See: https://tools.ietf.org/html/draft-ietf-oauth-jwt-bcp-06#section-3.1

**Comment by leastprivilege** [comment]
Agreed

**Comment by brentschmaltz** [comment]
@leastprivilege @kevinchalet wrote: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1385 i am thinking this is a good candidate for a fix next week.

I am thinking Delegate + IEnumerable<string>.

We have two new hires, so we can get more done :-)

**Comment by keegan-caruso** [comment]
@brentschmaltz How are you envisioning this looking vs TokenDecryptionKeyResolver or TokenDecryptionKeys on TokenValidationParameters?

**Comment by brentschmaltz** [comment]
@keegan-caruso I'm thinking TokenValidationParameters seems to make sense as that is where we control validation.

**Comment by brentschmaltz** [comment]
@leastprivilege 6.6.0 has be pushed to nuget.org
