### ISSUE TITLE
JwtSecurityTokenHandler mapping properties 'ShortClaimType' and 'json_type' should be smaller

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#123]
Currently this property default is: "http://schemas.xmlsoap.org/ws/2005/05/identity/claimproperties/ShortTypeName"
it should be:
shortTypeName or shortName.
Same with: 'json_type'
is: "http://schemas.xmlsoap.org/ws/2005/05/identity/claimproperties/json_type"
it should be:
json_type

**Comment by brentschmaltz** [comment]
Doesn't meet bar.

**Comment by alexandis** [comment]
Hey @brentschmaltz - probably you will shed some light on my issue? I'm adding custom property to "role" claim. It's added. But later when I access `Properties` of "role" claim in the request, it contains only this (default?) `http://schemas.xmlsoap.org/ws/2005/05/identity/claimproperties/ShortTypeName` key with value "role". Nothing more. I have absolutely no idea, who and how might have erased the added property...

**Comment by brentschmaltz** [comment]
@alexandis can you share the code you use?

**Comment by alexandis** [comment]
> @alexandis can you share the code you use?

Sorry, been a while... I was already explained, that JWT token does not preserve `Properties`. So instead of this, I just created a new claim.
