### ISSUE TITLE
Problem validating ES256 JWT

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1233]
I get this error - any idea what wrong (using 5.5.0 on both sides)? thanks!

```
SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: kid: 'gDXkdYYXB3AqRFAh26feOw'. Exceptions caught: ''. token: '{"alg":"ES256","kid":"gDXkdYYXB3AqRFAh26feOw","typ":"JWT"}.{"nbf":1565353200,"exp":1565353500,"iss":"http://localhost:5000","aud":"mvc.hybrid","nonce":"637009499964264282.YzI1OTE5ZDItZTJiOC00NTJjLWFkYjUtNzUzMmIxODUzNDhmYjk3MmEzOTctY2NlNy00ZjRmLWE2YzUtN2YwYTdmMDlmYmYx","iat":1565353200,"c_hash":"aSDyULdP7CdhKXkoLQLpXA","s_hash":"lyNRBYsSjognjNWFGz6Nvw","sid":"Qx6QayNnoYL1RixpINhLIQ","sub":"Ho6h0l2sTd7WVEDneDl1Vz7M0W8KhLj3NHYgo5xvu_U","auth_time":1565353198,"idp":"Google","amr":["external"]}'.
```

**Comment by brentschmaltz** [comment]
@leastprivilege confirming. You are using JsonWebTokenHander to create the token and then fail validating? 
You are using ES256 and an ECDKey?
How are you setting TokenValidationParameters?
It appears no keys were available.

**Comment by leastprivilege** [comment]
I am using the JwtSecurityTokenHandler - 

this is how I am creating the key:
https://github.com/IdentityServer/IdentityServer4/blob/features/aspnetcore3/src/IdentityServer4/src/Configuration/CryptoHelper.cs#L33-L39

this is how I put it into discovery
https://github.com/IdentityServer/IdentityServer4/blob/features%2Faspnetcore3/src/IdentityServer4/src/ResponseHandling/Default/DiscoveryResponseGenerator.cs#L427-L442

Then I use the OpenIdConnect handler from ASP.NET Core to validate it (OIDC authentication workflow). All on 5.5.0 and ASP.NET Core 3 Preview7

**Comment by brentschmaltz** [comment]
@leastprivilege ill have a look

**Comment by scottbrady91** [comment]
It looks like the issue is a combination of not stating the curve on key creation, and a missing `crv` on the JWKS.

**Comment by scottbrady91** [comment]
@brentschmaltz is there a way to get the JWKS style curve name from `ECDsa`? I'm only seeing the oid and friendly name.

For example, we'd need `P-256`, but I can only see `1.2.840.10045.3.1.7` or `nistP256`

**Comment by brentschmaltz** [comment]
@scottbrady91 @leastprivilege yep the crv is missing. when we try a convert the jwk, we skip it. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b16a4d5c90bef3a20b35282ef4dc1fb1b4d8cd49/src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs#L165

If you were to set the DefaultSkipUnresolvedJsonWebKeys = false, you would see an error.

@scottbrady91 you may get some info about the curve from ECParameters. 
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecparameters?view=netframework-4.8
This is only available of select targets.

**Comment by scottbrady91** [comment]
Okay, it looks like you don't expose the rfc7518 crv values in the ECParameters. I'll open a new issue for that :)

**Comment by brentschmaltz** [comment]
@scottbrady91 that should be opened here: https://github.com/dotnet/corefx

**Comment by brentschmaltz** [comment]
@leastprivilege please reopen if needed.
