### ISSUE TITLE
It should be possible to create a JWT with an empty payload.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1237]
This code blocks this.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b16a4d5c90bef3a20b35282ef4dc1fb1b4d8cd49/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L199

See: https://tools.ietf.org/html/rfc7159#section-4

**Comment by rtrtrt777** [comment]
nika
