### ISSUE TITLE
preferred_username claim from Azure AD v2 endpoint not available in the HttpContext.User.Identity.Claims collection

### ISSUE THREAD

**Issue by TiagoBrenck** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1238]
I have tried to set the default claim mapping off using the following line of code, and this shows all the other claims that AAD sends in the id_token, but preferred_username is still not there.

`JwtSecurityTokenHandler.DefaultMapInboundClaims = false;`

How can I get the value of **preferred_username** in the claims collection?

**Comment by GeoK** [comment]
Hi @TiagoBrenck - Are you saying that the preferred_username claim is present in the token, but not in the resulting claims collection?

The library [doesn't map](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/rel/5.5.0/src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs) the preferred_username claim.

**Comment by TiagoBrenck** [comment]
Yes, this is what I meant.

Should it be mapped though?

**Comment by TiagoBrenck** [comment]
Its described as the claim [Microsoft identity platform ID tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) that is the primary username that represents the user. How to get hold of this one in my code?

**Comment by GeoK** [comment]
The profile scope is required to receive this claim.
Can you share your Startup code?

**Comment by TiagoBrenck** [comment]
```csharp

services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
    .AddAzureAD(options => configuration.Bind("AzureAd", options));

services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
{
    options.Authority = options.Authority + "/v2.0/";
    options.TokenValidationParameters.NameClaimType = "preferred_username";
}
```

**Comment by GeoK** [comment]
I wasn't able to repro this. The _preferred_username_ claim is present both in the token and the claims collection.
As NameClaimType is set to "preferred_username", you can get the claim value via `HttpContext.User.Identity.Name`.

**Comment by TiagoBrenck** [comment]
Sorry @GeoK I missed one config.

```csharp
JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
    .AddAzureAD(options => configuration.Bind("AzureAd", options));

services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
{
    options.Authority = options.Authority + "/v2.0/";
    options.TokenValidationParameters.NameClaimType = "preferred_username";
}
```

**Comment by GeoK** [comment]
Hi @TiagoBrenck - nothing has changed except that _oid_, _sub_, and _tid_ claims types are no longer mapped to default claim types, which is as expected.
The _preferred_username_ claim is still there and accessible via `HttpContext.User.Identity.Name`.

**Comment by TiagoBrenck** [comment]
After analyzing the problem using [this sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API), we were expecting the *preferred_username* to be in the bearer token, but it is not since the bearer token is the *access token* acquired on the client side. The *access token* doesn't have the claim *preferred_username*, thus we wont see it in the claims collection as expected.

I am closing this issue because the result is as expected.
