### ISSUE TITLE
Exceptions thrown from IssuerSigningKeyResolver are lost

### ISSUE THREAD

**Issue by davebally** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1239]
Hi,

In the IssuerSigningKeyResolver,  it i throw an exception then the client is told 401.  
I would normal expect a 500 with the developer exception page.
Why not here ?

**Comment by brentschmaltz** [comment]
@davebally what runtime are you using? IdentityModel libraries are used by runtimes and SDK's who should understand the exceptions that are thrown and translate them into an appropriate response. 
This library does not know that it was involved in an http request.

**Comment by davebally** [comment]
This is under asp .net core.  Should i revert to that team ?

**Comment by brentschmaltz** [comment]
@davebally it makes sense to open an issue here: https://github.com/aspnet/AspNetCore 
We may need to make some changes so they bubble up the correct exception.

**Comment by brentschmaltz** [comment]
@davebally 	closing for now, if needed we can reopen
