### ISSUE TITLE
Consider exposing crv values for ECDSA keys

### ISSUE THREAD

**Issue by scottbrady91** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1241]
When handling ECDSA keys, it can be useful to know the corresponding crv value defined in rfc7518.

Currently, only the oidc and friendly name are exposed.

There are some mappings in IdentityModel's ECDsaAdapter, but these methods are private.

(moved from https://github.com/dotnet/corefx/issues/40192)

**Comment by scottbrady91** [comment]
In IdentityServer we were generating a JWKS endpoint where the developer provided many public keys of different types. I found myself having to create mappers between IdentityModel's named curves and the rfc7518 values: https://github.com/IdentityServer/IdentityServer4/blob/features/aspnetcore3/src/IdentityServer4/src/Configuration/CryptoHelper.cs#L107-L148

It seemed like something that should be reusable :)

**Comment by scottbrady91** [comment]
Thanks!

**Comment by brentschmaltz** [comment]
We should do this after adding 4.7.2 target.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1507

**Comment by jennyf19** [comment]
We think this is fixed in the latest IdentityModel. If not, please reopen. Thanks.
