### ISSUE TITLE
System.IdentityModel.Tokens.Jwt 5.5 on a NetStandard 1.4 project causes package error

### ISSUE THREAD

**Issue by damieng** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1244]
When trying to simply bump the package version up from 5.4.0 to 5.5.0 for System.IdentityModel.Tokens.Jwt on our project (netstandard1_4) I get the following error;

 NU1605    Detected package downgrade: NETStandard.Library from 2.0.3 to 1.6.1. Reference the package directly from the project to select a different version.
Auth0.AuthenticationApi -> System.IdentityModel.Tokens.Jwt 5.5.0 -> NETStandard.Library (>= 2.0.3)
Auth0.AuthenticationApi -> NETStandard.Library (>= 1.6.1)    Auth0.AuthenticationApi    D:\auth0\auth0.net\src\Auth0.AuthenticationApi\Auth0.AuthenticationApi.csproj    1

Full project is at https://github.com/auth0/auth0.net/blob/master/src/Auth0.Core/Auth0.Core.csproj for reference.

The only change I can see in 5.5.0 that might cause this is https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1138 ?

**Comment by GeoK** [comment]
Hi @damieng, the change that caused the NU1605 warning is actually https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1187.
I see that you made the same change in v6.5.3.

**Comment by damieng** [comment]
@davidfowl made the recommendation of adding the following line to our csproj which resolved the issue for us:

```xml
<NetStandardImplicitPackageVersion>2.0.3</NetStandardImplicitPackageVersion>
```

I would like to also upgrade our versions of System.Http to avoid known vulnerabilities for our multi-targeted project.  Is your #1187 PR a good thing to look into for how to do that?

(We're not directly affected by the system.http libraries given we are just using it for client functionality and the issues relate to server side but would like to upgrade anyway)

**Comment by davidfowl** [comment]
@terrajobst, Is there a way to target a lower version of NETStandard.Library for older TFMs? We might just need an explicit reference for ns1.4

**Comment by terrajobst** [comment]
@ericstj would know for usre.

**Comment by terrajobst** [comment]
> Of course if Microsoft didn't go out of their way to try and hide version information I might have some metrics numbers that could sway me.

What do you mean by that?

**Comment by mafurman** [comment]
@damieng It appears that the workaround worked; please reopen this issue if you need anything else.
