### ISSUE TITLE
CreateSignatureProvider should support EC-HSM Key type

### ISSUE THREAD

**Issue by MoAhuja** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1252]
We have been trying to leverage the JwtSecurityTokenHandler to validate JWT Tokens we're creating. We've recently switched over to using HSM backed elliptic curve keys (EC-HSM) key type from Azure Key Vault and the validateToken method is throwing the following error 

```'System.NotSupportedException: IDX10621: 'Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider' supports: 'Microsoft.IdentityModel.Tokens.SecurityKey' of types: 'Microsoft.IdentityModel.Tokens.AsymmetricSecurityKey' or 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey'. SecurityKey received was of type 'Microsoft.IdentityModel.Tokens.JsonWebKey'```

Looking through the CreateSignatureProvider method in the CryptoProviderFactory class, the "EC-HSM" key type doesn't appear to be a valid option when iterating through the key types. It seems to only support "EC", "RSA" and "Octet" as valid key type options.

```
if (jsonWebKey.Kty == JsonWebAlgorithmsKeyTypes.RSA || jsonWebKey.Kty == JsonWebAlgorithmsKeyTypes.EllipticCurve)
                            typeofSignatureProvider = typeof(AsymmetricSignatureProvider).ToString();
                        else if (jsonWebKey.Kty == JsonWebAlgorithmsKeyTypes.Octet)
                        {
                            typeofSignatureProvider = typeof(SymmetricSignatureProvider).ToString();
                            createAsymmetric = false;
                        }
```

Since neither of these code blocks get hit, the typeOfSignatureProvider is null and the following code snippet executes further down
```
if (typeofSignatureProvider == null)
                throw LogHelper.LogExceptionMessage(new NotSupportedException(LogHelper.FormatInvariant(LogMessages.IDX10621, typeof(SymmetricSignatureProvider), typeof(SecurityKey), typeof(AsymmetricSecurityKey), typeof(SymmetricSecurityKey), key.GetType())));
```

**Comment by brentschmaltz** [comment]
@MoAhuja you can make use of the extensibility of ICryptoProvider
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/ICryptoProvider.cs

Here is a pointer to test code to give you an idea of how it works.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d4d6d3598952410ff96ef8f38c9ca9ce74bca8bf/test/Microsoft.IdentityModel.Tokens.Tests/CryptoExtensibilityTests.cs#L197

**Comment by brentschmaltz** [comment]
This should be done after adding a 4.7.2 target.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1507

**Comment by brentschmaltz** [comment]
Here is a link that explains a bit about this key type. https://docs.microsoft.com/en-us/azure/key-vault/keys/about-keys

**Comment by jennyf19** [comment]
closing as workaround provided, please reopen if you disagree. thanks!
