### ISSUE TITLE
Support offline signature validation

### ISSUE THREAD

**Issue by briandunnington** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1254]
The official Key Vault docs around signature verification (https://docs.microsoft.com/en-us/azure/key-vault/about-keys-secrets-and-certificates) state "Verification of signed hashes is supported as a convenience operation for applications that may not have access to [public] key material. For best application performance, verify that operations are performed locally."

The KeyVaultSignatureProvider class makes an HTTP call (client.VerifyAsync) for every signature validation. It would be good if the key was cached and signature validation was done locally instead. As it stands now, we are using Key Vault signature verification with some custom authentication scheme so every single protected request now results in an additional HTTP call.

**Comment by brentschmaltz** [comment]
@briandunnington this should be possible as signatures use public keys.

**Comment by briandunnington** [comment]
@brentschmaltz Yes, it is possible to 'roll my own' logic and do the signature verification by grabbing the key and doing it myself. But it would be nice if the extension did this automatically which is why I raised it here.

**Comment by jennyf19** [comment]
@briandunnington is this still a feature you would use and need? what are the impacts with latency?

**Comment by briandunnington** [comment]
@jennyf19 We ended up rolling our own implementation to replace the KeyVaultSignatureProvider implementation. In our implementation, we grab the key vault key and then do the verification locally instead of letting it call out to key vault each time.

for our use case, we issue and sign a custom JWT which we use for authentication in our API endpoints. with the default implementation, each request requires a call to key vault to validate the JWT signature which took ~80-100ms. When you times that by millions of requests a day, it really adds up, especially when the rest of the API processing only takes <100ms total. By doing the signature validation with a local key, the latency is essentially erased completely. 

so yes, we would still use this, but have been using our custom implementation for the last 4+ years successfully so it is not pressing.

**Comment by keegan-caruso** [comment]
KeyVaultSignatureProvider  is no longer supported in 8x.

**Comment by logiclabs** [comment]
Is there any documentation confirming KeyVaultSignatureProvider is no longer supported in v8?  We've just updated from .NET v6 to v8, with IdentityModel 7, and the whole KeyVault Extensions does appear fairly broken already.  We are currently using it for signing JWTs.

The KeyVault extensions wiki page here doesn't mention any deprecation/lack of support: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Keyvault-extensions

Likewise it's not listed as a breaking change for IdentityModel 7.x: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x

Is there a suggested alternative for using KeyVault for signing JWTs, or do we need to roll our own version of KeyVaultSignatureProvider?
