### ISSUE TITLE
Need workaround for using Microsoft.IdentityModel.Protocols Module in .NET Core 3.0 

### ISSUE THREAD

**Issue by WalterWu-AppService** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1255]
We have an issue when using the Microsoft.IdentityModel.Protocols in .NET Core 3.0 project.

Currently, the module on Nuget is version 5.5.0 and cannot support the .NET Standard 2.1 which is for .NET Core 3.0 project.

When we directly add the DLL package "System.IdentityModel.dll" to the project, we cannot use the below code to get the token response.

```
if (someTime >= this._proxy.SecurityTokenResponse.Response.Lifetime.Expires){…}
(_proxy is a Microsoft.Xrm.Sdk.Client.ServiceProxy)
```

Could you please let me know if we have any workaround for using Microsoft.IdentityModel.Protocols in .NET Core 3.0?

Or is there any plan for support .NET Core 3.0 on this package?

**Comment by mafurman** [comment]
We currently do not support .NET Standard 2.1, though it is something we plan on supporting in the future (no release date yet)

We do support .NET Standard 2.0; is it possible for you to target that?

**Comment by brentschmaltz** [comment]
@WalterWu-AppService System.IdentityModel.dll is only supported on .NET desktop and will not be ported method by method.
We have ported enough to Core, in this repo, to support WsFederation (Signin), Saml1, Saml2, WsFedMetadata.

We have work items to enhance our WsTrust and WsFedMetadata which we expect to complete this quarter.

**Comment by brentschmaltz** [comment]
@WalterWu-AppService closing for now. Please track issues with WsTrust tag to get an idea of where we are heading.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AWsTrust
