### ISSUE TITLE
How to make AAD issue JWT signed with nonce for an app?

### ISSUE THREAD

**Issue by coclauso** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1256]
Hi,

I'm not sure that this is the correct resource for this, but I'm having difficulty finding an answer to a question, thought I would try here.

In [this question](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/853), @brentschmaltz replies to the poster that the JWTs issued to graph clients are signed with a nonce.  I have an app registered with AAD which needs the nonce signed token.  Is there a setting in my app registration I can make that will cause AAD to issue this instead of the regular token?

**Comment by brentschmaltz** [comment]
@coclauso this currently is an internal Microsoft technology that is used to reduce the need for the traditional OBO roundtrip when micro-services communicate as part of a call graph. We are not quite ready to offer and support this feature to the public yet, as there are no RFC's in this area. 

Why do you want the nonce?

**Comment by coclauso** [comment]
Thanks so much for the response.  Pertains to [this](https://stackoverflow.microsoft.com/questions/165411/example-with-sal-using-aad) and [this](https://stackoverflow.microsoft.com/questions/166538/how-to-get-a-nonce-in-access-token-from-aad) internal post.

**Comment by brentschmaltz** [comment]
@coclauso let me address this on the internal thread.
