### ISSUE TITLE
JWT claim in the form of DateTime get extra double-quote when converted to claims

### ISSUE THREAD

**Issue by oliviervaillancourt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1261]
Hi,

After an upgrade from 4.x to 5.5 of *System.IdentityModel.Tokens.Jwt*, we are noticing that if we read a Jwt that has a claim as a DateTime, then the value of Claim object is surrounded with double-quote.

Repro:
run this code:
```
var backendToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGFpbV9hc19kYXRldGltZSI6IjIwMTktMTEtMTVUMTQ6MzE6MjEuNjEwMTMyNloifQ.yYcHSl-rNT2nHe8Nb0aWe6Qu3E0ZOn2_OUidpxuw0wk";

            var handler = new JwtSecurityTokenHandler();

            var token = handler.ReadToken(backendToken) as JwtSecurityToken;
            var dateClaim = token.Claims.First();

            var claimValue = dateClaim.Value;
            Console.WriteLine(claimValue);
```
 
Notice that the value of `claimValue` is `"2019-11-15T14:31:21.6101326Z"` instead  of `2019-11-15T14:31:21.6101326Z` (extra double-quote).

From looking into the code a little it seems that this related to the use of JsonConvert.DeserializeObject without specifying a DateFormatHandling property.

Thanks

**Comment by GeoK** [comment]
Thank you for reporting this issue @oliviervaillancourt.
The fix will be released in v5.6.0.
