### ISSUE TITLE
Time related properties ignore timezone information

### ISSUE THREAD

**Issue by SamuelDebruyn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1262]
I use the following code to check if my token has expired or not:

```
var decoded = new JwtSecurityTokenHandler().ReadJwtToken(accessToken);
return decoded.ValidTo > DateTime.UtcNow;
```

However, it's not clear if I should use `UtcNow` or `Now`.

Timezone information seems to be lost in this conversion. If I'm not mistaken a JWT token stores the expiration timestamp as seconds since unix epoch in UTC so we should be sure that the `ValidTo` property is in UTC.

[RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1.4) specifies the following about the expiration:

```
The "exp" (expiration time) claim identifies the expiration time on
   or after which the JWT MUST NOT be accepted for processing.  The
   processing of the "exp" claim requires that the current date/time
   MUST be before the expiration date/time listed in the "exp" claim.
   Implementers MAY provide for some small leeway, usually no more than
   a few minutes, to account for clock skew.  Its value MUST be a number
   containing a NumericDate value.  Use of this claim is OPTIONAL.
```

The same RFC has this to say about the `NumericDate`:
```
A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.
```

I suggest one of either 2 solutions:

- Make `ValidTo` and other time related properties a `DateTimeOffset` so that TZ info is included
- Add clear documentation on the property indicating that the value is in UTC
- Out of the box solution: rely on NodaTime :)

Sidenote: the RFC also says that the expiration is an optional claim so maybe it should even be nullable.

**Comment by mafurman** [comment]
@SamuelDebruyn We will add documentation that states that we use UTC everywhere for this release (5.6.0). We can't change the method to return a DateTimeOffset as that would be a breaking change.
