### ISSUE TITLE
Consider supporting AES-GCM encryption for JWE on netcoreapp3.0

### ISSUE THREAD

**Issue by rytmis** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1264]
Due to requirements of the EU eIDAS directive, Finnish banks are moving to a common standard, the Finnish Trust Network, for strong authentication. Practically speaking, the standard is a set of requirements for either OpenID Connect or SAML v2.

While implementing FTN with one of the available identity brokers, I came across a limitation: JwtSecurityTokenHandler does not support AES-GCM for ID token encryption.

I assume this is because prior to .NET Core 3.0, AesGcm didn't exist in the BCL. It does now, and I was able to hack together an implementation that overrides ValidateToken in a class that derives from JwtSecurityTokenHandler. However, it now supports _only_ that, because I couldn't find a way to do it additively. Instead, I had to mimic from the original source and narrow it down to just AES-GCM-128 with RSA-OAEP.

Would it even be feasible to add netcoreapp3.0 as a separate target and support AES-GCM in that version? 

If not, is there a way to add support for new algorithms in the dependent code that doesn't require overriding the entire implementation?

**Comment by brentschmaltz** [comment]
@rytmis Yes, Yes and Yes.
We held off support for Saml2EncryptedAssertion until 3.0.
We may not get this into the release next week.
I put this into 5.6.1.

**Comment by brentschmaltz** [comment]
Marked this in 6.6.0, but we may not have time.

**Comment by brentschmaltz** [comment]
@rytmis we have the resources to make this happen.
The work is currently in this branch.

Until we release a Core 3.1+ target this feature will only be available on the windows platform.

**Comment by rytmis** [comment]
Thanks for the update! 

We're running on Linux containers on top of AKS, so I guess we'll wait for the newer target. We're fine for now, but obviously I'd love to get rid of any crypto-adjacent code that is ours to maintain. 🙂

**Comment by brentschmaltz** [comment]
@rytmis we added this for receiving, a while back....

**Comment by rytmis** [comment]
Awesome, thanks!

**Comment by brentschmaltz** [comment]
@rytmis not we didn't add support for creating yet.

**Comment by rytmis** [comment]
That's alright, I only need it when receiving tokens. :)
