### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ivikashjha** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1266]
I took ASP.Net quick start template from azure AD and its giving this error An existing connection was forcibly closed by the remote host

**Comment by brentschmaltz** [comment]
@ivikashjha this has to do with how you are setting up your tls.
You can start here: https://blogs.msdn.microsoft.com/friis/2017/10/06/troubleshooting-tls-ssl-scenario-1/

the asp.net team may be a better place to get helpL https://github.com/aspnet
