### ISSUE TITLE
Pin one of the 5.5.1 preview versions

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1267]
@brentschmaltz could you please pin one of the `5.5.1-preview-*` packages so it's not automatically pruned by MyGet? (it's annoying to have to update the dependency version on my side)

**Comment by brentschmaltz** [comment]
@PinpointTownes 5.5.1-preview-61011030454

**Comment by PinpointTownes** [comment]
Thanks!
