### ISSUE TITLE
LogHelper Throw needs to add innerException

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#127]
If the inner exception Is not null, the runtime Activatior.Creatinstance fails with method not found.

**Comment by brentschmaltz** [comment]
fix in 5.x KDev. Needs to be pushed to Release5.x

**Comment by tushargupta51** [comment]
Fixed in Release 5.x. Closing the issue.
