### ISSUE TITLE
Design a way to control simple settings without rebuilding and redeploying 

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1274]
Currently even a simple setting requires rebuilding.
It's possible that application developers could work around this, but it means everyone has to write the code.

When deploying, this would allow a simple way to slice different deployments.

**Comment by brentschmaltz** [comment]
We may just make progress on the design and some low hanging fruit.
Any suggestions are welcome.

**Comment by Tratcher** [comment]
Which settings did you have in mind? I hope they're only the diagnostic ones.

**Comment by brentschmaltz** [comment]
@Tratcher mainly related to diagnostic, but there could be others.
I am curious why you used the phrase "I hope ...."

**Comment by Tratcher** [comment]
Changing functional parameters based on some envronmetal state seems dangerous, you may unintentionally affect other applications on the machine. If you restrict it to diagnostics at least you won't break anyone.

 App models like asp.net already expose ways to specify functional parameters per app in config files. Integrating with those models for controlling diagnostics would be helpful.

**Comment by jennyf19** [comment]
won't fix. done by .NET configuration (IOptionMonitor and associated events which require cooperation with the application)
