### ISSUE TITLE
Why is JwtSecurityTokenHandler in System.IdentityModel.Tokens namespace?

### ISSUE THREAD

**Issue by NullEntity** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1277]
I'm trying to use this library to parse a JWT coming from a claim that I read from WCF/WIF in .NET 4.5. I found it extremely confusing that S.IM.Tokens.Jwt.JwtSecurityToken implements MS.IM.Tokens.SecurityToken instead of S.IM.Tokens.SecurityToken.. Shouldn't the package be in the in the MS.IM namespace instead?

**Comment by brentschmaltz** [comment]
@NullEntity Of the arguments that I lost over the years, this is one I really wish I would have won :-) That battle was lost 4-5 years ago. The reasons are historical and some marketing.

We have created Microsoft.IdentityModel.JsonWebTokenHandler as the logical replacement. We were able to streamline the pipeline somewhat an are about %15 faster on creation.
