### ISSUE TITLE
JwtSecurityTokenHandler.ValidateToken can set the out parameter in case of exception in ValidateToken

### ISSUE THREAD

**Issue by drago-draganov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1290]
```cs
validatedToken = ValidateSignature(token, validationParameters);
return ValidateTokenPayload(validatedToken as JwtSecurityToken, validationParameters);
```

It's unexpected to have the validatedToken set in case of exception.

**Comment by brentschmaltz** [comment]
@drago-draganov if the signature doesn't validate, we expect ValidateSignature to throw.

**Comment by drago-draganov** [comment]
@brentschmaltz,
The code snippet above is from: 

```cs
public override ClaimsPrincipal ValidateToken(string token, TokenValidationParameters validationParameters, out SecurityToken validatedToken)
```

ValidateSignature is totally expected to throw. The problem is when it doesn't, but ValidateTokenPayload throws instead. That leaves the out parameter validatedToken successfully initialized in case of validation failure.

**Comment by brentschmaltz** [comment]
@drago-draganov that is a good point, the out param should be null.

We will see if we can get this into 5.7. But we are booked.
Set as P2, changed Question -> Bug.
If we don't get this into 5.7, we will change the priority to P1 for vnext.
