### ISSUE TITLE
CTY header is not set for JWE

### ISSUE THREAD

**Issue by DShauchuk-IBA** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1295]
I'm using the following code to issue my JWEs:

```csharp
var signCreds = new SigningCredentials(new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration["Jwt:SigningKey"])), SecurityAlgorithms.HmacSha256);
var encryptionCreds = new EncryptingCredentials(new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration["Jwt:Encryptionkey"])), SecurityAlgorithms.Aes128KW, SecurityAlgorithms.Aes128CbcHmacSha256);

var handler = new JwtSecurityTokenHandler();


var jwtSecurityToken = handler.CreateJwtSecurityToken(
  Configuration["Jwt:Issuer"],
  Configuration["Jwt:Audience"],
  new ClaimsIdentity(claims),
  DateTime.UtcNow,
  expiresIn,
  DateTime.UtcNow,
  signCreds,
  encryptionCreds);
```

But it doesn't specify "cty" header of the token - just only alg, enc and typ. If I understand correctly, the header must be set for encrypted JWT so I have an issue while parsing the token in golang because of the headers absence.

I also tried the following ways to issue JWE:

```csharp
var signCreds = new SigningCredentials(new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration["Jwt:SigningKey"])), SecurityAlgorithms.HmacSha256);
var encryptionCreds = new EncryptingCredentials(new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration["Jwt:Encryptionkey"])), SecurityAlgorithms.Aes128KW, SecurityAlgorithms.Aes128CbcHmacSha256);

var handler = new JwtSecurityTokenHandler();

var tokenDescriptor1 = new SecurityTokenDescriptor
  {
     Audience = "you",
     Issuer = "me",
     Subject = new ClaimsIdentity(claims),
     EncryptingCredentials = encryptionCreds
};

var tokenDescriptor2 = new SecurityTokenDescriptor
  {
     Audience = "you",
     Issuer = "me",
     Subject = new ClaimsIdentity(claims),
     EncryptingCredentials = encryptionCreds,
     SigningCredentials = signCreds
};

var tokenDescriptor3 = new SecurityTokenDescriptor
  {
     Audience = "you",
     Issuer = "me",
     Subject = new ClaimsIdentity(claims),
     EncryptingCredentials = encryptionCreds,
     SigningCredentials = signCreds,
     AdditionalHeaderClaims = new Dictionary<string, object> { { "cty", "JWT" } }
   };

var enc = handler.CreateEncodedJwt(tokenDescriptor1);
var encSigned = handler.CreateEncodedJwt(tokenDescriptor2);
var encSignedWithCty = handler.CreateEncodedJwt(tokenDescriptor3);
```

But have the same result:  

![image](https://user-images.githubusercontent.com/55534364/69152284-2afa8280-0aaa-11ea-861a-22f308bbe0df.png)

**Comment by GeoK** [comment]
Hi @DShauchuk-IBA, you should be able to leverage _AdditionalHeaderClaims_ using [JsonWebTokens ](https://www.nuget.org/packages/Microsoft.IdentityModel.JsonWebTokens/)library.
You could use the _tokenDescriptor3_, just replace 
`var handler = new JwtSecurityTokenHandler();` with 
`var handler = new JsonWebTokenHandler();`

Now, looking at [the spec](https://tools.ietf.org/html/rfc7519#section-5.2):

> In the case that nested signing or encryption is
   employed, this Header Parameter MUST be present; in this case, the
   value MUST be "JWT", to indicate that a Nested JWT is carried in this
   JWT. 

, it looks like the library is not enforcing this rule both on creation and validation side.
I'm marking it as a bug for now.

Thank you for reporting the issue. Btw, which go library are you using?

**Comment by DShauchuk-IBA** [comment]
Thank you for the quick answer. 

I'm using [go-jose](https://github.com/square/go-jose/) library for parsing JWT.

**Comment by brentschmaltz** [comment]
@DShauchuk-IBA we are fixing this in our next release

**Comment by brentschmaltz** [comment]
@DShauchuk-IBA when we create the JWE, we don't set the 'cty' because the payload is just json. It is not an actual JWT {with three parts}. We don't have a way to determine what the 'cty' should be.

**Comment by brentschmaltz** [comment]
@DShauchuk-IBA @RojaEnnam What we decided is that for JsonWebTokenHandler we should add a new API similar to: [this](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/c2a6ed5877030f4a7829b5ebbb7242d987c14be8/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L230) for EncryptingCredentials. This will allow the caller to set the CTY by adding a value to additionalHeaderClaims.
For the JwtSecurityTokenHandler and JsonWebTokenHandler we should set 'cty == JWT' when we create the JWE as we are setting the payload to a JWS. 
The code in JsonWebTokenHandler will need to give priority to a 'cty' value found in additionalHeaderClaims as this would have been set deliberately. Call graphs using JwtSecurityTokenHandler do not seem to use AdditionalHeaderClaims, we should check that.

**Comment by brentschmaltz** [comment]
@RojaEnnam @DShauchuk-IBA what we decided is that we should
1. Add a new api similar to: [this](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/c2a6ed5877030f4a7829b5ebbb7242d987c14be8/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L230) with EncryptingCredentials.
2. For JwtSecurityTokenHandler and JsonWebTokenHandler set 'cty==JWT' when they create a JWE. As the payload is a JWS.
3. We know that JsonWebTokenHandler can make use of AdditionalHeaderClaims, if the 'cty' value is found in that collection, we should set the value of 'cty' to that value.
4. Check call graphs of JwtSecurityTokenHandler to ensure AdditionalHeaderClaims are used, if so do the same as 3. above.

**Comment by CumpsD** [comment]
Perhaps a silly question, but does this code mean a `cty` header will always be present when creating a JWT?

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs#L389-L404

```csharp
        internal void AddAdditionalClaims(IDictionary<string, object> additionalHeaderClaims)
        {
            if (additionalHeaderClaims?.Count > 0 && additionalHeaderClaims.Keys.Intersect(DefaultHeaderParameters, StringComparer.OrdinalIgnoreCase).Any())
                throw LogHelper.LogExceptionMessage(new SecurityTokenException(LogHelper.FormatInvariant(LogMessages.IDX12742, nameof(additionalHeaderClaims), string.Join(", ", DefaultHeaderParameters))));

            if (additionalHeaderClaims != null)
            {
                if (!additionalHeaderClaims.TryGetValue(JwtHeaderParameterNames.Cty, out _))
                    Cty = JwtConstants.HeaderType;

                foreach (string claim in additionalHeaderClaims.Keys)
                    this[claim] = additionalHeaderClaims[claim];
            }
            else
                Cty = JwtConstants.HeaderType;
        }
```

since that is being called in the ctor
