### ISSUE TITLE
Beautification of the repository

### ISSUE THREAD

**Issue by GeoK** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1296]
* Update the .readme page.
* Declutter the root directory out of unnecessary files.
* Introduce GitHub badges (total download count, weekly download count,  build status, link to the latest released nuget package, license)
* Restructure and compress the wiki pages (add dropdown menus)
*  Alter the title/name? (mention "Wilson"?)

**Comment by abatishchev** [comment]
Any change to come back to this, please? Right now it's impossible to understand from the [readme](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f262e31d7b3a404f2f6ea956b62d704c5e27fe0e/README.md) what's the name of the resulting NuGet package.

**Comment by brentschmaltz** [comment]
@abatishchev what would be of most help?

**Comment by abatishchev** [comment]
@brentschmaltz regarding my ask, would be great to display a blade of badges with the links to the nuget, build, deployment pipelines, etc.

**Comment by brentschmaltz** [comment]
@abatishchev the readme is a bit stale, our wiki is much more up to date.

**Comment by abatishchev** [comment]
@brentschmaltz I can submit a change similar to this one? https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2406/

**Comment by abatishchev** [comment]
Ah, wait. I see README already lists the latest nuget package version. Cool!

Should we add the latest build/release status too?

**Comment by abatishchev** [comment]
@brentschmaltz ping

**Comment by jennyf19** [comment]
@GeoK  it is beautiful now 🥰
