### ISSUE TITLE
Validate token with public key signature

### ISSUE THREAD

**Issue by jfnu** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1301]
In use cases, I don't see an example on how we can validate the token using public key with this convention "-----BEGIN PUBLIC KEY----- xxxx -----END PUBLIC KEY-----". Can we use jwtSecurityTokenHandler to do that? All the other online examples are using bouncycastle to do it.

Thank you

**Comment by jfnu** [comment]
In follow up to the question, 
how do we validate a token by 3rd party with public key less than 1024 size? for example in 512 size. The DefaultMinimumAsymmetricKeySizeInBitsForVerifyingMap is set to 1024.

 ValidateAsymetricSecurityKeySize method will throw exception "Microsoft.IdentityModel.Tokens.RsaSecurityKey" for verifying cannot be smaller than 1024.

**Comment by brentschmaltz** [comment]
@jfnu can you post a link to an example of 'bouncycastle' to see what this would take from us? Many other devs have hit this.

For keys smaller than 1024, you will have to use extensibility. Note I am suggesting JsonWebTokenHander as the api is simpler and the code is faster.

Either override CryptoProvider you can attach your own cryptoProvider on a SecurityKey see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/110ced71d96efaaaa4db42eb5f3737b7f31ec2d0/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1337

OR use the delegate in TokenValidationParameters.SignatureValidator. Here is where we call this.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/110ced71d96efaaaa4db42eb5f3737b7f31ec2d0/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1207

**Comment by jfnu** [comment]
@brentschmaltz here is the sample
https://stackoverflow.com/questions/49675501/configure-jwt-bearer-token-validation-using-the-public-security-key-in-net-core

need to strip out the header and footer of the public key.

**Comment by brentschmaltz** [comment]
@jfnu the reason is signature with less than 1024 bits are not considered tamper-proof and we don't recommend such key sizes.

While we accept 1024, we will only create with 2048 bits.
