### ISSUE TITLE
OpenIdConnectConfigurationRetriever.GetAsync() uses default JsonSerializerSettings

### ISSUE THREAD

**Issue by Debbus72** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1303]
We are using Microsoft.IdentityModel.Protocols.OpenIdConnect 5.6.0.
In our API (.Net Core 3.1) we have overridden the default JsonSerializerSettings (JsonConvert.DefaultSettings). Especially the setting `MissingMemberHandling` is set to `MissingMemberHandling.Error`.
This now interferes with the retrieval of the OpenIdConnectConfiguration-document since our provider returns more data than is present in `OpenIdConnectConfiguration`. Since this our 3rd-party provider, we can not change their document.

In this line ([OpenIdConnectConfigurationRetriever.cs:92](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/110ced71d96efaaaa4db42eb5f3737b7f31ec2d0/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs#L92)): 
```
OpenIdConnectConfiguration openIdConnectConfiguration = JsonConvert.DeserializeObject<OpenIdConnectConfiguration>(doc);
```

should that use the overload `JsonConvert.DeseriailzeObject<T>(string, JsonSerializerSettings)` so any conflicts with default-settings are prevented?

**Comment by brentschmaltz** [comment]
@Debbus72 can you describe how this is causing you issues?
What error are you receiving?

**Comment by Debbus72** [comment]
Of course.
So attached you will find the payload that we receive from our provider. This json-payload is then deserialized by the Retriever to the `OpenIdConnectionConfiguration`-class.
The exception that we receive is: 
IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.

With an inner-exception: 
Could not find member 'code_challenge_methods_supported' on object of type 'OpenIdConnectConfiguration'. Path 'code_challenge_methods_supported', line 1, position 1102.

I do not know if the entry in the payload is a valid OpenId property.

[response.txt](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/3948774/response.txt)

**Comment by brentschmaltz** [comment]
@Debbus72 I added response.txt to this test and it loaded fine.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a45ee58a27ddfe8422ed84076bf623e6c174cd03/test/Microsoft.IdentityModel.Protocols.Tests/FileDocumentRetrieverTests.cs#L68

Can you turn on PII by coding: IdentityModelEventSource.ShowPII = true;
Then we can see the entire stack.
The error seems to be related to a missing method.

**Comment by Debbus72** [comment]
The exception is:
```
IDX20803: Unable to obtain configuration from: 'https://*ourprovider*/oauth2/.well-known/oauth-authorization-server'.
```

Like I said, we have different default serialization settings set up in our program. So if you add this to your tests, the test will fail.
```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    MissingMemberHandling = MissingMemberHandling.Error
};
```

The default value is `MissingMemberHandling.Ignore` which, as you correctly said, will add the values to the AdditionalData. However, with `MissingMemberHandling.Error` it will throw the error.

**Comment by brentschmaltz** [comment]
@Debbus72 that makes sense.
Since Metadata changes over time, we could account for this by using JsonCnvert.PopulateObject(string, object, JsonSerializerSettings). This would be a change in behavior and some folks would now not fault.

By setting MissingMemberHandling.Error, you seem to be indicating you want to fault.

**Comment by brentschmaltz** [comment]
@Debbus72 in our 6.x branch, currently not released, we do not use the public Newtonsoft library, so you should not see the issue with that release.

We put our nightly packages here:
https://www.myget.org/feed/azureadwebstacknightly/package/nuget/Microsoft.IdentityModel.Protocols.OpenIdConnect

We plan on releasing 6.x in the new year.

**Comment by Debbus72** [comment]
I've include the 6.4.0-preview-61218030541 version from that feed and that seems to do the trick.
