### ISSUE TITLE
Consider exemption to the "PII is hidden" message for configuration retrieval failures

### ISSUE THREAD

**Issue by oliviervaillancourt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1304]
Hi,

We recently encountered a situation where the http request to retrieve the OpenID discovery document was failing in production.  Our logs are showing the very not useful `IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details...` message.  That completely hiding the real reason why the request failed.

I love the PII hiding feature for things like token validation failure and other.  However, I don't see how  the lines that throw the IDX20803 could disclose Personally Identifiable Information.  There's not user here. 

A proposition would be to not call ```LogHelper.FormatInvariant()``` on the Configuration retrieval if it fails.

Please educated me if there is a PII disclosure risk here.

PS: I guess that as an alternatively, I could turn off ShowPII just before the config retrieval and then turn in back on.  I would probably work but I don't feel everyone should have to do that.  

Thanks

**Comment by brentschmaltz** [comment]
@oliviervaillancourt i agree with you. In our need to satisfy GDPR, we used a big hammer, we need to revisit this.
I marked this as an Enhancement.

**Comment by oliviervaillancourt** [comment]
@brentschmaltz .  Thanks for the update.  If you think that a simple change to remove the "PII masking" in the case of `GetConfiguration`  is appropriate, I don't mind doing that work and submitting a PR.

Thanks

**Comment by peval27** [comment]
@brentschmaltz is there any configuration key in app.config that we could tweak without modifying the code?

**Comment by brentschmaltz** [comment]
@peval27 not right now, but we have work items to be able to control settings at runtime.

**Comment by brentschmaltz** [comment]
@peval27 others have commented on this.
We will work to make some progress on this in July.

see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1427 where we wrote:

We recognize the need to adjust this for an application that is running.
We have these issues that address this:
#1274

#1452

If you would like us to consider these in next months release, please put a mark on those issues.

**Comment by mafurman** [comment]
We're going to focus on #1274 so that it's easier to modify the value of ShowPII at runtime.
