### ISSUE TITLE
Remove dead code from ECDsaAdapter

### ISSUE THREAD

**Issue by leejeffr** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1310]
The following method has no references and appears not to be used anywhere. 

Microsoft.IdentityModel.Tokens.ECDsaAdapter.GetKeySize(string curveId)

I am wondering if it really is dead code and maybe consider removing it or explaining how it used.

**Comment by GeoK** [comment]
Hi @leejeffr - it's dead code, thank you for reporting.
I'm renaming the title.
