### ISSUE TITLE
Single-item-claim-array when using ClaimValueTypes.Json changing schema

### ISSUE THREAD

**Issue by azydevelopment** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1313]
Hi folks,

Please see the previous two issues I filed eventually routing me here by the AspNetCore folks:

IdentityServer/IdentityServer4#3968
https://github.com/dotnet/aspnetcore/issues/18178

When sending over a JWT with an array claim with only one value, the claim in user.profile gets transformed to just a string. When an array with 2 values gets sent over in the JWT claim, user.profile sets it to an array with those 2 values.

This means that the schema changes depending on how many items are in the claim which is less than ideal and forces some special casing.

### To Reproduce

Consider this code applied to a React + ASP.NET template with Individual User authentication/authorization. The snippet has IdentityServer send over the JWT claim as an array even if it only has one value in it:

```csharp
public Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    // Get all the roles associated with this subject
    IEnumerable<Claim> roleClaims = context.Subject.FindAll(JwtClaimTypes.Role);

    // Put those roles into a list so we can serialize them after
    IList<string> roles = new List<string>();
    foreach (Claim roleClaim in roleClaims)
    {
        Debug.Assert(roleClaim.Type == JwtClaimTypes.Role);

        roles.Add(roleClaim.Value);
    }

    // Serialize the roles into JSON
    string rolesJson = JsonSerializer.Serialize(roles);

    // Put the roles JSON into an actual Claim object
    Claim claim = new Claim(JwtClaimTypes.Role, rolesJson, IdentityServerConstants.ClaimValueTypes.Json);

    // Add the claim to the IssuedClaims which will eventually end up in the issued JWT
    context.IssuedClaims.Add(claim);

    return Task.CompletedTask;
}
```

The JWT that comes out on the other end does have an array with 1 value in it but user.profile transforms it into a string.

If you don't want to actually create a role before testing this, just replace `rolesJson` above with `"[\"role1\"]"`.

From AuthorizeServices.js checking out user.profile where the claims end up on the client side:

![image](https://user-images.githubusercontent.com/29720335/71945154-dbb40280-317a-11ea-9b83-e55bdba4ba1c.png)

![image](https://user-images.githubusercontent.com/29720335/71945160-e1a9e380-317a-11ea-9c1c-580820c818ab.png)

I considered this as a bug because it overrides the explicitly defined preference of IdentityServer.

### Further technical details
- ASP.NET Core version 3.1

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100     
 Commit:    cd82f021f4  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The VSCode 1.41.1

**Comment by brentschmaltz** [comment]
We should check how we handle roundtripping json when an array has a single string.
Check JsonWebToken.AddClaimsFromJToken

**Comment by brentschmaltz** [comment]
@azydevelopment we ran out of time, i moved this to next months release.

**Comment by azydevelopment** [comment]
Thanks for the update. Would love to get this fixed to remove the need for testing 2 schemas on authed requests

**Comment by brentschmaltz** [comment]
@azydevelopment i am not sure how this is caused by IdentityModel.
If you have additional details, please re-open with additional details.

**Comment by a7md0** [comment]
Facing the same issue here, there's inconsistency when returning list of items (i.e., Roles):

- Having no roles at all will not include an empty list
- Having one role will include the role as string
- Having two or more roles will include list of string

Why can't we just specify the type to be an array?

**Comment by NickDarvey** [comment]
@a7md0, did you find a workaround for this?

**Comment by a7md0** [comment]
> @a7md0, did you find a workaround for this?

@NickDarvey Yes, see this [Stackoverflow answer](https://stackoverflow.com/a/62284152/1738413)

For reference my code was
```c#
claims.AddClaims(userRoles.Select(role => new Claim("roles", role)));
```

Changed to
```c#
claims.AddClaim(new Claim("roles", JsonSerializer.Serialize(userRoles), JsonClaimValueTypes.JsonArray));
```

**Comment by qq874663394** [comment]
> > ，你找到解决方法了吗？
> 
> 是的，请参阅此 [Stackoverflow 答案](https://stackoverflow.com/a/62284152/1738413)
> 
> 作为参考，我的代码是
> 
> ```cs
> claims.AddClaims(userRoles.Select(role => new Claim("roles", role)));
> ```
> 
> 更改为
> 
> ```cs
> claims.AddClaim(new Claim("roles", JsonSerializer.Serialize(userRoles), JsonClaimValueTypes.JsonArray));
> ```

JsonArray is the solution
JSON Array are not the same as JSON String
JsonArray：
JsonClaimValueTypes.JsonArray = ["text":["a1","a2"]]

JSON String:
JsonClaimValueTypes.Json = ["text":"["a1","a2"]"]
