### ISSUE TITLE
JsonWebKeyConverter should be able to convert from/to all key types

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1317]
Some conversions are public some internal.

I'd like to have full round-trippable conversion for RSA, X509 and EC.

see also https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1208

**Comment by brentschmaltz** [comment]
@leastprivilege I assume you mean "when possible".

**Comment by leastprivilege** [comment]
I guess that's what I assume ;)

**Comment by brentschmaltz** [comment]
@leastprivilege of course ;-).

We are thinking of dropping netstandard 1.4, this will give us an unambiguous solution for crypto decision as 1.4 promises some features that are not actually available in net46  or net461.

**Comment by leastprivilege** [comment]
https://www.youtube.com/watch?v=GtUVQei3nX4

**Comment by brentschmaltz** [comment]
Ensure this issue is also addressed.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1338

**Comment by brentschmaltz** [comment]
Also consider: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1208

**Comment by brentschmaltz** [comment]
We may need to scope this for different frameworks.

**Comment by brentschmaltz** [comment]
We have pretty much done all we can until we add the 4.7.2 target.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1507
