### ISSUE TITLE
IDX10690 Wiki page needs to be updated once Wilson6x is released

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1327]
Wilson6x no longer has a netstandard1.4 target and we need to make sure that the Wiki page reflects that.

See: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IDX10690

**Comment by GeoK** [comment]
This one too:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Supported-Algorithms

**Comment by brentschmaltz** [comment]
release notes have updated, supported-algorithms are updated
