### ISSUE TITLE
JwtSecurityTokenHandler.CreateActorValue breaking change

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#133]
In the previous version, `CreateActorValue ` was able to serialize `ClaimsIdentity.Actor` without relying on `ClaimsIdentity.BootstrapContext` (by creating an ad-hoc JWT token and calling `WriteToken` to serialize it):

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1167

This is not the case anymore with the K version, which always throws if `BootstrapContext` is `null`: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens/Jwt/JwtSecurityTokenHandler.cs#L931

Is there any reason for this - rather inconvenient - change?

/cc @brentschmaltz @tushargupta51

**Comment by brentschmaltz** [comment]
I agree, it is too restrictive and should be relaxed.

**Comment by PinpointTownes** [comment]
Nice, thanks @tushargupta51 :+1:
