### ISSUE TITLE
AdditionalHeaderClaims and Claims in SecurityTokenDescriptor are ignored

### ISSUE THREAD

**Issue by erikly** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1335]
Claims added to AdditionalHeaderClaims and Claims in SecurityTokenDescriptor are ignored when the actual token is created. Self contained example:
```
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;

namespace JwtClaims
{
    class Program
    {
        static void Main(string[] args)
        {
            var descriptor = new SecurityTokenDescriptor
            {
                AdditionalHeaderClaims = new Dictionary<string, object> { { "x5c", "the x5c value" } },
                Claims = new Dictionary<string, object> { { "scope", "the scope value" } }
            };
            var token = new JwtSecurityTokenHandler().CreateJwtSecurityToken(descriptor);

            Console.WriteLine(string.Join(", ", token.Header.Keys)); // Does not contain x5c
            Console.WriteLine(string.Join(", ", token.Payload.Keys)); // Does not contain scope
            Console.ReadLine();
        }
    }
}
```
Using System.IdentityModel.Tokens.Jwt 5.6.0 and .NET Core 3.1.

This might be me misunderstanding how to use the library, in this case I'm very interested in where this is documented.

**Comment by mafurman** [comment]
Sorry for the confusion! The `SecurityTokenDescriptor.Claims` and `SecurityTokenDescriptor.AdditionalHeaderClaims` are currently only supported by the [Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs).

We should probably document this on the `SecurityTokenDescriptor` itself.

`Microsoft.Identity.JsonWebTokens` is our newer JWT library which is faster than `System.IdentityModel.Jwt` and also has more features, so I'd recommend using that one if you can.

**Comment by brentschmaltz** [comment]
@erikly does this answer your question?
Please reopen this issue if needed.

**Comment by Andrew-Webb** [comment]
> `Microsoft.Identity.JsonWebTokens` is our newer JWT library

Do you mean Microsoft.IdentityModel.JsonWebTokens, as in:-

https://www.nuget.org/packages/Microsoft.IdentityModel.JsonWebTokens/

?

**Comment by erikly** [comment]
It answered my question, thank you!
