### ISSUE TITLE
JsonWebKeyConverter - ConvertFromECDsaSecurityKey for netstandard 2.1

### ISSUE THREAD

**Issue by brunohbrito** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1338]
I was missing an option to convert ECDsa SecureKey to JsonWebKey at [JsonWebKeyConverter.cs](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/JsonWebKeyConverter.cs).

But I figure out that the method actually exists, `ConvertFromECDsaSecurityKey`, but is only available to netstandard 2.0.

There is any plans to move on an make it also available for netstandard 2.1 ?

**Comment by brentschmaltz** [comment]
@brunohbrito if you look at our dev branch (6.x) we have been adding some such needed features (along with SignedHttpRequest) that we are planning on releasing soon.

In addition, we are preparing a clean netstandard 2.0 crypto layer.
There are some breaking changes that we are currently sorting out.

**Comment by brentschmaltz** [comment]
@brunohbrito i am going to close this and reference this issue in: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1290
