### ISSUE TITLE
JwtSecurityTokenHandler ResolveIssuerSigningKey

### ISSUE THREAD

**Issue by davidikin45** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1339]
JwtSecurityTokenHandler.ResolveIssuerSigningKey doesn't compare jwt.x5t with signingKey.x5t if validationParameters.IssuerSigningKeys is used rather than validationParameters.IssuerSigningKey. Is there a reason for this?

**Comment by brentschmaltz** [comment]
@davidikin45 this is a bug, there is no good reason.
We will get this fixed as all keys will be tried.
