### ISSUE TITLE
Build NuGet packages from source

### ISSUE THREAD

**Issue by michaelmualem** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1344]
Hello,

I am trying to build the following NuGet packages from source code:
1. Microsoft.IdentityModel.Tokens.Saml
2. System.IdentityModel.Tokens.Jwt

Using the build.cmd script I am getting the error :
Start-Process : This command cannot be run due to the error: The system cannot find the file specified. At \azure-activedirectory-identitymodel-extensions-for-dotnet\build.ps1:103 char:30
+ ... ageResult = Start-Process -Wait -PassThru -NoNewWindow perl $root\src ...
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Does anyone have any idea what could be wrong ?

As it fails, I tried to generate the packages on build with Visual Studio. The build succeeded, but the output is a "0.0.1-preview" .nupkg file (although I checked out to version "5.6.0" tag). Why is that ? I need the 5.6.0 version.

Please help.
Best regards,
Michael

**Comment by brentschmaltz** [comment]
@michaelmualem we expect 'perl' to be installed.
We should adjust our build script to skip if perl is not available.
You could install perl OR comment out that line.

All our local builds have version 0.0.1-preview unless 'updateAssemblyInfo.ps1' is run.

**Comment by michaelmualem** [comment]
OK thanks for the quick response !

I ran updateAssemblyInfo.ps1 and thegenerated  NuGet package version indeed changed to 5.6.0 but it is still have "preview-70305113207" in its name. Why is that ? I don't want a preview version.

**Comment by GeoK** [comment]
@michaelmualem I'm curious to know why are you building nugets from source? 
To answer your question - run _updateAssemblyInfo.ps1_ with packageType = **release**.
 https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/cc6d48f33df400362d261b6272ba5e4215f64e52/updateAssemblyInfo.ps1#L2

**Comment by brentschmaltz** [comment]
@michaelmualem i assume you are satisfied with this result.
you can build the packages, but you will not be able to sign them
