### ISSUE TITLE
Microsoft.IdentityModel.Tokens, Version=5.6.0.0 calling 'Newtonsoft.Json, Version=10.0.0.0,

### ISSUE THREAD

**Issue by haytapot** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1345]
Target: .Net 4.6.1
System.IdentityModel.Tokens: v5.6.0
Newtonsoft.Json: v.12.0.3

I get this issue:
`Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`
...
...
`Calling assembly : Microsoft.IdentityModel.Tokens, Version=5.6.0.0, Culture=neutral`

newtonsoft should be greater then 10?

**Comment by GeoK** [comment]
Hi @haytapot - Please try out the solution proposed here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1033#issuecomment-431148176

As an alternative solution, reinstall the Newtonsoft.Json NuGet package using Package Manager Console Window. In Visual Studio go to View -> Other Windows -> Package Manager Console and then type in the console: `Update-Package –reinstall Newtonsoft.Json`

**Comment by KamranShahid** [comment]
Bit off topic but is there any planning of getting rid of newtonsoft for atleast .net core 3.1 and greater version?
In .net core 3.1 i am now using System.Text.json for every piece of code where newtonsoft were used. So Any plan for this library without newtonsoft

**Comment by GeoK** [comment]
@KamranShahid - We are planning on releasing Wilson 6x in a couple of weeks which won't have an external Newtonsoft.Json dependency.

**Comment by KamranShahid** [comment]
> @KamranShahid - We are planning on releasing Wilson 6x in a couple of weeks which won't have an external Newtonsoft.Json dependency.

Great. by the way what is "Wilson 6x" mean

**Comment by GeoK** [comment]
Apologies, I should have been more clear. Wilson is the code name for the library (set of IdentityModel assemblies). 6x refers to the major version of the next release.

**Comment by brentschmaltz** [comment]
@KamranShahid we have released 6.5.1 that does not have an external dependency on Newtonsoft.
