### ISSUE TITLE
Any possibility of overriding of minimumkey size of particular algorithm in AsymmetricSignatureProvider

### ISSUE THREAD

**Issue by KamranShahid** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1347]
Referring to my post 
https://stackoverflow.com/questions/60599339/any-way-to-create-a-jwt-token-with-key-size-512-and-changing-default-minimum-si

I need to change the minimum value of RSA256 key requirement from 2048 to 512.
Any possibility i can do it?

I am using .net core 3.1 with

Assembly Microsoft.IdentityModel.Tokens, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

I have to consume existing system key sets

**Comment by brentschmaltz** [comment]
@KamranShahid you can do that, but we set 2048 for security reasons. Keys of length 512 will not be accepted by our runtime as they are not strong enough.

You would have to make use of extensibility.
You would need a custom AsymmetricSignatureProvider
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/cc6d48f33df400362d261b6272ba5e4215f64e52/src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs#L38

Then overload: 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/cc6d48f33df400362d261b6272ba5e4215f64e52/src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs#L330

You may also need to overload: Sign and Verify.

**Comment by KamranShahid** [comment]
I am just using SecurityTokenDescriptor to generate the id token. So looks like there isn't any option in the class to override the settings.
For the hack i have used Reflection to change the Values DefaultMinimumAsymmetricKeySizeInBitsForVerifyingMap and DefaultMinimumAsymmetricKeySizeInBitsForSigningMap

Bit dirty code but effective 
```
var mainclass = typeof(AsymmetricSignatureProvider)
                       .GetField(nameof(AsymmetricSignatureProvider.DefaultMinimumAsymmetricKeySizeInBitsForSigningMap), BindingFlags.Public | BindingFlags.Static);
                var field = mainclass.GetValue(null) as Dictionary<string, int>;
                if (field != null)
                {
                    field["RS256"] = 512;

                }

                var mainclass2 = typeof(AsymmetricSignatureProvider).GetField(nameof(AsymmetricSignatureProvider.DefaultMinimumAsymmetricKeySizeInBitsForVerifyingMap), BindingFlags.Public | BindingFlags.Static);
                var field2 = mainclass2.GetValue(null) as Dictionary<string, int>;
                if (field2 != null)
                {
                    field2["RS256"] = 512;
                }
```

**Comment by brentschmaltz** [comment]
@KamranShahid you can always use reflection. Development teams do not consider changing internals as breaking. So this approach may not work in the future. When we mark items internal or private, we make assumptions that may not hold if changed externally.

**Comment by KamranShahid** [comment]
> @KamranShahid you can always use reflection. Development teams do not consider changing internals as breaking. So this approach may not work in the future. When we mark items internal or private, we make assumptions that may not hold if changed externally.

Then atleast put some option to set it as per the requirement.

**Comment by brentschmaltz** [comment]
@KamranShahid by design we make it hard to do things that we do not consider secure.

**Comment by KamranShahid** [comment]
> @KamranShahid by design we make it hard to do things that we do not consider secure.

Totally Agreed. But My Case is regarding support of some legacy system which might be running in production

**Comment by brentschmaltz** [comment]
@KamranShahid the solution I outlined above, although complicated (by design :-) ), is durable as it uses public API's. This is of the reasons for extensibility. Microsoft is committed to maintaining backward compatibility. There are times when this is has to be broken, but this is very rare as we know how much trouble breaking backward compatibility causes.
