### ISSUE TITLE
Base64UrlEncoder perf improvements

### ISSUE THREAD

**Issue by gfoidl** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1356]
In [gfoidl.Base64](https://www.nuget.org/packages/gfoidl.Base64/) I created a library with _base64Url_ support for direct encoding / decoding with usage of simd-instruction (and software-fallback).
It's quite a lot faster (with SIMD x2 ... x20 depeding on size, for .NET Standard x2 ... x6) with less allocations [[1]](https://github.com/gfoidl/Base64/blob/e0dbaddb9eb44462dabf2e29b3ab7899c613ef3e/perf/gfoidl.Base64.Benchmarks/results/EncodeStringUrlBenchmark-report.md), [[2]](https://github.com/gfoidl/Base64/blob/e0dbaddb9eb44462dabf2e29b3ab7899c613ef3e/perf/gfoidl.Base64.Benchmarks/results/DecodeStringUrlBenchmark-report.md).

Is there any interest in using this here?
If the external dependency is a no-go it's also possible to port the relevant code over here.

With the external dependency the change here is rather trivial, as it's just a forwarding in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2ff50e601b7a798b29a7ae11d455fb2aaae7070d/src/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.cs#L37 to `Base64.Url`-methods.

I can submit a PR in case of interest.

**Comment by brentschmaltz** [comment]
@gfoidl we can only take dependencies on .Net right now.
There is an option for users to use this work by hooking their own encoder.
We haven't seen a wide use of this extensibility, so we should run some test to see if your work can plug in.
Have a look to see if this model works: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2ff50e601b7a798b29a7ae11d455fb2aaae7070d/src/System.IdentityModel.Tokens.Jwt/JsonExtensions.cs#L31

**Comment by gfoidl** [comment]
If I see it right, then https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2ff50e601b7a798b29a7ae11d455fb2aaae7070d/src/System.IdentityModel.Tokens.Jwt/JsonExtensions.cs#L31 is an extension for `object <-> JSON`. 
_base64Url_ is used in [more places](https://github.com/search?q=Base64UrlEncoder+repo%3AAzureAD%2Fazure-activedirectory-identitymodel-extensions-for-dotnet+path%3A%2Fsrc&type=Code&ref=advsearch&l=&l=) in this repo than just `object <-> JSON`. Maybe I'm missing something now, but I don't think the extension model is the right place to hook it in.

> we can only take dependencies on .Net

My project has [a target for .NET Standard 2.0](https://github.com/gfoidl/Base64/blob/d835b32bd99fb2ad3044463ae254750a324537f8/Directory.Build.props#L24), this project has also one
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2ff50e601b7a798b29a7ae11d455fb2aaae7070d/build/targets.props#L3

But I could add a target for .NET 4.6.1 if that helps.
I'm not sure for .NET 4.5, because of the usage of `Span<T>`.

**Comment by brentschmaltz** [comment]
@gfoidl by 

> we can only take dependencies on .Net

We mean the actual .net assemblies, we can't take dependencies on 3rd parties at this layer.

**Comment by gfoidl** [comment]
Ah, OK. Thanks for the info. I'm closing this issue then.
