### ISSUE TITLE
NullReferenceException in JwtPayload when a claim has a null value. (A null value should be acceptable)

### ISSUE THREAD

**Issue by StephaneBischoff** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#136]
If a claim has a null value, then a NullReferenceException is raised in JwtPayload.

I believe that the line at fault is:
JwtPayload.cs -  line 375 ->  keyValuePair.Value.GetType()

**Comment by brentschmaltz** [comment]
@StephaneBischoff can you add the stacktrace? The .Net Claim.Value cannot be 'null', so we are trying to figure out what to do in this case. JSON allows 'null' values, but .Net doesn't.

**Comment by brentschmaltz** [comment]
We should at least fix the null ref and drop the claim. It will still be in the jwtpayload, but not in the ClaimsIdentity.

**Comment by Beanow** [comment]
+1 to fix this bug, blocking issue for us currently.

@brentschmaltz I disagree that the values should be dropped though. It suggests that the claim was missing, but this is not the case. The 3rd party explicitly indicated that a certain claim has an empty value. If we're talking dirty fixes I would suggest for example using ClaimValueTypes.HexBinary or any of the other binary encodings with value string.Empty. Essentially this is a valid representation of null.

```cs
if(keyValuePair.Value == null){
    claims.Add(new Claim(keyValuePair.Key, string.Empty, ClaimValueTypes.HexBinary, issuer, issuer));
}
```

On the other hand, getting this fixed at all takes priority in my opinion. Just putting it out there.

**Comment by tushargupta51** [comment]
@Beanow Thanks for your input. We are looking into this. Are you using 4.x or 5.x version?

**Comment by Beanow** [comment]
4.x, the latest stable using nuget.
And for debugging I've looked at the master branch's head.

**Comment by brentschmaltz** [comment]
@Beanow We are thinking about introducing a new ClaimValueType in this library to represent the null do you think that would work for you?

**Comment by Beanow** [comment]
I think that all hinges on how closely it behaves like null when implementing controller logic. Does it equal to null? Will it serialize to null when you're making json strings? Will the new C# operators treat it as null (`claim ?? default`)?
Then, will it conflict with whatever reason there originally was to not have nulls in owin?

**Comment by tushargupta51** [comment]
@Beanow You mentioned that using `string.Empty and ClaimValuetypes.HexBinary` is a valid representation of null. I was trying to find some evidence to back it up. Does it serialize to null when converting to json strings?

**Comment by Beanow** [comment]
@tushargupta51 I haven't tried them, they were my theories. It depends on the actual implementation I guess. You could also argue `string.Empty` hexadecimal should result in a format error. That's why it would be dirty though. I think the new ClaimValueType that is certainly null would be less error prone.
