### ISSUE TITLE
Api SecurityTokenExpiredExceptions in App Insights logs

### ISSUE THREAD

**Issue by waynethompson** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1368]
We have an angular application that gets an access token from identity server and uses it to connect to an aspnetcore api application.

I have added the authentication to the API application with
authenticationBuilder.AddJwtBearer()

In Azure Application Insights logs for the Api i get a lot of Microsoft.IdentityModel.Tokens.SecurityTokenExpiredExceptions but they don't affect the functionality.
IDX10223: Lifetime validation failed. The token is expired. ValidTo: '03/30/2020 02:28:05', Current time: '04/01/2020 22:26:59'.
Does anyone know why this happens or how to remove the chatter from the logs?

Is it possibly because someone has left the browser open for a day and it still has the old access token? Should I poll the Api after a period of time and then make it get a new access token?

**Comment by brentschmaltz** [comment]
@waynethompson this exception indicates the access token has expired and is no longer valid.
In general the token shouldn't be accepted if expired otherwise any tokens that have been leaked (either in logs or otherwise) OR are in the browser history can be used indefinitely.

The application should not be returning protected resources with this token.

Yes, you should get a new token.

**Comment by brentschmaltz** [comment]
@waynethompson so if you are holding on to the token for a while you will need to refresh it. 

We have libraries for js that do some of this work for you, refreshing when necessary.
Have a look at: https://github.com/AzureAD/microsoft-authentication-library-for-js

If you need to write your own code, the OAuth 'token' response contains metadata indicating when the token expires.

**Comment by brentschmaltz** [comment]
@waynethompson closing for now, please reopen if you have additional asks.
