### ISSUE TITLE
Incompatibility of 6.5 with existing Azure packages

### ISSUE THREAD

**Issue by geredwards** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1369]
I've updated a few references to the 6.5 IdentityModel libraries, but a few conflicts exist, particularly around existing Azure packages.
Latest version 4.1.2 of Microsoft.Azure.ServiceBus has a reference constraint on System.IdentityModel.Tokens.Jwt of >=5.4.0 && **<6.0.0** so is incompatible with the new packages.

Similarly, Microsoft.Azure.Management.ResourceManager.Fluent 1.32.0 ends up in a dependency on Microsoft.IdentityModel.Tokens (via Microsoft.Rest.ClientRuntime.Azure.Authentication) which is also <6.0.0.

So what's your advice here re using 6.5?
Add explicit references to affected projects?
Or not upgrade?

THANKS!

**Comment by brentschmaltz** [comment]
@geredwards I would stay with 5.4.0 or 5.5.0 until we sort this out.
What type of errors are you seeing?
Could you provide some of the steps in your scenario?

**Comment by geredwards** [comment]
Thanks for your reply, this is the scenario I have...

I have a .net Standard library project which references Microsoft.Azure.ServiceBus
A .net Core 3.1 app references that project, and also references System.IdentityModel.Tokens.Jwt.

I upgrade the packages across the board, so the System.IdentityModel references are now 6.5.

I now get a library project error stating: 
```
Error	NU1107	
Version conflict detected for System.IdentityModel.Tokens.Jwt. 
Install/reference System.IdentityModel.Tokens.Jwt 6.5.0 directly to project...

```
It complains because the project references Microsoft.Azure.ServiceBus 4.1.2 which has a constraint on System.IdentityModel.Tokens.Jwt (>= 5.4.0 && < 6.0.0).

If I then add the reference to System.IdentityModel.Tokens.Jwt directly into the project, I get a warning:
`Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.Azure.ServiceBus 4.1.2 requires System.IdentityModel.Tokens.Jwt (>= 5.4.0 && < 6.0.0) but version System.IdentityModel.Tokens.Jwt 6.5.0 was resolved.`

Hope that clarifies.

**Comment by brentschmaltz** [comment]
@geredwards thanks for the detail, i will see what we can do, for now you will have to stick with 5.5.0.

**Comment by brentschmaltz** [comment]
@geredwards we believe that 6.5.0 for most scenarios is back-compatible with 5.5.0.
There are very few edge cases that will cause issues.

In the Errors and warnings tab, you could suppress warning: NU1608.

**Comment by geredwards** [comment]
Thanks for the clarification... Good to hear that it should be backwards compatible. There appear to be quite a few existing packages which have constraints of <6.0.0 on the IdentityModel packages.

I think I'll stick to 5* for the time being - otherwise I'll need to reconfigure all our builds not to treat warnings as errors! :-)

THANKS!

**Comment by brentschmaltz** [comment]
@geredwards I will close this out for now.
You can restrict warnings for this specific warning and still fail on others.

**Comment by dxynnez** [comment]
@brentschmaltz is there any followup task created to help track on this? We also have dependencies on IdentityModel.Tokens > 6.0 but a lot of azure packages are still using IdentityModel.Tokens >= 5.1.2 && < 6.0.0.

**Comment by GeoK** [comment]
@dxynnez - This issue is raised in azure-sdk-for-net repo:
https://github.com/Azure/azure-sdk-for-net/issues/11617

**Comment by brentschmaltz** [comment]
@dxynnez @GeoK has provided a link with the project that needs fixing. Can you chime in there? I pinged them.

**Comment by dxynnez** [comment]
Thanks @GeoK and @brentschmaltz , will do.

**Comment by brentschmaltz** [comment]
@GeoK @jmprieur it looks like they are going to make a fix !
