### ISSUE TITLE
Support for receiving query string parameters as part of OIDC metadata response

### ISSUE THREAD

**Issue by jaraya-MSFT** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#137]
Currently, if the OIDC metadata endpoint contains a query string parameter in the URL it returns (ie: authorization_endpoint: https://example.com/path?key=value, OWIN-Katana does not handle this properly.

Basically, Katana attempts to add its own query string parameters with a new "?" delimiter in this case, creating an invalid URL (ie, https://example.com?key=value?someKatanaKey=secondValue

**Comment by brentschmaltz** [comment]
@jaraya-MSFT we should have this fixed in Beta5.
