### ISSUE TITLE
WsTrustChannelSecuritytokenProvider.GetProoftoken should not assume wstrust1.3

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1371]
KeyTypes are version specific (2005 != trust1.3), we need to know the version of the version of trust OR allow different version of trust.

This requires some thought through-out the call graph.
We need to establish the version of trust in the beginning of the read and pass a context through the call graph.

We need to also think about the rst/rstr exchange should versions match?

**Comment by mjrousos** [comment]
Good catch. The existing `GetTokenCore` also looks like it assumes Trust1.3 (when deserializing/serializing RSTs and RSTRs), so we'll probably need to update that, as well. I'll look to see how we've determined trust version in the past.

**Comment by mjrousos** [comment]
[The way this worked in NetFx](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Security/ClientCredentialsSecurityTokenManager.cs,399) was that `MessageSecurityVersion` was read:

1. First, from the issuer binding's SecurityBindingElement.
2. If that wasn't present, then (if that wasn't present) from `IssuedSecurityTokenParameters.DefaultMessageSecurityVersion`.
3. If none of those were set, from [the security token requirement's security binding element](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Security/Tokens/ServiceModelSecurityTokenRequirement.cs,23)
4. Finally, it defaulted to 2005.

We could do something like this in `WSTrustSecurityTokenProvider` and determine key type and pick a serializer based on the results.

**Comment by brentschmaltz** [comment]
we have added the version to WsTrustParameters
