### ISSUE TITLE
Unity : The type or namespace IdentityModel does not exist in the namespace System 

### ISSUE THREAD

**Issue by aidanikuz02** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1373]
Hello, Im using Microsoft Visual Studio 2017. I need to debug JWT so i installed System.IdentityModel.Token.Jwt from Project > Manage NuGet packages. But in unity it is showing error like title of this issue. How do i fix this? the version is 6.5.0. I also have the Microsoft.IdentityModel.xxx installed.

**Comment by keegan-caruso** [comment]
@aidanikuz02 Unity requires a special process to add nuget packages. Please follow this guide:

https://docs.microsoft.com/en-us/visualstudio/cross-platform/unity-scripting-upgrade?view=vs-2017#add-packages-from-nuget-to-a-unity-project

**Comment by brentschmaltz** [comment]
@aidanikuz02 if this doesn't solve your problem, please reopen.
