### ISSUE TITLE
TokenValidationParameters.ValidTypes is not preserved when cloning a TVP instance

### ISSUE THREAD

**Issue by kevinchalet** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1379]
Likely due to an oversight, the `ValidTypes` property is not set by TVP's constructor when cloning a TVP instance:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6cf2400a3d6f55cc62e4e07b55bd6b6e9ddd4189/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L145-L188

**Comment by brentschmaltz** [comment]
@kevinchalet right you are sorry about that, we will fix that.

**Comment by brentschmaltz** [comment]
@kevinchalet i piggy-backed this into a service fix we needed. Should be out in a day or so. 6.5.1.

**Comment by kevinchalet** [comment]
Good news! I know https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1378 is not a bug, but is there's any chance it could be part of an incoming release? As I said, I'm fine submitting a PR if you approve the idea and it could help.

**Comment by brentschmaltz** [comment]
@kevinchalet there was a memory pressure that we fixed that some teams were waiting on so we pushed 6.5.1, but our pipeline is fairly slick, so we can get 6.5.2 or 6.6.0 out with #1378 quickly.

**Comment by kevinchalet** [comment]
Great, thanks @brentschmaltz!
