### ISSUE TITLE
SignedHttpRequest values should be validated if they are found.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1393]
make these optional by default

**Comment by henrik-me** [comment]
@brentschmaltz perhaps these changes should be opt. in? That is, a flag which enables these claims to be optional and not required.

**Comment by brentschmaltz** [comment]
@henrik-me, yes thanks i changed the title to include 'default'.

**Comment by brentschmaltz** [comment]
If a non-empty or null value exist, then they should be validated.

for example 'm' is NOT required
if 'm' is null or empty-string then there should be no failure.

otherwise 'm' should be validated.

**Comment by brentschmaltz** [comment]
@keegan-caruso thanks for jumping on this.

We are in a interesting spot as our API's with Validate in TokenValidationParameters are skipped even if an artifact exists, except for signatures.
For example, TokenValidationParameters.ValidateLifetime == false and 'exp' is in the past, the check will never be made.

Currently, SignedHttpRequestParameters.ValidateM is ON or OFF.

This change is to enable logic: SignedHttpRequest arrives with 'M', then it will be validated.

If the application sets ValidateM == false AND 'M' == null || 'M' == string.Empty then the runtime will not throw an exception.

Said another way, 'ValidateM == false' means validate if it exists, but it's ok to be missing.
We do something similar with Json tokens in [JsonWebTokenHander.ValidateSignature](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/1884beb2c84a6792c8f142dbbe40dfb1dac3d635/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1189) 

This is in the belief that the only reason the value exists is the sender wanted to have the value validated.

If the sender wants to include custom information, they should used an undefined claim.

How can we do this cleanly and consistently with our other API's will be interesting.
