### ISSUE TITLE
Pass IKeyVaultClient as parameter

### ISSUE THREAD

**Issue by esavini** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1396]
I have one suggestion, to improve the testing of the projects that are using this library. I have spent the last two days making copy and paste of this library's code and adapting it. 
The major issue is you cannot pass the `IKeyVaultClient `instance to the constructors of `Microsoft.IdentityModel.KeyVaultExtensions.KeyVaultSecurityKey`and `Microsoft.IdentityModel.KeyVaultExtensions.KeyVaultCryptoProvider`.

The biggest consequences are:
- you cannot mock it in unit tests;
- if you are using dependency injection you can also have already an instance of `IKeyVaultClient ` but if you cannot pass it you are forced to repeat some code (credentials, etc).

**Comment by jennyf19** [comment]
closing a won't fix.
