### ISSUE TITLE
Consider adding a TokenType property to SecurityTokenDescriptor

### ISSUE THREAD

**Issue by kevinchalet** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1397]
When creating an encrypted JWT using the `CreateToken(SecurityTokenDescriptor tokenDescriptor)` API, the headers added to `SecurityTokenDescriptor.AdditionalHeaderClaims` are only used for the JWE container and not the JWS. If you want to assign the JWS a specific `typ`, you must first create an unencrypted token with `AdditionalHeaderClaims` populated and then encrypt it manually, potentially with `AdditionalHeaderClaims` populated too if you want both the JWE and the JWS to have a `typ` header.

This procedure is a bit counter-intuitive and frankly error-prone. Things would be much simpler if `SecurityTokenDescriptor` had a `TokenType` property that would be used when creating both the JWS and the JWE.

/cc @brentschmaltz @mafurman

**Comment by brentschmaltz** [comment]
@kevinchalet good idea. I marked this for 6.6.0.

**Comment by brentschmaltz** [comment]
@kevinchalet suggested this a couple of months ago, it would really help extensibility.
Let's get this in 6.7.1

**Comment by brentschmaltz** [comment]
@kevinchalet question is what do we do with this value for Saml tokens?

**Comment by kevinchalet** [comment]
@brentschmaltz sadly, I'm not aware of any equivalent in the marvelous world of SAML, so I'd say... nothing? (just like `TokenValidationParameters.ValidTypes`, that isn't used by the SAML handlers)

**Comment by brentschmaltz** [comment]
@kevinchalet one thought would be use the PropertyName JwtTokenType, then a comment.
Another possibility: JwtSecurityTokenDescriptor, here properties for token specific stuff could live.

First idea seems simplier.

**Comment by kevinchalet** [comment]
It's certainly an option, but is it really worth it? Wouldn't a `TokenType` property be more consistent with `TokenValidationParameters.ValidTypes` that doesn't include `Jwt` in its name?

**Comment by brentschmaltz** [comment]
Yep, overthinking it.
We can cover it in comments.

@kevinchalet thanks for your help.
