### ISSUE TITLE
Warning when building

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#140]
I get the following warning when building.

C:\github\Wilson4K\src\System.IdentityModel.Tokens\project.json(5,37): warning: Dependency specified was Microsoft.IdentityModel.Logging >= 1.0.0-beta4-* but en
ded up with Microsoft.IdentityModel.Logging 1.0.0-t150423000906.

**Comment by tushargupta51** [comment]
@brentschmaltz  Was it fixed after updating to the latest runtime?

**Comment by brentschmaltz** [comment]
@tushargupta51 I just installed 22823.1 with WTE and still see the issue.
