### ISSUE TITLE
issue in error message when no audience field present

### ISSUE THREAD

**Issue by hauntingEcho** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1401]
Currently, I'm receiving the following error message:
```
Error validating identity token: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'System.String'. Did not match: validationParameters.ValidAudience: 'System.String' or validationParameters.ValidAudiences: 'System.String'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at IdentityModel.OidcClient.IdentityTokenValidator.ValidateSignature(String identityToken, JwtSecurityTokenHandler handler, TokenValidationParameters parameters)
   at IdentityModel.OidcClient.IdentityTokenValidator.ValidateAsync(String identityToken, CancellationToken cancellationToken): ArgumentException
[...]
```

When trying to validate a JWT with the payload:
```
{
  "sub": "e1d79921-0795-4111-afee-431b1b411a74",
  "event_id": "431d9076-78a1-4d63-b431-4612c2ddb842",
  "token_use": "access",
  "scope": "openid profile email",
  "auth_time": 1588693872,
  "iss": "[CENSORED]",
  "exp": 1588697472,
  "iat": 1588693872,
  "version": 2,
  "jti": "ba3837df-16d1-48b2-a3e6-ce9aafe1e455",
  "client_id": "[CENSORED]",
  "username": "asdfasdf"
}
```

as there is no audience, [the field should not be validated per the JWT spec](https://tools.ietf.org/html/rfc7519#section-4.1.3).  However, I'm not really able to dig into what's going on without more info from that error message.  It looks like [it's being thrown here.](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f5628e689e97b80fba3efe81fc33903076c97ad5/src/Microsoft.IdentityModel.Tokens/Validators.cs#L126)

**Comment by hauntingEcho** [comment]
This turned out to be a dependency issue - closing this ticket

**Comment by pieteckhart** [comment]
Hi @hauntingEcho,
I am having the same error with the strange "System.String" value.

Can you help me out with what kind of dependency issue resulted in the error?

Thanks

**Comment by hauntingEcho** [comment]
I honestly don't recall - I think it had gone away for me after updating all of my project's dependencies.

**Comment by supertravio** [comment]
I had this issue. Triple check your JWT and confirm that the aud in the jwt is the same as what you've configured. In my case I was using the access token instead of the id token.

Updating project's dependencies didn't help me.

**Comment by joshhanson314** [comment]
For me, I had changed the ResourceApi name and forgot to update the Audience configuration of the API itself. Hope this is useful for others in the future.

**Comment by DaleMckeown** [comment]
For anyone else who might come across this issue in the future, it can also present itself in this manner if the AAD secret does not match.
