### ISSUE TITLE
OpenIdConnect and ASPNET 

### ISSUE THREAD

**Issue by juanan** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1421]
H,

I want to include in my ASPNET (.Net Framework 4.7.2) the protocol OpenIdConnect to authenticate against an Identity Server using a code authorization flow with Pkce.

My question is if I can use your Protocols.OpenIdConnect nuget package because all examples are with ASPNET Core or MVC.

Many thanks.

**Comment by brentschmaltz** [comment]
@juanan pkce is normally used for public clients, https://tools.ietf.org/html/rfc7636. Are you using public clients?

**Comment by juanan** [comment]
Yes, its a public client.

**Comment by brentschmaltz** [comment]
@juanan we don't have turn-key support for this as web servers usually use confidential clients, which require registering a public key with the Identity Server, when redeeming authorization code.

**Comment by juanan** [comment]
ok many thanks.
