### ISSUE TITLE
Microsoft.IdentityModel.Tokens 6.6.0 fails to install with Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.0

### ISSUE THREAD

**Issue by awbmansour** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1422]
Microsoft.IdentityModel.Tokens 6.6.0 fails to install due to compatibility issue with Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.0

The error message is:

Microsoft.IdentityModel.Tokens 6.6.0 is not compatible with Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.0 constraint: Microsoft.IdentityModel.Tokens (>= 5.1.2 && < 6.0.0)

Environment is Visual Studio 2019, an MVC 5 App, .NET 4.7.2

**Comment by brentschmaltz** [comment]
@awbmansour can you please open an issue here: https://github.com/Azure/azure-sdk-for-net
