### ISSUE TITLE
The default token validation does not allow explicitly specifying current time

### ISSUE THREAD

**Issue by onyxmaster** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1430]
The default implementation of token validation [depends on `DateTime.UtcNow`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e4928aff114bf17ee04bd0360b15da6d33694b06/src/Microsoft.IdentityModel.Tokens/Validators.cs#L327) to determine current time. While using `DateTime.UtcNow` as a default is fine and covers most of the production cases, the lack of ability to pass a custom date/time without using fully custom lifetime validator makes functional testing of libraries that depend on this package [unnecessarily](https://www.jerriepelser.com/blog/unit-testing-with-dates/) hard.
I believe that adding a `DateTime? TokenValidationParameters.CurrentTime` would go a long way to alleviate this issue.

**Comment by brentschmaltz** [comment]
@onyxmaster this makes sense and would help testing. For these type of reasons we changed to creating tokens dynamically for tests OR turning lifetime validation off. There are solid reasons for static tokens, such as reference testing, so I agree with such a feature.

**Comment by brentschmaltz** [comment]
@onyxmaster while i agree this would help, given that there is an easy way to make this happen with a delegate.
We decided to punt this.
