### ISSUE TITLE
SamlSerializer fails to validate token using XmlReader created from XDocument

### ISSUE THREAD

**Issue by gislikonrad** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1436]
I have a really obscure bug. The application I'm working on has need for a non-forward-only reader for XML based tokens. When validating these tokens, I'm using the SecurityTokenHandlers from this repository and sending in an XmlReader that is created by XDocument.CreateReader(). The SamlSecurityTokenHandler is unable to use this reader to validate tokens. It fails to read the attributes in the Assertion. This is not a problem in the Saml2SecurityTokenHandler. The problem is because of how the SamlSerializer reads the attributes in a different manner from the Saml2Serializer.

How SamlSerializer reads its attributes:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a9a4da0263cdf28d97056159247618040e8d1f87/src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSerializer.cs#L233

How Saml2Serializer reads its attributes:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a9a4da0263cdf28d97056159247618040e8d1f87/src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2Serializer.cs#L218

**Comment by gislikonrad** [comment]
I have a [repository](https://github.com/gislikonrad/saml-token-validation-error-repro) that contains a reproduction.

**Comment by brentschmaltz** [comment]
@gislikonrad yes, this is a error on our part.
During development of WsTrust, i coded a different solution for attributes.
When time permits, we will integrate this solution.
For now, I think your PR will fix the issue without any side effects.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e019cbea21f186903ad5a17e641d42bb93a856e3/src/Microsoft.IdentityModel.Protocols.WsTrust/XmlAttributeHolder.cs#L32
and: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e019cbea21f186903ad5a17e641d42bb93a856e3/src/Microsoft.IdentityModel.Protocols.WsTrust/WsPolicy/WsPolicySerializer.cs#L85

Thanks!

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1437
