### ISSUE TITLE
Customize RequestedAttribute element (AuthnRequest)

### ISSUE THREAD

**Issue by reponemec** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1446]
Is there a point somewhere in API for adding RequestedAttribute elements into the AuthnRequest element?
I use FederationMetadata.xml emited by STS but that file lacks (I do not know why) important ClaimsTypesOffered/ClaimType elements I need. If I add them into the metadata XML manualy, STS simply ignore them.

It seems a good point could be one of the .W... property of the WsFederationMessage class (https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.protocols.wsfederation.wsfederationmessage?view=azure-dotnet).
If so, I dont know which property I need to use and what string I must write into it.
Outgoing `<AuthnRequest>` element must include `<RequestedAttribute>` elemens as following:
`

	<saml2p:Extensions>
		<eidas:SPType>public</eidas:SPType>
		<eidas:RequestedAttributes>
			<eidas:RequestedAttribute Name="http://eidas.europa.eu/attributes/naturalperson/PersonIdentifier" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
			<eidas:RequestedAttribute Name="http://eidas.europa.eu/attributes/naturalperson/CurrentFamilyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
			<eidas:RequestedAttribute Name="http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
			<eidas:RequestedAttribute Name="http://eidas.europa.eu/attributes/naturalperson/DateOfBirth" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
		</eidas:RequestedAttributes>
	</saml2p:Extensions>`

Complete saml2p:AuthnRequest: [edias_authn_request.zip](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/4763611/edias_authn_request.zip)
More info: [eidas_message_format_v1.0.pdf](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/4763614/eidas_message_format_v1.0.pdf)

**Comment by brentschmaltz** [comment]
@reponemec the library you are referencing is designed for WaSignin scenarios. 
We haven't considered samlp scenarios.
Perhaps @AndersAbel has some help.

**Comment by AndersAbel** [comment]
The [Sustainsys.Saml2](/Sustainsys/Saml2) library supports eidas extensions in the AuthnRequest as well as the required extensions in the SP metadata.

Internally the Sustainsys.Saml2 library uses the Microsoft.IdentityModel libraries for token handling.

**Comment by brentschmaltz** [comment]
@AndersAbel thanks for jumping in.
@reponemec closing for now, please re-open if you need anything else.
