### ISSUE TITLE
DSigSerializer is difficult to override for multiple references

### ISSUE THREAD

**Issue by gislikonrad** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1449]
The ReadSignedInfo method in DSigSerializer calls the ReadReference method once and adds the Reference returned into the References collection. If another reference is available, then ReadSignedInfo throws an exception.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/brentsch/wstrust/src/Microsoft.IdentityModel.Xml/DsigSerializer.cs#L400

If the check for another reference and exception would be moved to a seperate method called ReadReferences, then that method could be easilly overridden to support multiple references.

**Comment by brentschmaltz** [comment]
@gislikonrad you are correct, we designed the serializer for a single reference related to saml tokens and wsfederation metadata.

This is a good suggestion and may open up users to develop support for multiple references.
I labeled this as an enhancement. 

Support multiple references is an undertaking that is a bit complicated and needs to take into the type of the message and the context the message is being read.

**Comment by brentschmaltz** [comment]
@gislikonrad provided a PR for this, but we ran out of time.
Make sure to get in for 6.7.1

**Comment by jennyf19** [comment]
@gislikonrad are you interested in doing a new PR or updating it to target IdentityModel 7 (now the dev branch)? apologies for dropping the ball on this one.

**Comment by gislikonrad** [comment]
I am interested in seeing these changes get merged in. I have to check if I have time to add them again.

**Comment by brentschmaltz** [comment]
@gislikonrad understand, we were focused on Wilson7, now that Wilson7 has been released, we can turn our attention to this issue.
