### ISSUE TITLE
Trouble finding examples for 1.0 tokens and .net framework 4.7.2

### ISSUE THREAD

**Issue by negberts** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1450]
Hi,

We have an Service Fabric application that is now using ADAL and an Angular SPA that call's the API of the service fabric application. The API runs on .net framework 4.7.2. We want to migrate to MSAL.

I have succesfully configured Angular to attach bearer tokens to the API. However, in the API the user is still unauthorized. 

The scope of the token is http://ilionx.onmicrosoft.com/PimLocalSfWebApi/user_impersonation

Migrating to version 2.0 scopes is not an option for now, since we have a lot of customers that would have to update their app registrations in their own tenants. 

The Web API is configured like this in startup.cs:

`ITenantConfigurationRepository tenantRepository = kernel.Get<ITenantConfigurationRepository>();
            List<Models.Tenant> allTenants = tenantRepository.GetAllAsync().Result;
            var validAudiences = allTenants.Select(tenant => tenant.WebApiAppUri).ToList();
            var validIssuers = allTenants.Select(tenant => string.Format("https://sts.windows.net/{0:D}/", tenant.AzureAdTenantId)).ToList();

            var tvps = new TokenValidationParameters
            {
                ValidAudiences = validAudiences,
                ValidIssuers = validIssuers,
                IssuerValidator = IssuerValidator.Validate
            };

            appBuilder.UseOAuthBearerAuthentication(new Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationOptions
            {
                AccessTokenFormat = new JwtFormat(tvps, new OpenIdConnectSecurityTokenProvider("https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"))
            });`

The OpenIdConnectSecurityTokenProvider has the following implementation:

`namespace Pim.ServiceFabricApi
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading;
    using Microsoft.IdentityModel.Protocols;
    using Microsoft.IdentityModel.Protocols.OpenIdConnect;
    using Microsoft.Owin.Security.Jwt;

    /// <summary>
    /// The OpenIdConnectSecurityTokenProvider class.
    /// </summary>
    /// <seealso cref="Microsoft.Owin.Security.Jwt.IIssuerSecurityKeyProvider" />
    public class OpenIdConnectSecurityTokenProvider : IIssuerSecurityKeyProvider
    {
        /// <summary>
        /// The synclock
        /// </summary>
        private readonly ReaderWriterLockSlim synclock = new ReaderWriterLockSlim();

        private readonly string metadataEndpoint;

        /// <summary>
        /// The configuration manager
        /// </summary>
        private ConfigurationManager<OpenIdConnectConfiguration> configManager;

        private string issuer;
        private IEnumerable<Microsoft.IdentityModel.Tokens.SecurityKey> tokens;

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenIdConnectSecurityTokenProvider"/> class.
        /// </summary>
        /// <param name="metadataEndpoint">The metadata endpoint.</param>
        public OpenIdConnectSecurityTokenProvider(string metadataEndpoint)
        {
            this.metadataEndpoint = metadataEndpoint;
            this.configManager = new ConfigurationManager<OpenIdConnectConfiguration>(metadataEndpoint, new OpenIdConnectConfigurationRetriever());

            RetrieveMetadata();
        }

        /// <summary>
        /// Gets the issuer the credentials are for.
        /// </summary>
        /// <value>
        /// The issuer the credentials are for.
        /// </value>
        public string Issuer
        {
            get
            {
                RetrieveMetadata();
                synclock.EnterReadLock();
                try
                {
                    return issuer;
                }
                finally
                {
                    synclock.ExitReadLock();
                }
            }
        }

        /// <summary>
        /// Gets all known security tokens.
        /// </summary>
        /// <value>
        /// All known security tokens.
        /// </value>
        public IEnumerable<Microsoft.IdentityModel.Tokens.SecurityKey> SecurityKeys
        {
            get
            {
                RetrieveMetadata();
                synclock.EnterReadLock();
                try
                {
                    return tokens;
                }
                finally
                {
                    synclock.ExitReadLock();
                }
            }
        }

        private void RetrieveMetadata()
        {
            synclock.EnterWriteLock();
            try
            {
                OpenIdConnectConfiguration config = configManager.GetConfigurationAsync().Result;
                issuer = config.Issuer;
                tokens = config.SigningKeys.ToList();
            }
            finally
            {
                synclock.ExitWriteLock();
            }
        }
    }
}`

All calls are receiving a 401 unauthorized error and ClaimsPrincipal.Current.Identity is always empty.

What am I missing? Is there any documentation for my scenario? (1.0 tokens and .NET framework) Help would be appriciated.

**Comment by jmprieur** [comment]
@negberts, I propose you try the scope `http://ilionx.onmicrosoft.com/PimLocalSfWebApi/.default` (see the other thread)

**Comment by brentschmaltz** [comment]
@jmprieur @negberts I don't think this is an IdentityModel issue and perhaps should be opened in https://github.com/AzureAD/microsoft-identity-web 

@negberts the following code could cause a deadlock, you should add ConfigureAwait(false).
OpenIdConnectConfiguration config = configManager.GetConfigurationAsync().Result;
