### ISSUE TITLE
Should AuthnContextClassRef  be required?

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1457]
The zero parameter constructor for Saml2AuthenticationContext passes null as a ClassReference.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2AuthenticationContext.cs#L56

ClassReference does not accept a null value

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2AuthenticationContext.cs#L104

Saml2Core, 2.7.2.2 lists AuthnContextClassRef as optional. Is there a reason behavior deviates from Saml2Core? Is there an overriding errata? The zero parameter constructor should either be removed or the ClassReference property should accept null depending on the answer

**Comment by brentschmaltz** [comment]
@keegan-caruso I agree with you that the constructor makes little sense, but it would be breaking to remove it. Users could new one up and set the correct parameters and everything would work.

When we serialize or deserialize, we do the right thing.

**Comment by keegan-caruso** [comment]
@brentschmaltz  not sure I follow

```cs
var authContext = new Saml2AuthenticationContext()
{
    ClassReference = new Uri(uriValue, UriKind.Absolute)
};
```

Will fail as the ClassReference will only be set after the ctor runs. I'm not sure that anyone could have actually used the ctor without hitting an error condition. Removing might be the wrong route still, agreed. If ClassReference should actually be required to be non-null maybe we should at least mark that ctor as deprecated to be able to given compile time warnings?

**Comment by brentschmaltz** [comment]
@keegan-caruso you are correct, in fact this constructor (public Saml2AuthenticationContext(Uri classReference)) could not be used either

I agree with marking both as deprecated, but am reluctant to take a breaking change.
Only if someone was using it for testing.
