### ISSUE TITLE
JwtPayload uses current culture to parse claim values

### ISSUE THREAD

**Issue by gislikonrad** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1467]
Running the tests in the solution on my machine (I live in Iceland), the [RoundTrip ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/0567929e7c7f4a299925f16a26d43ad5f8c60dc1/test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs#L211) tests fail because of the value of the **ClaimValueTypes.Double** claim. This is due to the value of **123.4** being changed to **1234** when it's being parsed from string using the **is-IS** culture. I'm sure other cultures could have this error aswell.

**Comment by brentschmaltz** [comment]
@gislikonrad thanks, we will fix this up.

**Comment by brentschmaltz** [comment]
@gislikonrad  fixed with: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/8433d584bf3890894fd9b8f3ceef156d0e16e47a
