### ISSUE TITLE
IDX10511: Signature validation failed. Keys tried: 'System.Text.StringBuilder'

### ISSUE THREAD

**Issue by DariusFaison** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1471]
`JwtValidator.ValidateJwtToken(header.Parameter, cancellationToken).GetAwaiter().GetResult();`

Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException
  HResult=0x80131500
  Message=IDX10511: Signature validation failed. Keys tried: 'System.Text.StringBuilder'
kid: 'System.String'. 
Exceptions caught:
 'System.Text.StringBuilder'.
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
  Source=WebRole1
  StackTrace:
   at WebRole1.Controllers.ValuesController.Get() in C:\Users\t-dafais\source\repos\AzureSample\WebRole1\Controllers\ValuesController.cs:line 35
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by brentschmaltz** [comment]
@DariusFaison i take it you would like to see a better message?

**Comment by brentschmaltz** [comment]
@DariusFaison this is related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1427
where we wrote: 
"
We recognize the need to adjust this for an application that is running.
We have these issues that address this:
#1274

#1452

If you would like us to consider these in next months release, please put a mark on those issues.
"

**Comment by wenx1** [comment]
I got this error as well. Could someone give more information what does this exception mean? 
`Signature validation failed. Keys tried: 'System.Text.StringBuilder'`

**Comment by brentschmaltz** [comment]
@DariusFaison there should be number IDxxxxxxx associated with this error.
By default, we filter exceptions and only show the type rather than the contenst.

If you want to see all details of the exception then you need to turn on PII see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/ca833866cc3091ea115125c3600d903cda539e74/src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs#L60

**Comment by Kurayami7** [comment]
What was the fix for this? Has this been resolved? I am facing this issue.
