### ISSUE TITLE
SecurityTokenDescriptor Audience is a string, but is should be an array of strings.

### ISSUE THREAD

**Issue by nikosft** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1479]
The [Audience property of the SecurityTokenDescriptor ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.securitytokendescriptor.audience?view=azure-dotnet#Microsoft_IdentityModel_Tokens_SecurityTokenDescriptor_Audience) is of type String. However it should by an array.

Copying pasting from rfc7519 section-4.1

> in the general case, the "aud" value is an array of case sensitive strings, each containing a StringOrURI value.  In the  special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value

**Comment by brentschmaltz** [comment]
@nikosft yep, we will have to add an API similar to TokenValidationParameters.ValidAudiences as we want to avoid breaking changes.

**Comment by jmprieur** [comment]
Design:
- Add a new property named "Audiences" of type IList<string>
- process it in the token creation.
