### ISSUE TITLE
nuspec file missing from microsoft.identitymodel.protocols.openidconnect 5.5.0

### ISSUE THREAD

**Issue by graphicsxp** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1484]
it's all in the title. I'm getting the error :

´C:\Program Files\dotnet\sdk\3.1.301\NuGet.targets(128,5): error NU5037: The package is missing the required nuspec file. Path: \.nuget\packages\microsoft.identitymodel.protocols.openidconnect\5.5.0  `

the nuspec file is indeed missing from the package. Can this be fixed ?

**Comment by GeoK** [comment]
Hi @graphicsxp - I just downloaded [Microsoft.IdentityModel.Protocols.OpenIdConnect 5.5.0](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/5.5.0), and I see _Microsoft.IdentityModel.Protocols.OpenIdConnect.nuspec_ file in the package.

The solution for scenario 2 might fix your issue:
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5037#scenario-2

**Comment by graphicsxp** [comment]
ok, this is so weird. I definitely had 5.5.0 installed and the nuspec was missing.
However after clearing all the packages in cache, now the package contains the nuspec. I can't explain that but my project builds...

**Comment by GeoK** [comment]
Awesome, I'm closing the issue.
