### ISSUE TITLE
Consider making issue templates

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1486]
It would be helpful for issue reporters and maintainers if the repository adopted issue templates.

An example from identity-web:
https://github.com/AzureAD/microsoft-identity-web/tree/master/.github/ISSUE_TEMPLATE

An example from aspnetcore:
https://github.com/dotnet/aspnetcore/tree/master/.github/ISSUE_TEMPLATE

Docs [link](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#:~:text=%20Creating%20issue%20templates%20%201%20On%20GitHub%2C,it%20to%20the%20repository%2C%20click%20Preview...%20More%20)

**Comment by jennyf19** [comment]
done.
