### ISSUE TITLE
How to change the kid value from thumbprint to public key finger print?

### ISSUE THREAD

**Issue by rudeGit** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1504]
The X509SigningCredentials class (via the base SigningCredentials) class defaults the Kid value to thumbprint of the certificate. When interacting with the non-dotnet world, they typically expect the kid value of the signing certificate to be public key finger print value.

There appears to be not a clean way to set the Kid value to other than what is provided.

Is there a way to do this while leveraging the X509SigningCredentials class?

**Comment by rudeGit** [comment]
This turned out to be rather simple. The following did the trick:

```
var signingCredentials = new X509SigningCredentials(certificate, algorithm);
var securityKey = signingCredentials.Key as X509SecurityKey;
securityKey.KeyId = "Yadda";
```

It had no effect on the signature computation but the output kid value was set to "Yadda" and I was able to verify the signature successfully.

**Comment by brentschmaltz** [comment]
@rudeGit glad you figured it out.
You could also write:
```
var signingCredentials = new SigningCredentials(new X509SecurityKey(certificate){KeyId= "Yadda-Yadda"}, algorithm);
```
