### ISSUE TITLE
Add Target 4.7.2

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1507]
With 4.7.2, we will be able to move the adapters for RSA and ECD for just 461 and 45.

For this issue, we can open up Creating a JsonWebKey from EC key.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1317

**Comment by HarmanDhunna** [comment]
Hi all, would love to see this feature!
