### ISSUE TITLE
Unable to add "sub" claim to JWT token.

### ISSUE THREAD

**Issue by vllama** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1510]
While migrating an asp.net  project to .net core  I have ran across the following issue:

when building a token using the following code:
```
//...
			var claims = new ClaimsIdentity(additionalClaims);
//...
			var tokenDescriptor = new SecurityTokenDescriptor {
				Audience = "https://localhost:44369",
				Issuer = "https://localhost:44369",
				Subject = claims ,
				Expires = DateTime.UtcNow.AddHours(_tokenConfig.TimeoutHours),
				SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(_tokenConfig.Key), SecurityAlgorithms.HmacSha256Signature)
			};
			
			//Token specific claims
			tokenDescriptor.Subject.AddClaim(new Claim(ClaimTypes.Name, user.Email, ClaimValueTypes.String));
			tokenDescriptor.Subject.AddClaim(new Claim("my.random.claim", user.Email));   
			tokenDescriptor.Subject.AddClaim(new Claim("sub", user.Email));   
	
			var token = tokenHandler.CreateJwtSecurityToken(tokenDescriptor);
```

the line : `tokenDescriptor.Subject.AddClaim(new Claim("sub", user.Email));`   has no effect.

Then in the controller action:

```
if (User is ClaimsPrincipal claimsUser) {
	string email = claimsUser.Claims.Where(c => c.Type == "sub").Select(c => c.Value)
	  .SingleOrDefault();
}
```
All other defined claims from above are present in claimsUser.Clamis, except for **"sub"**.

I noticed that in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/05e02b5e0383be40e45c667c12f6667d38e33fcc/src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs#L50
```
{ JwtRegisteredClaimNames.NameId, ClaimTypes.NameIdentifier },
 { JwtRegisteredClaimNames.Sub, ClaimTypes.NameIdentifier },
```
both  RegisteredClaimNames are mapped to the same ClaimType, so in the reversed dictionary only the first one will be present, but I'm not sure that means anything.

**Comment by brentschmaltz** [comment]
@vllama I believe you are experiencing "claimMapping".
Inbound the JwtSecurityTokenHandler uses this mapping: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/93334a8e94e66d3df36f2850a03549ed1bfd4234/src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs#L41, you should find a claim of type ClaimTypes.NameIdentifier. There will be a property on the claim with the short name sub.

You can turn this off by setting: JwtSecurityTokenHandler.DefaultMapInboundClaims = false, in your startup code.
There are other ways to do the same thing.

**Comment by vllama** [comment]
Thanks, I was able to modify the library that was looking for sub in the meantime to use the NameId, so that worked as well.

**Comment by brentschmaltz** [comment]
@vllama as a note the JsonWebTokenHandler has similar functionality as the JwtSecurityTokenHandler but does not perform any mapping.
