### ISSUE TITLE
Verifying a token signature using the public key (RS512)

### ISSUE THREAD

**Issue by lsiano** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1512]
Hello,

I have a signed jwt token (rs512) and its public key

I need to create code that verify if the signature its valid or not.

Can I do that with this library?
I haven't found much on the forums regarding the issue I'm facing

**Comment by mafurman** [comment]
Assuming I'm understanding your question correctly, you'll want to use the JsonWebTokenHandler.ValidateToken(string token, TokenValidationParameters validationParameters) API. You should be able to provide your public key on the TokenValidationParameters.IssuerSigningKey.

**Comment by brentschmaltz** [comment]
@lsiano let us know if you have any additional issues.
