### ISSUE TITLE
Add a WsTrustChannelFactory for getting a SecurityToken using WsTrust

### ISSUE THREAD

**Issue by gislikonrad** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1513]
Now, since there is work ongoing with WsTrust message serialization/deserialization, it would be good to get a WsTrustChannelFactory for the raw communication to a WsTrust server.

**Comment by brentschmaltz** [comment]
@gislikonrad this would be a good feature and would help us with a wstrust client.
Not sure where it fits in.

**Comment by brentschmaltz** [comment]
@gislikonrad this has been moved to WCF repo and is being completed.
see: https://github.com/dotnet/wcf and there is a current pull request.
