### ISSUE TITLE
Rapid Identity - at_hash

### ISSUE THREAD

**Issue by lmlearn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1519]
Hi,
I have been working with Rapid Identity; one of the scenarios we encountered is the at_hash claim.
The Rapid IDP at_hash has a base64url encoded padding. i.e. "==" at the end of the string.
Where as most of the IDP; like microsoft, google, okta, Auth0 don't have the padding in the token for validation.

Following is the code which validates the at_hash: 

**In class file:**

**Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator**

private static void CheckHash(HashAlgorithm hashAlgorithm, string expectedValue, string hashItem, string algorithm)
        {
            var hashBytes = hashAlgorithm.ComputeHash(Encoding.ASCII.GetBytes(hashItem));
            var hashString = Base64UrlEncoder.Encode(hashBytes, 0, hashBytes.Length / 2);
            if (!string.Equals(expectedValue, hashString, StringComparison.Ordinal))
            {
                throw LogHelper.LogExceptionMessage(new OpenIdConnectProtocolException(LogHelper.FormatInvariant("IDX21300", expectedValue, hashItem, algorithm)));
            }
        }

We should take care of the padding during validation as well. 

Regards,
Babu

**Comment by brentschmaltz** [comment]
@iambmelt are you saying the at_hash contains '==' as a postfix?
Are you asking us to remove the '==' if we see it?

**Comment by iambmelt** [comment]
> @iambmelt are you saying the at_hash contains '==' as a postfix?
> Are you asking us to remove the '==' if we see it?

Think I was accidentally tagged, @lmlearn ^^

**Comment by kevinchalet** [comment]
FYI the OIDC spec is crystal clear about the fact the `at_hash` is base64url-encoded (and not base64-encoded):

> OPTIONAL. Access Token hash value. Its value is the base64url encoding of the left-most half of the hash of the octets of the ASCII representation of the access_token value, where the hash algorithm used is the hash algorithm used in the alg Header Parameter of the ID Token's JOSE Header. For instance, if the alg is RS256, hash the access_token value with SHA-256, then take the left-most 128 bits and base64url encode them. The at_hash value is a case sensitive string.

Isn't that something your identity provider should fix on their side?

**Comment by brentschmaltz** [comment]
@kevinchalet @lmlearn yes that is correct about base64url encoding. We would not be willing to remove any chars from the at_hash.
I agree with @kevinchalet these characters should not be there.

There is extensibility for you to work around this issue here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/92580d7f1a3027c6f400cc11be46d9e061dedea2/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L566

Asp.net provides a way for you to use your own OpenIdConnectProtovolValidator.

**Comment by lmlearn** [comment]
HI All,
Thanks for the comments and suggestions; 
My suggestion was 
1. Check for at_hash with existing algo; if it fails for at_hash
2. Add the postfix "==" and check for the at_hash algorithm
If both fails we can consider the the validation failed.

Currently since the extension was provided; we are using the out of the box validation; and if it fails we added "==" to validate again. If both fails we consider to be at_hash failure.

The current algorithm is according to OAuth Standards;

Regards,
Babu
