### ISSUE TITLE
Claims list for JWT is incorrect in Mono 4.0.1

### ISSUE THREAD

**Issue by ryan1234** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#152]
This function, https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L654, returns the wrong list of claims in Mono 4.0.1.

Trying to debug on my own why, but hoping to get ideas.

For example, when I process a JWT on Windows, I get back 12 claims. This is correct. On OS X with Mono 4.0.1 I get 10 claims with the same JWT. 

Specifically the "scope" claim comes in as an array in the JWT and Windows will decompose that into several claims, while OS X keeps it as an array.

**Comment by tushargupta51** [comment]
Fixed in #161
