### ISSUE TITLE
Intermittently getting .”SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed”  on  Service deployed on AKS using Azure AD B2B client credential tokens

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1523]
We have deployed our services on - AKS aks version 1.16.9.  Our services have been developed using a wrapper library to authenticate token which internally uses Microsoft.Identity.Model.Token to validate the token. In most scenarios it works perfectly fine.  It has been configured to accept azure adb2c tokens as well as azure ad client credential tokens.
Once in a while (around 1 a month)  we are getting the error only when we use the azure adb2b client credential token. The same library works perfectly fine azure ad b2c tokens. 
```
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: ‘’
Exceptions caught:
 ''
```
Please note the exception caught is empty.  We have checked the kid of the token and Azure Ad B2B metadata endpoint  match.
After we get the error we continuously get the error till the pod is restarted . Once we recreate the pod  the exception vanishes

This is the version of the components we are using
BouncyCastle.NetCore - Version="1.8.5"
Microsoft.IdentityModel.Tokens =  Version="5.5.0"
Microsoft.IdentityMode 7.0.0"
Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.3"
System.Runtime" Version="4.3.0"

This is a snippet of the code we are using
```
static Microsoft.IdentityModel.Tokens.TokenValidationParameters TokenValidationParameters(AppConfig appConfig)
{
    var audiences = new List<string> {'audience1', 'audience2'};
    var issuers = new List<string> {'b2c', 'ad', 'auth0', 'identityserver'};
    var discoveryendpoints = new List<string> {'b2c meta url', 'ad meta url', 'auth0 meta url', 'identityserver meta url'};
    Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration openIdSigningConfigs = new Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration();
    foreach (var discoveryendpoint in discoveryendpoints)
    {
        Microsoft.IdentityModel.Protocols.ConfigurationManager<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration> configManager = new Microsoft.IdentityModel.Protocols.ConfigurationManager<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>(discoveryendpoint, new Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever());
        Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration config = configManager.GetConfigurationAsync().Result;
        foreach (var item in config.SigningKeys)
        {
            openIdSigningConfigs.SigningKeys.Add(item);
        }
    }
    var tvps = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
    {
        ValidateAudience = true,
        ValidateIssuer = true,
        ValidateLifetime = true,
        ValidAudiences = audiences,
        ValidIssuers = issuers,
        IssuerSigningKeys = openIdSigningConfigs.SigningKeys
    };
    return tvps;
}

 services.AddAuthentication(Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme) 
    .AddJwtBearer( 
    options => 
    { 
    options.TokenValidationParameters = TokenValidationParameters(tokenconfig); 
    });

**Comment by GeoK** [comment]
Hi @rsrinivasanhome - It seems like your code doesn't refresh signing keys when a key rollover happens. That would explain why you are seeing this issue (~once a month), and why the issue goes away when you restart the pod (it picks up new config).

**Comment by rsrinivasanhome** [comment]
My understanding is the keys change every day and the library we are using
should be taking care of rotating the keys. We have seen the same code work
perfectly fine with azure ad b2c tokens.

**Comment by rsrinivasanhome** [comment]
@GeoK  when the exception was logged we could see the kind .  The kind was the latest and the same as the value retrieved from the meta data end point.  Even if we use a new token the issue would persist.

**Comment by brentschmaltz** [comment]
@rsrinivasanhome how / when is 'tokenconfig' created?

**Comment by rsrinivasanhome** [comment]
The tokenconfig is stored in Kubernetes secrets and azure key vaults.  While analyzing the issue we found the Kubernetes pods were running fine for around 50 days without restarting. So token config is created well before deploying the pods.  This data is rather static and has not changed in a very long time.

**Comment by rsrinivasanhome** [comment]
One point to note when the issue occurred it effected all pods at the same time.  When we recreated the pods the issue stopped.

**Comment by rsrinivasanhome** [comment]
Please guide us how this issue can be resolved.

**Comment by brentschmaltz** [comment]
@rsrinivasanhome JwtBearerHandler will automatically call into Options.ConfigurationManager: GetConfigurationAsync() and RequestRefresh() if Options.ConfigurationManager is set.

Options.ConfigurationManager will be set automatically if the metadata or authority is passed to JwtBearerOptions in startup. However, in your case you want to have control over populating TVP. 

To trigger a refresh, you should set JwtBearerOptions.ConfigurationManager and generate the keys with the same code you have in the extension.

Please let us know if you have other questions.

**Comment by rsrinivasanhome** [comment]
During the startup we are calling a wrapper api to configure the signing keys. We have been using the same code for b2c end points and never faced an issue.  Why does this happen only when we are using b2b tokens - azure b2b client credential ?
