### ISSUE TITLE
Plans for adding .NET Core / NET5 targets

### ISSUE THREAD

**Issue by Scooletz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1524]
Hi,

This is not an issue, but rather an open question. If there's a separate channel for it, I'm happy to move this conversation elsewhere. If found the mention in readme about [community](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#community-help-and-support) but this is an open question, so I think it's better to write it here.

Yesterday I hosted [a webinar](https://www.youtube.com/watch?v=bSnjrlmTdnE) with @marcinhoppe which inspired me to dive into JWT implementation that is used by aspnetcore. As far as I understand this is the repository that is used underneath with its `JwtSecurityTokenHandler`. I noticed that currently, this are the supported targets:

- net45;
- net461;
- netstandard2.0

Are there any plans to add more, especially .NETCore or NET5 targets? I briefly took a look at implementation behind `JwtSecurityTokenHandler` and it looks like there's some potential for spanninfication for performance reasons. I'm aware that there are some degrees of spanification, whether or not introduce it in the API or just use it in the implementation itself, but with an additional target this seems potentially doable.

**Comment by keegan-caruso** [comment]
Hello,

We have this enhancement open to track this work

#1426

**Comment by Scooletz** [comment]
Lovely! I'll watch the issue you mentioned @keegan-caruso and closing this one. Thank you!
