### ISSUE TITLE
[Proposal] PII Filtering enchancement

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1527]
The filtering of PII is a frequently confusing topic for users of this library. Filtering everything or nothing isn't always an easy choice. Additionally, it would be an improvement to allow changes to this at runtime

What I suggest is introducing a new interface with a single method of or similar to:

```cs
ShouldRemovePII(string format, params object[] args)
```

As a property to IdentityModelEventSource.

And providing a default implementation that does a prefix match on the format string against a collection of allowed prefixes.

This would give a usage pattern of something similar to:

```cs
IdentityModelEventSource.LogFilter = new PrefixLogFilter
{
    Prefixes = new List<string> { "IDX20106:", "IDX20803" }
}
```

In net core, an implementer would have a clean path to change logging based on an IOptionsMonitor at that point. Similar behavior can be achieved in net framework (as an example, via an IConfigurationManager). Implementations should be thread safe between updates to their configuration and Filtering calls

**Comment by brentschmaltz** [comment]
@keegan-caruso what about if users could hook a delegate to get the exception message before we filtered it?

**Comment by keegan-caruso** [comment]
@brentschmaltz good point. I think that is also something we should look at and is in line with current APIs in this library.

That would give a path forward to hook up runtime log filtering based on an IOptionsMonitor with implementing only a delegate.

**Comment by brentschmaltz** [comment]
We are working on a updated model in this PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1725
