### ISSUE TITLE
Migration document doesn't have clear documentation on breaking changes from 4.x to 5.x 

### ISSUE THREAD

**Issue by DhivyaG19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1528]
Migration document doesn't have clear documentation on breaking changes from 4.x to 5.x . For example , this documentation doesn't have information about that IssuerSigningTokens in 4.x is replaced with IssuerSigningKeys in 5.x.

The [migration notes](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#usage) here links to [this page](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/513#issuecomment-252789227).
Please update the document with the breaking changes.

**Comment by GeoK** [comment]
Hi @DhivyaG19, are you migrating from Katana (Owin) 3x? Perhaps you'll find [this page](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Migrating-from-Katana-(OWIN)-3.x-to-4.x) to be helpful.

There is a lot of breaking changes in 5x (4x had only two assemblies and 5x has 10+), and 4x is not supported anymore. Is there anything specific that you would like to see in our migration docs?

**Comment by brentschmaltz** [comment]
@DhivyaG19 there are no other breaking changes from 4.x to 5.x then in our wiki.
If you have a specific issue, please let us know.
