### ISSUE TITLE
WsSecuritySerializer namespace should not write all elements and attributes with WS-Security 1.1 xmlns

### ISSUE THREAD

**Issue by gislikonrad** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1531]
I've been testing out the WS-Trust package from the brentsch/wstrust branch. One thing that I came accross is that when I'm using Trust 1.3 and I need to write a SecurityTokenReference, it's written using the WS-Security 1.1 xmlns. After looking through the code, this is true for WS-Trust 1.4 aswell.

WS-Security 1.1 specifies that all elements that were present in WS-Security 1.0 should be written using the 1.0 xmlns. There are actually only three XML entities in the WS-Security 1.1 spec that are required to be written using the WS-Security 1.1 xmlns.

1. The TokenType attribute
    - This is actually hard-coded when writing the SecurityTokenReference 
1. The SignatureConfirmation element
1. The EncryptedHeader element

All other XML entities that belong in the WS-Security 1.1 spec should be written with the WS-Security 1.0 xmlns. 

My source is [this pdf](https://www.oasis-open.org/committees/download.php/16790/wss-v1.1-spec-os-SOAPMessageSecurity.pdf) from oasis. All examples of elements and attributes are either prefixed with wsse or wsse11 which reference the WS-Security 1.0 and WS-Security 1.1 xmlns's respectively.

@brentschmaltz IMO, the WsSecuritySerializer should write all WS-Security XML entities, other that the three mentioned above, using the 1.0 xmlns. The three entities above should only be written if the WsSerializationContext has been set up to use WS-Security 1.1.

**Comment by gislikonrad** [comment]
I have tried using requests serialized using this library on an ADFS STS and a PingFederate STS and they both fail. If I write the SecurityTokenReference manually with the WS-Security 1.0 xmlns, it works.

**Comment by gislikonrad** [comment]
#1532 addresses this issue.

**Comment by brentschmaltz** [comment]
@gislikonrad will get this fixed for our WSTrust release.

**Comment by brentschmaltz** [comment]
@gislikonrad  fixed in this commit: 241e5f8374b8f4a7a53e44d6af87bf0b91410c50

**Comment by gislikonrad** [comment]
@brentschmaltz Was commit 241e5f8 orphaned? It says it doesn't belong to any branch in this repo.
