### ISSUE TITLE
Remove locks from SymmetricSignatureProviders and AsymmetricSignatureProviders

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1534]
Locking inside a signature provider can result in contention when multiple threads are using the same signature provider.
If signature caching is on AND multiple threads are in use, performance will be reduced.

Use an ObjectPool for:
1. AsymmetricSignatureProvider: AsymmetricAdapter
2. SymmetricSignatureProvider: KeyedHashAlgorithm

AsymmetricAdapter is internal, no additional apis will be needed for release.
SymmetricSignatureProvider has a virtual for creating the KeyedHashAlgorithm. This requires adding 'ReleaseKeyedHashAlgorithm'.

**Comment by keegan-caruso** [comment]
@brentschmaltz are there any other updates here or is this one ready to close?

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/00d4602f1eebbf42ec78cca66d8e59d9b7e892cc
