### ISSUE TITLE
Documentation for lifetime of `SecurityKey` asymmetric algorithms?

### ISSUE THREAD

**Issue by vcsjones** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1539]
In `dotnet/runtime` [there was a report][1] that `RSA` was not behaving as expected. The issue amounted to using an instance of `RSA` to `RsaSecurityKey`, which resulted in the `RSA` instance being put in `InMemoryCryptoProviderCache`. However, the `RSA` object was disposed of by the developer while it was in the cache, thus a subsequent validation using a different instance of an `RSA` object but for the same key would produce an error.

Is there documentation about expectations of the lifetime of `AsymmetricAlgorithm` instances when they are used with `SecurityKey`? 

[1]: https://github.com/dotnet/runtime/issues/43087

**Comment by brentschmaltz** [comment]
@vcsjones you are correct, if you pass an RSA object to the RsaSecurityKey AND caching is on, then a reference will be maintained. If in the meantime, you dispose of the RSA, there will be an issue.

Marked this bug as documentation.

**Comment by mafurman** [comment]
Adding documentation on this here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Caching-in-Microsoft.IdentityModel

**Comment by vcsjones** [comment]
@mafurman thank you!
