### ISSUE TITLE
ValidateIssuer TokenValidationParameters is ignored when validating a JWT without an issuer

### ISSUE THREAD

**Issue by attila-s** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#154]
I am using the following NuGet package to validate JSON Web Tokens.

Id: System.IdentityModel.Tokens.Jwt Version: 4.0.2.202250711

Tokens are signed by applying HS256.

However, using JwtSecurityTokenHandler's validateToken method, the token can only be validated if it contains an issuer claim ('iss') even if ValidateIssuer = false in the TokenValidationParameters.

The following ArgumentException is thrown:

Additional information: *IDX10221: Unable to create claims from securityToken, 'issuer' is null or empty. According to the [working draft of JSON Web Token (JWT) RFC](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32) issuer is not required for validating tokens, so this behavior is strange.*

As a workaround, I can create a custom subclass and override the ValidateSignature method so that it adds iss claim to the token if issuer is not present, but I believe it shall not be considered as an acceptable solution.

```csharp
class CustomJwtSecurityTokenHandler : JwtSecurityTokenHandler
{
    protected override JwtSecurityToken ValidateSignature(string token,
        TokenValidationParameters validationParameters)
    {
        var jwt = base.ValidateSignature(token, validationParameters);
        if (String.IsNullOrEmpty(jwt.Issuer))
        {
            jwt.Payload.AddClaim(new Claim(&quot;iss&quot;, &quot;default&quot;)); // this is a hack
        }
        return jwt;
    }
}
```

Can you confirm this is a bug?

Example JWT: 
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.rYCxfe5xe8m2H6SjCIj7axcoPm0Z5LYJXyjmt7qyLXM"

that corresponds to

{ "alg": "HS256", "typ": "JWT" }.{ "sub": "1234567890", "name": "John Doe",
"admin": true }. HMACSHA256( base64UrlEncode(header) + "." + base64UrlEncode(payload), qwertyuiop123456)

secret: qwertyuiop123456

Here is a sample program to reproduce the issue:
```csharp
using System.IdentityModel.Tokens;
using System.ServiceModel.Security.Tokens;
using System.Text;

namespace JWT { internal class Program {

    private static void Main(string[] args)
    {
        var jwtIssuer = "MyIssuer";
        var jwtAudience = "no_audience";;
 
        var validationParams = new TokenValidationParameters()
        {
            ValidateLifetime = false,
            ValidAudience = jwtAudience,
            ValidIssuer = jwtIssuer,
            ValidateIssuer = false,
            ValidateAudience = false,
            IssuerSigningToken = new BinarySecretSecurityToken(Encoding.ASCII.GetBytes("qwertyuiop123456"))
        };
 
        var jwtOnTheWire =
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.rYCxfe5xe8m2H6SjCIj7axcoPm0Z5LYJXyjmt7qyLXM";
 
        SecurityToken validatedToken;
 
        var handler = new JwtSecurityTokenHandler();
        handler.ValidateToken(jwtOnTheWire, validationParams, out validatedToken);
 
    }
}
}
```

**Comment by brentschmaltz** [comment]
I would recommend using TokenValidationParameters.IssuerValidator delegate rather than adding to the Payload.
http://openid.net/specs/openid-connect-core-1_0.html#IDToken
indicates that 'iss' is required, which is the reason for the default behavior.

When a ClaimsIdentity is created, the Issuer property cannot be null or just whitespace, so your delegate will need to return a value where string.IsNullOrWhiteSpace is false.

**Comment by dsfields** [comment]
The JWT class library being defined here is confusing.  Semantically, the library is implying that it is for parsing and validating JSON Web Tokens.  However, all of the claims validation being performed is a part of the OAuth standard.  There are no requirements that JWTs are to be exclusively used by OpenID Connect/OAuth.

I think this API needs to more clearly define that it is for consuming JWTs generated as part of a OAuth conversation.  However, I think that limits its usefulness, as not everyone using JWTs are using them for OAuth.

**Comment by brentschmaltz** [comment]
That is a fair comment. It is the OpenIdConnectProtocolValidator that needs to ensure the existence of the 'iss' claim.

http://tools.ietf.org/html/rfc7519#section-4

**Comment by brentschmaltz** [comment]
If this wasn't fixed in 5.x can you fix it or close it if it is fixed.

**Comment by tushargupta51** [comment]
Fixed in 5.x

**Comment by tushargupta51** [comment]
@brentschmaltz Are we planning to fix it in 4.x too? I saw the label, just wanted to confirm.

**Comment by brentschmaltz** [comment]
Yea we should fix in 4.x

**Comment by Tydude4Christ** [comment]
Please fix this in 4.x. I just got bit by this and have instead implemented the suggested CustomJwtSecurityTokenHandler workaround. Thanks.

**Comment by brentschmaltz** [comment]
@Tydude4Christ were are just planning out the release. Will let you know.

**Comment by Tydude4Christ** [comment]
@brentschmaltz Thanks, I look forward to it.
