### ISSUE TITLE
Base64UrlEncoder doesn't have '=' padding

### ISSUE THREAD

**Issue by aryamsft** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1546]
Hello, I'm using Docker Rest API's for our work and the API specifies I have to use base64url encoding [Docker Auth API](https://docs.docker.com/engine/api/v1.40/#section/Authentication).

I want to use this nuget package to do so but I noticed that the encoding doesn't have the '=' padding at the end, which causes authentication with Azure Container Registry to fail.  When the '=' is added at the end, authentication succeeds.

Why isn't the '=' added to the encoding?  Is there an option to end it via an API?  If not, can that option be added?

Or, is it Azure Container Registry/Docker that are mistaken to require the '=' padding for Base64UrlEncoding?

**Comment by brentschmaltz** [comment]
Base64Encoding is slightly different than Base64UrlEncoding, which does not have the padding characters: "==" and "=".
see: https://brockallen.com/2014/10/17/base64url-encoding/

**Comment by aryamsft** [comment]
@brentschmaltz There seems to be a disconnect in implementations then.

GoLang's implementation of base64.URLEncoding.EncodeToString() adds a '=' to the end of the encoding, as follows:

```
encodedDocker := base64.URLEncoding.EncodeToString(authMarshalJson)
```

You can specify not to add padding at the end this way:

```
encodedDocker = base64.URLEncoding.WithPadding(base64.NoPadding).EncodeToString(authMarshalJson)
```

If you look at the [Docker CLI Source code](https://github.com/docker/cli/blob/f8696535e9e516a5a404661697fef6f1228ada64/cli/command/registry.go) they use just EncodeToString().

Without the extra padding at the end, authentication with Azure Container Services doesn't work.

I'm also seeing some people online implement it with or without padding.

Without:  https://base64.guru/standards/base64url/encode
With:  https://simplycalc.com/base64url-encode.php

There is a thread about this issue here:  https://github.com/moby/moby/issues/41570

**Comment by Tratcher** [comment]
The padding is offically optional when using base64urlencoding, and it's better to exclude it in many context to avoid additional encodings.

https://tools.ietf.org/html/rfc4648#section-5
   The pad character "=" is typically percent-encoded when used in an
   URI [9], but if the data length is known implicitly, this can be
   avoided by skipping the padding; see section 3.2.

So that would mean the issue is with Azure Container Services not being able to handle the un-padded format.

**Comment by aryamsft** [comment]
Ok, let me contact ACR and see what they say.

**Comment by aryamsft** [comment]
Here is the response I got from ACR:

> The APIs you’ve mentioned are Docker Engine / Daemon (i.e. dockerd) APIs. They are not ACR or Docker Registry HTTP API V2 (i.e. registry sever) APIs.
> 
> The dockerd accepts base64url with padding only (source code available at [image_routes.go](https://github.com/moby/moby/blob/master/api/server/router/image/image_routes.go#L71) line 71). Therefore, any dockerd client should follow the Docker spec instead of the RFC spec.
> 
> Since dockerd runs on the client host, and is considered as a registry client (i.e. client code to ACR or any registries), and is maintained by Docker Inc., it is out of the scope of Azure Container Registry (ACR) and ACR servers.
> 

It seems like they are following what Docker does, which does use padding in their base64url encoding, which golang allows them to do.

I think it would be sensical to add the option of padding to the identitymodel library since Java, Golang and Python default to using padding and add optional flags/settings to encode without the padding.

[Java encoder](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.Encoder.html)
[GoLang encoding](https://golang.org/src/encoding/base64/base64.go?s=1326:1368#L33)
[Python encoder](https://docs.python.org/3.9/library/base64.html#base64.urlsafe_b64encode)

By telling developers they must not use padding instead of allowing for an option of padding when it may be needed, Microsoft isn't providing a more robust developer experience using IdentityModel when developing in C#.  I think we should be in parity with Java, GoLang and Python. 

I do hear what you are saying though.  According to the RFC, there is no reason to add the padding.  But it seems many languages and Docker support and even expect it.

@brentschmaltz @Tratcher What do you think?

**Comment by Tratcher** [comment]
The RFC calls out reasons not to add the padding, so for those reasons and to avoid similar compat issues caused by changing the behavior identitymodel really should not add padding by default.

Adding a compat option here to add the padding is possible, but such compat options tend to get buried if you're not using the lowest layer of the API. E.g. if you were using this from a higher layer like ASP.NET. They also only help you if you already understand the problem. That's why we push for RFC compatibility first and only add workarounds where that's not feasible.

File the dockerd issue and see if any progress can be made on that end. In the meantime you should be able to add the padding yourself, right?

**Comment by aryamsft** [comment]
I looked at [RFC4648](https://tools.ietf.org/html/rfc4648#section-3.2) again,

Section 3.2 it says

> Implementations MUST include appropriate pad characters at the end of encoded data unless the specification referring to this > document explicitly states otherwise.

Section 3.3 says

> Furthermore, such specifications MAY ignore the pad character, "=", treating it as non-alphabet data, if it is present before the > end of the encoded data.  If more than the allowed number of pad characters is found at the end of the string (e.g., a base 64 > string terminated with "==="), the excess pad characters MAY also be ignored.

For Base64URL encoding, it says:

> The pad character "=" is typically percent-encoded when used in an URI [9], but if the data length is known implicitly, this can > be voided by skipping the padding; see section 3.2.

It seems like not adding the '=' is simply an option that MAY be done by a particular specification.  The IdentityModel library is following a particular interpretation of the RFC, which is fine.  But it seems like GoLang, Python and Java default to a different interpretation, which is also fine.  But they do give the option to go in the other direction since the RFC doesn't say "MUST" or "MUST NOT" when it comes to encoding the '=' character.  

Given the language of the RFC it seems like that adding an option for the padding is the right move.

But yes, I can unblock the issue we are having in Service Fabric.  I'll implement base64url encoding since I can't use your library.

I'll bring up the point with Docker.  They may make it so that with or without the '=' will work, or the will update their docs to say that the base64url MUST include '=' for padding and refer to the RFC.

Your call on other or not you want to update the library.

**Comment by Tratcher** [comment]
@brentschmaltz @aryamsft let's wait and see how things go with Docker, ok?
