### ISSUE TITLE
[Fundamentals] Rename master branch to main

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1553]
**Main branch**
_An inclusive new default_
New repos created within Microsoft orgs now have the default branch name of 'main'.

Teams are encouraged to rename their default branches if they are still using the 'master' branch name. This is an important, but not urgent, change.

**See more:**
https://repos.opensource.microsoft.com/

**Comment by GeoK** [comment]
Closing the issue as our default branch is 'dev'.

**Comment by henrik-me** [comment]
We have a master branch. The master branch should be renamed whether it's the default or not. If master is not needed we should delete it.

**Comment by GeoK** [comment]
Done. I initially understood that we should rename the branch only if it's default.
