### ISSUE TITLE
The type initializer for 'System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler' threw an exception.

### ISSUE THREAD

**Issue by arunswarnam** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1554]
I am using a locally compiled version of System.IdentityModel.Tokens.Jwt.6.7.1.nupkg (not from Nuget) and I am getting the exception "The type initializer for 'System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler' threw an exception." from my project when instantiating `new JwtSecurityTokenHandler();`. I would like to know if there are any leads that will help me resolve the issue.

**Comment by brentschmaltz** [comment]
@arunswarnam can you share the exception.
the assembly is delayed signed and will thrown if you have not allowed skipping verification.
we have .reg files in the build folder that contain the reg keys that need to be set.

**Comment by arunswarnam** [comment]
@brentschmaltz Thanks for responding. `The type initializer for 'System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler' threw an exception.` is the exception the code is throwing. 

1)  Is there an instruction to build the assembly after cloning the project and checking out tag 6.7.1. I am currently attempting to build the assemblies for version 6.7.1 by running [this](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6.7.1/build.sh) script.
2) I am not sure how to skip verification. Any handles on this?

**Comment by GeoK** [comment]
@arunswarnam Are you building on Linux/MacOS? 
1. It should work out-of-the-box. I just did a fresh 6.7.1 build (running build.sh) on Ubuntu 18.04.2, running .NET 5.
2. You can flip this to `false` to disable delayed signing. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/30c16ab82cf4338c6d6e04a5d4094795aa83c587/build/common.props#L12

You can also disable strong name validation (if on Windows) by running these two scripts.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/build/strongNameBypass.reg
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/build/strongNameBypass2.reg

**Comment by arunswarnam** [comment]
Thanks @GeoK . I am building it on MacOS, running .NET 3.1.300 and I am currently running the same  build script.I can  try your suggestion but wouldn't disabling DelaySigning ask for the signing keys? Which I assume is not available to external developers?

**Comment by arunswarnam** [comment]
@GeoK when you mean running 'build.sh out-of-the-box'? 
1) Don't we need to update [this]( https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/30c16ab82cf4338c6d6e04a5d4094795aa83c587/build/version.props) file's version prefix to 6.7.1 and remove the version suffix?  If I don't do this, the .nupkg artifacts generated have a version 0.0.1-preview.
2) Similarly I also update the assembly info in [this](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/30c16ab82cf4338c6d6e04a5d4094795aa83c587/src/System.IdentityModel.Tokens.Jwt/Properties/AssemblyInfo.cs) file to 6.7.1. Don't we need to do this?

**Comment by arunswarnam** [comment]
@brentschmaltz I am really not sure about building this repo locally. I see this exception showing up when I was fiddling with building this repo as noted above. See if this gives more insights?

`System.ArgumentException: IDX12729: Unable to decode the header 'System.String' as Base64Url encoded string. jwtEncodedString: 'System.String'.
 ---> System.TypeInitializationException: The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception.
 ---> System.MethodAccessException: Attempt by method 'System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()' to access method 'Microsoft.IdentityModel.Json.JsonConvert.SerializeObject(System.Object)' failed.
   at System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.get_Deserializer()
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.DeserializeJwtHeader(String jsonString)
   at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlDeserialize(String base64UrlEncodedJsonString)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.Decode(String[] tokenParts, String rawData)
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.Decode(String[] tokenParts, String rawData)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ReadJwtToken(String token)`

**Comment by GeoK** [comment]
@arunswarnam - We are using [_friend assembly_](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-5.0#examples) mechanism to access internal classes/methods in other IdentityModel.* assemblies.
Are you using a different key to sign these assemblies? If so, that would result in a [public key](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/InternalsVisibleTo.cs) mismatch.

**Comment by arunswarnam** [comment]
@GeoK We don't strong name sign the assemblies but we do delay sign the assemblies with a different key. Will that still cause an issue?

**Comment by arunswarnam** [comment]
Thanks @GeoK .. The handle you gave regarding Friend Assemblies helped solve the issue. The main issue was delay signing the locally built nuget package with a different key.
