### ISSUE TITLE
HTML encoding breaks compatibility to use IdentityModel as an IdP for SharePoint

### ISSUE THREAD

**Issue by doeringp** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1555]
`AuthenticationProtocolMessage.BuildFormPost()` produces encoded form input values using `WebUtility.HtmlEncode()` that break the compatibility to use the AzureAD IdentityModel to build an IdP for SharePoint.

We wanted to use AzureAD IdentityModel for our companies' Identity Provider to support the WS-Federation protocol. Before we used the .NET Framework IdentityModel classes before, but now we want to move forward to .NET Core. After moving to Azure AD IdentityModel we discovered an issue with the authentication to SharePoint:

We now get an error page in SharePoint during the sign-in process at url path `/_trust`:

```
ID6018: Digest verification failed for reference
```

![image](https://user-images.githubusercontent.com/20394732/100052474-4f581000-2e1e-11eb-8835-810f5543fd6c.png)

Assumptions:
* SharePoint could not verify the signature of the SAML assertion.
* We found out that SharePoint doesn't decode HTML entities with numbers before validating the Signature.
* Numbered HTML entities are often german umlauts and other special characters.
* It seems like SharePoint just decodes named HTML entities like `&quot;`, `&lt;`, `&gt;`

If we replace those HTML entities with the right decoded value, authentication to SharePoint works:
```csharp
message.BuildFormPost().Replace("&#223;", "ß");
```

Example: `Gro&#223;bauteile` should be `Großbauteile`

I found out that the method `WriteFormPost()` in class `FederationMessage` in the System.IdentityModel.Services-namespace of the .NET Framework was using `HttpUtility.HtmlAttributeEncode(string s)` to encode the form input values. If we're using HtmlAttributeEncode authentication to SharePoint works again.

Please can we replace `WebUtility.HtmlEncode` with `HttpUtility.HtmlAttributeEncode` in the class `AuthenticationProtocolMessage`?

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/30c16ab82cf4338c6d6e04a5d4094795aa83c587/src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs#L74

**Comment by doeringp** [comment]
See also #755

**Comment by doeringp** [comment]
I find it interesting that it doesn't even work, when using the wsfed client library for .NET Core using the `AddWsFederation()` in Startup.cs.

I can reproduce the error using ASP.NET Core 2.1 and Microsoft.AspNetCore.Authentication.WsFederation Version 2.1.2.

I get a similar exception:
```
2020-11-24 07:03:53.1937|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HM4G7QNV3O5M", Request id "0HM4G7QNV3O5M:00000002": An unhandled exception was thrown by the application. System.Exception: An error was encountered while handling the remote login. ---> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: E32F1725618A14978275BC30308011BA9458D78A
'.
Exceptions caught:
 'Microsoft.IdentityModel.Xml.XmlValidationException: IDX30201: The 'Reference' did not validate: '#_9b849ad4-3bab-4200-a496-4fedf1649b92'.
   at Microsoft.IdentityModel.Xml.Reference.Verify(CryptoProviderFactory cryptoProviderFactory)
   at Microsoft.IdentityModel.Xml.SignedInfo.Verify(CryptoProviderFactory cryptoProviderFactory)
   at Microsoft.IdentityModel.Xml.Signature.Verify(SecurityKey key, CryptoProviderFactory cryptoProviderFactory)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: 'Microsoft.IdentityModel.Tokens.Saml.SamlSecurityToken'.
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by brentschmaltz** [comment]
@doeringp are you using AuthenticationProtocolMessage.BuildFormPost to support a WS-Federation message such as wa-signin?
Your logic seems correct, the token contained Großbauteile, then HtmlEncode encoded the ß to &#223;, When the receiver does not preform the inverse decoding the digest fails.

We can't change the encoding here as that most likely would break other users.
The other issue is HttpUtility.HtmlAttributeEncode is in System.Web that is not part of .net core https://github.com/dotnet/core/issues/838.

It may be simplest to use similar code as AuthenticationProtocolMessage and return an encoded message that works.

**Comment by doeringp** [comment]
@brentschmaltz Yes, we're using AuthenticationProtocolMessage.BuildFormPost to generate a [wsignin1.0 Response Message](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mwbf/99bbd73d-f1ed-491c-be6a-5e53d8f9d1e0).

By the way, our Identity Provider is based on the OSS project [IdentityServer/IdentityServer4](https://github.com/IdentityServer/IdentityServer4) and we're using the implementation of [616b2f/IdentityServer4.WsFederation](https://github.com/616b2f/IdentityServer4.WsFederation) to support WS-Federation IdP. The library supports .netstandard2.0.

I solved it now by overrding the method AuthenticationProtocolMessage.BuildFormPost() in a custom subclass of WsFederationMessage. We're now using HttpUtility.HtmlAttributeEncode for encoding attribute values.

```csharp
using Microsoft.IdentityModel.Protocols.WsFederation;
using System.Collections.Generic;
using System.Text;
using System.Web;

namespace IdentityServer4.WsFederation
{
    public class CustomWsFederationMessage : WsFederationMessage
    {
        private static string HtmlEncode(string s) => HttpUtility.HtmlEncode(s);
        private static string HtmlAttributeEncode(string s) => HttpUtility.HtmlAttributeEncode(s);

        public override string BuildFormPost()
        {
            var strBuilder = new StringBuilder();
            strBuilder.Append("<html><head><title>");
            strBuilder.Append(HtmlEncode(PostTitle));
            strBuilder.Append("</title></head><body><form method=\"POST\" name=\"hiddenform\" action=\"");
            strBuilder.Append(HtmlAttributeEncode(IssuerAddress));
            strBuilder.Append("\">");
            foreach (KeyValuePair<string, string> parameter in Parameters)
            {
                strBuilder.Append("<input type=\"hidden\" name=\"");
                strBuilder.Append(HtmlAttributeEncode(parameter.Key));
                strBuilder.Append("\" value=\"");
                strBuilder.Append(HtmlAttributeEncode(parameter.Value));
                strBuilder.Append("\" />");
            }

            strBuilder.Append("<noscript><p>");
            strBuilder.Append(HtmlEncode(ScriptDisabledText));
            strBuilder.Append("</p><input type=\"submit\" value=\"");
            strBuilder.Append(HtmlAttributeEncode(ScriptButtonText));
            strBuilder.Append("\" /></noscript>");
            strBuilder.Append("</form>");
            strBuilder.Append(Script);
            strBuilder.Append("</body></html>");
            return strBuilder.ToString();
        }
    }
}
```

**Comment by doeringp** [comment]
By the way it isn't hard to replace the dependency to [HttpUtility.HtmlAttributeEncode](https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility.htmlattributeencode?view=net-5.0#:~:text=3.0-,HtmlAttributeEncode(String%2C%20TextWriter),to%20a%20TextWriter%20output%20stream).

>The HtmlAttributeEncode method converts only double quotation marks ("), single quotation marks ('), ampersands (&), and left angle brackets (<) to equivalent character entities. It is considerably faster than the HtmlEncode method.

I think my solution will be to just copy the [original code of the method](https://referencesource.microsoft.com/#System.Web/Util/HttpEncoder.cs,46e7e533003d74d8) when we're migrating to .NET 5.

I understand that you don't want to break other users but in my company, we still need to support WS-Federation sign-in to SharePoint.

**Comment by mafurman** [comment]
Unfortunately, we can't use HttpUtility.HtmlAttributeEncode as it's located in System.Web and it would break other customers.
