### ISSUE TITLE
Unable to use RsaSecurityKey to validate tokens

### ISSUE THREAD

**Issue by intermension** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1560]
For some reason IssuerSigningTokens are no longer supported for token validation and it seems we must use IssuerSigningKeys.

Trying to use an RsaSecurityKey for validation requires using an RSA which just throws:

```
var validationParameters = new TokenValidationParameters()
{
      IssuerSigningKey = new RsaSecurityKey(rsaKey),
};
new JwtSecurityTokenHandler().ValidateToken(tokenString, validationParameters, out token);
```

> System.NotSupportedException: IDX10634: Unable to create the SignatureProvider.
> Algorithm: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1', SecurityKey: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: '', InternalId: 'X67iaqK33Jny0y39QnnYBizlK6zvt0SP6MYS1QGIX7w'.'
>  is not supported. 

This is because RSA has a hardcoded security algo:

`public override string SignatureAlgorithm { get; }`

For RSA this is "RSA" and for [RsaCryptoServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacryptoserviceprovider.signaturealgorithm?view=netcore-3.1
) this is 

> http://www.w3.org/2000/09/xmldsig#rsa-sha1

neither of which is permitted as per [supported algos doc](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Supported-Algorithms) we have to use at least rsa-sha-256.

Is it possible to RsaSecurityKey to validate tokens and if so what are the steps / types that should be used?

**Comment by udlose** [comment]
@intermension - were you able to resolve this?  I am also getting the `NotSupportedException: IDX10634: Unable to create the SignatureProvider` for Algorithm: 'RS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey
