### ISSUE TITLE
Invalid validation of non-present expiration JWT claims

### ISSUE THREAD

**Issue by shadow-cs** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1567]
The validators accepts nullable `notBefore` and `expires` `DateTime`s but return values from `JsonWebToken` `ValidFrom` and `ValidTo` properties return `DateTime.MinValue` if the claim is not present. So in my opinion `JsonWebTokenHandler` fails to properly convert it to nullable values.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/824068adaeb7b158df2b36d8787f689646e715e0/src/Microsoft.IdentityModel.Tokens/Validators.cs#L330

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/824068adaeb7b158df2b36d8787f689646e715e0/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs#L303-L313

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/824068adaeb7b158df2b36d8787f689646e715e0/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L995-L1000

As a result `SecurityTokenNoExpirationException` with `IDX10225` is never thrown.

The best way to handle this would be to change `JsonWebToken` results to nullable, but I guess it would be a big breaking change.

*Note: the above code snippets are from `6.8.0` branch but `dev` is at the same state (as of authoring this issue).*

**Comment by shadow-cs** [comment]
This bug is not that critical because the next checks properly mark not already valid tokens or expired tokens due to the default values returned by the properties.

**Comment by brentschmaltz** [comment]
@shadow-cs yes breaking changes are hard to manage given our level in the application stack, usually above .net core but below asp.net and the application layer. Many SDK's layer on top of us.

We can introduce a new API's.

**Comment by GeoK** [comment]
Would a change like this be sufficient to address the issue?

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/824068adaeb7b158df2b36d8787f689646e715e0/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L995-L997

`DateTime? expires = jsonWebToken.TryGetClaim(JwtRegisteredClaimNames.Exp, out var _) ? (DateTime?)jsonWebToken.ValidTo : null;`

Similar concept is used in JwtSecurityTokenHandler:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/30c16ab82cf4338c6d6e04a5d4094795aa83c587/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L779

**Comment by shadow-cs** [comment]
I was thinking more along the lines of:

```cs
DateTime? validTo = jsonWebToken.ValidTo;
if (validTo == DateTime.MinValue)
{
  validTo = null;
}
```

Another option might be to introduce an extension or utility method:

```cs
DateTime? GetValueOrNull(DateTime value) => value == DateTime.MinValue ? null : value;
```

Not sure if it wouldn't get too confusing then for the end users.

But if there's a pattern I'd stick with that... And the solution @GeoK suggests would fix the issue.

In the end it's your call 😉

**Comment by brentschmaltz** [comment]
@shadow-cs @GeoK i think consistency between the two handlers would be a good thing. As you suggest @GeoK a simple change to JsonWebTokenHandler should do the trick.

**Comment by yori-s** [comment]
Any chance this will make it into a 6.8.x?

I'm currently working around with a custom `TokenValidationParameters.LifetimeValidator` of the form
```c#
static bool ValidateLifetime(DateTime? nbf, DateTime? exp, SecurityToken token, TokenValidationParameters tvp)
{
    if (default(DateTime) == nbf) nbf = null;
    if (default(DateTime) == exp) exp = null;

    // undelegate
    var tvp2 = tvp.Clone();
    tvp2.LifetimeValidator = null;
    Validators.ValidateLifetime(nbf, exp, token, tvp2);
    return true;
}
```
but this feels awkward and brittle.

Also, I'm using `JsonWebTokenHandler` on 2 different projects and would rather not duplicate the above.
