### ISSUE TITLE
Add "name" claim to JwtRegisteredClaimNames

### ISSUE THREAD

**Issue by NinoFloris** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1568]
Add "name" claim to JwtRegisteredClaimNames

This seems to be a well established claim name, in use by Auth0, Okta and others.

**Comment by NinoFloris** [comment]
See also https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by brentschmaltz** [comment]
@mafurman i need to work in this file for https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1516 as i need to add the 'act' claim.

**Comment by brentschmaltz** [comment]
fixed with https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/183c04ad613b1c0355b68ad3278d5a45e5c8835b
