### ISSUE TITLE
Do I need to explicitly set TokenValidationParameters.ValidateIssuerSigningKey to true ???

### ISSUE THREAD

**Issue by scale-tone** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1571]
According to the [source code](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/main/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L626), the default value for **TokenValidationParameters.ValidateIssuerSigningKey** is **false**.

Yet, the [official manual token validation sample](https://github.com/Azure-Samples/active-directory-dotnet-webapi-manual-jwt-validation/blob/master/TodoListService-ManualJwt/Global.asax.cs#L134) doesn't bother setting it to **true** and keeps the default value.

[The doc is as confusing as can be](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateissuersigningkey?view=azure-dotnet), and doesn't explain anything. Doesn't even state what the default value is.

**Finally, are we required to explicitly set it to true when implementing our own token validation or not?**

If not, then why this knowledge is so very much hidden? The whole security model of our services relies on the correct understanding of this corner point, how can it be so opaque?!

If yes, then why the sample code doesn't do this and hence keeps spreading a huge security breach (which is that token's signature isn't actually being validated)?!

**Comment by brentschmaltz** [comment]
@scale-tone we added this wiki page.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Use-of-TokenValidationParameters.ValidateIssuerSigningKey

Let us know if you this explains the usage.

**Comment by scale-tone** [comment]
Thanks for that, @brentschmaltz . Please, correct the property name in that wiki page - it should be **ValidateIssuerSigningKey** all the way.

Also, I'd propose to call it not `additional validation`, but `custom validation with your own IssuerSigningKeyValidator`.

**Comment by brentschmaltz** [comment]
@scale-tone thanks for the comments, updated the wiki with your suggestions.
