### ISSUE TITLE
Returning internal JObjects in public APIs breaks updating to .net 5.0

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1580]
...e.g. in the OpenIdConnect configuration when a custom element is a JSON object.

Now the consuming code get returns a JObject - but it's internal and cannot do anything with that. This is a blocker for updating to .NET 5...

```cs
var config = await _manager.GetConfigurationAsync(cancel);

// cast will fail since JObject returned is the internal version...                        
var mtls = config.AdditionalData[OidcConstants.Discovery.MtlsEndpointAliases] as JObject;

config.TokenEndpoint = mtls[OidcConstants.Discovery.TokenEndpoint].ToString();
```

**Comment by brentschmaltz** [comment]
We are going to fix this in: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1516
