### ISSUE TITLE
Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.8.0.0

### ISSUE THREAD

**Issue by poyadav2001** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1586]
We are using .NET Frame work 4.7.2 and encountering the following error on using System.IdentityModel.Tokens.Jwt package

System.IO.FileNotFoundException: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IdentityModel.Tokens.Jwt, Version=6.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by brentschmaltz** [comment]
@poyadav2001 can you share your project file?

**Comment by poyadav2001** [comment]
https://microsoft.visualstudio.com/Universal%20Store/_git/SC.CST.Dunning/pullrequest/5569992?_a=files&path=%2FProduct%2FBilling%2Frunners%2FDunning.Runner%2FDunning.Runner.csproj

**Comment by brentschmaltz** [comment]
@poyadav2001 your project file seems normal.
This could be a deployment issue.
Do you see System.IdentityModel.Tokens.Jwt.dll in the output directory?

**Comment by brentschmaltz** [comment]
@poyadav2001 please reopen this if you need further assistance.
