### ISSUE TITLE
JwtSecurityTokenHandler.ValidateToken Error message unclear.

### ISSUE THREAD

**Issue by vllama** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1591]
When a validation fails, the error message contains the Type Name instead of the value.
Other validation errors have a similar issue.
Example:
"IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'."
Expected:
"IDX10223: Lifetime validation failed. The token is expired. ValidTo: '2021-01-01 9:10:10', Current time: '2021-01-01 9:10:11'."

**Comment by keegan-caruso** [comment]
Please see the wiki: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII

Inputs to the log messages are all filtered aggressively by default.

I'm going to close this issue for now, please reopen if the issue is still unclear.

**Comment by flamaniac** [comment]
Message in exception is incorrect:

![obraz](https://user-images.githubusercontent.com/6348462/107684399-0720ef00-6ca3-11eb-8721-38016b569bc0.png)


I am using identity build in the asp .net (net5.0). No Azure active directory involved but it seems asp .net uses your lib internally:
mentioned here ->  https://github.com/dotnet/aspnetcore/issues/23302
