### ISSUE TITLE
Before adding or using a SignatureProvider to the cache, check if the key material has been disposed of

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1596]
We shouldn't be using SignatureProviders that have had their keying material disposed of.
Adding this feature in requires these two PRs to go in first: 

- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1575 (cache eviction)
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1595 (IDisposable interface for security keys)

**Comment by brentschmaltz** [comment]
We can't do this on all platforms, so since this is a user error, we will punt as it didn't come up often
