### ISSUE TITLE
JwtRegisteredClaimNames Missing Standard OpenIdConnect claims

### ISSUE THREAD

**Issue by apsthisdev** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1598]
System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames does not contain "name" and "email_verified" claims. These are standard OpenId connect claims.

Additionally not all the standard and additional claims are provided, see below.
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim

**Comment by brentschmaltz** [comment]
We should update for 8.x

Cpoied from #1911
Actual behaviour
System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames should have more JWT claim names.

Additional context / logs / screenshots / links to code
https://www.iana.org/assignments/jwt/jwt.xhtml
https://www.rfc-editor.org/rfc/rfc7643.html#section-4.1.2

**Comment by ghost** [comment]
Any news?
