### ISSUE TITLE
AudienceValidator evaluation during TokenValidation doesn't honor ValidateAudience flag

### ISSUE THREAD

**Issue by duchau** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1599]
We're upgrading from an older version 5.6.0 to 6.8.0.  Seems like in the newest version, there was a change made to have AudienceValidator throw an exception here:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/36/commits/70c23ef985ad7d5c20a8e609b6c329642f311786

Which is fine and all. However, now it seems like if you specify a value for AudienceValidator AND set ValidateAudience = false, ValidateAudience does not get honored and we still evaluate the audience validator delegate rather than honoring the ValidateAudience flag.  Seems like ValidateAudience needs to be accounted for. If it's set to false, we shouldn't throw on the delegate?

We've worked around it for now by just manually nulling out AudienceValidator but still seems like a bug that should be fixed.

Sample code:
                TokenValidationParameters tokenValidationParams = new TokenValidationParameters
                {
                    AudienceValidator = AudienceValidator,
                };

                tokenValidationParams.ValidateAudience = false;

                JwtSecurityTokenHandler.ValidateToken(
                    token,
                    tokenValidationParams,
                    out validatedToken);

Previous behavior:
Passes validation

New behavior:
Throws Exception:
Microsoft.Online.Common.Authentication.SecurityTokenValidation.Exceptions.MalformedTokenException: Malformed access token ---> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10231: Audience validation failed. Delegate returned false, securitytoken: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.

**Comment by brentschmaltz** [comment]
@duchau yes, that was a deliberate change. If you specify an AudienceValidator, it will be called. We felt that if you set a Validator (of any type), you did that deliberately and it should be called.

**Comment by duchau** [comment]
Thanks for the confirmation. We'll fix our paths to manually handle this then.  Please update documentation to indicate that if AudienceValidator takes precedence over ValidateAudience flag in newer versions.
