### ISSUE TITLE
ConfigurationManager.GetConfigurationAsync() doesn't return JsonWebKeySet in 6.8.0

### ISSUE THREAD

**Issue by arianmotamedi** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1601]
We recently upgraded Microsoft.IdentityModel.JsonWebTokens 5.5.0 to 6.8.0, and noticed that the ConfigurationManager object no longer populates the JsonWebKeySet property of the OpenIdConnectConfiguration. This is the code:

```
var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
                metadataAddress: this.AuthorityUri + "/.well-known/openid-configuration",
                configRetriever: new OpenIdConnectConfigurationRetriever());
                
var configuration = await configurationManager.GetConfigurationAsync();
var configJson = JsonConvert.SerializeObject(configuration);
```

This is the serialized configuration object we get back in 5.5.0:

```
{
    "authorization_endpoint": "https://my-service:52044/not-implemented",
    "issuer": "https://my-service.com",
    "jwks_uri": "https://my-service:52044/keys",
    "JsonWebKeySet": {
        "keys": [
            {
                "e": "foo",
                "kid": "foo",
                "kty": "RSA",
                "n": "foo",
                "use": "sig",
                "x5t": "foo"
            },
            {
                "e": "foo",
                "kid": "foo",
                "kty": "RSA",
                "n": "foo",
                "use": "sig",
                "x5t": "foo"
            }
        ],
        "SkipUnresolvedJsonWebKeys": true,
        "signing_key": "foo"
    },
    "SigningKeys": [
        {
            "HasPrivateKey": false,
            "PrivateKeyStatus": 1,
            "KeySize": 2048,
            "Parameters": {
                "D": null,
                "DP": null,
                "DQ": null,
                "Exponent": "foo",
                "InverseQ": null,
                "Modulus": "foo",
                "P": null,
                "Q": null
            },
            "Rsa": null
        },
        {
            "HasPrivateKey": false,
            "PrivateKeyStatus": 1,
            "KeySize": 2048,
            "Parameters": {
                "D": null,
                "DP": null,
                "DQ": null,
                "Exponent": "foo",
                "InverseQ": null,
                "Modulus": "foo",
                "P": null,
                "Q": null
            },
            "Rsa": null
        }
    ],
    "token_endpoint": "https://my-service:52044/token"
}
```

This is what we get in 6.8.0:

```
{
    "AdditionalData": {
        "additionalData": {},
        "authorizationEndpoint": "https://my-service:52044/not-implemented",
        "claimsParameterSupported": false,
        "httpLogoutSupported": false,
        "jwksUri": "https://my-service:52044/keys",
        "logoutSessionSupported": false,
        "requestParameterSupported": false,
        "requestUriParameterSupported": false,
        "requireRequestUriRegistration": false,
        "tokenEndpoint": "https://my-service:52044/token"
    },
    "AuthorizationEndpoint": null,
    "CheckSessionIframe": null,
    "ClaimsParameterSupported": false,
    "EndSessionEndpoint": null,
    "FrontchannelLogoutSessionSupported": null,
    "FrontchannelLogoutSupported": null,
    "HttpLogoutSupported": false,
    "IntrospectionEndpoint": null,
    "Issuer": "https://my-service.com",
    "JwksUri": null,
    "JsonWebKeySet": null,
    "LogoutSessionSupported": false,
    "OpPolicyUri": null,
    "OpTosUri": null,
    "RegistrationEndpoint": null,
    "RequestParameterSupported": false,
    "RequestUriParameterSupported": false,
    "RequireRequestUriRegistration": false,
    "ServiceDocumentation": null,
    "TokenEndpoint": null,
    "UserInfoEndpoint": null
}
```

Looks like the objects serialize entirely differently between the two versions now, but the main concern here is that "JwksUri" is null in 6.8.0 [which I believe is why](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/rel/6.8.0/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs#L93) "JsonWebKeySet" is null.

This is how the configuration object is being populated on the server side:

```
/// <summary>
/// Get the OpenID Configuration.
/// </summary>
/// <returns>The Configuration.</returns>
[HttpGet(Name = "ConfigurationController.GetConfiguration")]
[ProducesResponseType(StatusCodes.Status200OK)]
public IActionResult GetConfiguration()
{
    var requestedUrlBase = $"{this.Request.Scheme}://{this.Request.Host}/";

    var configuration = new OpenIdConnectConfiguration
    {
        Issuer = this.tokenIssuer.Issuer,
        TokenEndpoint = requestedUrlBase + Routes.Token,
        AuthorizationEndpoint = requestedUrlBase + Routes.NotImplemented,
        JwksUri = requestedUrlBase + Routes.KeySet,
    };

    return this.Ok(configuration);
}
```

Is there anything extra needed to get the keysets back?

**Comment by brentschmaltz** [comment]
@arianmotamedi this is related to using an internal version of newtonsoft.
We are working on a fix.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1516

**Comment by brentschmaltz** [comment]
@arianmotamedi closing as we think #1516 will solve the issue.
Please re-open if this is not the case.

**Comment by arianmotamedi** [comment]
I can't reopen the issue, but this is still happening in 6.15.1 😞

**Comment by brentschmaltz** [comment]
@arianmotamedi if you write:
```cs
string configJson = OpenidConnectConfiguration.Write(configuration);
```
instead of 
```cs
var configJson = JsonConvert.SerializeObject(configuration);
```
You will see better results.

**Comment by dheerajawale-svg** [comment]
I did below workaround and was able to fix the issue

`    var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
        issuer + "/.well-known/jwks.json",
        new OpenIdConnectConfigurationRetriever(),
        new HttpDocumentRetriever());

    var discoveryDocument = configurationManager.GetConfigurationAsync().Result;

    if (discoveryDocument.SigningKeys.Any())
    {
        keys = discoveryDocument.SigningKeys.ToList();
    }
    else
    {
        foreach (var keyValPair in discoveryDocument.AdditionalData)
        {
            var signingKeysData = JArray.Parse(keyValPair.Value.ToString());

            foreach (JToken rsaKey in signingKeysData)
            {
                JsonWebKey jsonWebKey = new(rsaKey.ToString());
                keys.Add(jsonWebKey);
            }

            //Console.WriteLine(item.Value);
        }
    }

    return keys;
}`

**Comment by roganjoshua** [comment]
This is a workaround not a fix though

**Comment by remixtedi** [comment]
I've got the same issue in 7.5.2 and the workaround works but looks ugly.

**Comment by HeinA** [comment]
I also have this issue in 7.6.0

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/1184125/c924d231-5654-4bb1-8f7e-7425bceb5e0f)

I'm definitely setting it

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/1184125/3c03a323-815f-4c36-942e-bae908da7634)
