### ISSUE TITLE
Add option to remove the PII filtering on required fields.

### ISSUE THREAD

**Issue by RojaEnnam** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1607]
IdentityModelEventSource.ShowPII flag indicates whether or not PII is shown in logs. We need an option to remove the PII filtering on required fields.

**Comment by keegan-caruso** [comment]
relates to #1527

**Comment by brentschmaltz** [comment]
We have implemented a feature to mark fields as non PII.
