### ISSUE TITLE
'Method not found: 'System.Object Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.GetClaimValueUsingValueType(System.Security.Claims.Claim)'.'

### ISSUE THREAD

**Issue by ArjunSaiKumar** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1608]
'Method not found: 'System.Object Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.GetClaimValueUsingValueType(System.Security.Claims.Claim)'.'

When i tried to add Claim, Above error has raised and  **GetClaimValueUsingValueType**  nethod is not there in solution.

**Comment by brentschmaltz** [comment]
@ArjunSaiKumar that was an internal method in 5.x, we removed that method in 6.x.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2574f3cbc3736db085497b9b241ea5ae338357b9/src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs#L245

What were you using it for, perhaps we can suggest something that will work.

**Comment by brentschmaltz** [comment]
@ArjunSaiKumar i assume you were able to work around this.
