### ISSUE TITLE
Use inplace Base64url parsing

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1616]
public unsafe static byte[] UnsafeDecode(string str)
      {
         if (str == null)
         {
            throw new ArgumentNullException(nameof(str));
         }

         int len = str.Length;
         int mod = len % 4;
         if (mod == 1)
         {
            throw new FormatException(str);
         }

         int validLen = len + (4 - mod) % 4;
         bool needReplace = false;

         for (int i = 0; i < len; i++)
         {
            if (str[i] == base64UrlCharacter62 || str[i] == base64UrlCharacter63)
            {
               needReplace = true;
               break;
            }
         }

         if (!needReplace)
         {
            if (validLen == len)
            {
               return Convert.FromBase64String(str);
            }
            else
            {
               string validStr = new string(char.MinValue, validLen);
               fixed (char* src = str)
               fixed (char* dest = validStr)
               {
                  Buffer.MemoryCopy(src, dest, len * 2, len * 2);
                  for (int i = len; i < validLen; i++)
                  {
                     dest[i] = base64PadCharacter;
                  }
               }
               return Convert.FromBase64String(validStr);
            }
         }
         else
         {
            string validStr = new string(char.MinValue, validLen);
            fixed (char* dest = validStr)
            {
               int i = 0;
               for (; i < len; i++)
               {
                  if (str[i] == base64UrlCharacter62)
                  {
                     dest[i] = base64Character62;
                  }
                  else if (str[i] == base64UrlCharacter63)
                  {
                     dest[i] = base64Character63;
                  }
                  else
                  {
                     dest[i] = str[i];
                  }
               }

               for (; i < validLen; i++)
               {
                  dest[i] = base64PadCharacter;
               }
            }

            return Convert.FromBase64String(validStr);
         }
      }

 
If there is no need to create a new string, just pass input str to Convert.FromBase64String
Use unsafe code to convert the string one-time to avoid extra string allocation caused by string.Replace and string.Concat.
And if you are use .Net Core, there is a new method: string.Create, it can do the same thing of the unsafe code

**Comment by brentschmaltz** [comment]
fixed: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1620
