### ISSUE TITLE
Change in claim behaviour between 6.8 and 6.9

### ISSUE THREAD

**Issue by ParanoidPenguin** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1619]
Hi! Can I prefix this by saying I've no idea if this is a desirable change or otherwise... just something I noticed. We're running what I think is a fairly standard configuration of asp.net (full fx, not core) against azureAD for authentication. 

In 6.8, the observed behaviour was that my email address/UPN (however you think of it) came though in the claims collection with a claimType of "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", alongside various others, including a separate claim of claimType "name" with my actual name. 

On upgrading to 6.9 (and I presume this is related to PR#1545), there are now 2 claims in the collection of claimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", with the previous "name" now seemingly remapped as the first instance of this claim, and the second my email/UPN as before.

To illustrate:
v6.8
*snip other claims*
ClaimType: name Value: paranoidpenguin
ClaimType: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name Value: penguin@example.com

v6.9
*snip other claims*
ClaimType: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name Value: paranoidpenguin
ClaimType: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name Value: penguin@example.com

I was extracting the value from the claim using context.AuthenticationTicket.Identity.FindFirst(ClaimTypes.Name).Value, so the above change was essentially a breaking change for me. Could someone with more knowledge of this just confirm if the new behaviour is correct? I'm quite happy to update my code (and could potentially use ClaimTypes.Email, which is another entry). Thanks in advance.

**Comment by henrik-me** [comment]
@mafurman @brentschmaltz

**Comment by brentschmaltz** [comment]
@ParanoidPenguin can you share a copy of the jwt that you received?
That would help in debugging.

**Comment by ParanoidPenguin** [comment]
Hi! Unfortunately not at the moment... if I can replicate something in another environment then I'll add it, but nothing straightforward I can share right now

**Comment by oddeirik** [comment]
Seeing some of the same here, although in an older ASP.NET MVC 5 project. We've previously read the email/UPN from `ctx.AuthenticationTicket.Identity.Name`, but with version 6.9 this would suddenly return the user **name**, which obviously broke the user lookup for us. I didn't have time to look into it more then, so I just reverted back to 6.8 for the moment.

Edit: Also storing the JWT as an IdToken claim:
```
private Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedNotification ctx)
{
  ctx.AuthenticationTicket.Identity.AddClaim(new System.Security.Claims.Claim("IdToken", ctx.ProtocolMessage.IdToken));
  var userEmail = ctx.AuthenticationTicket.Identity.Name;
  [...]
}
```

**Comment by mafurman** [comment]
This was added in order to have consistent claim mapping for all registered JWT claim names. Given that we were doing the mapping for other claims (such as _given_name_ and _family_name_), we should have been doing this for _name_ as well in order to be consistent.

Can you turn the claim mapping off? The mapping will only affect claims that are in the short format (such as _name_), rather than something like _http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name_.

**Comment by oddeirik** [comment]
Thanks for the clarification! In our case, I'll look into getting the upn from the id token claim, as that should have been done in the first place I guess 😄

**Comment by brentschmaltz** [comment]
@oddeirik i assume you have this under control.
Please ping us if you have any issues.
