### ISSUE TITLE
Microsoft.IdentityModel.Protocols.WsTrust package updates

### ISSUE THREAD

**Issue by gislikonrad** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1623]
On nuget, the Microsoft.IdentityModel.Protocols.WsTrust package is at 6.8.0. This package obviously comes from the brentsch/wstrust branch. However, it isn't on the main branch and it hasn't been updated in tandem with the rest of the Microsoft.IdentityModel.* packages. Any specific reason for this?

**Comment by gislikonrad** [comment]
Another minor version has been released and no update for the WS-Trust package. Any news on this?

**Comment by gislikonrad** [comment]
Any update on this?

**Comment by gislikonrad** [comment]
@brentschmaltz Has development of the WS-Trust extension stopped?

**Comment by gislikonrad** [comment]
I would love to know if this has been abandoned so that I could possibly fork it for my own uses.

**Comment by ciaozhang** [comment]
Please check Microsoft.IdentityModel.Protocols.WsFederation

**Comment by thuannguy** [comment]
I needed to find source code of the Microsoft.IdentityModel.Protocols.WsTrust and couldn't find it anywhere. It's only until I found this question that I figured out where the repo is. Just in case someone needs it like me: you need to switch to the brentsch/wstrust branch: 

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/brentsch/wstrust/src/Microsoft.IdentityModel.Protocols.WsTrust
