### ISSUE TITLE
IDX21323 exception unnecessarily redacted RequireNonce value as PII

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1625]
I got the following exception when using [Microsoft.IdentityModel.Protocols.OpenIdConnect/6.8.0](http://nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/6.8.0):

> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolInvalidNonceException: IDX21323: RequireNonce is 'System.Boolean'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.

That message hides the actual value of RequireNonce and shows only the type 'System.Boolean'.

The exception was thrown by OpenIdConnectProtocolValidator.ValidateNonce: <https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/824068adaeb7b158df2b36d8787f689646e715e0/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L637>

The LogHelper.FormatInvariant method calls LogHelper.RemovePII for each argument: <https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/824068adaeb7b158df2b36d8787f689646e715e0/src/Microsoft.IdentityModel.Logging/LogHelper.cs#L345-L354>

Here though, the value of OpenIdConnectProtocolValidator.RequireNonce is controlled by the developer and does not depend on the person who is trying to log in, so I think the exception should include the actual value rather than redact it as PII.

**Comment by KalleOlaviNiemitalo** [comment]
I dare not claim that all System.Boolean values are free of PII. But perhaps this could be fixed by changing the format call to

```C#
LogHelper.FormatInvariant(LogMessages.IDX21323, LogHelper.NotPII(RequireNonce))
```

where LogHelper.NotPII would return a NotPIIWrapper instance, and LogHelper.RemovePII would recognize that type and format the wrapped value without redacting.

**Comment by KalleOlaviNiemitalo** [comment]
The source tree also contains many `LogHelper.FormatInvariant` calls in which some arguments are actually constants but will be redacted. Expressions like `JwtRegisteredClaimNames.Iss.ToLowerInvariant()`, `SignedHttpRequestClaimTypes.B`, ` nameof(configuration)`, or `typeof(Saml2Assertion)`. If you wanted to stop redacting those, I think you could add a separate `LogHelper.ConstantNotPII(object)` method and a Roslyn analyzer to verify that the argument to the method is indeed not PII. However, such a change would not be very valuable because developers are already able to search for an identifier like `IDX10621` in the source code to find out what the values of the constants were.

**Comment by brentschmaltz** [comment]
@KalleOlaviNiemitalo we are making some improvements to PII handling in this PR https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1725

Please feel free to comment in the PR.
