### ISSUE TITLE
Add RefreshToken to OpenIdConnectParameterNames

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#163]
refresh_token is returned as part of the 'code' -> 'access_token' flow. While defined in the OAuth 2.0 spec, it would be convenient to have this defined.

**Comment by tushargupta51** [comment]
@brentschmaltz can we add this property to OpenIdConnectMessage also?

**Comment by polita** [comment]
Fixed in both 4.x and 5.x
