### ISSUE TITLE
Json Serialialization of JsonWebKey

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1634]
Hi,

I have a JsonWebKey (retrieved from KeyVault) that I am wanting to serialize into the standard JWK json format. However, all of the code here seems to use Microsoft.IdentityModel.Json, which looks to be an internal version of NewtonSoft.Json. This is fine, but as an external user of the library how can I get a serialized version seeing that I can't use Microsoft.IdentityModel.Json?

Jeff

**Comment by chwarr** [comment]
Does issue [#1496, JsonWebKey - Not serializing properly](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1496) answer you question?

**Comment by brentschmaltz** [comment]
@jeffw-wherethebitsroam we are closing as we moved away from our internal json in version 7.x
