### ISSUE TITLE
IDX10501: Signature validation failed. Unable to match key:  kid: 'System.String

### ISSUE THREAD

**Issue by germankuber** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1638]
I am getting this error: IDX10501: Signature validation failed. Unable to match key:  kid: 'System.String.

I am looking the source code and I get this code:

` internal static void ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt(SecurityToken securityToken, DateTime? notBefore, DateTime? expires, string kid, TokenValidationParameters validationParameters, StringBuilder exceptionStrings)
        { 

            bool validIssuer = false;
            bool validLifetime = false;
            try
            {
                Validators.ValidateLifetime(notBefore, expires, securityToken, validationParameters);
                validLifetime = true;
            }
            catch (Exception)
            {
                // validLifetime will remain false
            }
            try
            {
                Validators.ValidateIssuer(securityToken.Issuer, securityToken, validationParameters);
                validIssuer = true;
            }
            catch (Exception)
            {
                // validIssuer will remain false
            }
            if (validLifetime && validIssuer)
                throw LogHelper.LogExceptionMessage(new SecurityTokenSignatureKeyNotFoundException(LogHelper.FormatInvariant(TokenLogMessages.IDX10501, kid, exceptionStrings, securityToken)));
            else
            {
                var validationFailure = ValidationFailure.None;
                if (!validLifetime)
                    validationFailure |= ValidationFailure.InvalidLifetime;
                if (!validIssuer)
                    validationFailure |= ValidationFailure.InvalidIssuer;
                throw LogHelper.LogExceptionMessage(new SecurityTokenUnableToValidateException(
                    validationFailure,
                    LogHelper.FormatInvariant(TokenLogMessages.IDX10516, kid, exceptionStrings, securityToken, validLifetime, validIssuer)));
            }
        }`

I do not undertand why, the code is throwing a exception when the validIssuer and validLifetime are true.

I am trying with a different configuration, this is the last one.

`.AddJwtBearer(options =>

                     {
                         options.RequireHttpsMetadata = false;
                         options.Events = events;
                         options.TokenValidationParameters = new TokenValidationParameters
                         {
                             ValidateIssuer = false,
                             ValidateAudience = false,
                             ValidateLifetime = false,
                             LifetimeValidator = (_, __, ___, ____) => false,
                         };
                         options.MetadataAddress =
                             "http://localhost:8080/auth/realms/myrealm/";
                     });`

I am returning false in the LifetimeValidator  for try to avoid the part of the code that throw a exception, but the error does not change.

**Comment by mafurman** [comment]
The method `ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt` is triggered after signature validation fails. Regardless of whether the issuer and the lifetime are valid, an exception will be thrown. This method is simply used to figure out the specific exception type that should be thrown in order to better help our users troubleshoot.

From the exception you're receiving, it seems like you have not provided the correct key for signature validation.

**Comment by mafurman** [comment]
@germankuber Closing this issue. Please reopen it if you have additional questions or if your problem has not been fully addressed!
