### ISSUE TITLE
Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.

### ISSUE THREAD

**Issue by KunalAdu** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1642]
Hi Team,

I have a problem with IdentityServer4 and my API running as an AKS instance. My IdentityServer4 and the the secured API runs locally in a Docker container without problems.

As soon as I run the Docker Container as an AKS  I get the following error. Authentication works without problems (Login). But as soon as I call my Web API with a valid Bearer Token I get the following error.

Has anyone got this error before ? Can anyone help me with steps which they followed ?

 _Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
---> System.Net.Http.HttpRequestException: Resource temporarily unavailable
---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
--- End of inner exception stack trace ---
at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
--- End of inner exception stack trace ---
at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()_

As I said, Local in Docker works without any problems. Has anyone ever had the following problem or does anyone know a solution?

Thanks & Regards 
Kunal Advani

**Comment by mafurman** [comment]
Our library throws this exception when we are unable to retrieve the OpenIdConnectConfiguration from the metadata endpoint. From the stack trace you provided, this seems like a connection issue.

Are you able to set `IdentityModelEventSource.ShowPII = true`? This would allow us to see more of the exception details.

**Comment by KunalAdu** [comment]
@mafurman : Thank you , Yes we tried that we got the URL and got to Know the issue .

We have hosted the docker image inside AKS the particular container is not able to do DNS Resolve (We are using CoreDNS)
For Java they have used (networkaddress.cache.ttl or sun.net.inetaddr.ttl) these for auto resolving .


Any settings/permission needs to be updated for .net core for CoreDNS ? So it can auto resolve 
As of now we have removed the entry from CoreDNS the PII URL which was configured , but still auto resolve needs to be fixed from .net core end

**Comment by hooyao** [comment]
I stuck in a similar issue, can't retrieve the configuration from `https://login.microsoftonline.com`, we mitigated the issue by providing a custom httpclient, though I don't quite understand what's going on
```
            services.AddHttpClient("AadHttpClient", c =>
                {
                    c.DefaultRequestHeaders.Add("Accept", "application/json");
                })
                .ConfigureHttpClient(
                    (provider, client) =>
                        client.Timeout = TimeSpan.FromSeconds(60)) // Set the client global timeout to 60s
                .AddPolicyHandler(
                    HttpPolicyExtensions
                        .HandleTransientHttpError()
                        .WaitAndRetryAsync(
                            3,
                            retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
                            (result, timeSpan, retryCount, context) =>
                            {
                                if (result.Result != null)
                                {
                                    AppServiceExtensions._logger.LogWarning(
                                        result.Exception,
                                        "Request failed with {StatusCode}. Waiting {TimeSpan} before next retry. Retry attempt {RetryCount}",
                                        result.Result.StatusCode,
                                        timeSpan,
                                        retryCount);
                                }
                                else
                                {
                                    AppServiceExtensions._logger.LogWarning(
                                        result.Exception,
                                        "Request failed because network failure. Waiting {TimeSpan} before next retry. Retry attempt {RetryCount}",
                                        timeSpan,
                                        retryCount);
                                }
                            }))
                .AddPolicyHandler(
                    HttpPolicyExtensions
                    .HandleTransientHttpError()
                    .CircuitBreakerAsync(5, TimeSpan.FromSeconds(30)))
                .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler() { MaxConnectionsPerServer = 1 });
            services.Configure<AadIssuerValidatorOptions>(options =>
            {
                options.HttpClientName = "AadHttpClient";
            });
```

**Comment by brentschmaltz** [comment]
@KunalAdu  We are making some improvements to our PII handling in this PR : https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1725

Please feel free to comment in that PR

**Comment by justinmchase** [comment]
I'm still seeing this error. Its trying to go out through our corporate firewall and we have the proper certs installed in the image (a simple httpclient get request works) but seems to not be using the machines certificates reliably.

Are there any docs around how to configure tls for the httpclient being used here?
