### ISSUE TITLE
Add new delegate to validate tokens being replayed that takes a token.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1651]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b45a5b4cf4e918ca2b2c12ff1951f1be7b592bac/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L99

This delegate takes the securitytoken as a string.
This requires the users to do some work to determine the token type and logic as different token types { JWT, SAML, SAML2, ...} may require special processing.
We have already hydrated the token into a object so pass it as a pararmeter.

**Comment by keegan-caruso** [comment]
Not a priority.

**Comment by AndersAbel** [comment]
I think this was a good idea. For Saml2 tokens it makes sense: There is already a token-unique Id that can be used to detect replay without having to store the entire token. As Saml2 tokens are quite large it is much more efficient to just store the id.

**Comment by keegan-caruso** [comment]
@AndersAbel could you write a feature request? Would be great to have it on the issue board from the perspective of a user of the library.
