### ISSUE TITLE
Base64UrlEncoder.Encode fails on empty string

### ISSUE THREAD

**Issue by PashaPash** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1655]
`Base64UrlEncoder.Encode("")` fails with the following exception on 6.10.0+:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
Stack Trace:
   at Microsoft.IdentityModel.Tokens.Base64UrlEncoder.UnsafeEncode(String str)
   at Microsoft.IdentityModel.Tokens.Base64UrlEncoder.EncodeString(String str)
   at Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode(Byte[] inArray)
   at Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode(String arg)
```

Possible cause: missing empty string check in new `UnsafeEncode` version:

```
       private unsafe static string UnsafeEncode(string str)
        {
            bool needReplace = false;
            int reductionSize = 0;
            if (str[str.Length - 1] == base64PadCharacter) // fails on empty string
                reductionSize = 1;
```

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/8e5bb2c5ec86aa3af44636ff28c48e855a904498#diff-d8157f3c41ee79206c7c316a85950971914d143866bc8ca23dcfc8d3658338b3R116

**Comment by mafurman** [comment]
I've gone ahead and labeled this as a bug on our end; we'll discuss this during our next planning meeting to see when we can prioritize it.

**Comment by cesarpayan** [comment]
The code path that leads to this bug no longer exists, and there's a specific check for an empty string in the Encode method now. This was done in PR#1698. Linked the PR to this issue.

**Comment by cesarpayan** [comment]
@PashaPash The bug was fixed as part of another issue, you can find the PR linked [here ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1698)(and the comment above for extra clarification). If you encounter the issue again please feel free to reopen this issue. I am closing the issue now. Thanks for letting us know!
