### ISSUE TITLE
What exactly is the process to get Pull Requests being merged?

### ISSUE THREAD

**Issue by KrisVandermotten** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1659]
If I look at PRs such as #1637 or #1645, I wonder what is stopping them from being merged.

Is there some step in the process we are missing here?

**Comment by mafurman** [comment]
Typically at least one member of our team would need to approve the PR, and we would also need you to rebase against the latest version of our 'dev' branch.

We've been a bit busy on our end, but we can take a look at these at our next planning meeting and see if we want to include them in our next release.

**Comment by lechu445** [comment]
@mafurman any news regarding to this topic?

**Comment by brentschmaltz** [comment]
@KrisVandermotten on https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1637 i need you to rebase against dev. I also left a comment.
on https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1645, we are doing extensive work removing splits, etc here: brentsch/json where we are switching to System.Text.Json. However that will be a while.
There is enough goodness in 1645, that we should take it soon, i will review it and run some perf comparisons against dev.

**Comment by brentschmaltz** [comment]
Closing this out as we are adding resources and working to speed things up.
