### ISSUE TITLE
IssuerSigningKeyResolver doesn't support async

### ISSUE THREAD

**Issue by punitsinghi** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1660]
Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolver doesn't support async delegate and hence any async call is a blocking call.

        IssuerSigningKeyResolver = (token, securityToken, identifier, parameters) =>
                {
                    //async call here
                }

**Comment by mafurman** [comment]
Thanks for bringing this to our attention!
At the current moment we don't provide any async delegates, but this is definitely a feature that we'll want to think about adding.

**Comment by Kyle0654** [comment]
Is there any estimate on when this might be supported? Fetching a public key using a JKU during authentication isn't great when the code has to run synchronously.

**Comment by brentschmaltz** [comment]
@jennyf19 we can combine all the delegates into one feature.

**Comment by adambajguz** [comment]
The issue is quite long and important, are there any updates on in?

**Comment by keegan-caruso** [comment]
Will be fixed in #2568
