### ISSUE TITLE
Is there a way to support ECDH-ES+A128KW ?

### ISSUE THREAD

**Issue by jxnkwlp** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1666]
My question: `EncryptingCredentials`  can support ` ECDH-ES+A128KW `  jwe algorithm ? Or how to extension it .

**Comment by mafurman** [comment]
We do not have support for that algorithm. You can see our list of supported algorithms [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Supported-Algorithms).

You may be able to add support for that algorithm by implementing a custom CryptoProvider as shown [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Using-a-custom-CryptoProvider).

**Comment by jxnkwlp** [comment]
I create custom `CryptoProvider` and `KeyWrapProvider`  to  support `ECDH-ES+A128KW`,  and can success generate token, but token can't be validate by third-party library, eg 'jose-jwt', and throw error `AesKeyWrap integrity check failed` . 

I create an console app for this test  https://github.com/jxnkwlp/identitymodel-extension-test  .

How can i do next ? or how to fix this error ?

**Comment by brentschmaltz** [comment]
@jxnkwlp Our SymmetricKeyWrapProvider uses ECB as the Mode, we are going to change that to use CBC by default and allow users to change it.

You could extend SymmetricKeyWrapProvider and override GetSymmetricAlgorithm (just copy what we have) and where we wrote ECB, use CBC.

**Comment by brentschmaltz** [comment]
@jxnkwlp we are currently working on this feature. @cesarpayan owns the implementation.

**Comment by brentschmaltz** [comment]
Closing this as we are working on supporting ECDH KW with multiple key sizes.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1726
