### ISSUE TITLE
Is System.IdentityModel.Tokens.Jwt 6.11.1 Thread Locked？

### ISSUE THREAD

**Issue by shinnosukekubo** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1669]
This is my Azure Metrix 「Thread Count」
![無題クリップ_072221_011025_AM](https://user-images.githubusercontent.com/16874548/126523326-71b7a441-1607-4624-8e55-7b4140593ef0.jpg)

I solved it just by returning version 5.8.0

my source code 

` public static string GenerateAccessToken(Guid id, string name, string version, int expireSeconds = ACCESS_TOKEN_EXPIRED_SECONDS)
        {
            var symmetricKey = Convert.FromBase64String(SECRET);
            var tokenHandler = new JwtSecurityTokenHandler();

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.NameIdentifier, id.ToString()),
                    new Claim(ClaimTypes.Name, name),
                    new Claim(ClaimTypes.Version, version),
                }),
                Expires = DateTime.UtcNow.AddSeconds(expireSeconds),

                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(symmetricKey), SecurityAlgorithms.HmacSha256Signature)
            };

            var stoken = tokenHandler.CreateToken(tokenDescriptor);
            var token = tokenHandler.WriteToken(stoken);

            return token;
        }`

**Comment by shinnosukekubo** [comment]
6.12.0 fixed this problem

**Comment by brentschmaltz** [comment]
@shinnosukekubo are you running the exact same code?
Is this method in your web server?

**Comment by brentschmaltz** [comment]
@shinnosukekubo i think this is solved by 6.12.0. see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1630
