### ISSUE TITLE
Pull request 161 should be reverted and fixed in Mono.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#168]
This is a temporary work-around for a Mono issue.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/161

It should be reverted once Mono has been fixed.

**Comment by tushargupta51** [comment]
This issue is for 4.x since the mentioned PR #161  was pushed to 4.x. I am not sure if we want to revert it  since 4.x is not supported on mono.

**Comment by brentschmaltz** [comment]
Agreed, our 4.x code is working as desired.
