### ISSUE TITLE
IDX10000: The parameter 'hashAlgorithm' cannot be a 'null' or an empty object.

### ISSUE THREAD

**Issue by jxnkwlp** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1680]
The project is .net 472 with owin + mvc  and use 'Microsoft.Owin.Security.OpenIdConnect'  .
When receive token (id token and access token), idtoken is jwe token, access token is jws token . 
then throw an exception : `IDX10000: The parameter 'hashAlgorithm' cannot be a 'null' or an empty object.` . 

i find the source in here   , 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/65af0a94057b583c4b9d1d95d19a9256dd77a50d/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L595

my question is :  in my jwe token , the header alg is `RSA-OAEP`,  but method `ValidateAtHash`  use id token header alg ,  so can't be find the hash algorithm,  it is a bug ? 

i think the hash algorithm need be  from header in  idtoken decrypted payload .

**Comment by jennyf19** [comment]
Released in [6.20.0](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.20.0).
