### ISSUE TITLE
Leaking tasks that cause UTs to fail in IdentityModels 6.12.0.0

### ISSUE THREAD

**Issue by isaiah-mayerchak** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1683]
### -- Package + version number --

System.IdentityModel.Tokens.Jwt 6.12.0.0 (updated from 6.6.0.0)

### -- Behavior --

We were made aware before upgrading that we needed to upgrade to a version >= 6.12.0.0 due to an issue that caused hanging tasks in unit tests that was fixed by this PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1667/commits/a2430d1554c621024e59f78c13cba3c00594ae91

After upgrading to 6.12.0.0, a subset of our unit tests began to fail due to hanging tasks, and we traced the problem to a function of ours that creates a `System.IdentityModel.Tokens.Jwt.JwtSecurityToken`, creates a new `System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler` and then invokes `WriteToken()` on that handler using the token.

Skipping this code in our unit tests results in no hanging tasks, which given the presence of the issue mentioned in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1667/commits/a2430d1554c621024e59f78c13cba3c00594ae91 makes it seem very likely that it's the same issue or a closely related one.

My understanding given the description in the linked PR is that post-fix this is likely the result of a cache containing providers of some kind that when non-empty can result in this issue. What doesn't quite make sense to me is that when peeking into the code for `JwtSecurityTokenHandler` the only cache I can see is the `ITokenReplayCache` that comes inside `TokenValidationParameters` in `ValidateToken`, but I'm skeptical about how relevant that actually is to the problem.

I'm wondering if I can get some help from some folks more familiar with this codebase to understand what's potentially going on here.

**Comment by brentschmaltz** [comment]
@isaiah-mayerchak we recognized this issue and are working on it.
@dannybtsai owns the solution.

**Comment by dannybtsai** [comment]
A new version, 6.12.1, has been published and it should fix the "leaking task" issue. The main changes are to make the task exits as soon as it finishes processing events (plus a 2-min time to reduce potential overhead of restarting tasks too frequently). There are more improvements we plan to make but hopefully this will address the UT failures so you are not blocked.
