### ISSUE TITLE
JwtSecurityTokenHandler: Deadlock (starvation) when used on single threaded TaskScheduler

### ISSUE THREAD

**Issue by vuplea** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1691]
The consumer loop `EventBasedLRUCache.EventQueueTaskAction` is probably meant to be run as a separate blocking thread; however, the way is it started `new Task(Action).Start()` does not do that, but uses `TaskScheduler.Current` to run it.

Since the consumer loop is blocking, this means it stops a single threaded `TaskScheduler` from all processing.
Perhaps the static `Task.Run`, which would run the consumer on the thread pool, should be used?

Version: 6.12.2
Runtime: .NET 5
Repro:
```
    static class Program
    {
        static void Main()
        {
            var scheduler = new ConcurrentExclusiveSchedulerPair().ExclusiveScheduler;
            scheduler.Run(ValidateSomething);
            Thread.Sleep(200);
            scheduler.Run(() => { }).Wait();
        }

        private static Task Run(this TaskScheduler scheduler, Action action) =>
            Task.Factory.StartNew(action, CancellationToken.None, TaskCreationOptions.DenyChildAttach, scheduler);


        private static void ValidateSomething()
        {
            var handler = new JwtSecurityTokenHandler();
            var tokenString = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAA"));

            var validationParameters = new TokenValidationParameters
            {
                RequireExpirationTime = false,
                RequireSignedTokens = true,
                ValidateAudience = false,
                ValidateIssuer = false,
                ValidateLifetime = false,
                IssuerSigningKey = securityKey,
            };
            handler.ValidateToken(tokenString, validationParameters, out _);
        }
    }
```

**Comment by mafurman** [comment]
Thanks for bringing this to our attention!

Are you referring to this line in the code?         
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/08e98d190301804748f646f681b93e82a6111ebb/src/Microsoft.IdentityModel.Tokens/EventBasedLRUCache.cs#L393

**Comment by vuplea** [comment]
Yes, that's what I meant to write😅.  `new Task(Action).Start()`,  I've edited it in the original message.

**Comment by brentschmaltz** [comment]
@vuplea are you actually using such a pattern?

**Comment by vuplea** [comment]
Yes, we use https://github.com/StephenCleary/AsyncEx/wiki/AsyncContext, though ConcurrentExclusiveSchedulerPair probably has it's users too.

Token validation might be done by other higher-level libraries, for which it's not obvious when it happens (this was our case).

**Comment by brentschmaltz** [comment]
@vuplea thanks for the detail. 
We will address this.

**Comment by dannybtsai** [comment]
@vuplea,
Our task is "fire-and-forget" and meant to run in the background for up to 2 min then end. I looked into the Task and TaskScheduler and it makes sense to use the Task.Run() instead of Task.Start()  as you suggested. The Task.Run() method uses the default TaskScheduler and it won't interfere with other task schedulers.

**Comment by brentschmaltz** [comment]
@vuplea i believe we fixed this, please reopen if we missed some cases.
