### ISSUE TITLE
[Bug 6.8.0.0]: Method not found: 'Void Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.ValidateTokenType(System.String, Microsoft.IdentityModel.Tokens.TokenValidationParameters)'

### ISSUE THREAD

**Issue by melionel** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1693]
Hi team,

I am using ASP.NET core authentication middleware to do authentication with Jwt token in my web application. 
Everything was fine before I upgrade **_Microsoft.IdentityModel.JsonWebTokens_** from **5.6.0.0 to 6.8.0.0**.

After upgrade, the httpcontext can not get user's Identity from authorization token. I tried to call httpcontext.AuthenticateAsync() but got below errors: 
`{"Method not found: 'Void Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.ValidateTokenType(System.String, Microsoft.IdentityModel.Tokens.TokenValidationParameters)'."} `

**Comment by mafurman** [comment]
Hey @melionel!

ValidateTokenType() is an internal method that was moved to a different location, so this seems like something that could be caused by a versioning issue.

What ASP.NET Core authentication middleware are you using? JwtBearer?

**Comment by melionel** [comment]
Thanks for you hint @mafurman !
I finally realized that the issue was caused by mis-matched version of  System.IdentityModel.Tokens.Jwt. Everything goes fine after I upgrade this package from 5.6.0 to 6.8.0
