### ISSUE TITLE
BUG: Both 'id_token' and 'access_token' should be present error should not have been raised 

### ISSUE THREAD

**Issue by mrochon** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1697]
This issue was originally [raised on Microsoft.Identity.Web git](https://github.com/AzureAD/microsoft-identity-web/issues/1422). Using Microsoft.Identy.Web 1.1. to request id_token, with ResponseType=code (rather than id_token) but not requesting any API scopes (just OIDC), I get error:

> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: IDX21336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.
at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateTokenResponse(OpenIdConnectProtocolValidationContext validationContext)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

Per protocol definition, using ResponseType=code rather than ResponseType=id_token is not only allowed but recommended. Why is the library flagging this as an error?

**Comment by brentschmaltz** [comment]
@mrochon does this error occur when you are redeeming the code for a token?

**Comment by mrochon** [comment]
I assume so since the only code I have in my app is in Startup

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAdB2C"));
            services.AddControllersWithViews();
           services.AddRazorPages()
                .AddMicrosoftIdentityUI();
        }

And the following in appSettings.json

“ResponseType”: “code”,

The user is challenged for authentication and then the app reports the exception.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by brentschmaltz** [comment]
@mrochon The spec seems to indicate both an id_token and token must be returned when redeeming the code.
see: https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse

**Comment by mrochon** [comment]
You are right, I mis-read the spec. I will add some API scope when using *code* as response type (User.Read won't work as it is B2C). Thanks.
