### ISSUE TITLE
JsonWebTokenHandler.ValidateSignature should check signature before getting all keys.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1708]
If the logic on this line succeeds, then an attempt to validate the signature with that key should occur before any other work.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/be1c621755848b38ca3222f52d01465fef9b3189/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1078

If that fails and TokenValidationParameters.TryAllIssuerSigningKeys is true, then try all other keys.

**Comment by ciaozhang** [comment]
As discussed, the logic won't try get all key if we have the matched key.
