### ISSUE TITLE
Can I using AD Identirymodel extensions to build a Microsoft Identity Planform?

### ISSUE THREAD

**Issue by phungxuanvuong** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1710]
I'm learning to build an Oauth2 and OpenID. I found that .Net doesn't provide a ready solution for it. I wonder if Microsoft used this repo to build the Microsoft identity platform?. Is there any document or guide on how to build a similar system using the open-source code provided by Microsoft?

**Comment by brentschmaltz** [comment]
@QuanJingHong what services are you looking to provide?

**Comment by phungxuanvuong** [comment]
> @QuanJingHong what services are you looking to provide?

I want to build a Server which to provides IdentityServer-like or Microsoft Identity platform-like features.

**Comment by jennyf19** [comment]
You can start with this [class](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs).

Closing as answered.
