### ISSUE TITLE
[FeatureRequest] Better Transient/ClientMisconfiguration error handling for ConfigurationManager.GetConfigurationAsync?

### ISSUE THREAD

**Issue by adarce** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1714]
During token validation, our service uses the below `ConfigurationManager.GetConfigurationAsync` API in order to retrieve the `OpenIdConnectConfiguration` for a tenant-specific authority (e.g.: `https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/`):
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/4f24eaecffca2a0ebacc63976682df0adab54805/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L124

For this particular API, our service would like to distinguish between two types of errors:
- **Transient Errors:** If the underlying `HttpDocumentRetriever` fails to call `https://login.windows.net/{tenantId}/.well-known/openid-configuration` due to some transient I/O or networking issue, then we want to surface this to the customer as a `503 ServiceUnavailable` error. This signals to the customer that the issue is transient, so that they can configure a retry policy to try again later.	
- **ClientMisconfiguration Errors:** Sometimes, customers will accidentally use a tenant ID belonging to the wrong environment (e.g.: the Microsoft PPE tenant `f686d426-8d16-42db-81b7-ab578e110ccd` doesn't exist in the Public Azure environment `https://login.windows.net`). When the underlying `HttpDocumentRetriever` calls `https://login.windows.net/f686d426-8d16-42db-81b7-ab578e110ccd/.well-known/openid-configuration`, it gets back a `400 BadRequest` error (`AADSTS90002: Tenant 'f686d426-8d16-42db-81b7-ab578e110ccd' not found.`). We want to surface this to the customer as a `401 Unauthorized` error with some appropriate error code (e.g.: `InvalidTenant`).

Currently, our service is unable to distinguish between the above two classes of errors. In both scenarios, the underlying ConfigurationManager/HttpDocumentRetriever throws an `InvalidOperationException` with an `IDX208xx`-level error code. **Could the error handling for this API be improved so that we can distinguish between these two types of errors?** It would be great if the thrown exception could surface additional data, such as the following:
- **HTTP status code** (e.g.: `400 BadRequest` or `500 InternalServerError`).
- **Error message** (assuming that PII can be sanitized without making the error message useless).
- **Correlation ID** (for the scenario where our DevOps engineers need to escalate a legitimate outage and provide eSTS/AAD a correlation ID for some incident).

**Internal tracking**
- [Product Backlog Item 1601972](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1601972 ): Better error handling for MetadataManager.GetOidcConfigurationAsync
  - [Product Backlog Item 1509137](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1509137): Create new exception type that contains errors from ESTS and add as InnerException to AuthenticationException

**Comment by brentschmaltz** [comment]
@ciaozhang this would work similar to the feature of returning IdentityProvider errors.
