### ISSUE TITLE
Support ECDH-ES Key Agreement

### ISSUE THREAD

**Issue by cesarpayan** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1726]
Currently there's no support for ECDH-ES as noted in this [issue ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1666)

Given the increase in usage of this algorithm we should support it instead of leaving it to users to implement via extension. 

We should support:
ECDH-ES+A128KW
ECDH-ES+A192KW
ECDH-ES+A256KW

Direct or symmetric key wrap

**Comment by he1994** [comment]
Notice that this task has been added as a 'To do' on the project board, is there a rough estimation when the support for ECDH-ES Key Agreement will be ready to be released?

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1866
