### ISSUE TITLE
Broken link. Use updated rfc link 

### ISSUE THREAD

**Issue by jsquire** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1728]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#24757](https://github.com/Azure/azure-sdk-for-net/issues/24757).

## Details

`http://tools.ietf.org/html/rfc7517#section-4` is no longer valid.  Use `https://datatracker.ietf.org/doc/html/rfc7517#section-4.2`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10d05e86-c1d9-aa61-e2d7-a940828f5175
* Version Independent ID: b8db8e73-678d-e138-2250-952f2c5de3c7
* Content: [JsonWebKeyUseNames Class (Microsoft.IdentityModel.Tokens) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.jsonwebkeyusenames?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Tokens/JsonWebKeyUseNames.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Tokens/JsonWebKeyUseNames.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jennyf19** [comment]
Included in [6.14.0 release](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.14.0)
