### ISSUE TITLE
Helpful information replaced with "System.String" in SecurityTokenInvalidIssuerException message

### ISSUE THREAD

**Issue by fschmied** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1732]
When you set up OpenID Connect with an invalid issuer (as happens easily, e.g., when configuring OpenID Connect with Azure AD see #1731), you get a `SecurityTokenInvalidIssuerException` that has all the helpful values replaced with "System.String": `IDX10205: Issuer validation failed. Issuer: 'System.String'. Did not match: validationParameters.ValidIssuer: 'System.String' or validationParameters.ValidIssuers: 'System.String'.`

This is really sad, as the original message of `IDX10205: Issuer validation failed. Issuer: 'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0'. Did not match: validationParameters.ValidIssuer: 'null' or validationParameters.ValidIssuers: 'https://login.microsoftonline.com/{tenantid}/v2.0'.` would have put me on the right track much faster.

This happens in an effort to remove personally identifiable information (PII) in LogHelper.FormatInvariant` resp. `LogHelper.RemovePII`. However, these values are not personal identifiable information.

**Comment by jennyf19** [comment]
@fschmied I think the issuer could include the domain or tenantId, which is OII, so PII for us. I agree that the message is not helpful, as I've ran into it a lot as well. Would an aka.ms link showing how to add PII logs w/additional information be helpful or do you have another suggestion?

**Comment by fschmied** [comment]
@jennyf19 I see. How about changing it to something like this? `IDX10205: Issuer validation failed because the actual issuer didn't match the valid issuer(s). Issuer: 'System.String (value removed)'. Did not match: validationParameters.ValidIssuer: 'System.String (value removed)' or validationParameters.ValidIssuers: 'System.String (value removed)'. PII protection removed values from this message. Enable PII logging via ... to see them.`

**Comment by jennyf19** [comment]
Included in [6.14.0 release](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.14.0)
