### ISSUE TITLE
Add default values in TokenValidationParameters.xml

### ISSUE THREAD

**Issue by jsquire** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1735]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#24854](https://github.com/Azure/azure-sdk-for-net/issues/24854).

## Details

Please include the default values in the documentation. How I supposed to know if need to specify the value for the the parameter if I don't know the default value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 522dd94f-d005-9cd0-0643-cd08b852c65b
* Version Independent ID: 855896f3-cff5-7d6f-153e-8413fdae508e
* Content: [TokenValidationParameters Class (Microsoft.IdentityModel.Tokens) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by venkateshkocherlakota** [comment]
Hi @jennyf19 and @KirillBorunov, Good day! 
@KirillBorunov - Could you please share the parameters for which default values are expected.
@jennyf19 - Could you please help me with the default values that are being expected.

**Comment by KirillBorunov** [comment]
> Hi @jennyf19 and @KirillBorunov, Good day! @KirillBorunov - Could you please share the parameters for which default values are expected. @jennyf19 - Could you please help me with the default values that are being expected.

ClockSkew
IgnoreTrailingSlashWhenValidatingAudience
NameClaimType
RequireAudience
RequireExpirationTime
RequireSignedTokens
RoleClaimType
SaveSigninToken
TryAllIssuerSigningKeys
ValidAlgorithms
ValidateActor
ValidateAudience
ValidateIssuer
ValidateIssuerSigningKey
ValidateLifetime
ValidateTokenReplay
ValidTypes

**Comment by brentschmaltz** [comment]
@jsquire the summary comments cover most of these items. I am not sure what the ask is?

**Comment by jsquire** [comment]
@brentschmaltz:  Please be aware that my role was only transferring as part of triage for the Azure SDK repository.   You'll want to direct questions to the author of the original issue, @KirillBorunov.

**Comment by brentschmaltz** [comment]
@KirillBorunov the summary comments cover most of these items. I am not sure what the ask is?

**Comment by KirillBorunov** [comment]
> @KirillBorunov the summary comments cover most of these items. I am not sure what the ask is?

What comments? Where they are? I don't see them on the documentation page where the items are listed nor in the documentation pages of each item.

I'm asking for the default value. For example: ValidateIssuer, is true or false by default when TokenValidationParameters instance is created? NameClaimType is "" or is "sub"? and so on...
I need to know what parameters I need to specify a value if the default is not what I need. But if I don't know the default value then I need to specify them all?

**Comment by brentschmaltz** [comment]
@KirillBorunov they are in the Summary comments;
From xml metadata
```cs
        //
        // Summary:
        //     Gets or sets a boolean to control if the lifetime will be validated during token
        //     validation.
        //
        // Remarks:
        //     This boolean only applies to default lifetime validation. If Microsoft.IdentityModel.Tokens.TokenValidationParameters.LifetimeValidator
        //     is set, it will be called regardless of whether this property is true or false.
        [DefaultValue(true)]
        public bool ValidateLifetime { get; set; }
```
Some defaults are missing, but not all.
I am asking you to be specific.

It looks like the documentation is not in sync with Summary comments
For example: https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validatelifetime?view=azure-dotnet
Doesn't specify the default.

**Comment by jennyf19** [comment]
@brentschmaltz I don't think there is a default xml tag, @jmprieur would know for sure. We'd have to move the default to the XML explicitly, so it shows up in the doc.

**Comment by brentschmaltz** [comment]
@jennyf19 the code i posted was from the xml metadata when i right-clicked to an external dll.
You are saying we also need to add details to the xml summary comments.

**Comment by jennyf19** [comment]
yes, correct.

**Comment by KirillBorunov** [comment]
> @KirillBorunov they are in the Summary comments; From xml metadata
> 
> ```cs
>         //
>         // Summary:
>         //     Gets or sets a boolean to control if the lifetime will be validated during token
>         //     validation.
>         //
>         // Remarks:
>         //     This boolean only applies to default lifetime validation. If Microsoft.IdentityModel.Tokens.TokenValidationParameters.LifetimeValidator
>         //     is set, it will be called regardless of whether this property is true or false.
>         [DefaultValue(true)]
>         public bool ValidateLifetime { get; set; }
> ```
> 
> Some defaults are missing, but not all. I am asking you to be specific.
> 
> It looks like the documentation is not in sync with Summary comments For example: https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validatelifetime?view=azure-dotnet Doesn't specify the default.

Ok, I did not know that attribute even exists.
My flow was:
1) I type: var test = new TokenValidationParameters();
2) I start typing: test.ValidateLifetime (the tooltip shows a short description about that property, no default value here).
3) When the line is complete: test.ValidateLifetime = true; I put the cursor over the property and VS shows a long description, but no default value.
4) I go to the documentation, no default value.

From now I will check these attributes, but I thing it should be in the documentation.

The properties without the DefaultValue attribute:
ValidAlgorithms
AuthenticationType
RoleClaimType
NameClaimType
ValidTypes
