### ISSUE TITLE
Add a non-LRU Provider Cache

### ISSUE THREAD

**Issue by dannybtsai** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1742]
The event based LRU cache implementation is designed to keep the most frequently used providers in the cache and evict the least used ones. This is more complicated and requires starting background tasks to process events. For some users who have a small number of providers this might not be needed as the cache is never full.
This task is for implementing a simpler and more lightweight non-LRU cache.

**Comment by brentschmaltz** [comment]
We will cover this under: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1782
