### ISSUE TITLE
IssuerValidator Delegate: Better documentation for custom validators

### ISSUE THREAD

**Issue by timo352** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1749]
[TokenValidationParameters.cs](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/3d152e470b167c6e9fce2c302496a3536e3987d8/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L81)

Right now the documentation for `IssuerValidator` does not specify how validation works. Based on the summary doc, I'd guess that the Issuer would be compared to whatever string I returned.

![image](https://user-images.githubusercontent.com/16926224/139715632-13effc59-2fe9-4a89-86fb-8c54cc520121.png)

Reading through the calling code, it looks like what is actually expected is throwing an exception if the issuer isn't valid. The remarks should mention this.

```
try
{
    Validators.ValidateIssuer(securityToken.Issuer, securityToken, validationParameters);
    validIssuer = true;
}
catch (Exception)
{
     // validIssuer will remain false
}
```

**Comment by timo352** [comment]
Happy to close if there is some documentation I'm missing - like a higher level coding style I'm unaware of.

**Comment by jennyf19** [comment]
@timo352 Is this what you are looking for? https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/ValidatingTokens#aadissuervalidator

**Comment by timo352** [comment]
> @timo352 Is this what you are looking for? https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/ValidatingTokens#aadissuervalidator

Yep, that's perfect. Thanks for providing that.
