### ISSUE TITLE
Add back ...xyzException(SerializationInfo info, StreamingContext context) for 4.5.x and desktop

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#175]
These constructors should be added back but #ifdef'd for FxCore.

**Comment by tushargupta51** [comment]
I think we missed the ctor here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KRelease/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Exceptions/OpenIdConnectProtocolException.cs#L64

All other oidc exception classes have these ctors inside "#if DESKTOPNET45" which I am not sure is the right target.

Please check the ctor for exception classes in Microsoft.IdentityModel.Tokens project too.
