### ISSUE TITLE
Broken links tools.ietf.org/html/

### ISSUE THREAD

**Issue by cesarpayan** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1750]
In code there are still links provided in comments that point to tools.ietf.org/html/ resources

These links redirect to datatracker.ietf.org/doc/html and either fail to redirect or redirect. Providing the link to datatracker.ietf.org would minimize the risk of the failure to redirect happening.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1774
