### ISSUE TITLE
[Bug] AadIssuerValidator doesn't work well with multiple auth schemes in ASP.NET Core

### ISSUE THREAD

**Issue by galhag** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1752]
**Which version of Microsoft Identity Web are you using?**
Microsoft.Identity.Web 1.18

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [x] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
We wanted to our production apps to start use Microsoft.Identity.Web,
Out flow contains S2S and the web api, should accept tokens from two tenants.
We currently use the AddJwtBearer, against two tenants, using two schemas.
When we try to achieve the same using the Microsoft.Identity.Web we are not able to get both tenants to work.

**Repro**
We have two tenants in AAD, tenantA, tenantB
and our appsettings contains two sections AzureAdA, AzureAdB with the relevant details.
We use S2S tokens, with roles for authorization, and constructing the relevant policy two work against both tenants.
When we set the app to work with only section A it works and accepts the tenantA tokens,
When we set it with section B only, it works as well and accepts the tenantB tokens,.
When we use both, it fails for tenantB.

asp dotnet core 3.1 web api with aad authentication
install the Microsoft.Identity.Web  package 
appsettings should contain two AzureAd sections (AzureAdA & AzureAdB) for two aad tenants
Run the app, and try to access the api with tenantA token,
then with tenantB token.
tenantB fails.

In the below code, if you change tenants to only have one entry, it works against the single tenant.

Add the below ConfigureServices.

```csharp
public void ConfigureServices(IServiceCollection services)
        {

            var tenants= new List<(string section, string schema)>
            {
                ("AzureAdA", "schemaA"),
                ("AzureAdB", "schemaB")
            };
            
            var auth = services.AddAuthentication();
            foreach(var (section, schema) in tenants)
            {
                auth.AddMicrosoftIdentityWebApi(Configuration, section, schema);
                services.AddControllers();
                services.Configure<JwtBearerOptions>(schema, options =>
                {
                    options.Events.OnAuthenticationFailed += context =>
                    {
                        Console.WriteLine($"{schema} FAILURE: {context.Exception}");
                        return Task.CompletedTask;
                    };
                });
            }
            
            services.AddAuthorization(options => 
                options.DefaultPolicy = new AuthorizationPolicyBuilder( tenants.Select(t => t.schema).ToArray())
                    .RequireAuthenticatedUser()
                    .Build());
        }
```

**Expected behavior**
We expect apps from both tenants to be authenticated.

**Actual behavior**
Apps from second tenant, tenantB,  fail with 401
looking on the jwt event for failure the reason is: 
 _Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'System.String'. Did not match: validationParameters.ValidAudience._

**Possible solution**

**Additional context / logs / screenshots**
This is the error from the auth faillure.

Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDW10303: Issuer: 'https://sts.windows.net/{tenantB}/', does not match any of the valid issuers provided for this application.
   at Microsoft.Identity.Web.Resource.AadIssuerValidator.Validate(String actualIssuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateIssuer(String issuer, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

**Comment by jmprieur** [comment]
@galhag you can specify the expected `Audience` for your app in the sections of your appsettings,json (Audience)
you can enable PII to see what audience was requested by your client, and which was registered in the app registration (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII)

**Comment by galhag** [comment]
I think I see the root cause, 

MicrosoftIdentityIssuerValidatorFactory is being added as a singleton
When the MicrosoftIdentityIssuerValidatorFactory.GetAadIssuerValidator gets hit the first time the issuer is being added to the concurrent doctionary where the key is the authorityHost, in our case login.microsoftonline.com, with a validator against the first tenant issuer.

It fails the validation for the first tenant, 
but in the validation against the second tenant, the key is already in the dictionary, and the validator is re used,
but in this case the validator picked up is against the first tenant issuer.

```
        public AadIssuerValidator GetAadIssuerValidator(string aadAuthority)
        {
            if (string.IsNullOrEmpty(aadAuthority))
            {
                throw new ArgumentNullException(nameof(aadAuthority));
            }

            Uri.TryCreate(aadAuthority, UriKind.Absolute, out Uri? authorityUri);
            string authorityHost = authorityUri?.Authority ?? new Uri(Constants.FallbackAuthority).Authority;

            if (_issuerValidators.TryGetValue(authorityHost, out AadIssuerValidator? aadIssuerValidator))
            {
                return aadIssuerValidator;
            }
            
            _issuerValidators[authorityHost] = new AadIssuerValidator(
                AadIssuerValidatorOptions,
                HttpClientFactory,
                aadAuthority);

            return _issuerValidators[authorityHost];
        }
```

I think the key here should be against the issuer uri, not just the host.

**Comment by jennyf19** [comment]
@galhag included in [M.IM.Validators 6.14.1 release](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.14.1) and will be in the Id Web 1.19.1 release, hopefully later today or tomorrow (11.5)
