### ISSUE TITLE
Default outbound map issue

### ISSUE THREAD

**Issue by jsquire** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1773]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#25274](https://github.com/Azure/azure-sdk-for-net/issues/25274).

## Details

There appears to be a bug in the default outbound map for http://schemas.microsoft.com/2012/12/certificatecontext/extension/authoritykeyidentifier: it maps to "certauthority key identifier" (with spaces).

The inbound map has "certauthoritykeyidentifier" (no spaces).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d69c6c7-cf53-6725-e0c1-814838f34c9f
* Version Independent ID: 7d632897-4ce5-d90e-e742-2bb26386708f
* Content: [JwtSecurityTokenHandler.OutboundClaimTypeMap Property (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytokenhandler.outboundclaimtypemap?view=azure-dotnet#System_IdentityModel_Tokens_Jwt_JwtSecurityTokenHandler_OutboundClaimTypeMap)
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by brentschmaltz** [comment]
@ihorwill can you help out by providing a pointer to a spec that defines the claim name?

**Comment by ihorwill** [comment]
Sorry - missed this in my inbox.

No, I am not aware of a spec for it. The primary problem is that the
mapping is not symmetric between the inbound and outbound maps.

Kind regards,
Ian

**Comment by brentschmaltz** [comment]
@ihorwill i put a breakpoint on this test, examined handler.OutboundClaimTypeMap and didn't see any spaces.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b24470757799a9d1d75f5f16314857f6bdc444d8/test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs#L450
The OutboundClaimTypeMap is created from the InboundClaimTypeMap here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b24470757799a9d1d75f5f16314857f6bdc444d8/src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs#L124

**Comment by brentschmaltz** [comment]
@jsquire closing this as i am not able to see an issue. Is there a sample that shows this happening?

**Comment by jsquire** [comment]
Hi @brentschmaltz.   Please be aware that my role was only to perform triage for the Azure SDK repository;  @ihorwill is the author of the original issue and is the person that you'd want to mention for any replies or inquiries.
