### ISSUE TITLE
Add public IList<SecurityKey> GetSigningKeys()

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#178]
We are moving away from SecurityTokens for signing and landing on SecurityKeys.
Adding this API to 4.x will help users migrate.

**Comment by brentschmaltz** [comment]
If we can .net 4.5 users can use our 5.x packages, this is not necessary.

**Comment by tushargupta51** [comment]
@brentschmaltz now that, .net 4.5 users can use wilson 5.x, can we close this?

**Comment by brentschmaltz** [comment]
Yes, let's close.
