### ISSUE TITLE
AadIssuerValidator throws System.NullReference exception 

### ISSUE THREAD

**Issue by RojaEnnam** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1781]
AadIssuerValidator throws System.NullReference exception when configuration is not set [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b24470757799a9d1d75f5f16314857f6bdc444d8/src/Microsoft.IdentityModel.Validators/AadIssuerValidator/AadIssuerValidator.cs#L153)

**Comment by brentschmaltz** [comment]
This is fixed in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1779
