### ISSUE TITLE
Our NuGet package dependencies need to be updated so that Microsoft.IdentityModel.* packages rely on an explicit version

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1794]
For a given version of a Microsoft.IdentityModel.* package, we currently require other packages from the library to be **greater than or equal to** that version. This can result in a MissingMethodException when there is a version mismatch (due to internal methods being modified), and it isn't necessarily clear to consumers why this is occurring. We should modify this so that **a specific version** of Microsoft.IdentityModel.* is required across all packages.

**Comment by jennyf19** [comment]
closing as duplicate
