### ISSUE TITLE
[Bug]  System.IdentityModel.Tokens.Jwt 6.15.0 publishing  always 6.14.1

### ISSUE THREAD

**Issue by jaelys** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1796]
In .NET 6
Nuget
System.IdentityModel.Tokens.Jwt package 6.15.0
rely
Microsoft.IdentityModel.JsonWebTokens.dll 6.15.0
Microsoft.IdentityModel.Tokens 6.15.0

Debug and Release compiled version of dll is normally 6.15.0
When publishing , the operation will be abnormal
could not load file or assembly system.identitymodel.tokens.jwt

The dll version is always 6.14.1

**Comment by brentschmaltz** [comment]
@jaelys I am not able to understand the issue, please reopen with additional details if this is still an issue.
