### ISSUE TITLE
[Bug] ValidateToken method incorrectly splitting token

### ISSUE THREAD

**Issue by risogolo** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1805]
System.IdentityModel.Tokens.Jwt package 6.15.1

Token is incorrectly splitted during validation in ValidateToken method, when splitting by dot sign (checking amount of token parts) 
my "iss" contains dots in https://sts.windows.net/xxxxxxxxxxxxxxxxxxxxxxxx/ therefore it is incorrectly splitted and then contains 6 token parts instead of 5

**Comment by brentschmaltz** [comment]
@risogolo can you provide us with a sample of the token?
thanks.

**Comment by risogolo** [comment]
{"typ":"JWT","alg":"RS256","x5t":"Mr5-AUibfBii7Nd1jBebaxboXW0","kid":"Mr5-AUibfBii7Nd1jBebaxboXW0"}.{"aud":"api://xxx","iss":"https://sts.windows.net/xxx/","iat":1642698948,"nbf":1642698948,"exp":1642704173,"acr":"1","aio":"AWQAm/8TAAAAy+IWjY/GgfcKW26lSZ4GeHDYeYjSFqehZGxI7uKpPws8OQeZEDH8NqJQLjAiWWBA4rppmFC1mz+CbsJIeM5NgjfBEJG02EwLUeN3UA6VkaObwlBm2maBe9amGDxIbbYt","amr":["pwd"],"appid":"xxx","appidacr":"0","email":"xxx@xxx.com","family_name":"xxx","given_name":"xxx","groups":["8ee812a8-3c0b-4827-b43e-ae026894e8db","6ffd0bb6-225f-4c43-9165-ce155d8e930c"],"idp":"live.com","ipaddr":"1.1.1.1","name":"xxx","oid":"xxxx","rh":"0.AU8A1eyYqiJNiEancCRcYo8-oJzYK3EP6NtIiFGUNYIiDX1PAPY.","roles":["Administrator"],"scp":"RolesScope","sub":"jw2l9WDa0MwJn4pCVC69jvwgKaoVWk1LYVtTllyI1ws","tid":"aa98ecd5-4d22-4688-a770-245c628f3ea0","unique_name":"live.com#xxx@xxx.com","uti":"9BKfaH3-W0KWTd3HwowkAA","ver":"1.0"}

it crates token part that contains string "windows" because it is between 2 dots, also there is lot more dots, I guess you nueed to split with dots that are outside of the curly brackets only

**Comment by brentschmaltz** [comment]
@risogolo closing as we believe that ver 7.x will take care of this.
