### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dommorin** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1815]
**Which version of Microsoft.IdentityModel are you using?**
6.16.0

**Where is the issue?**
 * [ X ] M.IM.Tokens

**Is this a new or an existing app?**
Existing App : bing chat aka Sydney from Turing team

**Repro**

```csharp
    using System;
    using System.Collections.Generic;
    using System.IdentityModel.Tokens.Jwt;
	using Microsoft.IdentityModel.Tokens;
    using System.Linq;
    using System.Security.Claims;
    using System.Security.Cryptography;
					
public class Program
{
	public static void Main()
	{
		string token;
		var audience = "www.mysite.com";
		var issuer = "me";
		string rsaKeyXml;
		using (var rsaProvider = new RSACryptoServiceProvider(2048))
		{
			rsaKeyXml = rsaProvider.ToXmlString(true);
			var rsa = new RsaSecurityKey(rsaProvider);
			var tokenDescriptor = new SecurityTokenDescriptor()
			{
				Expires = DateTime.UtcNow.AddSeconds(3600),
				Audience = audience,
				Issuer = issuer,
				SigningCredentials = new SigningCredentials(rsa, SecurityAlgorithms.RsaSha256Signature),
				IssuedAt = DateTime.UtcNow,
			};

			var tokenhandler = new JwtSecurityTokenHandler();
			token = tokenhandler.CreateEncodedJwt(tokenDescriptor);
		}
		
		Authorize(token, rsaKeyXml, audience, issuer);
		Console.WriteLine("No problem authorizing token first time");
		Authorize(token, rsaKeyXml, audience, issuer);
		Console.WriteLine("No problem authorizing token second time");
	}
	
	private static void Authorize(string token, string rsaKeyXml, string audience, string issuer)
	{
		using (var rsaProvider = new RSACryptoServiceProvider(2048))
		{
			rsaProvider.FromXmlString(rsaKeyXml);
			var rsa = new RsaSecurityKey(rsaProvider);
			TokenValidationParameters validationParameters = new TokenValidationParameters()
			{
				ValidIssuer = issuer,
				ValidAudiences = new string[] { audience },
				IssuerSigningKey = rsa,
			};
			var tokenhandler = new JwtSecurityTokenHandler();
			tokenhandler.ValidateToken(token, validationParameters, out var _);
		}
	}
}
```

**Expected behavior**
Token is authorized successfully on demand, without having to worry about what instance of RSACryptoServiceProvider is used.

**Actual behavior**
Upon second time we try to authenticate with a different RSACryptoServiceProvider instance, with the exact same code, we get the following exception:
Unhandled exception. Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10503: Signature validation failed. Token does not have a kid. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: '', InternalId: '2850HlLwc_fWY4qaZFim_m6wU9tHqGp0dt7-i_4DfOQ'. , KeyId: 
'. Number of keys in TokenValidationParameters: '1'. 
Number of keys in Configuration: '0'. 
Exceptions caught:
 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RSA'.
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.ThrowIfDisposed()
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.GetKey()
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.VerifyHash(ReadOnlySpan`1 hash, ReadOnlySpan`1 signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash(ReadOnlySpan`1 hash, ReadOnlySpan`1 signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.VerifyWithRsa(Byte[] bytes, Byte[] signature)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.Verify(Byte[] bytes, Byte[] signature)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify(Byte[] input, Byte[] signature)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters, BaseConfiguration configuration)
'.
token: '{"alg":"RS256","typ":"JWT"}.{"nbf":1645669923,"exp":1645673523,"iat":1645669923,"iss":"me","aud":"www.mysite.com"}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken& signatureValidatedToken, ExceptionDispatchInfo& exceptionThrown)
--- End of stack trace from previous location ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Program.Authorize(String token, String rsaKeyXml, String audience, String issuer)
   at Program.Main()
Command terminated by signal 6

**Possible solution**
n/a

**Additional context / logs / screenshots / links to code**
As a workaround we wrap RSACryptoServiceProvider in a singleton service class and use the same instance whenever we need to authorize a JWT token with RSA algorithm.

**Comment by brentschmaltz** [comment]
@dommorin you have hit an issue where we have cached the SignatureProvider and you have disposed of the RSA object that the SignatureProvider is using.

Of course all of this is happening underneath your code and is hard to understand why.

I rewrote your code to use RSAParameters instead of rsa and it is all good.
```cs
    // https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1815
    public class WilsonIssue1815
    {
        public static void Run()
	{
		string token;
		var audience = "www.mysite.com";
		var issuer = "me";
		string rsaKeyXml;
		RSAParameters rsaParameters;
		using (var rsaProvider = new RSACryptoServiceProvider(2048))
		{
			rsaParameters = rsaProvider.ExportParameters(false);
			var rsa = new RsaSecurityKey(rsaProvider);
			var tokenDescriptor = new SecurityTokenDescriptor()
			{
				Expires = DateTime.UtcNow.AddSeconds(3600),
				Audience = audience,
				Issuer = issuer,
				SigningCredentials = new SigningCredentials(rsa, SecurityAlgorithms.RsaSha256Signature),
				IssuedAt = DateTime.UtcNow,
			};

			var tokenhandler = new JwtSecurityTokenHandler();
			token = tokenhandler.CreateEncodedJwt(tokenDescriptor);
		}

		Authorize(token, rsaParameters, audience, issuer);
		Console.WriteLine("No problem authorizing token first time");
		Authorize(token, rsaParameters, audience, issuer);
		Console.WriteLine("No problem authorizing token second time");
	}

	private static void Authorize(string token, RSAParameters rsaParameters, string audience, string issuer)
	{
		try
		{
			var rsa = new RsaSecurityKey(rsaParameters);
			TokenValidationParameters validationParameters = new TokenValidationParameters()
			{
				ValidIssuer = issuer,
				ValidAudiences = new string[] { audience },
				IssuerSigningKey = rsa,
			};
			var tokenhandler = new JwtSecurityTokenHandler();
			tokenhandler.ValidateToken(token, validationParameters, out var _);
		}
		catch(Exception ex)
		{
			Console.WriteLine($"Exception: '{ex}'.");
                }
    }
}
```

**Comment by brentschmaltz** [comment]
@dommorin while the workaround may work, i will leave this open as our runtime could work better if we didn't cache a signature provider in these cases. 
That is where the user is providing an object that could be disposed of.
However, making this the default behavior would have a performance penalty for users that do not dispose.

**Comment by campersau** [comment]
I just hit the same issue using `RSA` instead of `RSACryptoServiceProvider`.


```c#
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography;

internal class Program
{
    private static string PublicKeyPem;
    private static string PrivateKeyPem;

    private static void Main(string[] args)
    {
        using (var rsa = RSA.Create())
        {
            PublicKeyPem = rsa.ExportRSAPublicKeyPem();
            PrivateKeyPem = rsa.ExportRSAPrivateKeyPem();
        }

        Test();
        Test();
        Test();

        Console.WriteLine("DONE");
    }

    static void Test()
    {
        using (var rsa = RSA.Create())
        {
            rsa.ImportFromPem(PublicKeyPem);
            rsa.ImportFromPem(PrivateKeyPem);

            var tokenDescriptor = new SecurityTokenDescriptor();
            tokenDescriptor.SigningCredentials = new SigningCredentials(new RsaSecurityKey(rsa), SecurityAlgorithms.RsaSha256); // this does not work
            //tokenDescriptor.SigningCredentials = new SigningCredentials(new RsaSecurityKey(rsa.ExportParameters(includePrivateParameters: true)), SecurityAlgorithms.RsaSha256); // this works

            new JwtSecurityTokenHandler().CreateEncodedJwt(tokenDescriptor);
        }
    }
}
```

Throws

```
System.ObjectDisposedException
  HResult=0x80131622
  Nachricht = Cannot access a disposed object.
ObjectDisposed_ObjectName_Name
  Quelle = System.Security.Cryptography
  Stapelüberwachung:
   bei System.Security.Cryptography.CngAlgorithmCore.ThrowIfDisposed()
   bei System.Security.Cryptography.CngAlgorithmCore.GetOrGenerateKey(Int32 keySize, CngAlgorithm algorithm)
   bei System.Security.Cryptography.RSACng.get_Key()
   bei System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   bei Microsoft.IdentityModel.Tokens.AsymmetricAdapter.SignWithRsa(Byte[] bytes)
   bei Microsoft.IdentityModel.Tokens.AsymmetricAdapter.Sign(Byte[] bytes)
   bei Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Sign(Byte[] input)
   bei Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   bei System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection, String tokenType, IDictionary`2 additionalHeaderClaims, IDictionary`2 additionalInnerHeaderClaims)
   bei System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityToken(SecurityTokenDescriptor tokenDescriptor)
   bei System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedJwt(SecurityTokenDescriptor tokenDescriptor)
   bei Program.Test() in C:\source\repos\ConsoleApp44\ConsoleApp44\Program.cs: Zeile36
   bei Program.Main(String[] args) in C:\source\repos\ConsoleApp44\ConsoleApp44\Program.cs: Zeile19
```

Workaround using  `ExportParameters` / `RSAParameters` does work.

**Comment by brentschmaltz** [comment]
closing as this pattern is not supported.

**Comment by fowl2** [comment]
@brentschmaltz could you clarify which pattern is not supported? There doesn't seem to be any warning in the [docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.jsonwebtokens.jsonwebtokenhandler.createtoken?view=msal-web-dotnet-latest).

Is it just to use `RSAParameters` instead of `RSA`?
