### ISSUE TITLE
HttpDocumentRetriever.GetDocumentAsync hangs in httpContext

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#183]
We missed a code path where this await should not be there as it blocks.
HttpResponseMessage response = await _httpClient.GetAsync(address, cancel).ConfigureAwait(false);
response.EnsureSuccessStatusCode();
return await response.Content.ReadAsStringAsync().ConfigureAwait(false);

HttpResponseMessage response = _httpClient.GetAsync(address, cancel).Result;
response.EnsureSuccessStatusCode();
return await response.Content.ReadAsStringAsync().ConfigureAwait(false);

**Comment by tushargupta51** [comment]
Fixed in 4.x: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/184

**Comment by dubscott** [comment]
Hi,
is there a way to see how this block would look like after the event has happened? I'm currently using version 1.0.2.202250711 from nuget but want to be sure that I'm experiencing the same problem before upgrading. 
My application occasionally hangs when executing ConfigurationManager.GetConfigurationAsync(CancellationToken ct). 
I haven't been able to step into the code in our Production environment when it happens (no debug symbols on symbolsource.com and when I compile locally the pdb file is not recognised). Though upon inspection at run-time, I can see that the ConfigurationManager's _docRetriever type is HttpDocumentRetriever so it seems likely but we don't experience the hang every time the app starts (when initially caching the configuration). ApplicationPool in IIS is set to recycle every 2 hours so unless I'm mistake, the configuration cache would never expire (_automaticRefreshInterval is set to default of 5 days)
We need to recycle the ApplicationPool to get the application back online. There is no real pattern as to when the problem occurs.

Any advice is greatly appreciated.
Scott

**Comment by brentschmaltz** [comment]
The deadlock happens when you call GetConfigurationAsync from within an Asp.Net method. Such as in a controller. From within the OWIN runtime, we have not seen deadlocks.

**Comment by dubscott** [comment]
UPDATE: I was able to replicate thanks to [this SO post](http://stackoverflow.com/questions/31243412/solving-onsendingheaders-deadlock-with-katana-openid-connect-middleware). The deadlock was indeed happening within the OWIN pipeline. Upgrading to version 1.0.2.206221351 from nuget got rid of the problem for me.

Thanks for providing the fix!
Scott

**Comment by brentschmaltz** [comment]
@dubscott thanks for confirming. Closing this issue.

**Comment by tushargupta51** [comment]
We need to fix this in 5.x.
