### ISSUE TITLE
[Documentation] Is JsonWebTokenHandler methods thread safe?

### ISSUE THREAD

**Issue by karataliu** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1837]
### Documentation related to component
[JsonWebTokenHandler](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs)

### Please check all that apply

- [ ] typo
- [ x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
To use JsonWebTokenHandler.ValidateTokenAsync in service, do we need to create a JsonWebTokenHandler instance per request or it is safe to use singleton JsonWebTokenHandler?

**Comment by brentschmaltz** [comment]
@karataliu ValidatetokenAsync is thread safe.
