### ISSUE TITLE
[Bug - Preview version] IIdentityLogger does not log information created before serviceProvider is available

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1845]
Only LogLevel.Trace works to log the first line (header) of the Wilson logs. This is because, for all the other log levels, the logger instance is not created yet. The logger instance in ASP.NET Core version requires an IServiceProvider, which is created in Id. Web [here](https://github.com/AzureAD/microsoft-identity-web/blob/jennyf/logger/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L186), but the static instances in Wilson have already been initialized by ASP.NET Core, so the NullIdentityModelLogger is getting created, which sets `IsEnabled` to false. Logging gets enabled later, but the initial messages are not capture.

FYI: @sruke @brentschmaltz @jmprieur

**Comment by jennyf19** [comment]
Is it a concern that the static constructor of the ConfigurationManager uses the static `LogHelper.LogVerbose` which uses `LogHelper.Logger`, are we sure that it will be initialized before it's used? Are static initializers guaranteed to be run in the correct order?

**Comment by jennyf19** [comment]
Todo (just ideas): 
- where else is a static constructor doing logging - are those logs important?
- impact in SAL?
- impact in MISE?
- option of subscribing to an event source (in Id Web)
- are static initializers guaranteed to be run in the correct order

**Comment by brentschmaltz** [comment]
@jennyf19 a static ctor is run the first time a type is accessed.

**Comment by sruke** [comment]
> 

Header information issue and missing logs issue where Logger is enabled later than expected are 2 separate issues.

Log level for header information is set to EventLevel.LogAlways. This level doesn't have an equivalent in ILogger's LogLevel enum and is currently mapped to LogLevel.Trace. That's why these logs are only seen at Trace level.  ILogger requires that each message has a log level defined and doesn't allow a message to be displayed always.

[This PR](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1843) modifies EventLevel from LogAlways to Information as that is the recommended log level for Identity libraries. Open to ideas on how it can be improved further.

**Comment by sruke** [comment]
ILogger is resolved via Dependency Injection (DI) using a ServiceProvider. AspNetCore team shared it is not possible to get an ILogger before serviceProvider is available. This means, any messages that are logged before serviceProvider is available will not be logged to AspNetCore's ILogger. Messages we're mainly concerned about are the ones logged in static constructors. Can we move these messages to another place? 

@jmprieur suggested that we enable an EventListener until a serviceProvide is available and flush the messages and disable it right after initializing LogHelper.Logger with an IIdentityLogger instance.

**Comment by sruke** [comment]
In Wilson, two static ctors - ConfigurationManager and JwtSecurityTokenHandler log messages. Both log AssemblyQualifiedName.

**Comment by sruke** [comment]
Created a separate issue for missing header information -
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1851

**Comment by sruke** [comment]
Verbose logs displayed by the static ctors are noisy and can be removed. The header information can be used as a substitute for view the Identity version.

Feature request was created to prefix error message with assembly version info to aid troubleshooting - https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1852
