### ISSUE TITLE
Add specific .NET 6 targets to projects.

### ISSUE THREAD

**Issue by AraHaan** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1854]
I am using a project that depends on SqlClient (local build which updates the nuget packages as well as targets .NET 6 explicitly), which depends on:
- Microsoft.Identity.Client (6.17.0)
- Microsoft.IdentityModel.JsonWebTokens (6.17.0)
- Microsoft.IdentityModel.OpenIdConnect (6.17.0)

It's all said and good, until I want to use .NET 6 and by surprise it uses the dependencies from the .NET Standard 2.0 target that adds needless package dependencies that can be avoided in .NET 6:
- Microsoft.CSharp (4.5.0)
- System.Security.Cryptography.Cng (4.5.0)

As such, I suggest to add specific .NET 6 targets that do not add packages for things already in the reference and runtime packs so consumers would get less files copied to their project's build output directories (that could potentially be outdated compared to the shared runtime's copy).

**Comment by brentschmaltz** [comment]
@AraHaan we are about to add a Net 3.1 target, which should get around the netstandard issue.
Afterwards, we will be adding a 6.0 target.

**Comment by AraHaan** [comment]
The Cng is in the .NET Core 3.1 framework reference?

**Comment by jmprieur** [comment]
What is Cng
.NET Core 3.1 is now out of support. you should probably move to .NET 6.0

**Comment by AraHaan** [comment]
Cng is System.Security.Cryptography.Cng which is in the runtime and ref packs in .NET 6.

**Comment by brentschmaltz** [comment]
@jmprieur should we add both 3.1 and 6.0 or just 6.0?

**Comment by AraHaan** [comment]
I think only 6.0 as 3.1 will be EOL by the end of the year.

**Comment by brentschmaltz** [comment]
@AraHaan
This [PR ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1866)added 6.0.
