### ISSUE TITLE
[FeatureRequest] Cache the previous "richer error details" in ConfigurationManager.GetConfigurationAsync.

### ISSUE THREAD

**Issue by adarce** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1858]
This feature request is a follow-up from [my previous feature request](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1714) (thanks for addressing that one!).

Consider a scenario where during token validation, we want to retrieve the `OpenIdConnectConfiguration` for a tenant-specific authority containing a tenant ID that does not exist by calling a URI like `https://login.windows.net/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/.well-known/openid-configuration`. Thanks to [this pull request](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1776), the underlying `HttpDocumentRetriever` now throws an `IOException` whose `Data` property contains the HttpStatusCode and full ResponseContent from the authority.

In `ConfigurationManager.GetConfigurationAsync`, there are currently two places where an IDX20803 exception can be thrown: at Line 176 and at Line 186 (see the below code snippet). The first time that `ConfigurationManager.GetConfigurationAsync` gets called, `_syncAfter` is `DateTimeOffset.MinValue`, so the IDX20803 exception at Line 176 gets thrown (which contains the inner exception) and `_syncAfter` is set to be (now + 5 minutes). But if `ConfigurationManager.GetConfigurationAsync` is called again with the same authority 2 minutes later, then the IDX20803 exception at Line 186 gets thrown instead, which doesn't contain an inner exception. Consequently, since the thrown exception is missing the rich details from its inner exception, our service is unable to distinguish if the error was due to client misconfiguration (e.g.: tenant not found) or some transient error (e.g.: networking issue).

**In this scenario, can the previous "richer error details" be cached so that if the 5 minute refresh interval hasn't elapsed yet, then an exception with better diagnostic information can be quickly thrown instead of a generic exception that is missing the richer error details?**

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/433f26b30b9b45adae9a9e7286edebf9222ba831/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L153-L186

**Comment by brentschmaltz** [comment]
@adarce that is a good idea and would help users.

**Comment by mancyc** [comment]
@ciaozhang when is this WI planned for?

**Comment by ciaozhang** [comment]
> @ciaozhang when is this WI planned for?

Will wrap up this work early next month.
