### ISSUE TITLE
[Bug] IDX10223 missing the date fields

### ISSUE THREAD

**Issue by ivanalfonso-msft** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1860]
Error message shows like:
`IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.`

**Comment by brentschmaltz** [comment]
@ivanalfonso-msft, what version are you using?
this is a result of PII being off.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII to turn PII on.
