### ISSUE TITLE
[Bug] Breaking change in 6.18.0 due to Always set 'cty==JWT' when creating a JWE.

### ISSUE THREAD

**Issue by ros-han-n** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1877]
**Which version of Microsoft.IdentityModel are you using?** 6.19.0
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [ x] M.IM.JsonWebTokens

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Repro**
Upgraded existing service to use 6.19.0 version of Microsoft.IdentityModel.JsonWebTokens

```csharp
            JwtHeader header = new JwtHeader(signingCredentials);
            header.Add("x5t", Base64UrlEncoder.Encode(clientCert.GetCertHash()));
            header.Add("x5c", System.Convert.ToBase64String(clientCert.Export(X509ContentType.Cert)));

            JwtPayload payload = new JwtPayload(
                clientId,
                audience,
                claims,
                DateTime.UtcNow,
                DateTime.UtcNow.Add(TimeSpan.FromHours(8)));
            var tokenDescriptor = new JwtSecurityToken(header, payload);
```

**Expected behavior**
Upgrading to 6.18.0 or higher should not cause breaking changes

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

Error message from MSAL library
{
    "error": "invalid_request",
    "error_description": "AADSTS5002726: Invalid JWT token. Found unsupported token header. Supported headers are: 'alg','typ','x5t','x5c','kid','use','enc','ctx','nonce','rh','kdf_ver','jku','jwk','x5u'\r\nTrace ID: f01313cf-7a14-4ccf-bad1-d2105442e100\r\nCorrelation ID: d66a3c1a-043b-4511-bb20-e6374bb74902\r\nTimestamp: 2022-06-14 04:39:59Z",
    "error_codes": [
        5002726
    ],
    "timestamp": "2022-06-14 04:39:59Z",
    "trace_id": "f01313cf-7a14-4ccf-bad1-d2105442e100",
    "correlation_id": "d66a3c1a-043b-4511-bb20-e6374bb74902"
}

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by brentschmaltz** [comment]
@ros-han-n 
We are going to be fixing this in our next release in a day or so.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1868
