### ISSUE TITLE
Refactor IConfigurationRetriever to be public

### ISSUE THREAD

**Issue by brockallen** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#188]
I'd like to replace this for the OIDC middleware with one that loads from a cache. The interface is currently internal and so my only options are to replace the entire ConfigurationManager or the IDocumentRetriever. ConfigurationManager is too coarse grained and IDocumentRetriever is too fine grained. 

I also noticed this is not injected into the ctor of the ConfigurationManager, so obviously there's some rework to support this request. It'd need to be properly injected (along with the document retriever).

I suspect you're not interested in doing this for Katana, but perhaps for ASP.NET 5.

**Comment by brentschmaltz** [comment]
Thanks.
We can fix this for Katana also since Katana just pulls in these assemblies.
Goal is to have a single nuget for 4.x and 5.
Will certainly do this for K.

**Comment by brockallen** [comment]
Thanks!

**Comment by brentschmaltz** [comment]
@tushargupta51 can you take care of this?

**Comment by tushargupta51** [comment]
Sure.

**Comment by tushargupta51** [comment]
@brockallen I made the interface public in #203 and changed the ctor for ConfigurationManager accordingly. The changes are made in 5.x only.

**Comment by brockallen** [comment]
Ok, thanks!

**Comment by zshift** [comment]
Is a fix for 4.x still planned, or will the change only be applied to 5.x?

**Comment by tushargupta51** [comment]
@zshift We still have plans to fix it in 4.x, though we don't any final dates yet for next 4.x release.

**Comment by brentschmaltz** [comment]
@ChenYan98 we will have to be careful that we don't break Katana users.
