### ISSUE TITLE
Not Able to work with Compiled code Micrososft.IdentityModel.Logging Setting ShowPII

### ISSUE THREAD

**Issue by SrikJagz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1881]
Hi, 

I have got Micrososft.IdentityModel.Logging 5.2.1 source code just to modify the ShowPII to true and so that I can collect additional Logs.  But the new compiled version is not working eventhough the .NETFramework (4.5.1) and DLL version are matching (5.2.1.050208)
The one taken from Nuget Package for this DLL is 31 KB while the compiled one is 15KB . I'm not sure where I'm missing.

Can someone please help me out

**Comment by jmprieur** [comment]
@sruke: can you please have a look?

**Comment by sruke** [comment]
You don't need the source code of Micrososft.IdentityModel.Logging to set ShowPII to true. 

You can instead do the following -
1. Add a reference to the NuGet Package Microsoft.IdentityModel.Logging in your project
2. Set IdentityModelEventSource.ShowPII = true; with in the project. 
   If on AspNetCore or OWIN, set this value in the Startup constructor.

Please note that by setting ShowPII to true you will see Personally Identifiable Information in the logs. Refer to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII

**Comment by brentschmaltz** [comment]
@SrikJagz please feel free to reopen if you are still seeing issues.

**Comment by SrikJagz** [comment]
Hi, 

Thanks a lot. I am able to fix this with your suggestions.

Regards,
Srikanth
