### ISSUE TITLE
[Bug] Library reports that AES256GCM is not supported in linux for .NET 6, but it seems to work just fine

### ISSUE THREAD

**Issue by EraYaN** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1882]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
6.19.0

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**

c. This is a new app

**Repro**

```csharp
var tokenValidParams = new TokenValidationParameters()
{
    ValidAlgorithms = new[] { SecurityAlgorithms.Aes256Gcm, SecurityAlgorithms.RsaOAEP, SecurityAlgorithms.RsaSha256 },
    ValidateIssuerSigningKey = true,
    IssuerSigningKey = _sigCredentials.Key, // X509SigningCredentials created from X509Certificate2
    TokenDecryptionKey = _encCredentials.Key, // X509EncryptingCredentialscreated from X509Certificate2
};
var result = tokenHandler.ValidateToken(<any GCM JWE>, tokenValidParams);
```
Example JWE header:
```
{
  "alg": "RSA-OAEP",
  "enc": "A256GCM",
  "typ": "JWT",
  "cty": "JWT",
  "kid": "<kid>",
  "x5t": "<x5t>"
}
```
**Expected behavior**
It should use the AesGcm class to decrypt the token if the AesGcm class reports that it is supported.

**Actual behavior**
Exception is throw with the message
"Encrytion/Decryption using algorithm 'A256GCM' is only supported on Windows platform"

Triggered by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/Encryption/AuthenticatedEncryptionProvider.cs#L86-L89=

**Possible solution**

`AesGcm` exposes a static property `IsSupported` https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm.issupported?view=net-6.0
That is probably a better source for throwing this error for the .NET 6 and 7 target.

I just tried this on a linux machine with the latest .NET 6 version and it returns True.

Maybe something like:
```
#if NETSTANDARD2_0
                    if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                        throw LogHelper.LogExceptionMessage(new PlatformNotSupportedException(LogHelper.FormatInvariant(LogMessages.IDX10713, LogHelper.MarkAsNonPII(algorithm))));
#elif NET6_0_OR_GREATER
                    if(!System.Security.Cryptography.AesGcm.IsSupported)
                        throw LogHelper.LogExceptionMessage(new PlatformNotSupportedException(LogHelper.FormatInvariant(LogMessages.IDX10713, LogHelper.MarkAsNonPII(algorithm))));
#endif
```
That will fail correctly on tvos and in the browser and such.

```csharp
Console.WriteLine(System.Security.Cryptography.AesGcm.IsSupported);
```

**Additional context / logs / screenshots / links to code**

**Comment by brentschmaltz** [comment]
@EraYaN i see, looks like we incorrectly applied the filtering.
@cesarpayan can you look into this.

**Comment by EraYaN** [comment]
I have created a PR to fix this issue for .NET 6 and up.
