### ISSUE TITLE
[Bug] Oracle IDCS not working over OpenID Connect protocol

### ISSUE THREAD

**Issue by mawasile** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1888]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [x] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
App in production using v5.3.0 but repro also in 6.20.0 
-->

**Repro**

```csharp
var metadataAddr
    = "https://idcs-<PII>.identity.oraclecloud.com/.well-known/idcs-configuration";
   

var openidConfiguration = await OpenIdConnectConfigurationRetriever.GetAsync(
    metadataAddr, 
    CancellationToken.None);

var authEndpoint = openidConfiguration.AuthorizationEndpoint;
if(authEndpoint == null)
{
    throw new Exception("missing auth endpoint!");
}
```

**Expected behavior**
authorization_endpoint and rest of the parameters should be read from discovery endpoint even if they are subnodes of the json structure that has beed returned

**Actual behavior**
values that are in the response json like authorization_endpoint are returned even if they are deeper in the json structure

**Possible solution**
Pare json in order to look for expected values 

**Additional context / logs / screenshots / links to code**
Oracle Cloud returns single json discovery response with OpenIdConnect values in a subnode (openid-configuration/authorization_endpoint). Example:

{
    
    "access-configuration": {
        "http_authentication_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/admin/v1/HTTPAuthenticator",
        "encryption_keys_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/admin/v1/EncryptionKeys",
        "password_authenticator_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/admin/v1/PasswordAuthenticator",
        "asserter_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/admin/v1/Asserter",
        "session_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/session/v1/Sessions",
        "session_validate_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/session/v1/SessionValidate",
        "session_refresh_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/session/v1/SessionRefresh",
        "secure_http_authentication_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/admin/v1/HTTPAuthenticator",
        "secure_encryption_keys_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/admin/v1/EncryptionKeys",
        "secure_password_authenticator_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/admin/v1/PasswordAuthenticator",
        "secure_asserter_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/admin/v1/Asserter",
        "secure_session_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/session/v1/Sessions",
        "secure_session_validate_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/session/v1/SessionValidate",
        "secure_session_refresh_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/session/v1/SessionRefresh"
    },
    **"openid-configuration": {**
        "issuer": "https://identity.oraclecloud.com/",
        **"authorization_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/oauth2/v1/authorize",**
        "token_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/oauth2/v1/token",
        "userinfo_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/oauth2/v1/userinfo",
        "revocation_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/oauth2/v1/revoke",
        "introspection_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/oauth2/v1/introspect",
        "end_session_endpoint": "https://idcs-<PII>.identity.oraclecloud.com/oauth2/v1/userlogout",
        "secure_authorization_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/oauth2/v1/authorize",
        "secure_token_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/oauth2/v1/token",
        "secure_userinfo_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/oauth2/v1/userinfo",
        "secure_revocation_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/oauth2/v1/revoke",
        "secure_introspection_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/oauth2/v1/introspect",
        "secure_end_session_endpoint": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/oauth2/v1/userlogout",
        "jwks_uri": "https://idcs-<PII>.identity.oraclecloud.com/admin/v1/SigningCert/jwk",
        "secure_jwks_uri": "https://idcs-<PII>.us-phoenix-idcs-2.secure.identity.oraclecloud.com/admin/v1/SigningCert/jwk",
        "scopes_supported": [
            "openid",
            "profile",
            "offline_access",
            "email",
            "address",
            "phone",
            "groups",
            "get_groups",
            "approles",
            "get_approles"
        ],
....
}

**Comment by brentschmaltz** [comment]
@mawasile the OpenIdConnectRetriever expects to see the metadata as per this specification: https://openid.net/specs/openid-connect-discovery-1_0.html
Is Oracle following this format?

**Comment by mawasile** [comment]
@brentschmaltz 
During the investigation with the customer, we found out that Oracle IDCS acctually has two endpoints. 
One not according to specification => https://idcs-<PII>.identity.oraclecloud.com/.well-known/idcs-configuration
and second one that is correct =>  https://idcs-<PII>.identity.oraclecloud.com/.well-known/openid-configuration

Feel free to close the issue as the second discovery endpoint can be used by the user.

**Comment by brentschmaltz** [comment]
@mawasile closing as Oracle endpoint not to spec.
