### ISSUE TITLE
[Bug] Unexpected fatal log about PII logging

### ISSUE THREAD

**Issue by esbenbjerre** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1898]
**Which version of Microsoft.IdentityModel are you using?**
6.20.0.0

**Where is the issue?**
 * [x] M.IM.Logging

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.

**Repro**
Create a new .NET Core app and use the identity framework.

**Expected behavior**
No fatal logs.

**Actual behavior**
Fatal log:
```
[06.29 10:23:48.3840] [FATAL] [14] [Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter] Microsoft.IdentityModel Version: 6.20.0.0. Date 06/29/2022 08:23:48. PII logging is OFF. See https://aka.ms/IdentityModel/PII for details.
```

I've tried to enable PII logging but then it just logs fatally that PII logging is ON. Why is this logged as a fatal error? It started happening after upgrading from 6.15 to 6.20.

**Comment by jennyf19** [comment]
@sruke I think we need to rethink having this log level just for capturing this log info.

**Comment by sruke** [comment]
Agreed. I think we should prefix the header information to the first message logged. Both can be separated by a new line to avoid confusion.
