### ISSUE TITLE
[Feature Request] Unmask properties that are NonPII to make log messages meaningful and for efficient troubleshooting

### ISSUE THREAD

**Issue by sruke** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1903]

**Comment by Blackclaws** [comment]
Just ran into this exact problem. There is PII logging on things like the JWT Token audience. While it might be that someone writes PII into the audience field this is usually _not_ the case as the audience should contain the intended service. Same as the issuer field which usually isn't a user.
