### ISSUE TITLE
[Bug] IDX10659 is thrown when using an X509Certificate with public key only on validating a JWT token

### ISSUE THREAD

**Issue by soerenmuehlbauer** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1910]
**Which version of Microsoft.IdentityModel are you using?**
6.21

**Where is the issue?**
 * S.IM.Tokens.Jwt

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**

1. Create a signed and encrypted jwt token using an X509Certificate (containing **private** and **public** key).
2. Try to validate the token with setting TokenValidationParameters.IssuerSigningKey and TokenValidationParameters.TokenDecryptionKey to an X509SecurityKey containing only a X509Certificate with the **public** key

**Expected behavior**
The token is validated fine

**Actual behavior**
error IDX10659 is thrown

**Additional context / logs / screenshots / links to code**
It seems that in case of decryption and finding the decryption keys CryptoProviderFactory.CreateKeyWrapProviderForUnwrap is called which then creates RsaKeyWrapProvider with willUnwrap set to true, which means creating an AsymmetricAdapter with requirePrivateKey == true. 
In my opinion we should not need the private key for decrypting the token. 
If I use the x5c cert with the private key it works as expected.

**Comment by brentschmaltz** [comment]
When a token that is encrypted, the public key is used.
When a token is decrypted, the private key is used.

**Comment by soerenmuehlbauer** [comment]
> When a token that is encrypted, the public key is used. When a token is decrypted, the private key is used.

You are right, I misinterpreted the rfc. Thank you!
