### ISSUE TITLE
[Bug] JwtRegisteredClaimNames is incomplete

### ISSUE THREAD

**Issue by dojoincom** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1911]
**Which version of Microsoft.IdentityModel are you using?**
6.21.0.0

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Expected behaviour**
Based on [this link](https://www.iana.org/assignments/jwt/jwt.xhtml) from IANA, there are more than eighty JWT claim names, but the `System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames` has twenty seven claim names. I needed to add user's roles to the token which in JWT is named "roles", but it is not available in the `JwtRegisteredClaimNames` struct.

**Actual behaviour**
`System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames` should have more JWT claim names.

**Additional context / logs / screenshots / links to code**
https://www.iana.org/assignments/jwt/jwt.xhtml
https://www.rfc-editor.org/rfc/rfc7643.html#section-4.1.2

**Comment by brentschmaltz** [comment]
@dorinung yes, there are additional claim names.
Not sure when we will add them all.

**Comment by brentschmaltz** [comment]
@dorinung closing as we have a duplicate #1598
