### ISSUE TITLE
Potential bug/doc request for obtaining graph tokens with ECC certificate assertions

### ISSUE THREAD

**Issue by kjkent** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1917]
Hi all,

Reposting this issue from https://github.com/AzureAD/microsoft-identity-web/issues/1809 on advice of a contributor there:

I hope this is the right repo to post this in. For the last couple of days I've been trying to figure out why we couldn't get our app to receive a token for the Microsoft Graph API. No matter how I tried, first with the msal-node library and then by manually constructing and sending JWT assertions, I couldn't figure it out.

_Edit: I have since wondered if JWTs for ECC certificates need to be signed differently to RSA certs in a way that msal-node doesn't handle and I haven't done in my manual code that works with RSA certs. I can post my code if that's appropriate/helpful_

The only error shown was the code "5000" and a message saying a server error had occurred.

It transpires that it's because we were using an ECC certificate. I got it reissued as 2048-bit RSA and it worked straight away.

I'm not sure if this is a bug report or a plea for this to be documented. The Azure Portal for the application allowed the potentially unsupported certificate to be uploaded, showing no signs of error.  I suppose it hinges on: is this expected behaviour?

All the best, and thanks.

**Comment by brentschmaltz** [comment]
@kjkent do you have a stack trace with messages?

**Comment by kjkent** [comment]
@brentschmaltz When I get the chance, I'll make a self-signed ECC cert and reproduce; I'll post the results here.

**Comment by kjkent** [comment]
@brentschmaltz apologies for the long silence -- work has been manic and I've been pulled onto other things. That said, I'm at a point where hopefully I should be able to try and recreate this in the next couple of weeks. What would be the best way to get a stack trace with the level of detail you're after? I recall that the Graph API just responded with something like a `400 - Bad Request`. I'll post my findings as soon as I get chance!

**Comment by brentschmaltz** [comment]
@kjkent closing a dup of #1878
