### ISSUE TITLE
Review if Thumbprints are failing because of 'casesensitivity'

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#192]
Customer reported to use a workaround: 

http://stackoverflow.com/questions/25593435/jwtsecuritytokenhandler-4-0-0-breaking-changes/25625447?noredirect=1#comment49933145_25625447

Check and see if we need to adjust for this.

Closing this requires tests to be written.

**Comment by tushargupta51** [comment]
@brentschmaltz I don't think this is an issue in 5.x. It seems to be related to ResolveIssuerSigningKey method which is not currently implemented in 5.x. We can drop this off of beta7 list I guess?

**Comment by ChenYan98** [comment]
This is not an issue in 4.x too. The customer should use correct SecurityKey or SecurityToken when setting TokenValidationParameters. In the reported issue, customer should use X509SecurityKey instead of RsaSecurityToken.
