### ISSUE TITLE
Binaries from package System.IdentityModel.Tokens.Jwt version 6.22 are showing a test publisher

### ISSUE THREAD

**Issue by eddynaka** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1926]
Hi,

I was looking at the last package that got produced and I saw this:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/16199012/184780149-4babbdf7-77ae-401e-bbab-79d86ee01d1d.png">

And I was expecting something like this:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/16199012/184780191-a7581d7f-decb-40da-ae7e-b1c6106983d4.png">

I don't see any issues with that, it is just strange.

**Comment by jmprieur** [comment]
@eddynaka  : would you have built the package locally? Or where did you get it from?

I'm not seeing the same as you:
![image](https://user-images.githubusercontent.com/13203188/184789569-79eecf5f-0e42-4415-865a-ce83e77563bc.png)

**Comment by eddynaka** [comment]
Hi @jmprieur ,

From nupkg manager, click in the binaries that you have in the package. In the lower window you will see the signed binary.

**Comment by brentschmaltz** [comment]
@eddynaka i see what you are saying, i checked back to 6.5.1 and see the same thing.
@jmprieur using Nuget Package Explorer i was able to confirm the signature details on the libraries are different that the signature on the package.

**Comment by brentschmaltz** [comment]
We have moved on to 7x, 6x is only taking security and important features.
