### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Sunnydc231** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1927]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [x] M.IM.JsonWebTokens
 * [x] M.IM.KeyVaultExtensions
 * [x] M.IM.Logging
 * [x] M.IM.ManagedKeyVaultSecurityKey
 * [x] M.IM.Protocols
 * [x] M.IM.Protocols.OpenIdConnect
 * [x] M.IM.Protocols.SignedHttpRequest
 * [x] M.IM.Protocols.WsFederation
 * [x] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [x] M.IM.Tokens.Saml
 * [x] M.IM.Validators
 * [x] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by jmprieur** [comment]
Closing as there is no repro step
