### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Sunnydc231** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1929]
#- [ ] - *@*Is********__[![image](https://user-images.githubusercontent.com/111330376/185028840-ceb9629f-8324-49e3-a1d1-4643a2ae462d.jpeg)]()__******** your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
- - - - [ ] #> ````
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmprieur** [comment]
Closing as there is no repro
