### ISSUE TITLE
[Bug] RefreshInterval is too long if no metadata has been retrieved (IDX20803)

### ISSUE THREAD

**Issue by ohadschn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1930]
**Which version of Microsoft.IdentityModel are you using?**
Latest - problem is present in `dev` branch at the time of writing.

**Where is the issue?**
 * [x ] M.IM.Protocols

**Is this a new or an existing app?**
Irrelevant, issue is present in current `dev` branch.

**Repro**
1. Have the initial `ConfigurationManager::GetConfigurationAsync` call fail for whatever reason (e.g. transient network issue)
2. Make any REST call to the service

Authentication will fail then with `IDX20803: Unable to obtain configuration from: ...` for the duration of `RefreshInterval` (5 minutes by default).

**Expected behavior**
When no AAD configuration is currently present in `ConfigurationManager` (`_currentConfiguration`), AAD configuration should be retrieved even if `RefreshInterval` has not yet passed

**Actual behavior**
When no AAD configuration is currently present, the SDK will throw `IDX20803` for the duration `RefreshInterval`.

**Possible solution**
Either ignore `RefreshInterval` if no AAD configuration is currently present, or provide a new configuration option such as `MissingConfigurationRefreshInterval` that would default to maybe 5 seconds.

**Additional context / logs / screenshots / links to code**
Upon failure, the sync timeout is set to `RefreshInterval`: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/900dc266687d24f96c78cd9af3ac085461f3bba0/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L150

Therefore, until `RefreshInterval` passes, all calls will fail immediately: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/900dc266687d24f96c78cd9af3ac085461f3bba0/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L162

**Workaround**
Could we just set `RefreshInterval` to be something like 5 seconds? What is the worst case scenario here, we make an AAD config call every 5 seconds? On it's face it doesn't seem like a huge issue...

**Comment by brentschmaltz** [comment]
@ohadschn BaseConfigurationManager.RefreshInterval allows you to set the value.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/900dc266687d24f96c78cd9af3ac085461f3bba0/src/Microsoft.IdentityModel.Tokens/BaseConfigurationManager.cs#L120?

Would this work for you?

**Comment by ohadschn** [comment]
> @ohadschn BaseConfigurationManager.RefreshInterval allows you to set the value.
> 
> https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/900dc266687d24f96c78cd9af3ac085461f3bba0/src/Microsoft.IdentityModel.Tokens/BaseConfigurationManager.cs#L120
> 
> Would this work for you?

As a workaround, yes, but presumably there is a reason the default value is 5 minutes as opposed to 5 seconds no?

**Comment by ciaozhang** [comment]
@ohadschn We adopted a bootstrap refresh interval when no AAD configuration is currently present in ConfigurationManager. The new timer with exponential backoff for failing to fetch metadata at bootstrap til we get the first config.
Would this work for you?

PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2052

**Comment by ohadschn** [comment]
@ciaozhang thank you, it looks good.
My only suggestion would be to have a limit lower than `RefreshInterval` for the case where `_currentConfiguration` is null.
So perhaps you'd define a `MaxBootstrapRefreshInterval` with a lower default than `RefreshInterval` (say 1 minute) and then instead of `if (_bootstrapRefreshInterval < RefreshInterval) ...` you would have something like `if (_bootstrapRefreshInterval < Math.Min(MaxBootstrapRefreshInterval, RefreshInterval)) ...`

**Comment by ciaozhang** [comment]
We believe the exponential backoff(begin with 1 second) is better option for the case where _currentConfiguration is null. 
Feel free to reopen it if you other suggestions.

**Comment by ohadschn** [comment]
@ciaozhang I'm not suggesting you should get rid of the exponential backoff, just use a lower maximum for it.
Keep everything as is, just change `if (_bootstrapRefreshInterval < RefreshInterval) ...` to `if (_bootstrapRefreshInterval < Math.Min(MaxBootstrapRefreshInterval, RefreshInterval)) ...` where `MaxBootstrapRefreshInterval` is lower than `RefreshInterval` (for example 1 minute).

BTW I can't reopen issues...

**Comment by ciaozhang** [comment]
@ohadschn  The bootstrapRefreshInterval won't longer than the RefreshInterval if you take a look of our implementation.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/5068c6eaf1c87cf3fac7fb7411bbaee7ded8baa4/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L181

**Comment by ohadschn** [comment]
@ciaozhang I understand, what I'm suggesting is to make sure the `_bootstrapRefreshInterval` is even lower than `RefreshInterval`. I'm suggesting to change this exact line to something like `if (_bootstrapRefreshInterval < Math.Min(MaxBootstrapRefreshInterval, RefreshInterval))` where `MaxBootstrapRefreshInterval` by default is lower than `RefreshInterval`.
