### ISSUE TITLE
[Bug] Regression from 6.21.0 to 6.23.1

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1942]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [x ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

6.21.0 -> JsonWebToken.CipherText returns null for decrypted token
6.23.1 -> JsonWebToken.CipherText returns String.Empty for decrypted token.

**Comment by brentschmaltz** [comment]
@joegoldman2 we can't take this into dev, which is our 7.x branch where the API states that string.Empty will be returned.
We would have to commit this into our dev6.x branch.

**Comment by joegoldman2** [comment]
I'll rebase and target dev6.x in this case, no problem.

**Comment by brentschmaltz** [comment]
@jacobjiangwei thanks

**Comment by joegoldman2** [comment]
The PR has been rebased and now targets dev6x.

**Comment by jennyf19** [comment]
closing as we are onto IdentityModel8x now ,if this is an issue,  please re-open.
