### ISSUE TITLE
[Feature Request] Support for .net 7.0 in IdentityModelTelemetryUtil.ClientSku 

### ISSUE THREAD

**Issue by sruke** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1947]
Today, an explicit condition doesn't exist in ClientSku logic for .net 7.0. 

Reference: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Logging/IdentityModelTelemetryUtil.cs#:~:text=public%20static%20string%20ClientSku%20%3D%3E

We have conditions for NET45, NET461, NET472, NETSTANDARD2_0 and NET6_0 but not NET7_0.

What is needed?
Evaluate if adding a condition for NET7_0 is sufficient and add it.

**Comment by jennyf19** [comment]
@sruke You should be able to do `NET6_0_OR_GREATER` https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives

**Comment by sruke** [comment]
Thank you, Jenny. I'll get this done during the week of 10/17.

Once .Net 7.0 is released in November then Wilson targets can be updated to point to it. Will create a separate issue to track this.

**Comment by cloud0259** [comment]
Hello,
Is it possible to add .NET 7.0 support?

**Comment by brentschmaltz** [comment]
@cloud0259 closing as we jumped to .net8.
