### ISSUE TITLE
`JsonWebTokenHandler` is not a `SecurityTokenHandler`/`ISecurityTokenValidator`

### ISSUE THREAD

**Issue by pinkfloydx33** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1953]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
`Microsoft.IdentityModel.JsonWebTokens` 6.24.0

**Where is the issue?**
 * [X] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [X] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
Combination of new applications and existing applications being migrated to M.IM.

**Repro**

I'm not sure if this is a documentation bug or a bug in the implementation so I've opened this as the latter. I apologize as this is something of a mixed report.

The documentation for `JsonWebTokenHandler` indicates that is *supposed* to be a `SecurityTokenHandler`, however it only inherits from `TokenHandler`:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b7a4fdd6c55b1a017469c15e4f4ffeecf9f577f6/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L22-L26

Because of this, it's also *not* a `ISecurityTokenValidator` and no alternative that supports `JsonWebToken` seems to be available.

I stumbled across this in an ASPNET Core application. Because it is *not* a `SecurityTokenHandler` (and one doesn't seem to be available), we were unable to "swap-out" `S.IM.Tokens.Jwt.JwtSecurityToken` for `M.IM.JsonWebTokens.JsonWebToken` in a custom Signature Validator for `TokenValidationParameters` that ignores signature (having been performed by API gateway, [see here](https://stackoverflow.com/questions/49932596/ignore-jwt-bearer-token-signature-i-e-dont-validate-token))

The current implementation makes use of the fact that ASP.NET [automatically adds a token validator/handler](https://github.com/dotnet/aspnetcore/blob/56075e222e6e8f07989fb877a4737b3430dbb6a0/src/Security/Authentication/JwtBearer/src/JwtBearerOptions.cs#L17-L25) for the S.IM type, but not the M.IM type. The code compiles but then fails at runtime since the S.IM handler cannot validate the M.IM token type.

```csharp
// existing code
var opts = new JwtBearerOptions();
opts.TokenValidationParameters.SignatureValidator = (token, _) => new JwtSecurityToken(token);

// updated code -- compiles but fails at runtime
var opts = new JwtBearerOptions();
opts.TokenValidationParameters.SignatureValidator = (token, _) => new JsonWebToken(token);
```

Although we can [add our own validator](https://github.com/dotnet/aspnetcore/blob/56075e222e6e8f07989fb877a4737b3430dbb6a0/src/Security/Authentication/JwtBearer/src/JwtBearerOptions.cs#L106), there doesn't seem to be one to add that would accept the `JsonWebToken` type. If `JsonWebTokenHandler` inherited `SecurityTokenHandler` like it claims, it would automatically implement `ISecurityTokenValidator` which we could presumably add/replace 

**Expected behavior**
`JsonWebTokenHandler` inherits `SecurityTokenHandler`/`ISecurityTokenValidator`, or the documentation is corrected and an alternative made available.

**Actual behavior**
`JsonWebTokenHandler` does not inherit `SecurityTokenHandler` nor implement `ISecurityTokenValidator`

**Additional context / logs / screenshots / links to code**
The code which compiles above but fails at runtime, throws a `Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException`:

> IDX10506: Signature validation failed. The user defined 'Delegate' specified on TokenValidationParameters did not return a 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken', but returned a 'Microsoft.IdentityModel.JsonWebTokens.JsonWebToken' when validating token: '[PII of type 'System.String' is hidden

**Comment by brentschmaltz** [comment]
@pinkfloydx33 this is by design. ISecurityTokenVaidator was believed to be the right interface moving forward as it contains an out parameter which is not usable for async calls, see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b7a4fdd6c55b1a017469c15e4f4ffeecf9f577f6/src/Microsoft.IdentityModel.Tokens/ISecurityTokenValidator.cs#L32


We believe that TokenHandler is the model moving forward.

**Comment by pinkfloydx33** [comment]
I assume you mean "_wasn't_ believed to be the right interface"?

In  that case then it's still a documentation bug as the xmldoc claims it to be a `SecurityTokenHandler`.

Aside: aspnet's jwt handler uses the method with the out parameters and therefore appears to have a hard req on S.IM. Unless I'm missing something, it doesn't look to have been updated for net7, meaning there's going to be a disparity for another cycle.

There's already an ongoing issue around it that forces one to manually reference S.IM in their application else be faced with a runtime MissingMethodException--which is ironic considering the release notes suggest it should be deprecated.
