### ISSUE TITLE
Breaking changes on ReadonlyJsonWebToken?

### ISSUE THREAD

**Issue by renatogbp** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1958]
After upgrading Microsoft.IdentityModel.S2S.Tokens from 3.21.1 to 3.36.1 we started seeing this exception:

`(redacted).Exceptions.ArtifactValidationException: Artifact validation unexpectedly failed. ---> Rhino.Mocks.Exceptions.ExpectationViolationException: (redacted)("", System.InvalidCastException: Unable to cast object of type 'Microsoft.IdentityModel.JsonWebTokens.JsonClaimSet' to type 'Microsoft.IdentityModel.Json.Linq.JToken'.
at lambda_method60(Closure , Object )
at (redacted).Jwt.ReadonlyJsonWebToken..ctor(SecurityToken token)
at ...`

What's the guidance here?

**Comment by brentschmaltz** [comment]
@renatogbp The JsonWebToken has been modified to use System.Text.Json so this cast will not work.

Microsoft.IdentityModel.Json.Linq.JToken is an internal class and it is unexpected that users would be accessing those types.
How is your code written.

**Comment by renatogbp** [comment]
Here's my code (jwtHandler is a `JsonWebTokenHandler`):

```
var jwt = new ReadonlyJsonWebToken(jwtHandler.ReadToken(encodedToken));
```

**Comment by brentschmaltz** [comment]
@renatogbp can you provide an encodedSkypetoken?
What does ReadonlyJsonWebToken do?

**Comment by renatogbp** [comment]
Here's a sample of encodedToken
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJza3lwZWlkIjoidGVzdCIsImlhdCI6MTMzMDQ3MzYwMCwiZXhwIjoxMzMwNDczNjYwLCJzY3AiOjAsImNzaSI6IjAifQ.
```

**Comment by renatogbp** [comment]
Hi @brentschmaltz, I am solving the issue internally with SEAL team. Thanks for the help though.
