### ISSUE TITLE
Can i use this extension in monoDevelop-Unity?

### ISSUE THREAD

**Issue by hojjat-reyhane** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#196]
I'm working with unity 3d and i want to implement JWT. Is there any body help me how import and use this extension? Does this extension work in MonoDevelop-Unity?

**Comment by brentschmaltz** [comment]
The aspnet guys seem to know most about MONO, you might want to ask there:

https://github.com/aspnet/Home

**Comment by brentschmaltz** [comment]
@hojjat-reyhane did you find what you needed?

**Comment by hojjat-reyhane** [comment]
Thanks for answering, no i did not. The problem is that i'm new to unity and don't know how to use .NET extensions.

**Comment by hojjat-reyhane** [comment]
I searched again and found that i should to use .dll file of extension. The dll should compile for .NET framework 3.5 or before. I tested a JSON dll for .NET 3.5 but it did not work. The .NET 2.0 version worked very well. Now i want .NET 2.0 dll file of this extension and don't know how to get it!!!

**Comment by hojjat-reyhane** [comment]
Again me!!! I downloaded the dll file from this link for .NET framework 4.5 but it didn't work in unity.
https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/4.0.2.206221351
Has JWT any extension for .NET framework 3.5 or before?

**Comment by brentschmaltz** [comment]
All our JWT work requires 4.5 .Net as it depends on System.Security.Claims that showed up in 4.5.

**Comment by hojjat-reyhane** [comment]
That's a bad news, very bad news.
I want to connect to a web service with unity and don't want any body see the contents. Is there any chance i can implement JWT by myself in c# .NET framework 3.5?

**Comment by hojjat-reyhane** [comment]
I just want to encode, decode and validate data with a single algorithm (does not matter witch one). Any extra methods is useless for me.

**Comment by ghanashyaml** [comment]
Try using Dominic Baier's JWT implementation found in leastpriviledge.com which should work for you.

-----Original Message-----

**Comment by hojjat-reyhane** [comment]
@ghanashyaml if you mean this "Thinktecture.IdentityModel", it's for .NET 4.5 too.

**Comment by ghanashyaml** [comment]
Yes, there is an older version of the dll somewhere that has it.

**Comment by brentschmaltz** [comment]
@hojjat-reyhane Please feel free to reopen.
