### ISSUE TITLE
[Feature Request]  Let ReadToken exceptions trickle up to ValidateTokenAsync

### ISSUE THREAD

**Issue by Esurnir** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1965]
**Is your feature request related to a problem? Please describe.**
When I have let's say an assembly binding problem on my .net framework web app during validation of a JWT. Instead of getting an exception telling me it couldn't find the right assembly with the correct strong name the app instead sent me a IDX14100 error message `JWT is not well formed: '{0}', there are no dots (.).\nThe token needs to be in JWS or JWE Compact Serialization Format. `
This lead to a wild goose chase trying to validate the tokens were well formed (hidden characters?). Then lead to me having to debug the nugget package in order to find what the real exception was and which DLL were faulty.

The problem come from this function : https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b7a4fdd6c55b1a017469c15e4f4ffeecf9f577f6/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1173 which is used inside ValidateTokenAsync and doesn't let ValidateTokenAsync recover the real exception.

**Describe the solution you'd like**
I would like to have a way to recover the initial exception either through a logging setting or through the Exception property of TokenValidationResult.

**Describe alternatives you've considered**
Debuguing the internal dlls. Trying to mount the project on my visual studio resulted in strong name signature error. Debuguing using microsoft symbols can be tedious due to async throwing me into execution context and the debuging experience of external library can be tedious to the uninitiated (of which I'm one unfortunately).

**Additional context**
It seems the try catch masquing the original Exception was added in the rewrite to use System.Text.Json and not in the original code.

**Comment by brentschmaltz** [comment]
@Esurnir I agree we should not swallow this exception.
Would you have found the issue earlier if we exposed the inner exception?

**Comment by Esurnir** [comment]
> @Esurnir I agree we should not swallow this exception.
> 
> Would you have found the issue earlier if we exposed the inner exception?

Definitely, it was probably the second place I looked for a hint as to what was wrong after the first exception message. I would still have probably tried to check to see my token was malformed but as soon as I see the real exception so often I would have had the solution within maybe 5 minutes on a slow brain day.

**Comment by brentschmaltz** [comment]
@Esurnir Thanks for the PR !
