### ISSUE TITLE
ITokenReplayCache should have async methods?

### ISSUE THREAD

**Issue by Idhor** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#197]
I'm implementing my first JWT authentication and i need to protect against replay attacks
I was wondering if the ITokenReplayCache  should have async methods in case the developer need to lookup on something that requires I/O like a file or a database

**Comment by brentschmaltz** [comment]
I deliberately wanted this to be sync. If there is a need for async, then we would need to lock somewhere because the contract is about only the first token is accepted.

**Comment by brentschmaltz** [comment]
@Idhor feel free to reopen if you don't agree.
