### ISSUE TITLE
[Bug] JsonWebTokenHandler fails on kid validation if TokenValidationParameters.ConfigurationManager is null

### ISSUE THREAD

**Issue by luciwoof** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1974]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
Microsoft.IdentityModel.JsonWebTokens 6.25.0

**Where is the issue?**
 * [x] M.IM.JsonWebTokens

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

```csharp
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Protocols;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.IdentityModel.Tokens;

string jwks = @"{
    ""keys"": [
        {
        ""kty"": ""EC"",
        ""use"": ""sig"",
        ""crv"": ""P-256"",
        ""kid"": ""UxD/HxiD9WFuV9CoacB25R/UX6I="",
        ""x"": ""_khe_wjVF_Zjzs0LjquTwnnJ_SRvcXQmrJHNQQMP6ro"",
        ""y"": ""IqNy420xylaCmEW5enQT4fjVMZfa3sxAQzwjMnyL_9U"",
        ""alg"": ""ES256""
        }
    ]
}";

var signingKeys = JsonWebKeySet.Create(jwks);

string jwt = "eyJhbGciOiJFUzI1NiIsImtpZCI6IlV4RC9IeGlEOVdGdVY5Q29hY0IyNVIvVVg2ST0iLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE2Njk3OTcwMjIsImV4cCI6MTY2OTc5NzYyMiwiaXNzIjoiSXNzdWVyU3RyaW5nIiwiYXVkIjoiSXNzdWVyU3RyaW5nIiwic3ViIjoiSXNzdWVyU3RyaW5nIn0.-HkZAxjY3Jz7JIhSne8o0kP9wneT9fDa6gkPbVjaA5cNmLj4XE11XY4eIVZUax1ilVuKYj_4sHmn02DRULAjEA";

string issuer = "IssuerString";

TokenValidationParameters parameters = new()
{
    IssuerSigningKeys = signingKeys.Keys,
    ValidateIssuerSigningKey = true,
    ValidIssuer = issuer,
    ValidateIssuer = true,
    ValidAudiences = new string[] { issuer },
    ValidateAudience = true,
    RequireSignedTokens = true,
    RequireExpirationTime = true,
    ValidateLifetime = false,

    TryAllIssuerSigningKeys = false
};

var handler = new JsonWebTokenHandler();
var result = handler.ValidateToken(jwt, parameters);

if (!result.IsValid)
{
    Console.WriteLine(result.Exception);
}
else
{
    Console.WriteLine("Valid!");
}
```
Creating an empty configuration manager works as a workaround:
```csharp
OpenIdConnectConfiguration config = new();

parameters.ConfigurationManager = new StaticConfigurationManager<OpenIdConnectConfiguration>(config);

result = handler.ValidateToken(jwt, parameters);

if (!result.IsValid)
{
    Console.WriteLine(result.Exception);
}
else
{
    Console.WriteLine("Valid!");
}
```

**Expected behavior**
JWT should be validated using the keys from the TokenValidationParameters. ConfigurationManager should not be required, quoting the documentation: 
> The obtained issuer and signing keys will then be used along with those present on the TokenValidationParameters for validation of the incoming token.

This works as expected when using JwtSecurityTokenHandler.

**Actual behavior**
JWT is not validated as ConfigurationManager is null. It fails on the check https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/87be17baffebf602c8def0d581f4b7306de7042e/src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs#L444

It should however use the other ResolveTokenSigningKey if ConfigurationManager is null: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/87be17baffebf602c8def0d581f4b7306de7042e/src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs#L476

**Possible solution**
JwtSecurityTokenHandler does a check on this, and uses the correct ResolveTokenSigningKey if ConfigurationManager is null: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/87be17baffebf602c8def0d581f4b7306de7042e/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1297

A similar check in JsonWebTokenHandler would fix the issue: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1447 

I am more than happy to create a PR implementing this.

**Additional context / logs / screenshots / links to code**
N/A

**Comment by brentschmaltz** [comment]
@bal2 thanks for the excellent detail.
I think another fix would be to modify [JwtTokenUtilities.ResolveTokenSigningKeys](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/9ddad8fc51ed2732622323612acad83f6629d5ba/src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs#L442) to only check configuration if not null, then call ResolveTokenSigningKey(string kid, string x5t, TokenValidationParameters validationParameters) if no keys are matched.

If you would like to create a PR, that would be great.
We use the dev branch for commits.
