### ISSUE TITLE
Creating JWTs on CoreCLR

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#198]
Hi. 

I want to create Jwts in an ASP.NET 5 app on the CoreClr.

What's the right Nuget to use for this? In the past I have X509SigningCredentials in the JwtSecurityToken ctor - I can't find this class. Where can I find it? Or is there a replacement?

thanks!

**Comment by leastprivilege** [comment]
nm - got it.

**Comment by Blackbaud-CameronBlack** [comment]
Where is it?  ;)  same problem
