### ISSUE TITLE
[Documentation] Sample link is dead

### ISSUE THREAD

**Issue by mrochon** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1982]
### Documentation related to component
POP

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [X] error(s) in the example
- [ ] needs an example

### Description of the issue
[Documentation references](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/dev/4.-Console-app-calls-web-API-with-PoP) on [this page](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/SignedHttpRequest-aka-PoP-(Proof-of-Possession)) gives 404.

**Comment by ciaozhang** [comment]
Fixed the broken link.
