### ISSUE TITLE
[Feature Request] Support ECD with X509Certificates

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1984]
X509Certificates can have RSA or ECD keys.
Currently this runtime assumes that an X509Certificate implies RSA.
ECD has become common, and this forces customers to convert the X509SecurityKey to a ECDsaSecurityKey.

**Comment by jennyf19** [comment]
closing as duplicate. Thanks @cakescience
