### ISSUE TITLE
Links and image not displayed correctly

### ISSUE THREAD

**Issue by Daniel-Krzyczkowski** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1986]
In the wiki documentation under [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/SignedHttpRequest-aka-PoP-(Proof-of-Possession)), links does not work and image does not display correctly.

**Comment by ciaozhang** [comment]
Fixed the link.
