### ISSUE TITLE
[Bug] ValidateToken does not embed the inner exception

### ISSUE THREAD

**Issue by Esurnir** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1992]
**Which version of Microsoft.IdentityModel are you using?**
The dev branch.

**Where is the issue?**
 * [X] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**

b. The app is in production and I haven't upgraded Microsoft.IdentityModel.*, but started seeing this issue by rereading my previous PR.

**Repro**

```csharp
string token = "abdc.efgh";
var parameter = new TokenValidationParameters
                        {
                            IssuerSigningKey = KeyingMaterial.JsonWebKeyRsa256SigningCredentials.Key,
                            ValidAudience = Default.Audience,
                            ValidIssuer = Default.Issuer,
                        };
var result = new JsonWebTokenHandler().ValidateToken(token, parameter);
```

**Expected behavior**
I should expect result.Exception.InnerException to not be null.

**Actual behavior**
The innerException is null.

**Possible solution**
This is very awkward... I made this bug, I intended to fix #1965 . But after rereading my pr #1969 a month later... I realized I passed the inner exception to the FormatInvariant helper function and not as the second argument of new ArgumentException.

I'm writing a PR that does the job properly and add Unit tests verifying that the inner Exception is indeed passed on to the caller instead of being silently dropped.

**Comment by brentschmaltz** [comment]
@Esurnir thanks, PR committed.
