### ISSUE TITLE
[Bug] S.IM.Tokens.Jwt doesn't seem to be handling UNIX timestamps in milliseconds 

### ISSUE THREAD

**Issue by ElNew** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1999]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
 S.IM.Tokens.Jwt 6.25.1

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**

The app is in production

**Repro**

```csharp

JwtSecurityTokenHandler jwtTokenHandler = new();

var authTokenValidationParameters = new TokenValidationParameters
{
    ValidateLifetime = true,
    ValidateIssuer = false,
    ClockSkew = TimeSpan.Zero,
    ValidateIssuerSigningKey = false,
    ValidateSignatureLast = true
};

var jwtToken =    "eyJ0eXBlIjoiSldUIiwibm9uY2UiOiJZVS1jSWQzZEVTc2w0czg0aFlnMlVmRG1fY0xXT25ZUnJuelVRUTlEWTZrIiwiYWxnIjoiSFMyNTYiLCJ4NXQiOiJ0eHY3SGdKeXVaY0RTOG1oVDZsQzNJdFlmV2siLCJraWQiOiJ0eHY3SGdKeXVaY0RTOG1oVDZsQzNJdFlmV2sifQ.eyJvaWQiOiJhYWFhYWFhYS1mZmZmLWRlYWQtYWFhYS1mZmZhYWZmZmZhYWYiLCJwdWlkIjoiRkZGRkZGRjExMTExMTExMSIsInRpZCI6IjcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0NyIsInVwbiI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTYzMTEwNzkyMDQzMywibmJmIjoxNjMxMTA3OTIwNDMzLCJleHAiOjE2MzExMDc5MjA0MzMsImFwcGlkIjoiMTFjNjMxMWYtMTNhMy0xMWJjLTgxMTQtNzUxMThjNjUxMTdhIiwiYXVkIjoiMzExODY2ZmMtZWUxMS00MTExLTgxMTYtM2YxMTRiMTExZTExIiwic2NwIjoiVXNlci5SZWFkLkFsbCIsImFwcGlkYWNyIjoiMiIsInZlciI6IjEuMCIsImF1dGhfdGltZSI6MTY3MjM5NDM3NywiYWNjdCI6MCwiYWNyIjoiMSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0Ny8ifQ.1fZk79vl7-EXaeMxJmK7QhPG0ux1W2MfW-SMlJ1B5Sc";
TokenValidationResult jwtTokenValidatinResult = await jwtTokenHandler.ValidateTokenAsync(jwtToken, authTokenValidationParameters).ConfigureAwait(false);
Console.WriteLine(jwtTokenValidatinResult.IsValid);
Console.WriteLine(jwtTokenValidatinResult?.Exception);
```

**Expected behavior**
Token fails validation because it's expired.

**Actual behavior**
Token fails validation saying it misses an exp claim. The token contains the claim. 

Microsoft.IdentityModel.Tokens.SecurityTokenNoExpirationException: IDX10225: Lifetime validation failed. The token is missing an Expiration Time. Tokentype: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken& signatureValidatedToken, ExceptionDispatchInfo& exceptionThrown)
--- End of stack trace from previous location ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenAsync(String token, TokenValidationParameters validationParameters)
**Possible solution**
Looks like the problem lies with the seconds vs milliseconds UNIX timestamp, where the milliseconds is not handled.

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by jmprieur** [comment]
Did the problem appear in .NET 7?

**Comment by ElNew** [comment]
Get the same in both 6 and 7. Could I be doing something wrong? It looks very straightforward.
It appears only when the code gets a token with timestamps in milliseconds. No problem with the ones where the timestamp is expressed in seconds.

**Comment by brentschmaltz** [comment]
@ElNew the time in the JWT is 1631107920433 which we interpreted in the [JWT spec](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.4) as EPOCH time which maps to: (GMT) September 8 - 2021.

If you need to handle different time formats you can set this delegate [TokenValidationParamaters.LifetimeValidator](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/93cd144c0daf4f98a669714f2dfe2e9442e06aa2/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L547) which will be called to validate the lifetime of the JWT.
