### ISSUE TITLE
[Documentation] System.IdentityModel.Tokens.Jwt vs Microsoft.IdentityModel.JsonWebTokens

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2006]
### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
I would like to better understand the difference between the difference between `System.IdentityModel.Tokens.Jwt` and `Microsoft.IdentityModel.JsonWebTokens`. I am not able to find anything in the documentation.

**Comment by tebeco** [comment]
@brentschmaltz and for anyone reading

The recommendation seemns to be `Microsoft.IdentityModel.JsonWebTokens` but this probably needs to be explicited and documented @brentschmaltz like just adding a line on the nuget description

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki
![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/2266487/2f455c4f-7e9e-44c7-8138-e2e232f2fb91)


just doing this would be a very good enhancement:

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/2266487/00955202-ce82-4cf5-a27d-684b7f2bf6d3)

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/2266487/4b03b2af-8aa0-4f19-acc0-587af102cd18)

**Comment by jennyf19** [comment]
Great feedback, thanks @tebeco

**Comment by westin-m** [comment]
The changes have been made and will be reflected in NuGet with the next release.
