### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jlinn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2013]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel 6.26.0

**Where is the issue?**
 * [*] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is in production and I haven't upgraded Microsoft.IdentityModel.*, but started seeing this issue.

**Repro**

```csharp
    public string? Decrypt(string token)
    {
        var handler = new JsonWebTokenHandler();
        return handler.DecryptToken(new JsonWebToken(token), new TokenValidationParameters(
        {
            TokenDecryptionKeyResolver = _resolver.Resolve
        });
    }
```

**Expected behavior**
When `_resolver.Resolve` returns multiple keys, `handler.DecryptToken()` should succeed if any one of the resolved keys is successfully unwrapped.

**Actual behavior**
When multiple keys are supplied by the resolver, `handler.DecryptToken()` throws an exception if any of the given keys cannot be unwrapped.

**Possible solution**
The `JsonWebTokenHandler.GetContentEncryptionKeys` method looks very similar to [JwtSecurityTokenHandler.GetContentEncryptionKeys](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1748), with one notable difference: 
The `JwtSecurityTokenHandler` version uses [||](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1811) where `JsonWebTokenHandler` uses [&&](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6.26.0/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1012) when checking for successfully unwrapped keys to return.

**Comment by brentschmaltz** [comment]
@jlinn we are closing as we are only fixing issues in JsonWebTokenHandler as this is our path moving forward for JWT.
