### ISSUE TITLE
[Bug] Investigate why adding async/await to token validation flow caused a reduction in performance and fix it

### ISSUE THREAD

**Issue by sruke** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2017]
Changes that need to be investigated: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/9ccf9536413025e189ef443ffe02e72397ab93a9

**Comment by brentschmaltz** [comment]
This has been fixed.
