### ISSUE TITLE
When will the inbound claim type map be turned off by default?

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#202]
I am on 2.0.0-beta5 - and it seems I still have to do 

JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

Am I missing something - or has this been changed in later builds?

**Comment by brentschmaltz** [comment]
POR is to put that in the official beta7 build, but you should see it in a nightly soon.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/95 set to Beta7
