### ISSUE TITLE
[Bug] Shortened signatures signed with SymmetricSignature is still valid

### ISSUE THREAD

**Issue by gran0123** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2022]
**Which version of Microsoft.IdentityModel are you using?**
6.26.1

**Where is the issue?**
 * [X] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [X] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment running .net framework 4.8.1 using the latest version 6.26.1. The problem occured in previous version as far as I know.

**Repro**

Create snippet:
```csharp
var key = Encoding.ASCII.GetBytes("uITr+Gft1bEH3SHsCLViiozvrrswogHQJQeIzv/ok5E=");
var tokenDescriptor = new SecurityTokenDescriptor
{
    Subject = new ClaimsIdentity(new[]
    {
        new Claim("cid", "123")
    }),
    Expires = DateTime.UtcNow.AddYears(50),
    IssuedAt = DateTime.UtcNow,
    Issuer = "http://localhost:5000/",
    Audience = "http://localhost:5000/",
    SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key),
        SecurityAlgorithms.HmacSha256Signature)
};
var tokenHandler = new JsonWebTokenHandler();
var jwsToken = tokenHandler.CreateToken(tokenDescriptor);
```

Validation snippet:
```csharp
var key = Encoding.ASCII.GetBytes("uITr+Gft1bEH3SHsCLViiozvrrswogHQJQeIzv/ok5E=");
var tokenHandler = new JsonWebTokenHandler();
var validationResult = tokenHandler.ValidateToken(jwsToken, new TokenValidationParameters
{
    ValidateIssuerSigningKey = true,
    IssuerSigningKey = new SymmetricSecurityKey(key),
    ValidateIssuer = true,
    ValidIssuer = "http://localhost:5000/",
    ValidateAudience = true,
    ValidAudience = "http://localhost:5000/",
});
```

**Expected behavior**
Validation snippet from above should return `validationResult.IsValid` `false` if I remove characters from the signature of the created jws token.

**Actual behavior**
E.g this is a token created by above create snippet:
`eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiIxIiwiY2xleHRlcm5hbCI6InRydWUiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAvIiwiZXhwIjozMjUzODU1Nzg0LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAvIiwiaWF0IjoxNjc1OTMyNTg0LCJuYmYiOjE2NzU5MzI1ODV9.jg7jUPrimxCW3yVcVD6RB7Inw45EfHBt5bthzf_2aWk`

If I remove the last four characters `2aWk` from the signature and send that to `tokenHandler.ValidateToken()`, it still returns `validationResult.IsValid` `true`.

**Possible solution**
No one yet.

**Additional context / logs / screenshots / links to code**
Something is happening in the `Utility.AreEqual()` method. This method is called inside `SymmetricSignatureProvider.Verify()`.
`Utility.AreEqual()` states that ` /// The attempt here is to take the same time if an attacker shortens the signature OR changes some of the signed contents.` which is not the case. The correct signature is four characters short and `result` inside `Utility.AreEqual()` should not be 0 which is the case when I debug external source code.

**Comment by brentschmaltz** [comment]
this was fixed with https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2008 our next release will fix this.
