### ISSUE TITLE
[Bug] Wrong error message formatting for IDX10653 (System.Security.Cryptography)

### ISSUE THREAD

**Issue by DavidVollmers** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2033]
Coming from https://github.com/dotnet/runtime/issues/83347

### Description

While testing my own code I ran into the following exception:
`IDX10653: The encryption algorithm 'System.String' requires a key size of at least 'System.Int32' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 'System.Int32'. 
(Parameter 'key')`

I understand that my symmetric key is too short (should it not be zero-padded automatically?) but the error message is the weird part. It seems to me that something went wrong in here and it doesn't use the values but rather the types when formatting the error message.

### Reproduction Steps

Here is an example project reproducing the behavior:
https://github.com/DavidVollmers/IDX10653/blob/main/Program.cs

### Expected behavior

The exception message should look like this:
`IDX10653: The encryption algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha512' requires a key size of at least 128 bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 32. (P
arameter 'key')`

### Actual behavior

The exception message looks like this:
`IDX10653: The encryption algorithm 'System.String' requires a key size of at least 'System.Int32' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 'System.Int32'. 
(Parameter 'key')`

### Configuration

- .NET 6.0
- Windows 10 Enterprise (11.‎03.‎2021, 19045.2604)
- x64

**Comment by brentschmaltz** [comment]
@DavidVollmers we should turn off PII filtering.

**Comment by DavidVollmers** [comment]
@brentschmaltz I am confused. What does personal identifiable information has to do with this?

**Comment by ciaozhang** [comment]
@DavidVollmers 
It is fixed in 6.15.0. Now they are marked as NonPII. May I know your Wilson version?

**Comment by DavidVollmers** [comment]
What do you mean by "Wilson" version?

**Comment by ciaozhang** [comment]
> What do you mean by "Wilson" version?

@DavidVollmers  The Microsoft.IdentityModel.Tokens version.

**Comment by DavidVollmers** [comment]
Ah I see. Since I am either using `System.IdentityModel.Tokens.Jwt` or `Microsoft.AspNetCore.Authentication.JwtBearer` it is not that clear. For `System.IdentityModel.Tokens.Jwt` it seems I can just upgrade to `6.31.0` but for `Microsoft.AspNetCore.Authentication.JwtBearer` it is difficult; The NuGet uses `Microsoft.IdentityModel.Protocols.OpenIdConnect` version `6.10.0` for the latest .NET 6 package which itself uses `System.IdentityModel.Tokens.Jwt` version `6.10.0`.

**Comment by jennyf19** [comment]
Marking this as closed, as it looks to be resolved. If that's not the case, please re-open.
