### ISSUE TITLE
[Feature Request] Use GeneratedRegex in JwtTokenUtilities

### ISSUE THREAD

**Issue by eerhardt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2036]
**Is your feature request related to a problem? Please describe.**
When publishing an app for NativeAOT (see #2035), IL generation at runtime is disabled.

One usage of IL generation at runtime is `new Regex(regex, RegexOptions.Compiled)`. At startup, RegexOptions.Compiled instructs the Regex engine to generate IL given the regular expression, and use the generated IL, instead of interpreting the expression every time it is executed.

When you use a "Compiled" Regex in NativeAOT, the Regex engine ignores the `Compiled` option and instead falls back to interpreting the expression at runtime. This means your app runs slower when on NativeAOT.

**Describe the solution you'd like**
The solution to this issue is to use the new Regex Source Generator:

* https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators
* https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#source-generation

However, this feature is only available when targeting `net7.0` and above. So we would need the following:

1. We would need to target `net7.0` in `Microsoft.IdentityModel.JsonWebTokens.csproj`.
    - This means updating any CI scripts and build machines to use the .NET 7 SDK.
2. JwtTokenUtilities would look like this:

```C#
    public partial class JwtTokenUtilities
    {
        private const int RegexMatchTimeoutMilliseconds = 100;
        /// <summary>
        /// Regex that is used to figure out if a token is in JWS format.
        /// </summary>
        public static Regex RegexJws = CreateJwsRegex();

        /// <summary>
        /// Regex that is used to figure out if a token is in JWE format.
        /// </summary>
        public static Regex RegexJwe = CreateJweRegex();

#if NET7_0_OR_GREATER
        [GeneratedRegex(JwtConstants.JsonCompactSerializationRegex, RegexOptions.CultureInvariant, RegexMatchTimeoutMilliseconds)]
        private static partial Regex CreateJwsRegex();
        [GeneratedRegex(JwtConstants.JweCompactSerializationRegex, RegexOptions.CultureInvariant, RegexMatchTimeoutMilliseconds)]
        private static partial Regex CreateJweRegex();
#else
        private static Regex CreateJwsRegex() => new Regex(JwtConstants.JsonCompactSerializationRegex, RegexOptions.Compiled | RegexOptions.CultureInvariant, TimeSpan.FromMilliseconds(RegexMatchTimeoutMilliseconds));
        private static Regex CreateJweRegex() => new Regex(JwtConstants.JweCompactSerializationRegex, RegexOptions.Compiled | RegexOptions.CultureInvariant, TimeSpan.FromMilliseconds(RegexMatchTimeoutMilliseconds));
#endif
```

Note that there are benefits to using the source generator even when not in NativeAOT mode. For example, your app starts faster because it doesn't need to generate IL at runtime.

**Describe alternatives you've considered**
Live with slower NativeAOT applications.

**Additional context**
The following benchmark shows `JsonWebTokenHandler.CanReadToken` performance is 2-3x faster on NativeAOT when using the source generated Regex:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="\git\azure-activedirectory-identitymodel-extensions-for-dotnet\src\Microsoft.IdentityModel.JsonWebTokens\Microsoft.IdentityModel.JsonWebTokens.csproj" />
    <PackageReference Include="BenchmarkDotNet" Version="0.13.5" />
  </ItemGroup>

</Project>
```

```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using Microsoft.IdentityModel.JsonWebTokens;
using Perfolizer.Horology;

var job = Job.Default
                    .WithWarmupCount(1) // 1 warmup is enough for our purpose
                    .WithIterationTime(TimeInterval.FromMilliseconds(250)) // the default is 0.5s per iteration, which is slighlty too much for us
                    .WithMinIterationCount(15)
                    .WithMaxIterationCount(20) // we don't want to run more that 20 iterations
                    .DontEnforcePowerPlan(); // make sure BDN does not try to enforce High Performance power plan on Windows

var config = DefaultConfig.Instance
    .AddJob(job.AsDefault()); // tell BDN that this are our default settings

BenchmarkSwitcher
    .FromAssembly(typeof(Program).Assembly)
    .Run(args, config);


public class JsonWebTokenHandlerBenchmark
{
    const string jwsToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik15VGVzdFVzZXIiLCJzdWIiOiJNeVRlc3RVc2VyIiwianRpIjoiMWVhZjQ4NzYiLCJzY29wZSI6Im15YXBpOnNlY3JldHMiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjA4MCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzA4IiwiaHR0cDovL2xvY2FsaG9zdDo1Mjk0IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE3MyJdLCJuYmYiOjE2Nzg5OTg2MjUsImV4cCI6MTY4Njk0NzQyNSwiaWF0IjoxNjc4OTk4NjI2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.Ol6TuW6OgkaLcuFWx5O4JGcGwqdG9IlvA84roUQPhc8";
    const string jweToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6IlJzYVNlY3VyaXR5S2V5XzIwNDgiLCJ0eXAiOiJKV1QifQ.eyJlbWFpbCI6IkJvYkBjb250b3NvLmNvbSIsImdpdmVuX25hbWUiOiJCb2IiLCJpc3MiOiJodHRwOi8vRGVmYXVsdC5Jc3N1ZXIuY29tIiwiYXVkIjoiaHR0cDovL0RlZmF1bHQuQXVkaWVuY2UuY29tIiwibmJmIjoiMTQ4OTc3NTYxNyIsImV4cCI6IjE2MTYwMDYwMTcifQ.GcIi6FGp1JS5VF70_ULa8g6GTRos9Y7rUZvPAo4hm10bBNfGhdd5uXgsJspiQzS8vwJQyPlq8a_BpL9TVKQyFIRQMnoZWe90htmNWszNYbd7zbLJZ9AuiDqDzqzomEmgcfkIrJ0VfbER57U46XPnUZQNng2XgMXrXmIKUqEph_vLGXYRQ4ndfwtRrR6BxQFd1PS1T5KpEoUTusI4VEsMcutzfXUygLDiRKIcnLFA0kQpeoHllO4Nb_Sxv63GCb0d1076FfSEYtyRxF4YSCz1In-ee5dwEK8Mw3nHscu-1hn0Fe98RBs-4OrUzI0WcV8mq9IIB3i-U-CqCJEP_hVCiA";

    private readonly JsonWebTokenHandler handler = new JsonWebTokenHandler();

    [Benchmark]
    public bool JWS() => handler.CanReadToken(jwsToken);

    [Benchmark]
    public bool JWE() => handler.CanReadToken(jweToken);
}
```

### Existing Code Normal CoreCLR (not AOT'd)
`dotnet run -c Release -f net7.0`

| Method |     Mean |    Error |  StdDev |
|------- |---------:|---------:|--------:|
|    JWS | 662.5 ns | 10.21 ns | 9.05 ns |
|    JWE | 861.8 ns |  5.27 ns | 4.12 ns |

### Existing Code Publish AOT
`dotnet run -c Release -f net7.0 --runtimes nativeaot7.0`

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|    JWS | 1.798 us | 0.0222 us | 0.0197 us |
|    JWE | 2.376 us | 0.0106 us | 0.0099 us |

* Note the change in time units from nanoseconds to microseconds.

### Proposed Code Normal CoreCLR (not AOT'd)
`dotnet run -c Release -f net7.0`

| Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|    JWS | 598.0 ns |  6.53 ns |  6.11 ns |
|    JWE | 788.3 ns | 11.16 ns | 10.44 ns |

### Proposed Code Publish AOT
`dotnet run -c Release -f net7.0 --runtimes nativeaot7.0`

| Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|    JWS | 558.8 ns | 19.37 ns | 22.31 ns |
|    JWE | 702.2 ns |  5.12 ns |  4.54 ns |

**Comment by eerhardt** [comment]
cc @brentschmaltz

**Comment by eerhardt** [comment]
After chatting with Stephen Toub, he let me know that in net8.0 we will see even better perf gains due to the fact that Regex will use the [new IndexOfAnyValues APIs](https://github.com/dotnet/runtime/pull/78093) introduced in .NET 8. Here are the benchmark's numbers I'm seeing on .NET 8:

### Existing Code Normal CoreCLR (not AOT'd)
`dotnet run -c Release -f net8.0`

| Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|    JWS | 259.0 ns |  6.09 ns |  6.76 ns |
|    JWE | 318.3 ns | 10.46 ns | 12.04 ns |

### Existing Code Publish AOT
`dotnet run -c Release -f net8.0 --runtimes nativeaot8.0`

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|    JWS | 1.603 us | 0.0142 us | 0.0118 us |
|    JWE | 2.148 us | 0.0370 us | 0.0328 us |

* Note the change in time units from nanoseconds to microseconds.

### Proposed Code Normal CoreCLR (not AOT'd)
`dotnet run -c Release -f net8.0`

| Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|    JWS | 275.9 ns | 15.69 ns | 18.07 ns |
|    JWE | 302.9 ns |  4.47 ns |  3.96 ns |

### Proposed Code Publish AOT
`dotnet run -c Release -f net8.0 --runtimes nativeaot8.0`

| Method |     Mean |   Error |  StdDev |
|------- |---------:|--------:|--------:|
|    JWS | 274.2 ns | 4.44 ns | 3.71 ns |
|    JWE | 325.7 ns | 4.20 ns | 3.93 ns |

______________

Note that `Existing Code Publish AOT` only got slightly better on .NET 8. Using the source generator will give us an even bigger perf gain on NativeAOT when we target .NET 8.

**Comment by cg110** [comment]
I recently came across this same area of code as being a performance issue as well.

And took a step back from using the regex, as it's just expensive when there you're really out to check 2 things:
all the chars are valid JWT
the right number of segments are present (and only some can be empty)

There's a lurking string.split in there that is used just to count how many segments there are, which is just wasted memory and memcpying.
If instead you loop over every char and compare it against the valid JWT chars solves a part of the problem.
If you also compare the char against . you can store the segment breaks, and then check the segments make as a jwe or jws token.

Turns out the net 8 code be made to be quick on earlier .net versions by swapping the span.IndexOfAnyExcept with a "custom" function...

**Comment by eerhardt** [comment]
> There's a lurking string.split in there that is used just to count how many segments there are, which is just wasted memory and memcpying.

See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1964 for addressing those.

> it's about half the time of the src gen regex for net 8.

Can you share your code and benchmark?

**Comment by cg110** [comment]
sure, I need to cleanup the code a bit though, to be sure there aren't more optimizations, I get the netfx fast which is what I cared about (SrcGen versions are the same as the shipping ones, but with the string.split removed, and for net7 it's source generated)
dotnet run -c Release -f net48
|       Method |        Mean |     Error |      StdDev |
|------------- |------------:|----------:|------------:|
|          JWS |  7,045.1 ns | 115.47 ns |   102.36 ns |
|          JWE | 11,134.0 ns | 898.25 ns | 1,034.42 ns |
|    JWSSrcGen |  6,682.8 ns | 239.91 ns |   276.28 ns |
|    JWESrcGen |  9,168.0 ns | 130.99 ns |   116.12 ns |
| JWSRegexFree |    716.0 ns |   8.11 ns |     7.19 ns |
| JWERegexFree |    987.8 ns |  19.05 ns |    17.82 ns |

dotnet run -c Release -f net6.0
|       Method |       Mean |    Error |   StdDev |
|------------- |-----------:|---------:|---------:|
|          JWS | 1,121.1 ns | 24.54 ns | 28.26 ns |
|          JWE | 1,466.0 ns | 18.30 ns | 15.28 ns |
|    JWSSrcGen |   938.5 ns |  8.39 ns |  7.85 ns |
|    JWESrcGen | 1,379.8 ns | 26.54 ns | 29.50 ns |
| JWSRegexFree |   500.0 ns | 12.45 ns | 13.84 ns |
| JWERegexFree |   697.0 ns | 14.93 ns | 16.60 ns |

Net7, I must have mixed up a test, as it's not actually faster than the src gen version.
|       Method |     Mean |    Error |   StdDev |
|------------- |---------:|---------:|---------:|
|          JWS | 651.5 ns | 29.38 ns | 33.83 ns |
|          JWE | 827.2 ns | 23.61 ns | 27.19 ns |
|    JWSSrcGen | 434.8 ns |  9.36 ns | 10.78 ns |
|    JWESrcGen | 583.1 ns | 10.26 ns |  8.57 ns |
| JWSRegexFree | 493.0 ns | 11.26 ns | 12.96 ns |
| JWERegexFree | 676.2 ns |  8.86 ns |  8.29 ns |

I suspect there's some work to do on the .net 7 version.

I need to look at a .net8 optimized version, using IndexOfAnyExcept

**Comment by cg110** [comment]
net8 version using IndexOfAnyExcept:
|       Method |      Mean |    Error |   StdDev |
|------------- |----------:|---------:|---------:|
|          JWS | 257.56 ns | 5.357 ns | 5.954 ns |
|          JWE | 278.74 ns | 4.588 ns | 3.582 ns |
|    JWSSrcGen |  94.37 ns | 1.049 ns | 0.930 ns |
|    JWESrcGen | 106.87 ns | 1.774 ns | 1.385 ns |
| JWSRegexFree |  32.92 ns | 0.423 ns | 0.375 ns |
| JWERegexFree |  40.25 ns | 0.250 ns | 0.233 ns |

nativeaot8:
|       Method |        Mean |     Error |    StdDev |
|------------- |------------:|----------:|----------:|
|          JWS | 1,439.87 ns | 47.712 ns | 54.945 ns |
|          JWE | 1,814.83 ns | 35.326 ns | 29.499 ns |
|    JWSSrcGen |    97.42 ns |  1.297 ns |  1.150 ns |
|    JWESrcGen |   109.36 ns |  2.160 ns |  2.021 ns |
| JWSRegexFree |    33.81 ns |  0.226 ns |  0.189 ns |
| JWERegexFree |    40.85 ns |  0.677 ns |  0.695 ns |

using indexOfAnyExcept with net7 was terrible :(

net 8 version (I believe it should be correct, but haven't put it through unit tests, and it may need some more polishing)
`

    public override bool CanReadToken(string token)
    {
        if (string.IsNullOrEmpty(token))
        {
            return false;
        }
        if (token.Length > MaximumTokenSizeInBytes)
        {
            LogHelper.LogInformation(IDX10209, LogHelper.MarkAsNonPII(token.Length), LogHelper.MarkAsNonPII(MaximumTokenSizeInBytes));
            return false;
        }
        Span<int> segmentLengths = stackalloc int[JwtConstants.JweSegmentCount];
        int segmentCount = 0;
        var tokenSpan = token.AsSpan();

        int index;
        while ((index = tokenSpan.IndexOfAnyExcept(JwtValidChars)) != -1)
        {
            if (tokenSpan[index] == '.' && segmentCount < (JwtConstants.JweSegmentCount - 1))
            {
                segmentLengths[segmentCount] = index;
                segmentCount++;
                tokenSpan = tokenSpan.Slice(index + 1);
            }
            else
            {
                // invalid char or too many segments
                LogHelper.LogInformation(IDX12720);
                return false;
            }
        }

        // add last segment
        if (segmentCount < JwtConstants.JweSegmentCount)
        {
            segmentLengths[segmentCount] = tokenSpan.Length;
            segmentCount++;
        }
        else
        {
            // too many segments, error
            LogHelper.LogInformation(IDX12720);
            return false;
        }

        // a valid token should be 3 or 5 segements
        if (segmentCount == JwtConstants.JwsSegmentCount)
        {
            // segment 0 and 1 can't be empty
            // segment 2 can be empty
            return segmentLengths[0] != 0
                && segmentLengths[1] != 0;
        }
        else if (segmentCount == JwtConstants.JweSegmentCount)
        {
            // segment 0 can't be empty
            // segment 1 can be empty
            // segment 2, 3, 4 can't be empty
            return segmentLengths[0] != 0
                && segmentLengths[2] != 0
                && segmentLengths[3] != 0
                && segmentLengths[4] != 0;
        }

        LogHelper.LogInformation(IDX12720);
        return false;
    }
    internal static readonly IndexOfAnyValues<char> JwtValidChars = IndexOfAnyValues.Create("-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz");
`

**Comment by cg110** [comment]
So it appears that the net 8 code above can be made good for all net48-7 by altering the while loop:

`while ((index = tokenSpan.IndexOfAnyExcept(JwtValidChars)) != -1)`

to:
`while ((index = IndexOfNonJwtChar(tokenSpan)) != -1)`

And then providing a suitable function:
```
#if NET8_0_OR_GREATER
    private static int IndexOfNonJwtChar(ReadOnlySpan<char> span)
        => span.IndexOfAnyExcept(JwtValidChars);
    internal static readonly IndexOfAnyValues<char> JwtValidChars = IndexOfAnyValues.Create("-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz");
#else

    private static int IndexOfNonJwtChar(ReadOnlySpan<char> span)
    {
        for (int i = 0; i < span.Length; i++)
        {
            var c = span[i];
            // net 7 regex source generator converted the set [-0-9A-Z_a-z] to this:
            if (c < '{' && ("\0\0 Ͽ\ufffe蟿\ufffe߿"[c >> 4] & (1 << (c & 0xF))) != 0)
            {
                continue;
            }
            return i;
        }
        return -1;
    }
#endif
```

netfx48 shows a gain, as does net6, net7 it's now a smidge faster than the source generated regex.  I've no idea if the unicode string comes through.
Sadly it's not very readable/understandable or maintainable.  For net7 though it's the only way to match the src generated regex (as that's the trick the regex is using)

While faster, the code still needs to be maintainable, so it could use an if that matches the set of chars, which isn't quite as fast as above, and net7 shows it to be a little slower than the src gen regex.
I don't know if there's a more optimal way of doing this if statement, that would be readable and as fast as above.
```
if (c is
            (>= 'A' and <= 'Z')
            or (>= 'a' and <= 'z')
            or (>= '0' and <= '9')
            or '-'
            or '_')
```

**Comment by eerhardt** [comment]
Why not just stick with Regex? Note that the Regex's are public properties:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dfe9ea29f550e613b70c2646f60d65caf1493e7a/src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs#L27-L37

**Comment by cg110** [comment]
For net 7 or later yes, i can only match the src generated regex by using the tricks it does.  So its extra complexity for marginal gain.  Net 6 may as well stick to regex for simplicity.

However for netfx regex performance is pretty terrible, and some of us are stuck with netfx for some years. However that's probably something I can subclass and override.
