### ISSUE TITLE
[Feature Request] Add support for Mapping Claims to JsonWebTokenHandler

### ISSUE THREAD

**Issue by eerhardt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2044]
**Is your feature request related to a problem? Please describe.**
Trying to upgrade ASP.NET's `AddAuthentication().AddJwtBearer()` implementation from `JwtSecurityTokenHandler` to `JsonWebTokenHandler`, it appears a missing feature is the `MapInboundClaims` feature that `JwtSecurityTokenHandler` has.

This means if a token with payload like:

```json
{
  "sub": "1234567890",
  "unique_name": "MyTestUser",
  "iat": 1516239022
}
```

is issued using the new `JsonWebTokenHandler`, the `unique_name` claim isn't set on the resulting `ClaimsIdentity` as illustrated in the following repro program:

```C#
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;

const string token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidW5pcXVlX25hbWUiOiJNeVRlc3RVc2VyIiwiaWF0IjoxNTE2MjM5MDIyfQ.RdBPDWUy92hIn9MjxdzZjkn5yeFObc9-cq5xMaDFuag";

string symmetricKeyEncoded_256 = "Vbxq2mlbGJw8XH+ZoYBnUHmHga8/o/IduvU/Tht70iE=";
byte[] symmetricKeyBytes_256 = Convert.FromBase64String(symmetricKeyEncoded_256);
SymmetricSecurityKey symmetricSecurityKey_256 = new SymmetricSecurityKey(symmetricKeyBytes_256) { KeyId = "symmetricKeyBytes_256" };

var validationParameters = new TokenValidationParameters
{
    ValidateIssuerSigningKey = true,
    RequireSignedTokens = false,
    IssuerSigningKey = symmetricSecurityKey_256,
    ValidateIssuer = false,
    ValidateAudience = false,
    ValidateLifetime = false,
    ValidAlgorithms = new List<string> { SecurityAlgorithms.HmacSha256 }
};

JwtSecurityTokenHandler oldHandler = new JwtSecurityTokenHandler();
TokenValidationResult result = await oldHandler.ValidateTokenAsync(token, validationParameters);

Console.WriteLine(result.ClaimsIdentity.Name); // prints 'MyTestUser'

JsonWebTokenHandler newHandler = new JsonWebTokenHandler();
result = await newHandler.ValidateTokenAsync(token, validationParameters);

Console.WriteLine(result.ClaimsIdentity.Name ?? "<null>"); // should print 'MyTestUser' but instead prints '<null>'
```

**Describe the solution you'd like**
`JsonWebTokenHandler` should be able to map the `unique_name` claim to the `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` claim, so the `ClaimsIdentity` works properly, like it does with `JwtSecurityTokenHandler`.

**Describe alternatives you've considered**
ASP.NET could implement this functionality itself, but that seems inefficient, and it wouldn't help anyone else moving to the `JsonWebTokenHandler` API.

**Additional context**
N/A

cc @brentschmaltz

**Comment by brentschmaltz** [comment]
@eerhardt i would like to suggest the default is off.

**Comment by eerhardt** [comment]
> i would like to suggest the default is off.

I think that makes sense. My assumption is that ASP.NET will default it to on for their customers though. Just to minimize any breaking changes.
