### ISSUE TITLE
[Feature Request] Consider adding LogTokens as a sub feature of ShowPII

### ISSUE THREAD

**Issue by sri-** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2046]
**Is your feature request related to a problem? Please describe.**
It is not clear that tokens are also logged when ShowPII is set to true.

**Describe the solution you'd like**
Separate out logging tokens into a different property like LogTokens

**Describe alternatives you've considered**
Currently we have turned off ShowPII.

**Comment by brentschmaltz** [comment]
@sri- we are adding this feature, will be in the next release.

**Comment by ciaozhang** [comment]
@sri- 
We introduced a new flag[LogCompleteSecurityArtifact](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6c4010ae233f86fd7e8e5c2bc50df2f3bc5a2f82/src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs#L41) which indicates whether or not complete <see cref="SecurityArtifact"/> is shown in logs when <see cref="ShowPII"/> is set to true. False by default.
It is available in Wilson v 6.31.0 now.
