### ISSUE TITLE
[Documentation] Tokens are exposed (logged, shown in exceptions) when ShowPII is enabled

### ISSUE THREAD

**Issue by sri-** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2047]
### Documentation related to component
IdentityModelEventSource.ShowPII

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
Update documentation to indicate that tokens are also logged/exposed when ShowPII is turned on.

**Comment by brentschmaltz** [comment]
@sri- this has been fixed in 7.x
