### ISSUE TITLE
MissingMethodException when using version 6.28.1

### ISSUE THREAD

**Issue by jouni-kantola** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2051]
**Version**
```xml
<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.28.1" />
``` 

**Where is the issue?**
 * [x] S.IM.Tokens.Jwt

**Is this a new or an existing app?**
The app is in production and I haven't upgraded Microsoft.IdentityModel.*, but started seeing this issue.

**Repro**
Update NuGet package from version 6.27.0 to 6.28.1. Run code below:

```csharp
public bool TryValidateJwtToken(string token, IEnumerable<string> validAudiences, out IEnumerable<Claim> claims)
{
    claims = null;
    try
    {
        var handler = new JwtSecurityTokenHandler();
        var parameters = new TokenValidationParameters
        {
            RequireSignedTokens = true,
            IssuerSigningKeys = discoveryResponse.KeySet.Keys.Select(key => new RsaSecurityKey(new RSAParameters
            {
                Exponent = Base64UrlEncoder.DecodeBytes(key.E),
                Modulus = Base64UrlEncoder.DecodeBytes(key.N)
            })
            { KeyId = key.Kid }),
            ValidateIssuer = true,
            ValidIssuer = discoveryResponse.Issuer,
            ValidateAudience = true,
            ValidAudiences = validAudiences,
        };
        var claimsPrincipal = handler.ValidateToken(token, parameters, out _);
        claims = claimsPrincipal.Claims;
    }
    catch (Exception ex)
    {
        // Goes BOOM!
    }

    return claims != null;
}
```

**Expected behavior**
In version 6.27.0 we got parsed claims. That is what we expect to happen.

**Actual behavior**
In version 6.28.1 we're getting the following error both when targeting `netstandard2.0` (which we use) and `net6.0`:
```
"Method not found: 'Boolean Microsoft.IdentityModel.Tokens.TokenUtilities.IsRecoverableConfiguration(Microsoft.IdentityModel.Tokens.TokenValidationParameters, Microsoft.IdentityModel.Tokens.BaseConfiguration, Microsoft.IdentityModel.Tokens.BaseConfiguration ByRef)'."
```

Stack trace:
```
{System.MissingMethodException: Method not found: 'Boolean Microsoft.IdentityModel.Tokens.TokenUtilities.IsRecoverableConfiguration(Microsoft.IdentityModel.Tokens.TokenValidationParameters, Microsoft.IdentityModel.Tokens.BaseConfiguration, Microsoft.IdentityModel.Tokens.BaseConfiguration ByRef)'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at [REDACTED].TryValidateJwtToken(String token, IEnumerable`1 validAudiences, IEnumerable`1& claims) in [REDACTED]\TokenValidator.cs:line [REDACTED]}
```

**Comment by brentschmaltz** [comment]
@jouni-kantola thanks for reporting, will look into this quickly.

**Comment by brentschmaltz** [comment]
@jouni-kantola can you confirm all of your IdentityModel assemblies have the same version?

**Comment by jouni-kantola** [comment]
👍 Thanks for pointing me into the right direction. When I explicitly referenced the `System.IdentityModel.Tokens.Jwt` version `6.28.1` everything works as expected. I'll close the issue.

**Comment by brentschmaltz** [comment]
@jouni-kantola we had started an effort to check that all assemblies are the same version to avoid such issues.
That effort was bumped from the list.
I pointed out this issue to the team, adding that logic may get a higher priority now.

**Comment by sipsorcery** [comment]
I'm getting the same exception after updating to the latest stabke nuget packages. My relevant packages seem to be:

```
<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.5" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="7.0.5" />
```

The resulting `System.IdentityModel.Tokens.Jwt` assembly version in my executable directory is `6.24.0.31013`.

Update:

Explicitly adding a package reference resolves the problem. This wasn't needed previously.

`<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.29.0" />`

**Comment by brentschmaltz** [comment]
@sipsorcery this can happen when IdentityModel moves some internals around and the versions do not match.
M.A.A.JwtBearer pulls in S.IM.T.Jwt version 6.15.1, some transitive dependency must be pulling in 6.24.0
Do you have any other IdentityModel assemblies, if so what are the versions.

**Comment by sipsorcery** [comment]
Nope, no other IdentityModel assemblies.
