### ISSUE TITLE
[Bug] unique_name vs name in older version of System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by havarnov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2062]
**Which version of Microsoft.IdentityModel are you using?**
System.IdentityModel.Tokens.Jwt 6.10.0 & 6.10.1

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of System.IdentityModel.Tokens.Jwt

**Repro**

```csproj
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.10.0" />
  </ItemGroup>
```

```csharp
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using Microsoft.IdentityModel.Tokens;

var claims = new List<Claim>
{
    new Claim(ClaimTypes.Name, "<some name>"),
    new Claim("aud", "some audience"),
};
var key = new byte[1024];
new Random().NextBytes(key);
var securityKey = new SymmetricSecurityKey(key);
var signingCredentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256Signature);
var tokenDescriptorSystem = new SecurityTokenDescriptor
{
    Subject = new ClaimsIdentity(claims),
    Issuer = "some issuer",
    Expires = DateTime.UtcNow.AddMinutes(10),
    SigningCredentials = signingCredentials
};

var tokenHandler = new JwtSecurityTokenHandler();
var token = tokenHandler.CreateToken(tokenDescriptorSystem);
var tokenString = tokenHandler.WriteToken(token);
```

**Expected behavior**

The following program will create a JWT token with the following payload for version 6.5.0 -> 6.9.0 and from 6.10.2 ->

```json
...
"unique_name": "<some name>",
...
```

**Actual behavior**
But for version 6.10.0 and 6.10.1 it will create the following payload:

```json
...
"name": "<some name>",
...
```

**Possible solution**

This seems like a critical enough regression that I think that version 6.10.0 and 6.10.1 should be unlisted from nuget.org.
It's especially easy to be bitten by this bug since this package is often included as a transitive dependency and it's not obvious which version that ultimately gets included in the final binary.

**Comment by brentschmaltz** [comment]
@havarnov i checked in 6.9.0 this commit changed the claim type: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/183c04ad613b1c0355b68ad3278d5a45e5c8835b

It was removed in 6.10.2 in this commit: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/d6f2b66d788195b50f2b1f700beb497851194c73

I will speak to the team about delisting the packages 6.9.0 -> 6.10.1.

**Comment by havarnov** [comment]
Thanks!

You might be right about the error being introduced in 6.9.0, but the repro program I posted above works as intended with version 6.9.0 (i.e. ```"unique_name": "<some name>",```).

**Comment by brentschmaltz** [comment]
@havarnov thanks for bringing this to our attention.

**Comment by jennyf19** [comment]
@havarnov is this repro'ing on the 7x versions as well?

**Comment by brentschmaltz** [comment]
@havarnov we are closing as we are only fixing security issues on 6.x
