### ISSUE TITLE
[Bug] JsonWebToken ctor does not set EncodedToken or EncodedSignature

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2065]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [x] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

This [ctor ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2a1cf333770b8bff683322b15e229f261f883989/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs#L97)to JsonWebToken does not set EncodedToken or EncodedSignature.
This could lead to null refs as users should expect these values to be set.

**Comment by ciaozhang** [comment]
Fixed in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2064

**Comment by brentschmaltz** [comment]
fixed in 7.x
