### ISSUE TITLE
[Documentation] Broken links in proof of possession wiki

### ISSUE THREAD

**Issue by dapathy** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2074]
### Documentation related to component
Proof of possession

### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue
[This wiki page](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/SignedHttpRequest-aka-PoP-(Proof-of-Possession)) features broken links to proof of possession samples.

**Comment by ciaozhang** [comment]
Fixed the broken link.
