### ISSUE TITLE
SkipUnresolvedJsonWebKeys not ignored when serializing

### ISSUE THREAD

**Issue by yolofy** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2085]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
Microsoft.IdentityModel 6.30.1

**Where is the issue?**
 * [X] S.IM.Tokens.Jwt

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

```csharp
        var rsa = RSA.Create();
        RsaSecurityKey publicKey = new(rsa.ExportParameters(false)) { KeyId = Guid.NewGuid().ToString() };
        var jsonWebKey = JsonWebKeyConverter.ConvertFromSecurityKey(publicKey);
        jsonWebKey.Use = "sig";
        jsonWebKey.KeyOps.Add("sign");
        jsonWebKey.Alg = "RS256";
        var jsonWebKeySet = new JsonWebKeySet { Keys = { jsonWebKey } };
        var json = System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(jsonWebKeySet);
        Console.WriteLine(json);
        /* OUTPUT (formatted for readability):
            {
                "keys": [
                    {
                        "alg": "RS256",
                        "e": "AQAB",
                        "key_ops": [
                            "sign"
                        ],
                        "kid": "35c9de05-16dc-4436-910d-dc206c76dd59",
                        "kty": "RSA",
                        "n": "za0Xe_z17QzFt2E1-jNQcqgf8Gnu2Wja7jLK2eiMnU-_1uk4F_8o1hhJMVsr20SmIOzVWhB75FSDM6D4EuE4Lit0HioXPaaaUOAScpK76MnhBfkcfYfF0olpepwoIjQBGB2Ql3WhIjP3wIgtrZxURsRFNFsZcrGJYSo0xXqG31U9X5326p44W_2mgB0UFS8hA92AOBg6bCMKVt8VpNVrwC8lT5Gn7I_DG84JuPvAHTxIPLwXyxsB8EpOtAeE-0iny-3ADXntm8Vj29J5m2UO5CiTWCDp8VMqWzX6lJwalWbQi9mv5692K4GwKsDLiMF7OZXyVo3nBaHVw6LLqU_K2Q",
                        "use": "sig"
                    }
                ],
                "SkipUnresolvedJsonWebKeys": true
            }
         */
```

**Expected behavior**
`SkipUnresolvedJsonWebKeys ` is not present in the serialized form

**Actual behavior**
`SkipUnresolvedJsonWebKeys` is present

**Possible solution**
Add JsonIgnore attribute of some sort

**Additional context / logs / screenshots / links to code**
`<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.30.1" />`

**Comment by brentschmaltz** [comment]
@yolofy is this blocking for you?
I ask because we are making major changes and moving away from our internal clone of newtonsoft.
If you can wait a month or so, will we be able to fix this in our 7.x release.

**Comment by brentschmaltz** [comment]
@yolofy we will not be fixing such issues in the 6.x branch.
If this is still an issue in the 7.x release, please open a new issue.
