### ISSUE TITLE
Avoid referencing System.Text.Encoding

### ISSUE THREAD

**Issue by Bartleby2718** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2086]
See https://github.com/dotnet/runtime/issues/86671 for the full context. 

TL;DR: `Microsoft.IdentityModel.JsonWebTokens` 6.25.1 transitively depends on a vulnerable package `System.Private.Uri` 4.3.0. This can be avoided if `Microsoft.IdentityModel.JsonWebTokens` no longer depends on `System.Text.Encoding` 4.3.0.

**Comment by brentschmaltz** [comment]
@Bartleby2718 thank you, we will get this into the next release.

**Comment by ViktorHofer** [comment]
Note that the following two PRs already take care of that:
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2098
- https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2087

**Comment by teo-tsirpanis** [comment]
We can close this.

**Comment by Bartleby2718** [comment]
Fixed in #2133 (merged into `dev7x`)
