### ISSUE TITLE
Add back TokenValidationParameters.CertificateValidator

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#209]
This was removed in Beta5, because X509CertificateValidator was not in FxCore.
It will be needed when we validate Saml tokens that contain x5c (essentially a self check as the token contains the keys). In this case we need to validate the signing key (only for x509).

**Comment by tushargupta51** [comment]
When doing this, add tests too :) Closing #78 as dup.

**Comment by brentschmaltz** [comment]
With https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/595 we will be reintroducing the CertificateValidation.

**Comment by brentschmaltz** [comment]
The design for #595 decouples SignatureValidation from Reading. The 'KeyInfo' is never used to validate a token, but instead to find a 'trusted' key in TokenValidationParameters. Because of this change, we don't need this feature.
