### ISSUE TITLE
[Bug] HS256 requiring a kid

### ISSUE THREAD

**Issue by sjrulandch** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2104]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
`System.IdentityModel.Tokens.Jwt, 6.30.1`

**Where is the issue?**
 * [X ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of System.IdentityModel.Tokens.Jwt  (6.30.0 -> 6.30.1)

**Repro**

```csharp
```

**Expected behavior**
Our understanding is that kid is not required for HS256.

**Actual behavior**
Using a very simple JWT for internal server 2 server comms (example below). This is signed with a static encryption key. After upgrading to the latest patch release, AspNet (.NET6), began failing token validation with the message below
```
        "Message": "IDX10503: Signature validation failed. Token does not have a kid. Keys tried: \u0027[PII of type \u0027System.Text.StringBuilder\u0027 is hidden. For more details, see https://aka.ms/IdentityModel/PII.]\u0027. Number of keys in TokenValidationParameters: \u00271\u0027. \nNumber of keys in Configuration: \u00270\u0027. \nExceptions caught:\n \u0027[PII of type \u0027System.Text.StringBuilder\u0027 is hidden. For more details, see https://aka.ms/IdentityModel/PII.]\u0027.\ntoken: \u0027[PII of type \u0027System.IdentityModel.Tokens.Jwt.JwtSecurityToken\u0027 is hidden. For more details, see https://aka.ms/IdentityModel/PII.]\u0027. See https://aka.ms/IDX10503 for details.",
        "Source": "System.IdentityModel.Tokens.Jwt",
        "HResult": -2146233088,
        "Data": {},
        "StackTrace": "
		at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)\n
		at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignatureAndIssuerSecurityKey(String token, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)\n
		at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken\u0026 signatureValidatedToken, ExceptionDispatchInfo\u0026 exceptionThrown)\n
		--- End of stack trace from previous location ---\n
		at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken\u0026 signatureValidatedToken)\n
		at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken\u0026 validatedToken)\n
		at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()"
```

**Possible solution**
Rolling back 6.30.1 -> 6.30.0 corrected the issue

**Additional context / logs / screenshots / links to code**
Sample token. Replace `xxx` with the domain of choice.
```
{
  "alg": "HS256",
  "typ": "JWT"
}.{
  "aud": "https://api.xxx.com",
  "exp": 1686067052,
  "iat": 1685980652,
  "iss": "https://security.api.xxx.com",
  "sub": "xxx"
}.[Signature]```

**Comment by brentschmaltz** [comment]
@sjrulandch by any chance is TokenValidationParameters.TryAllIssuerSigningKeys being set to false?
Our logic is if kid is not set, then try all keys if TryAllIssuerSigningKeys is true.

**Comment by sjrulandch** [comment]
We are not setting `TryAllIssuerSigningKeys`. The [default appear to be true](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.tryallissuersigningkeys?view=msal-web-dotnet-latest).

```
                o.TokenValidationParameters = new TokenValidationParameters()
                {
                    ValidateIssuerSigningKey = true,
                    ValidateIssuer = true,
                    IssuerSigningKey = useStaticKeyValidation ? new SymmetricSecurityKey(signingKey.ToBytes()) : null,
                    ValidIssuer = issuer,
                    ValidateAudience = true,
                    ValidAudience = audience,
                    ValidateLifetime = true,
                };
```

**Comment by Sanjidhalim** [comment]
I hit the same issue recently and in my case the error message was misleading. Is your encryption key less than 32 bytes? I see there was a recent change to enforce key sizes [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/008e2f7200685fb3fe8f98c7cd81e8971d2d8ed3) and using a longer key fixed the issue for me. 

Regardless, this looks like a breaking change since validation of previously valid tokens will fail after this change.

**Comment by sjrulandch** [comment]
Yes, I eventually discovered the same. The key size in one particular spot had been configured as too short.

Sorry, I should have updated sooner. Thanks for responding!
