### ISSUE TITLE
[Feature Request] Conditional compilation for net8.0

### ISSUE THREAD

**Issue by westin-m** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2111]
As of #2108, net8.0 is a required build target. Add a condition to the build props that targets net8.0 if an environment variable is set, making it opt-in.

**Comment by jmprieur** [comment]
Also, when building .NET 8:
- Remove the reference to sourcelink when building .NET 8 (as it's included)
- Enable the configuration binding generator (which should remove a bunch of AoT warnings): [What's new in .NET 8 | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#configuration-binding-source-generator)
- only emit our AoT warnings when building with .NET 8?
