### ISSUE TITLE
[Feature Request] Add nullable types to Wilson to detect the possible NullReferenceException

### ISSUE THREAD

**Issue by FuPingFranco** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2135]
***Is your feature request related to a problem? Please describe.***

In order to improve robustness, I'd like to enable nullable across the solution which allows variables to have null as a value, which can be useful in cases where a value may not be present or when a value is optional. It also allows for the use of null-forgiving operator, which suppresses nullable warnings for an expression.

***Describe the solution you'd like***

To enable nullable in a C# project, you can add the following line to your .csproj file: 

&lt;Nullable> enable &lt;/Nullable>

This will enable nullable reference types for the entire project. 

You can also enable nullable reference types for individual files by adding the following line to the top of the file: 

#nullable enable

Once you have enabled nullable reference types, you can use the null-forgiving operator to suppress nullable warnings for a specific expression.

***Describe alternatives you've considered***

In C#, alternatives to nullable include using default values, using the null-coalescing operator, or using the null-conditional operator. The null-coalescing operator is used to return the left-hand operand if it is not null, or the right-hand operand otherwise. The null-conditional operator is used to check if an object is null before accessing its properties or methods. If the object is null, the expression returns null instead of throwing a null reference exception.

**Comment by jennyf19** [comment]
https://user-images.githubusercontent.com/13203188/258225796-e6ec4c48-cfdc-42c8-817b-28be9f6e1b84.png

**Comment by jennyf19** [comment]
@FuPingFranco can you drop the image of the assemblies that were finished and then close the issue? Thank you.

**Comment by FuPingFranco** [comment]
Closing this issue, below are the assemblies which got covered under this issue.

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">



</head>

<body>




PROJECT​ | STATUS​
-- | --
Microsoft.IdentityModel.Abstractions​ | Done​
Microsoft.IdentityModel.JsonWebTokens​ | TBD
Microsoft.IdentityModel.KeyVaultExtensions​ | Done​
Microsoft.IdentityModel.Logging​ | TBD/PR closed
Microsoft.IdentityModel.LoggingExtensions​ | Done​
Microsoft.IdentityModel.ManagedKeyVaultSecurityKey​ | Done​
Microsoft.IdentityModel.Protocols​ | TBD
Microsoft.IdentityModel.Protocols.OpenIdConnect​ | TBD
Microsoft.IdentityModel.Protocols.SignedHttpRequest​ | TBD
Microsoft.IdentityModel.Protocols.WsFederation​ | Done​
Microsoft.IdentityModel.TestExtensions​ | Done​
Microsoft.IdentityModel.Tokens.Saml​ | TBD
Microsoft.IdentityModel.Tokens​ | TBD/ PR closed
Microsoft.IdentityModel.Validators​ | TBD
Microsoft.IdentityModel.Xml​ | TBD
System.IdentityModel.Tokens.Jwt​ | TBD




</body>

</html>
