### ISSUE TITLE
[Bug] Investigate and correctly fix test issues in #2107

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2148]
PR #2107 brought in test failures in some classes, which were fixed in #2147 as a workaround, but a more permanent fix needs to be found. 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2147

This was only impacting tests.

**Comment by brentschmaltz** [comment]
was fixed in 7.x branch.
