### ISSUE TITLE
Extra time spent renting from ArrayPool 

### ISSUE THREAD

**Issue by westin-m** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2152]
20% of CPU time is being spent renting from the ArrayPool.  From quick glance, it looks like that and one of the largest sources of allocation is because the code isn’t disposing of the JsonDocuments that get produced as part of the parsing.  JsonDocument rents from the ArrayPool, and disposing it returns arrays to the pool.  If lots of these are created and not disposed, it not only allocates (because there’s nothing left in the pool), it still spends all the time searching the pool for an array it’ll never find, and in this case incurring a lot of contention with all of the other threads doing the same.

**Comment by brentschmaltz** [comment]
We will be moving to utf8Reader

**Comment by brentschmaltz** [comment]
fixed in 6.x, 7.x is not using JsonDocument.
