### ISSUE TITLE
Extra byte array allocation

### ISSUE THREAD

**Issue by westin-m** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2153]
Utility.AreEqual is allocating two new byte[]s on every use. It appears the implementation is trying to avoid some kind of timing attack and is thus always trying to compare the full length of the inputs even when bad inputs come in. Questions on whether that’s really necessary aside, there’s no need to allocate such byte[]s even in that case.  For example, if you instead directly assign those `new byte[] { /* all consts */ }` into a ReadOnlySpan<byte>, and just do everything in terms of span rather than array, the C# compiler won’t actually allocate for those dummy arrays… it’ll instead just put that data into the data section of the assembly and create spans that point directly to that data.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview2
