### ISSUE TITLE
Use span-based APIs rather than byte arrays to verify signatures

### ISSUE THREAD

**Issue by westin-m** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2154]
SymmetricSignatureProvider.Verify is using the byte[]-based keyedHashAlgorithm.ComputeHash(input). Rather than allocating a byte[] just to compare it, you can stackalloc a span, use the span-based APIs to store into that, and then compare the spans.  Yet another reason to change the (Utility.AreEqual)[#2153] to be span-based.  In general, try to use the span-based APIs to write into existing arrays or stack space (for known small-ish sizes) whenever possible rather than using APIs that create new byte[]s/strings.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview2
