### ISSUE TITLE
Lazy instantiation in TokenValidationParameters

### ISSUE THREAD

**Issue by westin-m** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2155]
TokenValidationParameters has this `public IDictionary<string, object> InstancePropertyBag { get; } = new Dictionary<string, object>();`. Can that be lazily instantiated? I don’t see any other code in the repo (beyond tests) using InstancePropertyBag, yet every TokenValidationParameters being constructed is creating this dictionary instance.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview2
