### ISSUE TITLE
Reduce interface dispatch

### ISSUE THREAD

**Issue by westin-m** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2156]
E.g. in JsonClaimSet.CreateClaims, the code is doing `IList<Claim> claims = new List<Claim>();`.  If you just change that to `List<Claim> claims = new List<Claim>();`, interface dispatch in the rest of the method when working with that `claims` will be removed.  On their own, these won’t move the needle much, but changes here and there can add up.

**Comment by brentschmaltz** [comment]
This has been implemented.
