### ISSUE TITLE
Calls to LogHelper incur cost even when logging is disabled

### ISSUE THREAD

**Issue by stephentoub** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2163]
Many calls to LogHelper are incurring allocation and other costs even when logging is disabled.  More than half of all the calls to LogInformation, for example, pass a parameter that will cause the call site to allocate an array for the params array argument.  Other call sites box value type arguments to be passed in that params array as an object. Etc.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview2
