### ISSUE TITLE
Target langversion 11, instead of latest

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2165]
latest picks a language version based on the target TFM:

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults

Remaining projects:

src/Microsoft.IdentityModel.KeyVaultExtensions/Microsoft.IdentityModel.KeyVaultExtensions.csproj

‎src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj

‎src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj

‎test/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.Tests/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.Tests.csproj

‎test/Microsoft.IdentityModel.KeyVaultExtensions.Tests/Microsoft.IdentityModel.KeyVaultExtensions.Tests.csproj

**Comment by stephentoub** [comment]
Fixed by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2184

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview2
