### ISSUE TITLE
[Possible breaking change in 7x] JsonWebKey spec requires property names to be case-sensitive. 6x is case-insensitive 

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2202]
[JsonWebKey spec](https://datatracker.ietf.org/doc/html/rfc7517#section-8.1)

JsonWebKey deserialization in IdentityModel 6.x is case-insensitive. The question is, in IdentityModel 7x, should we:

a) enforce case-sensitivity (breaking change), or

b) add a flag/override for users who want to follow the spec. Flag would be false by default

Thoughts?

**Comment by brentschmaltz** [comment]
With case-insensitive property names we will miss out on the performance gains from Utf8JsonReader.ValueTextEquals where we can create the UTF8 bytes of each property name.
For an example see: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/use-utf8jsonreader#use-valuetextequals-for-property-name-lookups

**Comment by Forge36** [comment]
Did this ship as a breaking change? I've spent the past day debugging the upgrade my 6->7 upgrade (assuming it was something on my end).

Reverting to 6.32.3 fixes my application.

**Comment by brentschmaltz** [comment]
@Forge36 we fixed this and now allow mixed case property names.

We will be releasing a new version with this PR soon.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2491
