### ISSUE TITLE
[Bug] CryptoProviderFactory.cs should implement IDisposable and dispose the CryptoProviderCache.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2209]
**Which version of Microsoft.IdentityModel are you using?**
6.32.2

**Where is the issue?**

 * [x] M.IM.Tokens

**Is this a new or an existing app?**
This is captured by a test and prevent a partner from upgrading.

```csharp 
public class CryptoProviderFactory  // does not implement IDisposable
...
        public CryptoProviderFactory()
        {
            CryptoProviderCache = new InMemoryCryptoProviderCache() { CryptoProviderFactory = this };
        }
...
```
whereas `InMemoryCryptoProvider` is IDisposable.

**Expected behavior**
Implement IDisposable and dispose the in memory crypto provider cache.

**Actual behavior**
CryptoProviderFactory is not disposable whereas `InMemoryCryptoProvider` is IDisposable.

Note: This needs to be fixed in 6.x and in 7.x

**Comment by henrik-me** [comment]
Triage: We will need simple repro steps to convert into a unit test to showcase the issue we are fixing repro's before fix is applied. Also need clarification on why this was not an issue previously.

**Comment by bgavrilMS** [comment]
There is static analysis that may be able to detect (some?) of these cases: 

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2213

**Comment by brentschmaltz** [comment]
We are not going to do this now.
