### ISSUE TITLE
No simple "hello world" sample for the 95% use-case: generate / validate a simple vanilla HS256 token.

### ISSUE THREAD

**Issue by grokit** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#222]
I noticed that this project does not have an easy example that can just be picked-up and used for the simpler, "95%" use-cases. For example, the python implementation of JWT (see http://jwt.io/) has this on the frontpage:

```
import jwt
encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')
```

I had to build a similar "simple few-liners" for C# leveraging this repository. Would it helped if I contributed it back? I will have to refactor a bit anyays, so what would be most helpful:
- Adding a program that refers to this repository with a simple class & "hello world" 2 liner?
- Adding a unit-test that contains an utility class and a few test that show how to use that easy, basic functionality class?
- Nothing at all, you would prefer me not to contribute the code back?

Let me know!

**Comment by grokit** [comment]
Hey Brent, this has been labelled, but to my question earlier, do you want me to submit the fix?

**Comment by brentschmaltz** [comment]
Sure, submit a PR to KDev

**Comment by brentschmaltz** [comment]
@grokit are you still interested?

**Comment by NickolasAcosta** [comment]
Would greatly appreciate this!

**Comment by grubbr** [comment]
Would also really appreciate this! An example detailing the simpler/"95%" use case (for example using a symmetric key/secret) would be great.

**Comment by grokit** [comment]
Hey everyone, I started this thread. I started using this library & wrote small tests, but since I got no reply on whether or not I could integrate it back I ended up using a different library.

So now I'm pretty busy & don't have time to integrate back the work that I did to the library (and since I now use a different library, it's hard to allocate the time).

**Comment by polita** [comment]
Please add a link to the existing test for this.

**Comment by brentschmaltz** [comment]
@ghost @grokit @nickolasacosta  
We are moving all documentation related items to #601 
Please comment there. It would be great if you could add items in priority.
