### ISSUE TITLE
[Bug] JwtSecurityToken in 7.0.0-preview3 has a Y2038 bug

### ISSUE THREAD

**Issue by eerhardt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2261]
**Which version of Microsoft.IdentityModel are you using?**
7.0.0-preview3

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
This is breaking tests in ASP.NET Core.

**Repro**

Run the following app with `System.IdentityModel.Tokens.Jwt` `Version="7.0.0-preview3"`

```csharp
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(new string('a', 128)));
var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

var claims = new[] { new Claim(ClaimTypes.NameIdentifier, "Bob") };

var token = new JwtSecurityToken(
    issuer: "issuer.contoso.com",
    audience: "audience.contoso.com",
    claims: claims,
    expires: new DateTime(2038, 1, 20),
    signingCredentials: creds);

foreach (var claim in token.Claims)
    Console.WriteLine($"{claim}");

```

**Expected behavior**
The app should output

```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: Bob
exp: 2147580000
iss: issuer.contoso.com
aud: audience.contoso.com
````

**Actual behavior**
```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: Bob
exp: -2147387296
iss: issuer.contoso.com
aud: audience.contoso.com
```

**Possible solution**
Looks like we are casting a `long` to an `int` here:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6602db21ac1cb76aae7fe38557d2502cbf33e69f/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L200

which looks incorrect.

**Comment by ghost** [comment]
Similar to #92 and #2124 about tokens expiring after 03:14:07 UTC on 19 January 2038?

**Comment by eerhardt** [comment]
Similar, yes. But this is a new, distinct issue from those 2 existing issues. The above code worked on `6.x` and `7.0.0-preview`, but now fails on `7.0.0-preview3`.

**Comment by brentschmaltz** [comment]
@eerhardt https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2268 has the fix.

**Comment by jennyf19** [comment]
Included in [preview4 release](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview4)
