### ISSUE TITLE
[Feature Request] Deprecate int? JwtPayload.Exp, .Iat, .Nbf

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2266]
These properties return int, EpochTime requires a long to correctly represent the datetime.

We should add new methods in 7
Expiration, IssuedAt, NotBefore of type long?.

And mark Exp, Iat, Nbf as obsolete.

**Comment by jennyf19** [comment]
In [7.0.0-preview5](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview5)
