### ISSUE TITLE
[Feature Request] JsonSerializationPrimitives needs to set a Maximum depth for recursion when deserializing/serializing

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2269]
Wilson7 currently does not have a maximum level for deserializing a token where the json contains Arrays of Arrays.
For example {"a1":["a2",["a3",[.... ]]]}

We need to decide how may levels, the maximum size of a token is set, but that could be a lot of levels.

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonreaderoptions.maxdepth?view=net-7.0 indicates 64 for reading
https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonwriteroptions.maxdepth?view=net-7.0 indicates 1000 for writing

**Comment by brentschmaltz** [comment]
@keegan-caruso here are the tests that we used when the level was set to 2.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/9e87d9b02f8cbf098310c1177196a34cbb2dcd18/test/Microsoft.IdentityModel.Tokens.Tests/Json/JsonSerializerPrimitivesTests.cs#L24

**Comment by jennyf19** [comment]
In [7.0.0-preview5](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview5)
