### ISSUE TITLE
 Revert TokenValidationParameters.IssuerValidatorAsync delegate back to Task from ValueTask

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2286]
We can evaluate this change later, but other places in our call graph expect a Task.

**Comment by jennyf19** [comment]
In [7.0.0-preview5](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0-preview5)
