### ISSUE TITLE
OIDC Protocol Validator needs to skip chash validation in 'code' only flow

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#229]
In 'code' only flow, we redeem the code for an id_token. The id_token does not have the chash_claim.

When we pass this id_token and the original response message to the protocol validator, then it tries to validate the chash because of non null validationContext.IdToken. The validation will fail with IDX10308 error at this line:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L378
because of lack of chash claim.

Fix: We should look at the response type in the state sent to the Authorization Server and decide whether we should validate chash or not.

**Comment by brentschmaltz** [comment]
When a OICD Response message arrives that just has 'code'. This implies a confidential client flow. The code will be redeemed for a token to use against the userinfo endpoint and an id_token describing the authentication. The original message should not be passed to the OIDCValidator with the id_token. The id_token should be validated and the subject from the UI endpoint must be the same subject as the id_token.

**Comment by tushargupta51** [comment]
@Tratcher 
"The original message should not be passed to the OIDCValidator with the id_token."..that is the key statement.

**Comment by brentschmaltz** [comment]
@tushargupta51 @Tratcher I reviewed the code, I think the call around ~423 is not needed.  That is not an OIDC response message, but a OAuth response message.
