### ISSUE TITLE
OpenIdConnectConfiguration.Copy should 'deep' copy collections.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#230]
the method Copy(OpenIdConnectConfiguration config) should copy the strings in collections.
The existing code uses references as in: 
_acrValuesSupported = config._acrValuesSupported;

We should write:
_acrValuesSupported = new Collection<string>(config._acrValuesSupported);
to keep the two objects independent.

**Comment by tushargupta51** [comment]
@brentschmaltz Do we need a deep copy here? The 'Copy' method is private and is called from one of the constructors public OpenIdConnectConfiguration(string json). This constructor deserializes the json into a local config object which is what we copy over to "this".
