### ISSUE TITLE
[Feature Request] Add support to JsonWebToken.TryGetValue<IList> and ICollection.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2300]
Add support to JsonWebToken.TryGetValue<IList<string>>  and ICollection<string>.

Users would be expecting this to work.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/7.0.0
