### ISSUE TITLE
[Bug]  System.IdentityModel.Tokens.Jwt upgrade from 6.32.3 to 7.0.0 breaks OpenIdConnect

### ISSUE THREAD

**Issue by twogood** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2323]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

We use .NET SDK 7.0.304

We never explicitly reference Microsoft.IdentityModel.

We use Microsoft.AspNetCore.Authentication.OpenIdConnect version 7.0.11

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [X] S.IM.Tokens.Jwt

**Is this a new or an existing app?**
b. The app is in production and I haven't upgraded Microsoft.IdentityModel.*, but started seeing this issue.

**Repro**
(Sorry)

**Expected behavior**
System.IdentityModel.Tokens.Jwt is used in a different project that is a dependency of the project using Microsoft.AspNetCore.Authentication.OpenIdConnect so don't expect OpenIdConnect to break because I update a JWT nuget even if it is a new major version.

**Actual behavior**
```
TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(string address, IDocumentRetriever retriever, CancellationToken cancel)
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(string address, IDocumentRetriever retriever, CancellationToken cancel)
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(string address, IDocumentRetriever retriever, CancellationToken cancel)
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)
```

**Possible solution**
N/A

**Additional context / logs / screenshots / links to code**
Workaround: downgrade to 6.32.3

Also found this SO post: https://stackoverflow.com/questions/77098132/error-generating-jwt-token-during-asp-net-core-web-api-authorization

**Comment by nicoletacristian** [comment]
I am having exactly the same scenario and same error message

**Comment by bdbvb** [comment]
In my case, I was referencing Microsoft.IdentityModel.Tokens. When I updated this to v7, I got an error similar to the above.

It turns out that I needed to update the various Microsoft.IdentityModel.XXX libraries which are transitive dependencies and were still on version 6.32.3. I updated these from the NuGet package manager in Visual Studio 2022 (17.7.4).

See:

Issue https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2320

https://devblogs.microsoft.com/nuget/introducing-transitive-dependencies-in-visual-studio/

**Comment by twogood** [comment]
Thank you @bdbvb!

I'm not sure if I'll update the transitive deps or just stay on 6.x for now.

**Comment by brentschmaltz** [comment]
@twogood all versions of IdentityModel assemblies must be the same.
@bdbvb you are correct.

**Comment by brentschmaltz** [comment]
@twogood please let us know if you need and additional help.
