### ISSUE TITLE
[Bug] System.IdentityModel.Tokens.Jwt 7.* broke loose JWT parsing

### ISSUE THREAD

**Issue by erri120** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2325]
**Which version of Microsoft.IdentityModel are you using?** `System.IdentityModel.Tokens.Jwt 7.0.0`

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The issue appears in `System.IdentityModel.Tokens.Jwt 7.0.0` only. The bug was introduced in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2268 (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/2df4ca87d984cf44c6d30f00d8156651b1d7aae2).

**Repro**

Try and parse a JWT where `sub` is a number instead of a string.

**Expected behavior**
`sub` and other "string" fields should convert a number into a string instead of throwing.

**Actual behavior**
The `JwtPayload.CreatePayload` method throws an exception because `sub` is expected to be a string: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2df4ca87d984cf44c6d30f00d8156651b1d7aae2/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L115-L141

**Possible solution**
Implicitly convert a number to a string.

**Additional context / logs / screenshots / links to code**
Version 6.* had "loose" parsing of JWT tokens. This changed in 7.* to a more strict parser that throws an exception when a number is encountered instead of a string. While this behavior is spec-compliant (https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2), some backends written in loosly typed languages like JavaScript don't convert a number to a string before creating the JWT. As such, many tokens in the wild will be affected by this change to a stricter parser.

**Comment by brentschmaltz** [comment]
@erri120 yes, we now expect the 'sub' to be a string.
To maintain back compat, we will have to add some control to allow for this to work.

**Comment by evanlhyde** [comment]
Experiencing this as well

**Comment by jennyf19** [comment]
For reference: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f5fef2269a6eea5ba52d707d7235acf6a504db9f/src/Microsoft.IdentityModel.JsonWebTokens/Json/JsonWebToken.PayloadClaimSet.cs#L92 -> `ReadAsString` , check in header claims as well.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f5fef2269a6eea5ba52d707d7235acf6a504db9f/src/Microsoft.IdentityModel.JsonWebTokens/Json/JsonWebToken.HeaderClaimSet.cs#L49

**Comment by brockallen** [comment]
`sub` has [always been a string](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.2). If it were treated as an `int` previously, then it was a bug.

**Comment by leastprivilege** [comment]
ah specs - details...

**Comment by brentschmaltz** [comment]
@brockallen @leastprivilege correct 'sub' is a string, was never supposed to be number.
However, we think that this could break users of asp.net8.0 and i can't think of a good reason to fault here.

We will map string -> datetime, or a string -> number to be backcompat with 6.x.

**Comment by dmytro-gokun** [comment]
@brentschmaltz  Just to clarify.. Is there going to be a 7.0.4 release which introduces back compatibility again or is it going to be fixed in 8.0 only?

**Comment by jennyf19** [comment]
> @brentschmaltz Just to clarify.. Is there going to be a 7.0.4 release which introduces back compatibility again or is it going to be fixed in 8.0 only?

This will be fixed in a 7.1.x release (the next release) ETA is mid-Dec.

**Comment by dmytro-gokun** [comment]
@jennyf19 Thanks for the info. And what about 8.0? Will it have this fixed from the get go or will we need to wait for some sort of a patch release?
