### ISSUE TITLE
Unable to deserialize JSON into JsonWebKeySet

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2326]
Currently, it is not possible to deserialize a JWK Set into `Microsoft.IdentityModel.Tokens.JsonWebKeySet` without additionnal configuration.

This is because the `Keys` property is readonly.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/eeaa61ba4887ded80875ed5659aa8a7c04b1da96/src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs#L82

Steps to reproduce:
```cs
using System.Net.Http.Json;
using Microsoft.IdentityModel.Tokens;

var client = new HttpClient();
var response = await client.GetAsync("https://login.microsoftonline.com/common/discovery/v2.0/keys");
var jsonWebKeySet = await response.Content.ReadFromJsonAsync<JsonWebKeySet>();
var count = jsonWebKeySet!.Keys.Count; // 0
```

**Known workarounds**

Before .NET 8, we can use `JsonWebKeySet.Create(string)` to create an instance of `JsonWebKeySet` from the raw content:

```cs
using System.Net.Http.Json;
using Microsoft.IdentityModel.Tokens;

var client = new HttpClient();
var response = await client.GetAsync("https://login.microsoftonline.com/common/discovery/v2.0/keys");
var raw = await response.Content.ReadAsStringAsync(); // An temporary string is allocated here :(
var jsonWebKeySet = JsonWebKeySet.Create(raw);
var count = jsonWebKeySet!.Keys.Count; // 5
```

With .NET 8, we can use the new [`JsonObjectCreationHandling`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonobjectcreationhandling) introduced, this way:

```cs
using System.Net.Http.Json;
using System.Text.Json.Serialization;
using System.Text.Json;
using Microsoft.IdentityModel.Tokens;

var client = new HttpClient();
var response = await client.GetAsync("https://login.microsoftonline.com/common/discovery/v2.0/keys");
var jsonWebKeySet = await response.Content.ReadFromJsonAsync<JsonWebKeySet>(new JsonSerializerOptions
{
    PreferredObjectCreationHandling = JsonObjectCreationHandling.Populate
});
var count = jsonWebKeySet!.Keys.Count; // 5
```

**Suggested solution**
 
We can add the attribute `JsonObjectCreationHandlingAttribute` with the value `JsonObjectCreationHandling.Populate` directly on the `Keys` property to allow the deserialization without additional configuration.
This attribute has been introduced in .NET 8 so it will probably be necessary to condition it with `if NET8_0_OR_GREATER`.

**Comment by brentschmaltz** [comment]
@cakescience yes, this is an issue we hit when removing Newtonsoft and removing the Set;
What you have written above will not work until we release a .net 8 target with the attribute changes.

Using the ctor that takes a string will work.

**Comment by brentschmaltz** [comment]
@cakescience once .net 8 is released, we can address this and similar issues.
