### ISSUE TITLE
[Bug] Missing pdb's for all  IdentityModel assemblies 

### ISSUE THREAD

**Issue by gauravyug** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2327]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
For all IdentityModel assemblies the  pdb's need to be added to microsoft's symbol servers 
 microsoft.identitymodel.protocols.dll : 6.24
microsoft.identitymodel.abstractions.dll : 6.24
system.identitymodel.tokens.jwt.dll : 6.24
microsoft.identitymodel.jsonwebtokens.dll : 6.24
microsoft.identitymodel.protocols.openidconnect.dll : 6.24
microsoft.identitymodel.tokens.dll : 6.24
microsoft.identitymodel.logging.dll : 6.24
**Is this a new or an existing app?**
This is for Visual Studio existing extension SSDT

**Comment by brentschmaltz** [comment]
@gauravyug will have a look.

**Comment by gauravyug** [comment]
Can we have an update on this.
We need these symbols, as soon as possible.

**Comment by brentschmaltz** [comment]
@gauravyug do you still need this, it fell off our radar.
Please reopen if needed.
