### ISSUE TITLE
[Bug] After updating from 6.32.3 to version 7 keep getting invalid token and unauthorized

### ISSUE THREAD

**Issue by TheMadMattt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2329]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [X] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [X] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [X] S.IM.Tokens.Jwt
 * Other (please describe)

**Repro**

```csharp

// Configuration
services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(x =>
            {
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(signingKey)),
                    ValidateIssuer = true,
                    ValidIssuer = issuer,
                    ValidateAudience = true,
                    ValidAudience = audience,
                    RequireExpirationTime = true,
                    ValidateLifetime = true,
                    ClockSkew = TimeSpan.Zero
                };
            });

//Generating JWT

var signingCredentials = new SigningCredentials(
            new SymmetricSecurityKey(Encoding.ASCII.GetBytes(_securitySettings.Key!)),
            SecurityAlgorithms.HmacSha256);

        var handler = new JwtSecurityTokenHandler();

        var jwt = new JwtSecurityToken(
            issuer: _securitySettings.Issuer,
            audience: _securitySettings.Audience,
            claims: claims,
            notBefore: now,
            expires: expires,
            signingCredentials
        );
```

**Expected behavior**
Should accept token and authorize request successfully

**Actual behavior**
It returns 401 and Bearer= invalid_token

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by brentschmaltz** [comment]
@TheMadMattt is there an exception of error message you can share?

**Comment by TheMadMattt** [comment]
There is no error message. Request is returning 401 and in headers there is Bearer invalid_token

**Comment by brentschmaltz** [comment]
@TheMadMattt are you able to get any info from the host?

**Comment by TheMadMattt** [comment]
It’s happening locally

**Comment by brentschmaltz** [comment]
@TheMadMattt can you run the application and break when an exception is thrown?
The post the details.

**Comment by TheMadMattt** [comment]
I’m using Microsoft Authorize attribute. [Authorize()] returns 401 after updating to ver 7. Reverting back to 6.32.3 solve the issue

**Comment by brentschmaltz** [comment]
@TheMadMattt we will try and repo locally.

**Comment by AlexandreBossard** [comment]
I may have the same issue, everythings is fine with `6.32` but I keep getting invalid signature errors with `7.0`. I have implementemented my own handler and I'm callig `JsonWebTokenHander.ValidateTokenAsync(token, paremeters)`. When running the code in debug with `"justMyCode": false`, it's raising a:
```
System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
```
I'm trying to validate an asymmetrically signed token with ecdsa, public keys are fetched by the token handler's ConfigurationManager.

The sad part is that this exception is gobbled up by the `JsonWebTokenHandler` and only the validation error is visible / catchable, unless I've missed it.

**Comment by ddfreiling** [comment]
@AlexandreBossard Sounds related to #2333 , I had to add an explicit dependency on `Microsoft.IdentityModel.Validators` v7.x to fix the exact same error.

**Comment by jmprieur** [comment]
Yes, please see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x#reminder

**Comment by jennyf19** [comment]
closing, as looks to be a version mismatch. Please see the link @jmprieur provided. Thanks. Please reopen if you hit the issue again.

**Comment by TheMadMattt** [comment]
It is not version mismatch, I updated every IdentityModel package to the same version and still getting invalid_token (.NET 7)
