### ISSUE TITLE
HttpDocumentRetriever should have property to allow http, OFF by default

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#233]
Users in developing or testing sometimes need the ability to use http. We need a property here to allow http. OFF by default.

**Comment by leastprivilege** [comment]
There are valid reasons for allowing HTTP for both the discovery endpoint, the redirect URI and the authority in general.

* internal networks
* SSL offloading
* local caches

please don't make HTTPS a requirement (that you can't turn off) on any of those

**Comment by tushargupta51** [comment]
@leastprivilege Https will be turned on by default but you can turn it off by setting RequireHttps to false on HttpDocumentRetriever. The code is in review.
