### ISSUE TITLE
[Bug] LogCompleteSecurityArtifact Is not Logging Complete Security Artifact

### ISSUE THREAD

**Issue by CheetahChrome** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2358]
Microsoft.IdentityModel.[JsonWebTokens & Tokens & Tokens.Jwt] = 7.0.2
-> Exception thrown in S.IM.Tokens.Jwt.JwtSecurityToken.

New application., when I run with `IdentityModelEventSource.LogCompleteSecurityArtifact = true;` I still get the error with PII text hidden....should it not be hidden? Also why am I getting `System.Text.StringBuilder` is hidden? What does that mean stringbuilder is hidden? Isn't it in System.Text?

Can the error be more descriptive and also show the PII information...or am I missing something?

> {See below for preceding text}...Keys tried: '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Number of keys in TokenValidationParameters: '1'. <br>Number of keys in Configuration: '0'. <br>Exceptions caught:<br> '[PII of type 'System.Text.StringBuilder' is hidden. 
For more details, see https://aka.ms/IdentityModel/PII.]'.<br>token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. See https://aka.ms/IDX10503 for details.</TD></TR></TABLE>

```csharp
var jwtSource = jwt.Replace("Bearer ", "");
var secretBytes = Encoding.ASCII.GetBytes(secret);

IdentityModelEventSource.LogCompleteSecurityArtifact = true;

// Validate
var TokenHandler = new JwtSecurityTokenHandler();
var validationParameters = new TokenValidationParameters
{
	ValidateIssuerSigningKey = true,
	ValidateAudience = false,
	ValidateIssuer = false,
	IssuerSigningKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(secretBytes)
};

var result = TokenHandler.ValidateToken(jwtSource, validationParameters, out Microsoft.IdentityModel.Tokens.SecurityToken validatedToken);
```

**Expected behavior**
Listing of the PII hidden values. 

**Actual behavior**
Somewhat helpful error message, the link to the site is helpful but doesn't mention this scenario. 

Note

The initial part of the error is `SecurityTokenSignatureKeyNotFoundException: IDX10503: Signature validation failed. Token does not have a kid. Keys tried: ` to reproduce if that helps.

**Comment by brentschmaltz** [comment]
@CheetahChrome did you turn PII on?

IdentityModelEventSource.ShowPII= true;

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/5231862fdde23e73b66fbadf878b2d0143830fd1/src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs#L36

**Comment by CheetahChrome** [comment]
That was it. -thx
