### ISSUE TITLE
Is Unicode mapping being handled correctly?

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#236]
How are we handling Unicode mapping? For example, the OIDCProtocolValidator compares sub strings, is mapping an issue here?

**Comment by RandalliLama** [comment]
Moving out as we are past runway for RC1.

**Comment by polita** [comment]
Moving any coding changes to the backlog. Adding a test-and-document work item for RTM. If we find issues, let's use this to address them.
