### ISSUE TITLE
[Bug] Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

### ISSUE THREAD

**Issue by lgeissbauer-btig** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2371]
Microsoft.IdentityModel.Tokens, Version=7.0.3.0

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.Tokens.Jwt

**Expected behavior**
App just running

**Actual behavior**
```
Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, CancellationToken cancel)
   at App.WebApplicationManager.Start(String[] args) in C:\SVN\Source\trunk\App\WebApplicationManager.cs:line 21
   at App.Programm.Main(String[] args) in C:\SVN\Source\trunk\App\Program.cs:line 20

C:\SVN\Source\trunk\App\bin\Debug\net7.0-windows\App.exe (process 14948) exited with code 0.
```

**Comment by jmprieur** [comment]
Please see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x#reminder

**Comment by brentschmaltz** [comment]
@lgeissbauer-btig this could be a mismatch of assemblies.
Please re-open if this is not the case.

**Comment by lgeissbauer-btig** [comment]
I did the `dotnet list yourProject.csproj package  --include-transitive` and found out that there are

```
   > Microsoft.IdentityModel.Protocols                                                  6.15.1
   > Microsoft.IdentityModel.Protocols.OpenIdConnect                                    6.15.1
```
Now how to find where are these packages are used. In the `obj/project.assets.json` I found:
```
"Microsoft.AspNetCore.Authentication.JwtBearer/7.0.13": {
        "type": "package",
        "dependencies": {
          "Microsoft.IdentityModel.Protocols.OpenIdConnect": "6.15.1"
        },
```
How would I update that?

**Comment by lgeissbauer-btig** [comment]
This one fixed it. ty all!

https://github.com/dotnet/aspnetcore/issues/50943
