### ISSUE TITLE
Using Nightly Build OpenId 

### ISSUE THREAD

**Issue by johnkattenhorn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#239]
Hi,

I'm suffering similar issues to those raised in #143 so I'm trying to use the nightly build bits from myget.

So I un-installed Microsoft.IdentityModel.* and System.IdentityModek.* from my project and replaced them with packages from myget and got an error from my code

    return new OpenIdConnectAuthenticationOptions
            {
                ClientId = ConfigurationManager.AppSettings["ExternalAuth.WAAD.ClientId"],
                ClientSecret = ConfigurationManager.AppSettings["ExternalAuth.WAAD.ClientSecret"],
                Authority = String.Format(CultureInfo.InvariantCulture, "https://login.microsoftonline.com/{0}", ConfigurationManager.AppSettings["ExternalAuth.WAAD.TenantId"])
            };

    Additional information: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I figured I needed a redirect in my web.config so I added

      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.296" newVersion="5.0.0.296" />
      </dependentAssembly>

But I get the same message before but now with the Version=5.0.0.296. I've confirmed that this in the version number when I check the properties of the .dll in question.

I've missed a step I'm sure but not sure what it could be, anyone help ?

**Comment by johnkattenhorn** [comment]
By using the Assembly Binding Log View I could see this was being caused by not upgrading Microsoft.IdentityModel.Protocol.Extensions package not matchup, however attempting to upgrade to the Prerelease currently available in Nightly gives the following error:

    Could not install package 'Microsoft.IdentityModel.Protocol.Extensions 2.0.0-beta6-207061559'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm just checking the package itself now to see what I can find.

**Comment by johnkattenhorn** [comment]
So I downloaded the nugget package in question from myget and there isn't a net451 directory like there is for the other packages, there is a dnx451 though.

I tried to use this but my fusion log revealed that it is not signed so I think this means my redirect gets ignored.

    === Pre-bind state information ===
    LOG: DisplayName = Microsoft.IdentityModel.Protocol.Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    (Fully-specified)
    LOG: Appbase = file:///C:/dev/Repos/aspnet-zero/src/MyCompanyName.AbpZeroTemplate.Web/
    LOG: Initial PrivatePath = C:\dev\Repos\aspnet-zero\src\MyCompanyName.AbpZeroTemplate.Web\bin
    LOG: Dynamic Base = C:\Users\johnk\AppData\Local\Temp\Temporary ASP.NET Files\root\3d0dcf42
    LOG: Cache Base = C:\Users\johnk\AppData\Local\Temp\Temporary ASP.NET Files\root\3d0dcf42
    LOG: AppName = 668d31cf
    Calling assembly : Microsoft.Owin.Security.OpenIdConnect, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\dev\Repos\aspnet-zero\src\MyCompanyName.AbpZeroTemplate.Web\web.config
    LOG: Using host configuration file: C:\Users\johnk\Documents\IISExpress\config\aspnet.config
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Redirect found in application configuration file: 1.0.0.0 redirected to 2.0.0.82.
    LOG: Post-policy reference: Microsoft.IdentityModel.Protocol.Extensions, Version=2.0.0.82, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    LOG: GAC Lookup was unsuccessful.
    LOG: Attempting download of new URL file:///C:/Users/johnk/AppData/Local/Temp/Temporary ASP.NET Files/root/3d0dcf42/668d31cf/Microsoft.IdentityModel.Protocol.Extensions.DLL.
    LOG: Attempting download of new URL file:///C:/Users/johnk/AppData/Local/Temp/Temporary ASP.NET Files/root/3d0dcf42/668d31cf/Microsoft.IdentityModel.Protocol.Extensions/Microsoft.IdentityModel.Protocol.Extensions.DLL.
    LOG: Attempting download of new URL file:///C:/dev/Repos/aspnet-zero/src/MyCompanyName.AbpZeroTemplate.Web/bin/Microsoft.IdentityModel.Protocol.Extensions.DLL.
    LOG: Assembly download was successful. Attempting setup of file: C:\dev\Repos\aspnet-zero\src\MyCompanyName.AbpZeroTemplate.Web\bin\Microsoft.IdentityModel.Protocol.Extensions.dll
    LOG: Entering download cache setup phase.
    LOG: Assembly Name is: Microsoft.IdentityModel.Protocol.Extensions, Version=2.0.0.82, Culture=neutral, PublicKeyToken=null
    WRN: Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN
    ERR: The assembly reference did not match the assembly definition found. 
    ERR: Setup failed with hr = 0x80131040.
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by tushargupta51** [comment]
@johnkattenhorn Which version of MS.IM.Protocols.Extensions are you using: 1.x or 2.x? We added the support for net451 in 2.x in beta7 but we also did some package renaming (more details here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KRelease/CHANGELOG.md). You can get the latest 1.x package from nuget.org (https://www.nuget.org/packages/Microsoft.IdentityModel.Protocol.Extensions/1.0.2.206221351) and it should have the fix for #143.

**Comment by johnkattenhorn** [comment]
I'm trying to use 2.x as System.IdentityModel.Tokens.Jwt version 5.x seem dependant on it. There definitely seems to be a packaging issue for identity model extensions as you can see from my comments about the 2.x packages for beta 6 just don't include the 451.

I didn't release though that in fact this fix has been pushed to the latest 1.x as well, maybe I have a different problem and I'm fault finding logic is faultly :-)

It would still be good to try out 2.x packages though.

**Comment by tushargupta51** [comment]
@johnkattenhorn If you want to use 2.x, then you have to use beta7 or higher since we added support for net451 after that. It does not exist in beta6 so beta6 packages wont work against dotnet 4.5.1.

**Comment by brentschmaltz** [comment]
@johnkattenhorn we are experiencing issues with packages with VS 2013. Package manager is complaining.  Also note, we haven't tested 4.5.1 with these beta packages.

**Comment by johnkattenhorn** [comment]
Hey @brentschmaltz, I'm using VS2015 and I'm going to look into this issue again later today to see if I've picked the wrong package (beta6) by mistake and I'll report back.

The only other thing I was thinking of trying was to try to build from source again by sign them so I could perform the version re-directs for dependent assemblies (e.g. ASP.NET Identity).

**Comment by brentschmaltz** [comment]
@johnkattenhorn closing this out, please re-open if you still have a problem.
