### ISSUE TITLE
Constructor Difference for SignigingCredentails in .NET Core

### ISSUE THREAD

**Issue by devprj22** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2392]
I am working on migrating my app from .NET Core to .NET Framework.

In the codebase, we have following piece of code -

```
                samlAssertion.SigningCredentials = new SigningCredentials(
                    securityKey,
                    SecurityAlgorithms.RsaSha1Signature,
                    SecurityAlgorithms.Sha1Digest,
                    securityKeyIdentifier);
```

In the .NET Core implementation, I see that the `SigningCredentials` class inside `Microsoft.IdentityModel.Tokens.Saml` namespace **does not** takes `securityKeyIdentifier`.

I looked at the .NET Framework implementation and could see that securityKeyIdentifier was just present as a public field with a getter and was not used in any computation logic inside `SigningCredentails`.

So, it looks like it is not needed, but it would be great if anyone can confirm that we are good using the .NET Core constructor without `securityKeyIdentifier`.

**Comment by brentschmaltz** [comment]
@devprj22  in general the .net core implementation is not a 1:1 port of System.IdentityModel.
We don't need SecurityKeyIdentifier.
