### ISSUE TITLE
[Question] Cannot serialize object

### ISSUE THREAD

**Issue by JordanRhode** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2397]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel.Tokens 7.0.3
System.IdentityModel.Tokens.Jwt 7.0.3

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Repro**
```csharp
var tokenDescriptor = new SecurityTokenDescriptor
{
	Claims = new Dictionary<string, object>
	{
		{ "test_claim", new { property = "value" } }
	},
	// non-relevant properties omitted
};
var tokenHandler = new JwtSecurityTokenHandler();
var securityToken = tokenHandler.CreateToken(tokenDescriptor);
```

**Expected behavior**
I would expect a security token to be created

**Actual behavior**
An exception with the following message is thrown: `IDX11025: Cannot serialize object of type: '<>f__AnonymousType10`1[System.String]' into property: 'test_claim'.`

**Possible solution**

**Additional context / logs / screenshots / links to code**
Reverting back to the following fixes this error:
Microsoft.IdentityModel.Tokens 6.32.0
System.IdentityModel.Tokens.Jwt 6.32.0

**Comment by lachezar-gizdov** [comment]
We got this error, seems to be connected:

"IDX11025: Cannot serialize object of type: 'System.Object' into property: ...."

System.IdentityModel.Tokens.Jwt 7.0.3

**Comment by JoshuaEN** [comment]
Nested dictionaries can be used as a workaround:
```csharp
var tokenDescriptor = new SecurityTokenDescriptor
{
Claims = new Dictionary<string, object>
    {
        { "test_claim", new Dictionary<string, string> { { "property", "value" } } }
    },
// non-relevant properties omitted
};
var tokenHandler = new JwtSecurityTokenHandler();
var securityToken = tokenHandler.CreateToken(tokenDescriptor);
```

Tested on System.IdentityModel.Tokens.Jwt (7.0.3)

**Comment by Menyus777** [comment]
The same happens with Collection types.
```
ArgumentException: IDX11025: Cannot serialize object of type: 'System.Linq.Enumerable+SelectEnumerableIterator`2[GoTo.Synapse.TokenService.Domain.Common.Model.Capability,System.String]' into property: 'capabilities'.
Microsoft.IdentityModel.Tokens.Json.JsonSerializerPrimitives.WriteObject(ref Utf8JsonWriter writer, string key, object obj)
```

**Comment by steffibreuer** [comment]
And also with `HashSet<object>`

**Comment by tuukkapuranen** [comment]
The following also works with version 6.35.0, but results in an `IDX11025` error with version 7.2.0:
```
var descriptor = new SecurityTokenDescriptor
{
    Claims = new Dictionary<string, object>
    {
        { "events", new Dictionary<string, object> { { "http://schemas.openid.net/event/backchannel-logout", new object() } } }
    }
};
```
The workaround mentioned might not be directly applicable as the resulting json should be of the form:

```
  {
   "events": {
     "http://schemas.openid.net/event/backchannel-logout": {}
     }
  }
```
Note the lack of quotes in the value.

**Comment by IGx89** [comment]
As another workaround you can wrap your object in a call to `JsonSerializer.SerializeToElement`:
```csharp
Claims = new Dictionary<string, object>
{
    { "test_claim", JsonSerializer.SerializeToElement(myObject) }
},
```

**Comment by keegan-caruso** [comment]
@JordanRhode please see this comment: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2455#issuecomment-1911006805

We had to move away from Newtonsoft internally to System.Text.Json. This was to provide reflection free code that works well with native aot.

We need to do better in our docs for 7x around this.

**Comment by keegan-caruso** [comment]
Please reopen if you have additional questions.

**Comment by Menyus777** [comment]
@keegan-caruso I'm sorry, but what is the fix for collection types? Many oidc claims uses array of strings to represent values. This change basically broke all these. Also our custom JWS token has a claim named `capabilities`. THis claim contains nuemrous string values as an array. Currently I can not increase the nuget version to 7.x.x as with an upgrade I can no longer generate jws tokens cos it fails with the above error.

**Comment by JordanRhode** [comment]
> @keegan-caruso I'm sorry, but what is the fix for collection types? Many oidc claims uses array of strings to represent values. This change basically broke all these. Also our custom JWS token has a claim named `capabilities`. THis claim contains nuemrous string values as an array. Currently I can not increase the nuget version to 7.x.x as with an upgrade I can no longer generate jws tokens cos it fails with the above error.

Have you tried wrapping your `capabilities` claim value in `JsonSerializer.SerializeToElement`?

Here is the working solution for my reproduction of the error above:
```
var tokenDescriptor = new SecurityTokenDescriptor
{
    Claims = new Dictionary<string, object>
    {
        { "test_claim", System.Text.Json.JsonSerializer.SerializeToElement(new { property = "value" }) }
    },
    // non-relevant properties omitted
};
var tokenHandler = new JwtSecurityTokenHandler();
var securityToken = tokenHandler.CreateToken(tokenDescriptor);
```

**Comment by Menyus777** [comment]
Ouch, I have read `SerializeToObject`... I see this prolly serializes the value to a Json element. Will try this one thanks...

**Comment by eldarmahmudov** [comment]
Use NewtonSoft JSon  

Create method like this

      Dictionary<string, object> GetAsDictionary<TPayload>(TPayload payload)
        {
            return JObject.FromObject(payload).ToObject<Dictionary<string, object>>();
        }

And add object like below
  
  ```
        var tokenDescriptor = new SecurityTokenDescriptor
            {
                Issuer = "Issuer",
                Subject = new ClaimsIdentity(new[] {
                    new Claim("guid", guid.ToString("N")) }),
                Expires ="Your Token Expire Date",
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(secretKey), SecurityAlgorithms.HmacSha256Signature),
                Claims = new Dictionary<string, object>() { { "details", GetAsDictionary(tokenPayload) } }
            };
```

**Comment by vmandic** [comment]
Thank you @IGx89, `SerializeToElement()` solves this issue.
