### ISSUE TITLE
Nightly feeds on myget spells 'extensions' as 'extensiions' extra i

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#241]

**Comment by tushargupta51** [comment]
@brentschmaltz Where did you see that typo? In the package name? I don't see it here: https://www.myget.org/gallery/azureadwebstacknightly

**Comment by tushargupta51** [comment]
Ah, got it. It was in the feed description. Fixed it.
