### ISSUE TITLE
amr is an array

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#242]
http://openid.net/specs/openid-connect-core-1_0.html#IDToken

amr
OPTIONAL. Authentication Methods References. **JSON array of strings** that are identifiers for authentication methods used in the authentication. For instance, values might indicate that both password and OTP authentication methods were used. The definition of particular values to be used in the amr Claim is beyond the scope of this specification. Parties using this claim will need to agree upon the meanings of the values used, which may be context-specific. The amr value is an array of case sensitive strings.

**Comment by brentschmaltz** [comment]
This will result in a OM change. We should tackle this soon.
