### ISSUE TITLE
Cannot install packages on Visual Studio 2013

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#243]
Create a Visual Studio project in 2013 and attempt to add a 5.x package.
Tushar,  please add the error description.

**Comment by tushargupta51** [comment]
Related Issues:
https://github.com/aspnet/Home/issues/368
https://github.com/aspnet/EntityFramework/issues/657

Solution:
Update nuget manager on VS 2013 here : Tools > Extensions and Updates > Updates  to be >=2.8.3. Tested after updating the nuget and it installs all the packages, used configurationManager api, all works fine.
