### ISSUE TITLE
Adding fields to Client Secret JWT

### ISSUE THREAD

**Issue by PedroSchroeder** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2432]
Hi!
I'm integrating Microsoft ID authentication into my API (api0) and plan to access it using two different APIs (api1 and api2). For this, I'm utilizing a unique Client Secret for each API. However, I'm encountering a challenge: there isn't a field in the generated JWT token (created with the Client Secret) that indicates which API is making the request to api0. I would like to add a custom field to the JWT token to identify the originating API. Those are the default fields in the JWT:

```
{
  "aud": "",
  "iss": "",
  "iat": 1,
  "nbf": 1,
  "exp": 1,
  "aio": "",
  "azp": "",
  "azpacr": "",
  "oid": "",
  "rh": "",
  "sub": "",
  "tid": "",
  "uti": "",
  "ver": "2.0"
}
```

**Comment by jmprieur** [comment]
@PedroSchroeder 
You could use the azp claim. It contains the Application ID of the client application that requested the token. I assume that api1 and api2 have a different client Id (they should)

**Comment by PedroSchroeder** [comment]
Thank you so much, @jmprieur! I have one more question: Is it possible to implement an automated system for renewing the client secret when it's nearing expiration, or do I need to manually create a new client secret each time?
