### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wmmihaa** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2443]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
7.0

**Where is the issue?**
 * [x] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Problem**
As we've updated the existing ASP.Net Core application from .net6 => .net8 validation of JWT tokens no longer work. **It's important that existing tokens, generated from the .net6 version of the application continues to work as before.**

**Existing code**
```csharp
services.AddAuthentication().AddJwtBearer(options =>
{
    options.RequireHttpsMetadata = false;
    options.SaveToken = true;
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuerSigningKey = true,
        IssuerSigningKey = key,
        ValidIssuer = token.Issuer,
        ValidAudience = token.Audience,
        ValidateIssuer = true,
        ValidateAudience = true
    };
   
    // added after suggestions from https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events
    options.UseSecurityTokenValidators = true; 

    options.Events = new JwtBearerEvents();
    options.Events.OnChallenge = context =>
    {
        context.HandleResponse();

        var payload = new JObject
        {
            ["error"] = context.Error,
            ["error_description"] = context.ErrorDescription,
            ["error_uri"] = context.ErrorUri
        };

        context.Response.ContentType = "application/json";
        context.Response.StatusCode = 401;

        return context.Response.WriteAsync(payload.ToString());
    };
});
```

**Also...**
I've read about the breaking changes in this post https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events. But I'm a bit confused to what `service` refers to as in:
```csharp
service.Configure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme,  options => {
    options.UseSecurityTokenValidators = true;
    options.Events.TokenValidated = (context) => {
        // As you were doing before
        JwtSecurityToken token = context.SecurityToken as JwtSecurityToken;
        // Do something ...
    };
});
```
Is there a sample of this code in the whole context of `program.cs`

**Comment by keegan-caruso** [comment]
What is the error you are seeing?

**Comment by wmmihaa** [comment]
I'm adding this comment as it might help others....
We've migrated an application from .net6 => .net8. Users can generate JWT tokens within the application and use the token to authenticate when calling the API of the same application.
After upgrading the application, users could not be authenticated and the response was always "invalid token" (Unable to decode the payload).

The problem in our case was that the JwtSecurityToken was setting the JwtRegisteredClaimNames.Iat claim to DateTime.UtcNow.ToString() which worked fine in .Net 6, where as this has changed in .Net 8 which requires the Iat to be set using epoch format. After this change was applied all JWT tokens were evaluated correctly.
