### ISSUE TITLE
[Feature Request] Remove KeyVaultExtensions and ManagedKeyVaultSecurityKey

### ISSUE THREAD

**Issue by ciaozhang** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2454]
Those 2 extensions cause [CVE](https://identitydivision.visualstudio.com/IDDP/_componentGovernance/95750?_a=alerts&typeId=20680128&alerts-view-option=active). The new KV library will cause dependency issue, no plan to adopt the new one.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/dev/src/Microsoft.IdentityModel.KeyVaultExtensions

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/dev/src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey

**Comment by brentschmaltz** [comment]
We need to remove this in 8.0.

**Comment by jennyf19** [comment]
will stop releasing these soon and add documentation for guidance.

**Comment by joegoldman2** [comment]
I guess this issue is fixed by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2635 and can be closed?

**Comment by brentschmaltz** [comment]
Completed: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2635

**Comment by philliphoff** [comment]
@brentschmaltz @jennyf19 Is there guidance for those using (or wanting to use) the former `KeyVaultExtensions` package for, say, JWE creation/validation?

**Comment by logiclabs** [comment]
Any chance of removing the Wiki documentation around KeyVaultExtensions? They are already pretty much broken in .NET 8 and IdentityModel 7.  As per @philliphoff  comment, it would also be great if an alternative could be documented?
