### ISSUE TITLE
[Question] How to Serialize custom objects into JWT? 

### ISSUE THREAD

**Issue by realemx** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2455]
**Which version of Microsoft.IdentityModel are you using?**
System.IdentityModel.Tokens.Jwt 6.35.0
System.IdentityModel.Tokens.Jwt 7.2.0

**Where is the issue?**
 * [ X ] M.IM.Tokens

**Is this a new or an existing app?**
We have an app in production with .NET 6 & System.IdentityModel.Tokens.Jwt 6.35.0 where everything works like we have designed it a year ago. Now we want to update to .NET 8 and every package possible, but there is a breaking change we need a solution for: We need custom json object in the token as a claim. Now with 7.2.0 it seems to be not possible to archive the 6.x.x behaviour.

**Repro**

```csharp
public class DemoClass
{
    public string RandomName { get; set; }
    public List<string> RandomList { get; set; }
}

// ...

var securityToken = new JwtSecurityToken(
                issuer: PermissionConstants.ISSUER,
                audience: PermissionConstants.AUDIENCE,
                expires: DateTime.UtcNow.AddMinutes(30),
                notBefore: DateTime.UtcNow,
                claims: claims,
                signingCredentials: new X509SigningCredentials(certificate, SecurityAlgorithms.RsaSha256)
            );

var obj = new DemoClass {
    RandomName = "Foo",
    RandomList = new List<string> { "Bar", "Baz" }
};
securityToken.Payload["customClaimDirect"] = obj;
securityToken.Payload["customClaimJson"] = JsonConvert.SerializeObject(obj);
```

**Expected behavior**
This ist from the decoded token on version 6.35.0
(I did not include the "customClaimJson" claim as it already did not work on 6.35.0, I just added it to the code for completeness sake)
```json
"customClaimDirect": {
    "RandomName": "Foo",
    "RandomList": [
      "Bar",
      "Baz"
    ]
  },
```

**Actual behavior**
the "customClaimDirect" claim throws this:
> System.ArgumentException: IDX11025: Cannot serialize object of type: 'DemoClass' into property: 'customClaimDirect'.

And the serialized one produces this, which we can not use:
```json
"customClaimJson": "{\"RandomName\":\"Foo\",\"RandomList\":[\"Bar\",\"Baz\"]}"
```

**Possible solution**
Restore the old behaviour by bringing it back to 7.2+ or let me know a workaround to get this working again.

**Comment by keegan-caruso** [comment]
JsonConvert.SerializeObject is newtonsoft, yes? Internally we switched to system.text.json.

You should be able to use [SerializeToElement](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.serializetoelement?view=net-8.0#system-text-json-jsonserializer-serializetoelement(system-object-system-text-json-serialization-metadata-jsontypeinfo)) from the new library.

You will also see benefits if you move away from JwtSecurityToken to JsonWebToken

**Comment by realemx** [comment]
Thank you @keegan-caruso, SerializeToElement already brought back the old behaviour. We will also look into using JsonWebToken, thank you for the advice.

**Comment by realemx** [comment]
I need to reopen this.

We wanted to change to JsonWebToken, sadly we can not see a way to get our desired behaviour back. 

If we understand the library correctly, this is how a token now get's created:

```cs
var handler = new JsonWebTokenHandler();
var tokenString = handler.CreateToken(tokenDescription);
```

But this directly creates the string, were we cannot insert our custom classes. If we try to add them to the Claims, it requires to serialize them to a string first, which breaks the token again because it get's escaped. 

Is there a way to get the JwtSecurityToken behaviour with the new JsonWebToken ?

**Comment by keegan-caruso** [comment]
Here is an example using your demo class of serializing / deserializing.

```cs
            var obj = new DemoClass
            {
                RandomName = "Foo",
                RandomList = new List<string> { "Bar", "Baz" }
            };

            var descriptor = new SecurityTokenDescriptor
            {
                Claims = new Dictionary<string, object>
                {
                    { "customClaimJson", JsonSerializer.SerializeToElement(obj) }
                },
            };

            var handler = new JsonWebTokenHandler();
            var tokenExample = handler.CreateToken(descriptor);

            var readToken = handler.ReadJsonWebToken(tokenExample);
            var customClaim = readToken.GetPayloadValue<JsonElement>("customClaimJson");

            // this will use reflection, can use source generation to avoid reflection.
            // https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/reflection-vs-source-generation?pivots=dotnet-8-0
            var readObject = JsonSerializer.Deserialize<DemoClass>(customClaim);
```

I'm going to close this issue again but feel free to reopen if this isn't clear.
