### ISSUE TITLE
[Feature Request] Add support for Google first class discover properties

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2456]
https://accounts.google.com/.well-known/openid-configuration contains: 
code_challenge_methods_supported
revocation_endpoint
device_authorization_endpoint

Add support in OpenIdConnectConfiguration as first class properties.

Care should be taken to use an [AppContent](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext?view=net-8.0) Switch as some customers may be expecting to find the values in AdditionalData.

**Comment by ghost** [comment]
I'm interested in implementing this feature, but I have questions first. What is the purpose of the switch? To have the values in the dedicated properties and also in AdditionalData? Or only in AdditionalData if enabled? IMHO, given that these three metadata are standard, customers shouldn't have to enable a switch to have the values in the dedicated properties.

**Comment by brentschmaltz** [comment]
@joegoldman2 if you have existing code that expects to find the values in AdditionalData, after the update the values will not be there, and the scenario will break.

Users will need to be able to control the if the values are added only to the first class properties.

**Comment by ghost** [comment]
Could the behavior for version 8 (because we'd be introducing a breaking change here) be to have the values available by default in the dedicated properties? Because we're talking here about standard protocol properties where AdditionalData shouldn't be necessary.
