### ISSUE TITLE
Incorrect cast in AsymmetricSignatureProvider

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#247]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens/AsymmetricSignatureProvider.cs#L106

With recent changes in CoreFX, `RSACertificateExtensions.GetRSAPublicKey` can now return a `RSACng` instance - instead of a `RSACryptoServiceProvider` - on platforms supporting CNG.

Since IdentityModel expects a `RSACryptoServiceProvider`, the cast fails and the `rsa` variable is null on CoreCLR, which later causes a NRE in `RSACryptoServiceProviderProxy`.

Related topic: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/130

**Comment by csunali** [comment]
Thank you, @PinpointTownes, for pinging the right people in the right repository! :+1:

**Comment by brentschmaltz** [comment]
@PinpointTownes thanks.

**Comment by PinpointTownes** [comment]
@tushargupta51 thanks for fixing this bug :+1:
