### ISSUE TITLE
[Bug] Upgrading M.ANC.Authentication.JwtBearer to latest version breaks because of breaking change in S.IM.Tokens.Jwt

### ISSUE THREAD

**Issue by synercoder** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2477]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel 6.35

**Where is the issue?**
 * [X] M.IM.Protocols.OpenIdConnect _(kinda)_
 * [X] S.IM.Tokens.Jwt

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Repro**
**Working version:** https://github.com/synercoder/JwtBearerBreakingChange
**Broken by upgrading 6.0.25 to 6.0.26:** https://github.com/synercoder/JwtBearerBreakingChange/tree/upgrade-to-broken ([change commit](https://github.com/synercoder/JwtBearerBreakingChange/commit/be954a8da8c1ba7dfe331c4138e1fe9184960491))
**Fix/workaround (see below):** https://github.com/synercoder/JwtBearerBreakingChange/tree/work-around ([change commit](https://github.com/synercoder/JwtBearerBreakingChange/commit/e63e51815c7ffeea7bb891558a538f2ba2954e56))

**Expected behavior**
The validation keeps working after upgrading to latest version.

**Actual behavior**
**Short version:** It doesn't work anymore.

**Long version:** In `System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler` the method `protected virtual JwtSecurityToken ValidateSignature(string token, TokenValidationParameters validationParameters)` was used to verify the signature in the 
`public override ClaimsPrincipal ValidateToken(string token, TokenValidationParameters validationParameters, out SecurityToken validatedToken)` method. This method is since rewritten/refactored, to no longer use the previously mentioned `ValidateSignature`.

**The entire method is no longer used in the entire class.**

Thus sub-class implementations of JwtSecurityTokenHandler that only override `JwtSecurityToken ValidateSignature(string token, TokenValidationParameters validationParameters)` will no longer work.

**When was this change introduced?**
Well... This change was introduced in S.IM.Tokens.Jwt in [#1797](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1797/files#diff-0b1054c790c38d665f14eee85e63889a6c64f63e87ab7ded11b86708f1ed1475) so 6.16.0 / 23 jan **2022** (2 years ago).

But... this issue only surfaced when I was upgrading `Microsoft.AspNetCore.Authentication.JwtBearer` from 6.0.25 to 6.0.26, which came out on 9 jan **2024** (three weeks ago), because:
```
Microsoft.AspNetCore.Authentication.JwtBearer 6.0.26
 => Microsoft.IdentityModel.Protocols.OpenIdConnect 6.35.0
     => System.IdentityModel.Tokens.Jwt 6.35.0,
Microsoft.AspNetCore.Authentication.JwtBearer 6.0.25 
 => Microsoft.IdentityModel.Protocols.OpenIdConnect 6.10.0
     => System.IdentityModel.Tokens.Jwt 6.10.0
```

**Possible solution**
If you expose the current protected method to the public, and then hook that method up to `JwtBearerOptions.TokenValidationParameters.SignatureValidator`, the code will work again. Also, if the method is no longer in use, mark it as obsolete or better yet, make it a breaking change and delete the method. See https://github.com/synercoder/JwtBearerBreakingChange/commit/e63e51815c7ffeea7bb891558a538f2ba2954e56

**Comment by brentschmaltz** [comment]
@synercoder yep, you are correct. We don't call the virtual.
Marked the bug as a regression.

**Comment by sampulsar** [comment]
The issue was also found using Azure AD as the library initially was able to parse the tokens but later tests found that it was not able to parse the tokens once they were automatically cycled. The resolution was to upgrade to form 6.xx to 7.xx.

**Comment by brentschmaltz** [comment]
upgrading seems to fix the issue.

**Comment by synercoder** [comment]
@brentschmaltz  I like to disagree and reopen, because there still is a protected virtual method that people can override that is not used/called anywhere, same virtual also exists in 7.4.0 tag and isn't called anywhere as well. Upgrading wont help.
