### ISSUE TITLE
COSMETIC ISSUE - Microsoft.IdentityModel.JwtTokens

### ISSUE THREAD

**Issue by chris-briddock** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2483]
I have spotted a little error with output when running tests when validating a JWT token.

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/14249890/4bdaa66a-0cca-4def-a323-693c8590b8fd)

It says the "Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: The token's kid is missing. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey"

**Comment by brentschmaltz** [comment]
@chris-briddock what this message is saying is:
The JWT did not have a kid, and we tried a SymmetricSecurityKey with this keyid.

I think it is ok, please reopen if i missed something.
