### ISSUE TITLE
Design decisions from v6 to v7

### ISSUE THREAD

**Issue by dgioulakis** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2486]
In upgrading our IdentityModel libraries to v7, I've noticed breaking changes to the serialization of `OpenIdConnectConfiguration`, and before I go about implementing a solution, I was curious to learn the reasons why the changes were made - just in case there is something I'm not considering, but perhaps should.

In particular, a `[JsonIgnore]` attribute was placed over `JsonWebKeySet`. Therefore, no serialization of keys will occur. This has been problematic for us because we cache our customer's identity provider metadata in Redis. We cannot rely on the Microsoft `ConfigurationManager` in-memory, instance-based cache because our identity providers are not statically defined in Startup.cs, but instead loaded dynamically from the database. Therefore, the `ConfigurationManager` instances are ephemeral and so I've decorated the default `OpenIdConnectConfigurationRetriever` to use our own distributed caching tier.
e.g.
```
new CachingConfigurationRetriever<OpenIdConnectConfiguration>(new OpenIdConnectConfigurationRetriever(), _cache)
```

Unfortunately, by no longer serializing the `JsonWebKeySet`, we have lost our ability to validate JWTs, resulting in the exception:
```
SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
```

1. Aside from all the performance enhancements the team has done, and migration away from Newtonsoft, is the intent of the new serialization logic for `OpenIdConnectConfiguration` to match the .well-known discovery endpoint specs?
2. Are there any plans to make public the `JsonWebKeySetSerializer`?
    - Or is there another mechanism I can currently use to serialize this data - aside from writing our own?

e.g. Caching Decorator Example
```
public async Task<T> GetConfigurationAsync(string address, IDocumentRetriever retriever, CancellationToken cancel)
{
    return await _cache.GetOrSetAsync<T>(
        CacheKey.Authentication.Federation.IdentityProviderMetadata(address),
        async (ctx, token) =>
        {
            try
            {
                token.ThrowIfCancellationRequested();
                return await _inner.GetConfigurationAsync(address, retriever, token);
            }
            catch
            {
                ctx.Options.SetDuration(TimeSpan.FromSeconds(5));
                throw IdentityException.Authentication.Federation.IdPMetadataInaccessible;
            }
        },
        CacheKey.Authentication.Federation.DefaultIdentityProviderMetadataCacheOptions,
        token: cancel);
}
```

**Comment by brentschmaltz** [comment]
@dgioulakis yes, the logic behind the [JsonIgnore] was to restrict the values to those found in a standard .well-known discovery endpoint.

Our goals were to increase performance, reduce memory allocations and support [AOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7%2Cwindows) which has constraints on reflection.

We recognize that, OpenIdConnectConfiguration, JsonWebKey, JsonWebKeySet, JsonWebToken are not sealed and an extensibility model for serialization is needed. Currently we add unknown properties to AdditionalData (Dictionary<string, objext>) this is somewhat workable, but not idea.

The [JsonIgnore] was added to reduce functionality while we designed and implemented an extensibility solution.

We have issued opened, here is one of [them.](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2290)

If [JsonIgnore] was removed, would this fix your immediate situation.

We haven't discussed opening up the internal serializers.
We do realize extensibility is needed in some form.

**Comment by dgioulakis** [comment]
@brentschmaltz Removing the `[JsonIgnore]` attribute would likely fix this issue, but it would understandably take away from your goal to match the OIDC spec on .well-known endpoints. Effectively, in v6, we were able to easily cache both openid-configuration and the jwks endpoint data in one model.

I could create a simple wrapper of sorts that just encapsulates these two documents and cache that.
e.g.
```
public record OpenIdConnectConfigurationWrapper(OpenIdConnectConfiguration Configuration, JsonWebKeySet JsonWebKeySet);
```

Then upon retrieval from cache, set the configuration's keys manually from the jsonWebKeySet. This is what I'm currently looking at doing, but I won't be able to take advantage of your jsonwebkey serializers since they're internal.

**Comment by brentschmaltz** [comment]
@dgioulakis if we to make the serializer public, without extensibility in the first release, AdditionalData will be populated with .net types and JsonElements which could then be set on derived classes.

That would be preferred to removing the JsonIgnore.

**Comment by dgioulakis** [comment]
Thanks for the helpful info @brentschmaltz. For now, I think it's probably best for us to rollback to v6.35.0 until I can dedicate more time to ensuring the migration to v7 would not introduce regressions for our customers. I see there may also be existing issues with the parsing of Google's OIDC config (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2347) and we have a number of customers using their IdP.

I'll keep an eye out for new releases from the team here.

**Comment by brentschmaltz** [comment]
@dgioulakis we are currently fixing #2347 along with other similar issues.

**Comment by ClumsyPenguin** [comment]
Are the still plans to open up the serializers as i encountered the same issue.
I am currently rocking `System.IdentityModel.Tokens.Jwt` on `7.5.1`

I also had to make a wrapper around configuration like so.

```csharp
public class OpenIdConnectDiscoveryConfigurationWrapper
{
    [JsonConstructor]
    public OpenIdConnectDiscoveryConfigurationWrapper(Url authorizationUrl, Url tokenEndpoint, Url endSessionEndpoint, JsonWebKeySet jsonWebKeySet)
    {
        AuthorizationUrl = authorizationUrl;
        TokenEndpoint = tokenEndpoint;
        EndSessionEndpoint = endSessionEndpoint;
        JsonWebKeySet = jsonWebKeySet;
    }
    
    [JsonPropertyName("TokenEndpoint")]
    public Url TokenEndpoint { get; private set; }
    
    [JsonPropertyName("AuthorizationUrl")]
    public Url AuthorizationUrl { get; private set; }
    
    [JsonPropertyName("EndSessionEndpoint")]
    public Url EndSessionEndpoint { get; set; }
    
    [JsonPropertyName("JsonWebKeySet")]
    public JsonWebKeySet JsonWebKeySet { get; private set; }
}

```

However i am able to cache the keys in Redis. I've yet to figure out how to correctly deserialize them 
![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/22469147/99bc0a56-0e8b-45cb-baff-f8c3276173f6)

Currently i've yet to figure out how to deserialize them since retrieving this object from Redis result in an empty `JsonWebKeySet`

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/22469147/93d8f0a2-2307-4ff7-a86b-97824a432d17)
