### ISSUE TITLE
[Feature Request] Add a JsonWebToken Constructor that accepts ReadOnlyMemory representation of the encodedToken

### ISSUE THREAD

**Issue by sruke** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2487]
**Is your feature request related to a problem? Please describe.**
The usage of String.Split to extract segments from the token is expensive as it creates new strings and leads to additional memory allocation.

**Describe the solution you'd like**
- Introduce a JsonWebToken Constructor that accepts ReadOnlyMemory representation of the encodedToken. This would allow us to substitute string.Split with span.Slice which will avoid string creation.
- Update existing constructors to call into ReadTokens(ReadOnlyMemory<char>) to maintain a single code path and enable current implementations to take advantage of some of the improvements without making any changes.

**Comment by Saibamen** [comment]
I would love to see benchmarks

**Comment by sruke** [comment]
> I would love to see benchmarks

Added benchmarks in the [PR](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2458)  that I just linked to the GitHub issue and in the [discussion board](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/discussions/2488) where a preview has been shared. Appreciate any feedback.

@Saibamen ^
