### ISSUE TITLE
SymmetricSignatureProvider for coreclr has no implementation / support for HMAC

### ISSUE THREAD

**Issue by sandorfr** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#250]
As mentioned in this issue (https://github.com/aspnet/Security/issues/439), it is not possible to produce HMAC signed token atm. This is quite annoying because Hmac token are very common (azure mobile services uses them) and the RSA alternative does not currently work on OSX coreclr.

The workaround was quite easy, I just had to create a SignatureProviderFactory which returns a SymmetricSignatureProvider inspired from the main branch of this repo. It just feels really hacky for something that common.

Since there is nothing coming for that matter on the KDev branch, I would be very happy to provide a pull request adding that support.

Warm regards

**Comment by sandorfr** [comment]
I also had to derive SymmetricSecurityKey to implement GetSignatureProvider which is used by the current JwtSecurityTokenHandler despite I provide an explicit SignatureProviderTokenFactory.

The current code base seems a little confusing with that SignatureProviderTokenFactory which can come from to many different places and you can't replace with your own with a single configuration.

**Comment by RandalliLama** [comment]
@brentschmaltz Could you take a look at this?

**Comment by tushargupta51** [comment]
@sandorfr We are planning to add Symmetric Signature provider support in KDev in RC. Do you want to send a PR for just HMAC support or complete symmetric signature provider because currently in KDev, it is just stubs.

**Comment by sandorfr** [comment]
I'm gonna make a preview PR with my current work so we can discuss how I can make it more complete.

**Comment by brentschmaltz** [comment]
great, love to see it.

**Comment by sandorfr** [comment]
Yes I noticed that while preparing my PR, there almost nothing to be done (or I'm missing something)
https://github.com/sandorfr/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1

**Comment by brentschmaltz** [comment]
@sandorfr I think your fix looks pretty good.  We don't want to create signature with SHA1, we can verify them though. Can you get the PR against this repo?

**Comment by sandorfr** [comment]
@brentschmaltz I already signed a CLA for another PR should I do it again?

Regarding the SHA1, I know this is not the best choice in terms of security but is there a specific reason to prevent people to do it without overriding the signature provider is they need it?

**Comment by martinbliss** [comment]
This was closed due to a commit/merge but is it available for consumption? Because I've tried "5.0.0-beta8-21031116" and "5.0.0-rc1-211161024" and issues regarding signing credential algorithms persist with both. How can I track the whereabouts of the KDev branch with respect to Nuget?

With the beta8 version, I get an algorithm not supported exception. With the rc1, I get a "signatureProvider argument cannot be null or empty" and this is because SecurityKey.GetSIgnatureProviderForSigning() returns null regardless of input (it appears, anyway).

For the record, below are algorithms I tried:

http://www.w3.org/2001/04/xmldsig-more#hmac-sha256
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512

**Comment by tushargupta51** [comment]
@martinbliss, this will be part of rc2 release which will be released in mid feb to nuget. In the meantime, you can comsume our nightly dev packages from myget here: http://myget.org/gallery/azureadwebstacknightly. Please be advised that these are not the released bits, official release to nuget will be in mid feb. The package has been renamed from system.im.tokens to microsoft.im.tokens.
