### ISSUE TITLE
Mismatched version results in failure to read claims

### ISSUE THREAD

**Issue by reduckted** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2506]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**

The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Repro**

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.4.0" />
  </ItemGroup>

</Project>
```

`Program.cs`:
```csharp
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

JwtPayload payload;
JwtSecurityTokenHandler handler = new();

JwtHeader tokenHeader = new(
        new SigningCredentials(
        new SymmetricSecurityKey(Encoding.UTF8.GetBytes("abcdefghijklmnopqrstuvwyxyzabcdefghijklmnopqrstuvwyxyz")),
        SecurityAlgorithms.HmacSha256
    )
);

var claims = new List<Claim> {
    new Claim(ClaimTypes.NameIdentifier, "42", ClaimValueTypes.Integer32),
    new Claim(ClaimTypes.Name, "me", ClaimValueTypes.String)
};

payload = new JwtPayload(null, null, claims, null, null);

var serialized = handler.WriteToken(new JwtSecurityToken(tokenHeader, payload));
var deserialized = handler.ReadJwtToken(serialized);

foreach (var claim in deserialized.Claims) {
    Console.WriteLine($"{claim.Type} : {claim.Value}");
}

```

**Expected behavior**
The output should be:
```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier : 42
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name : me
```

**Actual behavior**
The actual output is:
```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier : 42
```

**Possible solution**

N/A

**Additional context / logs / screenshots / links to code**
Downgrading `Microsoft.IdentityModel.Tokens` to v7.3.1 produces the expected behavior.

Both Visual Studio's built-in JWT text visualizer and https://jwt.io/ both show that there are two claims in the token.
![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/10321525/b2017c32-9069-436e-bf4a-7c8648b22777)

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/10321525/c5705fa7-e267-423e-9b93-712c58c462e2)

**Comment by joegoldman2** [comment]
As you are still using `JwtSecurityTokenHandler`, you should also update `System.IdentityModel.Tokens.Jwt` to version 7.4.0. Can you try to add `<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.0" />` in your csproj?

FYI, it is now recommended to migrate to `Microsoft.IdentityModel.JsonWebTokens` and `JsonWebTokenHandler` to play with JWT.

**Comment by reduckted** [comment]
OK, adding `System.IdentityModel.Tokens.Jwt@7.4.0` gives me the expected behavior, but if that package at that version is required, then it should be declared as a dependency of `Microsoft.IdentityModel.Tokens`.

**Comment by keegan-caruso** [comment]
See the note here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x#reminder

The problem is this library expects all the version to be the same as far as IdentityModel dlls.

**Comment by reduckted** [comment]
@keegan-caruso That information should really be somewhere more prominent, like in the readme file.

Even better would be to produce a build-time warning if the versions are out of sync.
