### ISSUE TITLE
[Feature Request] Migrate to Microsoft.IdentityModel.JsonWebTokens for Microsoft.IdentityModel.Protocols.OpenIdConnect

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2509]
Currently `Microsoft.IdentityModel.Protocols.OpenIdConnect` depends on `System.IdentityModel.Tokens.Jwt`. As `Microsoft.IdentityModel.JsonWebTokens` seems to be the recommended package to use today, `Microsoft.IdentityModel.Protocols.OpenIdConnect` should be updated to use it.

**Comment by keegan-caruso** [comment]
roughly a duplicate of #2078

**Comment by joegoldman2** [comment]
> roughly a duplicate of #2078

Right, thank you. I didn't see it. Closing this issue.
