### ISSUE TITLE
Adding crypto extensibility for hash validation

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#251]
In OpenIdConnectProtocolValidator, add extensibility to allow users to specify the algorithms to be used for validation (chash and athash).

**Comment by brentschmaltz** [comment]
1. the algorithms should be as extensive as AsymmetricSignatureProvider.GetHashAlgorithm
2. extensible, virtual might be enough.
