### ISSUE TITLE
[Bug] Version Conflict Between 7.4.0 Versions And Latest AspNetCore.Authentication.OpenIdConnect Version

### ISSUE THREAD

**Issue by mcardoalm** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2510]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel 7.4.0

**Where is the issue?**
 * [X] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [X] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Repro**
If your project references Microsoft.AspNetCode.Authentication.OpenIdConnect, latest version 8.0.2, which in turn references  Microsoft.IdentityModel.Protocols.OpenIdConnect >= 7.1.2, you can't also reference the latest 7.4 version of any of the Microsoft.IdentityModel packages like Microsoft.IdentityModel.JsonWebTokens or Microsoft.IdentityModel.Tokens. Version 7.3.1 works fine, but we had a project referencing Microsoft.IdentityModel.JsonWebTokens and we updated to 7.4 and there must be some sort of conflict with the changes in that release, because our openid auth would always fail with:

IDX10500: Signature validation failed. No security keys were provided to validate the signature.

**Expected behavior**
No error.

**Actual behavior**
Exception throw.

**Possible solution**
Downgrade to 7.3.1 for any Microsoft.IdentityModel packages, or add a new manual package reference to Microsoft.IdentityModel.Protocols.OpenIdConnect version 7.4

**Additional context / logs / screenshots / links to code**

**Comment by 304NotModified** [comment]
Thanks for reporting, we also see this issue. 

Related error messages:
> Bearer was not authenticated. Failure message: IDX10500: Signature validation failed. No security keys were provided to validate the signature

and
 
> Bearer error="invalid_token",error_description="The signature key was not found"

7.3.1 worked well and the downgrade fixes this issue.

**Comment by jmprieur** [comment]
@mcardoalm, @304NotModified 
when you run:
```
dotnet list yourProject.csproj package --include-transitive
```

do you see that all the versions of Microsoft.IdentityModel are the same?
(they need to be)

**Comment by keegan-caruso** [comment]
See the note here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x#reminder

The problem is this library expects all the version to be the same as far as IdentityModel dlls.

**Comment by mcardoalm** [comment]
Hi Keegan,

That was definitely the problem, having different versions, but it can be very hard to figure that out with OpenID being transitively included from AspNetCore and then pulling in the JsonWebTokens library to do some other token creation. Hopefully this will at least help any others that come across this issue.

After I manually added a package reference to the latest OpenIDConnect package thus forcing all the Microsoft.IdentityModel packages onto the same version, everything was fine.

Thanks,
Mike

**Comment by 304NotModified** [comment]
> The problem is this library expects all the version to be the same as far as IdentityModel dlls.

This is really a new dependency hell. This makes upgrading components hard.
