### ISSUE TITLE
Microsoft.IdentityModel.Protocols.OpenIdConnect 7 - mtls_endpoint_aliases

### ISSUE THREAD

**Issue by eirikurharaldsson** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2511]
**Where is the issue?**
Microsoft.IdentityModel.Protocols.OpenIdConnect 7.0.3 and later.
The parsing of metadata silenty failes, when openid metadata includes a json element: mtls_endpoint_aliases
Example of the section:
"mtls_endpoint_aliases": {
"token_endpoint": "https://idpserver/oauth/v2/oauth-token",
"revocation_endpoint": "https://idpserver/oauth/v2/oauth-revoke",
"introspection_endpoint": "https://idpserver/oauth/v2/oauth-introspect",
"pushed_authorization_request_endpoint": "https://idpserver/oauth/v2/oauth-authorize/par",
"userinfo_endpoint": "https://idpserver/oauth/v2/oauth-userinfo"
},

Everything value after this section is ignored by OpenConfigurationRetriver
See below:
![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/134050263/d1c4ba7b-0f20-426c-9a7a-204f3ad4a721)

I originally posted the issue on dotnet because this bug affects the JwtBearer middleware, but was told that it belonged here instead.
https://github.com/dotnet/aspnetcore/issues/52330

The app is in production and I have downgraded from version 8 of JwtBearer middleware as a workaround to an older version one which is using version 6 of OpenIdConnect, which does not include this issue

**Repro**

```var jwtAuthority = "https://[youropenidserver]/oauth/v2/oauth"; // without the "/.well-known/openid-configuration" part

var configManager = new ConfigurationManager<OpenIdConnectConfiguration>(
       $"{jwtAuthority}/.well-known/openid-configuration",
          new OpenIdConnectConfigurationRetriever(),
             new HttpDocumentRetriever(new HttpClient()));

// GetConfigurationAsync has a time interval that must pass before new http request will be issued.
var configuration = await configManager.GetConfigurationAsync(new CancellationToken());

Console.WriteLine(configuration.JwksUri);

var issuers = new[] { configuration.Issuer };
var issuerSigningKeys = configuration.SigningKeys;

foreach (var issuer in issuers)
{
    Console.WriteLine(issuer);
}

foreach (var issuerSigningKey in issuerSigningKeys)
{
    Console.WriteLine(issuerSigningKey);
}
```

**Expected behavior**
By using our Console app example (in Steps to Reproduce)
JwksUri has value and is written to the screen. (Expected)
same goes for Issuers and SigningKeys (Expected)
This used to work in version 6. But broke in version 7+

**Comment by keegan-caruso** [comment]
Hello, can you try the version release this week? 7.4.0

If I'm understanding correctly #2491 should have fixed this

**Comment by eirikurharaldsson** [comment]
Tried with version 7.4.0 of the nuget package. Same issue. You can try it with the sample above.

**Comment by eirikurharaldsson** [comment]
This works with 7.4.0

**Comment by keegan-caruso** [comment]
thanks for confirming!
