### ISSUE TITLE
[Bug] byte[] values in JwtPayload et al. are serialized as arrays instead of base64.

### ISSUE THREAD

**Issue by LeadAssimilator** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2524]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel 7.x.x

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Repro**

```csharp
Console.WriteLine(new JwtPayload { { "Fail", new byte[] { 0x21, 0x62, 0x36, 0x34 } } }.SerializeToJson());
//6.x.x - {"Fail":"IWI2NA=="}
//7.x.x - {"Fail":["33","98","54","52"]}
```

**Expected behavior**
byte[] arrays are serialized as base64.

**Actual behavior**
byte[] arrays are serialized as arrays.

**Possible solution**

**Additional context / logs / screenshots / links to code**
Prior to 7.0.0, byte[] arrays were serialized as base64. This is both the default behavior of System.Text.Json and Json.NET. However since 7.0.0 this changed to serialize them as arrays. If this was intentional, it is an undocumented breaking change affecting backwards compatibility and interoperability with other systems expecting the older format!

**Comment by keegan-caruso** [comment]
@brentschmaltz , can you take a look please?

**Comment by brentschmaltz** [comment]
@LeadAssimilator @keegan-caruso I will have a look.
