### ISSUE TITLE
Fix ConfigurationManager.GetConfigurationAsync to avoid hiding inner exceptions

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#253]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L183-L188

This code path hides the inner exception without logging it, please fix it.
(btw, the `retrieveEx` variable is never used)

/cc @tushargupta51

**Comment by tushargupta51** [comment]
Thanks @PinpointTownes

**Comment by PinpointTownes** [comment]
Thanks for the fix @tushargupta51! :+1:
