### ISSUE TITLE
[Feature Request] remove .net 461

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2544]

**Comment by joegoldman2** [comment]
I guess this issue is fixed by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2642 and can be closed?

**Comment by brentschmaltz** [comment]
Completed: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2642
