### ISSUE TITLE
FileLoadException for System.Runtime.CompilerServices.Unsafe, when using System.memory

### ISSUE THREAD

**Issue by HamzaBA26** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2563]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [X] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

Issue found in Microsoft.IdentityModel.Protocols.OpenIdConnect 7.5.1

**Is this a new or an existing app?**

This is found in development, as we were upgrading Microsoft.IdentityModel.Protocols.OpenIdConnect to latest version, our tests ran into this issue. 

**Repro**

```csharp
  public class Tests
  {
    [SetUp]
    public void Setup()
    {
      var sd = new byte[] { 1, 2 };

      sd.AsSpan(0, 2);
    }

    [Test]
    public void Test1()
    {
      Assert.Pass();
    }
  }
```

**Expected behavior**

Expected being able to use System.Memory library while having Microsoft.IdentityModel.Protocols.OpenIdConnect referenced in a class library project.

**Actual behavior**

Throws an System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1

**Possible solution**

This seems only to be an issue for class libraries. If your project is Executable this does not seems to an issue. Workaround for class libraries is using the 'Microsoft.NET.Test.Sdk' library as this seems to fix the issue.
 
From my limited understanding is, that there is an event-handler in both the library 'Microsoft.NET.Test.Sdk' and the executable project. That looks up the GAC, to resolve the FileLoadException. 

**Additional context / logs / screenshots / links to code**

The issue seems to be introduced for Microsoft.IdentityModel.Protocols.OpenIdConnect at version 6.23.0.

Here is a picture of a test project, which hits this issue.

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/42834022/5a196dc8-dafa-459c-a019-fc3fade2417c)

**Comment by pmaytak** [comment]
@HamzaBA26 Does this error still happen for you?

Thanks for the repro. Can you try directly referencing System.Memory 4.5.5? It's the same [version ](https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens/7.5.1) that IdentityModel packages reference.

**Comment by sruke** [comment]
@HamzaBA26, thank you for providing the steps to reproduce the issue. I was able to replicate it in a class library targeting .NET Framework 4.8 with IdentityModel v7.5.1. I also needed to add an explicit reference to System.Memory v4.5.5 to resolve a compile-time error related to byte[] not containing a definition for AsSpan.

In the class library:

- System.Memory references System.Runtime.CompilerServices.Unsafe v4.5.3 (assembly version 4.0.4.1).
- Microsoft.IdentityModel.Protocols.OpenIDConnect v7.5.1 references System.Runtime.CompilerServices.Unsafe v6.0.0 (assembly version 6.0.0).

This resulted is a FileNotFoundException for System.Runtime.CompilerServices.Unsafe (version 4.0.4.1) similar to what you have observed.

After searching, I found similar reports on StackOverflow (See [post1](https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe#:~:text=I%20assume%20that,of%20these%20versions.), [post2](https://github.com/jstedfast/MailKit/issues/1462)). The best long-term solution would be to migrate to .NET Core. 

Can you try adding a binding redirect, favoring the higher version of System.Runtime.CompilerServices.Unsafe (v6.0.0) referenced by Microsoft.IdentityModel.Protocols.OpenIDConnect and let us know if it resolves the issue for you?

Also, could you clarify if your project is a Web App or Web API? In this case, adding a binding redirect should be straightforward. If it's a class library, the approach may be different.

To check the assembly version of a package, you can visit NuGet.org, search for the package, and use "Open in NuGet Package Explorer" to view the version under the strong name for the dll.

I found the explanation in [Nick Craver - Binding Redirects](https://nickcraver.com/blog/2020/02/11/binding-redirects/) post very helpful.

**Comment by HamzaBA26** [comment]
I have migrated to core, and that seems to have solved the issue.
