### ISSUE TITLE
[Bug] A possible vulnerability in the package

### ISSUE THREAD

**Issue by gdoron** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2566]
Hi, 
I reported a thing I believe to be a vulnerability in the researcher portal 5 days ago, and still haven't got a response there. 
I might have filled the form incorrectly (feels like Stan by Eminem 😂), so just letting you know of 
_VULN-124206_. 

Best, 
Doron

**Comment by jennyf19** [comment]
Thanks @gdoron we will follow up. Appreciate you bringing this to our attention
