### ISSUE TITLE
ValidateTokenResponse requires Token

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#258]
ValidateTokenResponse requires both IdToken and Token, but the spec says it should be IdToken and AccessToken. I don't see any scenarios that say they return Token.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L264-L268
http://openid.net/specs/openid-connect-core-1_0.html#TokenResponse
@tushargupta51 @brentschmaltz

**Comment by tushargupta51** [comment]
Token corresponds to accesstoken.

**Comment by Tratcher** [comment]
Then why does OIDCMessage define both Token and AccessToken? And why does ValidateTokenResponse check for Token rather than AccessToken?

**Comment by tushargupta51** [comment]
@Tratcher It is confusing to have both properties on OpenIdConnectMessage. AccessToken is the right property to use. I have pushed out a fix to oidcProtocolValidation branch.

Do you have any opinion on #256? I am thinking of making that change too in this fix PR.
