### ISSUE TITLE
[Feature Request] Consider publicly exposing Base64UrlEncoder.Decode(ReadOnlySpan<char>, Span<byte>)

### ISSUE THREAD

**Issue by paulomorgado** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2608]
This can be extremely useful for decoding large payloads.

[`Base64UrlEncoder.Encode(ReadOnlySpan<byte>, Span<char>)`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/rel/7.5.1/src/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.cs#L114) is public but [`Base64UrlEncoder.Decode(ReadOnlySpan<char>, Span<byte>)`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/rel/7.5.1/src/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.cs#L200) is not.

`Making Base64UrlEncoder.Decode(ReadOnlySpan<char>, Span<byte>)` public would make the library more complete.

**Comment by keegan-caruso** [comment]
Hello,

Base64URL support is targeting net9 for support in the runtime:

https://github.com/dotnet/runtime/issues/1658
 
We would rather not add this method to the public API when it will be handled at the runtime level.

**Comment by keegan-caruso** [comment]
Please open again if needed.
