### ISSUE TITLE
Add timeout values to all regex expressions

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#261]
https://github.com/aspnet/dnx/issues/1752

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs#L63

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L386

/cc @blowdart @tushargupta51

**Comment by brentschmaltz** [comment]
@PinpointTownes Thanks. 
For beta8 the plan is to check: if (regex.MatchTimeout == Timeout.InfiniteTimeSpan) and if so, then create a new regex setting the Matchtimeout to 2 secs.  
In RC we can make the value configurable.
I pushed a proposed fix to the 'Regex' branch.  Have a look if you want.

**Comment by PinpointTownes** [comment]
Thanks! That's an interesting fix, (even if I'm not sure it's really useful to check the default timeout) :+1:

**Comment by tushargupta51** [comment]
1169194e08ba98e0fbeba4b40f5cdabe2daab4ee

**Comment by tushargupta51** [comment]
@brentschmaltz Do you want to close this or leave it open as a tracking issue for RC?

**Comment by brentschmaltz** [comment]
@PinpointTownes I am trying to be careful here by respecting any user set defaults. I can't query the AppDomain in Core as I don't think it exists.

@tushargupta51 we need to make this configurable so users don't have to revert to the AppDomain. This is similar to XmlReader quotas when processing SAML tokens.

**Comment by tushargupta51** [comment]
Closing this one as beta8 fix, opened #262 for rc investigation.

**Comment by PinpointTownes** [comment]
Thanks :+1:
