### ISSUE TITLE
[Bug] Evaluate usage of DateTime.TryParse for performance

### ISSUE THREAD

**Issue by eerhardt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2615]
**Which version of Microsoft.IdentityModel are you using?**
latest version.

**Where is the issue?**
 * [x] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Repro**

Looking at a CPU profile of validating JWT tokens, between 5-8% of the time is spent in 2 calls to `DateTime.TryParse`:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/753959a8af318497ecf60c466a23f7c972f310a0/src/Microsoft.IdentityModel.Tokens/Json/JsonSerializerPrimitives.cs#L713

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/753959a8af318497ecf60c466a23f7c972f310a0/src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs#L602-L604

For every string claim in the JWT, we are calling `DateTime.TryParse` on each value, whether it is expected to be a DateTime or not. This is expensive. We should consider if can eliminate these calls, or only call them if necessary.

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/8291187/2a2ce220-9ba2-4033-991a-9c37515acc38)

![image](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/assets/8291187/1ddb7419-a216-4a6c-82e9-bb9e815ad97d)

**Comment by brentschmaltz** [comment]
@eerhardt  Excellent find, this was added for backcompat.
We should state what claims we will consider as a possible datetime, ignore the rest.

I think we need to wrap this in a AppContext switch as we could break users.
We are investigating an API that will give users the ability to step in front of property claim.
When that API is ready, users will be able to handle specific claims.
