### ISSUE TITLE
Add NotNullWhen attributes to CollectionUtilities?

### ISSUE THREAD

**Issue by mariesophie** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2620]
## Summary

Help the linter determine, whether the collection is null after calling this function.

## Motivation and goals

I came across the extension function `IsNullOrEmpty` for `IEnumerable<T>` in `CollectionUtilities` today, which is a cleaner and nicer way of checking for null and not accidentally iterating over the collection to get a count.
Now I know, that it is not null, but my IDE still issues warnings about possible null references.

## Question
Is this something I can create a Pull Request for or what would be the correct way of addressing this issue?

**Comment by joegoldman2** [comment]
Already covered by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2394.

**Comment by keegan-caruso** [comment]
Hello, feedback from the community was that CollectionUtilities should not have been public. 

We have moved it to internal in 8x.
