### ISSUE TITLE
[Feature Request] use `<inheritdoc/>` for overridden members

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2664]
Overridden members (methods or properties) from a base class should not repeat all the XML documentation, but rather use `<inheritdoc/>` in order to avoid repetition and simplify reading.

For example:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/55cc10ea53503b129afd55734ad9e9dd8203b339/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L474-L483

**Comment by joegoldman2** [comment]
If you are ok with that, I would be happy to propose few PRs to fixed it.

**Comment by keegan-caruso** [comment]
@joegoldman2 ReadToken in JsonWebTokenHandler make the comment more specific such that it is about JWTs rather than security tokens as in TokenHandler.

What would you suggest we change it to?

**Comment by ghost** [comment]
For each I can check the difference and keep the inherited documentation if it is more specific. Would you accept a PR per project for example?

**Comment by keegan-caruso** [comment]
Per project sounds great! We will accept this.

**Comment by keegan-caruso** [comment]
@joegoldman2 Are there any files that need updated in your opinion or do you consider this done?

**Comment by ghost** [comment]
Considering all PRs that have been merged about XML docs, I think we can close this issue.
