### ISSUE TITLE
Add assembly versions to logs.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#270]
We need a way to log the version of the assemblies that are running. Some runtimes do that with each message. Since our logger is separate from the assemblies we need to capture the dependant assemblies versions. We could do it with the first message or in each message.

**Comment by brentschmaltz** [comment]
I have completed some work addressing #205 so taking ownership.

**Comment by polita** [comment]
Can we log the assembly version in JWTSecurityTokenHandler and ConfigurationManager with a static ctor.
