### ISSUE TITLE
Windows 10 UWP Support?

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#271]
Are the new packages (Jwt handler, OIDC disco client) supposed to work in Win 10 UWP apps? Is this a design goal?

**Comment by brentschmaltz** [comment]
It wasn't a design goal, checking to see how far off we are.

**Comment by leastprivilege** [comment]
Writing OIDC clients for native apps would required JWT validation - disco doc parsing would be nice to have.

**Comment by brentschmaltz** [comment]
@leastprivilege We are looking into Disco Doc's.  
UWP  is possible, but not for RC1.

**Comment by leastprivilege** [comment]
RTM?

**Comment by brentschmaltz** [comment]
@leastprivilege I am thinking RC2 or a nightly post RC1.  I will try and remember to ping you when it gets committed.

**Comment by brentschmaltz** [comment]
@leastprivilege why does this interest you?

**Comment by leastprivilege** [comment]
Because I needed to write a OIDC-based authN library for UWP (using WAB). Problem is that I cannot validate the id_token on the client side.

**Comment by PinpointTownes** [comment]
Thanks to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/511823615bcb9ee6f5e1f9a2cdfcfd0dae701b2e, isn't UWP now natively supported, since `dotnet5.4` includes `.NET 4.6`, `dnxcore50` and UWP?

**Comment by leastprivilege** [comment]
Is the current pre-release build working already for UWP?

**Comment by leastprivilege** [comment]
@brentschmaltz what's the roadmap for this?

**Comment by polita** [comment]
@ChenYan98 Please build a sample to try this out.

**Comment by ChenYan98** [comment]
UAP is not supported for RTM.

**Comment by polita** [comment]
@ChenYan98, Please send mail to @jbarton to figure out if the errors we see are expected.

**Comment by polita** [comment]
Need to readme our support. We can do this during escrow.

**Comment by polita** [comment]
@leastprivilege Some parts of the cryptography libraries (such as CSP) won't work on UWP. In theory, other parts of the stack should work. However, we haven't verified that they actually do work on a UWP, and I foresee that we won't be able to do that until after RTM. If you'd like to take a swing at trying it out and letting us know what you find, we'd be appreciative.

I'm moving this to the backlog for now. Hopefully we can get deeper into this after we're done for RTM.
