### ISSUE TITLE
Remove support for SHA1

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#275]
SHA1 is know to be at the end of life. If users need it they can use extensibility.

**Comment by ryanbuening** [comment]
@brentschmaltz my IdP does not support SHA2, it only supports SHA1 currently.

I'm trying to get WS-Federation working with my ASP.NET Core project. Is it possible to use SHA1 with the new WS-Federation middleware? (https://github.com/aspnet/Security/issues/1473)
