### ISSUE TITLE
Change Inbound and Outbound algorithm map from static to instance based

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#278]
Because of algorithm mapping being static, tests fail since some of the tests update the maps with custom values, other tests see these custom mapped values and fail.

E.g. in CreateAndValidateTokenTests.ExtensibilityTests.cs, inbound alg map is updated
            originalAlgorithmValue = ReplaceAlgorithm(newAlgorithmValue, SecurityAlgorithms.RsaSha256Signature, JwtSecurityTokenHandler.InboundAlgorithmMap);
            RunAlgorithmMappingTest(jwt.RawData, IdentityUtilities.DefaultAsymmetricTokenValidationParameters, handler, ExpectedException.NoExceptionExpected);
            ReplaceAlgorithm(newAlgorithmValue, originalAlgorithmValue, JwtSecurityTokenHandler.InboundAlgorithmMap);

even if the test is putting the original value back, other tests (Multiple X5c) still see the "newalgorithmvalue" and fails.

This is prevented currently using
-[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly)] attribute in assembly info.cs. but we should fix this behavior.

**Comment by brentschmaltz** [comment]
We are just going to remove the mapping.

**Comment by brentschmaltz** [comment]
RC1 fixes. #300
