### ISSUE TITLE
[Bug] JWT Verification Issue

### ISSUE THREAD

**Issue by Jean6123** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2785]
Microsoft.IdentityModel.Tokens 8.0.1

 * [ ] M.IM.Tokens

Log below

Handling request: GET /OpticalService/GetFames
Authentication failed: IDX14100: JWT is not well formed, there are no dots (.).
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJuYmYiOjE3MjQwNDAzNzEsImV4cCI6MTcyNDEyNjc3MSwiaWF0IjoxNzI0MDQwMzcxLCJpc3MiOiJwdWJsaXNoZXIiLCJhdWQiOiJsaXN0ZW5lciJ9.psHX3LyqmUsYFafRz2UD1T2cL3ru8o_h28jEUtfPxFk
Finished handling request.

```csharp
server side key generation
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = "publisher", 
        ValidAudience = "listener", 
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("12345678901234567890123456789012")) // 密钥
    };
    options.Events = new JwtBearerEvents
    {
        //OnMessageReceived = context =>
        //{
        //    var authHeader = context.Request.Headers["Authorization"].ToString();
        //    Console.WriteLine($"Received token: {authHeader}");

        //    if (!string.IsNullOrEmpty(authHeader) && authHeader.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
        //    {
        //        string token = authHeader.Substring("Bearer ".Length).Trim();
        //        Console.WriteLine($"Token: {token}");
        //        context.Token = token;
        //    }

        //    return Task.CompletedTask;
        //},

        
        OnAuthenticationFailed = context =>
        {
            Console.WriteLine($"Authentication failed: {context.Exception.Message}");
            Console.WriteLine($"Token: {context.Request.Headers["Authorization"]}");
            return Task.CompletedTask;
        }
    };
});

client side key generation
var tokenHandler = new JwtSecurityTokenHandler();
var key = Encoding.UTF8.GetBytes("12345678901234567890123456789012");
var tokenDescriptor = new SecurityTokenDescriptor
{
    Subject = new ClaimsIdentity(new Claim[]
    {
        new Claim(ClaimTypes.Name, login.Username)
    }),
    Expires = DateTime.UtcNow.AddHours(24),
    Issuer = "publisher",
    Audience = "listener",
    SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
};
var token = tokenHandler.CreateToken(tokenDescriptor);
var tokenString = tokenHandler.WriteToken(token);

return Ok(new { Token = tokenString });

**Comment by keegan-caruso** [comment]
Hello @Jean6123 

The log message makes it look like the token includes the Bearer prefix, can you let us know if this is true here?

**Comment by Jean6123** [comment]
Yes it includes, But that's not the root cause because I have tried to removed the Bearer prefix but it does't work either, I have founded that if I switch the sequence of this two call app.UseAuthentication();
app.UseAuthorization();
Everything goes well.
And by the way, how to make a local debug environment so that I can discover the root cause by myself?

**Comment by keegan-caruso** [comment]
Yes, Authentication needs to be before Authorization as authorization relies on the results from authentication.

**Comment by keegan-caruso** [comment]
See here for some docs on logging: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/How-to-log-from-IdentityModelEventSource.Logger
