### ISSUE TITLE
Update to 9.0.100-rc1

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2789]
Breaking changes due to https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0057

Several places need to be fixed, especially in the tests. right now it's set to warn in the common.props
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/build/common.props#L48

and here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/build/commonTest.props#L32

Todo:
remove the two <warn> in the props and address all the issues.
Will probably need
`#if NET9_0_OR_GREATER`
in all the places

**Comment by kllysng** [comment]
Moving to 9.0.100-rc.1
