### ISSUE TITLE
ConfigurationManger.GetConfigurationAsync should log details of configuration

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#279]
public async Task<T> GetConfigurationAsync(CancellationToken cancel)
Only logs on error.
We should log:
Where metadata was retrieved,
Details of metadata.  json retruned is probably enough.

**Comment by tushargupta51** [comment]
@brentschmaltz  We log that information in OpenIdConnectConfigurationRetriever.GetAsync().

**Comment by brentschmaltz** [comment]
@tushargupta51 we should log where we tired to get the data, 'address' typeof(retriever)

**Comment by tushargupta51** [comment]
@brentschmaltz we log the 'address' in the retriever GetDocumentAsync method. If someone hooks in their own retriever, then they need to add a logging statement too. We are not sure if the address is a valid address until we get to the document retriever, thats why logging it at the retriever level makes sense.

**Comment by tushargupta51** [comment]
If we fail to retrieve metadata, address is added to the exception message.

**Comment by brentschmaltz** [comment]
@tushargupta51 here is how I am thinking. Suppose a user plugs their own retriever and they don't log and there is an error. Our logs will show nothing. However, if we log at the ConfigurationManager level the typeof(retriever), right away we will have something to help us. 
I don't think there is any harm in logging at the manager level.
As a note, I don't see our FileDocumentRetriever.GetDocumentAsync logging.

**Comment by tushargupta51** [comment]
@brentschmaltz In that scenario, our logs will show the: Unable to retrieve from <metadata address>. Inner Exceptio: <ex>. Inner exception will have more details about the exception thrown at a deeper level (e.g. in document retriever). We do have logging at the manager level too.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L185

We do have logging in case of error in FileDocRetriever: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols/Configuration/FileDocumentRetriever.cs#L51

We have logging at 3 levels:
1. COnfiguration Manager: if something fails, we log the exception with metadata address and inner exception.
2. OIDCConfigurationRetriever: we log the metadata received from metadata endpoint, jwksuri, and jwkskey.
3. Document Retriever: In case address is not correct (http e.g.), or something goes wrong when retrieving the data, we log the exception with the address.

**Comment by brentschmaltz** [comment]
@tushargupta51 FileDocumentRetriever logs in the case of error, but not in the positive case. I am not focusing on the negative case, but the positive case. So what you are saying is that we've got it covered. I am good with that and will close the issue.
