### ISSUE TITLE
[Feature Request] Use fixedtimeequals on Net Core targets

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2825]
This code:  https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/411d0841bf30db8bf1a8448e255cacf7b77534c4/src/Microsoft.IdentityModel.Tokens/Utility.cs#L155-L158

Should be replaced with [cryptographicoperations.fixedtimeequals](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptographicoperations.fixedtimeequals?view=net-8.0)

On Net Core targets

**Comment by pmaytak** [comment]
The implementation looks very similar to what we already have. The do also add `MethodImplOptions.NoOptimization` attribute.

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CryptographicOperations.cs#L37

**Comment by westin-m** [comment]
The proposed changes result in a significant performance loss. See the linked PR for benchmarks

**Comment by pmaytak** [comment]
We should take this and should add NoOptimization attribute.
