### ISSUE TITLE
[Bug] X509CertificateLoader does not have a .LoadCertificate() with the same args as some X509Certificate2 constructors

### ISSUE THREAD

**Issue by kllysng** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2833]
See #2821 

[Here ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f0d09d408948c6920f171299bee9167d0850a51b/test/Microsoft.IdentityModel.TestUtils/KeyingMaterial.cs#L33C8-L36C9)are examples of the args we need.

If the correct .LoadCertificate() args are added, we should use them.

**Comment by jennyf19** [comment]
This is done correct @kellyyangsong ? I'll mark it as such, but please fix if that's not right.
