### ISSUE TITLE
Add ECDsaSecurityKey ctor that takes CngKey

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#286]
Currently, there is no relatively easy way to determine if a CngKey is a private or a public key. Add this ctor when there is a good way to determine that.

**Comment by tushargupta51** [comment]
I pinged WinCrypt guys internally, and it seems that the only way to determine whether a CngKey has a private key or not is to do a fake sign with it. We need to evaluate if we need this constructor or not. Doing a fake sign might be expensive especially in case of hardware keys.

**Comment by tushargupta51** [comment]
@brentschmaltz should we close this one? I dont think having a ctor that takes CngKey has enough value that we do fake signing to determine whether the key is private or not. Users who have a CngKey object and want to initialize ECDsaSecurityKey object, they can pass the blob (by exporting from the CngKey) and blobFormat(public or private).

**Comment by brentschmaltz** [comment]
I don't think a 'fake' signature test is the way to go. Consider a hardware key OR a KeyVault (where a network Async is needed).

**Comment by PinpointTownes** [comment]
Tying `ECDsaSecurityKey` to CNG is NOT a good idea, as it prevents cross-platform scenarios. Its constructor should only take an `ECDsa` parameter instead of trying to create a CNG key.

I opened https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/325 to track that.
