### ISSUE TITLE
[Bug] Set internal _syncAfter using only AutomaticRefreshInterval - ConfigurationManager updating keys too frequently

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2866]
The internal _syncAfter field controls if metadata is refreshed (http call).
The value was set to the minimum of AutomaticRefreshInterval and RefreshInterval.

RefreshInterval controls the interval that must pass for RequestRefresh() to make an http call.
RefreshInterval is usually a much smaller timespan, so in effect many more calls would be made to obtain metadata.

This fix only uses the AutomaticRefreshInterval to set _syncAfter.
This has the side effect of extending the time for the next AutomaticRequest, however, that makes sense.

**Comment by tustyan-vcc** [comment]
There is a relevant comment in another issue.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2774#issuecomment-2363619630

Also it seems there is another issue with using Interlocked.CompareExchange method mentioned there, that also causes a lot more calls towards metadata endpoint when several threads try to validate the token:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2774#issuecomment-2363677688

**Comment by jennyf19** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/8.1.1
