### ISSUE TITLE
Remove Pragma Disable Warning For New ValidateTokenAsync Method on Saml2TokenHandler

### ISSUE THREAD

**Issue by FuPingFranco** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2880]
Due to the TDD approach we are taking on constructing the new ValidateTokenAsync method on Saml2TokenHandler that implement our new token validation model, we introduced `pragma warnings disable` around methods that passed CancellationToken. We should be able to remove them once we get into async validators such as the Issuer validator.

**Comment by iNinja** [comment]
This will be solved once #2929 is merged.
