### ISSUE TITLE
[Bug] Breaking change between 8.0.2 and 8.1.0

### ISSUE THREAD

**Issue by ssmelov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2926]
**Which version of Microsoft.IdentityModel are you using?**
8.0.2 and 8.1.0

**Where is the issue?**
 * [x] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Description**
There is a breaking change between version 8.0.2 and version 8.1.0 due to a modification in [TokenValidationResult constructor's parameter](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/5ba278b1028e5848c51918b38479c12678052cd1#diff-2f8e0e4e168e97a398bef564b3c81830acd59d6116c0120966666ffcbd7a0cabL65).
During token validation, the [JsonWebTokenHandler.ValidateTokenPayloadAsync method creates a TokenValidationResult instance](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d88aa8d42351d974f28ffd374284bbae9451a3e5/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.ValidateToken.cs#L584C20-L584C109). If Microsoft.IdentityModel.JsonWebTokens version 8.0.2 is used alongside Microsoft.IdentityModel.Tokens version 8.1.0, it throws a MissingMethodException.

**Comment by jennyf19** [comment]
@ssmelov We fixed this in 8.1.2: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/8.1.2

Can you try moving to the latest (8.1.2) instead?

**Comment by jennyf19** [comment]
closing as fixed in 8.1.2

**Comment by leastprivilege** [comment]
That's a classic Wilson.
