### ISSUE TITLE
[Feature Request] Make "kid" Configuration for JsonWebToken Optional

### ISSUE THREAD

**Issue by sruke** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2960]
What: Introduce a configuration option for adding the "kid" to the JsonWebToken.

Why: Currently, the "kid" is automatically included in the JsonWebToken whenever it is present in the signing credentials. However, the JWT specification does not require the "kid" to be included, so there are scenarios where it may not be needed.

How: Implement a flag in the JsonWebTokenHandler that allows users to choose whether or not to include the "kid" in the generated JWT.

**Comment by pmaytak** [comment]
@sruke @msbw2 Should this be closed or is there more work to do?

**Comment by msbw2** [comment]
> @sruke @msbw2 Should this be closed or is there more work to do?

It should have auto-resolved when the PR merged, right?

**Comment by pmaytak** [comment]
Only if it's associated with specific words: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue
