### ISSUE TITLE
Update to use .net generations

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#298]
.Net generation defines the API that is available on all platforms that a given generation supports. For more information about what .net generation is, please refer to: https://github.com/davidfowl/aspnetvnextwebapiapp/blob/master/Generations.md.

We need to update project.json to use "dotnet5.4" as target instead of platform specific targets like dnxcore50, dnx451 etc.

**Comment by brentschmaltz** [comment]
@tushargupta51 is this needed for RC1?

**Comment by tushargupta51** [comment]
Yes
