### ISSUE TITLE
Kid header parameter

### ISSUE THREAD

**Issue by zygimantas** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#299]
Decoded JWT token header looks like this:

``` javascript
{
    "alg": "RS256", 
    "typ": "JWT", 
    "kid": null
}
```

Is there any reason to include this parameter at all if the value is not provided?

>The "kid" (key ID) Header Parameter is a hint indicating which key
>was used to secure the JWS.  This parameter allows originators to
>explicitly signal a change of key to recipients.  The structure of
>the "kid" value is unspecified.  Its value MUST be a case-sensitive
>string.  Use of this Header Parameter is OPTIONAL.
>https://tools.ietf.org/html/rfc7515#section-4.1.4

>The "kid" (key ID) header parameter is a hint indicating which specific key owned by the signer
>should be used to validate the signature. This allows signers to explicitly signal a change of key to
>recipients. Omitting this parameter is equivalent to setting it to an empty string. The interpretation
>of the contents of the "kid" parameter is unspecified. This header parameter is OPTIONAL.
>http://self-issued.info/docs/draft-jones-json-web-token-01.html

**Comment by brentschmaltz** [comment]
I don't see a reason to include kid as null.

**Comment by tushargupta51** [comment]
I think this issue is addressed with the latest changes: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtHeader.cs#L65

**Comment by tushargupta51** [comment]
@zygimantas @brentschmaltz closing this as fixed.
