### ISSUE TITLE
Change #defines for new targets

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#304]
from: https://github.com/aspnet/Announcements/issues/98

#if DNX451
        // whatever 
#endif 
...
#if DNXCORE50
        // whatever 
#endif 

Change that to:

#if NET451
        // whatever 
#endif 
...
#if DOTNET5_4
        // whatever 
#endif

**Comment by brentschmaltz** [comment]
Moved to RC2 to revisit as Tushar pointed out that since these are tests, it is OK for now.

**Comment by tushargupta51** [comment]
dnxcore50 changes to netstandardapp1.5
