### ISSUE TITLE
Add TryValidateToken for a exceptionless usage pattern

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#312]
https://github.com/aspnet/Security/issues/411#issuecomment-148547863

An invalid token is not always an exceptional circumstance. Consider supporting TryValidateToken similar to int.TryParse.

**Comment by brentschmaltz** [comment]
@Tratcher how are you envisioning this scenario being used?

**Comment by Tratcher** [comment]
Such as having multiple bearer token middleware for different providers, each will try to validate the token and then pass onto the next middleware if they didn't understand it.

**Comment by brentschmaltz** [comment]
@Tratcher If the intent is to provide support for multiple-providers, then we need logic for the MW to ignore the token completely. It would be inefficient to have n MW's attempt crypto operations. int.TryParse only determines if bytes are well-formed. TokenValidation is slightly more involved.

**Comment by Tratcher** [comment]
What information does the middleware have on which to make that decision except to attempt to read the token? There aren't any other headers or path information to look at.

**Comment by PinpointTownes** [comment]
> It would be inefficient to have n MW's attempt crypto operations. 

I guess this new `TryValidateToken` thingy could call `CanReadToken` very early to avoid processing incompatible tokens.

**Comment by brentschmaltz** [comment]
Not sure why we  wouldn't want failure on an expired token or invalid tokens. these are errors.
What I am saying is that a model where the handler looks at the token and for deterministic reasons detects it shouldn't handle that token, logs the fact and returns without error is goodness. It is important to fail when an error condition is clearly apparent.

We need to have a clean definition of the contract for TryValidateToken, which we need to move forward. 

Today, users can swallow errors by hooking the 'error' notification.

**Comment by Tratcher** [comment]
Fair. So what are the stages of validation?
1. Is this a JWT?
2. Can I decrypt it?
3. Is it tied to the correct authority?
4. Are there any protocol validation issues? (e.g. missing claims, expired, etc.)

**Comment by brentschmaltz** [comment]
We came to the conclusion we do need something like this. I am thinking we need: ShouldValidate or CanValidate that for performance reasons takes some out param to cache any work performed parsing.

**Comment by brentschmaltz** [comment]
@Tratcher when an message arrives and the handler determines it is a well formed OIDC message. It now needs to determine if it should handle the message, including token validation. This determination of course takes cycles and the results could be used by the next handler. An efficient design would capture partial results and use a policy to determine if the message / token should be processed. The 'token' part of the policy could contain such things as 'issuers' or 'audiences'. A ValidationContext could be used to maintain partial results between handlers.

Even without any changes today, the exception: SecurityTokenSignatureKeyNotFoundException would be a hint that the OIDCHandler could use to log the exception and 'skip' to the next handler. This exception indicates that the metadata does not pertain to this token.

**Comment by Tratcher** [comment]
That exception is already used as a hint for RefreshOnIssuerKeyNotFound.

**Comment by brentschmaltz** [comment]
@Tratcher yes that is the logic based off of the SecurityTokenSignatureKeyNotFoundException. Question is what should the handler do? Do we want to capture the deserialization of the token? Teams I have worked with that process a large number of logins / sec are concerned about such things.

**Comment by polita** [comment]
We will document all exceptions that can be thrown in #375. This should enable you to catch the exceptions you care about.
