### ISSUE TITLE
User control over nbf and expires'

### ISSUE THREAD

**Issue by jgemedina** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#314]
I want to be able to define a token descriptor with no expiration and no notBefore claims, however, when I set the Lifetime Property in the TokenDescriptor to null expecting to have this effect, I noticed that such claims were still being added.

In `JwtSecurityTokenHandler.CreateToken(TokenDescriptor)` the values for notBefore and expires are initialized based on the value of the property Lifetime, they are assigned null if such property happens to also be null.

However, later on in the override `JwtSecurityTokenHandler.CreateToken(string, string, ClaimsIdentity, DateTime?, DateTime?, SigningCredentials, SignatureProvider)` this values are defaulted to `DateTime.UtcNow` for `notBefore` and that plus a configured offset for `expires`.

Wondering if we should leave up to the User controlling the lifetime of the token completely.

**Comment by brentschmaltz** [comment]
@jgemedina excellent observation. Our 5.0 version has introduced OM to control this. Can you use that release?

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L946

**Comment by polita** [comment]
We need to figure out if this is still a bug in 5.x as well.

**Comment by Tydude4Christ** [comment]
I'm experiencing something similar in 5.x, where if the `Expires` property of `SecurityTokenDescriptor` has a value then `iat` and `nbf` get assigned to `DateTime.UtcNow` in `JwtSecurityTokenHandler.CreateToken(TokenDescriptor)` even though the corresponding properties in the descriptor are `null`.

**Comment by brentschmaltz** [comment]
fixed by @ChenYan98 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/462
