### ISSUE TITLE
Add missing ECDSA xmldsig identifiers to SecurityAlgorithms

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#315]
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512

https://tools.ietf.org/html/rfc6931

@brentschmaltz I can submit a PR for that :clap:

**Comment by PinpointTownes** [comment]
RSASSA-PSS identifiers should also be added:

> http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha384-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha512-rsa-MGF1

**Comment by brentschmaltz** [comment]
@PinpointTownes so even though we don't support those right now, I see no downside in introducing them for users who are taking advantage of custom SigningProviders.
