### ISSUE TITLE
Code/access token hashing should use ASCII encoding

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#318]
http://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken

`OpenIdConnectProtocolValidator.ValidateHash` uses UTF8 while the specs target ASCII. It's probably not a big deal, since access tokens and authorization codes are often only composed of ASCII chars, but something we may want to fix for RTM to avoid potential mismatches.

/cc @brentschmaltz

**Comment by brentschmaltz** [comment]
thanks
