### ISSUE TITLE
Update RsaSecurityKey and ECDsaSecurityKey to support cross-platform scenarios

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#325]
In IdentityModel 5, `RsaSecurityKey` and `ECDsaSecurityKey` are directly tied to `RSAParameters` and `CngKey`, which prevents cross-platform and advanced scenarios like using a HSM.

These primitives should only accept `RSA` and `ECDsa` instances in their constructor parameters and determining the right implementation should be made by the classes using `RsaSecurityKey` and `ECDsaSecurityKey`, just like in IdentityModel 4.

**Comment by tushargupta51** [comment]
@PinpointTownes How `RSAParameters` prevent cross plat scenarios? `RSAParameters` is available on unix/coreclr: https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Security.Cryptography.OpenSsl/src/System/Security/Cryptography/RSAOpenSsl.cs#L44

**Comment by PinpointTownes** [comment]
Actually, RsaSecurityKey's issue is not about cross-platform but about usability: not being able to flow a `RSA` instance prevents tons of advanced scenarios like using a `RSACryptoServiceProvider` tied to a HSM.

**Comment by tushargupta51** [comment]
@PinpointTownes @brentschmaltz this came up in the review of PR #334 and I want to start the discussion here to agree upon a solution before I make any further changes to the PR.

What is the best place to put these constructors that take `RSA` and `ECDSA` instances, is it the `RsaSecurityKey`/`ECDsaSecurityKey` classes or `AsymmetricSignatureProvider` or both. Comparing to System.IdentityModel 4.5, `RsaSecurityKey` has the constructor that takes the `Rsa` instance as well as the `AsymmetricSignatureFormatter`/Deformatter (which is similar to SignatureProviders in Wilson) took the `Rsa` instance in the constructor.

@brentschmaltz pointed out that it does not look right that we create a SecurityKey from an `Rsa` instance which is essentially a signature provider and then use that key to create the `SignatureProvider`. Why not have a constructor on `SignatureProvider` that takes `AsymmetricAlgorithm` and try to cast it as `ECDsa` or `RSA`, if it cannot then we throw.

**Comment by PinpointTownes** [comment]
> What is the best place to put these constructors that take RSA and ECDSA instances, is it the RsaSecurityKey/ECDsaSecurityKey classes or AsymmetricSignatureProvider or both.

Ideally, only the security key classes. Trying to find the best algorithm instance should be made by `AsymmetricSignatureProvider` internally. Only requiring an `AsymmetricSecurityKey` (or better, an `AsymmetricAlgorithm`) in the constructor is fine.

> Comparing to System.IdentityModel 4.5, RsaSecurityKey has the constructor that takes the Rsa instance as well as the AsymmetricSignatureFormatter/Deformatter (which is similar to SignatureProviders in Wilson) took the Rsa instance in the constructor.

Are you sure? IIRC, they were abstract classes and had no default constructor. Or maybe you mean the specialized implementations (like RSA PKCS#1)?

> @brentschmaltz pointed out that it does not look right that we create a SecurityKey from an Rsa instance which is essentially a signature provider and then use that key to create the SignatureProvider. 

IMHO, `RsaSecurityKey` should only take a `Rsa` algorithm object and expose it. Specific usage (like signing or encrypting) should be decided elsewhere: reducing `SecurityKey` to a signature provider doesn't seem right.

> Why not have a constructor on SignatureProvider that takes AsymmetricAlgorithm and try to cast it as ECDsa or RSA, if it cannot then we throw.

If by `SignatureProvider` you mean the asymmetric one, yep, I agree (requiring an `AsymmetricSecurityKey` instance is not really necessary, as we can retrieve the needed attributes like the key size from the algorithm instance itself, even on CoreCLR).

**Comment by tushargupta51** [comment]
> Are you sure? IIRC, they were abstract classes and had no default constructor. Or maybe you mean the specialized implementations (like RSA PKCS#1)?
Yes, I mean the specialized implementations. I looked at the RSAPKCS1.

So, your recommendation is to have only one constructor on `RsaSecurityKey` that takes an `RSA` instance. And have 2 constructors on `AsymmetricSignatureProvider`
1. that takes `AsymmetricAlgorithm` object and then try to cast it to a more specific implementation like `ECDsaCng` or `RSaCng` etc.
2. that takes `AsymmetricKey` object (as it does currently) and then uses the key's `AsymmetricAlgorithm` property (e.g. `RSA`) to determine the right implementation (`RsaCng` or `RsaOpenSSL`). It seems this one is less important to you.

**Comment by PinpointTownes** [comment]
Yep, except for the two constructors part (unless there's a specific reason to take a key and not just an algorithm, but I can't find one). Only having a constructor taking an `AsymmetricAlgorithm` should be enough IMO.

**Comment by tushargupta51** [comment]
Closing this issue since we added constructors on SecurityKey's classes that takes in `RSA` and `ECDsa` instances to support cross-plat scenarios. Moving the discussion about the need of other constructors that take `RsaParameters` and byte blob to another issue #337 .

**Comment by PinpointTownes** [comment]
:clap: :clap:
