### ISSUE TITLE
beta8 -> rc1-final jwt signature validation fails

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#326]
Moving from aspnet/security repo: https://github.com/aspnet/Security/issues/582

----------------------------------------------------------------------------------------------------------

I have been utilizing this same jwt signature validation code since beta6 and it has worked without issues. 

Once I upgraded to rc1-final. Signature validation fails, because the payload is different on the consumer end and I can not determine why, before I start posting the Generation and Consumer code were their any rc1-final changes that could have potentially cause this issue I am encountering?

I have verified the secret used in the generation is the same as being used to validate the signature, like I said this code is the same as from dnx beta 6.

**Generation Key:**

    var hmac = new HMACSHA256(Convert.FromBase64String(client.Secret));
    var key = new InMemorySymmetricSecurityKey(hmac.Key);
    var signingCredentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256Signature, SecurityAlgorithms.Sha256Digest);

*Ticket generated payloads:*

**jwt.EncodedHeader**
    
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

**jwt.EncodedPayload**

 
     eyJ1bmlxdWVfbmFtZSI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJlbWFpbCI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJzdWIiOiJjb3JleWhAaGVhcnRsZWdhY3kuY29tIiwiaXNzIjoiYXV0aC5oZWFydGxlZ2FjeWRldi5jb20iLCJhdWQiOiJQb3N0TWFuIiwiZXhwIjoxNDQ3OTU0NTUxLCJuYmYiOjE0NDc5NTQ1NTB9

*diff: Q1NTB9*

*Incoming Bearer Payload:*

**jwt.EncodedHeader**

    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

**jwt.EncodedPayload**
            
    eyJ1bmlxdWVfbmFtZSI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJlbWFpbCI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJzdWIiOiJjb3JleWhAaGVhcnRsZWdhY3kuY29tIiwiaXNzIjoiYXV0aC5oZWFydGxlZ2FjeWRldi5jb20iLCJhdWQiOiJQb3N0TWFuIiwiZXhwIjoxNDQ3OTU0NzQ0LCJuYmYiOjE0NDc5NTQ3NDN9

*diff: Q3NDN9*

**StartUp**

    app.UseJwtBearerAuthentication(config =>
            {
                config.AutomaticAuthenticate = true;
                config.TokenValidationParameters.ValidateAudience = true;
                config.TokenValidationParameters.ValidateIssuer = true;
                config.TokenValidationParameters.RequireExpirationTime = true;
                config.TokenValidationParameters.ValidateLifetime = true;
                config.TokenValidationParameters.RequireSignedTokens = true;
                config.TokenValidationParameters.ValidateIssuerSigningKey = true;
                config.TokenValidationParameters.ValidateSignature = true;
               
                config.SecurityTokenValidators.Clear();
                config.SecurityTokenValidators.Add(new CustomSecurityTokenValidator(appName)); // <-- signature validation happens here
            });

So inside of CustomSecurityTokenValidator I have this 

    var jwt = new JwtSecurityToken(securityToken);

I am curious if the JwtSecurityToken class is somehow modifying the jwt payload and if that was recently modified in rc1-final?

    public override ClaimsPrincipal ValidateToken(string securityToken,
            TokenValidationParameters validationParameters, out SecurityToken validatedToken)
        {
            var jwt = new JwtSecurityToken(securityToken);

**Comment by tushargupta51** [comment]
copying from original issue:

I was able to resolve the issue using following code. I will validate this works using the properties provided via JwtSecurityToken ctor, and if so I will close this.

     private static SecurityToken SignatureValidator(string token, TokenValidationParameters validationParameters)
    {

            var authRepo = new AuthModelRepository();
            var authClient = authRepo.GetAuthClientByOAuthClientID(validationParameters.ValidAudience);

            var tokenParts = token.Split('.');
            var header = tokenParts?[0];
            var tokenHdr = JwtHeader.Base64UrlDeserialize(header);

            var payload = tokenParts?[1];
            var tokenPld = JwtPayload.Base64UrlDeserialize(payload);

            var signedData = $"{header}.{payload}";

            var signature = tokenParts?[2];

            var secretBytes = Convert.FromBase64String(authClient.Secret);

            var hmac = new HMACSHA256(secretBytes);
            var hmacKey = hmac.Key;

            var computedSignature = CryptoHashHelper.CalculateHMAC256Hash(signedData, hmacKey);

            if(signature!=computedSignature)
                throw new NullReferenceException("Invalid token signature specified.");

            var secToken = new JwtSecurityToken(token);
            return secToken;
        }

     public static string CalculateHMAC256Hash(string input, byte[] key)
     {
            var hmac256 = new HMACSHA256(key);
            byte[] byteArray = Encoding.UTF8.GetBytes(input);
            using (MemoryStream stream = new MemoryStream(byteArray))
            {
                byte[] hashValue = hmac256.ComputeHash(stream);
                return EncodingHelper.Base64Url.Encode(hashValue);
            }

      }


**Update**
After using the same data values but using the JwtSecurityToken(string) class properties the validation does not pass.

![capture](https://cloud.githubusercontent.com/assets/621804/11292647/af5b95dc-8f16-11e5-8076-8918fb43ac4b.PNG) ^^ ignore me throwing a null ref ex

**Comment by tushargupta51** [comment]
@dynamiclynk is this still an issue? From your comments above, it seems that the generated string jwt paylod is different that the incoming jwt token paylod. Why is that so? JwtSecurityToken(string) constructor decodes the string into a JwtSecurityToken but if the strings are different, it will result in 2 different tokens.

**Comment by dynamiclynk** [comment]
It's not an issue for me any longer due to the fact I abstracted the token signature validation, and that works. Prior (beta8) to rc1-final I did not have to do this and was able to use the jwt properties provided from JwtSecurityToken.

**Comment by brentschmaltz** [comment]
@dynamiclynk What is the value of jwt.RawSignature? Where do you instantiate the JwtSecurityToken?

**Comment by brentschmaltz** [comment]
@dynamiclynk can you shoot me the value of jwt.RawData? I think we have an encoding issue.

**Comment by tushargupta51** [comment]
@brentschmaltz @dynamiclynk We do have an issue with the encoding. I ran few tests and observed the following:

     string rawHeader = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9";
     JwtHeader header = JwtHeader.Base64UrlDeserialize(rawHeader);
     string jsonFromRawHeader = Base64UrlEncoder.Decode(rawHeader);
     string jsonFromObject = header.SerializeToJson();
     string encodedHeader = header.Base64UrlEncode();

The above code yields following results:

jsonFromRawHeader = "{\"typ\":\"JWT\",\"alg\":\"HS256\"}"
jsonFromObject = "{\"alg\":\"HS256\",\"typ\":\"JWT\"}"
encodedHeader = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

As you can see, the order of properties in the json generated from the rawHeader and from the object is different. The difference in order cause the encoding to generate a different value when we call Base64UrlEncode.Encode(jsonFromObject).

I am not sure how we can preserve the order of the fields when serializing the object back to json.

Another interesting that I noticed is that the behavior with payload is not consistent. Sometimes, I got different results but now I am consistently getting same values for both rawPayload and EncodedPayload.

**Comment by tushargupta51** [comment]
@dynamiclynk Since we cannot preserve the order of fields (as it was in the original json), the encoded values are not guaranteed to be same as the raw values. When validating the signature, one should always use the raw values - jwt.RawHeader, jwt.RawPayload, jwt.RawSignature.

In the VS screenshot above, it should be
     var signedData = $"{jwt.RawHeader}.{jwt.RawPayload}";

Let us know if you had the signature validation issues when using the raw values.

**Comment by dynamiclynk** [comment]
You should be able to preserve the order of the jsonFromRawHeader fields if you Serialize the jwt string to a concrete object JwtHeader  then Json Deserialize the JwtHeader object right?

*Concrete Object*
```c#
public JwtHeader
{
    string typ {get;set;}="JWT";
    string alg {get;set;}="HS256";
    etc....
}
```

When I have time I will verify if I have any issues with the raw values.

**Comment by tushargupta51** [comment]
@dynamiclynk not always since we are not sure about the order of fields in the raw header, it could be typ, alg or alg, typ. Only thing we can control is the order of json deserialized from JwtHeader but it may not match the one in the raw header.
