### ISSUE TITLE
Implement Validators.ValidateIssuerSecurityKey

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#329]
Validators.ValidateIssuerSecurityKey is not currently implemented in both 4.x  and 5.x. This method validates the security key that signed the jwt token. Evaluate if we need this method or not.

Related: #209

**Comment by brentschmaltz** [comment]
This customer hit this issue. http://stackoverflow.com/questions/35282863/how-can-i-get-openidconnectauthenticationmiddleware-to-validate-the-signing-cert
We should fix it. Also hook up the delegate.

**Comment by tushargupta51** [comment]
We have a delegate hooked up in 5.x: TokenValidationParameters.IssuerSigningKeyValidator. Though, we dont have anything like that in 4.x

**Comment by bgever** [comment]
There is a serious issue with this, that from an API consumer standpoint, this missing implementation is not obvious at all. In fact, it was only that when I *happen* to check the source code, that I found out the actual validation is commented out!

So in the following case:

```cs
var validationParameters = new TokenValidationParameters
{
    ValidateIssuer = true,
    ValidateIssuerSigningKey = true
};
var jwtHandler = new JwtSecurityTokenHandler();
SecurityToken token;
ClaimsPrincipal principal = jwtHandler.ValidateToken(serializedJwt, validationParameters, out token);
```

There is no warning at all, and I would *falsely believe* that the validation is happening, posing a security risk if I would not test that the library doesn't do its job.

If it is not implemented, remove it from the API, or make it clear to API consumers that no validation is happening.

I would expect a `NotImplementedException` to be thrown. In the message it could detail that there is a *workaround* by specifying your own `IssuerSigningKeyValidator` delegate in the `TokenValidationParameters`.

**Comment by brentschmaltz** [comment]
For 4.x in Validators.ValidateIssuerSecurityKey throw meaningful error when
1. Key is not X509SecurityKey - tell users we only support X509SecurityKey.
2. if  validationParameters.CertificateValidator == null, after checking that key is X509SecurityKey. - tell user they need to set CertificateValidator.

**Comment by brentschmaltz** [comment]
@bgever for 5.x, we will do something, but this is not a big concern because you are required to add keys to TokenValidationParameters. It is assumed you trust them. We left this in 5.x mainly because if we support signedxml (again), sometimes the xml has public keys embeded in the xml. In that case you need to validate you trust the cert.
