### ISSUE TITLE
Add extensibility for different RSA platforms

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#335]
Our current implementation of AsymmetricSignatureProvider.ResolveDotNetCoreAsymmetricAlgorithm assumes RSAOPenSsl is the right thing if !Windows. Need some kind of extensibility here.

if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                    _rsa = new RSACng();
                else
                    _rsa = new RSAOpenSsl();

**Comment by tushargupta51** [comment]
@brentschmaltz Currently, if a user wants to extend the `AsymmetricSignatureProvider`, he has to override the implementation in SignatureProviderFactory (or SecurityKey.GetSignatureProvider) to return the custom provider and plug in their own implementation of algorithms.

What do you mean by adding extensibility here? Making ResolveDotNetCoreAsymmetricAlgorithm  and ResolveDotNetDesktopAsymmetricAlgorithm  methods virtual (currently they are private)?

**Comment by brentschmaltz** [comment]
We need a way to allow users to create the RSA type they need. I don't think a static method Rsa.Create() will work as it is not dynamic. We can have a virtual ResolveAsymmetricAlgorithm (btw the method for DOTNET5_4 and other can be the same name) OR introduce a delegate: AsymmetricAlgorithmResolver. The tension of creating a clean design is the result of  AymmetricAlgorithm cannot do much by default and we always have to upcast. 

We may need to invent that type (similar to the Formatter and Deformatters).

**Comment by bartonjs** [comment]
https://github.com/dotnet/corefx/issues/2953 was fixed, so the platform RSA.Create() is now available.  While it currently does not allow for fully-arbitrary RSA implementations, it does leave the decision of "what is the right RSA for this platform?" in corefx.

**Comment by tushargupta51** [comment]
@bartonjs are these changes part of rc2 packages or rc3? We are using the rc2 version of .net packages for next release.

**Comment by bartonjs** [comment]
@tushargupta51 Looks like both? :smile:  I just checked in rc2-23818, and I see it there.  Lemme know if you're not encountering a path-to-success.
