### ISSUE TITLE
Constructors on RsaSecurityKey and ECDsaSecurityKey classes

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#337]
From a comment on the PR #334: this is about the usefulness of following 2 constructors:
1. ECDsaSecuirytKey(byte[] blob, CngKeyBlobFormat blobFormat)
2. RsaSecurityKey(RsaParameters rsaParameters)
CngKey and RsaParameters properties are used by AsymmetricSignatureProvider to create ECDsa and Rsa instances respectively when keys are constructed using components and not the crypto provider instances. Taking these properties off of the class only makes sense when we remove the constructors too, otherwise those constructors wont offer any value.

Investigate whether having these constructors on the classes are useful or not:
1. Should we have `CngKey` property on the `ECDsaSecurityKey` class?
2. Should we have `RsaParamaters` property on `RsaSecurityKey` class?

cc: @brentschmaltz @pinpointtownes

**Comment by PinpointTownes** [comment]
> Should we have RsaParamaters property on RsaSecurityKey class?

Ideally, I'd say no. That said, I agree it's a really convenient way to instantiate a RSA key, so maybe it would be worth keeping it as a static factory method:

```csharp
public static RsaSecurityKey Create(RSAParameters parameters) {
    var algorithm = // Since RSA.Create() is not ready yet,
                    // determine the best implementation locally:
                    // RSACryptoServiceProvider on Windows desktop and Mono,
                    // RSACng on CoreCLR for Windows and RSAOpenSsl on CoreCLR for Linux.
    algorithm.ImportParameters(parameters);
    return new RsaSecurityKey(algorithm);
}
```

> Should we have CngKey property on the ECDsaSecurityKey class?

CngKey is totally Windows-specific (it won't work at all everywhere else), so I'm not sure it's really pertinent to have it in the public contract. Sadly, we don't have an `ECDsaParameters` equivalent to easily import an elliptic curve key (from a JWK set for instance). Even on Windows, you must hack a blob array to import a CNG key (which is probably why you've decided to close https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/62).

/cc @bartonjs

**Comment by bartonjs** [comment]
@PinpointTownes Yeah, `ECParameters` is on my ever-growing todo list :(.   The good news is it's reusable between ECDH and ECDSA.  The bad news is it's massively polymorphic (named curve, explicit prime curve, explicit char2 binomial, explicit char2 trinomial, explicit char2 pentanomial, future formats) and we haven't come up with the way to handle it.  But, since you've asked, I've decided to move that todo item off of my whiteboard and onto https://github.com/dotnet/corefx/issues/5314.

**Comment by brentschmaltz** [comment]
@PinpointTownes @bartonjs @tushargupta51  Tushar and I had a chat about this. Our issue is how do we create the ECDsa provider from key material obtained from metadata. Having ECParameters similar to RSAParameters was our first thought. However, we are now considering having JsonWebKey derive from SecurityKey. This will allow us to localize the complexity to our CryptoProviderFactory. Resulting in: OIDC discovery -> JsonWebKey -> SignatureProvider -> Verify(...).  Currently JsonWebKeySet has to know how to translate keys to providers, which we could remove.
I think it is safe to assume users with hardware or private keys, can use the constructors that take RSA or ECDsa. 
We may create a ECParameter class in System.IdentityModel.Tokens if we feel it has value.

**Comment by brentschmaltz** [comment]
@PinpointTownes +1 were are getting rid of the constructors that take CNG stuff.

**Comment by bartonjs** [comment]
@brentschmaltz I don't know how an ECParameter type would help you without the ECDsa implementations accepting one.  You could probably figure out how to jam it into a blob of the right format, create a CngKey around it, and pass that to ECDsaCng, but what's your plan for OpenSsl?

If creating one internally helps some part of your code, please don't make it a public type; it'll just confuse matters when we add it in System.Security.Cryptography.Algorithms.

**Comment by brentschmaltz** [comment]
@bartonjs probably the JsonWebKey is enough to create a ECDsa provider, which exists in OpenSsl. So ECParameter may not be needed. However, it would only make sense to have it as a public type, since ECParameters helps devs.
There has to be platform specific code somewhere, for Wilson we choose our CryptoProvider. Inside that type, users can do all the thunking they need. We just need to make sure the extensibility is smooth.

**Comment by PinpointTownes** [comment]
> @PinpointTownes Yeah, ECParameters is on my ever-growing todo list :(.
I've decided to move that todo item off of my whiteboard and onto dotnet/corefx#5314.

Thanks (FWIW, I really admire your work on crypto stuff)! :clap: 

> However, we are now considering having JsonWebKey derive from SecurityKey.
We may create a ECParameter class in System.IdentityModel.Tokens if we feel it has value.

Not sure how it would help. As mentioned by @bartonjs, having your own `ECParameters` won't be really helpful if you have no way to import the EC key. To make that work on Linux, I guess you'd have to make some serious interop stuff to create an `EC_KEY` blob (by calling `EC_KEY_new_by_curve_name` with the curve name and `EC_KEY_set_public_key_affine_coordinates` with the X/Y coordinates extracted from the JWK key).

**Comment by brentschmaltz** [comment]
I agree that ECParameters should be in dotnet/corefx. For now, the goal is to make sure EC is possible xplat. We can implement on a priority basis what works by default.
