### ISSUE TITLE
Support for JSON-valued claims

### ISSUE THREAD

**Issue by jackwhelpton** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#342]
I'm trying to implement the [Token Exchange draft](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-03), which features JWT claims of the form:

``` javascript
{
    "aud": "https://as.example.com",
    "iss": "https://client.example.net",
    "exp": 1441910060,
    "scp": ["status","feed"],
    "sub": "user@example.net",
    "may_act":
    {
        "sub": "admin@example.net",
        "name": "Admin"
    }
}
```

When I construct a `JwtSecurityToken` object, the claims generated for the token above are:

```
"aud": "https://as.example.com"
"iss": "https://client.example.net"
"exp": "1441910060"
"scp": "status"
"scp": "feed"
"sub": "user@example.net"
"may_act": "\"sub\": \"admin@example.net\""
"may_act": "\"name\": \"Admin\""
```

Are the separate `may_act` claims expected? They're created by these lines of code:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b2f7484d3bf6786e355922b113d27ca06d0cc2ba/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L342-L359

As `JObject` implements `IEnumerable{JProperty}`, this code creates a separate claim for each `JProperty`. These claims are not valid/complete JSON objects.

What's the recommended approach here? I can reassemble a JSON object in an `IClaimsPrincipal` extension method, but I wonder whether `JObject` should be special-cased in the code above to ensure that only a single (JSON-valued) claim is created in the first place.

**Comment by brentschmaltz** [comment]
@jackwhelpton I have been out for a few days, I will look into this.

**Comment by brentschmaltz** [comment]
@jackwhelpton I would like to get this shorted out before we drop rc2. Can you share you created you JWT? I have experimented with a couple of different ways to add the claims and that affects the result.

**Comment by leastprivilege** [comment]
In IdentityServer we introduced a ClaimTypeValue.Json.

**Comment by jackwhelpton** [comment]
I've been experimenting with IdentityServer 4, and what @leastprivilege refers to above is exactly the approach I'd taken (within an `ICustomGrantValidator`).

When debugging I then just used that JWT in string form. There's no sensitive information in it, so here's the exact line:

```csharp
var jwt = new JwtSecurityToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjIyNTMwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDoyMjUzMC9yZXNvdXJjZXMiLCJleHAiOjE0NTQwODYzMzYsIm5iZiI6MTQ1NDA4MjczNiwiY2xpZW50X2lkIjoicmFrdXRlbi5jYXRhbG9nIiwic2NvcGUiOiJjb3JlIiwibWF5X2FjdCI6eyJzdWIiOiIxNzQxMjI2IiwibmFtZSI6IjE3NDEyMjYiLCJ0ZXN0LWNvbXBsZXgtcHJvcGVydHkiOnsia2V5IjoidmFsdWUifX19.FEa___lR8uks4R7npuHvOSSw4fbde83z2-9X-ZMgwQPvk1rSbv8dKEgdCuhE16u7rn6oERhJJeyJGJsEJRDDY3gjLlPmWdy2nTlxpnMOwOctrWipKsualVZvr0Jt9P4pMECYrxl434waL6CbVEQri6-fYwnIPrp8fCGl-WxSbF4z1UWKGfYxOhYr9e0zx5kLLWmLM-kBsPPeqO2h0DcF0-kdvTJ1XER5_ev2Sf_RgMkFhC2bMYhFfheMAWLrDdsnEeZfw4X8hkS5lJ_1adas4fEs2ETBBerLf6p2I8Majy0vosybtTAw7XhKSarbDtA7PVmR_vb8mopLvw0tWf4ssQ");
```
My experimental fix was to add a block like this to the `Claims` property linked to above:
```csharp
// Do we have a JSON object?
var json = keyValuePair.Value as JObject;
if (json != null)
{
    claims.Add(new Claim(keyValuePair.Key, json.ToString(), JwtConstants.JsonClaimValueType, issuer, issuer));
    continue;
}

// Do we have a collection of objects?
var values = keyValuePair.Value as IEnumerable<object>;
if (values != null)
{
    ...
    continue;
}

...
```

I ended up moving to a "continue" pattern as adding another special case like this leads to (what looked to me to be) an excessive level of nesting.

**Comment by brentschmaltz** [comment]
@jackwhelpton @leastprivilege that is a good idea. I am fiddling with it to understand how to think about n/v that have imbedded JSON.

On a separate note, the parsing code that transforms JSON -> .Net Claims is dependent on the serialization engine. I also have remnants from when the .Net JavaScriptSerializer was used.
It seems that if we want support different serializers, we need to account for this. It means some additional extensibility and removing or improving the static JsonExtensions.

**Comment by tushargupta51** [comment]
Re-opening since this is not fixed in 4.x yet.

**Comment by polita** [comment]
Because of the way we create the subtoken, there's no good way to override the claims creation.

**Comment by ycrumeyrolle** [comment]
Any chance to have a fix ?

**Comment by brentschmaltz** [comment]
@ChenYan98 5.x changed so that  
"may_act":
{
    "sub": "admin@example.net",
    "name": "Admin"
}

Would return a single System.Security.Claims.Claim:  {may_act, { "sub":"admin@example.net", "name":"Admin"}, JsonClaimValueTypes.JsonArray}. Which is a single claim where the ValueType indicates the string is well formed JSON.

Please investigate the work involved in making this change in 4.x. See: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/test/System.IdentityModel.Tokens.Jwt.Tests/JwtPayloadTest.cs#L284
For example of the test.

**Comment by ChenYan98** [comment]
If we update Wilson to 5.x in Katana in next few months then I think we are ok with not fixing this for 4.x. @brentschmaltz what is your opinion?

**Comment by brentschmaltz** [comment]
@ChenYan98 We haven't closed on ensuring 5.x will be modified to support Katana. Let's table this until we make that decision.

**Comment by Tratcher** [comment]
There may be an update to Katana in the next few months where it could move to 5.x if it didn't impact consumers too much.
