### ISSUE TITLE
Whats the plan for the Microsoft.IdentityModel.S2S.* classes?

### ISSUE THREAD

**Issue by SharePointRadi** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#343]
A lot of stuff used Microsoft.IdentityModel.S2S classes, such as OAuth2S2SClient. This includes SharePoint Apps. 
Is there an equivalent, or plans for one, in the vnext builds?
I am working on a new SharePointContext class and would like to know the best way forward to migrate the existing one delivered with the tooling when you create a new SharePoint App project. Thanks!

**Comment by brentschmaltz** [comment]
@SharePointRadi can you point me to the repo? I want to be sure I am understanding the question here.

**Comment by SharePointRadi** [comment]
Hey @brentschmaltz 

I'm referring to the following assembly: Microsoft.IdentityModel.Extensions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=69c3241e6f0468ca I don't think it was ever open source.

It has many classes that deal with S2S auth and is the basis for all SharePoint app development. The current repo has something that appears to be the successor: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/master/src/Microsoft.IdentityModel.Protocol.Extensions

But there is nothing there for the S2S stuff.

**Comment by brentschmaltz** [comment]
@SharePointRadi We have moved forward on S2S specific libraries, but it is too early to share publically.

**Comment by tushargupta51** [comment]
closing this for now. Feel free to re-open if you have any follow-up question.
