### ISSUE TITLE
System.IdentityModel.Tokens.Jwt.dll has a hard dependency on Newtonsoft.Json 6.0

### ISSUE THREAD

**Issue by xinyu8** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#350]
It looks like System.IdentityModel.Tokens.Jwt.dll version 5.0.0.112 has a hard dependency on Newtonsoft.Json version 6.0.0.0.  It blocks us from using this dll because other components in our system has dependency on Newtonsoft.Json 8.0.  It would be great to remove this dependency so that consumer could plugin their own JSON serializer and deserializer.  Maybe the hard dependency could be removed from the JsonExtensions static constructor so that the custom JSON lib could be plugged in via properties.

**Comment by brentschmaltz** [comment]
@xinyu8 what error are you experiencing? Compile? Updating References? Runtime?

**Comment by xinyu8** [comment]
It's runtime error for not be able to load Newtonsoft 6.0 dll.
Background: we use pacman (instead of Nuget) to manage packages/libraries. The IdentityModel dll is packaged into one pacman package from Nuget without any external dependencies.  After encounter the runtime error, I tried to add dependencies to Newtonsoft pacman package within my component.  However, I was not able to add Newtonsoft 6.0 because the minimum version of Newtonsoft supported in pacman is 8.0.

**Comment by brentschmaltz** [comment]
@xinyu8 I am not familiar with 'pacman'. Where can I get it so I can play with it?

**Comment by xinyu8** [comment]
oh, that Bing or OSD depot. You could start from https://www.bingwiki.com/Pacman

**Comment by brentschmaltz** [comment]
Fixed with PR #355
