### ISSUE TITLE
RSACryptoServiceProviderProxy is upleveling incorrectly.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#358]
RSACryptoServiceProviderProxy should not uplevel the CSP for hardware keys.
We should have a set of ProviderTypes that we restrict the uplevel for. Currently 1 and 12 seem right.

**Comment by tushargupta51** [comment]
All possible values of provider types are here: https://msdn.microsoft.com/en-us/library/system.security.cryptography.cspparameters.providertype(v=vs.110).aspx

From that list, the ones that are concerned with rsa are:
1. prov_rsa_full == 1
2. prov_rsa_sig == 2
3. prov_rsa_schannel == 12
4. prov_rsa_aes == 24

Only #4 supports sha256. Before uplevelling the rsa provider, we check if it can be read as a `RsaCryptoServiceProvider` object. Chances that it is of type RsaCryptoServiceProvider but its provider type value is none of the ones mentioned above are pretty low. I think its safe to have this check before we uplevel:

    if (rsa.CspKeyContainerInfo.ProviderType != PROV_RSA_AES && !rsa.CspKeyContainerInfo.HardwareDevice)

**Comment by brentschmaltz** [comment]
I marked this as RC2, Can we get tests in place? Also we need to ignore HardwareKeys.

**Comment by tushargupta51** [comment]
`!rsa.CspKeyContainerInfo.HardwareDevice` will ignore hardware keys. Unfortunately, we dont have any tests for hardware keys right now, and might not be able to get that in rc2. What other tests do you think we need? Certs with provider type == 12?

Also, ignore my comment about including algorithm parameter, noticed that we removed support for sha1 earlier, we only support sha256, sha384, sha512, for all of these we need to uplevel.

**Comment by brentschmaltz** [comment]
I am OK with getting the tests for Hardware key for post RC2. We will need to have a custom RSAProvider for this.

**Comment by polita** [comment]
I think you're saying that we're going to uplevel 1, 2, and 12, correct? The logic is right for rsa.CspKeyContainerInfo.ProviderType != PROV_RSA_AES, but I worry that it's not going to be obvious to the code reader that we're explicitly upleveling those 3 values. In addition, if we ever get a new value, I think we probably don't want to uplevel until we explicitly decide to. I recommend that we write it as:

(rsa.CspKeyContainerInfo.ProviderType == prov_rsa_full || rsa.CspKeyContainerInfo.ProviderType == prov_rsa_sig || rsa.CspKeyContainerInfo.ProviderType == prov_rsa_schannel) && !rsa.CspKeyContainerInfo.HardwareDevice

**Comment by tushargupta51** [comment]
Yes, we uplevel if its 1  or 2 or 12.

**Comment by tushargupta51** [comment]
@polita @brentschmaltz I think we don't need to check for the provider type == 2. That type did not even exist in my registry (and as a result wasted lot of time in debugging the test failure). From the link here: https://msdn.microsoft.com/en-us/library/windows/desktop/bb394803(v=vs.85).aspx, it seems that Microsoft RSA Signature Cryptographic Provider (provider that corresponds to prov_rsa_sig) is no longer supported. Most common type is prov_rsa_full with some usage of prov_rsa_schannel. I think we should only check for prov_type == 1 and 12.

**Comment by PinpointTownes** [comment]
Don't forget that on Mono, `CspKeyContainerInfo.ProviderType` also returns `1`: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/179.

Though Wilson is broken ATM due to the missing ECDsa types, it might be a good idea to add a special case for Mono to avoid using `RSACryptoServiceProviderProxy`.

**Comment by tushargupta51** [comment]
@PinpointTownes will get to that when we fully support mono.

**Comment by tushargupta51** [comment]
Re-opening since this is not fixed in 4.x yet.

**Comment by tushargupta51** [comment]
Closing this as we do not uplevel `RsaCryptoServiceProvider` in 4.x., that happens in System.IdentityModel.Token.SecurityKey class in .net. Please note that the fix for upleveling without breaking hardware keys is available in .net 4.6.2 and later versions.
