### ISSUE TITLE
OpenIdConnectConfiguration should 'remember' new metadata.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#359]
OpenIdConnectConfiguration has a fixed set of properties. For future proofing new metadata, we need to design a way to capture new metadata and expose it to users.

**Comment by brentschmaltz** [comment]
Fixed, added Property AdditionalData
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/382/files

**Comment by tushargupta51** [comment]
Re-opening for 4.x

**Comment by polita** [comment]
If this is going to take more than a few hours, let's close without fixing for 4x.

**Comment by brentschmaltz** [comment]
We were much smarter about how we parsed JSON in 5.x. This fix would take more than a couple of hours.
