### ISSUE TITLE
JwtSecurityTokenHandler.CreateJwt no longer sets JwtSecurityToken.SigningCredentials

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#360]
_Moved from https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/232._

______

The recent changes introduced by @brentschmaltz [in this commit](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/6cefb7cf902abdfb594fb785f30bec8e5af4059b) broke `CreateJwt`, which is no longer able to flow the `SigningCredentials` taken as a parameter to the `JwtSecurityToken` it returns due to the (weird) lossy serialization + deserialization process it's now using:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L371

This is obviously a serious regression since calling `WriteToken` to serialize the JWT now results in a compact JWT that lacks the signature.

/cc @brentschmaltz @tushargupta51

**Comment by brentschmaltz** [comment]
@PinpointTownes thanks, will look into this.

**Comment by PinpointTownes** [comment]
> Will put back the original behavior.

Thanks! :clap:

**Comment by PinpointTownes** [comment]
@brentschmaltz people want your fix :trollface: 

![image](https://cloud.githubusercontent.com/assets/6998306/14323305/4e261590-fc20-11e5-92b0-02c1dc2cfebb.png)

**Comment by brentschmaltz** [comment]
@PinpointTownes It was committed today. Should be in tonight's myget.release.

**Comment by sunsided** [comment]
Which package would that be? Because force-refreshing my packages from `aspnetcidev` doesn't seem to do the trick.

**Comment by capesean** [comment]
It's not in the `aspnetcidev` feed yet, it's only in the `azureadwebstacknightly`:
https://www.myget.org/gallery/azureadwebstacknightly

See the version for: `System.IdentityModel.Tokens.Jwt`

You'll need to add that feed to your nuget config if you want to pull that package from there before it gets into aspnetcidev.

**Comment by sunsided** [comment]
Ah, well that both explains it and makes sense at the same time!

**Comment by PinpointTownes** [comment]
Unfortunately, trying to use the azureadwebstacknightly feed - as I had initially suggested - will cause more pain because ASOS needs to be fixed to react to a breaking change in `IdentityModel`: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/232#issuecomment-207046066

Sadly, since the updated package is not on the aspnetcidev feed we use, I can't push the fix ATM.
