### ISSUE TITLE
Generate XML documents when building.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#369]
each project.json file under src, should include:     "xmlDoc": true in the compilationOptions.
such as: 
 "compilationOptions": {
    "warningsAsErrors": true,
    "keyFile": "../../tools/Key.snk",
    "nowarn": [
      "CS1591"
    ],
    "xmlDoc": true
  },

**Comment by PinpointTownes** [comment]
Was it too late to fix that for RC2?

**Comment by brentschmaltz** [comment]
@PinpointTownes we are going to work on it and if we can get it done before ASP.NET is done AND they will take a new drop. But I wouldn't block ship on it.
