### ISSUE TITLE
Review Exceptions Thrown by JwtSecurityTokenHandler

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#375]
1. Make sure there are tests for all exception paths.
2. Exception messages displayed to users are correct, make sense, are actionable, well-formed.
3. Derivation makes sense. For example, SecurityTokenInvalidSignatureException derives from SecurityTokenValidationException, etc.
4. /// Method comments reflect Exceptions thrown correctly.

**Comment by tushargupta51** [comment]
@vibronet This is the issue that asp.net is waiting on.
