### ISSUE TITLE
how to integrate AD b2c in Bot Framework?

### ISSUE THREAD

**Issue by whatsdis** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#379]
been trying all day to get my bot framework chat bot to authenticate user via Active directory B2C

Is it possible to call /Account/SignIn URL from bot framework to authenticate the user? Afterwards, how would you capture the token and pass it to BotUserData?

The only authentication example I found was https://azure.microsoft.com/en-us/blog/bot-framework-made-better-with-azure/ but that solution does not compile. I ripped out the relevant bits and plugged it in to my botframework but it will not authenticate a user. After logging in it just gets stuck at the microsoft login saying something went wrong without any helpful insight.

really would like to get authentication working with botframework but no documentation exists....which makes the problem worse.

**Comment by matvelloso** [comment]
Hello. While we don't have a great sample of that yet (working on it) you can take this one and adapt: https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleFacebookAuthBot 

The difference is that this sample is specific for Facebook, so it will generate an oauth string that will send the user straight to facebook's page. In your scenario you will need to generate an oauth URL that will take the user to AAD B2C's auth page (basically following these guidelines: https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-reference-oidc/). Sorry things are a bit raw right now, we're working on it :)

The way this works is basically by giving the user a URL to go authenticate on some web page and that web page will handle the token back to the bot.

**Comment by samsmithnz** [comment]
I know this is a year old, but is there an Azure AD sample out there now? I'm having a bit of trouble finding a good working example to clone.

**Comment by DaveVoyles** [comment]
Looking for the same, @samsmithnz

**Comment by v-kydela** [comment]
This thread may provide some good insight: https://github.com/Microsoft/BotFramework-Services/issues/78
