### ISSUE TITLE
Release Notes for RTM.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#387]
Opening this to track changes for RC2.

OpenIdConnectConfiguration, JsonWebKey, JsonWebKeySet now return collections that users will need to add / remove items rather than setting the entire collection.

**Comment by tushargupta51** [comment]
We will release notes when releasing RTM.

**Comment by polita** [comment]
Let's do this during escrow.
