### ISSUE TITLE
Reintroduce GetAsymmetricAlgorithm/GetSymmetricAlgorithm

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#395]
The base `AsymmetricSecurityKey` and `SymmetricSecurityKey` classes should expose `GetAsymmetricAlgorithm`/`GetSymmetricAlgorithm` to allow retrieving the underlying algorithm without having to cast the security key to known types.

@brentschmaltz any chance we could bring back these APIs for RTM?

**Comment by brentschmaltz** [comment]
@PinpointTownes my current thought is to role back the change we did in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/386, make the fix that we check for AsymmetricAlgorithmResolver before faulting and rethink it. We are always going to have the situation where users need to extend algorithm support. The model we put in requires deriving both Provider and Key. I am thinking all the key votes on is does the algorithm match my class: Symmetric or Asymmetric. Even then, with all the specs it will be hard to have a comprehensive solution over time. A natural extensibility model is needed here.

This kind of fits with this bug.
What are your thoughts on rolling back 386.

**Comment by PinpointTownes** [comment]
TBH, without seeing a prototype, it's hard to say :smile: 

That said, assuming `AsymmetricAlgorithmResolver` would work as .NET Desktop's `CryptoConfig`, then yeah, this sounds like the right approach to enable crypto agility on the long term.

Concerning `SecurityKey.IsSupportedAlgorithm`, no real preference. I believe the signature should stay as-is, so I'm not sure it's worth reverting it ATM. From my POV, it just needs to support the missing algorithms. Introducing a `CryptoConfig`-like for crypto agility would be a great bonus for RTM.

**Comment by tushargupta51** [comment]
@PinpointTownes Unfortunately, we cant make any changes to RC2, the bar is too high. We will get it fixed in nightlies though.

For `IsSupportedAlgorithm`, I am thinking of adding a delegate: `CryptoProviderFactory.IsSuuportedAlgorithmDelegate` (maybe a different name). Then `SecurityKey.IsSupportedAlgorithm` will look like this:

         public override bool IsSupportedAlgorithm(string algorithm)
        {
            if (string.IsNullOrEmpty(algorithm))
                return false;

            if (CryptoProviderFactory.IsSupportedAlgorithmDelegate)
                return CryptoProviderFactory.IsSupportedAlgorithmDelegate(algorithm);

            switch (algorithm)
            {
                case SecurityAlgorithms.RsaSha256:
                case SecurityAlgorithms.RsaSha384:
                case SecurityAlgorithms.RsaSha512:
                case SecurityAlgorithms.RsaSha256Signature:
                case SecurityAlgorithms.RsaSha384Signature:
                case SecurityAlgorithms.RsaSha512Signature:
                    return true;

                default:
                    return false;
            }
        }


For extending the algorithm support, this is what one needs to do then:
     CryptoProviderFactory factory = new CryptoProviderFactory();
     factory.AsymmetricAlgorithmReslolver = <my resolver>;
     factory.IsSuuportedAlgorithmDelegate = <my delegate>;
     CryptoProviderFactory.Default = factory;

**Comment by PinpointTownes** [comment]
@tushargupta51 for RC2, it's of course too late, that's why I suggested keeping the API as-is (no rollback) and adding the necessary stuff in the next milestone :+1: 

Your approach seems fine, and it's pretty close to what `CryptoConfig` offers,:

```
public override bool IsSupportedAlgorithm(string algorithm)
{
    if (string.IsNullOrEmpty(algorithm))
    {
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgument(algorithm, SR.GetString(SR.EmptyOrNullArgumentString, "algorithm"));
    }

    object algorithmObject = null;

    try
    {
        algorithmObject = CryptoHelper.GetAlgorithmFromConfig(algorithm);
    }
    catch (InvalidOperationException)
    {
        algorithmObject = null;
    }

    if (algorithmObject != null)
    {
        SignatureDescription signatureDescription = algorithmObject as SignatureDescription;
        if (signatureDescription != null)
            return true;
        AsymmetricAlgorithm asymmetricAlgorithm = algorithmObject as AsymmetricAlgorithm;
        if (asymmetricAlgorithm != null)
            return true;
        return false;
    }

    switch (algorithm)
    {
        case SecurityAlgorithms.RsaV15KeyWrap:
        case SecurityAlgorithms.RsaOaepKeyWrap:
        case SecurityAlgorithms.RsaSha1Signature:
        case SecurityAlgorithms.RsaSha256Signature:
            return true;
        default:
            return false;
    }
}
```

**Comment by brentschmaltz** [comment]
@PinpointTownes thanks again for your input :+1:

**Comment by PinpointTownes** [comment]
On a related note, I opened a ticket on dotnet/corefx to bring back `X509Certificate2.PublicKey.Key` and `X509Certificate2.PrivateKey`: https://github.com/dotnet/corefx/issues/8491.

It would allow implementing `X509SecurityKey.GetAsymmetricAlgorithm` without having to call the algo-specific extensions.

**Comment by brentschmaltz** [comment]
@PinpointTownes we changed the model from the key returning an algorithm to returning a CryptoProvider / SignatureProvider. Which makes X509SecurityKey.GetAsymmetricAlgorithm equivalent to X509SecurityKey.GetSignatureProvider. 

This aligns with our belief that keys just have data, CryptoProviders do work. The extensibility seemed easier when these two pieces are kept separate.

**Comment by PinpointTownes** [comment]
> @PinpointTownes we changed the model from the key returning an algorithm to returning a CryptoProvider / SignatureProvider. Which makes X509SecurityKey.GetAsymmetricAlgorithm equivalent to X509SecurityKey.GetSignatureProvider.

That would be true if I wanted to use the `AsymmetricAlgorithm` instance returned by `GetAsymmetricAlgorithm()` to sign data or to verify a signature, but relying on `SignatureProvider` no longer works if I want to access the underlying public key material (e.g to expose the RSA modulus/exponent in a JWK set)

**Comment by brentschmaltz** [comment]
Can't you get the modulus/exponent from the key?

**Comment by PinpointTownes** [comment]
@brentschmaltz oops, looks like I missed your reply.

> Can't you get the modulus/exponent from the key?

Sure. But for that, I need a `RSA` instance, to call `ExportParameter`. And currently, I have to manually cast a `SecurityKey` to `RsaSecurity` or `X509SecurityKey` to get this precious instance.

I need a base method that allows me to retrieve an algorithm instance if it's supported, independently of the key type.

**Comment by brentschmaltz** [comment]
Moving to backlog. Will address next release.

**Comment by brentschmaltz** [comment]
@PinpointTownes (spinning up for vnext). What scenario are you looking to support here?

**Comment by PinpointTownes** [comment]
@brentschmaltz same as before: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/444#issuecomment-225746555 :smile:

**Comment by PinpointTownes** [comment]
This ticket is still in the backlog. Is there anything I can do to help?

**Comment by brentschmaltz** [comment]
@PinpointTownes is this the main issue for this request to produce a JsonWebKey to place in a JWK set? 
> no longer works if I want to access the underlying public key material (e.g to expose the RSA modulus/exponent in a JWK set)

Our current design uses an intermediate class to create algorithms from keys. SecurityKeys by default don't have algorithms and are seen as data.  X509 populated from a cert being different different as it comes with a algorithm.

**Comment by PinpointTownes** [comment]
> @PinpointTownes is this the main issue for this request to produce a JsonWebKey to place in a JWK set?

Yes (at least for my scenario. Other people might need these methods for something else).

> Our current design uses an intermediate class to create algorithms from keys. SecurityKeys by default don't have algorithms and are seen as data. X509 populated from a cert being different different as it comes with a algorithm.

The fact your current design relies on `CryptoProviderFactory` doesn't prevent you from bringing back `GetAsymmetricAlgorithm()`. It's just another level of abstraction.

**Comment by brentschmaltz** [comment]
We could put GetAlgorithm on xyzProviders, but I don't think they fit on the key.

**Comment by brentschmaltz** [comment]
We are not going to support this as AsymmetricAlgorithm needs to be cast which leads to issues when the underlying framework changes as happened between 4.5 and 4.6.

A key has only data. A provider knows how to interact with the underlying layers to produce the correct crypto operations.

**Comment by PinpointTownes** [comment]
> A key has only data. A provider knows how to interact with the underlying layers to produce the correct crypto operations.

Care to share more information or better, write a sample about how to achieve the desired result without the suggested APIs?
