### ISSUE TITLE
Branch guidance and releases page

### ISSUE THREAD

**Issue by bgever** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#402]
I'm using NuGet package [System.IdentityModel.Tokens.Jwt v5.0.0-rc2](https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/5.0.0-rc2-305061149), however I am unable to find from this repo which branch was used to release this package. The Releases page also uses different versions not aligned with the NuGet package.

The master branch seems outdated with last commits around Dec 2015, however, dev, KDev, KRelease, KDevRC2 (*is this the one?!*) have recent commits. How do I know which branch to check? This should be documented in the README.md on the master branch.

**Comment by tushargupta51** [comment]
@bgever We usually tag our releases with the package version released on nuget. We forgot to tag a release for Rc2. Also, we have 7 packages that are released every release. Some of the packages start with 2.0.0 and some starts with 5.0.0 but all of them have the same patch/release number which should be used to find a branch corresponding to a released package. I just added a release for Rc2.

Master branch corresponds to the latest official GA version which is 4.x. 5.x/2.x are pre-release versions - KDev and KRelease are the tracking branches. But, if you want to track a branch for a specific release, use our tag branches here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tags

**Comment by bgever** [comment]
Thanks for creating the RC2 release.

If I were to contribute code with a PR, I would have to know what branch would be the best to branch off and create the PR for. Currently that is still unclear, though your message helped. My current guess is the KDev branch?

I suggest to add a CONTRIBUTING.md to the root of the project (also in the master branch), which may refer to a Wiki page here on GitHub, detailing which branch to best branch off, and what certain branches mean and how they are used. Especially what's in the master branch, because some repos keep stable code there (like this repo) and some other repos have the active latest development in master.

**Comment by tushargupta51** [comment]
@bgever Agree with you. We need better documentation. I will update Contributing, Readme and wiki so that external users have more idea about the code structure, now that we have 3 different versions in same repo.

In the meantime, if you have to contribute to the latest versions, KDev is the right branch. If you want to contribute to 4.x versions, dev is the right branch.

**Comment by bgever** [comment]
Great, thanks for clearing that up @tushargupta51! :smile:

**Comment by polita** [comment]
Fixed with PR #413

**Comment by bgever** [comment]
Awesome, super clear now, thanks a ton @polita! I like how README.md now clearly versions the namespaces.
