### ISSUE TITLE
ValidateTokenReplay happens too early in JwtSecurityTokenHandler.ValidateToken

### ISSUE THREAD

**Issue by bgever** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#404]
Refer to the following line in the `JwtSecurityTokenHandler.ValidateToken` method:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L562

The call to `ValidateTokenReplay` happens presumably at this line because the `expires` variable is available. However, there are more validations after this call.

*These validations, including the issuer, should happen before the replay is checked.*

The reason is the `jti` claim, which says per the [RFC7519 spec](https://tools.ietf.org/html/rfc7519#section-4.1.7) (emphasis mine):

> 4.1.7.  "jti" (JWT ID) Claim
> 
>    The "jti" (JWT ID) claim provides a unique identifier for the JWT.
>    The identifier value MUST be assigned in a manner that ensures that
>    there is a negligible probability that the same value will be
>    accidentally assigned to a different data object; **if the application
>    uses multiple issuers, collisions MUST be prevented among values
>    produced by different issuers as well.**  The "jti" claim can be used
>    to prevent the JWT from being replayed.  The "jti" value is a case-
>    sensitive string.  Use of this claim is OPTIONAL.

So when the cache delegate as part of the ValidateTokenReplay call would check the JWT, it would use the `jti` claim to look up duplicates. However, this should be from the **context of the issuer**, which currently isn't verified at that stage.

Therefore, I would recommend to change the location of the ValidateTokenReplay to move it down until all validations have completed, after [line 613](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L613).

**Comment by brentschmaltz** [comment]
@bgever this makes sense. Thanks for the input. Marked for RTM.

**Comment by bgever** [comment]
Great, thanks for adding to the RTM milestone, @brentschmaltz.
