### ISSUE TITLE
SecurityKey.GetSignatureProvider uses different parameter names than SignatureProvider.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#407]
SecurityKeys use: verifyOnly
SignatureProviders use: willCreateSignatures

they should both be the same.

**Comment by tushargupta51** [comment]
I think the reason we did not change that earlier is because this will be a breaking change for people, since it changes the meaning of the boolean, and we thought it was not worth it.

**Comment by polita** [comment]
Let's just live with this, since this would be a breaking change.
