### ISSUE TITLE
SecurityToken exceptions should include details as properties

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#422]
E.g. SecurityTokenInvalidAudienceException should have an InvalidAudiance property containing the invalid value. Similarly for SecurityTokenInvalidIssuerException, SecurityTokenInvalidLifetimeException, SecurityTokenNotYetValidException, SecurityTokenExpiredException, and maybe SecurityTokenInvalidSignatureException and SecurityTokenSignatureKeyNotFoundException.

RE: https://github.com/aspnet/Security/pull/845

**Comment by polita** [comment]
@Tratcher We've moved this to the backlog because we don't think we can get this done for RTM.

**Comment by polita** [comment]
@Tratcher This info is in the exception message for logging and debugging. We don't think this needs to be specific properties in the exception types.

**Comment by Tratcher** [comment]
@polita @brentschmaltz please reconsider, the current messages are not suitable for our scenario (sending to a remote client). We want to generate our own messages with the relevant details.

**Comment by brentschmaltz** [comment]
@Tratcher can you give us an example for say: InvalidAudienceException. What is bad about the current message, what your new message would look like and what would the new InvalidAudienceException properties return.

**Comment by Tratcher** [comment]
The issue is not the current messages per say, the issue is that we are crossing a trust boundary and cannot pass through unknown data. Your messages are "for logging and debugging", where ours are for remote users. Even if we validated all of your messages now, we can't vet them every time you make changes.  We just want the raw data and we'll make sure what we send to the client is appropriate.

Prior discussion for reference: https://github.com/aspnet/Security/pull/845#issuecomment-221709584

**Comment by polita** [comment]
Done with #479.

**Comment by Tratcher** [comment]
Milestone Backlog? What release was this in?

**Comment by brentschmaltz** [comment]
@Tratcher 5.1.0
