### ISSUE TITLE
Double space in error message IDX10214

### ISSUE THREAD

**Issue by bgever** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#426]
The error message [IDX10214](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b2f7484d3bf6786e355922b113d27ca06d0cc2ba/src/common/ErrorMessages.cs#L59) contains a double space, inconsistent with error message IDX10205. Occurs in both the 4.x and 5.x branches.

Noticed this when creating unit tests checking both these messages.

Will submit a PR shortly.

**Comment by brentschmaltz** [comment]
@bgever thanks, will wait for your PR

**Comment by bgever** [comment]
Note, the PR is for 4.x (dev branch), the same issue is also in 5.x, do I need to make another PR to the KDev branch?

**Comment by tushargupta51** [comment]
@bgever Yes, please.

**Comment by bgever** [comment]
Submitted PR #437 for 5.x.

**Comment by tushargupta51** [comment]
Thanks @bgever .

**Comment by bgever** [comment]
Thanks for accepting the PRs. :smile:
