### ISSUE TITLE
Update Json.NET to 9.0.1

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#431]
It has support for netstandard with removes the need for using imports in project.json files
We are updating all ASP.NET repositories to this version, given that some of our projects have a transitive dependency to Json.NET from this library it would be good if it can be updated here. See https://github.com/aspnet/Security/pull/867#issuecomment-224014808 for more details.

**Comment by Eilon** [comment]
@polita @brentschmaltz @tushargupta51 FYI we would like to get this in ASAP because all the new stuff is standardizing on this version of Json.NET.

**Comment by polita** [comment]
@Eilon @javiercn We're on it. Should be done today.

**Comment by brentschmaltz** [comment]
@Eilon @javiercn just pushed *-rc3-306061321 to our myget feed.
https://www.myget.org/F/azureadwebstacknightly/api/v3/index.json

**Comment by Eilon** [comment]
Thanks!
