### ISSUE TITLE
Test and document how we handle unicode mapping

### ISSUE THREAD

**Issue by polita** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#442]
Let's do this during escrow.

**Comment by brentschmaltz** [comment]
The JSON https://tools.ietf.org/html/rfc7159 specification defines a text mappings.

Section https://tools.ietf.org/html/rfc7159#section-8 describes equivalency classes of characters. 
We should she how this applies to our string comparisons such as: audience comparisons when validating tokens.
