### ISSUE TITLE
Strong name validation failed (Exception from HRESULT: 0x8013141A)

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#445]
The latest IdentityModel packages are completely broken on .NET Desktop, likely because they now use delay signing:

> sn -vf Microsoft.IdentityModel.Protocols.OpenIdConnect.dll

> Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation. Tous droits réservés.

> Microsoft.IdentityModel.Protocols.OpenIdConnect.dll est un assembly à signature
différée ou dont le test de signature a été effectué

/cc @brentschmaltz @polita @tushargupta51 

@davidfowl thanks for the precious hint :clap:

**Comment by Tratcher** [comment]
@muratg @Eilon This broke our build as well.

**Comment by Eilon** [comment]
Yup, we've been talking to @brentschmaltz @tushargupta51 @polita since last night. We'll get this fixed ASAP!

**Comment by polita** [comment]
@PinpointTownes We updated the CLI and .NET references and pushed new packages. Give them a try.

**Comment by PinpointTownes** [comment]
Looks like they are not on the aspnetcidev feed yet. I'll wait a bit before giving them a try :smile:

**Comment by brentschmaltz** [comment]
@PinpointTownes were you able to build?

**Comment by Tratcher** [comment]
FYI: Our builds are passing now.

**Comment by PinpointTownes** [comment]
@brentschmaltz yep, looks like it's working, now. Thanks :+1:
