### ISSUE TITLE
How to limit accepted JWT alg values for validation?

### ISSUE THREAD

**Issue by bgever** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#449]
I could not find a way to restrict the supported signing algorithms which are checked during validation.

For instance, I only want to accept RS384 and up or HS512. So HS256 must not be accepted.

Note, there are no [unit tests](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs) covering this situation.

**Comment by polita** [comment]
Wilson supports this today. Please provide some guidance on how to do this.

**Comment by brentschmaltz** [comment]
@bgever we are just finishing up 5.2.0 in reviewing this is going to be a bit hard, you will need to overload the cryptoProvider.IsSupportAlgorithm. I suspect you would like to see something on TokenValidationParameters. Perhaps ValidSigningAlgorithms, similar to ValidIssuers. If so, can you open a new bug for that.

Look here: https://github.com/brentschmaltz/Wilson5x/blob/master/src/ValidateTokens/Program.cs#L9

**Comment by bgever** [comment]
Thanks a lot for the sample code @brentschmaltz. Now I also understand who or what Wilson was, as mentioned by @polita. 😄

In practise, we haven't seen a situation where we actually had to restrict the algorithms yet, as they haven't been marked as obsolete or insufficient. Theoretically this can still happen in future - think SHA-1. With your code sample there is at least a workaround.

Indeed your suggested `ValidSigningAlgorithms` on `TokenValidationParameters ` is what I had in mind as well and would be a great solution.

If this is on your roadmap, I don't see a need to report it as a new issue, but if you prefer this for tracking, I'm happy to open a new one.

**Comment by brentschmaltz** [comment]
@bgever it would be great if you would open the issue. It is good to show that customers are looking for such a feature, helps in triage.
