### ISSUE TITLE
Add ConfigureAwait to avoid deadlock

### ISSUE THREAD

**Issue by ChenYan98** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#450]
The same issue has been mentioned in #301

**Comment by tushargupta51** [comment]
Talked to @brentschmaltz about this, we don't have a repro ATM, moving this to 5.0.1.

**Comment by ChenYan98** [comment]
Fixed in 5.0.1.
In general, using .Result is always a bad idea and should never be used...ever. even with the fix, using .Result could cause a deadlock.
If you really need .Result, you should try the following code as by default ConfigurationManager uses WebClient, which exhibits issues with .Result.
`HttpClient httpClient = new HttpClient(); var configManager = new ConfigurationManager<OpenIdConnectConfiguration>(authority, httpClient); var config = configManager.GetConfigurationAsync().Result;`

**Comment by tushargupta51** [comment]
@ChenYan98 The requirement of specifying `HttpClient` is only for 4.x wilson, right? If I recall correctly, 5.x uses HttpClient by default and not WebClient?

**Comment by ChenYan98** [comment]
@tushargupta51 You are right, 5.x should not have this problem since HttpClient used as default.
