### ISSUE TITLE
JwT Token Signature Validation with RSA Signing Keys Fails 

### ISSUE THREAD

**Issue by adamcode** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#455]
The implementation of JsonWebKeySet doesn't correctly create a signing key in all cases as it doesn't correctly interpret the unsigned integer for the modulus in all cases. This means token signature validation will fail. For example if your public key is:-

{"keys":[{"kty":"RSA","kid":"SylLC6Njt1KGQktD9Mt+0zceQSU=","use":"sig","alg":"RS256","n":"AK0kHP1O-RgdgLSoWxkuaYoi5Jic6hLKeuKw8WzCfsQ68ntBDf6tVOTn_kZA7Gjf4oJAL1dXLlxIEy-kZWnxT3FF-0MQ4WQYbGBfaW8LTM4uAOLLvYZ8SIVEXmxhJsSlvaiTWCbNFaOfiII8bhFp4551YB07NfpquUGEwOxOmci_","e":"AQAB"}]}

Then the first bytes seem to be incorrectly interpreted as a signed integer as this isn't explicitly converted in this code:- 

 Modulus = Base64UrlEncoder.DecodeBytes(webKey.N)

In contrast an implementation using BouncyCastle.Math.BigInteger handles this case as it has a more explicit conversion to an unsigned integer:-

var modulus = new BigInteger(webKey.N);
var correctModulus = modulus.ToByteArrayUnsigned();

The System.Numerics.BigInteger doesn't have an equivalent unsigned method so I couldn't see a way to do this using that .Net framework class. 

I don't control the key used for signing so couldn't setup a test as this issue seems to only happen for a certain combination of bytes at the start of the modulus. However, I can share a JWT signed with this token for some verification.

**Comment by brentschmaltz** [comment]
@adamcode Can you share a JWT?

**Comment by adamcode** [comment]
Here is one that shows the issue:-

eyAidHlwIjogIkpXVCIsICJraWQiOiAiU3lsTEM2Tmp0MUtHUWt0RDlNdCswemNlUVNVPSIsICJhbGciOiAiUlMyNTYiIH0.eyAic3ViIjogInRlc3R1c2VyMkBleGFtcGxlLmNvbSIsICJpc3MiOiAiaHR0cDovL29wZW5hbS5ob25leXdlbGwuY29tOjYwODAvb3BlbmFtL29hdXRoMiIsICJ0b2tlbk5hbWUiOiAiaWRfdG9rZW4iLCAibm9uY2UiOiAiNjM2MDIyNDM5NzE4NDUyODE2Lk1tTXpOelZrWm1JdFpXVXpZeTAwTkRZd0xXRXdNell0T1RnNU1HVmxZemMyTTJRek1qVmlPVEE0T0dJdFpHSm1ZeTAwWm1JMExXSXdOV010TWpsbFpXUTNNRE16TURabSIsICJhdWQiOiBbICJmcmN1c3RvbWFwcHJlZyIgXSwgImNfaGFzaCI6ICJGMUlKU3UyRV80MTNnU21sRDdBZ3lnIiwgIm9yZy5mb3JnZXJvY2sub3BlbmlkY29ubmVjdC5vcHMiOiAiYTI5ODRkOTMtMjM5Ni00ZTE5LWI4NjEtY2YxMTZlNTIzM2M2IiwgImF6cCI6ICJmcmN1c3RvbWFwcHJlZyIsICJhdXRoX3RpbWUiOiAxNDY2NjQ3MTg2LCAicmVhbG0iOiAiLyIsICJleHAiOiAxNDY2NjUwNzg3LCAidG9rZW5UeXBlIjogIkpXVFRva2VuIiwgImlhdCI6IDE0NjY2NDcxODcgfQ.kCWJsTLVZSlGmfI6kwVW4BxFrk6fX52GDInda8GfnFNWnceGRG7r9uR_xcfHpppIgiq6PNdu_-kGMpnViYGLvWOMFLeqr-S49v4wGI2jJ5sUrM3luDlnQ5DA7IDJ4r_BUYiORqFwqbSnlRZ2pvgLSohmpZDF_ggHz0Q0SJra-lo

**Comment by brentschmaltz** [comment]
@adamcode What I am seeing here is the modulus is 129 bytes. It should be 128 bytes.
see: https://tools.ietf.org/html/rfc7518#section-6.3.1.1

If I use just the first 128 bytes the signature check succeeds.

>             var n = "AK0kHP1O-RgdgLSoWxkuaYoi5Jic6hLKeuKw8WzCfsQ68ntBDf6tVOTn_kZA7Gjf4oJAL1dXLlxIEy-kZWnxT3FF-0MQ4WQYbGBfaW8LTM4uAOLLvYZ8SIVEXmxhJsSlvaiTWCbNFaOfiII8bhFp4551YB07NfpquUGEwOxOmci_";
            var e = "AQAB";
            var modulus = Base64UrlEncoder.DecodeBytes(n);
            var modulus2 = new byte[128];
            Buffer.BlockCopy(modulus, 1, modulus2, 0, 128);
            var rsaParameters = new RSAParameters()
            {
                Exponent = Base64UrlEncoder.DecodeBytes(e),
                Modulus = modulus2
            };
            var key = new RsaSecurityKey(rsaParameters);
            key.KeyId = "SylLC6Njt1KGQktD9Mt+0zceQSU=";

**Comment by adamcode** [comment]
This will work, but I suspect the reason it is 129 is that the DecodeBytes call is incorrectly adding a sign bit to the front of the bytes. I think it would be safer to try and ensure the correct conversion from the bytes to an unsigned large integer is done rather than trim the byte.

**Comment by adamcode** [comment]
Out of interest I looked at how https://github.com/bcgit/bc-csharp/blob/master/crypto/src/math/BigInteger.cs handled the removal of the sign bit - there's a lot of code in there to both remove leading 0 bytes in the constructor and then handle the output the correct bytes in the ToByteArray method.

**Comment by brentschmaltz** [comment]
@adamcode I am thinking about this from the perspective of the decoder.  In general, a decoder does so without any idea of what it is decoding. Following the logic here: https://tools.ietf.org/html/rfc7518#section-6.3.1.1 seems to indicate the creator of the modulus should only add the significant 128 bytes. You could argue for RSA, it's obvious that it should be 128. Such assumptions make interrop difficult.

**Comment by brentschmaltz** [comment]
closing as we think this is the issuers responsibility not the consumer.
