### ISSUE TITLE
Renaming branches

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#459]
Now that we have released 5.x version, we are going to rename some of the branches.

**5.x**
KDev -> dev
KRelease -> release

**4.x**
dev -> dev4x

This will give errors if you have a local clone and you do "git pull" as there will be no remote tracking branch for KDev.

```
$ git pull upstream KDev
fatal: Couldn't find remote ref KDev
```
To fix this, you can fetch from the upstream and merge the old branch (KDev) into the new one (dev).

```
git fetch upstream
git checkout dev
git merge KDev
```

We plan to do this by end of Monday, July 4, 2016.

**Comment by tushargupta51** [comment]
cc: @brentschmaltz @polita @ChenYan98 @PinpointTownes @bgever @korroz @sandorfr @brockallen @leastprivilege @Tratcher

**Comment by PinpointTownes** [comment]
Great. The previous branching strategy was a real mess :+1:

**Comment by brentschmaltz** [comment]
thanks guys.

**Comment by bgever** [comment]
Thanks for the heads-up.
