### ISSUE TITLE
JSON Web Encryption (JWE) support

### ISSUE THREAD

**Issue by mmariano** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#46]
Can you please implement JWE support? I have a requirement for using this and it is not available. It also seems pretty common to use JWT and JWE together (for example OpenID Connect spec). So this would be really helpful. Thank you!

**Comment by mmariano** [comment]
@brentschmaltz: Any update on this? We ended up encrypting the json using our own technique. It works fine but we needed to explain to external clients how to decrypt. It would of been better to use standard JWE. Thanks again for help.

**Comment by brentschmaltz** [comment]
JWE is a planned work item, no dates yet.
Ist step is a refactoring to move the JSON processing currently JWS (and then JWE) out of the JWTSecurityTokenHandler and into a layer below that other stacks can use. Same strategy is planned for SamlSecurityTokenHandler, isolate the crypto.

**Comment by brentschmaltz** [comment]
We have support for 'dir'. Closing as additional releases will add additional modes.
