### ISSUE TITLE
TokenValidationParameters namespace change impacts OpenIdConnectAuthenticationOptions

### ISSUE THREAD

**Issue by chriswill** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#466]
I understand that TokenValidationParameters has moved from System.IdentityModel.Tokens to Microsoft.IdentityModel.Tokens in the 5.0.0 release.

However the class Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions has a property called TokenValidationParameters which references System.IdentityModel.Tokens.TokenValidationParameters.  It's current version is 3.01 and has not been updated to reflect the namespace change.  The last update was Feb, 2015.

This means that 5.0.0 breaks an existing installation of Microsoft.Owin.Security.OpenIdConnect.

Are you aware of any plans to update that library? I had to roll back to get my app working again.

**Comment by tushargupta51** [comment]
@chriswill Katana (Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions) does not support Wilson 5.x and there are no current plans to update 3.0.1 to use wilson 5.x. You need to switch to new asp.net core to get this support: https://github.com/aspnet/Security

**Comment by leastprivilege** [comment]
That will be problematic.

I already heard reports of users where the Katana JWT bearer MW clashes with some other lib that depends on v5.

**Comment by brentschmaltz** [comment]
@leastprivilege @chriswill an issue needs to be opened against Katana. @leastprivilege can you post here a link to the issue folks are seeing. I recently moved a project from Wilson4.x to Wilson5.x the changes were small.

**Comment by leastprivilege** [comment]
e.g.

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/94

**Comment by Tratcher** [comment]
https://katanaproject.codeplex.com/workitem/464
