### ISSUE TITLE
Standardize package names.

### ISSUE THREAD

**Issue by Zoltu** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#467]
It took me about 30 minutes to figure out that `System.IdentityModel.Tokens.Jwt` is part of the latest .NET Standard compatible release for this project.  Almost all of the `System.*` stuff from Microsoft has been renamed to `Microsoft.*` including most of the stuff hosted here.  Unfortunately, it appears that `JWT` and `SAML` somehow missed the boat which lead me to quite a bit of confusion since I was able to find `Microsoft.IdentityModel.Tokens` but I couldn't find `Microsoft.IdentityModel.Jwt` on NuGet.

I can appreciate the desire for backwards compatibility, but I think that when all of ASP.NET moved namespaces would have been a good time to also move this stuff (since it is primarily used in ASP.NET applications).  I'm not sure if that ship has already sailed, but as a user consistency in naming provides great value as it makes it easy for me to locate things and also makes it clear to me how things are grouped together.  When I see `System.IdentityModel.Tokens.Jwt` and `Microsoft.IdentityModel.Tokens` I don't think those two are related and so I continue searching.

Also, with all of the .NET Standard stuff increasing confusion in the ecosystem (trying to figure out what I can use on NetCore and what I can't), having things left in the `System.*` namespace is a hint to me that it hasn't been migrated to NETStandard and therefore may not work for me.  By having these two packages left behind further increased my confidence that the ones I was looking at wouldn't work in NETCore.

**Comment by brentschmaltz** [comment]
@Zoltu this is great feedback. We had to pick a 'we think this will hurt fewer folks' option. We would have liked to leave everything in System.xyz, but we received feedback from users wanting to use System.IdentityModel.Tokens forced a change from System.IdentityModel.Tokens -> Microsoft.IdentityModel.Tokens. System.IdentityModel.Tokens.Jwt has millions of downloads. We wanted to keep that ns and assembly name for users searching nuget. Nuget.org doesn't allow for aliasing of package names yet.
