### ISSUE TITLE
RSASecurityKey constructors issue

### ISSUE THREAD

**Issue by pieromm80** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#469]
Hi, I'm trying to create a new RSASecurityKey object, but I'm obtaining a weird behaviour
My code looks like this:
`using Microsoft.IdentityModel.Tokens;`
`using System.Security.Cryptography;`
`...`
`RSAParameters Parameters = new RSAParameters()`
`            {`
               `Modulus = /*my key*/,`
                `Exponent = /*my exponent*/,`
`            };`
            `RsaSecurityKey Key = new RsaSecurityKey(Parameters);`

It tells me:
`The type 'RSAParameters' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Security.Cryptography.Algorithms, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`
But `RSAParameters` is a class from `System.Security.Cryptography` and also the constructor's signature says it.
 Moreover `System.Security.Cryptography.Algorithms` doesn't support the version 4.5 of the dotnet framework.
If I try to use the alternative constructor `public RsaSecurityKey(RSA rsa)` it gives me the same error...
Any suggestion?

**Comment by brentschmaltz** [comment]
@pieromm80 what version of .net are you targeting? 4.5.1 is the min version. Can you share your project.json?

**Comment by pieromm80** [comment]
Thanks for the answer, I'm using 4.5 I'll try with 4.5.1 and look if it works properly

**Comment by pieromm80** [comment]
It was a matter of framework version, with 4.5.1 everything is ok! Thanks!

**Comment by polita** [comment]
Closing
