### ISSUE TITLE
System.IdentityModel.Tokens.Jwt 5.0.0 dependencies

### ISSUE THREAD

**Issue by gerbenvl** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#473]
Hi,

In version 5.0.0 of System.IdentityModel.Tokens.Jwt there is a dependency introduced on Microsoft.IdentityModel.Tokens. Lot's of things break because of that. Is this dependency really correct? The 5.0.0-rc1 and before didn't have this one. I always learned that Microsoft.IdentityModel.Tokens is the namespace/dll from the deprecated WIF 3.5 version?

Thanks!

**Comment by brentschmaltz** [comment]
@gerbenvl we introduced an updated Microsoft.IdentityModel.Tokens.dll that is not the same as WIF 3.5 version. I believe -rc1 did have the dependency.

**Comment by gerbenvl** [comment]
Ok thanks. But then even more things will break in our software. Can I find a changelog / release notes somewhere?

Or what's the strategy? Where is this version 5.0.0 meant for compared to version 4?

Thanks!

**Comment by tushargupta51** [comment]
@gerbenvl You can find the changelog here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/CHANGELOG.md
