### ISSUE TITLE
Add support for frontchannel_logout_supported and frontchannel_logout_session_supported in OpenIdConfiguration

### ISSUE THREAD

**Issue by will-bartlett** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#474]
See: http://openid.net/specs/openid-connect-frontchannel-1_0.html.

**Comment by polita** [comment]
@brentschmaltz, please clarify the feature request.

**Comment by brentschmaltz** [comment]
@will-bartlett are you asking for new properties on OpenIdConfiguration?

**Comment by will-bartlett** [comment]
Yes.

**Comment by brentschmaltz** [comment]
@will-bartlett have these properties been added to AAD Discovery?

**Comment by leastprivilege** [comment]
Why would the AAD disco document be the reference here? they are in the spec the OP linked.

**Comment by brentschmaltz** [comment]
it certainly makes sense to follow the spec. 
I was wondering if AAD supported them, so we would have an endpoint to test against (and if we got the names right).

**Comment by leastprivilege** [comment]
maybe you should setup IdentityServer and Openiddict - so you have something spec compliant to test against ;)

**Comment by will4274** [comment]
@brentschmaltz frontchannel_logout_supported is advertised from both endpoint. frontchannel_logout_session_supported is not advertised because... we don't support it :) and so the default value of false is implied by the spec.
