### ISSUE TITLE
Wilson and API convergence

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#476]
The CoreFX team is currently working hard to make the "API convergence" plan a reality, which will make existing apps must easier to port (good news: all the signature formatter/deformatter classes will be back as part of these changes: https://github.com/dotnet/corefx/issues/9990).

https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/

Does the Azure AD team have a similar plan for Wilson? IMHO, it would be **extremely disappointing** if IdentityModel was the only .NET stack offering a poor migration path from .NET Desktop to .NET Core.

Related topic: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/327#issuecomment-162992208

/cc @brentschmaltz @polita @vibronet

**Comment by brentschmaltz** [comment]
@PinpointTownes I am investigating where dotnet core is currently on crypto.

**Comment by PinpointTownes** [comment]
@brentschmaltz your [other post](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/395#issuecomment-252021815) gives me the impression you're not going to do anything for the API convergence plan. Am I right?

**Comment by brentschmaltz** [comment]
@PinpointTownes we can't blindly pull in API's as they were in .Net 3.5. I am not drawing a line in the sand and saying NO, rather we have to be selective. The world has changed and our understanding of the API's that make sense is much crisper than in 2006 when IdentityModel was conceived. I agree, developers would be best served with a converged API set. Our first goal was ensuring support for ASP.NET V5. After 1.1 (November) we can start thinking about priorities and resourcing w.r.t. convergence.

On the GetAsymmetricAlgorithm / GetSymmetricAlgorithm I don't see this OM on a SecurityKey. Although perhaps through CryptoFactory might make sense.

**Comment by PinpointTownes** [comment]
> @PinpointTownes we can't blindly pull in API's as they were in .Net 3.5. I am not drawing a line in the sand and saying NO, rather we have to be selective. The world has changed and our understanding of the API's that make sense is much crisper than in 2006 when IdentityModel was conceived.

I'm not suggesting bringing back the entire IM stack (e.g I'm not sure it would be worth reviving `System.IdentityModel.Services`).

My demands are limited to primitive types/methods like `GetAsymmetricAlgorithm`/`GetSymmetricAlgorithm`/`IsSupportedAlgorithm`, that can be easily implemented and are highly susceptible of being used by third party code. Types like `SecurityKeyIdentifier` and `SecurityKeyIdentifierClause` could also be nice to have (tho I agree they were difficult to use).

> On the GetAsymmetricAlgorithm / GetSymmetricAlgorithm I don't see this OM on a SecurityKey. Although perhaps through CryptoFactory might make sense.

If you believe `CPF` is a better place, I won't fight for that. But note it might have usability concerns: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/453#issue-160535145

**Comment by brentschmaltz** [comment]
@PinpointTownes looks like we are converging, Study time is needed on the .Net crypto plan, so I can see where they are headed. I should have some time after we get the first cut at JWE out. We want to get that out for preview1, so we have time for feedback before 1.1 goes out.

**Comment by brentschmaltz** [comment]
@PinpointTownes I want to clarify for IdentityModel OM / API's. We don't have any plans to support a platform scenario such as: write code against Desktop and it will compile and run against Core. I hope I am clear on that. If we are missing Desktop OM / API in Core that are helpful such as GetAsymmetricAlgorithm, we are open to discussing them as they come up. This one seems helpful. We have no plan-of-record to move Core OM / API into Desktop. Which would allow for Core code to compile and run on Desktop as some other parts of .Net have.

**Comment by PinpointTownes** [comment]
> I hope I am clear on that.

You are. It's just extremely deceiving to see that IM is the only stack that won't be part of the API convergence plan for .NET Standard 2.0 :-1:

**Comment by brentschmaltz** [comment]
@PinpointTownes our long term goal is to have code written against .Net CORE compile and run against .Net Desktop. We haven't been able to commit to the .Net Standard 2.0 timeline. However, this remains a long term goal.

**Comment by brentschmaltz** [comment]
closing for now till POR is established.

**Comment by PinpointTownes** [comment]
Any news? :smile:

**Comment by brentschmaltz** [comment]
@PinpointTownes nothing concrete

**Comment by thuannguy** [comment]
I have a big product which relies heavily on System.IdentityModel. I want to migrate it to the Core stack but the lack of IdentityModel support makes it an impossible task for me :(

**Comment by brentschmaltz** [comment]
@thuannguy we have added support for Saml2, Saml1, WsFed (not fully compatible) in to our 5.2.0 release which has 45, 451 and netstandard1_4 targets. 5.x already had support for OAuth2/OIDC.

System.IdentityModel does not have support for OAuth2/OIDC.

Please open an issue for WsTrust support here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet . See: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/759 for expanding WsFed support. 

Can you expand on your Async needs?

**Comment by thuannguy** [comment]
Thank you :) I have been watching [azure-activedirectory-identitymodel-extensions-for-dotnet](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues) closely. Hope that one day it will be mature enough to replace the current System.IdentityModel.

Regarding OAuth2/OIDC: yep, it is irrelevant in this context. I use another 3rd library to implement OIDC server.

WS-Trust support request: sure, I will open an issue for supporting it.

Async: My application has entry point for all SSO requests:

`
    public class MyGatewayController : Controller
    {
        ActionResult EntryPointOfMyGateway()
        {
            return ALongPipeline.ResolveAction();
        }
    }
`

The ResolveAction method can return many different ActionResult, but many of them look like the below:


`
    public class MyActionResult : ActionResult
    {
        public override void ExecuteResult(...)
        {
            // do something
            // do some network call which can be changed to use Async
            // process result
        }
    }
`

I think I really need the ExecuteResultAsync method supported by Asp.Net core :)
