### ISSUE TITLE
Only use the Payload of the JWT when checking for Token Replay

### ISSUE THREAD

**Issue by remyblok** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#478]
I had asked a question on StackOverflow regarding JWT token signatures not to be unique: http://stackoverflow.com/questions/38508522/why-is-a-jwt-signature-not-unique-for-a-specific-payload.

Based on the answer that the signature does not have to be unique for a given payload (in some cases), I think that when checking the token for Replay only the Payload-part should be checked. Now when calling the `Validators.ValidateTokenReplay` in the `JwtSecurityTokenHandler` the entire JWT token is send, including the signature part. This makes it possible that tokens with a certain payload can be replayed by changing the signature. 

It is possible to extract the payload from the JWT in the implementation of the `ITokenReplayCache`, but this is not something that is logical to do and is not something I would expected. Only verifying the Payload for replay 'protects' developers from this issue. Alternatively only send the jti-claim when it is supplied.

**Comment by brentschmaltz** [comment]
@remyblok See answer on SO. he JwtSecurityTokenHandler calls TokenValidationParameters.TokenReplayCache with the JWT  after signature validation.

**Comment by remyblok** [comment]
@brentschmaltz Thank for answering. I do not believe your answer is correct. I also added an comment to the SO thread.

Basically it boils down to that there a multiple signatures possible for the same payload. All these signatures validate the payload, so there is not integrity issue with the payload. But for replay attacks this means that you could replay the payload simply by changing the last character of the signature. This is not save. Therefor I suggest to send only the payload to the TokenReplayCache, this way the replay cache only validates the parts that matter, the payload and leave the signature out altogether.
