### ISSUE TITLE
RsaSecurityKey.HasPrivateKey throws a NotSupportedException when the underlying algorithm instance is a RSACng on .NET Desktop

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#480]
``` csharp
System.NotSupportedException: Méthode non prise en charge.
   à System.Security.Cryptography.RSA.DecryptValue(Byte[] rgb)
   à Microsoft.IdentityModel.Tokens.RsaSecurityKey.get_HasPrivateKey()
```

In > .NET 4.6, `RSA.DecryptValue` and `RSA.EncryptValue` are considered as "obsolete" (which is a very debatable choice, IMHO) and are now virtual instead of abstract. It wouldn't be a big deal if `RSACng` implemented them... but it does not. The sad news is that IdentityModel can't handle `RSACng`-based keys on .NET Desktop as it uses `RSA.DecryptValue` to "determine" if there's a private key (I guess IM 4.5 Desktop is similarly impacted).

Ideally, we should use `Decrypt(byte[] data, RSAEncryptionPadding padding)` or `SignData(byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)` but these APIs are not part of .NET 4.5. One option might be to re-target IM 5 to require .NET 4.6. Another one is to use reflection to use these new APIs when they exist.

Reference: http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/rsa.cs,193

/cc @brentschmaltz @polita

**Comment by brentschmaltz** [comment]
@PinpointTownes

**Comment by brentschmaltz** [comment]
fell on the mouse, accidentally closed.

**Comment by brentschmaltz** [comment]
@PinpointTownes another possibility is to have a 4.6.3 target in addition to 4.5.1 and Core 1.0. Are you up to date on Reflection on Core? Could it be used?

**Comment by PinpointTownes** [comment]
> @PinpointTownes another possibility is to have a 4.6.3 target in addition to 4.5.1 and Core 1.0.

Yep, that's a (non-breaking) option.

> Are you up to date on Reflection on Core? Could it be used?

It would certainly work on .NET Core, but not sure about .NET Native (because using reflection is generally more problematic with AOT). That said, I'm not sure Wilson supports .NET Native (yet), so it may not be an issue.

**Comment by brentschmaltz** [comment]
@PinpointTownes I commented on 12623, We will need another target 4.6.2 and fault for 4.6.1 and below when RSA doesn't resolve to RSACryptoServiceProvider. I am not sure reflection is the answer. Maybe @bartonjs has a cleaver idea.

**Comment by bartonjs** [comment]
Making one target for 4.5.x (where RSACryptoServiceProvider is king) and another for 4.6 makes sense to me.

Not necessarily useful addendum 1: The underlying model for the providers seems to be to not answer if a key has private-key powers, but to say "this is nuanced.. just try it and see if it works".  For example, you could have a key that is permitted for signing, but not decryption, so "has (a) private key" is not a true indicator (If false you know it will fail, if true you don't know until you try).

Not necessarily useful addendum 2: I've heard (though not personally seen the data) that .NET 4.6.1 is currently the most-deployed version, so maybe it's finally time to start dropping 4.5.x scenarios.

**Comment by PinpointTownes** [comment]
@brentschmaltz sounds good (tho' I'm not sure why you need to fault on 4.6.1, as the API you need are supposed to be present in 4.6).

> maybe it's finally time to start dropping 4.5.x scenarios.

@bartonjs unfortunately, the ASP.NET Core packages that rely on IdentityModel target .NET 4.5.1, so dropping 4.5.x would have to be a "global" decision.

**Comment by brentschmaltz** [comment]
@PinpointTownes yes, we should use the correct target, @bartonjs what target has all the CNG we need?
@bartonjs echoing pinpoint, asp.net needs 4.5.1 support.

**Comment by bartonjs** [comment]
@brentschmaltz Base class refreshes were RSA: 4.6(.0), ECDSA: 4.6.1 DSA: 4.6.2  (You should still be able to test for the ability to sign with DSA on 4.6, 4.6.2 added FIPS 186-3 support)

**Comment by brentschmaltz** [comment]
@PinpointTownes @bartonjs do you think a 4.6.1 target would be OK. I am thinking RSA / ECDSA priority over DSA.

**Comment by brentschmaltz** [comment]
@bartonjs I agree that evidence of a 'private' key is not sufficient to determine success of a crypto operation such as signing or decrypting. It is necessary though. Idea is to fail early, when it is obvious.

**Comment by bartonjs** [comment]
> do you think a 4.6.1 target would be OK

That's what netstandard 2.0 is based on.

> Idea is to fail early, when it is obvious. 

I'm not saying I disagree -- just that the provider models that we're based on don't necessarily want to expose this information, so it's hard to expose it well from the implementation-independent layer (without taking the perf hit of trying to sign or decrypt something on every key load to answer the question, which could end up popping UI for protected keys).

**Comment by brentschmaltz** [comment]
> which could end up popping UI for protected keys
@bartonjs this makes sense, particularity when thinking about remote services such as KeyVault.
If consent is required, wouldn't that logic get executed before using the private Key? 
Are you recommending to forgo such checks and let the call fail when executed?

**Comment by bartonjs** [comment]
> Are you recommending to forgo such checks and let the call fail when executed?

Yeah.  Things like `cert.HasPrivateKey` are reasonable to check (since it's already provided and won't pop UI), but I wouldn't go spelunking on a key handle.  Just request the operation when needed, and let the chips fall where they may.  (If that changes your exception model then maybe you need something more complicated; but it's at least how I'd start tackling the problem)

**Comment by brentschmaltz** [comment]
@PinpointTownes would you be OK with deferring the HasPrivateKey for the ctor RSASecurityKey(RSA rsa) ?
This would workaround your current issue.

**Comment by PinpointTownes** [comment]
@brentschmaltz hum, I'm not sure to understand how this would solve this issue. Do you mean you want `HasPrivateKey` to return `true` without even making a real check?

**Comment by brentschmaltz** [comment]
@PinpointTownes Yes, the issue since the apis are not available for 4.5.1. Other wise we would have to do some seemingly messy checks.

bartonjs recommended only checking when it makes sense.

**Comment by PinpointTownes** [comment]
> @PinpointTownes Yes, your issue occurs as apis are not available for 4.5.1. Other wise we would have to do some seemingly messy checks.

Well, the most sensible way to fix that is to add a `net461` target, or use reflection to call the new RSA methods.

I don't think lying and returning an invalid result is the right answer here. If an app or a library uses `HasPrivateKey`, it likely expects a correct result.

**Comment by brentschmaltz** [comment]
Adding a net461 target won't help download .net users. HasPrivateKey is really of limited use and gets in the way more than it helps.

**Comment by PinpointTownes** [comment]
I still don't understand how doing that would help, really. Even if you work around this issue in `RsaSecurityKey`, `HasPrivateKey` is not the only place that is incompatible with `RSACng`. The entire `AsymmetricSignatureProvider` class doesn't work well with non-`RSACryptoServiceProvider` instances on .NET Desktop: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs#L600-L605

**Comment by brentschmaltz** [comment]
There must be a target mismatch going on here were newer .Net objects are passed to IdentityModel.
Is that what is going on?

**Comment by brentschmaltz** [comment]
Moving to 5.1.4

**Comment by ohadschn** [comment]
Is there a recommended workaround? Basically this fails:

```cs
var key = CngKey.Import(Convert.FromBase64String(PrivateKey), CngKeyBlobFormat.Pkcs8PrivateBlob);
var rsaSecurityKey = new RsaSecurityKey(new RSACng(key));
new JwtSecurityTokenHandler().CreateJwtSecurityToken(
  issuer: "foo",
  audience: "https://foo.com",
  subject: new ClaimsIdentity(),
  notBefore: null,
  expires: DateTime.UtcNow.AddSeconds(50),
  issuedAt: null,
  signingCredentials: new SigningCredentials(rsaSecurityKey, SecurityAlgorithms.RsaSha256),
  encryptingCredentials: null);
```

```
   System.NotSupportedException: 'NotSupported_Method'
   at System.Security.Cryptography.RSACng.DecryptValue(Byte[] rgb)
   at Microsoft.IdentityModel.Tokens.RsaSecurityKey.get_HasPrivateKey()
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.HasPrivateKey(SecurityKey key)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForSigning(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityToken(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials)
```

**Comment by brentschmaltz** [comment]
@PinpointTownes @ohadschn Kevin is correct, we have to address this.

Have you tried this ctor? https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/RsaSecurityKey.cs#L45

**Comment by PinpointTownes** [comment]
@brentschmaltz the real question is... do you envision a fix within the next 2 years? I reported this bug more than a year ago :sweat_smile:

**Comment by ohadschn** [comment]
@brentschmaltz thanks for the tip! Looks like this is working:

```cs
var key = CngKey.Import(Convert.FromBase64String(PrivateKey), CngKeyBlobFormat.Pkcs8PrivateBlob);
key.SetProperty(new CngProperty("Export Policy", 
	BitConverter.GetBytes((int) CngExportPolicies.AllowPlaintextExport), 
	CngPropertyOptions.Persist));
var rsaSecurityKey = new RsaSecurityKey(new RSACng(key).ExportParameters(true));
var handler = new JwtSecurityTokenHandler();
var token = handler.CreateJwtSecurityToken(
    issuer: "foo",
    audience: "https://foo.com",
    subject: new ClaimsIdentity(),
    notBefore: null,
    expires: DateTime.UtcNow.AddSeconds(50),
    issuedAt: null,
    signingCredentials: new SigningCredentials(rsaSecurityKey, SecurityAlgorithms.RsaSha256),
    encryptingCredentials: null);
```

**Comment by brentschmaltz** [comment]
@ohadschn glad it worked.
@PinpointTownes fair enough. POR is to get this into 5.2.0 release.

**Comment by brentschmaltz** [comment]
@PinpointTownes @lovemaths  Perhaps we need a new API that has a tri-state. Yes/No/Donotknow. Then we can fault on No. What I want to change is any attempted use of the key as we are assuming a specific crypto provider and using the one associated with the key. I am in favor with what Jermery suggested, it looks like trying to help users fail early doesn't actuallly help in this case.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/778

**Comment by PinpointTownes** [comment]
I'm not opposed to having new APIs, but the "fix" you ended up implementing is just abominably wrong:

  - It does not fix the original API so any app using it won't get any benefit from this "fix" when moving to the latest IM bits.

  - The new API uses `ExportParameters(true)` to determine whether there's a private key or not. This is wrong because this will always fail with non-exportable software keys and hardware keys (e.g when the key is in a Smart Card or in a HSM).

Please consider re-opening this ticket as the original demand was not satisfied (IM is still badly broken).

Cumulative things you should do to fix that:

  - Revert the PR.

  - Update `HasPrivateKey` to use reflection to determine whether the new RSA APIs exist and call them instead of blindly using the deprecated `DecryptValue` method.

  - Consider adding a new TFM so you can directly use the new APIs without reflection.

Then, you'll still be able to add new APIs. I don't think the one you added is ideal. Instead, you may consider adding more precise APIs:

```csharp
public bool? CanDecrypt { get; } // true = yes, false = no, null = unknown.

public bool? CanEncrypt { get; } // true = yes, false = no, null = unknown.

public bool? CanSign { get; } // true = yes, false = no, null = unknown.

public bool? CanVerify { get; } // true = yes, false = no, null = unknown.
```

**Comment by brentschmaltz** [comment]
@PinpointTownes please feel free to open an issue (again) for a new TFM for 4.6.0+.

We are addressing #675 #581 #488 and will fix this code at the same time https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/ECDsaSecurityKey.cs#L72
As this is clearly not a good idea, given we don't know where the key lives.

I considered using bool?, but landed on an enum as it seemed to read better.
So we are still not done here. I am investigating what happens when a user has a 4.5.1 target, then .Net gets upgraded to 4.6.1. We still have work to do.

**Comment by PinpointTownes** [comment]
> @PinpointTownes please feel free to open an issue (again) for a new TFM for 4.6.0+.

I'm fine doing that, but this ticket should be re-open to fix the existing API on existing targets.

> I considered using bool?, but landed on an enum as it seemed to read better.

Actually, it could even be a `bool`, because the decrypting/encrypting/signing/verifying operation either fails or succeeds (there's no intermediate state).
