### ISSUE TITLE
Nuget package for 5.x does not handle Katana or ASP.NET 4.x well

### ISSUE THREAD

**Issue by CodeCharm** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#481]
The 5.0 Nuget `System.IdentityModel.Tokens.Jwt` package will appear in the Visual Studio Nuget Package Manager as an upgrade to 4.x. However, an existing Katana (OWIN) or ASP.NET 4.x project that depends on these assemblies may not be able to use the upgrade without breaking.

The Nuget package (at https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/5.0.0 as of this report) does not have a Project Url entry, nor any straightforward way to discover the [changelog](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/CHANGELOG.md).

I'll be honest; I don't know exactly what all the dependencies should be. I just know that a notification from the PM that a package can be upgraded, even a major version release, should not require me to do a wholesale upgrade of my project to a new version of the platform (it's similar in concept of moving from .NET 2.x to .NET 4.x) without due warning. Hiding the warning in a changelog that is not easily discoverable is kinda uncool.

I'd be happy to help, but I'm not a Nuget ninja, and I would likely break a lot of stuff.

**Comment by brentschmaltz** [comment]
@CodeCharm We need to add the ProjectUrl. 

You are not the only one to hit this. We cover this in readme.md 
We should add stronger and easier found text to help users understand 5.0 is a major change.

**Comment by brentschmaltz** [comment]
@CodeCharm https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/595 we plan a coordinated release with Katana that will use the 5.2.0 release to address this issue.
