### ISSUE TITLE
JwtSecurityTokenHandler.CanReadToken() does not check if each part is a base64url-encoded value

### ISSUE THREAD

**Issue by neverendingqs** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#482]
As per https://tools.ietf.org/html/rfc7519#section-3:

> A JWT is represented as a sequence of URL-safe parts separated by
   period ('.') characters.  Each part contains a base64url-encoded
   value.

[JwtSecurityTokenHandler.CanReadToken()](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a18c4d6fbef3a48cd734bd8a027fdb9013b27c3e/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L319) does not appear to check if each part of the token is base64. Because of this, when [JwtSecurityTokenHandler.ReadJwtToken()](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a18c4d6fbef3a48cd734bd8a027fdb9013b27c3e/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L319) is called, it eventually reaches [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a18c4d6fbef3a48cd734bd8a027fdb9013b27c3e/src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs#L331) or [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a18c4d6fbef3a48cd734bd8a027fdb9013b27c3e/src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs#L349), causing an `ArgumentException` to be thrown.

Steps to reproduce:

```cs
/*
    // throws FormatException
    JwtHeader.Base64UrlDeserialize( "1" );

    // does not throw
    JwtHeader.Base64UrlDeserialize( "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9" );
*/

JwtSecurityTokenHandler tokenHandler = new JwtSecurityTokenHandler();

const string token = "1.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ";
// or "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.1.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"

// returns true
Console.Out.WriteLine( tokenHandler.CanReadToken( token ) );

// Throws ArgumentException
var jwtToken = tokenHandler.ReadToken( token );

**Comment by polita** [comment]
@neverendingqs CanReadToken() does check to ensure it's well-formed: that it's a three-part string, dot-separated, and each segment is base64Url encoded. It just turns out that "1" is a valid base64Url encoded value. CanReadToken is meant to be a lightweight call to ensure it has the right form for a JWT token. If you need to know if the JWT token is well-formed, parsable json, you can do that with ReadToken, which is a more expensive call.

If you have a scenario that this is blocking, please send us a few more details so we can understand it.
