### ISSUE TITLE
JsonWebKeyECTypes.P512 doesn't correspond to a standardized named curve

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#486]
`P512` is likely a typo, as there's no such curve in the DSS spec: http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf

Instead, it should be named `P521` and the constant value should be `P-521`. Since the existing values are invalid, I'd recommend removing them in the next version.

https://tools.ietf.org/html/rfc7518#section-6.2.1.1

/cc @brentschmaltz @polita

**Comment by polita** [comment]
Fixed.
