### ISSUE TITLE
Introduce native support for raw ECDSA keys in JsonWebKeySet.GetSigningKeys()

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#487]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/62 was closed, but AFAICT, raw ECDSA keys are still not supported in the latest bits:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/JsonWebKeySet.cs#L103

Wilson should target .NET Standard 1.6 and use `ECDsa.Create(ECParameters)` to create new ECDSA keys from EC-based JWKs.

/cc @brentschmaltz @polita

**Comment by brentschmaltz** [comment]
@aarondandy @PinpointTownes I agree we need a 1.6 target.
We will see if we can fit this into our next release.

**Comment by PinpointTownes** [comment]
@brentschmaltz oh, you guys are still alive? :trollface:

**Comment by brentschmaltz** [comment]
@PinpointTownes yes sir.

**Comment by brentschmaltz** [comment]
We will get this into the June release

**Comment by brentschmaltz** [comment]
@PinpointTownes we need to push this to August 5.2.4 release.

**Comment by bearkat2173** [comment]
Please also improve the error messaging for unsupported protocols.  JwtSecurityTokenHandler currently reports
> Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: 'IDX10501: Signature validation failed. Unable to match 'kid...

It took many agonizing hours to track the issue down to JsonWebKeySet, confirming my suspicion that ECDSA is, in fact, not supported.

**Comment by brentschmaltz** [comment]
@PinpointTownes we added support in 5.4.0

**Comment by brentschmaltz** [comment]
This should not have been closed, we bumped up our ECDsa in 5.4.0, but we still need to create ECDsa from JsonWebKey. We will push this out till 5.4.1.

**Comment by PinpointTownes** [comment]
That was an unfortunate omission, indeed :smile:
