### ISSUE TITLE
CryptoProviderFactory.IsEcdsaAlgorithmSupported() doesn't ensure algorithms are compatible with the curves used by ECDSA keys

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#488]
`IsEcdsaAlgorithmSupported` returns `true` if the algorithm corresponds to `ES256`, `ES384` or `ES512` but doesn't ensure the curve type of the ECDSA key is compatible with the specified algorithm.

`ES256` -> `P-256` (= `ECCurve.NamedCurves.nistP256`)
`ES384` -> `P-384` (= `ECCurve.NamedCurves.nistP384`)
`ES512` -> `P-521` (= `ECCurve.NamedCurves.nistP521`)

/cc @brentschmaltz @polita

**Comment by brentschmaltz** [comment]
moving to 5.1.4

**Comment by PinpointTownes** [comment]
@mafurman why was this thread closed? I don't see in the PR diff any chance impacting the APIs mentioned in this ticket.

**Comment by brentschmaltz** [comment]
@PinpointTownes @mafurman Yes, we need a check between 'algorithm' and 'CRV'. I would argue this is not a IsEcdsaAlgorithmSupported function. As this describes what the runtime is capable of.
The check you are looking for is matching CRV with Algorithm. I think this is covered with the combination of GetKeySize and ValidateECDSAKeySize.

**Comment by PinpointTownes** [comment]
Let me remind you what the requirement is, in case you'd have missed it (well, this ticket was opened almost 2 years ago so...):

I need `CryptoProviderFactory.IsSupportedAlgorithm(string algorithm, SecurityKey key)` to return `false` if `key` is an ECDSA key AND `algorithm` an ECDSA algorithm that uses a curve different than the one associated with `key`.

**Comment by brentschmaltz** [comment]
We will add tests to make sure that contract is enforced.
