### ISSUE TITLE
Why IdentityModel Extensions for .NET 5 only works for ASP.NET Core

### ISSUE THREAD

**Issue by rosslyn-cuongle** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#489]
I am using IdentityModel Extensions for .NET 4 for our project (ASP.NET MVC 5), now  IdentityModel Extensions for .NET 5 has been released but I am not sure that I can upgrade our application to IdentityModel Extensions for .NET 5 as the mention from readme:

>IdentityModel Extensions for .NET 5 has now been released. If you are using IdentityModel Extensions with ASP.NET, the following combinations are supported:

* **IdentityModel Extensions for .NET 4.x** and **ASP.NET 4**
* **IdentityModel Extensions for .NET 5.x** and **ASP.NET Core 1.x**

>All other combinations aren't supported.

I am just curious why IdentityModel Extensions for .NET 5 only supports ASP.NET Core and cannot support ASP.NET MVC 5.

What if I use this package only for token generation and validation which is not related to ASP.NET?

**Comment by brentschmaltz** [comment]
@rosslyn-cuongle when we say ASP.NET 4, we are really speaking about using this with Katana. If you have an application that targets { ASP.NET 4, Katana } you cannot upgrade to IdentityModel 5.0, 

IdentityModel supports two runtimes. FxCore and .Net 4.5.1.

**Comment by rosslyn-cuongle** [comment]
@brentschmaltz Thanks for your answer, if we only use OWIN OpenIdConnect middleware to to authentication with Azure AD on ASP.NET MVC, is this possible to upgrade in this case?

**Comment by brentschmaltz** [comment]
@rosslyn-cuongle I just spun up an asp.net MVC specifying 4.5.1 for the .Net library and was able to include this code: 

>      public async Task<ActionResult> Index()
        {
            var configurationRetervier = new OpenIdConnectConfigurationRetriever();
            var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>("https://login.microsoftonline.com/common/.well-known/openid-configuration", configurationRetervier);
            var config = await configurationManager.GetConfigurationAsync();
            var issuer = config.Issuer;
            return View();
        }

**Comment by brentschmaltz** [comment]
@rosslyn-cuongle closing issue, let me know if you need anything else
