### ISSUE TITLE
Incorrect handling of 'exp', 'nbf' and 'iat' claim values

### ISSUE THREAD

**Issue by RussKie** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#490]
**System.IdentityModel.Tokens.Jwt: v5.0.0**

I'm building an .NET Core app for an existing large ecosystem.
.NET Core side upon receiving a JWT which works everywhere else (in the ecosystem and decoded by https://jwt.io decoder) fails with the following exception:

```
An unhandled exception occurred while processing the request.

SecurityTokenNoExpirationException: IDX10225: Lifetime validation failed. The token is missing an Expiration Time.
Tokentype: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
```

however the underlying issue is this:

```
IDX10700: Error found while parsing date time. The 'nbf' claim has value '1471924298.67746' which is could not be parsed to an integer.
```

[The offending code](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L732):

```
secondsAfterBaseTime = Convert.ToInt64(dateValue, CultureInfo.InvariantCulture);
```

The implementation is contrary to the spec: https://tools.ietf.org/html/rfc7519#section-2:

> NumericDate
>       A JSON numeric value representing the number of seconds from
>       1970-01-01T00:00:00Z UTC until the specified UTC date/time,
>       ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
>       2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
>       which each day is accounted for by exactly 86400 seconds, **other
>       than that non-integer values can be represented**.  See RFC 3339
>       [RFC3339] for details regarding date/times in general and UTC in
>       particular.

The correct behavior must process datetime represented by a `double` instead of an `long`.

**Comment by RussKie** [comment]
I half expected this to be a relatively straight forward fix until I tried to fix it myself... Oh God almighty
I'm not sure it can be easily fixed until https://github.com/dotnet/corefx/issues/11082 is fixed.

My first attempt was to make it `double`, but then `double.ToString()` (which is used a lot) [truncates the precision to 15](https://msdn.microsoft.com/en-us/library/kfsatb94.aspx#Anchor_2), which immediately causes failures.

Next I tried to convert values with "G17" format, but then `JwtPayload` uses JSON.NET to deserialise data (via `JsonExtensions`) which suffers from the same problem above - precision is truncated and values mismatch.

Then I tried using `decimal` instead of `double`, but then there is no `ClaimValueTypes.Decimal` available and again some tests fail...

A possible solution may be updating signature of [Deserializer delegate](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JsonExtensions.cs#L45) to include `JsonSerializerSettings`

```
    public delegate object Deserializer(string obj, Type targetType, JsonSerializerSettings settings);

    private static readonly JsonSerializerSettings CustomJsonSerializerSettings = new JsonSerializerSettings { FloatParseHandling = FloatParseHandling.Double };
```

This may direct JSON.NET not to truncate the precision.

I tried that too, but there is still one test failing System.IdentityModel.Tokens.Jwt.Tests.JwtSecurityTokenHandlerTests.ActorTests, which I can't seem to comprehend...

**Comment by brentschmaltz** [comment]
@RussKie what test is failing? We should fix this without relying on using extensibility. Can you help me understand how truncation effects your scenario? We can certainly add new ClaimValueTypes as we did in JsonClaimValueTypes if a solution requires it.

**Comment by RussKie** [comment]
@brentschmaltz I don't think I will have any time to provide you any more details on the problems I had until sometime next week.

But I don't think there can be a proper fix until the underlying problem (https://github.com/dotnet/corefx/issues/11082) is fixed.

**Comment by brentschmaltz** [comment]
@RussKie thanks, in the meantime I'll review dotnet/corefx#11082

**Comment by brentschmaltz** [comment]
@RussKie I am closing this as I think the solution really is: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/660

**Comment by RussKie** [comment]
We put on ice all .net core exercises and this PR has gone stale...
I still maintain your implementation is contrary to the spec.

I am not sure how you envisage for #660 to address the issue.

**Comment by brentschmaltz** [comment]
@RussKie apoligies, closed the wrong issue.

**Comment by ChenYan98** [comment]
#781
