### ISSUE TITLE
Licensing: Apache-2.0 or MIT?

### ISSUE THREAD

**Issue by tngraf** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#494]
License.txt and Readme.md indicate the Apache Software License, version 2.0 as license for the whole project. Our license scanner (FOSSology) tells us that nearly every file has an MIT license header.
It would be good to have a more transparent license information.

**Comment by brentschmaltz** [comment]
@tngraf we should clean that up.

**Comment by polita** [comment]
@tngraf Thanks for pointing this out. After much discussion, we've decided MIT is the right license. I've updated our license.txt and readme.md. Fixed with #506 and #502
