### ISSUE TITLE
OWIN Authentication issue while hitting some pages in Web Application

### ISSUE THREAD

**Issue by bharatmangal04** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#495]
OWIN Pipeline throwing exception 

at Microsoft.IdentityModel.Protocols.AuthenticationProtocolMessage.SetParameter(String parameter, String value)
 at Microsoft.IdentityModel.Protocols.WsFederationMessage..ctor(IEnumerable 1 parameters)
 at Microsoft.Owin.Security.WsFederation.WsFederationAuthenticationHandler.<AuthenticateCoreAsync>d__1f.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<BaseInitializeAsync>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware 1.d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.d__5.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
 at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
 at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

seems like issue is with in the Microsoft.Identity.Protocol.Extension.dll
[https://github.com/owin/owin/issues/53](url)

**Comment by Tratcher** [comment]
This is only the stack trace. What was the actual exception type and message?

**Comment by bharatmangal04** [comment]
its null reference exception.
Value+cannot+be+null.%0d%0aParameter+name%3a+parameter

**Comment by bharatmangal04** [comment]
I think issue keyValue.Key is passing as null.

**Comment by bharatmangal04** [comment]
I am on skype so do let me know if we can chat over there.. (bgupta@microsoft.com)

**Comment by bharatmangal04** [comment]
<h1>An unhandled exception occurred while processing the request.</h1>
                <h2 class="titleerror">ArgumentNullException: Value cannot be null.
Parameter name: parameter</h2>
                    <p class="location">Microsoft.IdentityModel.Protocols.AuthenticationProtocolMessage.SetParameter(String parameter, String value)</p>
        <ul id="header">

**Comment by polita** [comment]
@bharatmangal04 Can you tell us the version of Microsoft.IdentityModel.Protocols that you're using?

**Comment by bharatmangal04** [comment]
I am using the OWIN which include package Microsoft.IdentityModel.Protocols.Extensions.dll

**Comment by brentschmaltz** [comment]
@polita I think it is 4.x since wsFed is used.

**Comment by bharatmangal04** [comment]
@polita @ChenYan98 : Because of this issue we are not able to go live with ADFS implementation. Its impacting Client.

**Comment by bharatmangal04** [comment]
If possible, please provide some hotfix so that i can quickly check. some beta version of this DLL

**Comment by brentschmaltz** [comment]
@bharatmangal04 this faults because we are being passed a <key, value> pair where the key is null. 
We can't set this value and see it as a programming error.

**Comment by bharatmangal04** [comment]
/// <summary>
        /// Initializes a new instance of the <see cref="WsFederationMessage"/> class.
        /// </summary>
        /// <param name="parameters">Enumeration of key value pairs.</param>        
        public WsFederationMessage(IEnumerable<KeyValuePair<string, string[]>> parameters)
        {
            if (parameters == null)
            {
                return;
            }

            foreach (KeyValuePair<string, string[]> keyValue in parameters)
            {
                if (!string.IsNullOrEmpty(keyValue.Key))
                {
                    foreach (string strValue in keyValue.Value)
                    {
                        SetParameter(keyValue.Key, strValue);
                    }
                }
            }
        }

I think we need to handle like this if key is null then it should not call setparameter variable. 

I think these values originate from OWIN (Katana) framework

**Comment by brentschmaltz** [comment]
@bharatmangal04 @ChenYan98 @polita We debugged through this and the web application is creating a form with a null key. This is probably an error. However we need to think about if we should fault here as in a release product this could cause issues. On the other hand, if we don't fault we may be hiding the issue. 
A comprise may be to fault in debug environment and log an error in release.

**Comment by polita** [comment]
Since this is a programming error that @brentschmaltz and @bharatmangal04 worked through, closing this issue.

**Comment by bharatmangal04** [comment]
@polita @brentschmaltz 

Hi Polita, I would suggest to keep this issue open till we have the implementation to throw error in debug mode and log error in release mode to break the application. 

I can not reopen this so can you please reopen this.

**Comment by polita** [comment]
@bharatmangal04 My understanding is that this throws an exception with this message:
Value+cannot+be+null.%0d%0aParameter+name%3a+parameter
And this exception gets logged in release mode. Is that not true?

**Comment by bharatmangal04** [comment]
@polita : Yes, In Debug Mode: It Should throw an exception so that developer know that there is any issue with the form data.  In Release mode: It should just logged the exception and continue instead of throwing so that it will not affect the production environment.

**Comment by polita** [comment]
@bharatmangal04 It should throw the same exception in debug and release. In debug, you can catch the exception and examine the stack and debug. In release, that exception should get logged. If that's not happening, please explain the gap.

**Comment by bharatmangal04** [comment]
@polita: Here is current Gap:
WsFederationMessage(IEnumerable> parameters) Method is not catching the exception and only throwing. 

We are using the OWIN framework for WSFederation Authentication which internally calling Microsoft.Identity.Protocal.External.Dll.  As some of the data in the form has key as a null due to which we are having error and application is breaking and we don't have control on that data as well. 

WsFederationMessage(IEnumerable> parameters) Method should catch the exception and log in release mode and throw error in debug mode. 

I don't have control to make the changes in the Microsoft.OWIN.Secutity.WSFederation or Microsoft.Identity.Protocal.External.Dll.

**Comment by polita** [comment]
@bharatmangal04  Exception bubbling will ensure that the developer gets the exception and the full stack. Yes, it's possible for us to catch this particular ArgumentNullException and throw a more specific exception. However, the existing exception, coupled with the stack, should give you all the information you need to track down the null key.

We do, in fact, throw the ArgumentNullException in debug mode. In release mode, this exception will be thrown and logged. That should direct the developer to make the necessary fixes to their app to not pass a null key value.

**Comment by brentschmaltz** [comment]
@bharatmangal04 you can hook the AuthenticationFailedNotification which gives you the opportunity to examine all failures.

**Comment by bharatmangal04** [comment]
@polita @brentschmaltz , 

I do understand that but instead of throwing Exception in release mode if we can log the exception that will help to break the entire page. 

While looking the Logs we can drill down the exception in production environment.

**Comment by bharatmangal04** [comment]
I do understand that but instead of throwing Exception in release mode if we can log the exception that will help instead  of breaking the entire page. 

While looking the Logs we can drill down the exception in production environment.

**Comment by oscarhult** [comment]
@bharatmangal04, did you find a solution to this? It seems the "IsNullOrEmpty(keyValue.Key))"-check was not implemented in 1.0.4/4.0.4.

**Comment by bharatmangal04** [comment]
@oscarhult, I have taken the copy of project and filter the forms with empty key by my self.

**Comment by oscarhult** [comment]
@bharatmangal04, thank you for the quick reply and I'm sorry if this is the wrong place to discuss this issue. When modifying `WsFederationMessage.cs` my `Microsoft.IdentityModel.Protocol.Extensions.dll` receives a new publicKeyToken and will no longer be loaded.

`Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key.`

Did you rebuild every single dependancy-library aswell to get this to work or did you find a better solution?
