### ISSUE TITLE
Problem adding to a Xamarin/iOS project

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#501]
I am getting the following error in Xamarin Studio 6.1

Could not install package 'System.Security.Cryptography.Cng 4.2.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I thought Wilson is targeting netstandard 1.4 - which is according to

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

compatible with Xamarin.

**Comment by brentschmaltz** [comment]
@bartonjs can you help shed light on this?  Microsoft.IdentityModel.Tokens project.json does target 1.4.

**Comment by bartonjs** [comment]
Not... really?  The package has a win/unix split implementation, and it's possible that Xamarin/iOS doesn't count as either.  But that seems like it'd be a pretty pervasive issue.  I've never encountered Xamarin package restore, so I don't know how well tried it is.

**Comment by leastprivilege** [comment]
Well - then maybe now is the time to add this to your test matrix ;)

**Comment by leastprivilege** [comment]
Could someone look into that - I want to use Wilson across the .net standard supported platforms.

**Comment by brentschmaltz** [comment]
@leastprivilege I'll poke into it this week.

**Comment by leastprivilege** [comment]
thanks!

**Comment by brentschmaltz** [comment]
@leastprivilege turns out that S.S.Cryptography.Cng is only supported on Windows. I'll see if we need it OR can hide it.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/515
