### ISSUE TITLE
Investigate if RegEx should be compiled

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#504]
Currently our regex expressions are not compiled
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs#L58

discussion has indicated there may be a 30% perf increase
https://blog.codinghorror.com/to-compile-or-not-to-compile/

**Comment by Tratcher** [comment]
@mikeharder FYI

**Comment by brentschmaltz** [comment]
We should be using the static RegEx.Match(), this will compile and keep the last 15 expressions in memory. I made this change in JWEBrent, this fix will eventually be in dev for 5.0.1 preview.

**Comment by brentschmaltz** [comment]
Regex's are now compiled
