### ISSUE TITLE
Issue when accessing Office 365 social api with ADAL

### ISSUE THREAD

**Issue by devlanfear** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#505]
We are trying to access Office 365 Social API with ADAL library (Microsoft.IdentityModel.Clients.ActiveDirectory - 3.13.1.846, Microsoft.IdentityModel.Clients.ActiveDirectory.Platform-3.13.1.846) - 
https://test.sharepoint.com/_api/social.feed/actor(item=@v)/feed?@v=%27https://test.sharepoint.com/sites/Demo/newsfeed.aspx%27

We get HTTP response with StatusCode = 401:
x-ms-diagnostics: 3000003;reason="Invalid audience Uri 'https://test.sharepoint.com/'.";category="invalid_client"

Response:
{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."}

Azure Active Directory app has permission for Office 365: Have full control of all site collections.

Can you please provide any details for this issue?

**Comment by polita** [comment]
@devlanfear This is about the ADAL .NET library, not the Identity Model extensions. Can you open this issue at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues?

Alternatively, you can [ask on StackOverflow](http://stackoverflow.com/questions/tagged/adal) and our team monitors issues tagged with "adal".
