### ISSUE TITLE
Reintroduce SecurityTokenHandler.ValidateToken()

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#507]
The `SecurityTokenHandler` base class doesn't expose this precious method. Please consider bringing it back.

/cc @brentschmaltz @polita

**Comment by brentschmaltz** [comment]
@PinpointTownes what is your scenario and what API signature are you proposing?

**Comment by PinpointTownes** [comment]
> what API signature are you proposing?

```
ClaimsPrincipal ValidateToken(string token, TokenValidationParameters validationParameters, out SecurityToken validatedToken)
```

... which is identical to the method signature used by `JwtSecurityTokenHandler`.

**Comment by brentschmaltz** [comment]
@PinpointTownes I assume you meant (... validationParameters)
no 'out' param?

**Comment by PinpointTownes** [comment]
The JWT handler has an out parameter (for the security token).

That said, we could also have an overload taking the SecurityToken as an input parameter.

**Comment by brentschmaltz** [comment]
out params and async don't work together. I would like to get rid of the out parameter and return a ValidationContext with the CP, Token etc. Will do this when we hook up async.

**Comment by PinpointTownes** [comment]
In the meantime, `SecurityTokenHandler` has no validation method, which requires casting handler instances to `ISecurityTokenValidator`... this doesn't make much sense.

**Comment by brentschmaltz** [comment]
It makes sense that SecurityTokenHandler should validation methods. Passing a SecurityToken is problematic when working with XML tokens, which is why we moved away for it. Has to do performance and c14n where we use xmlreader rather than moving into a DOC. We found almost 10x improvement using the xmlreader. How about just ValidateToken as it is today?  Probably could get that into preview1.

**Comment by brentschmaltz** [comment]
I am closing this because we can't bring back validation against a SecurityToken object. It is too problematic. The most important part of the validation is the signature. There is no guarantee of anything unless the signature validates. I don't want to give users any idea that anything else makes sense. We dropped this API as such. We will be adding API's to hook reading delegates to TokenValidationParameters. Later, when we tackle async, we will loose the out param and return some structure TBD.

**Comment by PinpointTownes** [comment]
So the answer you give to people who want a validation method in `SecurityTokenHandler` to ensure that the token (and specially the signature) is valid is... nope, no such thing for you?

Again, this makes no sense. But that's an habit with this library and this team.

**Comment by brentschmaltz** [comment]
@PinpointTownes I call foul here, we take a number of asks. When you suggested that unsolicated WsFed message should fail, I got right on board.
The tension is sometimes between the way things were in System.IdentityModel circa 2005 and today.

What I am saying is that an API of the form ValidateToken(SecurityToken, ...) is impossible (well hard), to ensure that the SecurityToken (as an object) was signed and all the claims are valid in all cases. While someone with your experience could probably get it right, I am reluctant to recommend adding back that API. I am suggesting that we have an alternative that power users can use, but the average user will by default have a hard time getting into trouble.

**Comment by PinpointTownes** [comment]
> @PinpointTownes I call foul here, we take a number of asks.

Not sure if I'm supposed to laugh or cry.

> While someone with your experience could probably get it right, I am reluctant to recommend adding back that API. I am suggesting that we have an alternative that power users can use, but the average user will by default have a hard time getting into trouble.

Again, this makes absolutely no sense.

All the existing handlers you develop (i.e JWT, SAML and SAML2) already expose a `public virtual ClaimsPrincipal ValidateToken(string token, TokenValidationParameters validationParameters, out SecurityToken validatedToken)` that is part of the public contract and thus can be both called and overridden by the "average user" of your lib. I'm not asking to change that (which would be a breaking change, BTW).

All I'm asking is to make the `SecurityTokenHandler` implement `ISecurityTokenValidator` that exposes this validation method so we don't have to use ugly casts in our code when switching between handlers.

**Comment by brentschmaltz** [comment]
@PinpointTownes - please laugh. 
I thought you were asking for the overload with (SecurityToken, ...), which I can't support. 
Defining public abstract SecurityTokenHandler(string, tvp, out securityToken) is fine.

This ask makes sense. I will reopen.

**Comment by PinpointTownes** [comment]
> Defining public abstract SecurityTokenHandler(string, tvp, out securityToken) is fine.

`abstract` will be a breaking change. You'll probably want to make it virtual instead.

> I thought you were asking for the overload with (SecurityToken, ...), which I can't support.

I explicitly asked for `ClaimsPrincipal ValidateToken(string token, TokenValidationParameters validationParameters, out SecurityToken validatedToken)` but...

... it's not clear why you couldn't also add a `ClaimsPrincipal ValidateToken(SecurityToken token, TokenValidationParameters validationParameters)` overload:

```
var token = handler.ReadToken("token as a string");
var principal = handler.ValidateToken(token, tvp);
```

**Comment by brentschmaltz** [comment]
@PinpointTownes yea, virtual.

> ... it's not clear why you couldn't also add a ClaimsPrincipal ValidateToken(SecurityToken token, TokenValidationParameters validationParameters) overload:

Once a token has been deserialized into a .Net object, it is very hard to ensure that the signature is valid. Even if the original string exists, how do we make sure all artifacts in the SecurityToken are what arrived? 
SignatureValidation is an integral part of validation. If the Signature doesn't validate, nothing about the claims should be assumed.

**Comment by PinpointTownes** [comment]
> Once a token has been deserialized into a .Net object, it is very hard to ensure that the signature is valid. Even if the original string exists, how do we make sure all artifacts in the SecurityToken are what arrived?

Isn't that what properties like `JwtSecurityToken.RawData` are for? i.e retrieving the original token that was read by the `ReadToken` API?

**Comment by brentschmaltz** [comment]
`RawData` was originally envisioned to set the bootstrap context on the ClaimsIdentity so OnBehalfOfFlows would work. It is hard to reconcile that all the Claims in a hydrated token map to the `RawData`. There is an interesting flow where hydrating a token once makes sense, when multiple Identity Providers are involved. In this case you need the 'iss' to get the metadata (keys, issuer, ...).
