### ISSUE TITLE
Provide a factory or static method that can create a JwtSecurityToken without exceptions

### ISSUE THREAD

**Issue by ccrookms** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#508]
As discuss in mail thread with Brent and apparently requested by ASP.NET team, we would love a way that we can validate a token and produce the result in one call (e.g. result class that may have a status and a token if it could be validated) that doesn't use exceptions at all. Ideally, no exceptions would be thrown and caught under this method either but at least providing this to callers would be great.

@brentschmaltz

**Comment by brentschmaltz** [comment]
As a note: the current OM doesn't work with async as out params are not allowed.

**Comment by brentschmaltz** [comment]
@ccrookms @henrik-me we have added an TokenValidationResult JsonWebTokenHandler.ValidateToken that does not throw.
I added the label ASP.NET handler to coordinate with the SAL work.

**Comment by brentschmaltz** [comment]
We will be handling the in a comprehensive manner.
