### ISSUE TITLE
Unable to check the results of using JwtSecurityToken is concluded

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#511]
_From @xielongjiang on October 6, 2016 9:0_

This is my code

```
const string sec = "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429090fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1";
            var now = DateTime.UtcNow;
            var securityKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(Encoding.Default.GetBytes(sec));
            var signingCredentials = new Microsoft.IdentityModel.Tokens.SigningCredentials(
                securityKey,
                SecurityAlgorithms.HmacSha256Signature);

            var header = new JwtHeader(signingCredentials);

            var payload = new JwtPayload
            {
                { "iss", "a5fgde64-e84d-485a-be51-56e293d09a69"},
                { "scope", "https://example.com/ws"},
                { "aud", "https://example.com/oauth2/v1"},
                { "iat", now},
            };

            var secToken = new JwtSecurityToken(header, payload);

            var handler = new JwtSecurityTokenHandler();
            var tokenString = handler.WriteToken(secToken);
            Console.WriteLine(tokenString);
```

I finally get a demerit and to JWT. IO calibration, the calibration was a failure

_Copied from original issue: aspnet/Security#1000_

**Comment by Tratcher** [comment]
I don't understand the question, but those components are located over here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

**Comment by Tratcher** [comment]
_From @xielongjiang on October 6, 2016 18:10_

I mean, my final output, to https://jwt.io/ website when checking is failed @Tratcher

**Comment by brentschmaltz** [comment]
@xielongjiang are you saying that the jwt token created by Sytem.IdentityModel.Tokens.Jwt fail validation on Jwt.IO?

**Comment by xielongjiang** [comment]
@brentschmaltz Yes, Using the latest System. IdentityModel. Tokens. Jwt

**Comment by brentschmaltz** [comment]
We need to repro.

**Comment by brentschmaltz** [comment]
@Loongle checkout https://github.com/brentschmaltz/CodeSnips/blob/master/src/JwtTokens/WriteJwtSecurityToken.cs#L12

I changed the algorithm type and base64 encoded the keybytes.
