### ISSUE TITLE
Cannt find assembly "System. IdentityModel. Tokens. Jwt, Version = 5.0.0.127, Culture = neutral, PublicKeyToken = 31 bf3856ad364e35"

### ISSUE THREAD

**Issue by xielongjiang** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#512]
Cannt find assembly "System. IdentityModel. Tokens. Jwt, Version = 5.0.0.127, Culture = neutral, PublicKeyToken = 31 bf3856ad364e35"

` 
var symmetric = new SymmetricKeyIssuerSecurityTokenProvider(issuer, audienceSecret);
var ssuerSecurity = new IIssuerSecurityTokenProvider[] { symmetric };

 app.UseJwtBearerAuthentication(
                new JwtBearerAuthenticationOptions
                {
                    AuthenticationMode = AuthenticationMode.Active,
                    AllowedAudiences = new[] { audienceId },
                    IssuerSecurityTokenProviders = ssuerSecurity
                });
`

Error occurred in UseJwtBearerAuthentication

I use Microsoft.Owin.Security.Jwt, Version=3.0.1.0

Why did you delete the TokenValidationParameters ? ?

**Comment by brentschmaltz** [comment]
@xielongjiang Our 5.0 release is not compatible with Katana (3.0.x) release.

**Comment by brentschmaltz** [comment]
@xielongjiang closing this issue, please reopen if you need additional information.
