### ISSUE TITLE
System.Identity.Tokens.Jwt Can't find IssuerSigningTokens

### ISSUE THREAD

**Issue by xielongjiang** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#513]
I use vsersion 5.0.0.127

In  vsersion 5.0.0.127, can't find TokenValidationParameters

Later found it in Microsoft. IdentityModel. Tokens

Where is my lovely  `IssuerSigningTokens  `

**Comment by brentschmaltz** [comment]
@xielongjiang IssuerSigningTokens was removed in 5.0. We use IssuerSigningKeys as only keys are used for signing.

**Comment by tofutim** [comment]
Can someone leave a clue on how to convert? I am working on Microsoft.Azure.Mobile.Server.

```
            TokenValidationParameters validationParams = new TokenValidationParameters
            {
                ValidateAudience = true,
                ValidAudience = Audience,
                ValidateIssuer = true,
                ValidIssuer = Issuer,
                ValidateLifetime = parsedToken.Payload.Exp.HasValue,  // support tokens with no expiry				
                IssuerSigningKey = new BinarySecretSecurityToken(HmacSigningCredentials.ParseKeyString(SigningKey))
            };
```
Need to change BinarySecretSecurityToken to IssuerSigningKey. I presume I use tha tSigningKey at the end, but how to make that into a SecurityKey?

**Comment by brentschmaltz** [comment]
That API has been removed in 5.0. Only keys are used, not tokens

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by ShaneCourtrille** [comment]
@brentschmaltz Great but since the existing API was broken is there anything posted on how to move existing code forward?

**Comment by brentschmaltz** [comment]
@ShaneCourtrille you will have to update your code when moving to 5.x+.

This may help you: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Migrating-from-Katana-(OWIN)-3.x-to-4.x
