### ISSUE TITLE
[JWT] IDictionary<> payload is incorrectly converted to IEnumerable<>

### ISSUE THREAD

**Issue by ycrumeyrolle** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#514]
A JWT claim structured as an Dictionary is not treated as a Dictionary but as an IEnumerable. 
This is because the claim is firstly casted into an IEnumerable. As the Dictionary is an IEnumerable, the following code is never reached : 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L364

The `IDictionary<string, object>` cast attempt should be done before the `IEnumerable<object>` cast attempt.

**Comment by brentschmaltz** [comment]
@ycrumeyrolle what issue is this causing you?

**Comment by ycrumeyrolle** [comment]
I assume to have a dictionary or a JSON string as claim value, but I have a couple of claims corresponding to nested value. This is harder to rebuild structured data from claims. 
In addition, if the code flow was as I suppose it should be, the dictionary is converted into a couple of claims in JSON, with a unique property. 

May be I am misunderstanding the desired behaviour...

**Comment by brentschmaltz** [comment]
@ycrumeyrolle I suspect you are using 4.x is that true?

**Comment by ycrumeyrolle** [comment]
You are right!

**Comment by brentschmaltz** [comment]
@ycrumeyrolle we are encouraging users to move to 5.x, if this is not possible please reopen.
