### ISSUE TITLE
Exception IDX11008 when called from WIF 

### ISSUE THREAD

**Issue by estarre** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#52]
When using the JwtSecurityTokenHandler in my web application I ended up with an exception IDX11008 (This method is not supported to validate a 'jwt' use the method: ValidateToken(String, TokenValidationParameters, out SecurityToken))
The call stack is this:
System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(SecurityToken token) +46 System.IdentityModel.Tokens.SecurityTokenHandlerCollection.ValidateToken(SecurityToken token) +73 System.IdentityModel.Services.TokenReceiver.AuthenticateToken(SecurityToken token, Boolean ensureBearerToken, String endpointUri) +118 System.IdentityModel.Services.WSFederationAuthenticationModule.SignInWithResponseMessage(HttpRequestBase request) +489 System.IdentityModel.Services.WSFederationAuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs args) +361 System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

I created the web application with Visual Studio 2013 by using the the wizard for .NET 4.5: "ASP .NET Web Application" and then the "Web Forms" template. Then "Change Authetication", "Organizational Accounts", "On-Premisis" and then the fedaration URL of Azure ACS.

I don't know if I did it as it is supposed to work. But I don't understand why the ValidateToken is declared obsolete while it is called by the .NET Framework.

**Comment by brentschmaltz** [comment]
Erik, 

Just noticed this :-(

Your solution seems fine. Just keep in mind the JwtSecurityToken is not being validated but the RawData.
