### ISSUE TITLE
Can I use this lib to create APNS jwt token which is ES256 algorithm?

### ISSUE THREAD

**Issue by allenrui** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#526]

**Comment by brentschmaltz** [comment]
@allenrui not sure what APNS is. Can you add some detail?

**Comment by brentschmaltz** [comment]
@allenrui We do have support for ES256 (ECDSA keys). Please reopen if this doesn't work for you.
Here a test showing how to sign with a Ecdsa key.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs#L171
