### ISSUE TITLE
Ensure OpenIdConnectProtocolValidator follows spec for hybrid flow or deviations are recorded on wiki.

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#528]
When doing a code+id_token hybrid flow there are some additional validations required between the id_token from the authorization endpoint and the one from the token endpoint.
http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken2
1) the sub claim must match.
2) the iss claim must match.

**Comment by keegan-caruso** [comment]
@keegan-caruso To move issue to Identity Web
