### ISSUE TITLE
SymmetricSignatureProvider

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#53]
Support for Symmetric Algorithms needs to be added back into K.
This support was dropped while FxCore was solidifying the crypto support.
Action is to review the symmetric support in FxCore and determine if it is sufficient if not, add a PInvoke layer into the OS.

**Comment by videege** [comment]
I think I am running into this issue using beta7 - I am using the JWT library to generate JWT tokens with a symmetric security key and the framework is throwing an algorithm not supported error (see http://stackoverflow.com/questions/32438878/dnx-core-5-0-jwtsecuritytokenhandler-idx10640-algorithm-is-not-supported-htt).  

Is it currently not possible to use symmetric keys with the `JwtSecurityToken` and `JwtSecurityTokenHandler` classes?

**Comment by brentschmaltz** [comment]
SymmetricKey support is not available right now. Closing issue dup of #58
