### ISSUE TITLE
Discussion for S.IM moving forward

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#532]
@PinpointTownes @leastprivilege @brockallen
I am opening up this to ask for feedback on how S.IM should move forward.

**Comment by PinpointTownes** [comment]
Well, you already know my POV: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/327#issuecomment-162330668 https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/327#issuecomment-162992208 https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/476#issuecomment-254307988 :smile:

**Comment by brentschmaltz** [comment]
closing this as both 327 and 476 are open and no other comments have been added.
@PinpointTownes Thanks for the feedback, when allocating resources customer feedback plays a big role.

**Comment by leastprivilege** [comment]
Oh yes - and please change the inbound claim type map handling to opt-in, rather than opt-out.

I gave this feedback a couple of times - the JwtHandler is not the place for (automatic) claims transformation - I want the exact claim types in principal that got issued from my STS - and not MS proprietary ones.

**Comment by polita** [comment]
@leastprivilege Can you add that comment to one of the other two issues that we're using to track this request? #327, #476.

**Comment by leastprivilege** [comment]
They are both closed..

**Comment by leastprivilege** [comment]
I opened #550
