### ISSUE TITLE
Breaking change in JwtSecurityTokenHandler between 5.0.0 and 5.1.0

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#535]
@polita once said "unfortunately, we can't make any breaking changes in minor or patch versions"... obviously you forgot your own rule when adding JWE support, because `CreateJwtSecurityToken`'s signature changed between 5.0.0 and 5.1.0 (it now accepts an `EncryptingCredentials` instance)...

```
MissingMethodException: Method not found: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityToken(System.String, System.String, System.Security.Claims.ClaimsIdentity, System.Nullable1<System.DateTime>, System.Nullable1<System.DateTime>, System.Nullable`1<System.DateTime>, Microsoft.IdentityModel.Tokens.SigningCredentials)'.
```

Reported by @chris5287 on Gitter.

**Comment by brentschmaltz** [comment]
We will have to fix that by adding additional OM.

**Comment by polita** [comment]
@PinpointTownes Thanks for pointing this out for us. It wasn't intentional; we always aim to preserve backwards compatibility in a minor release. We're working out a fix for our next release.

**Comment by BrainCrumbz** [comment]
Sorry for (possibly) dumb question: which particular package should we downgrade as a workaround until this is fixed?
We hit that as soon as we moved all .NET-related packages from 1.0.1 version to 1.1.0 version.

**Comment by PinpointTownes** [comment]
@BrainCrumbz FYI, I pushed new aspnet-contrib bits to NuGet.org a few minutes ago. Since ASOS beta7 doesn't use `CreateJwtSecurityToken`, it should work with 1.1.0. Don't hesitate to give it a try when you have a minute :smile: 

(I'm preparing a blog post that details the most important changes between beta6 and beta7)

**Comment by PinpointTownes** [comment]
@BrainCrumbz posted: http://kevinchalet.com/2016/11/30/the-new-aspnet-contrib-packages-are-out/

**Comment by brentschmaltz** [comment]
@BrainCrumbz @PinpointTownes we are planning on releasing this fix to nuget shortly (within weeks).
I am going to push it to dev, so tomorrows (11/31 nightly feed on myget should have it: https://www.myget.org/gallery/azureadwebstacknightly).

**Comment by brentschmaltz** [comment]
@PinpointTownes @BrainCrumbz please reopen if the nightly fix fails.

**Comment by BrainCrumbz** [comment]
@brentschmaltz thanks for the update, might give it a go in the next days.

@PinpointTownes just tried that, it some issue, will report in its own project.

**Comment by PinpointTownes** [comment]
> @PinpointTownes @BrainCrumbz please reopen if the nightly fix fails.

It will be hard to confirm, as ASOS no longer uses this method... :sweat_smile:
