### ISSUE TITLE
Add API breaking change detection to the build

### ISSUE THREAD

**Issue by Eilon** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#537]
It would be good to have automated API breaking change detection run on every build. It typically adds only a few seconds per build, and the value is quite obvious.

There are many various tools to automate such checks, including those used by the Roslyn and .NET teams. We wrote our own due to some unique requirements, and that is available here: https://github.com/aspnet/BuildTools/tree/dev/src/Microsoft.AspNetCore.BuildTools.ApiCheck. If you wish to use this tool, we can help you get it set up.

This could help prevent issues such as https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/535.

**Comment by polita** [comment]
@Eilon That would be great. This particular issue was a result of how the compiler generates calls to APIs with default parameters. Would the tools you guys use have found a breaking change with default parameters (which are evil, but was part of the existing pattern)?

**Comment by Eilon** [comment]
I recall that the ASP.NET-written tool does check for breaking default parameter changes. @javiercn wrote the tool, so he could say for sure.

But, this particular case looks like it would have been caught by the most naïve of tools anyway, because I think the signature of the method changed. (In practice it's only compilers that have real awareness of optional parameters; reflection doesn't lie 😄 )

**Comment by PinpointTownes** [comment]
@Eilon hey, that would be great if you could write a tiny how-to for this tool :smile: 
I'd really like to use it when going to RTM with the aspnet-contrib projects.

Does it integrate with Sake?

**Comment by Eilon** [comment]
@PinpointTownes ah, documentation? We have commits 😄 This is the change where @javiercn integrated the tool into the ASP.NET/EF build: https://github.com/aspnet/KoreBuild/pull/131

Ultimately it just runs the ApiCheck tool (a standard .NET CLI tool) in certain 'src' folders with certain parameters, so it should be very easy to integrate it into any build system.

**Comment by PinpointTownes** [comment]
> @PinpointTownes ah, documentation? We have commits :smile:

The last time I said that, I was told to "go fuck myself"... so... :trollface: 

Thanks for the link! It looks like it will be quite easy to use with Sake, as there's a dedicated target :+1:

**Comment by lovemaths** [comment]
merged to dev branch.
