### ISSUE TITLE
Very weird issue, one machine (out of many) unable to match "kid"

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#545]
_From @brphelps on December 10, 2016 2:9_

I'm stumped, so I figured an issue was a good place to start. We UseJwtBearerAuthentication to configure our ASP Core 5 app, and generally have been doing so without a hitch so far. Our deployed environments and local environments are able to validate tokens, at least, until we got a new hire. This new hire's machine seems to be giving validation errors where other machines (including PROD machines) are not. 

This is the error we see:

Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid': 'RrQqu9rydBVRWmcocuXUb20HGRM', 

   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()

Is there anything on the ASP NetCore side that would contribute to this? As you might imagine from the call stack, we're relying on .Net 4.6.2 to actually provide the CLR implementation to us. The weirdest part about this error is that it seems to only be specific to his machine, which blows my mind (this is validating AAD tokens pretty much out of the box).

_Copied from original issue: aspnet/Security#1064_

**Comment by brentschmaltz** [comment]
@Tratcher where did the JWT come from? Can you provide some details about where the keys are obtained? Type of keys? TokenProvider?

**Comment by brphelps** [comment]
I'm the originator :). The token is issued from AAD (ADAL talking to AAD specifically). 

We're currently using this configuration:

app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                Authority = $"{authSettings.AadInstance}{authSettings.Tenant}",
                Audience = authSettings.ClientId,
                TokenValidationParameters = new TokenValidationParameters()
                {
                    ValidateIssuer = false,
                    ValidateAudience = true
                },
                Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = context =>
                    {
                        context.SkipToNextMiddleware();
                        return Task.FromResult(0);
                    }
                }

            });

**Comment by brentschmaltz** [comment]
@brphelps thanks, what is the authority?
