### ISSUE TITLE
OpenIdConnectResponseType is missing some constants

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#546]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectResponseType.cs

It's missing "none" and "token" at least, although it would be good to have all the combinations (code token) (token id_token) (code token id_token)

**Comment by brentschmaltz** [comment]
@javiercn I am not sure about "none" or "token".
"code token", "token id_token", "code token id_token" seem valid.

http://openid.net/specs/openid-connect-core-1_0.html#Authentication

**Comment by javiercn** [comment]
Hi,

Token is defined in the OAuth 2.0 spec:
https://tools.ietf.org/html/rfc6749#section-11.3.2

None is defined in the OAuth 2.0 multiple response types spec:
http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#OAuthResponseTypesReg

The Open Id connect spec makes an explicit note about the "token" 

> While OAuth 2.0 also defines the token Response Type value for the Implicit Flow, OpenID Connect does not use this Response Type, since no ID Token would be returned.

That said, I think it's useful to have it as part of the list of response types for servers that support both, OAuth 2.0 and OpenId Connect.

**Comment by brentschmaltz** [comment]
@javiercn will put this in 5.1.2

**Comment by brentschmaltz** [comment]
@javiercn will be in tomorrows nightly.
