### ISSUE TITLE
JWT Handler on iOS

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#548]
Since 5.1 I can add the package to a Xamarin iOS project - but when validating a JWT I get the below exception.

Any ideas?

"IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: a3rMUgMFv9tPclLa6yF3zAkfquE\n'.\nExceptions caught:\n 'System.NotImplementedException: **Derived classes must provide an implementation**.\n  at System.Security.Cryptography.RSA.HashData (System.Byte[] data, System.Int32 offset, System.Int32 count, System.Security.Cryptography.HashAlgorithmName hashAlgorithm) [0x00000] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/security/cryptography/rsa.cs:89 \n  at System.Security.Cryptography.RSA.VerifyData (System.Byte[] data, System.Int32 offset, System.Int32 count, System.Byte[] signature, System.Security.Cryptography.HashAlgorithmName hashAlgorithm, System.Security.Cryptography.RSASignaturePadding padding) [0x0008a] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/security/cryptography/rsa.cs:166 \n  at System.Security.Cryptography.RSA.VerifyData (System.Byte[] data, System.Byte[] signature, System.Security.Cryptography.HashAlgorithmName hashAlgorithm, System.Security.Cryptography.RSASignaturePadding padding) [0x00011] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/security/cryptography/rsa.cs:143 \n  at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Verify (System.Byte[] input, System.Byte[] signature) [0x0005d] in <f6fface39b224c079207c34f8d556585>:0 \n  at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.Byte[] encodedBytes, System.Byte[] signature, Microsoft.IdentityModel.Tokens.SecurityKey key, System.String algorithm, Microsoft.IdentityModel.Tokens.TokenValidationParameters validationParameters) [0x00082] in <5b3d2ff3122e411f897a3bee8b024790>:0 \n  at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.String token, Microsoft.IdentityModel.Tokens.TokenValidationParameters validationParameters) [0x0019f] in <5b3d2ff3122e411f897a3bee8b024790>:0 \n'.\ntoken: '{\"alg\":\"RS256\",\"typ\":\"JWT\",\"x5t\":\"a3rMUgMFv9tPclLa6yF3zAkfquE\",\"kid\":\"a3rMUgMFv9tPclLa6yF3zAkfquE\"}.{\"iss\":\"https://demo.identityserver.io\",\"aud\":\"native\",\"exp\":1481724549,\"nbf\":1481724249,\"nonce\":\"a2d49e2bc14beb5ec6f79bb20cfb03c4b01c7f89bebc0cd692dd485fdb716059\",\"iat\":1481724249,\"c_hash\":\"ZPg_282TmzmwwpE2xDnfiA\",\"sid\":\"4c58ecf10b87455e95a82144dc481057\",\"sub\":\"88421113\",\"auth_time\":1481724146,\"idp\":\"idsrv\",\"amr\":[\"password\"]}'."

**Comment by brentschmaltz** [comment]
@leastprivilege I suspect that this functionality is not available on iOS. 
@bartonjs is this correct?

**Comment by bartonjs** [comment]
It means that the Xamarin implementation of RSA has not overridden the HashData method (which was added in .NET 4.6 / .NET Standard 1.3).  @akoeplinger are you guys aware of that?

**Comment by akoeplinger** [comment]
@bartonjs Yeah, looks like that's the case. I wasn't aware of it, not sure if we should've received a notice that we should override those methods :)

**Comment by leastprivilege** [comment]
thanks - could you fix that please? 

I've been using PCLCrypto (https://github.com/AArnott/PCLCrypto) so far and this deals with x-plat crypto quite well. Moving away from PCL to netstandard - it should be easier to implement a cross platform OpenID Connect library. But no joy so far.

When my original iOS issue was closed, I assumed someone tested it as well.

**Comment by akoeplinger** [comment]
Ok, so it turns out we _did_ implement these methods for RSA in Mono 4.8/Xamarin.iOS 10.4 which are in the alpha channel right now. Can you please try with those builds?

I see it not being implemented for DAS though, so I'll file an issue for that.

**Comment by leastprivilege** [comment]
OK - will do. thanks!

**Comment by leastprivilege** [comment]
just did a quick test. seems to work. thanks! Will do more testing and let you know if there are more issues.
