### ISSUE TITLE
Stop transforming inbound/outbound claim types by default

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#550]
I gave this feedback a couple of times - the JwtHandler is not the place for (automatic) claims transformation. This is either application logic or explicit opt-in behavior.

I want the exact claim types in the principal that got issued from my STS - and not MS proprietary ones.

**Comment by brentschmaltz** [comment]
@leastprivilege I agree with you in principal. 
If we turn it off by default, we need to consider how ClaimsIdentity.Name and ClaimsPrincipal.IsInRole are affected. These apis use ClaimsIdentity.NameClaimType and ClaimsIdentity.RoleClaimType with are set to the mapped types.

A possible mitigation is:
clearing static JwtSecurityTokenHandler.DefaultInboundClaimTypeMap in global scope.

**Comment by leastprivilege** [comment]
Why is this your concern? Anybody can set the RoleClaimType and NameClaimType when validating a token to match whatever they are expecting.

Both are legacy and shouldn't be used anymore anyways.

wrt statics - it's 2016.

**Comment by brentschmaltz** [comment]
My concern is back-compat. ClaimsIdentity.Name, which is tied to NameClaimType, could be null. This has caused null-refs in code that expects a non-null value.

It almost 2017 :-).

**Comment by leastprivilege** [comment]
Again - why is this your concern?

There might be JWTs without a "name" claim (or something that maps to it) at all. Actually they are pretty common.

The same issue would exist.

**Comment by brockallen** [comment]
> My concern is back-compat

With that? This is a new(er) technology, and no where in the specs do you see WS-* claim types recommended. Stop treating the developers like they are incompetent.

If you must make these decisions for developers, then put a layer elsewhere in the app layer to give you SOAP-flavored claim types, but don't mandate this on the rest of people by default. By forcing this, you're shoehorning people into a legacy mode of claim types. Then you have more backwards compat problems down the road.

At some point you (and the developers consuming your stuff) need to evolve. This awful mindset of wanting to babysit your developers prohibits that.

**Comment by brentschmaltz** [comment]
The back-compat scenario where an AuthorizationDecisionPoint (internal or external) functions differently when S.IM.Tokens.Jwt generates different claims by default, is the concern. A comprehensive set of tests may catch such issues. It is doubtful that all issues would be shown through testing.

**Comment by brockallen** [comment]
I think the issue here is the difference in expectation of a JWT library. From my point of view this library should just do JWT semantics and nothing more. From your perspective you think it should do a lot more including interpreting claim types and doing other things related to authorization (as you just said). The disconnect is the source of the complaints.

**Comment by brentschmaltz** [comment]
@brockallen I don't think the library should do more than JWT semantics. The tension is related to a choice we made 5 years ago when WsFed and OAuth were running side-by-side. We thought normalizing the claim types would help users write a single Authorization Policy independent of the token type OR protocol. That is where the claim transformation of JWT claim types originated. Now, we have existing users that have written Authorization Policies based on the claims returned from ValidateToken. If we change those claim types **by default**, the authorization result could change.  These leads me to suggesting a simple way to set the default OFF as a compromise.

**Comment by brockallen** [comment]
That's why this should be a brand new library for a new age, rather than carrying forward legacy design and choices.

**Comment by brentschmaltz** [comment]
@brockallen I think you are arguing for Microsoft.IdentityModel.Tokens.Jwt that works in the new world and let System.IdentityModel.Tokens.Jwt function as it does for legacy.

**Comment by brentschmaltz** [comment]
@leastprivilege @brockallen I propose in the next minor release we add an easy off switch.
Then in the 2.0 refresh we remove the mapping code and leave it to higher levels or a pluggable delegate.

**Comment by brockallen** [comment]
> Then in the 2.0

2.0, as in the same time-frame as 2.0 of .NET Core and ASP.NET Core?

**Comment by brentschmaltz** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by brentschmaltz** [comment]
Design note: the creation of the ClaimsIdentity claims should use Claim.Clone(). This will work for all 'non-mapped' claims, as for those a new claim will need to be created with a different 'type'. This is important since JwtPayload.Claims is virtual and users could be creating custom claims.

**Comment by brentschmaltz** [comment]
Our new Microsoft.IdentityModel.Tokens will not transform and will work directly with JSON.
