### ISSUE TITLE
5.1.0: JWT with "cty":"JWT" in header cannot be read

### ISSUE THREAD

**Issue by johncrim** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#554]
In System.IdentityModel.Tokens.Jwt 5.1.0, JWTs with a valid header like:

```
{
  "alg": "HS256",
  "typ": "JWT",
  "cty": "JWT"
}
```

cannot be read, due to this code in `JwtSecurityToken.DecodeJws()`:
```
        private void DecodeJws(string[] tokenParts)
        {
            // We do not support other content types for JWS.
            if (Header.Cty != null)
                throw LogHelper.LogExceptionMessage(new ArgumentException(string.Format(CultureInfo.InvariantCulture, LogMessages.IDX10723, tokenParts[1], RawData)));

```

Note that this is **not** an issue in the master branch, but is a (blocking for me) issue in the release branch, and in the existing released NuGet package.

This test fails (release branch only):
```
        [Fact]
        public void PayloadParsesWithCtyInHeader()
        {
            // This token has JWT header: { "alg": "HS256", "typ": "JWT", "cty": "JWT" }
            string token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.E-Dl3jALtUnmEZzbFuyFV15wkqTsQU_zRci5u6yBrHc";

            var jwtHandler = new JwtSecurityTokenHandler();
            var jwt = jwtHandler.ReadJwtToken(token);
        }
```

**Comment by johncrim** [comment]
Note that per https://tools.ietf.org/html/rfc7519#section-5.2 (covering the `cty` header), the current behavior is reasonable (and an implementation I'm integrating with is incorrect). However, this is a breaking change from the prior version of System.IdentityModel.Tokens.Jwt (version 4.0.3.308261200).

I think the biggest reason that this is a bug is that it prevents successful interoperability with other implementations (this is a blocking issue for me for integrating with https://www.aoe.com/en/products/forgerock/forgerock-openam.html). The question is whether this exception is truly necessary.

**Comment by brentschmaltz** [comment]
@johncrim lax on receive and per spec on send is probably the way to adjust here. I marked this for the 5.1.2 release

**Comment by brentschmaltz** [comment]
@johncrim we will get this into 5.1.3

**Comment by brentschmaltz** [comment]
@johncrim committed into dev, will be in nightly builds.
5.1.3 will be released by Feb 28th.
