### ISSUE TITLE
Strong name validation exception when using the 5.1.1 packages on .NET Desktop

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#557]
@brentschmaltz @polita @tushargupta51 FYI, the new 5.1.1 package doesn't work on .NET Desktop. An exception is thrown at runtime due to a strong name validation failure:

Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A).

.NET Core is not impacted as it doesn't enforce strong name validation.

**Comment by polita** [comment]
Thanks @PinpointTownes. We'll fix it ASAP.

**Comment by polita** [comment]
@PinpointTownes It looks like we accidentally published privately-built bins. I am cutting a new build now.

**Comment by PinpointTownes** [comment]
lol, that doesn't sound like a great way to start this new year :trollface: 

Thanks for your reactivity :+1:

**Comment by polita** [comment]
It's not my ideal. :)

**Comment by brentschmaltz** [comment]
@PinpointTownes 5.1.2 looks good.

**Comment by polita** [comment]
We've pushed 5.1.2 packages to NuGet.

**Comment by PinpointTownes** [comment]
Thanks, I'll give them a try tomorrow.

Note: you should consider updating https://technet.microsoft.com/library/security/3214296 to list the fixed packages. It would be also worth mentioning that the 5.0.0 bits were not vulnerable.
