### ISSUE TITLE
JWT handler and UAP

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#559]
When I reference the JWT handler in a Win10 project I get errors like:

Severity	Code	Description	Project	File	Line	Suppression State
Error		System.Security.Cryptography.Csp 4.3.0 provides a compile-time reference assembly for System.Security.Cryptography.Csp on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.			0	

Any idea what I am doing wrong?

**Comment by leastprivilege** [comment]
I removed all the AOTs - but still get

Severity	Code	Description	Project	File	Line	Suppression State
Error		System.Security.Cryptography.Csp 4.3.0 provides a compile-time reference assembly for System.Security.Cryptography.Csp on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.			0

**Comment by brentschmaltz** [comment]
@leastprivilege by UAP do you mean Universal Windows Application?

**Comment by bartonjs** [comment]
Looks like we don't have a UAP/UWP version of that library.

**Comment by brentschmaltz** [comment]
@leastprivilege @bartonjs i take it this means this scenario is not supported by .net?

**Comment by brentschmaltz** [comment]
@ChenYan98 I think we should include System.Security.Cryptography.Csp only in NetStandard 14. I pushed brentsch/559 for you to get an idea of what I am thinking.

**Comment by leastprivilege** [comment]
I am confused - I thought the JWT handler is netstandard 1.4 - and according to your table, that makes it compatible with UAP/Win10?!

**Comment by brentschmaltz** [comment]
@leastprivilege yes JWT handler is netstandard 1.4. However, System.Security.Cryptography.Csp appears to have no implementation in 1.4. We don't need S.S.C.Csp in 1.4, if we drop that reference in project.json, your problem will go away. We use S.S.C.Algorithms and let the runtime serve up the correct implementation.

**Comment by leastprivilege** [comment]
cool - so this is a bug right? Can you fix that in a bugfix release - e.g. 5.1.3 ?

**Comment by brentschmaltz** [comment]
@leastprivilege - yep I will ping you when we get this in.

**Comment by brentschmaltz** [comment]
@leastprivilege can you try out 5.1.3-pre-402070922 from the nightly feed: https://www.myget.org/F/azureadwebstacknightly/api/v3/index.json

**Comment by leastprivilege** [comment]
I didn't have a chance to try it yet - but IMHO you should be more agile for bug fix releases. This issue is already older than 4 weeks.

**Comment by pellea** [comment]
Any update on this?

**Comment by brentschmaltz** [comment]
@pellea nightly x.5.3 should solve the issue.

**Comment by pellea** [comment]
Yes, I can reference the nightly package.
But I doubt that @leastprivilege will use this package in it's "production" package.

**Comment by leastprivilege** [comment]
Of course I won't. I think bug fix releases should be released quicker. That's the beauty of this new work flow.

What's the ETA?

**Comment by brentschmaltz** [comment]
@leastprivilege @pellea Feb 28th.

**Comment by leastprivilege** [comment]
UWP is working now. thanks!
