### ISSUE TITLE
IDX10213: SecurityTokens must be signed. SecurityToken: '{0}'

### ISSUE THREAD

**Issue by paritoshfulsunge2015** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#563]
Using WS-Federation ASP.Net OWIN middleware to sign-in users from a single Azure AD tenant, on signin request control goes to login.windows.net but receiving security token must be signed error when the token comes back to identitymodel,tokens.saml2securitytokenhandler

Exception: IDX10213: SecurityTokens must be signed. SecurityToken: '{0}'. at Microsoft.IdentityModel.Tokens.Saml2SecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken;

**Comment by brentschmaltz** [comment]
@paritoshfulsunge2015 I not sure I under stand your concern. Is it that the message is wrong?

**Comment by paritoshfulsunge2015** [comment]
@brentschmaltz 
There are two issues here, 
1. The message is incomplete. It says SecurityToken: '{0}' but the format placeholder is never replaced with the actual token.

2. Ideally I should not receive this error at all, I have the app configured as mentioned in the Microsoft docs link "https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications". The code line that is throwing this exception expects the token to be signed and I am pretty sure that token received from AAD is signed as I can see signing certificate in the metadata.

**Comment by brentschmaltz** [comment]
@paritoshfulsunge2015 thanks for the clarification. I'll look into it.

**Comment by paritoshfulsunge2015** [comment]
@brentschmaltz Sorry by mistake I gave the incorrect link for the reference Microsoft doc for app setup. Below is the correct link:
https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-wsfederation/

**Comment by brentschmaltz** [comment]
@paritoshfulsunge2015 couple of questions.
1. Did you just try this sample for the first time OR did it every work?
2. Why did you choose wsFed over OIDC?

**Comment by paritoshfulsunge2015** [comment]
@brentschmaltz 
Did you just try this sample for the first time OR did it ever work? --- Yes the sample works for OpenID Connect 
Why did you choose wsFed over OIDC? --- We are just evaluating both the protocols

**Comment by bharatmangal04** [comment]
Hi Team, We are facing same issue and due to which production environment is down but as an alternative we have removed the secondary certificate from the ADFS server.

Can we get the solution for this on priority basis
