### ISSUE TITLE
TokenValidationParameters.IssuerSigningKeyResolver is not async

### ISSUE THREAD

**Issue by Pikhulya** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#566]
It seems like the purpose of TokenValidationParameters.IssuerSigningKeyResolver is to customize the way signing keys are resolved/retrieved. Therefore, it would be logical to accept that there are scenarios where they key will be downloaded from somewhere which would involve IO operation but since the delegate defined in  azure-activedirectory-identitymodel-extensions-for-dotnet/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs 
is not async then any IO call which would be made inside the resolver would be blocking call.
Can the delegate be changed to be async one?

**Comment by brentschmaltz** [comment]
@Pikhulya this should be done at the same time as https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/468

**Comment by brentschmaltz** [comment]
@Pikhulya Will fix with https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/468
