### ISSUE TITLE
IDX10213: SecurityTokens must be signed. SecurityToken: '{0}'

### ISSUE THREAD

**Issue by zivillian** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#567]
During AD FS CertificateRollover there are multiple Token Signing Keys. This results in an SecurityTokenValidationException with the above message.

The reason is a missing break in [SecurityKeyResolver.ResolvesToSigningToken()](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b605b48dcf16a9b68e3521b862b43ea684fc000f/src/Microsoft.IdentityModel.Protocol.Extensions/SecurityKeyResolver.cs#L204).

**Version:** 1.0.3.308261200

This may also be the source for #563

**Comment by bharatmangal04** [comment]
Hi Team,  We are facing same issue and due to which production environment is down but as an alternative we have removed the secondary certificate from the ADFS server. 

Can we get the solution for this on priority basis.

**Comment by brentschmaltz** [comment]
@zivillian @bharatmangal04 Will get into next release, will be out next week.

**Comment by bharatmangal04** [comment]
Thanks @brentschmaltz Please let me know the date of release. we have next production release on next week so will see if we can update the nugget package in our code base.

**Comment by brentschmaltz** [comment]
@bharatmangal04 I pulled your changed into release4x. That is the last fix for now. I will merge into dev4x and let you know when the nightlies are out on myget so you can verify. Hopefully we can meet your production date.

**Comment by brentschmaltz** [comment]
@bharatmangal04 @zivillian Changes are in dev4x and release4x. release4x was in a bad merge state. I had to rebase ontop of dev4x, then push -f.
