### ISSUE TITLE
IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier

### ISSUE THREAD

**Issue by lokesh-zende** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#569]
Hi, 
I am new to OAuth and I am trying to implement it in my application.
I have added a relying party by referring [this ](http://www.gi-architects.co.uk/2016/04/setup-oauth2-on-adfs-3-0/)link.
![image](https://cloud.githubusercontent.com/assets/20038894/22500416/49d6a02a-e88a-11e6-9a7d-b88a1a8611c9.png)
As suggested in a link, I have not attached any certificate while creating a relying party.

Now in my application, this code redirects me to AD FS login page where user enters his login credentials.
![image](https://cloud.githubusercontent.com/assets/20038894/22500959/9bcafcd0-e88c-11e6-8a85-92452f171ca5.png)

After login at AD FS, I successfully receive the encrypted JWT token using below code.

![image](https://cloud.githubusercontent.com/assets/20038894/22500998/cb58e890-e88c-11e6-9d45-afd703fe0592.png)

Now I am trying to validate the same token using below code

![image](https://cloud.githubusercontent.com/assets/20038894/22501036/e739f342-e88c-11e6-86f6-797849e32654.png)

but while validating the token, I get error as 
`

IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier

    (

    IsReadOnly = False,

    Count = 1,

    Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0xAE373EDE1C71AB1233A099B1891B3C59C3B825FE)

    )

', 

token: '{"typ":"JWT","alg":"RS256","x5t":"rjc-3hxxqxIzoJmxiRs8WcO4Jf4"}.{"aud":"https://lxi322.lxi.company.com","iss":"http://PW12DEVADFS.PW12DEV.company.com/adfs/services/trust","iat":1485938952,"exp":1485942552,"upn":"lokesh@PW12DEV.company.com","email":"lokesh.zende@outlook.com","given_name":"lokesh","auth_time":"2017-02-01T08:49:11.955Z","authmethod":"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","ver":"1.0","appid":"a8cb2a71-da38-4cf4-9023-7799d00e09f8"}'.`

Where am I going wrong ? Can you help me on this ? 

Thanks.

**Comment by brentschmaltz** [comment]
TokenValidationParameters that you pass to ValidateToken needs to have the key necessary to validate the signature of the JWT. Normally you would get the key for the discovery endpoint using ConfigurationManager https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs

You can also set: TokenValidationParameters.IssuerSigningKey

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L354

**Comment by brentschmaltz** [comment]
@lokesh-zende if you need additional information, please reopen.
