### ISSUE TITLE
Build Error DEV4X-  Microsoft.IdentityModel.Protocol.Extensions.Tests

### ISSUE THREAD

**Issue by bharatmangal04** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#570]
Hi All, 

I have clone the solution from DEV4X branch but not able to build the solution due to missing one file "ConfigurationDocument.xml".

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "D:\GitSource\azure-activedirectory-identitymodel-extensions-for-dotnet\tests\Microsoft.IdentityModel.Protocol.Extensions.Tests\ConfigurationDocument.xml" because it was not found.	Microsoft.IdentityModel.Protocol.Extensions.Tests

As a workaround I removed this from project file. Does this file require if yes can someone please add to the solution.

**Comment by brentschmaltz** [comment]
@bharatmangal04 sorry about that. I removed the dependency. It was accidentally added.
