### ISSUE TITLE
Version 5.1.2 Breaks attempt to use OpenIdConnectConfiguration.

### ISSUE THREAD

**Issue by DarkBond** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#576]
I've got a version of the AAD B2C examples from [https://github.com/Azure-Samples/active-directory-dotnet-webapi-manual-jwt-validation](url) that work just great out of the box with version 4.0.1.  However, I'm connecting to the B2C endpoints, so I'm also using ConfigurationManager<OpenIdConnectConfiguration> in order to get the V 2.0 endpoint metadata.  When I upgrade to System.IdentityModel.Tokens.Jwt version 5.1.2, the call to ConfigurationManager fails.  The call looks like:
```
ConfigurationManager<OpenIdConnectConfiguration> configManager = new ConfigurationManager<OpenIdConnectConfiguration>(stsDiscoveryEndpoint);
OpenIdConnectConfiguration config = await configManager.GetConfigurationAsync();
```
The JSON deserializer is unable to decode a type called **DateTimeUtil**:

`Additional information: Could not load type 'System.IdentityModel.DateTimeUtil' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
`

**Comment by brentschmaltz** [comment]
@DarkBond DateTimeUtil is in Microsoft.IdentityModel.Tokens. If you are using Katana, you must stick with the 4.x versions of IdentityModel.

**Comment by DarkBond** [comment]
Brent, close this one out.  I started with one of the examples on GITHUB.  When I upgraded the System.IdentityModel.Tokens.Jwt from 4.0.0 to 5.2.1, apparently the Microsoft.IdentityModel.Protocols.OpenIdConnect didn't upgrade as well, so I was left with a bad configuration by Nuget.  Upgrading and re-installing the packages seems to have solved the issue.  Sorry for the trouble.

**Comment by brentschmaltz** [comment]
@DarkBond thanks for getting back so soon.
