### ISSUE TITLE
Consider not automatically initializing collections in OpenIdConnectConfiguration

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#578]
When trying to use the type for serializing a metadata document it includes a bunch of properties with empty json arrays that increase the size of the document.

The properties are marked with `DefaultValueHandling = DefaultValueHandling.Ignore` but given that they are initialized on the constructor, there's no way to take advantage of that.

I can see two options to fix this:
Option 1 is stop initializing the collection (but that would be a breaking change).
Option 2 is add a setter to collection properties so that they can be set to null by people trying to serialize the object.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs#L113

**Comment by brentschmaltz** [comment]
@javiercn let's use https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/580 for discussions.

**Comment by brentschmaltz** [comment]
@mafurman have a look at this when you have a chance.
