### ISSUE TITLE
Do not serialize some properties on JsonWebKey

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#579]
When trying to serialize an instance of JsonWebKey there are a few properties that are showing up on the wire even though they are not set.

```
{
  "key_ops": [],
  "kid": "DevelopmentKey.5efea89c-6b7f-4ab3-9579-14b1134a4636",
  "kty": "RSA",
  "e": "AQAB",
  "n": "",
  "use": "sig",
  "x5c": [],
  "keySize": 2048,
  "hasPrivateKey": false,
  "keyId": null,
  "cryptoProviderFactory": {
      "customCryptoProvider": null
}
```

It would be good if you could hide these properties by using JsonIgnore http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonIgnoreAttribute.htm

(KeySize, HasPrivateKey, KeyId, CryptoProviderFactory)

It would also be good if you can add a setter to the collection properties so that they can be set to null and not send over the wire when empty.

This issue is related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/578

**Comment by brentschmaltz** [comment]
@javiercn definitely we will put the 'ignore' into 5.1.4 for 
`(KeySize,` HasPrivateKey, KeyId, CryptoProviderFactory)

As for setting collections to null, that is always a discussion with two camps. Allowing null as https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L502 leads to always checking for null when using concat when aggregrating keys for validation. We changed to always having a non-null collections and enums as per .Net guidelines.
Perhaps though we could introduce a JsonSerializer that skips the empty collections.

**Comment by javiercn** [comment]
Maybe you could do this for collections http://www.newtonsoft.com/json/help/html/ConditionalProperties.htm

**Comment by brentschmaltz** [comment]
@javiercn something like that might work.
We will endeavor to get this into 5.2.0
