### ISSUE TITLE
Problem with Microsoft.IdentityModel.Protocols.OpenIdConnect nuget package dependencies. 

### ISSUE THREAD

**Issue by pavlalexandr** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#580]
Hi guys, 
faced with a problem when I use Microsoft.AspNetCore.Authentication.OpenIdConnect in my ASP.NET MVC  6 application. 
When I create OpenIdConnectOptions:
` return new OpenIdConnectOptions
            {
                // For each policy, give OWIN the policy-specific metadata address, and
                // set the authentication type to the id of the policy
                MetadataAddress = string.Format(AadInstance, Tenant, policy),
                AuthenticationScheme = policy,
                CallbackPath = new PathString(string.Format("/{0}", policy)),

                // These are standard OpenID Connect parameters, with values pulled from config.json
                ClientId = ClientId,
                PostLogoutRedirectUri = RedirectUri,
                Events = new OpenIdConnectEvents
                {
                    OnRemoteFailure = RemoteFailure,
                },
                ResponseType = OpenIdConnectResponseType.IdToken,

                // This piece is optional - it is used for displaying the user's name in the navigation bar.
                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                }
            };`

there is error is rises:
> Can't load file or assembly "Microsoft.IdentityModel.Tokens, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Исключение из HRESULT: 0x80131040)
> === Информация о состоянии предварительной привязки ===
Журнал: DisplayName = Microsoft.IdentityModel.Tokens, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
Журнал: Appbase = file:///C:/Work/PowerBiPortal/Angular2Application1/bin/Debug/net461/win7-x64/
Журнал: Initial PrivatePath = NULL
Вызов сборки: Angular2Application1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
Журнал: данная привязка начинается в контексте загрузки default.
Журнал: используется файл конфигурации приложения: C:\Work\PowerBiPortal\Angular2Application1\bin\Debug\net461\win7-x64\Angular2Application1.exe.Config.
Журнал: используется файл конфигурации главного узла: 
Журнал: используется файл конфигурации компьютера из C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
Журнал: ссылка после применения политики: Microsoft.IdentityModel.Tokens, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

That's really strange because at Nuget dependencies tree I can see only System.IdentityModel.Tokens.Jwt (>= 5.1.2)

**Comment by brentschmaltz** [comment]
@pavlalexandr we delisted 5.1.0 as there was a security issue. You should be using x.1.2 releases from IdentityModel. You may need to add a binding redirect in your config file.
Something like: https://github.com/brentschmaltz/Katana/blob/master/OAuthBearer/Web.config#L107

**Comment by brentschmaltz** [comment]
@pavlalexandr I am closing this now, please reopen if you are still having issues.
