### ISSUE TITLE
Consider reducing the size of the generated nonce

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#586]
Currently we generate a nonce by base64 encoding two concatenated Guids, wich produces a rather large value.

We could generate a smaller nonce using the RandomNumberGenerator from System.Security.Cryptography to generate a value with the same security characteristics but with a shorter length.

This affects the sizes of multiple cookies in ASP.NET and the size of the id tokens that we generate and should be easy to implement

**Comment by brentschmaltz** [comment]
@javiercn you can override GenerateNonce, so I marked this as P2.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L108

Also, you can filter out any claims you wish by setting the following.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L77

**Comment by brentschmaltz** [comment]
@javiercn you can control this yourself. Please feel free to reopen if you are unable.

**Comment by brockallen** [comment]
@brentschmaltz keep in mind that guid generation on non-windows does not carry the same entropy guarantee that it does on windows. you should use a CRNG.

**Comment by brentschmaltz** [comment]
@brockallen that's one reason GenerateNonce is virtual. I'll consider your suggestion.
