### ISSUE TITLE
Bump all IdentityModel nuget packages to 5.2.0 for next release

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#587]
Users seem confused by the versioning (I know I am).
M.IM.Logging 1.x
M.IM.Protocols 2.x
M.IM.Tokens 5.x

For the next release bump them all to 5.2.0.

@PinpointTownes @leastprivilege @Tratcher @brockallen  OK?

**Comment by Tratcher** [comment]
Yes please

**Comment by PinpointTownes** [comment]
@brentschmaltz assuming there's no breaking change, yeah, that's fine.

**Comment by brentschmaltz** [comment]
committed into wsfed topic branch
