### ISSUE TITLE
Add a constant for the Prompt parameter values

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#588]
I can't find a constant with the values for the prompt parameter.
Can we add a class with these constants? Something like OpenIdConnectPrompt with the 4 values defined by the spec `none, login, consent, select_account`

**Comment by brentschmaltz** [comment]
@javiercn should be easy enough

**Comment by brentschmaltz** [comment]
@lovemaths javiercn is asking for a new class similar to OpenIdConnectResponseType. 
@javiercn I think the name OpenidConnectPrompt is fine.
