### ISSUE TITLE
Add a constant for the offline_access scope value in OpenIdConnectScope class

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#589]
The class OpenIdConnectScope is missing the offline_access constant. It would be nice if we could add it.
http://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectScope.cs

**Comment by brentschmaltz** [comment]
@lovemaths just add to OpenIdConnectScope.cs
