### ISSUE TITLE
Recent JWE implementation flaw findings

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#590]
Have you guys seen that:

http://blog.intothesymmetry.com/2017/03/critical-vulnerability-in-json-web.html

**Comment by brentschmaltz** [comment]
@leastprivilege yes I have seen that.

**Comment by brentschmaltz** [comment]
@leastprivilege we do plan on supporting KeyExchange, when we do we will do the right thing.
