### ISSUE TITLE
Serialize SecurityKey to JsonWebKey

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#591]
Is there a built-in way to turn a SecurityKey (e.g. RSA or X509) into a JsonWebKey for serialization?

**Comment by brentschmaltz** [comment]
@leastprivilege no, but that would be a good feature. I marked it as 5.x general release. We will see how much bandwidth we have post 5.2.0.
