### ISSUE TITLE
Roadmap for WS-Fed/SAML token support

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#595]
Hi @brentschmaltz  (and @polita)

in the last update you said "April timeframe" - 

I need to know more details.

What exactly will be released in April?

* IdentityModel update to support SAML tokens?
* WsFederationConfiguration, WsFederationMessage and related classes?

How is that related to the WS-Federation middleware for ASP.NET Core? Is this planned in the same timeframe? Or IdentityModel first - and then the middleware later? If yes - when (roughly) ?

I have a couple of customers that need that functionality soon - otherwise I will port those things myself for the time being.

https://github.com/chrisdrobison/aspnetcore-wsfed
is a good start - but there's the versioning conflict which makes it impractical to use.

thanks

**Comment by brentschmaltz** [comment]
@leastprivilege @Tratcher We are getting close, the WsFed topic branch has the code for Saml and WsFed.
I was hoping for a prototype this week, but it will most likely push out to next week. 
The code is in 5.x and will have support for Core and Desktop.

@leastprivilege @PinpointTownes @Tratcher I was thinking of dropping support for Saml1 tokens for the first release (they are messy with multiple key as each subject can have a key). Do you think that would be OK?

See:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/WsFed

**Comment by leastprivilege** [comment]
ADFS uses SAML1.1 tokens by default IIRC - so not supporting that would miss the main reason we need SAML in the first place.

**Comment by leastprivilege** [comment]
Do you have an approx ETA when the WS-Fed part is complete - so we can build our own middleware.

**Comment by chrisdrobison** [comment]
As soon as this is done, I'm going to update the one I did until the
official one is out.

**Comment by leastprivilege** [comment]
great! I will help out!

**Comment by PinpointTownes** [comment]
> Do you think that would be OK?

I agree with @leastprivilege.

**Comment by brentschmaltz** [comment]
@leastprivilege @PinpointTownes alright, we will include Saml1. Should have an E2E in a week or so.

**Comment by rtaylor72** [comment]
Any update on this since it has been a week or so?  We are also waiting for this!

**Comment by brentschmaltz** [comment]
@rtaylor72 we are working in the WsFed topic branch. I expect to have an End to End within days. Basic xmldsig, saml2 tokens and wsfedmetadata. Once we the E2E is stable, we will merge into the 'dev' branch and start nightly signed builds pushed out to myget.

**Comment by leastprivilege** [comment]
..and? ;)

**Comment by brentschmaltz** [comment]
@leastprivilege it's moving along nicely... hit a snag with core will have to drop the netstandard 1.4 target for wsfed. Will have to use core2.0.

https://github.com/dotnet/corefx/issues/18682#issuecomment-296108348

**Comment by leastprivilege** [comment]
But full framework support is still planned? When do you merge to dev?

**Comment by brentschmaltz** [comment]
@leastprivilege full framework support is planned. We are currently testing against a forked version of katana. When we have that working, we will push to dev. It's close.

**Comment by brentschmaltz** [comment]
@leastprivilege we merged our WsFed topic branch into dev. It was a bit premature due to vacations. But justified as Katana and asp.net can start. We have a fork of Katana that we manually tested samples against here: https://github.com/lovemaths/AspNetKatana/tree/integration .  So I am closing this. I expect a couple of weeks work to complete the effort. Probably end of May or Early June.

**Comment by leastprivilege** [comment]
Update?

**Comment by brentschmaltz** [comment]
The dev branch has Saml2 reading, xml enveloped signature validation, wsfed metadata (light I admit).
We have successfully run against Katana, coreFx has put in a fix for C14n. 
We are now looking at end of June for a solid preview.

**Comment by DaleMckeown** [comment]
Looking forward to WS-Fed for ASP.NET core. ADFS signin is the last thing preventing me from pushing a load of new & upgraded sites.

**Comment by cbrhea** [comment]
Also (patiently) waiting for ADFS in core. It's the only reason we're avoiding the move to core for new projects at the moment.

Excited to see the preview!

**Comment by northof490** [comment]
Any update?

**Comment by brentschmaltz** [comment]
@northof490 we are moving along nicely. Our 5.2.0 drops on myget https://www.myget.org/gallery/azureadwebstacknightly have the latest.

We have the primitive support for WsFed metadata, Saml2Tokens with signature validation.

**Comment by WayneCBarker** [comment]
Haven't had an update in a while. Whats the current status?

**Comment by brentschmaltz** [comment]
@northof490 @WayneCBarker We will be issuing a preview with Katana (https://github.com/aspnet/AspNetKatana/) next week using the 5.2.0 bits. These will have the same API set that asp.net Core will use. The date for Asp.net Core WsFed support has not been set yet.

**Comment by Zoxive** [comment]
Is there an Issue for tracking WSTrust13 support? It looks like the latest 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs#L184
only supports WsTrust2005

You can see the old one would try WSTrust13 first.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs#L170

**Comment by brentschmaltz** [comment]
@Zoxive nice we need to support both.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/688

We are working our way through back-compat test to ensure SAML1 (4.x) == SAML1 (5.2.0), etc. We haven't gotten to WsFed yet.

We Saml1 we have
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/668

**Comment by lovemaths** [comment]
@Zoxive I made a PR https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/703 for WSTrust13 support, please take a look.

**Comment by brentschmaltz** [comment]
@leastprivilege @Zoxive @WayneCBarker @ClintRhea @northof490 @ClintRhea closing this as we dropped Preveiw1 and it has been integrated into Katana and Core. We will open issues as needed.

**Comment by domedellolio** [comment]
@brentschmaltz It is not clear for me if the support to WSFed/Saml has been released or not.
I mean, is there a middleware available?

**Comment by PinpointTownes** [comment]
@domedellolio the WS-Federation middleware is being ported ATM. You can track the progress here: https://github.com/aspnet/Security/tree/tratcher/wsfed. It will be released as an out-of-band package for ASP.NET Core 2.0.

**Comment by domedellolio** [comment]
@PinpointTownes same for SAML?

**Comment by PinpointTownes** [comment]
@domedellolio you mean the SAML 2.0 protocol? (SAMLP)

**Comment by domedellolio** [comment]
Yes of course @PinpointTownes

**Comment by PinpointTownes** [comment]
SAMLP has never been supported by Microsoft and AFAIK, there's no plan to support it in .NET Core.

**Comment by domedellolio** [comment]
You're right. I was looking to a way to authenticate with ADFS, so my question
Thanks @PinpointTownes

**Comment by brentschmaltz** [comment]
@PinpointTownes correct, we still have no POR for SAMLP.

**Comment by homam1** [comment]
Any update here guys ?
Supporting WSTrust13 in ASP.Net Core?
