### ISSUE TITLE
Singing Credentials - System.IdentityModel vs Microsoft.IdentityModel

### ISSUE THREAD

**Issue by dazinator** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#598]
Hello,

I am using the NuGet package `System.IdentityModel.Tokens.Jwt` version 5.1.3 targeting `.net 452`

When creating a `JwtSecurityToken` the `SigningCredentials` parameter expected is of type: `Microsoft.IdentityModel.Tokens.SigningCredentials`. 

I find this very non-intuitive, because there is also a `SigningCredentials` in the `System.IdentityModel.Tokens` namespace (from assembly `System.IdentityModel, Version=4.0.0.0`. and, it's natural to assume that types all in the `System.IdentityModel` namespace, would work cohesively together.

Is this only a temporary thing - i.e will these namespaces be fully unified at some point in the future?

Cheers

**Comment by brentschmaltz** [comment]
@dazinator for historical reasons we maintain JWT libraries in the System.IdentityModel.Tokens.Jwt namespace and assembly. All the other assemblies are in Microsoft.IdentityModel.xyz assemblies and namespaces. There was a discussion during the 5.x release to use Microsoft.IdentityModel.Tokens.Jwt, The arguments for keeping the S.IM.Tokens.Jwt won the day.

**Comment by brentschmaltz** [comment]
@dazinator  https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/595 when this issue is complete. There will be a release of Katana that will work with 5.2.0.

this will remove most of the issues.
feel free to reopen if you need to.

**Comment by dazinator** [comment]
Ok cheers- Thanks for explaination!
