### ISSUE TITLE
OpenId Azure AD B2C

### ISSUE THREAD

**Issue by mvscosta** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#599]
When use the Microsoft.IdentityModel.Protocol.Extensions, have been generate an error on concatenate the URL with policy, client id and parameters of openid.
Error only occur in pre release 2.0.0 beta 6.
example of url with the error: note for ?client_id
https://login.microsoftonline.com/XXXXX.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_signinsignup?client_id=36b246da-999f-4cf6-9ec9-718a10728b6b&redirect_uri=https%3a%2f%2flocalhost%3a44344%2f&response_mode=form_post&response_type=code+id_token....
the correct url that created using 1.0.4 was:
https://login.microsoftonline.com/XXXXXXonmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_signinsignup&client_id=36b246da-999f-4cf6-9ec9-718a10728b6b&redirect_uri=https%3a%2f%2flocalhost%3a44344%2f&response_mode=form_post&response_type=code+id_token.....

**Comment by brentschmaltz** [comment]
@mvscosta yes we did fix a bug where two '? ?' were generated. Is this an issue in a released product?

**Comment by brentschmaltz** [comment]
@mvscosta use latest version of M.IM from nuget. 
Reopen if still an issue.
