### ISSUE TITLE
Question- Where is documentation for this library?

### ISSUE THREAD

**Issue by mhamri** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#601]
I looked at wiki, readme.md and other places that I thought would find the latest version of this library but get disappointed. 

the readme.md instead of getting started has some non-informative information that really doesn't help to use this library. the developer needs to go through the test files and read one by one to learn how to use this library.

**Comment by brentschmaltz** [comment]
@mhamri where would you like us to start?

**Comment by mhamri** [comment]
if I wanted to add something to the documentation I would write how different method works to sign, to check for the different algorithms. how to use differents method to create a token. I saw there is a couple of creating methods that returning different types, all of them named as createSOMETHINGtoken() but the usage is not defined and it's up to the developer figure out and put the puzzle together, it's a guesswork

**Comment by brentschmaltz** [comment]
@mhamri thanks. This helps.

**Comment by brentschmaltz** [comment]
@brockallen I saw the confused emoji.  It is unlikely we can get all the documentation in for the 5.2.0 release.
So I am looking for suggestions on priority of documentations.

@mhamri thanks for your suggestion.

@2211868381 @ghost @grokit @nickolasacosta  @DUSK can you add your priorities here?

**Comment by 2211868381** [comment]
Documentation

**Comment by 2211868381** [comment]
@brentschmaltz Show us basic usage, such as how to create a token, how to select an algorithm, Encode And Decode a token, thank you.

**Comment by franklinyu** [comment]
I would also like API reference besides documentation, so that user can view API on browser without browsing the source code directly. I'm using Sandcastle in my C# projects, and I think it is the de-facto documentation generator.
<https://ewsoftware.github.io/SHFB/>
<https://github.com/EWSoftware/SHFB>

**Comment by jmprieur** [comment]
There is the start of a documentation in the [wiki](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki), with links to reference documentation for two of the assemblies

**Comment by franklinyu** [comment]
@jmprieur Thanks a lot for the pointer. Nevertheless I would like to see API documentation for `System.IdentityModel.Tokens.Jwt`.

**Comment by jmprieur** [comment]
@franklinyu : my impression is that we don't generate it currently. I'll make sure that it is generated (which will take a few days as the library needs to be emboarded in the pipeline)

**Comment by franklinyu** [comment]
In addition, what's the relationship between `System.IdentityModel.*` and `Microsoft.IdentityModel.*`? I thought `System.IdentityModel.Tokens.Jwt` should belong to [WIF API](https://docs.microsoft.com/en-us/dotnet/framework/security/wif-api-reference).

**Comment by jmprieur** [comment]
oh, sorry, I mis-read it. yes … System.IdentityModel.Tokens.Jwt is a different library? (not from this repo?) is it?

**Comment by franklinyu** [comment]
It is this library, and it is mentioned in the wiki page you pointed me to.

**Comment by stricq** [comment]
I've been searching all morning for example/tutorial code on how to use/implement SAML.  I cannot find ANYTHING.  There is no code.  Does anyone have anything anywhere on how to use SAML?

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki
Here is all we have.
