### ISSUE TITLE
Doesn't compile in Linux

### ISSUE THREAD

**Issue by mbearup** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#604]
The build.sh doesn't seem to work. By default it uses KoreBuild which pulls in its own .NET 2.0.0 environment...
- With **v2.0.0**, I get an error about missing Microsoft.DNX.props
- If I modify KoreBuild's cli.version to **1.0.3**, I get an error that the .Metaproj files are missing
- If I run dotnet migrate (**2.0.0**)to upgrade the .csproj files, the build actually gets pretty far, but then fails with **NuGet.targets(97,5): error : Unable to resolve 'System.IdentityModel.Tokens.Saml**.

If I can get this working I'll submit a PR, but it doesn't seem like this works out of the box.

**Comment by brentschmaltz** [comment]
@mbearup what version / branch of Wilson 4.x,  5.x?
We need to build cleanly on Linux

**Comment by mbearup** [comment]
@brentschmaltz 
- I've been working out of master
- I just tried release4x and there's no top-level build script (e.g. build.sh)
- I also tried 'release' and got the same error about the DNX.props file missing.

If there's another branch/tag i should try let me know.

**Comment by brentschmaltz** [comment]
@mbearup 4.x does is not a 'Core' project.

Master and Release should be fixed.

**Comment by brentschmaltz** [comment]
@mbearup sorry to be so long on this, we were getting our WsFed work into 5.2.0.
That build script assumes that dotnet.1.0.3 is installed in c:\dotnet. So we don't need to download the cli.
5.2.0 also uses csproj files.

**Comment by brentschmaltz** [comment]
@mbearup we completed our 5.2.0 build scripts and @lovemaths will work with you to get this fixed

**Comment by lovemaths** [comment]
@mbearup @brentschmaltz  Please install the latest dotnet sdk (dotnet-sdk-2.0.0-preview2-006497) from [here](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md), and try the build.sh in linuxbuild branch. I tested it on ubuntu 14.04. Please let me know if it works for you. Thank you.
