### ISSUE TITLE
Ambiguous reference Microsoft.IdentityModel.Protocols

### ISSUE THREAD

**Issue by moritzgloeckl** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#607]
Hi, 

I'm trying to add a library to an existing (rather large) project, which is using `Microsoft.IdentityModel.Protocols` and `Microsoft.IdentityModel.Protocols.OpenIdConnect`, but the library is depending on `Microsoft.IdentityModel.Protocol.Extensions`. Since both libraries feature a `ConfigurationManager` I'm getting an ambiguous reference error (CS0433).

Is there anything I can do about this? I can't use the library like this unfortunately... I'm open to changes to our project too.

Thanks very much!

**Comment by brentschmaltz** [comment]
@moritzgloeckl it sounds like you are mixing 4.x and 5.x assemblies.

M.IM.Protocols and M.IM.Protocols.OpenIdConnect can be used together.
M.IM.Protocol.Extensions cannot be used with the assemblies above as they have the same namespace.

Why do you need the new libraries?

**Comment by moritzgloeckl** [comment]
Hi @brentschmaltz, thanks for your answer. I'm trying to add [https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation](this library), to validate JWT tokens generated by their server. 

The problem is I tried to either just use M.IM.Protocols and M.IM.Protocols.OpenIdConnect for the library, or the other way round (my project using the dependency of the library), but that doesn't work since the `ConfigurationManager` class has different overloads. So I'm a bit clueless what I should do now...

Thanks

**Comment by moritzgloeckl** [comment]
Any updates?

**Comment by brentschmaltz** [comment]
@moritzgloeckl you can't mix 4.x and 5.x libraries.  So you will have to use the 4.x version.
