### ISSUE TITLE
Log error when JsonWebKey parameter types are not as expected

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#61]
Parameters are expected to be strings, if not we need to log the error.
see: public JsonWebKey(IDictionary<string, object> dictionary)

**Comment by brentschmaltz** [comment]
We should consider if the constructor that takes a dictionary makes sense first. we should lock on the design for Beta7.

**Comment by ChenYan98** [comment]
We don't fix it in 4.x since there is no logging module.
