### ISSUE TITLE
IDX10659 error when using X509Certficate to decrypt JWT token

### ISSUE THREAD

**Issue by theunrepentantgeek** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#615]
I've found that a JWT encrypted with `EncryptingCredentials` that wrap an `X509SecurityKey` cannot then be decrypted with those credentials. Instead, decryption throws a `SecurityTokenKeyWrapException`:

When running on .NET Core 1.1.0:

    Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException:
    IDX10659: UnwrapKey failed, exception from crypto operation:
    Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException:
    Key does not exist

When running on .NET Framework 4.7 (note how the inner exception differs):

    Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException:
    IDX10659: UnwrapKey failed, exception from crypto operation:
    System.Security.Cryptography.CryptographicException:
    Error occurred while decoding OAEP padding.

**Expectation**: A JWT encrypted with an `X509SecurityKey` should be decryptable with the exact same key.

I've reproduced the problem with multiple different X509Certficates, on three different machines, under two different user accounts, so I think I've eliminated the certificate as the source of the problem. Signing works properly from end to end in each test, which I think shows that both the public and private keys from the certificate are properly accessible.

## Reproduction

I've created [a full repro demonstrating the issue](https://github.com/theunrepentantgeek/jwt-x509certificate-encryption/commits/master), including console apps for both .NET Core and .NET Framework.

### Using a Custom Crypto Provider

In `CryptoProviderFactory.cs`, the method `CreateKeyWrapProvider(SecurityKey, string)` has a hard coded value for `willUnwrap` of **false**. I found that registering a custom implementation of `CryptoProviderFactory` with the `X509SecurityKey` worked:

    // Use
    var key = new X509SecurityKey(certificate)
    {
        // Custom provider to ensure we can unwrap the key properly when decrypting the token
        CryptoProviderFactory = new UnwrappingCryptoProviderFactory()
    };

    // Declaration
    public class UnwrappingCryptoProviderFactory: CryptoProviderFactory
    {
        public override KeyWrapProvider CreateKeyWrapProvider(SecurityKey key, string algorithm)
        {
            switch (key)
            {
                case X509SecurityKey x509Key:
                    return new RsaKeyWrapProvider(x509Key, algorithm, true);

                default:
                    return base.CreateKeyWrapProvider(key, algorithm);
            }
        }
    }

While this worked in my testing, I'm not sure of the other consequences of this approach and wouldn't necessarily recommend it in other contexts.

### Using an RsaSecurityKey

Replace the `X509SecurityKey` with an `RsaSecurityKey` created from the private key of the certificate:

    var key = new RsaSecurityKey(certificate.GetRSAPrivateKey());

This works with some certificates but not others, even though all have 2048 bit RSA keys.

A more compatible approach seems to be to export parameters from the certificate and use those to create the `RsaSecurityKey`:

    var key = new RsaSecurityKey(certificate.GetRSAPrivateKey().ExportParameters(true));

This works with all the certificates I tried.

**Comment by brentschmaltz** [comment]
@theunrepentantgeek excellent bug. I am on vacation until the 17th. Will address this when I get back.

**Comment by brentschmaltz** [comment]
@bartonjs do you have any insight?

**Comment by bartonjs** [comment]
`Key does not exist` almost always means "you're using CAPI to open a CNG key".  The fact that it comes from the corefx win32 internal exception type suggests to me that you're reading the certificate KEY_PROV_INFO property directly and trying to open the key directly.

But that shouldn't be a problem when using the RSA object directly... unless you're trying to manually build up the provider name and the key (container) name and call CngKey.Open; because on downlevel OSes that will fail to open CAPI keys through CNG because there's nowhere to specify the AT_EXCHANGE vs AT_SIGNATURE... (cert.GetRSAPrivateKey() goes through a function which has access to that data and passes the extra data to the CNG-open-a-CAPI-key function correctly).

 Or... maybe... you're having some sort of re-open that is having trouble with user vs machine keys?

@theunrepentantgeek If you have disclosable PFXes that succeed and fail for a differential diagnosis, that'd be helpful.  And also, knowing what OS you're on would be good.

**Comment by theunrepentantgeek** [comment]
Rest assured, I'm not trying to do anything clever. The last time I had a firm grasp on cryptography was 25 years ago at university. To say the state of the art has progressed is somewhat of an understatement.

Everything I'm doing is using the managed classes, no direct access to any OS API; my use case is cross platform, so I've stayed well within the bounds of .NET Core itself.

The `EncryptingCredentials` instance used by my [sample repo](https://github.com/theunrepentantgeek/jwt-x509certificate-encryption/commits/master) is created by this method:

```
public static EncryptingCredentials CreateCertificateEncryptionCredentials()
{
    var certificate = FindCertificate();
    var key = new X509SecurityKey(certificate);
    var result = new EncryptingCredentials(key, SecurityAlgorithms.RsaOAEP, SecurityAlgorithms.Aes256CbcHmacSha512);
    return result;
}
```
I've reproduced the error on these OSs:
* Windows 10 build 16193 (Insider Fast Ring as of 18/5/2017)
* Windows 10 build 15063 (Insider Slow Ring as of 18/5/2017)
* Windows Server 2012 (not sure of the exact version, my colleague is not at his desk)

I'm pretty sure the problem isn't specific to a given certificate - in desperation, I wrote a test case that queried for every single certificate on my machine and tried them all. Results were consistent - none of them worked.

**Comment by brentschmaltz** [comment]
@theunrepentantgeek I cloned the sample and made a small change in KeyFactory at
https://github.com/theunrepentantgeek/jwt-x509certificate-encryption/blob/master/library/KeyFactory.cs#L46  Essentially, creating an X509Certificate2 in memory to rule out it has to do with a cert.  new Driver().TokenTest() succeeded.

@bartonjs does this fit with what you are thinking?

            ```
string SelfSigned2048_SHA256 = @"MIIKYwIBAzCCCiMGCSqGSIb3DQEHAaCCChQEggoQMIIKDDCCBg0GCSqGSIb3DQEHAaCCBf4EggX6MIIF9jCCBfIGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhxE338m1L6/AICB9AEggTYMrXEnAoqfJTuvlpJieTu8LlJLL74PWG3GJmm+Rv45yMFjm332rVZKdLEOFmigUGGMfjk7uFBBLSpm3L/73g2LdNBFhMFnmdWlw0Nzs/Q4pxmHN+b9YPWv8KpiFc/CIUl30Nqf7NHk1CdM026iuY/eJlIO6eM8jWz/NP4pK+kZav5kvQIrZ6n1XYstw7Fw8Ils4pCGUsiFwNGFuSVLCRwxHqvEUgVmV3npUbCwKATSRNcs23LGHo4oZO1sj4u7cT66ke5Va/cGLrIPz4d+VelRkrPCcbgFi4bo24aA9b8dayMV7olDF+hbHTH9pYfPV5xUejsfGeX4BM7cH6Kp7jKKXJQq9MD26uEsrK9Bt4eoO1n4fK59+u0qSI7329ExsPA76uL9E5Xd+aDUpOUyJRCtnjY/Nz9IO/6zR5wdL72ux8dEzJAYqRgpmwIgyaXE7CYqmc9VHE65zddcpOFicVIafXfftAmWAPuyvVxkij04uAlSH2x0z+YbHG3gSl8KXpzfRmLeTgI1FxX6JyIV5OV8sxmvd99pjnosT7Y4mtNooDhx3wZVuPSPb7RjIqFuWibEyFLeWbCZ418GNuTS1CjpVG9M+i1n3P4WACchPkiSSYD5U9bi/UiFIM2yrAzPHpfuaXshhorbut3n/WBXLHbW/RAqOWMeAHHiJNtyq2okTM6pqp09HGjc3TbDVzyiA5EgfEdMPdXMNDZP7/uVFk+HQAm35Mrz+enMHjnLh4d8fy2yRuMs1CTLrQrS3Xh1ZbUn6EJ5EaZCMjoGd4siBIOuQvrxRwYfpnRB+OYMetkpUtMFCceMTS809zAS+rXxZ9Nfnk1q5c73+f0p9UZTLzajwNhPMhtQL1xYA2tVobVA+6hSxb7bgiH7+2qhoTBkmwzEkfXg7ALL2erBWHJJn5Hr8e4C3OdDFo/qCfA1E9IK3qIyLTzbhQnNRD+6KKTPP2ynGCJz2oIn6gmh29jKLwZc69FHMHdikevk58EXzKmHK9sy6YAFXQ4pBRKpaNwiQiNbUJsO/WYQ9CSoKRQjBOs7l1UbB2roYRXuUyZ+pLjOXnzaHOjF4nrNL8PP6XnCfJUXfmpQpaY/Q0zT4R1Zw+lXjfKoVd5JFPoWjoHGNQyFnvlyyUldB3jHQptbtUjV4fkeKXPhqcjn3QMSwN9nbwqiig88fiItVJFmDHemywfyiEtsDwc5yann0vNquegT/W9G0dq/7+z3e8V9e8040RpdepKiHH4o9cmyIT8gUNkXkJXsN9ZNaekUCGuhTqpzM2K3+zW1K7lTLq9/w3malhfIYw0mdHx2bz6nkyf6XezCQt7Fwc263r+YbAV16hjJJaTZcIqggoe5Al8B48mcCmGwNBF+Le/4/yoArzxlLbbljG3xIODJa+Vh01lWqK09mRbNpUjUtHswLuve48vabA2aZZmoxlsN3e7wLywrZ+Tvg4zg8R2ZzjjCXHkBI7qtZZZxMe+x2w3NbTnN54Gk1U/Pg3nVj242qCWR43A1Cp6QRrhi2fsVoNZCuHSUkykhH6q3Y/06OdgVyCyboXh0XnttlLbNLp3Wd8E0Hzr0WEm/Tdv1VDNu5R3S73VX1WIJ6z3jyTvm9JkzJFAxrk0mwAzBOSS34eYRQnhWFCT8tqHWIAzHyH+YJ9RmTGB4DANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBbBgkqhkiG9w0BCRQxTh5MAHsANwBBADIAMABDAEMAOQAzAC0AOABFAEEAMQAtADQAQQA2ADYALQA4AEEAMwA4AC0AQQA2ADAAQwAyADUANAA2ADEANwA3ADAAfTBdBgkrBgEEAYI3EQExUB5OAE0AaQBjAHIAbwBzAG8AZgB0ACAAUwB0AHIAbwBuAGcAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUAByAG8AdgBpAGQAZQByMIID9wYJKoZIhvcNAQcGoIID6DCCA+QCAQAwggPdBgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBBjAOBAhbuVGIv2XFPQICB9CAggOwUo/TgmdO5qDdDqOguXP1p5/tdAu8BlOnMbLQCB4NJ+VU3cnmzYAJ64TlkLqXGCww+z6aKVqtEODud5KMwVuUkX1Eu9Q+kLpMF1y6chkCVmfmMOzU0PsfMWghYSp4FEtWuYNzVQ869qrMCpVDoX8jUroUVkX3BV8sVUV7ufFYdFbwo++c/yCtrHxw4/oagjkXZXV9QBns+fLraJU/mO7isZJwHjscAZhckTdHGEr7hOqD/sHLPXYAgYCmkplH6aSNdyc6VmFXxmpKYFwlGnSA+xlJNcwrfyrljg5iUjpFMCcUuuOhjDCkIgTYsyT48uOgkoBLQzuQ8Oua3tpG1DQ6x2HJSHhQaILpNMZ6nWUrt9YRjdJHdCtdZGN/FPrASd8Vi68XIHu4dAy9zXKSL7GxsBCXXTE/XYca0v3rOnpvye1yt3zxssKPoMlgSUxsoUj9Moqyt+bjYJqV8tJwGt1xpB3k+QgpkmJnMY2i18r9sm59q2t+mWFfFwq/bIozNbzPBNzqq1q4fl80/7qEX046+KybgjaUrIAPiBYsTlAGNMfUAPuO/vb/FTq5Pk9SXepEqc+NkXrkOGzskOALefD9+DWDOy4j1loCvIXjLb1B9e4C5AIqzU4Sxq9YaDgVIVSK9GoVriaq8WQUSBktPruQD1rgPiHr94LZ0RgEBAReO9x3ljCXon6/sJEFUR024zbmEKol+HuY7HMPRzY5113nodOMYsYMFK5G+g4x5WtANN/qnoV16laBqJvQJ0iCj3LH8j0ljCPEMFUl87/Yp1I6SYrD9CycVNo3GuXdNFxKlKCUlf5CVjPWEhfM1vEvUSqwQuPEJ8gj9zK2pK9RpCV3E3Jo+47uNKYQQlh/fJd5ONAkpMchs303ojw7wppwQPqXavaHWX3emiZmR/fMHpVH812p8pZDdKTMmlk2gHjN7ysY3eBkWQTRTNgbrR2cJ+NIZjU85RA7/5Nu8630y1zBEe24RShio7yQjFawF1sdzySyWAl+qOMm7/x488qpfMQet7BzSuFPXqt3HCcH2vH2h2QFLgSA6/6Wx5XVeSQJ0R0rmS0cqAKlh9kqsX2EriG/dz2BxXv3XRymN2vMC9UOWWwwaxRh6DJv/UTHLL+4p6rLDC1GXZ/O4TVqKxNe9ShpzJx2JGwBl5VW4Rqo4UNTZTMn/L6xpfcdtVjpV+u5dD6QGBL57duQg9zqlJgMRbm/zjbC80fMjHpjbEUkf9qkl3mqEFp/vtrFiMCH4wH7bKswNzAfMAcGBSsOAwIaBBTjZISkPzPwKqSDK4fPHZMa83IUXgQUt9xlRgPPpTLoO5CUzqtQAjPN124=";
            return new X509Certificate2(Convert.FromBase64String(SelfSigned2048_SHA256), "SelfSigned2048_SHA256", X509KeyStorageFlags.PersistKeySet);

```

**Comment by lovemaths** [comment]
@theunrepentantgeek We found the bug in our code and we will fix it. Thank you.

**Comment by brentschmaltz** [comment]
@theunrepentantgeek thanks!
Your workaround is perfectly fine to use.

**Comment by theunrepentantgeek** [comment]
@brentschmaltz Thanks for the confirmation; I'll leave it in my repo for now but will remove it when your NuGet package is updated.
