### ISSUE TITLE
SecurityTokenHandlerCollectionExtensions question

### ISSUE THREAD

**Issue by chrisdrobison** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#617]
I'm trying to update my asp.net core wsfed library with the new 5.2 nightlies. There used to be a library called Microsoft.IdentityModel.Protocol.Extensions, but I'm guessing based off the new changes that this is going away. Has SecurityTokenHandlerCollectionExtensions been moved or something else taken it's place?

**Comment by brentschmaltz** [comment]
@chrisdrobison M.IM.ProtocolExtensions was a collection of types that were needed for wrapping S.IM and providing OIDC support for Katana. Yes, we did drop the "SecurityTokenHandlerCollectionExtensions and moved the types into well defined assemblies. M.IM.Tokens, M.IM.Token.Saml, etc.

There is an update to Katana that will work with 5.2.0 being planned. Release date is not finalized yet.
