### ISSUE TITLE
Add support for additional key types in JsonWebKeySet 

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#62]
Currently RSA is the only supported key type, that is 'Kty must equal JsonWebAlgorithmsKeyTypes.RSA'
We need to add support for
1. x5t
2. Symmetric
3. ECH

**Comment by tushargupta51** [comment]
It wont be breaking change, pushing it out to RC2

**Comment by brentschmaltz** [comment]
@tushargupta51 check, but I think we are done.
