### ISSUE TITLE
JWT custom validation

### ISSUE THREAD

**Issue by zixiangx** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#622]
Hi,

Would like to check, is there an appropriate method to overrride in the Security Handler that allows me to pass in additional validation, maybe in the ValidateToken method?

More specifically, I would like to verify the JTI against a blacklist. I have previously constructed this validation as a separate middleware but my the responses were shaped by the JwtBearerAuthentication middleware after the response returns back overwriting any custom status code / messages I've passed back.

Using a custom policy based authentication also returns the wrong status code with the same issues, so I was thinking of doing it directly inside the security handler.

**Comment by brentschmaltz** [comment]
@zixiangx there is no general delegate for checking if the token is appropriate for a specific purpose. Sometimes that is related to the method called OR the parameters passed to the method.

You can override ValidateToken, call the base, check the ClaimsPrincipal for a specific claim.
If you create a derived TokenValidationParameters type, this will be passed to this method and you can hang any thing you need on that.

Please re-open if you have any additional questions.

**Comment by brentschmaltz** [comment]
@zixiangx I opened https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/623 there seemed to be a whole here.

**Comment by zixiangx** [comment]
Thanks @brentschmaltz, will follow [#623](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/623)
