### ISSUE TITLE
An idea about discovery document to find issuer and key material

### ISSUE THREAD

**Issue by risogolo** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#635]
Why functionality for discovery document to find issuer and key material is not incorporated into library and must be done manually like [HERE](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcManual/Controllers/HomeController.cs) method ValidateIdentityToken. It took me 2 days to find out how to do it, I was still expecting that such functionality must be already in the library itself.

**Comment by brentschmaltz** [comment]
@risogolo we currently have code in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L90 that retrieves metadata from the discovery endpoint. Asp.net has hooked simplified the discovery by layering on top of this, by allowing the setting of just the Authority. https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L102 
What did you have to do?

**Comment by risogolo** [comment]
But my code does not run within aspnetcore http pipeline, then you need to figure out how to do reach discovery document, download certificate and translate to the key and that is not straightforward.

**Comment by leastprivilege** [comment]
You are confusing two libraries here. The above snippet is from my `DiscoveryClient` library. 
Microsoft has the `ConfigurationManager<OpenIdConnectConfiguration>`. 

Both can be used without the pipeline.

**Comment by risogolo** [comment]
Yep, thank you, it helped
