### ISSUE TITLE
How to modify code after library version change

### ISSUE THREAD

**Issue by phatcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#636]
The sample code for Azure B2C (https://docs.microsoft.com/en-gb/azure/active-directory-b2c/active-directory-b2c-devquickstarts-api-dotnet) uses the following to wire up OAuth to JWT

            app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
            {
                // This SecurityTokenProvider fetches the Azure AD B2C metadata & signing keys from the OpenIDConnect metadata endpoint
                AccessTokenFormat = new JwtFormat(tvps, new OpenIdConnectCachingSecurityTokenProvider(String.Format(AadInstance, Tenant, DefaultPolicy)))
            });

However, this code doesn't compile if the nuget package is updated to the latest - what's the equivalent code please.

**Comment by Tratcher** [comment]
You can't. https://github.com/aspnet/AspNetKatana/issues/7. We're working on it.

**Comment by brentschmaltz** [comment]
@phatcher you can follow the work in the 'dev' branch as we pull in WsFed support. The 5.2.0 release will align Katana with Asp.Net core reducing this frustration.
