### ISSUE TITLE
Unclear on how you would get a JwtSecurityToken, Securely

### ISSUE THREAD

**Issue by DSUK** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#637]
Suppose I have a public key and I received a jwt string randomly from the internet
(for the sake of argument you want to write the function `JwtSecurityToken GetVerifiedJwt(string jwtString, RsaSecurityKey securityKey)` and to throw an exception on an invalid jwt  or "alg": "none")

I know you can write `new JwtSecurityToken(jwtString)` but that wouldn't detect whether the jwt was falsified.

**Comment by brentschmaltz** [comment]
@DSUK I owe you a sample.

**Comment by brentschmaltz** [comment]
@DSUK I am moving all questions about documentation into #601.

Could you chime in on what your priorities would be?
