### ISSUE TITLE
Encrypted JWTs?

### ISSUE THREAD

**Issue by jacobslusser** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#640]
I'm looking to create an encrypted JWT and I'm a little lost.

**Option 1:** Articles like this one suggest just encrypting the string representation of a JWT:
[https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java#Token_information_disclosure](https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java#Token_information_disclosure)

**Option 2:** However, this article suggests nesting a signed JWT inside an encrypted JWT:
[https://connect2id.com/products/nimbus-jose-jwt/examples/signed-and-encrypted-jwt](https://connect2id.com/products/nimbus-jose-jwt/examples/signed-and-encrypted-jwt)

My preference would be to use option 2 as I assume this is the correct way of encrypting a JWT. I can't seem to find the right overloads and/or properties in the `JwtSecurityToken` object though to make it work. On the `JwtHeader` I see a property called `Cty` which is great, because I need to use that to set the content type, and on the `JwtSecurityToken` I see a property called `InnerToken` which looks promising. I don't, however, know how to set that property and/or create a `JwtPayload` that wraps an existing JWT.

Has anybody else done this before and able to provide a sample?

**Comment by brentschmaltz** [comment]
@jacobslusser we have unit tests here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/test/System.IdentityModel.Tokens.Jwt.Tests/CreateAndValidateTokens.cs#L620

The model is when calling https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L493

If EncryptingCredentials is set, then a JWE will be created.

**Comment by jacobslusser** [comment]
@brentschmaltz, thanks for your response. I have some **follow-up questions**.

Funny you mention that... after posting I persisted for another couple hours and found the `JwtSecurityTokenHandler.CreateJwtSecurityToken` method -- a parent to the one you mentioned. As far as I can tell, that is the only way to create a signed and encrypted token because all the other methods seem to want `SigningCredentials` *or* `EncryptingCredentials`, but not both. **Perhaps you could show me otherwise?**

So the code I currently have is like this:
```cs
var now = DateTime.UtcNow;
var key = Encoding.UTF8.GetBytes("C9CB44D98642A7062A0D39B94B6CDC1E54276F2E7CFFBF44288CEE73C08A8A65");
var securityKey = new SymmetricSecurityKey(key);

var claims = new[]
{
    new Claim(JwtRegisteredClaimNames.Sub, "1234567890"),
    new Claim("name", "John Doe"),
    new Claim("admin", "true", ClaimValueTypes.Boolean)
};

var jwt = new JwtSecurityTokenHandler().CreateJwtSecurityToken(
    issuer: "example.com",
    audience: "example.com",
    subject: new ClaimsIdentity(claims),
    expires: now.AddMinutes(30),
    issuedAt: now,
    signingCredentials: new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256),
    encryptingCredentials: new EncryptingCredentials(securityKey, JwtConstants.DirectKeyUseAlg, SecurityAlgorithms.Aes256CbcHmacSha512));

var token = new JwtSecurityTokenHandler().WriteToken(jwt);

Console.WriteLine("Encrypted JWT: " + new JwtSecurityTokenHandler().WriteToken(jwt));

Console.WriteLine();
Console.WriteLine("Push ENTER to exit.");
Console.ReadLine();

```

The result is:
```
Encrypted JWT: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwidHlwIjoiSldUIn0..kv71w0GLaULzcsdYyuOFSw.96gllkIz90WGtYt03kwqaEa4pUsODH0dpv0hh8HmjoukVvCPgT-apO_zUQwXO1dJkQbhtXqOCBjoEtqG-dpziUgfaZEz_4_XXpyNj8_v24mx8atPfcRDbTgHpgKSY2iZ-5thiXrSojmpVW6vIWksp7uKRN9BUA-ZC-QtLiUpyMVPP40Ft341bKfLF2jaAiYcwsRsUszb7KFE3Xy7fjwarlXemqGQbH3JamZVQo4vxxobg9z6BB0853AoBXewsV4V5GPFBXCv7WURblw3kp3Epe-lnHjdUbIY3kOhWeaPKDzoCAelUMqAoszvjQ1_1mAxDmV6rufaAB6kBLveDd2V4xM6leoFP3bZaP7sWiCJjYc.JuXpkjiUIj6BQqLgEW4W2NAH9Hr5SoHXYTd26TkdshI
```

As you can see, the second part of the JWE -- which as I understand is the encrypted key -- is empty. **Why is that?**

Finally, I would love some clarification around the choice of encryption algorithms. I'm trying to create a JWE using AES-GCM and AAD, as mentioned in my first link, however, I'm not sure if .NET supports this algorithm. **Do you know?**

**Comment by brentschmaltz** [comment]
@jacobslusser if you look at the protected header you will see the alg == dir. This is why the encrypted key is missing. It is assumed that the recipient will know the key. When you specified: JwtConstants.DirectKeyUseAlg that instructed the runtime to select 'dir'. 

The code to review to understand is here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L580

**Comment by jacobslusser** [comment]
@brentschmaltz thanks for your help. Does the code I'm using otherwise look okay for creating an encrypted token -- if I was the creator and consumer?

**Comment by brentschmaltz** [comment]
@jacobslusser your code seems fine. 
I would recommend using the API's that take a SecurityTokenDescriptor. Aside from allowing you to stash items. We are adding api's in 5.2.0 for handling ZIP and other content types (cty). @lovemaths found that it's hard to push delegates etc through the call stack. Similar to TokenValidationParameters that provide a simple extensibility, we will probably adds those hooks in SecurityTokenDescriptor.

**Comment by brentschmaltz** [comment]
@jacobslusser I will close this now. Please feel free to re-open if you need additional info.
