### ISSUE TITLE
Should we fault if the 'assertion id' is not per spec?

### ISSUE THREAD

**Issue by ChenYan98** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#647]

**Comment by brentschmaltz** [comment]
This has caused some issues in the past where this would fail. but given the token is signed by a trusted issuer, we should perhaps be lax here and accept as the issuer set it.

**Comment by brentschmaltz** [comment]
@ChenYan98 have a look at this one.

**Comment by ChenYan98** [comment]
Agree

**Comment by brockallen** [comment]
What did  you decide? As a side note, I've done tons of integrations with crappy implementations that don't use URIs and I've had to do ugly workarounds to make it validate.

**Comment by brentschmaltz** [comment]
@brockallen we landed on: lax when receiving, spec compliant when creating.
