### ISSUE TITLE
Issue with .net core 2.0 JWT

### ISSUE THREAD

**Issue by nicksav** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#649]
Guys, time to time getting 500 Error. When looking as AI:
![image](https://user-images.githubusercontent.com/9266365/28145137-46b571de-67b3-11e7-8721-ff4a0ae8f685.png)

Any idea what might be wrong here?

**Comment by brentschmaltz** [comment]
@nicksav could be a bug. Can you sent me the jwt?

**Comment by brentschmaltz** [comment]
@nicksav This is not an IdentityModel bug. The null ref is thrown inside System.Text.

I opened: https://github.com/dotnet/corefx/issues/22646
