### ISSUE TITLE
Naming scheme: System.IdentityModel vs Microsoft.IdentityModel

### ISSUE THREAD

**Issue by thuannguy** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#651]
Similarly to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/598, but in a wider scope: IdentityModel had the Microsoft.IdentityModel namespace back to .Net 3.5 time, then it was changed to the System.IdentityModel namespace. After checking the latest source in the https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/xml branch, I found out that all assemblies have the Microsoft.IdentityModel namespace again which triggers a few questions that I hope someone in the team can help me answer

- Is this repository the equivalent of System.IdentityModel found in .Net 4.x but for .Net Core 2.x?
- Will Microsoft.IdentityModel be the official namespace from now on?
- Do this repo accept PR from non-MS developers?

Thank you for reading :)

**Comment by brentschmaltz** [comment]
@thuannguy Microsoft.IdentityModel is not the complete equivalent of System.IdentityModel in .Net. It has the parts for OAuth, OpenIdConnect, WsFed with support for Jwt, Saml1 and Saml2 creation and validation. System.IdentityModel will continue to be supported for desktop apps. Yes, Microsoft.IdentityModel provides support for .Net Core and currently these are the assemblies that Asp.Net and others use. I am avoiding using the word official, but the is where our current effort if focused.

We welcome PR's, there is a form you need to sign. We have just standardized on a new Testing model that is making it's way through our repo. Older work is being converted. Saml and Xml tests in the dev branch are the best place to view the model.

**Comment by brentschmaltz** [comment]
@thuannguy let us know if you have any additional questions.

**Comment by thuannguy** [comment]
Thank you for a quick response :) I'm developing products around System.IdentityModel heavily so it's good me to know what the "roadmap" is :)
