### ISSUE TITLE
Add a handler that takes in JSON and returns JSON

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#660]
Currently our JwtSecurityTokenHandler returns a ClaimsPrincipal that has a translated representation of the JSON that was found in the JWT. For some customers, it is more natural to work with JSON layer.

This feature would introduce the ability to work with JSON directly.
Hooks could be added to return ClaimsPrincipal if it makes sense.

**Comment by RussKie** [comment]
There is also another issue which I raised a year ago - https://github.com/dotnet/corefx/issues/11082#issuecomment-242279236

**Comment by brentschmaltz** [comment]
@RussKie we would need make a couple of changes to support something like: FooClaim : Claim, FooClaimsPrincipal flowing though the asp.net runtime (or any other runtime). 
Currently asp.net serializes  using https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/Data/TicketSerializer.cs#L117. A FooTicketSerializer could be used. Alternatively, we added some APIs that can facilitate the serialization: https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/ClaimsPrincipal.cs#L549, if ASP.net used these, we could figure something out. @PinpointTownes  found some bugs, but those could be fixes.

**Comment by brentschmaltz** [comment]
see https://github.com/dotnet/corefxlab/issues/2017
