### ISSUE TITLE
Add tests to ensure 5.2.0 tokens are compatible with 4.x tokens.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#668]
We will need to ensure the Saml tokens generated by 5.2.0 are the same as 4.x. In order to do this we will need to create an assembly that uses 4.x and 5.2.0 at the same time.

What we need to see is
1. that given a set of SecurityTokenDescriptor, both run-times will create the same tokens.
2. given Saml tokens (1 and 2), the ClaimsIdentity created will be the same.

To do this we will need to create an assembly that links the references directly dll's as nuget will not work with it's 'target' matching.

We may need to have this assembly outside of our normal testing environment.
I would recommend starting with a separate project and then folding it in. 
Most important is to get it working, then we can think about how we automate the test runs.

**Comment by brentschmaltz** [comment]
We finished the first part for AttributeStatement.
When https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/689 is complete, we can finish 2 and compare ClaimsIdentities.

**Comment by brentschmaltz** [comment]
This was scoped to AuthenticationStatement generated by SecurityTokenDescriptor. 
Please close this and open two new issues.
1. For AuthenticationStatement, AuthorizaitonDecisionStatements. P2
2. JWT vs. SAML2 vs Saml1 in 5.x. (tests are disable) P1

**Comment by ChenYan98** [comment]
Create issue #724 and #725.
