### ISSUE TITLE
Add support for WsTrust 1.3 when processing WsFedMessage

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#688]
Currently we only support trust 20005.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs#L184
only supports WsTrust2005

You can see the old one would try WSTrust13 first.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs#L170

**Comment by Zoxive** [comment]
#703 is merged. This should be good to go!

**Comment by homam1** [comment]
@Zoxive  what about ASP.Net core?
