### ISSUE TITLE
Finish ValidateToken for SamlSecurityTokenHandler

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#689]
We put ValidateToken completion on hold for until we had support for writing SamlToken with signatures.
Now that that work is available, we should finish ValidateToken for SamlTokens.
The Framework code is in place, we need to make sure we have:
1. Enough test coverage
2. Comments are correct.
3. Validate returns expected ClaimsPrincipal.

**Comment by ChenYan98** [comment]
#715
