### ISSUE TITLE
where's the documentation ?

### ISSUE THREAD

**Issue by 2211868381** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#697]
where's the documentation ?
Thank you

**Comment by brentschmaltz** [comment]
@2211868381 you are not the only one asking this.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/601

We can't get it all done at once, can you help us help you by providing some priority?

Please add comments to #601
