### ISSUE TITLE
The URI attribute in Reference element must start with #

### ISSUE THREAD

**Issue by ChenYan98** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#704]
We didn't check if the URI start with #. Please check https://www.oasis-open.org/committees/download.php/3406/oasis-sstc-saml-core-1.1.pdf
5.4.2 for more detail.

**Comment by brentschmaltz** [comment]
For sure we should be strict on writing.
On receiving, I am not so sure. If the receiver trusts the IdentityProvider then the absence of a '#' is really insignificant. The token will be validated.
This falls into the category of strict on send, lax on receive.
