### ISSUE TITLE
digital signature: sign data on server and validate on client side

### ISSUE THREAD

**Issue by assafb81** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#717]
Hi,
my goal is to use digital signature in order to prevent MITM attack.
my private key and public key are saved in PEM files.

I have a code in client side that is working.
I can sign and verify data  with jsrsasign package.
sign:
```
const privKey = rsa.KEYUTIL.getKey(PRIVATE_KEY);
const sig = new rsa.Signature({ alg: 'SHA256withRSA' });
sig.init(privKey);
sig.updateString(JSON.stringify(data));
const sigValue = sig.sign();
```

verify:
```
const pubKey = rsa.KEYUTIL.getKey(PUBLIC_KEY);
const rsaObj = new rsa.Signature({ alg: 'SHA256withRSA' });
rsaObj.init(pubKey);
rsaObj.updateString(JSON.stringify(data));
const isValid = rsaObj.verify(signature);
```
How can I sign (using private key in PEM file and alg 'SHA256withRSA') in the server side using System.IdentityModel.Tokens.Jwt in my server side written in C#.
 
--note: currently I tried using bouncyCastle to sign on the server side (in C#) with no luck, can't verify data.

**Comment by brentschmaltz** [comment]
The PEM key will need to be translated into a SecurityKey that IdentityModel understands. Looks like rsa.KEYUTIL seems to do that.
Then this sample may help you: https://github.com/brentschmaltz/Wilson5x/tree/master/src/CreateTokens

**Comment by assafb81** [comment]
Hi,
I looked at the example you send me...it seems to be a lot of trouble only for signing.
I tried using bouncyCaslte library on the server side - converting PEM private key AsymmetricKeyParameter that bouncyCastle understands. 
But the verification fails on the client side.

**Comment by brentschmaltz** [comment]
@assafb81 can you post a link to assafb81? Perhaps we should have first class support for PEM keys.

**Comment by assafb81** [comment]
the link to : [https://www.bouncycastle.org/csharp/index.html](url)
I did not find forum/support link in that site

**Comment by assafb81** [comment]
The issue is resolved. 
In a nutshell: I am using jose-jwt package in the server side in order to create a Token in the server side, the data is stored in the sub property in the Claims section.
On the client side I verify the token using jsrsasign package.
