### ISSUE TITLE
Add support for Saml2 EncryptedAssertion

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#734]
Saml2 tokens can have encrypted assertions, we didn't get them into 5.2.0.

**Comment by Veikedo** [comment]
Up
ps. Saml1 token also can be encrypted

**Comment by Extant-1** [comment]
+1

This feature would be very much welcome to avoid having to write a custom TokenValidator

**Comment by brentschmaltz** [comment]
@Veikedo @Extant-1 I marked this for 5.2.3 (June 2018). It may be a stretch, I'll cost it out.

**Comment by brentschmaltz** [comment]
Moved to 5.2.4

**Comment by brentschmaltz** [comment]
No need for this now, removing until needed.
