### ISSUE TITLE
Saml2 Metadata support plans?

### ISSUE THREAD

**Issue by AndersAbel** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#758]
I'm working on porting the Kentor.AuthServices SAML2 P library and have got stuck on the Metadata classes. What are the plans to implement those? As far as I can see there is no MetadataSerializer available (yet) and a lot of the classes for metadata representation (e.g. ContactPerson) are missing.

**Comment by brentschmaltz** [comment]
@AndersAbel for our 5.2.0 release we are focused on support for consuming WsFed messages. For that we need: TokenEndpoint, Keys and Issuer. We may extend that for vNext. I suggest you open an issue asking for full or subset Metadata support. I can then mark the issue with "User reported".

**Comment by AndersAbel** [comment]
@brentschmaltz thanks for quick response. I'll focus on reading the endpoints for now and get back to porting the full metadata support once #759 has been discussed.
