### ISSUE TITLE
Add api to create new RSASecurityKey

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#762]
For POP scenarios it is common to require a RSA key.
This API would abstract the underlying crypto operators that change for different OS's and runtimes (Core vs. Desktop)

**Comment by GeoK** [comment]
@brentschmaltz - By looking at the description, I believe that this issue has already been resolved.

**Comment by brentschmaltz** [comment]
yep
