### ISSUE TITLE
The DSigSerializer read methods are not consistent with those of WsFederationMetadataSerializer

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#766]
Currently, the DSigSerializer read methods (ex. ReadIssuerSerial()) return void, but those of WsFederationMetadataSerializer all return the type that was read. The methods in DSigSerializer should be changed to behave in a similar way.

**Comment by brentschmaltz** [comment]
We should fix this for 5.2.0 release
