### ISSUE TITLE
ValidateToken throws undocumented FormatException

### ISSUE THREAD

**Issue by vanillajonathan** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#780]
The `ValidateToken` method in the `JwtSecurityTokenHandler` class throws a undocumented `FormatException`.

Example input: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.f`

> FormatException: IDX14700: Unable to decode: 'f' as Base64url encoded string.

**Comment by vanillajonathan** [comment]
The method documentation does not declare the possibility of `SecurityTokenValidationException` either.

**Comment by brentschmaltz** [comment]
@vanillajonathan what is the expectation here? The exception is thrown in ReadToken outside of ValidateToken.

**Comment by vanillajonathan** [comment]
@brentschmaltz That the `ValidateToken` method internally calls the `ReadToken` method is something internal to your API and none of my concern as an user of the API.
I called `ValidateToken`, not `ReadToken`.

When I call a method, such as `ValidateToken` then I read the documentation for the method to know which exceptions I can expect.

I called `ValidateToken` and the application crashed with a `FormatException` that caught me off guard! Whoa, nowhere did the documentation mention that one.

I expect methods to document any exceptions that may be thrown by calling that method.

**Comment by brentschmaltz** [comment]
@vanillajonathan the transitive closure of all exceptions is hard. But, exceptions that an internal library method throws should be in scope. 
I agree, we should document this exception in ValidateToken OR better yet, catch the exception ReadToken throws, wrap it inside SecurityTokenValidationException.

**Comment by vanillajonathan** [comment]
@brentschmaltz Oh yeah, about `SecurityTokenValidationException`, that's not documented either. 😄
Only `ArgumentNullException` and `ArgumentException` are documented.

Not sure whether validation failure ought to be considered something exceptional either.

**Comment by brentschmaltz** [comment]
@vanillajonathan SecurityTokenValidationException is documented on ValidateSignature. If every exception that is by a caller, then the summary comments would get unruly.  What I suggest is that we state that we throw: ArgumentException, ArgumentNullException, or SecurityTokenValidationException (or derived). Anything else would be wrapped.

`Not sure whether validation failure ought to be considered something exceptional either.`

An exception means that the operation was unable to be completed. If we had a `TryValidate`, throwing would be the wrong thing.

**Comment by vanillajonathan** [comment]
@brentschmaltz I new up an instance of the `JwtSecurityTokenHandler` class, perhaps I press F12 and check what's in there. I call the public method `ValidateToken`. All I see is the method signature and the XML documentation. There is no way for me to know that it internally calls `ValidateSignature` since I didn't write the method and I don't see the code.

A developer can't be expected to go on GitHub and read the source code just to find out the exceptions to expect.

**Comment by brentschmaltz** [comment]
@vanillajonathan I agree that the user should know what exceptions to expect and what they mean. Let me see what we can do.

**Comment by brentschmaltz** [comment]
@vanillajonathan @mafurman given that this is the main entry point for users.
Can we add a "remarks" section that will contain the exceptions in the individual subcalls and write somethining like: This method calls: ValidateAudience that can throw: 
You can find most of the call graph in M.IM.Tokens/Validators.cs
 /// <exception cref="SecurityTokenInvalidAudienceException">If <see cref="TokenValidationParameters.ValidAudience"/> is null or whitespace and <see cref="TokenValidationParameters.ValidAudiences"/> is null.</exception>
        /// <exception cref="SecurityTokenInvalidAudienceException">If none of the 'audiences' matched either <see cref="TokenValidationParameters.ValidAudience"/> or one of <see cref="TokenValidationParameters.ValidAudiences"/>.</exception>

**Comment by vanillajonathan** [comment]
@brentschmaltz That would be an improvement since it would be easier to discover the exceptions when:
- browsing the source code on GitHub
- looking up the documentation online on docs.microsoft.com
- Go To Definition (<kbd>F12</kbd>) in Visual Studio

Keep in mind though that IntelliSense in Visual Studio does not include information from the `<remarks`> tag.

**Comment by brentschmaltz** [comment]
@vanillajonathan good point about f12.
@mafurman make sure that F12 shows the exception details. That may mean we don't put the exceptions in the remarks.
