### ISSUE TITLE
Changelog and upgrade path for 3.x to 4.x

### ISSUE THREAD

**Issue by angularsen** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#782]
Hi, where can I find the changelog or upgrade path from 3.0.2 to 4.x? 

The current [CHANGELOG.md](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/CHANGELOG.md) only covers changes from 4.x to 5.x.

### An example, upgrading from 3.0.2 to 4.0.4

These properties no longer exists and I can't seem to find equivalent ones with intellisense:

```csharp
new System.IdentityModel.Tokens.TokenValidationParameters
 {
     AudienceUriMode = AudienceUriMode.Always,
     SaveBootstrapContext = true,
}
```

Before: 
```
// Assembly: System.IdentityModel.Tokens.Jwt, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// Assembly location: ....\System.IdentityModel.Tokens.Jwt.3.0.2\lib\net45\System.IdentityModel.Tokens.Jwt.dll
```

After: 
```
// Assembly: System.IdentityModel.Tokens.Jwt, Version=4.0.40306.1554, Culture=neutral, PublicKeyToken=31bf3856ad364e35`
// Assembly location: ....\System.IdentityModel.Tokens.Jwt.4.0.4.403061554\lib\net45\System.IdentityModel.Tokens.Jwt.dll
```

**Comment by brentschmaltz** [comment]
@angularsen can you move to 5.x?

**Comment by angularsen** [comment]
I am not entirely sure yet, until I have tried it. Would it be an easier transition to 5.x than to 4.x?

From what I have read previously there has been a lot of issues with upgrading to 5.x for people on the OWIN and Katana stack, and we are also running that. That is, we are not running ASP.NET Core.

From what I can read on the issues list here, it seems that 5.2.0 addresses that, but it's all very fresh and I'd rather not run into issues that are hard to google and figure out.

**Comment by brentschmaltz** [comment]
@angularsen the majority of the BIG changes are in the SAML / WsFed support. If you are using OIDC / JWT / OAuth most changes are at the bug fix level.

**Comment by angularsen** [comment]
Ok thanks, I'm closing this until I get more progress on the project and know whether I'll be going for 4.x or 5.x.
