### ISSUE TITLE
Unable to parse WsFed metadata from Windows ADFS 2016 or 2012 R2

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#786]
See
https://github.com/aspnet/Security/issues/1473#issuecomment-335726577
https://github.com/aspnet/Security/issues/1473#issuecomment-335779826

**Comment by lovemaths** [comment]
@Tratcher This a duplicate with #739, we fixed this issue in dev branch.

**Comment by Tratcher** [comment]
Ok, let us know when there's a signed update on myget they can test.

**Comment by brentschmaltz** [comment]
Closing will let you know.
