### ISSUE TITLE
5.2.0 Preview 2 ETA/Plan?

### ISSUE THREAD

**Issue by Zoxive** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#796]
Just went to try 5.2.0 Preview 1 and ran into a few issues, then i noticed that the Preview 1 package is a month old.(https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.WsFederation/5.2.0-preview1-408290725)

Well that explains things, as the things i wanted to use were completed in the last month.
#703 
#763 

Is there a plan for a preview 2?

**Comment by Tratcher** [comment]
@brentschmaltz I'd like to at least get a working build on myget to validate some of the fixes. That could wait until you've finished your feature work if needs be.

**Comment by brentschmaltz** [comment]
@Zoxive @Tratcher POR is to drop preview2 next week, we are finishing up some XML validation.
