### ISSUE TITLE
Add note in ChangeLog that SecurityTokenDescriptor type is not available.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#80]
SecurityTokenDescriptor has been removed for Beta1

**Comment by PinpointTownes** [comment]
Hey @brentschmaltz 

Any chance you could accept a PR bringing back `SecurityTokenDescriptor`? :smile:

**Comment by PinpointTownes** [comment]
Ping @brentschmaltz 

Bringing back `SecurityTokenHandler.CreateToken` and `SecurityTokenDescriptor` would really be useful to avoid taking a dependency on a specific security token handler: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/src/Owin.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.cs#L1276-L1285.

**Comment by brentschmaltz** [comment]
@PinpointTownes yes will bring that back. Also new methods for creating Signed Jwt's.
I am thinking instance or static: 
(JwtSecurityTokenHandler) string Handler.CreateTokenString(string issuer, string audience, IEnumerable<Claim> claims, DateTime? notBefore, DateTime? expires, SigningCredentials signingCredentials, SignatureProvider signatureProvider). Where the return is a signed encoded string.

AND / OR 

string Handler.CreateTokenString(SecurityTokenDescriptor descriptor)

**Comment by PinpointTownes** [comment]
Great :smile: 

(personally, I'm not a huge fan of methods with terribly long signatures, specially in this case, where encrypted JWT tokens support will likely need to add a new `EncryptingCredentials` parameter)

**Comment by brentschmaltz** [comment]
@PinpointTownes I think that is a good reason for bringing back a 'revised' STD. Moving away from 'soap' made a few of the old STD seem questionable to move forward. That is the reason we dropped it for now.  Thanks for chiming in.

**Comment by brentschmaltz** [comment]
@PinpointTownes first thing I want to do is add an overload that replaces ClaimsIdentity subject, with IEnumerator<Claim> claims OR NameValueCollection claims. This will help.  How strong do you feel that an STC type will help you?  I would like to get this in RC1.

**Comment by PinpointTownes** [comment]
I think changing the `subject` type is an orthogonal thing. Bringing back `STD` would mainly help abstracting the specific implementations, so one would be free to replace a JWT handler with a SAML/SAML2 one :+1: 

This change is interesting. Will it help supporting "complex" claims (like the "address" claim: http://openid.net/specs/openid-connect-core-1_0.html#AddressClaim)?

**Comment by brentschmaltz** [comment]
@PinpointTownes I see your point about different token types. API should abstract be on the SecurityTokenHandler. I would like to see API hat creates the encoded token in one step. I think the two step: SecurityToken CreateToken(...) -> string WriteToken(...) can be improved. 

Something like: 
string SecurityTokenHandler.CreateEncodedToken( <bunch of parameters) >) 
OR 
string SecurityTokenHandler.CreateEncodedToken(SecurityTokenDescriptor)

We should be able to support the complex claims today. That said, this would be a good thing to ensure before calling this done. We did some early testing but coverage and model is vague to me now.
