### ISSUE TITLE
Enable  Microsoft.IdentityModel.Tokens.Tests.PerformanceTests.Jwt_Performance

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#800]
This test was disabled while xml tokens were being developed. We need this with a baseline against 4.x and System.IdentityModel for xml tokens.

**Comment by GeoK** [comment]
@brentschmaltz Is this issue still relevant considering that we added new perf and stress tests?

**Comment by brentschmaltz** [comment]
nope, closed.
