### ISSUE TITLE
Trying to use the library with IdentityServer IdP / WS-Federation, and getting the following error

### ISSUE THREAD

**Issue by homam1** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#816]
I already posted this before [here](https://github.com/aspnet/Security/issues/1497). but again following it up here.

Trying to use the library with IdentityServer IdP / WS-Federation, and getting the following error

An unhandled exception occurred while processing the request.

```
XmlReadException: IDX21011: Unable to read XML. Expecting XmlReader to be at ns.element: 

'http://schemas.xmlsoap.org/ws/2005/02/trust.RequestSecurityTokenResponse', found: 
'http://docs.oasis-open.org/ws-sx/ws-trust/200512.RequestSecurityTokenResponseCollection'.

```
Using JWT Token.

**Note**, this is not during reading the metadata, however, after authentication and redirecting back from the identity provider. The url is: `/signin-wsfed`

Any idea how to fix it? Any workaround?

**Comment by brentschmaltz** [comment]
@homam1 I believe this is fixed. We posted nightlies here:
https://www.myget.org/feed/azureadwebstacknightly/package/nuget/Microsoft.IdentityModel.Xml/5.2.0-preview1-41106221449

**Comment by homam1** [comment]
Is it just adding a library and the problem should gone?

**Comment by homam1** [comment]
Is this working with ASP.Net core with .Net framework ?
