### ISSUE TITLE
Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateSignature throws on missing signature

### ISSUE THREAD

**Issue by AndersAbel** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#824]
`Microsoft.IdentityModel.Tokens.Saml.dll!Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateSignature(string token, Microsoft.IdentityModel.Tokens.TokenValidationParameters validationParameters)` throws a `NullReferenceException` if the Saml2 assertion contains no signature, even though `TokenValidationParameters.RequireSignedTokens` is `false`.

I hit this when debugging against the 5.02.0.41106 nightly build from myget. I'll try to copy over a test case to repro it and fix it.

Regarding the scenario: It is fairly common when using the SAML2 protocol that the assertion XML node does not contain a signature. Instead the entire response message is signed. So handling an assertion without a signature is a must to be able implement SAML2P.

**Comment by brentschmaltz** [comment]
@AndersAbel thanks for finding this.  If you can provide a stack or sample that would be great. Should be easy enough to repro though.

**Comment by brentschmaltz** [comment]
@mafurman can you have a look at this?

**Comment by mafurman** [comment]
Taking a look at this now!

**Comment by mafurman** [comment]
@AndersAbel The issue should be fixed now. 👍

**Comment by brentschmaltz** [comment]
@AndersAbel we just pushed 5.2.0-preview1-41109045532.

**Comment by AndersAbel** [comment]
Thanks for quick response and action. I've downloaded the new package and it now works.
