### ISSUE TITLE
Create a test that will check if all custom Exceptions are found by LogHelper

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#829]
When the 'ShowPII' flag is off, LogHelper.FormatInvariant() needs to know if we're throwing an exception whose message is safe to display. We need to create a test that will ensure all exceptions created by us are properly found by this method.

Depends on #826 being completed.

**Comment by brentschmaltz** [comment]
completed
