### ISSUE TITLE
Nullref exception while reading wsFederation metadata

### ISSUE THREAD

**Issue by DaanWasscher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#831]
My idp gives me a metadata document where the attribute "use" is missing on the KeyDescriptor element. This results in a nullreference exception from "WsFederationMetadataSerializer".

The spec (https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) tells me that the "use" attribute is optional. 

In my case the provided certificate is used for signing the tokens.

Version "5.2.0-preview1-408290725"

**Comment by DaanWasscher** [comment]
The commit only partially fixes the problem. 

The nullref exception actually originates in method "ReadSecurityTokenServiceTypeRoleDescriptor" of the wsfederationmetadataserializer.

`if (reader.IsStartElement(Elements.KeyDescriptor, Namespaces.MetadataNamespace) && reader.GetAttribute(Attributes.Use).Equals(keyUse.Signing))`

The attribute is missing, hence calling the Equals method fails.

**Comment by lovemaths** [comment]
@DaanWasscher If possible, can you provide a copy of your metatadata document so I can test the whole document.

**Comment by DaanWasscher** [comment]
Of course, it is attached as a zip file because github does not accept .xml files.

[FederationMetadata.zip](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/1474469/FederationMetadata.zip)

**Comment by lovemaths** [comment]
@DaanWasscher Thank you, I updated the PR and tested your metadata document

**Comment by lovemaths** [comment]
@brentschmaltz Please review https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/832

**Comment by lovemaths** [comment]
merged to dev
