### ISSUE TITLE
iat and exp are strings instead of numbers (System.IdentityModel.Tokens.Jwt/JwtRegisteredClaimNames.cs)

### ISSUE THREAD

**Issue by cwkummer** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#838]
Per RFC 7519 (https://tools.ietf.org/html/rfc7519#section-4), the iat and exp claims MUST be numbers. In System.IdentityModel.Tokens.Jwt/JwtRegisteredClaimNames.cs (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtRegisteredClaimNames.cs) they are both of type string. This is a breaking error for code the follows the RFC spec, such as jsonwebtoken (https://github.com/auth0/node-jsonwebtoken). Specifically, jsonwebtoken considers every token issued with a string iat claim to be invalid. I did not have the chance to review if any other registered claims are of the wrong type, but the implentations should probably be reviewed against the spec.

**Comment by AndersAbel** [comment]
That's just the constants for the names of the claims. And the names are of course strings. There's nothing in that file that concerns the format of the values.

**Comment by cwkummer** [comment]
OK, I referenced the wrong file. However, if you inspect the output of a JWT created using the reserved claims, the iat and exp are both strings. I will attach a code sample later.

Thanks,

Chris Kummer
Systems/Infrastructure Architect
Department of Technology

**Comment by brentschmaltz** [comment]
@cwkummer  The 'Claims' returned have a string as the value, but JwtSecurityToken.Payload has the values as long.

**Comment by cwkummer** [comment]
@brentschmaltz @AndersAbel 
However, the System.IdentityModel.Tokens.SecurityTokenHandler.WriteToken method creates the iat and exp claims as strings (with quotes) when I believe they should be NumericDates.
![image](https://user-images.githubusercontent.com/23132869/33348243-75b8dee0-d44a-11e7-942f-ab487e6324a0.png)
These being strings is breaking the jwt.verify function of jsonwebtokens.
https://www.npmjs.com/package/jsonwebtoken#token-expiration-exp-claim

Can this be corrected?

**Comment by brentschmaltz** [comment]
@cwkummer AH! this is worth revisiting.

**Comment by GeoK** [comment]
@cwkummer I'm not able to reproduce this issue.
Actually _System.IdentityModel.Tokens.SecurityTokenHandler_ is an abstract class.

_System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler_ implements the _SecurityTokenHandler_ class and _WriteToken_ method returns a JWT in Compact Serialization Format.

See the example below:

            DateTime expires = new DateTime(2018, 8, 6, 13, 7, 24);
            var jwt = new JwtSecurityToken(expires: expires);
            var jwtHandler = new JwtSecurityTokenHandler();
            var compactSerializationFormat = jwtHandler.WriteToken(jwt);
	
			
compactSerializationFormat will be _eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJleHAiOjE1MzM1ODYwNDR9._
, which corresponds to:

 {
  "alg": "none",
  "typ": "JWT"
}.{
  "exp": **1533586044**
}.[Signature]

**Comment by mattiasback** [comment]
Hi, the above issue is still present when adding custom claims (the iat for example)
```
//List of claims to be added to token
DateTime now = DateTime.UtcNow;
long unixSeconds = new DateTimeOffset(now).ToUnixTimeSeconds();
var claims = new[]
{
	new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
	new Claim(JwtRegisteredClaimNames.Sub, userId.ToString()),
	new Claim(JwtRegisteredClaimNames.Iat, unixSeconds.ToString())     //Iat
};

//removed for brevity

JwtSecurityToken token = new JwtSecurityToken
(
	issuer: "issuer",
	audience: "audience",
	claims: claims,
	notBefore: null,
	expires: expiry,
	signingCredentials: new SigningCredentials(key, SecurityAlgorithms.HmacSha256)
);
```
{
  "jti": "87a50d0d-d151-4dec-97ab-5c523bc94bf7",
  "sub": "08d702f2-7123-3ebb-8770-478873bc095d",
  "iat": **"1562599948"**,
  "exp": 1565191948,
  "iss": "issuer",
  "aud": "audience"
}

**Comment by GeoK** [comment]
Hi @mattiasback, this behavior is by design. You created a claim without specifying its value type.
String is used as a type when valueType is not specified ([docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claim.-ctor?view=netframework-4.8#System_Security_Claims_Claim__ctor_System_String_System_String_System_String_)).

The iat claim will be created as long if you change your code to:
`new Claim(JwtRegisteredClaimNames.Iat, unixSeconds.ToString(), ClaimValueTypes.Integer64)`

Note: `token.Payload.Iat` always returns long.
