### ISSUE TITLE
Create a JwtHeader with both Signing and Encrypting Credential

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#839]
Does not seem to be supported. why?

**Comment by brentschmaltz** [comment]
@leastprivilege I am thinking of apis that work with JObject, SigningCredentials, EncryptingCrentials. JObject becomes a JWS using SigningCredentials for definition of how to sign. JWE is created using EncryptingCredentials. I am experimenting with a set of such API's. It seems cleaner and is quite a bit faster.

**Comment by brentschmaltz** [comment]
We will be adding this to M.IM.Tokens.JsonWebTokenHandler in 5.2.4
