### ISSUE TITLE
AsymmetricSignatureProvider GetHashAlgorithm should recognize standard names

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#84]
GetHashAlgorithm currently requires the hash name to be one that it understands something like from SecurityAlgorithms.???. 
It should also understand "SHA2" or "SHA256" to trigger SHA256.Create().
Same for others.

**Comment by brentschmaltz** [comment]
Currently we need to map from the Json algorithm and key specs to a value in SecurityAlgorithms. We should be able to remove the mapping.

**Comment by brentschmaltz** [comment]
this will be addressed with #85

**Comment by tushargupta51** [comment]
Re-opening since this is not fixed in 4.x yet.

**Comment by polita** [comment]
Unless a customer asks for this, we will stick with the fix in 5.x
