### ISSUE TITLE
Consider updating JwtPayload.Claims to support stringified dates

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#842]
When receiving a stringified date, JSON.NET automatically deserializes it as a `DateTime` value which is not handled by `JwtPayload.Claims` (that ends up calling the fallback logic):

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a566fa80fe2338cea5400fa24303af87f0a35f63/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L372

Unfortunately, this "encode to JSON" logic is not ideal for `DateTime` values as it causes additional quotes to appear in the final claim value as highlighted by https://github.com/aspnet/Security/issues/1556#issue-277004242.

/cc @brentschmaltz

**Comment by brentschmaltz** [comment]
@PinpointTownes I would like to consider this for vNext and get the WsFed release out. 5.2.x would be on a faster cadence.

**Comment by brentschmaltz** [comment]
@PinpointTownes were are looking at this and trying to understand what the Claim in the ClaimsIdentity should be?

**Comment by brentschmaltz** [comment]
We are not sure what is being asked here.
Please feel free to reopen with additional details.

**Comment by brentschmaltz** [comment]
@PinpointTownes we put in this change that might be what you are looking for.'https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1261
