### ISSUE TITLE
AsymmetricSignatureProvider IsSupportedAlgorithm should recognize standard names

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#85]
IsSupporterAlgorithm currently requires the hash name to be one that it understands something like from SecurityAlgorithms.???. 
 It should also understand "SHA2" or "SHA256" to trigger SHA256.Create().
 Same for others.

**Comment by brentschmaltz** [comment]
If this is fixed, also address GetHashAlgorithm, so they are in sync.

**Comment by tushargupta51** [comment]
Re-opening since this is not fixed in 4.x yet.

**Comment by polita** [comment]
This is fixed in 5.x.
