### ISSUE TITLE
Validation of token issued for MSGraph failed 

### ISSUE THREAD

**Issue by leonidzh** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#853]
I'm trying to validate token that works perfectly with MSGraph in my service too (to reuse it), but validation fails with the following exception: 
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey
Does MSGraph validates tokens in some different way? My code is pretty simple:

string configEndpoint = "https://login.windows-ppe.net/common/v2.0/.well-known/openid-configuration";

            var configManager = new ConfigurationManager<OpenIdConnectConfiguration>(configEndpoint, new OpenIdConnectConfigurationRetriever());
            var config = await configManager.GetConfigurationAsync();

            var validationParameters = new TokenValidationParameters
            {
                ValidateAudience = false,
                ValidateIssuer = false,
                ValidateLifetime = false,
                IssuerSigningKeys = config.SigningKeys
            };

            string token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFDSkpCb0tCSGcyUjViYzhBWU1KV2lOM2c5Q2l2aUE1N3YzZTJWZGVQMVRSajhWTHBfZ29DWXFUdDJPdlpOWXlFVU1YUGFWdjl0NFNLdlVLWUpIb3NIVHVTdEhnVW0zNnNCX2hoa2dxSVdEZXlBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoiSUVtMW1TbVo1THlRaVRLWDBOVEFTczdsT09zIiwia2lkIjoiSUVtMW1TbVo1THlRaVRLWDBOVEFTczdsT09zIn0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC1wcGUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy1wcGUubmV0LzVkMmZiYjc0LTYyNjctNGNjNS1hOWVlLTQ4MTU3ZjQxZmYwOS8iLCJpYXQiOjE1MTI2NTE0NTcsIm5iZiI6MTUxMjY1MTQ1NywiZXhwIjoxNTEyNjU1MzU3LCJhY3IiOiIxIiwiYWlvIjoiQVNRQTIvOEpBQUFBeVBhK2JkWGVrL1JnTUNwZ1RyYWU5WURPUnJjTUNSZVp4cldyZTc4N3BHOD0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6InRhbHBlcnRkZWxtZWFwcDQ3M3N0ZyIsImFwcGlkIjoiNTg0N2ExN2YtYTQ0Ni00YTBhLWI3ODktOGY3M2M4MzM0ZTYzIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJTZWNBZG1pbiIsImdpdmVuX25hbWUiOiJTZWNBZG1pbiIsImlwYWRkciI6IjE2Ny4yMjAuMTk3LjIyNSIsIm5hbWUiOiJTZWNBZG1pbiIsIm9pZCI6IjM5MjFmYmM0LTlhMWYtNDM4ZS1iNGM3LTIzMjVmNWYwOGNkZSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzN0ZGRUExRUIxRDI4Iiwic2NwIjoiVXNlci5SZWFkIiwic3ViIjoidU9PRHFjX0t6SUgxRWdXUnFhZ3lVNm5zN2hHZkcyLWlWZ1l6MmpXakxqdyIsInRpZCI6IjVkMmZiYjc0LTYyNjctNGNjNS1hOWVlLTQ4MTU3ZjQxZmYwOSIsInVuaXF1ZV9uYW1lIjoiU2VjQWRtaW5Ad2RhdHB0ZXN0MzEuY2NzY3RwLm5ldCIsInVwbiI6IlNlY0FkbWluQHdkYXRwdGVzdDMxLmNjc2N0cC5uZXQiLCJ1dGkiOiJ5QnhjQkE3SVNVR0cxNlBpcUZjSUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyIxOTRhZTRjYi1iMTI2LTQwYjItYmQ1Yi02MDkxYjM4MDk3N2QiXX0.hVhzAf_mq9jaJ57m5plpR5ZqYRACNbFlbG6501RSyEpoJDPLlRIr6CdkAGmoaTUw0Bir3J5xhTv94TYS7s0lG8rA9om-Ue6fJ5S04Lk4Z2EuVuW7NXa1Mf-4_mmfAOeQdFPgdkndGLcjjlMaR9SkAreAY4Re8vYAgq_27cauvh0HjUuntN2IEP067wtBNzCIevsLNA-1mkTti2wC19mOWI8fhSM3aMdxsPiYOuEsVN6uThBk6A3s2brIOkvR3LR1VVYfivSiuDKrEkrgmqEC4n55K2c5MJgdZdYM921wGt0dvSt2mvY8sURK649kVFXdbelV0akJe7nWEaZpNkIk4Q";

            var tokendHandler = new JwtSecurityTokenHandler();
            var result = tokendHandler.ValidateToken(token, validationParameters, out SecurityToken jwt);

**Comment by brentschmaltz** [comment]
@leonidzh If you notice the JWT.Header has a 'nonce' in it. This token is signed in a particular way and need a transformation before the signature will succeed.

**Comment by papa-pep** [comment]
Could you be more specific about what that transformation is?  Running into the same issue here...

**Comment by leonidzh** [comment]
The same question - is this some proprietary MS Graph transformation or I can do the same in my code?
