### ISSUE TITLE
Expand support for KeyInfo when signing and validating xml

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#859]
Current support for KeyInfo is limited to X509Data.
SecurityTokenReference is used for thumbprints
Others may be useful such as Subject, etc...
See https://www.w3.org/TR/2001/PR-xmldsig-core-20010820/#sec-KeyInfo for additional types.

**Comment by brentschmaltz** [comment]
We will need this for WsTrust.
We should add at least one or two additional keyinfo types in July.

**Comment by jennyf19** [comment]
@brentschmaltz was this done?

**Comment by brentschmaltz** [comment]
@jennyf19 Not sure when they were added, in addition to X509Data, we now have <RetrievalMethod>, <KeyName>, <KeyValue>.

Haven't heard from anyone asking for more, if others are needed, we can add extensibility.

**Comment by keegan-caruso** [comment]
Not a priority. Can re-open.
