### ISSUE TITLE
WsFederation - Supported SAML Protocol and Token versions 

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#865]
_From @gabosistvanpwc on January 10, 2018 20:53_

Hello,

I'm using the Microsoft.AspNetCore.Authentication.WsFederation 2.0.0-preview2 nuget package and I would like to know what are the current SAML protocol/token versions that are supported?

I'm getting the following exception when receiving a RequestSecurityTokenResponse from the IdP (the first time the POST is done to the "/signin-wsfed" endpoint) :

IDX11112: Exception thrown while reading 'AuthenticationStatement' for SamlSecurityToken. 
Inner exception: 'Microsoft.IdentityModel.Xml.XmlReadException: IDX30107: 'InclusiveNamespaces' is not supported.   

and I was wondering if this might be because of a not supported saml token version. I might be completely wrong on this but I think that the IdP is using the SAML 2.0 protocol and SAML 1.1 tokens. 

Thank you

_Copied from original issue: aspnet/Security#1603_

**Comment by Tratcher** [comment]
_From @reicher001 on January 10, 2018 22:4_

Here is the part of the SAML token we believe is causing this error.

`<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                                <InclusiveNamespaces PrefixList="#default saml ds xs xsi" 
                                    xmlns="http://www.w3.org/2001/10/xml-exc-c14n#" />
                            </Transform>
`

We have tested with SAML 1.1 and SAML 2.0 tokens and found they both produce this same error.

**Comment by reicher001** [comment]
We have successfully tested this code with Azure Access Control Service.  But when we use our on premise identity provider we are getting this error.  I want to be clear this error is not from a setup that uses Azure Active Directory.

Also would like to note that .NET Framework WIF can use these exact same SAML tokens successfully.

**Comment by gabosistvanpwc** [comment]
After investigating the issue further, I think we came to the point that we can post the right question. 

It seems that the "InclusiveNamespaces" feature is not supported currently for WsFederation, the class Microsoft.IdentityModel.Xml.DSigSerializer is throwing explicitly an exception when this tag is found when parsing the signature.

 https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d74c4b7236b8c4d9d5037404e6563ad52cdb3763/src/Microsoft.IdentityModel.Xml/DsigSerializer.cs#L530 

We are trying to implement WsFederation in one of our Asp .NET Core applications and this issue seems to be a blocker since we don't have control over the Identity Providers response. Also using .NET Framework WIF we were able to parse and consume the response correctly from the same Identity Provider.

Will this feature be supported?

Is there any workaround or any possibility to just ignore these lines in the response instead of throwing an exception?

Thank you

**Comment by brentschmaltz** [comment]
@Tratcher @gabosistvanpwc we hadn't planned on supporting 'inclusiveNamespaces' in this release. The workaround will be a bit of work as DSigSerializer and TransformFactory will need to be plumbed.

**Comment by reicher001** [comment]
So if this is not in this release, where on the road map does it fall?

**Comment by brentschmaltz** [comment]
@reicher001 @gabosistvanpwc would supporting 'InclusiveNamespaces' on read would enough?

**Comment by reicher001** [comment]
Yes, I believe so.

**Comment by brentschmaltz** [comment]
@reicher001 I think we can handle reading. I'll think about what writing would look as that gets coded up. It requires some new OM.

**Comment by reicher001** [comment]
Is there a target date for 5.2.0?  Really just trying to see if this is weeks or months.

**Comment by brentschmaltz** [comment]
@reicher001 this will be the last bug. We expect to drop in a few days.

**Comment by reicher001** [comment]
@brentschmaltz Is this still on track to be resolved in a few days?

**Comment by brentschmaltz** [comment]
@reicher001 yes. We will have a drop on myget that we can test out the fix.
Once we show it works, we will be able to drop 5.2.0.

**Comment by brentschmaltz** [comment]
@Tratcher @reicher001 we dropped 5.2.0-preview2-50124220239 that should have this fixed.

https://www.myget.org/feed/Packages/azureadwebstacknightly

Can you give these bits a try?

**Comment by gabosistvanpwc** [comment]
What is the recommended way to use these changes with the WsFederation nuget package?

**Comment by Tratcher** [comment]
@gabosistvanpwc add the myget feed Brent gave to your project's nuget settings. Then update the dependencies in your project.

**Comment by Tratcher** [comment]
@brentschmaltz my sanity test with those packages passed.

**Comment by brentschmaltz** [comment]
@Tratcher thanks.

**Comment by reicher001** [comment]
This appears to have resolved the issue we were seeing with the InclusiveNamespaces in the SAML tokens.

**Comment by brentschmaltz** [comment]
@reicher001 thanks. We dropped 5.2.0 with this fix on nuget.org.

**Comment by reicher001** [comment]
@Tratcher @brentschmaltz When do we think the Microsoft.AspNetCore.Authentication.WsFederation nuget package will be updated?  Currently using Preview 2.

**Comment by Tratcher** [comment]
Soon (TM). We're testing the final build now.

**Comment by reicher001** [comment]
@Tratcher Any problems found in your testing?  I am trying to get a sense of the timeline so we can decide if we deploy with the preview or hold out for the final release.

Thanks,
Rick

**Comment by Tratcher** [comment]
This has now released.
