### ISSUE TITLE
Which nuget package to use?

### ISSUE THREAD

**Issue by yaliashkevich** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#867]
What is difference between following nuget packages:
Microsoft.IdentityModel.Protocol.Extensions
Microsoft.IdentityModel.Protocols.OpenIdConnect

It looks like "Extensions" package is kind of predecessor for Protocols.XXX packages.
I'm I right? so for new development it is intended to use appropriate Protocols.XXX package

**Comment by brentschmaltz** [comment]
@yaliashkevich M.IM.Protocol.Extensions was introduced in the 3.x and 4.x versions. With 5.x we introduced additional assemblies that are descriptive of their usage.

For new development I would recommend the 5.2.x versions. Currently 5.2.x is in preview2, however POR is to ship a release this week.
