### ISSUE TITLE
How to define the key (symmetric or asymmetric) used for validating the issuer authority (the signer of the token)

### ISSUE THREAD

**Issue by Eilon** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#868]
_From @gabosistvanpwc on January 9, 2018 0:53_

In previous versions the following configuration was used to define the token validation sequence and to make sure that signer of a token and the token issuer are as expected.

```
<system.identityModel>
   <issuerNameRegistry type='derived from ValidatingIssuerNameRegistry'>
      <authority name='someFriendlyName'>
         <keys>
            <add thumbprint='caseInsensitiveString'/>
            <add symmetricKey='Base64Encoded bytes' />
         </keys>
         <validIssuers>
            <add name='issuer1'/>
            <add name='issuer2'/>
         </validIssuers>
      </authority>
   </issuerNameRegistry>
</system.identityModel>
```

What properties should be set in the WsFederationOptions object to define the keys (thumbprint and symmetricKey tags) for validating the issuer authority?

Thank you
  

_Copied from original issue: aspnet/Security#1599_

**Comment by Eilon** [comment]
_From @blowdart on January 9, 2018 20:28_

@Tratcher this is WS-Fed, so you :)

**Comment by Eilon** [comment]
_From @Tratcher on January 9, 2018 20:32_

@brentschmaltz ?

**Comment by Eilon** [comment]
_From @gabosistvanpwc on January 11, 2018 17:0_

Is there any support right now for validating the issuer name registry, similar to https://docs.microsoft.com/en-us/dotnet/framework/security/validating-issuer-name-registry ?

I think this the piece of code from the System.IdentityModel.Tokens.ValidatingIssuerNameRegistry class that is doing this check in .NET Framework 4.5.1 :

```
protected virtual bool IsThumbprintValid(string thumbprint, string issuer)
{
     foreach (IssuingAuthority authority in this.IssuingAuthorities)
     {
         if ((((authority != null) && (authority.Thumbprints != null)) && ((authority.Issuers != null) && authority.Thumbprints.Contains(thumbprint))) && authority.Issuers.Contains(issuer))
        {
            return true;
        }
    }
   return false;
}
```

Thank you

**Comment by Eilon** [comment]
@brentschmaltz can you take a look at this?

**Comment by brentschmaltz** [comment]
@Eilon we don't have any first class support. We extensiblity using a delegate that can be set to validate the key that  signed the token. The API takes the key, token and tokenvalidationparameters.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L62

**Comment by gabosistvanpwc** [comment]
I have made the following updates to the WsFederation configuration:

```
services.AddAuthentication()
        .AddWsFederation(options =>
        {                
            options.TokenValidationParameters.ValidateIssuerSigningKey = true;
            options.TokenValidationParameters.IssuerSigningKeyValidator = IssuerSigningKeyValidator;
        })

private bool IssuerSigningKeyValidator(SecurityKey securityKey, SecurityToken securityToken, TokenValidationParameters validationParameters)
{
     return true;
}
```

While signing in the method IssuerSigningKeyValidator is not being called, am I missing something?

Also I was not able to find any references to this method in the WsFederationHandler class ( https://github.com/aspnet/Security/blob/9ebfc5634a42971fd9850717bf45fa4b8d7245da/src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationHandler.cs#L150 ) .

Thank you!

**Comment by brentschmaltz** [comment]
@gabosistvanpwc it looks like we were not calling the delegate.
We fixed the issue and it will be in the next drop.

**Comment by brentschmaltz** [comment]
@gabosistvanpwc we dropped 5.2.0-preview2-50124220239 that should have this fixed.

https://www.myget.org/feed/Packages/azureadwebstacknightly

**Comment by brentschmaltz** [comment]
@gabosistvanpwc please reopen if this issue is still occurring.
