### ISSUE TITLE
JwtSecurityTokenHandler: Case-sensitive comparisons of KeyId cause wrong exception messages

### ISSUE THREAD

**Issue by apodogov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#869]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/af5e5c2b0100e8348c63e2d2bb45612e2080841e/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1068

Because this comparison is case-sensitive, is some cases you can receive exception "Unable to match 'kid'" when kid really matched and validation failed due to another reason. In such cases expected exception is "Signature validation failed. Keys tried..."

For example this happens when JWT's header contains KeyId is lower case and X509SecurityKey stores KeyId in upper case:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/af5e5c2b0100e8348c63e2d2bb45612e2080841e/src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs#L56

BTW, for example JsonWebKey doesn't set KeyId at all and sets Kid instead. But I'm too lazy to file another issue now.

**Comment by brentschmaltz** [comment]
@apodogov I feel your pain. In the case of Thumbprint for sure CaseInsensitve would be fine. 
The spec indicates case sensitive: https://tools.ietf.org/html/rfc7517#section-4.5

This seems a little restrictive as if a signature validates with a key obtained from a trusted source, the kid is somewhat irrelevant.

**Comment by brentschmaltz** [comment]
@apodogov @mafurman how about we check if the key is X509SecurityKey and use case-insensitive match for those keys?
