### ISSUE TITLE
Microsoft.IdentityModel.Tokens 5.2.0 is unable to parse ADFS 2.0 FederationMetadata.xml

### ISSUE THREAD

**Issue by Abdruggi** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#871]
The new version of the library is unable to parse ADFS 2.0 FederationMetadata.xml files. I get the following exception:

IDX20803: Unable to obtain configuration from: 'https://[servername]/FederationMetadata/2007-06/FederationMetadata.xml'. Could not load type 'Microsoft.IdentityModel.Tokens.Xml.DelegatingXmlDictionaryReader' from assembly 'Microsoft.IdentityModel.Tokens, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by brentschmaltz** [comment]
@Abdruggi can you share what IdentityModel assemblies you have in your 'bin' folder?
DelegatingXmlDictionaryReader is in Microsoft.IdentityModel.Xml.dll

**Comment by Abdruggi** [comment]
@brentschmaltz File Version: 5.2.0.41113

**Comment by brentschmaltz** [comment]
@Abdruggi file version should be 5.2.0.50129

**Comment by brentschmaltz** [comment]
@Abdruggi please reopen if after updating the assembly and you still have the same issue.

**Comment by Abdruggi** [comment]
@brentschmaltz Now it works. Thx for your help.
