### ISSUE TITLE
Jwe validation requires special configuration of TokenValidationParameters

### ISSUE THREAD

**Issue by abdulbeard** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#872]
Hello,

I've been using your nuget package for a library I'm writing. While trying to create a JWE using [JwtSecurityTokenHandler](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs), I found what I consider a bug. Seems like your strategy for creating a JWE is by wrapping the JWT inside of it, as per [this](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L859).
However, when one attempts to validate this token using [TokenValidationParamters ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs)that don't have [RequireSignedTokens](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L468) set to true (the default value), token validation fails.
This is because upon validation when you call [ValidateSignature](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L759),  the `decryptedJwt` represents a token whose `RawSignature` is `nullOrEmpty` when you call [ReadJwtToken](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L685) on it.
This ends up making [this if statement](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1009) true, and as a result, you get the `IDX10504` error.

Is this intended behavior?

P.S. This bug is not present when the token being created has a nested JWE.

Here, you can find a way to replicate this issue:

```c#
   class Program
    {
        private const string Key = "C5AxWRAoC/lp3Ayt1RcAxMQDZ74fy1f6rzA7ko1GME06/FkBhRML1BNLXMwTVeoRAJ2oVvIdTy8b4Px8FgJ7e36hCp6SopZhoAng1HwPtLYg4QUXMfjCjaKEqba4/e5nsZXaJpn9a6CaSFy6WL3PPV5m7ZyFK+jLlhT+X5inqPk=";
        static void Main(string[] args)
        {
            // works like a charm
            var token = CreateJwe();
            var validationParamters = GetValidationParameters();
            validationParamters.RequireSignedTokens = false;
            var claimsPrincipalSuccess = ValidateToken(token, validationParamters, out var validatedTokenSuccess);


            //fails and throws an IDX10504
            var faultyToken = CreateJwe();
            var claimsPrincipalFailure = ValidateToken(faultyToken, GetValidationParameters(), out var validatedTokenFailure);
        }

        private static string CreateJwe()
        {
            var header = new JwtHeader(new EncryptingCredentials(GetSecurityKey(), JwtConstants.DirectKeyUseAlg,
                SecurityAlgorithms.Aes256CbcHmacSha512));
            var payload = new JwtPayload(GetClaims());
            var token = new JwtSecurityToken(header, payload);
            return new JwtSecurityTokenHandler().WriteToken(token);
        }

        private static ClaimsPrincipal ValidateToken(string token, TokenValidationParameters validationParameters, out SecurityToken validatedToken)
        {
            var claimsPrincipal = new JwtSecurityTokenHandler().ValidateToken(token, validationParameters, out validatedToken);
            return claimsPrincipal;
        }

        private static SymmetricSecurityKey GetSecurityKey()
        {
            return new SymmetricSecurityKey(Encoding.Default.GetBytes(Key));
        }

        private static TokenValidationParameters GetValidationParameters()
        {
            return new TokenValidationParameters
            {
                IssuerSigningKey = GetSecurityKey(),
                ValidIssuer = "TheMan",
                ValidateIssuer = true,
                ValidateLifetime = true,
                ValidateAudience = false,
                TokenDecryptionKey = new EncryptingCredentials(GetSecurityKey(),
                    JwtConstants.DirectKeyUseAlg,
                    SecurityAlgorithms.Aes256CbcHmacSha512).Key

            };
        }

        private static List<Claim> GetClaims()
        {
            return new List<Claim>
            {
                new Claim("exp", "1517638188"),
                new Claim("iat", "1517609388"),
                new Claim("iss", "TheMan"),
                new Claim("nbf", "1517609388")            };
        }
    }

```

**Comment by brentschmaltz** [comment]
@mafurman can you have a look into this.

**Comment by ChenYan98** [comment]
I think you missed to create the nested JWS's header in your CreateJwe(). Without this, you cannot sign JWS  with the SigningCredentials. @mafurman can help to test it.

**Comment by mafurman** [comment]
I replicated the issue, and I believe that the nested JWS must be created with a JwtHeader that takes in SigningCredentials rather than EncryptingCredentials in order for your sample to work. Otherwise no signature can be generated, hence the error that you're receiving.

**Comment by abdulbeard** [comment]
So is it a bug then that I can create a JWE by setting `validationParamters.RequireSignedTokens = false` and not having a `JWS` with a `JwtHeader` with `SigningCredentials`?

**Comment by brentschmaltz** [comment]
@abdulbeard by default, the library requires that the JwtPayload that contains the claims to be signed. In this case, that payload is inside a JWE. When creating the JWE, if you supply SigningCredentials, the inner JWT will be a JWS and the default will succeed.

Setting the IssuerSigningKey in GetValidationParameters() is really a no-op.
I played around with the code here (to try and explain better): https://github.com/brentschmaltz/IdentityModel/blob/master/SupportIssues/Issue872.jwe.cs
