### ISSUE TITLE
5.2.0 breaks tests in IdentityServer4 for .NET 4.6.1

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#873]
Upgrading to 5.2.0 breaks tests in IdentityServer4. You can easily repro by cloning the dev branch here:

https://github.com/IdentityServer/IdentityServer4

* run build.ps1
* update the JWT handler to 5.2.0
* run build.ps1 again

The odd thing is, it is not deterministic - and different tests fail all the time (the JWT handler is always involved) - and only on net461 - not on netcoreapp2.0

**Comment by brentschmaltz** [comment]
@leastprivilege I will have a look.

**Comment by leastprivilege** [comment]
Any update?

**Comment by leastprivilege** [comment]
Seems to be gone with 5.2.1 

btw you obsolete message for HasPrivateKey is wrong.

**Comment by brentschmaltz** [comment]
@leastprivilege good. I'll touch up the message for HasPrivateKey.
