### ISSUE TITLE
Unhandled System.FormatException in LogHelper.LogExceptionMessage()

### ISSUE THREAD

**Issue by chrisbrook83** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#876]
We have observed a situation where exceptions thrown by `System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken` are being effectively swallowed due to a bug in the subsequent logging code in this module.

The actual exception was `SecurityTokenSignatureKeyNotFoundException`, caused by an issue with our configuration.

However. there is a bug in `Microsoft.IdentityModel.Logging.IdentityModelEventSource.PrepareMessage`, which results in a `System.FormatException` being thrown instead.

The bug is on ln322, here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Logging/IdentityModelEventSource.cs#L322

Because `args` is a `params` argument, it can _never_ be null (in the example I debugged, no args values are passed, so this value is an empty array). However, this causes `FormatInvariant` to be called, with the `SecurityTokenSignatureKeyNotFoundException` message string being passed as the format string, which is clearly invalid.

**Steps to repro**
* Call `PrepareMessage` with a `message` argument containing curly braces (e.g. a message containing a plaintext JWT token body), and no `args` params objects.

**Fix**
Change ln322 in `IdentityModelEventSource` from:
* `if (args != null)` ...to
* `if (args.Length > 0)`

...generally speaking, I would also suggest that any logging code should always fail safe, so that the underlying exception is never swallowed / substituted.

**Comment by brentschmaltz** [comment]
@chrisbrook83  sorry for the bug, we'll get this fixed.
