### ISSUE TITLE
[JWE] inner token payload validated twice

### ISSUE THREAD

**Issue by ycrumeyrolle** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#878]
Is there any reason to validate twice the same payload of the inner token?  
May be a bug?
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L733

```
                ValidateTokenPayload(innerToken, validationParameters);
                jwtToken.InnerToken = innerToken;
                validatedToken = jwtToken;
                return ValidateTokenPayload(innerToken, validationParameters);
```

**Comment by brentschmaltz** [comment]
@ycrumeyrolle looks very suspicious, thanks. I'm out for another week, will check this out when I return.

**Comment by mafurman** [comment]
I looked into this, and I don't see any reason why we can't simply remove one of the validate calls.
