### ISSUE TITLE
Add .netstandard2.0 target

### ISSUE THREAD

**Issue by JNappee** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#879]
.netstandard1.4 is quite old now and it would be nice to have a .netstandard2.0 compatible dll.

**Comment by brentschmaltz** [comment]
@jnappee in general we want to use the lowest version possible. Specifying 1.4 just defines the contracts we support. The lower the number the more runtimes we can support. We will add a new target as there are some features in 1.6 we need in crypto.

**Comment by JNappee** [comment]
I totally agree with that unless there are breaking changes between major versions and then binding standard libs to the upper versions can introduce bugs. Isn't that the case with 1.4, 1.6 and 2.x?

**Comment by brentschmaltz** [comment]
@JNappee there is a strong effort to ensure back-compat between runtimes.
