### ISSUE TITLE
JsonWebKey KeyId is null resulting in JwtHeader with no kid

### ISSUE THREAD

**Issue by kevin-meyer** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#885]
I'm creating a `JsonWebKey` from json and using it in the `SigningCredentials` for a `JwtSecurityToken`.  This results in a `JwtHeader` with no `kid` defined (it looks to the `signingCredentials.Key.KeyId`).

Shouldn't `JsonWebKey` keep the base `KeyId` in sync with the `Kid`?

**Comment by brentschmaltz** [comment]
@kevin-meyer yes that is a bug. To get around it, as you probably figured out, you will need to set JsonWebKey.Kid.
