### ISSUE TITLE
Nu-Get package fails to install due to NewtonSoft.Json conflicts ...

### ISSUE THREAD

**Issue by bdcoder2** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#886]
Using Visual Studio Community 2017 v15.7.

1. I created an Azure Functions project.
2. I use NuGet to install System.IdentityModel.Tokens.Jwt v5.2.1
3. Click Install, result:

```
  GET https://www.nuget.org/api/v2/Packages(Id='System.IdentityModel.Tokens.Jwt',Version='5.2.1')
  OK https://www.nuget.org/api/v2/Packages(Id='System.IdentityModel.Tokens.Jwt',Version='5.2.1') 98ms
Restoring packages for D:\vsprojects\serverless_functions\v1\test1\test1.csproj...
NU1107: Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue. 
 test1 -> System.IdentityModel.Tokens.Jwt 5.2.1 -> Newtonsoft.Json (>= 10.0.1) 
 test1 -> Microsoft.NET.Sdk.Functions 1.0.8 -> Newtonsoft.Json (= 9.0.1).
Package restore failed. Rolling back package changes for 'test1'.
Time Elapsed: 00:00:02.6098449
========== Finished ==========
```

This is an AZURE FUNCTIONS project -- there is no app.config or web.config file in which I can set dependencies .

HOW can I use JWT in Azure functions when the rest of my code will require the latest version of Newtonsoft.Json (v11.0.1) ?

It appears that Microsoft.NET.Sdk.Functions 1.0.8 REQUIRES a specific version of Newtonsoft.Json, i.e.: must be = 9.0.1, rather than >= 9.0.1.

ALSO - where is the documentation?  The following has NOTHING with regard to using JWT:
https://docs.microsoft.com/en-us/dotnet/framework/security/json-web-token-handler-api-reference

**Comment by mafurman** [comment]
This seems to be a known issue with Microsoft.NET.Sdk.Functions. A potential workaround is to include the following package reference in your .csproj file:

`<PackageReference Include="Newtonsoft.Json" Version="11.0.1" />`

(Note: anything greater than 10.0.1 should work.)

This overrides the requirement set by Microsoft.NET.Sdk.Functions and should allow you to successfully install System.IdentityModel.Tokens.Jwt. 

As far as documentation goes, we currently do not have any documentation on https://docs.microsoft.com.

**Comment by bdcoder2** [comment]
Thanks mafurman!

Added the line to the .csproj file -- NOTE -- I did have reload the project after tampering with the .csproj file.  Then pulled in the System.IdentityModel.Tokens.Jwt via NuGet:

`TOOLS -> NuGet Package Manager -> Manage NuGet Packages for Solution...`

NuGet did issue the following warning:

`Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.NET.Sdk.Functions 1.0.9 requires Newtonsoft.Json (= 9.0.1) but version Newtonsoft.Json 11.0.1 was resolved.`
