### ISSUE TITLE
WSFederation Support with Windows Identity

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#887]
_From @joetherod on March 6, 2018 17:58_

Is there support for WFFederation SSO authentication with WIF?
Currenyly using the following namespaces in .NET 4.6

using System.IdentityModel;
using System.IdentityModel.Services;
using System.IdentityModel.Services.Configuration;
using System.IdentityModel.Tokens;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Permissions;

DeflateCookieTransform
RsaEncryptionCookieTransform
RsaSignatureCookieTransform

Is there any information on how to do this in ASPNET Core MVC?

Thanks

_Copied from original issue: aspnet/Security#1683_

**Comment by Tratcher** [comment]
_From @blowdart on March 6, 2018 19:2_

Yes. https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.WsFederation/

https://github.com/aspnet/Security/issues/1473 has the discussion from Preview 1 to Release.

**Comment by Tratcher** [comment]
_From @laj0206 on March 7, 2018 21:3_

Hi @blowdart, thanks for the information. 
In .NET 4.6, we used to use SessionSecurityTokenHandler including RsaEncryptionCookieTransform to parse token since token is been encrypted by certificate. Is there a way to do the same thing in net core? I am not able to find a way based on the current nuget package. 
Could you please kindly advise? Thanks

**Comment by Tratcher** [comment]
@brentschmaltz

**Comment by Tratcher** [comment]
_From @joetherod on March 9, 2018 16:50_

@brentschmaltz any update on WSFederation supporting SessionSecurityTokenHandler including RsaEncryptionCookieTransform.
Or is there a sample implementation that can do the same thing for authentication via WSFederation for SSO?

**Comment by Tratcher** [comment]
_From @joetherod on March 13, 2018 13:23_

No update? @brentschmaltz Very unfortunate that this prerelease is unusable at this point.

**Comment by brentschmaltz** [comment]
@Tratcher just getting all caught up. This looks like a new feature for Core.

**Comment by joetherod** [comment]
@brentschmaltz is this enhancement going to happen?

**Comment by joetherod** [comment]
Is this available now in 5.3? Can examples be provided?

**Comment by brentschmaltz** [comment]
@joetherod @Tratcher We don't have that RsaCookieTransform coded.
We could put together a sample.
It is really a wrapping of SignedRSA over EncryptedRSA.

**Comment by joetherod** [comment]
@brentschmaltz  That would be appreciated. I saw that the issue was closed with the 5.3 release.
thanks

**Comment by brentschmaltz** [comment]
@joetherod 	we are looking for a quick release for a couple of xml items, we will toss this in.

**Comment by joetherod** [comment]
@brentschmaltz Is there a release date for this support and will it have examples on how to use?

**Comment by brentschmaltz** [comment]
@joetherod we currently has this marked for 5.3.1 which is in a couple of weeks.

**Comment by joetherod** [comment]
@brentschmaltz Core 2.2 is out? 5.3.1?

**Comment by joetherod** [comment]
@brentschmaltz I see the 5.3.1 branch. Do you have examples on how to do the SessionSecurityTokenHandler including RsaEncryptionCookieTransform.
Basically, we have many apps that use SSO via WSFederation. And the app that is actually doing the work is still .NET 4.5. My app is in core, so I want to be able to process the same FedAuth cookies to ensure the user is authenticated.

**Comment by mafurman** [comment]
@joetherod ASP.NET Core will automatically create an SSO cookie using Cookie middleware/handler. Does this not work for you?

**Comment by joetherod** [comment]
@mafurman Our current SSO implementation uses .NET 4.5 Windows Identity and WS Federation. The WS fed http module parses the wa form and creates the FedAuth cookies based on our certs. We have new .NET core apps that want to be able to use the same SSO feature. the current port you have has no support for it. I need an auth middleware component in core to process that form federated form and creates the same fedauth cookies. and if the the fedauth cookies exist, it needs to decrpty and process it to determine if user is authenticated. The current port you has no support for that.
If you can show me how to do this in Core with the available code, please do. I've been waiting over a year for this.

**Comment by brentschmaltz** [comment]
@joetherod are you looking to have .NET 4.5 and CORE servers processing the same SSO cookies?

**Comment by joetherod** [comment]
@brentschmaltz yes. We have a portal where a user can login. within that portal the user can navigate to different apps using the same auth ticket. Our apps were all 4.5. We are in the process of porting them over to core. We want to use the same auth ticket in new core apps.

**Comment by brentschmaltz** [comment]
@joetherod thanks for that detail. Essentially, you will need a to plug in a custom cookie handler into core that knows how to hydrate the 4.5 cookies into a User.
Does that sound right?

**Comment by joetherod** [comment]
@brentschmaltz yes. I need to register something in startup so the Core User is set to authenticated or not and claims are set.

**Comment by joetherod** [comment]
@brentschmaltz Not only to hydrate the cookie, but also process the wsresult via the post from the login app and creates the auth cookies and establishes the authentication. This is how the wsfederation httpmodule is setup on every .net 4.5 app that uses SSO.

**Comment by Tratcher** [comment]
AspNetCore has a WsFed auth handler. It's the cookies that are the hard part.

**Comment by brentschmaltz** [comment]
@Tratcher @joetherod I'll have a look at what it will take to add this ability as an extension.

**Comment by joetherod** [comment]
@brentschmaltz Looking forward to it. Thank you.

**Comment by joetherod** [comment]
@brentschmaltz Is there an eta for the 5.5.0 release with this support?

**Comment by brentschmaltz** [comment]
no feed back in 3 years, triaging.
