### ISSUE TITLE
Exception on Newtonsoft

### ISSUE THREAD

**Issue by ritun85** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#889]
Hi ,
I am getting same kind of exception when I try to refer System.IdentityModel from openspan project it throws me below error. As openspan itself uses Newtonsoft 5.X it does not allow 10.X. We dont have any option to provide binding redirect as there is no straight way to add config file in openspan. Please suggest

Source: "System.IdentityModel.Tokens.Jwt"
HResult: -2146233036

StackTrace Information

at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
at System.IdentityModel.Tokens.Jwt.JwtPayload.SerializeToJson()
at System.IdentityModel.Tokens.Jwt.JwtPayload.Base64UrlEncode()
at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.get_EncodedPayload()
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
at TokenGenerator.TokenGen.CreateToken()

Exception Information
Exception Type: System.IO.FileLoadException
Message: "Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

Regards,
Ritun

**Comment by ritun85** [comment]
Hi @brentschmaltz,

Openspan is tool built on top of visual studio for creating  solutions for robotic automation. Currently openspan is using fixed version of newtonsoft ( v5).I have a business requirement where I need to build a robotic solution where I need to create jwt token. I have installed system.identitymodel.jwt nuget package which internally dependent on newtonsoft v10. When I am running the application runtime I am getting error. there is no straight way to add config file in robotics solution.
Please let me know if you need more information.

Regards,
Ritun

**Comment by brentschmaltz** [comment]
@ritun85 what target (45, 45.1, netstandard1.4) are you using?
We did some research and we can reduce the target to 6.0.1 for 45 and 4.5.1, which we are thinking of doing.

**Comment by ritun85** [comment]
@brentschmaltz target framework is .net 4.5.

**Comment by brentschmaltz** [comment]
@ritun85 we can't go below 6.0.1. Closing for now. Please reopen if needed.
