### ISSUE TITLE
TEST: Consolidate ExtensibilityTests and CreateAndValidateTokens

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#89]
There seems to be a bunch of duplication here.

**Comment by tushargupta51** [comment]
There does not seem to be duplication in these 2 test classes. Though, we need a cleanup of our tests to make sure we have less or no redundancy.

**Comment by tushargupta51** [comment]
@brentschmaltz assigning this to you since you will be working on test cleanup
