### ISSUE TITLE
WSFederation - No token validator was found for the given token.

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#893]
_From @Tratcher on March 20, 2018 14:54_

_From @StevanoHallo on March 20, 2018 9:33_

The exception I'm getting when attempting to use WSFederation in my .NET Core App:

SecurityTokenException: No token validator was found for the given token.

`Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()`

This is my 'ConfigureServices':

> services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
            })
            .AddWsFederation(options =>
            {
                options.Wtrealm = "https://localhost:1234";
                options.MetadataAddress = "https://adfs.company.co.uk/federationmetadata/2007-06/federationmetadata.xml";
            })
            .AddCookie();

I also have 'app.UseAuthentication();' at the top of 'Configure' as well.

I've tried using the MetaData and also building the options manually without it. Both result in the same exception. Looking at Fiddler as well, it seems to be authenticating with ADFS and I'm getting a 200 back. We use the same ADFS server for our .NET 4.6 Apps and that works fine. 

But I'm not sure if I'm missing something or there is an issue with the library?

_Copied from original issue: aspnet/Security#1700_

_Copied from original issue: AzureAD/azure-activedirectory-library-for-dotnet#1018_

**Comment by Tratcher** [comment]
We would need an example token to investigate.

**Comment by Tratcher** [comment]
_From @StevanoHallo on March 20, 2018 14:16_

@Tratcher Here's an example token pulled from a response. Thanks.

[Token.txt](https://github.com/aspnet/Security/files/1829678/Token.txt)

**Comment by Tratcher** [comment]
_From @jmprieur on March 20, 2018 15:42_

@Tratcher : is this an ADAL.NET question? or more a middleware or asp.NET core question
cc: @henrik-me @brentschmaltz

**Comment by Tratcher** [comment]
IdentityModel handles the token processing. I expect this issue is due to missing encrypted token support.

**Comment by Tratcher** [comment]
_From @jmprieur on March 20, 2018 15:48_

Do you mean, @Tratcher that this is an issue for https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet ?

**Comment by Tratcher** [comment]
Ah, you're right. Sorry for the bad copy. Moving now...

**Comment by jmprieur** [comment]
Thanks @Tratcher for confirming. I was wondering how we could help on this topic, and could not figure out a starting point. I'll let you close this issue from here when you have moved it. (unless you can really move it?)

**Comment by henrik-me** [comment]
@brentschmaltz @mafurman who can likely assist on the issue raised

**Comment by brentschmaltz** [comment]
@Tratcher @jmprieur @henrik-me we don't support encrypted tokens right now. It is a know issue for Saml2. Not sure if we need to expand to general encrypted tokens.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/734
