### ISSUE TITLE
Nuget Depenencies using Outdated Monikers?

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#895]
When I saw DNX 4.5.1 and DNXCore 5.0 [as Nuget dependencies](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocol.Extensions/2.0.0-beta6-207211625), I was confused since I had seen the DNX moniker before.

I then found this SO Post: [Do not use DNX, use latest identifiers.](https://stackoverflow.com/a/39077331/185123)

![image](https://user-images.githubusercontent.com/14079228/37854786-c1c4b6a6-2ec2-11e8-81b6-2e944fce616b.png)

**Comment by Tratcher** [comment]
Microsoft.IdentityModel.Protocol.Extensions is an abandon prototype last updated in 2015. Recent projects do not have this problem, correct?

**Comment by spottedmahn** [comment]
Oh, I see, thanks!

I don't think so.  I checked [Microsoft.IdentityModel.Protocols.OpenIdConnect](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/) and that looks good.

---

I'm really trying to get this sample updated: [active-directory-b2c-dotnet-webapp-and-webapi](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/issues/28#issuecomment-375418816)

**Comment by ggirard07** [comment]
@Tratcher If `Microsoft.IdentityModel.Protocol.Extensions` is an abandoned prototype. Can you deprecate it  in NuGet please...?

**Comment by Tratcher** [comment]
'deprecate'? That's not a nuget feature. Unlist?

I thought the beta6 version number would be a giveaway.

**Comment by spottedmahn** [comment]
>'deprecate'? That's not a nuget feature

Surprising 😲

**Comment by ggirard07** [comment]
Sorry for the confusion.
I saw in that past owners of packages updating their package title and description to clearly indicate it as deprecated and give a hint on the new packages replacing the deprecated one(s).
