### ISSUE TITLE
BootstrapContext type changed

### ISSUE THREAD

**Issue by phatcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#897]
I'm upgrading some code that was using Microsoft.IdentityModel.Protocol.Extensions to Microsoft.IdentityModel.Protocols.OpenIdConnect.

Previously when setting TokenValidationParameters.SaveSiginToken then the resulting ClaimsIdentity would have a BootstrapContext of type System.IdentityModels.Tokens.BootstrapContext and now it appears to be just the string containing the JWT.

Was this intended?

**Comment by brentschmaltz** [comment]
@phatcher yes it is intentional as the type BootstrapContext is not available on .NetCore.
The type was intentionally set to be object on ClaimIdentity so that is was runtime sensitive.

**Comment by phatcher** [comment]
@brentschmaltz Thanks for that

**Comment by spottedmahn** [comment]
Wonder if there is any migration guidance?
