### ISSUE TITLE
NameClaimType Doesn't Seem like Validation in TokenValidationParameters

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#899]
Apparently one must configure where to get the user's name claim from so that they can perform operations like `var name = User.Identity.Name;`

In the following [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/blob/cf011352babed2685c9c324e308a2b8775640c2b/TaskWebApp/App_Start/Startup.Auth.cs#L78) example, the value is configured via `TokenValidationParameters`.

That doesn't feel right to me.  It is not validating the name claim, it is telling it where to find it, no?

```csharp
app.UseOpenIdConnectAuthentication(
	new OpenIdConnectAuthenticationOptions
	{
		// Generate the metadata address using the tenant and policy information
		MetadataAddress = String.Format(AadInstance, Tenant, DefaultPolicy),

		// These are standard OpenID Connect parameters, with values pulled from web.config
		ClientId = ClientId,
		RedirectUri = RedirectUri,
		PostLogoutRedirectUri = RedirectUri,

                ....

		// Specify the claims to validate
		TokenValidationParameters = new TokenValidationParameters
		{
			NameClaimType = "name"
		},
	}
);
```

---

[nameClaimType](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/nameclaimtype)

>Sets the claim type that specifies the Name property. The claim type is used to search for a Claim in the collection of ClaimsIdentity objects returned by the ValidateToken method of this token handler. The value of the matching claim is then set as the name of the IIdentity generated from this token handler.

---

Reference: [Azure AD B2C: User.Identity.Name is null, but User.Identity.m_instance_claims[9] has the name](https://stackoverflow.com/a/49470129/185123)

Reference: https://github.com/aspnet/AspNetKatana/issues/186

**Comment by Tratcher** [comment]
Duplicate? What more are you hoping for here beyond the Katana discussion?

**Comment by brentschmaltz** [comment]
@spottedmahn if TokenValidationParameters.NameClaimType is set to "name", then the Property ClaimsIdentity.Name will return the value of the first Claim where Claim.Type=="name". By default the value is: ClaimTypes.Name == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

**Comment by spottedmahn** [comment]
Hey @Tratcher - I was going to the "owner" of `TokenValidationParameters` to get their 2 cents 😊

After the Katana discussion/research, I understand Katana is taking a dependency on this project.

It's not a big deal, it just doesn't feel right.  To me, it is not self-documenting.  Seems to be violating the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) too.  Maybe I'm not understanding something though.  Just an outsiders viewpoint.

On the surface, it would seem there should be a `TokenValidationParameters` class and a `TokenConfigurationParameters` class.

**Comment by spottedmahn** [comment]
Hi @brentschmaltz - thanks for the reply.  Please see [the above](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/899#issuecomment-376969011) post for clarification, thanks!

**Comment by brentschmaltz** [comment]
@spottedmahn I get your point. Controlling the result of ClaimsIdentity.Name is probably not what one thinks about when validating a token. ClaimsConfigurationParameters (or something may fit).
I'll reopen for now, and let's think about it. We want to get a release ready by mid april.
A future release will have an async pattern and will require new apis. Passing in a context returning a result may fit in.

**Comment by spottedmahn** [comment]
Hey @brentschmaltz - thanks for the update!! ⚡

Sounds good to me.  Let me know if I can help.  Happy to submit a PR 😊!

**Comment by brentschmaltz** [comment]
@spottedmahn we will ping you when we start the async work.

**Comment by brentschmaltz** [comment]
@jennyf19 we may want to consider this with our ClaimsIdentity work.

**Comment by jennyf19** [comment]
FYI @GeoK

**Comment by keegan-caruso** [comment]
Closing as designed. 

It would be disruptive to a lot of projects to change this.
