### ISSUE TITLE
JsonWebKeySet fail to deserialize in some cases 

### ISSUE THREAD

**Issue by hanabi1224** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#901]
When JsonConvert.DefaultSettings.ObjectCreationHandling is set to ObjectCreationHandling.Replace, JsonWebKeySet cannot deserialize Keys property thus causes IDX10500  : Signature validation failed. No security keys were provided to validate the signature.

There's also bug in OpenIdConnectConfigurationRetriever line 100, openIdConnectConfiguration.JsonWebKeySet = JsonConvert.DeserializeObject<JsonWebKeySet>(keys);
When the same default JsonConvert setting is set, it fails to deserialize keys

**Comment by brentschmaltz** [comment]
@mafurman please have a look at this.
