### ISSUE TITLE
High LSA CPU load due to key creation usage

### ISSUE THREAD

**Issue by Kdamour** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#906]
Under heavy traffic loads, the LSA is pegged up to 100% due to key creation and management when using JWT tokens for each request (client request & verify on server).  Allowing for cached key classes rather than recreating resulted in a significant drop (down into single digits for CPU load on LSA).

**Comment by brentschmaltz** [comment]
This is blocking IOT scenarios.
