### ISSUE TITLE
Add SourceLink to release builds

### ISSUE THREAD

**Issue by mjsabby** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#909]
[SourceLink](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md) is supported by recent C# Compilers that allows source indexing of built code to the repo.

Both Windows and Portable PDBs support it. Therefore you can enable it generally for both .NET and .NET Core builds.

**Comment by brentschmaltz** [comment]
@mjsabby thanks for pointing out how we can improve the library.

**Comment by brentschmaltz** [comment]
@mjsabby this will be in tonight's drop on myget: https://www.myget.org/gallery/azureadwebstacknightly

**Comment by mafurman** [comment]
I can confirm that SourceLink is enabled for the most recent drop.  😊

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/921

**Comment by mjsabby** [comment]
Thank you @mafurman @brentschmaltz -- It's available on nuget now.

**Comment by mjsabby** [comment]
@chapalexiv @VKoka we should integrate this update.
