### ISSUE TITLE
JsonWebKey.CreateECDsa() should throw an exception if the operating system is not Windows.

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#917]
Part of #581.
Support for ECDsa creation on other operating systems will be added once we decide on a new target to support.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/918
