### ISSUE TITLE
Add .NET Standard 2.0 target

### ISSUE THREAD

**Issue by natemcmaster** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#925]
I realize this was already requested in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/879, but I have additional reasons for you to consider.

- The justification for closing https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/879#issuecomment-367996497 was a desire to keep the libraries compatible with as many runtimes as possible. This and adding netstandard2.0 are not mutually exclusive. You could add netstandard2.0 and keep netstandard1.x
 - Benefits of netstandard20
    - Simplified package graph
        - Smaller .NET Core SDK installers. IdentityModel is in the .NET Core SDK installer offline cache (currently ~140MB). If you upgraded to netstandard20, we think we can shave ~15 MB from the offline cache because we don't need to bundle a bunch of .NET Standard 1.x packages.
        - Faster restore. .NET Standard 1.x has a notorious problem of pulling in dozens of packages transitively, and most are unnecessary for users targeting .NET Core 2.0 and .NET Framework 4.6.1. By adding netstandard20 to your packages, these packages are no longer necessary.
        - Improved build performance. It costs time to resolve the packages from NETStandard.Library 1.6 and de-duplicate them against .NET Standard 2.0 and .NET Core 2.0 reference assembiles
    - Source-build. ASP.NET Core depends on IdentityModel. We'd like to enable in source-build, but .NET Standard 1.x is not (and won't be) supported source-build (see https://github.com/dotnet/source-build/issues/375)

cc @muratg

**Comment by brentschmaltz** [comment]
@natemcmaster @Tratcher 
We will drop this into 5.2.3.
5.2.2 is slated for 4-23, so too late for this release.

**Comment by natemcmaster** [comment]
Thanks @brentschmaltz!

**Comment by Tratcher** [comment]
What's the time frame for 5.2.3?

**Comment by brentschmaltz** [comment]
@natemcmaster @Tratcher We are going to move 2.0 to the 5.2.6 release and put a 4.6.1 target into 5.2.5

**Comment by natemcmaster** [comment]
@brentschmaltz You can reduce the urgency on this one if we're the only motivation to make changes. We're fine with the status-quo for the 2.x timeframe in .NET Core. We are going to tackle unification to netstandard2.0 again for .NET Core 3.0, but that's farther out -- I'll loop you in on details via email when we have a better idea of what this means.

**Comment by brentschmaltz** [comment]
@natemcmaster keep us in the loop. Are you suggesting we skip 2.0 and move to 3.0?

**Comment by gulbanana** [comment]
.net core 3.0 doesn’t correspond to a .net standard 3.0, so that probably wasn’t the intention

**Comment by brentschmaltz** [comment]
@gulbanana @natemcmaster our next release will have a 2.0 target.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1020

**Comment by natemcmaster** [comment]
Yay!
