### ISSUE TITLE
Any easier way to set TokenValidationParameters.IssuerSigningKey to Support "RSA" and "Ecdsa" both Algorithm  for JwtSecurityTokenHandler  ValidateToken method(I am Using System.IdentityModel.Tokens.Jwt 5.2.2 NuGet package) ?

### ISSUE THREAD

**Issue by anud1** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#926]
Currently we are creating ECDsaSecurityKey class object for ECDsa algorithms and X509SecurityKey class object for RSA algorithms based on a switch condition. Is there any other better way to do this?

**Comment by brentschmaltz** [comment]
@anud1 can you share a bit of the code .

**Comment by anud1** [comment]
Ok.. if we  need to validate various tokens signed with different algorithms(rsa or ecdsasha or... etc. ).. den we  are doing something like this : 


 var validationParameters = new TokenValidationParameters
            {
                ..... some code goes here...
                IssuerSigningKey = GetSecurityKey(signingCert, alg) // Creating key based on switch statement
            };

private SecurityKey GetSecurityKey(X509Certificate2 signingCert, string algorithm)
        {
           
            switch (algorithm)
            {
                case SecurityAlgorithms.EcdsaSha256:
                case SecurityAlgorithms.EcdsaSha256Signature:
                case SecurityAlgorithms.EcdsaSha384:
                case SecurityAlgorithms.EcdsaSha384Signature:
                case SecurityAlgorithms.EcdsaSha512:
                case SecurityAlgorithms.EcdsaSha512Signature:
                    return new ECDsaSecurityKey(new ECDsaCng({CNGkey}));
                case SecurityAlgorithms.RsaSha256:
                case SecurityAlgorithms.RsaSha256Signature:
                case SecurityAlgorithms.RsaSha384:
                case SecurityAlgorithms.RsaSha384Signature:
                case SecurityAlgorithms.RsaSha512:
                case SecurityAlgorithms.RsaSha512Signature:
                    return new X509SecurityKey(signingCert);
		case SecurityAlgorithms.HmacSha256:
                    return new SymmetricSecurityKey({key });

            }
            
    }

**Comment by brentschmaltz** [comment]
@anud1 let us know if you need anything else.
