### ISSUE TITLE
Issiue with UserNameClaimType and RoleClaimType

### ISSUE THREAD

**Issue by jkljajic** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#927]
when you try to change ClaimsIdentity for UserNameClaimType and RoleClaimType it not have effect use standard because of JwtSecurityTokenHandler and MapInboundClaims always take default from mapInboundClams for example if i setup RoleClaimType = name it will use one xml default from MapInboundClams.
to work I need to disable MapInboundClaims = false.
or
`JwtSecurityTokenHandler.DefaultInboundClaimTypeMap = new Dictionary<string, string>();`

Is this bug or.

**Comment by brentschmaltz** [comment]
@jkljajic sorry you are experiencing this issue. Many users have commented about how mapping is a problem. In our 5.2.2 release, we introduced a simple way to turn off mapping. We had to leave mapping on by default for back compatibility reasons.

Here is the fix: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/923

In the 5.2.3 we are planing a new call graph for validating / creating tokens that will have mapping off by default.
