### ISSUE TITLE
ClaimTypeMapping access permission?

### ISSUE THREAD

**Issue by beefsteak** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#929]
public static class JwtRegisteredClaimNamesMappingConvert
    {
        public static string ToClaimTypeName(this string claimTypes)
        {
            switch (claimTypes)
            {
                case ClaimTypes.Name:
                    return JwtRegisteredClaimNames.UniqueName;
                case ClaimTypes.NameIdentifier:
                    return JwtRegisteredClaimNames.NameId;
                case ClaimTypes.Role:
                    return "role";
                default:
                    throw new NotSupportedException(nameof(claimTypes));
            }
        }
    }

if (HttpContext.User.Identity is ClaimsIdentity identity)
            {
                var nameIdClaim = identity.Claims.SingleOrDefault(claim => claim.Type == ClaimTypes.NameIdentifier.ToClaimTypeName());

It would be more convenient to provide this conversion.

**Comment by brentschmaltz** [comment]
@beefsteak You can edit Inbound and Outbound claims mapping with these properties.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L158

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L178

If this doesn't work for you please reopen the issue.
