### ISSUE TITLE
JwtSecurityTokenHandler leaves "actor" as a claim in the claims collection.  Previous versions did not do that. (neither does Saml2SecurityTokenHandler)

### ISSUE THREAD

**Issue by wvdd007** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#93]
In het new version of the `JwtSecurityTokenHandler`, an "actas" token gets correctly transscribed to a jwt token.  However, when reading back the token with 
```c#
public override ClaimsPrincipal ValidateToken(
string securityToken, 
TokenValidationParameters validationParameters,
out SecurityToken validatedToken)
```
We get a `ClaimsPrincipal` with an `Identity` that has a non-null `Actor` property.  This is correct and just like before.  However, in the current version the "actor" field from the jwt gets added as a claim.  This was not the case in the 0.1.0 code.  Which one is correct (IMHO the old version - the `Saml2SecurityTokenHandler` also doesn't add this as a claim so why should the `JwtSecurityTokenHandler` behave differently) ?
Here is an example claim : `http://schemas.xmlsoap.org/ws/2009/09/identity/claims/actor -----> eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJodHRwOi8vc2NoZW1hcy5ldXJvY29uc3VtZXJzL3dzLzIwMTMvMDQvaWRlbnRpdHkvY2xhaW1zL3VzZXJpZCI6InVzcjovL2ZlZC8xMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEifQ.`

**Comment by brentschmaltz** [comment]
If I understand you:
ClaimsIdentity.Actor should be set to a valid ClaimsIdentity if the jwt has the 'actort' claim.
ClaimsIdentity.FindFirst("actort") should be null.

You can make use of the JwtSecurityTokenHandler.InboundClaimFilter (static) and add "actort" this will filter out that claim.

**Comment by wvdd007** [comment]
We use both the `Jwt` and the `Saml2` security token handler.  I was suggesting to have a consistent behavior for both in an `ActAs` scenario.  Both `Saml2` and `Jwt` assign the `Actor` property on the `ClaimsIdentity`.  But `Saml2` does not expose the "`actor`" as a claim, while `jwt` does.  I somehow find this inconsistent.  Since `Saml2` is around for the longest time I would suggest to remove the claim after assiging it to the `Actor` property (`nbf`, `exp` etc are also considered "meta data" and I would suggest handling the `actor` the same way.  It's just a suggestion.

**Comment by brentschmaltz** [comment]
I agree with you, it is inconsistent between SAML and Jwt. 
I updated the status to bug. There was some back and forth about having some of these 'metadata' claims showing up in the ClaimsIdentity. This is what led to the InboundClaimFilter, defaulting to NOT filtering.

**Comment by wvdd007** [comment]
Hello, thanks for dealing with this.
