### ISSUE TITLE
x5t not populated for X509SecurityKey

### ISSUE THREAD

**Issue by C-Ross** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#931]
When using an X509SecurityKey in a SigningCredential to create a JWT the x5t JWT header field is not populated.  Optimally the produced JWT would 

```
var asymmetricSecurityKey = new X509SecurityKey(certificate);
var tokenDescriptor = new SecurityTokenDescriptor()
{
  Audience = c_audience,
  Issuer = c_issuer,
  SigningCredentials = new SigningCredentials(asymmetricSecurityKey, SecurityAlgorithms.RsaSha256),
  Subject = GetClaims(claimInfo)
 };

var tokenHandler = new JwtSecurityTokenHandler { TokenLifetimeInMinutes = 14400, };
string jwt = tokenHandler.CreateEncodedJwt(tokenDescriptor);
```
This produces a properly signed JWT, with the KID populated from the Thumbprint of the X509 Certificate, but the x5t is not.  

> {
>     "alg":  "RS256",
>     "kid":  "429AB025FACD26DEF3071DD77777111D675A4253",
>     "typ":  "JWT"
> }

This causes some consumers such as AAD to not be able to look up the certificate and process the token.

**Comment by brentschmaltz** [comment]
@C-Ross we added back X509SigningCredentials. If you pass that class to JwtHeader, then we create the x5t. That was the behavior in 4.x. Sorry for the hassle.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/0e5a18fdabe68cc8a1f3dc336e0de5e40cf332da
