### ISSUE TITLE
SignatureProvider caching and thread safety

### ISSUE THREAD

**Issue by omsmith** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#934]
Heyo

Looking over the recent signature provider caching changes, I wonder if they're properly respecting the thread safety warnings on `SignatureProvider`?

> Any public static (Shared in Visual Basic) members of this type are thread safe. Any instance members are not guaranteed to be thread safe.
>
> [MSDN](https://msdn.microsoft.com/en-us/library/system.identitymodel.tokens.signatureprovider(v=vs.114).aspx#Anchor_5)

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/cdf16ed31e2c1065fbede2d4e7f870395bdd1b7d/src/Microsoft.IdentityModel.Tokens/InMemoryCryptoProviderCache.cs#L40-L41

Perhaps these should be storing `ThreadLocal<SignatureProvider>` instead?

**Comment by brentschmaltz** [comment]
@omsmith are you concerned about the ConcurrentDictionary OR the SignatureProvider?
Once a SignatureProvider is created, the operations Sign / Verify are atomic.
ConcurrentDictionary was designed to be thread safe.

**Comment by brentschmaltz** [comment]
@omsmith yes the SignatureProvider is thread safe. I will document that.

**Comment by brentschmaltz** [comment]
@omsmith I added some tiny document, just a start really, with a note about this particular issue.
Plans are in place to increase documentation and samples.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Documentation
