### ISSUE TITLE
Validating JWT token based on parameters in WIF configuration

### ISSUE THREAD

**Issue by Hihaj** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#94]
Why oh why is the [`JwtSecurityTokenHandler.ValidateToken`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L641) overload that WIF happens to use not supported? When searching for how to integrate the JwtSecurityTokenHandler with WCF+WIF, all solutions I've found include creating a custom SecurityTokenHandler that inherits from JwtSecurityTokenHandler and implements ValidateToken by populating a TokenValidationParameters instance from WIF configuration. I really, really think there should be an "official" implementation that supports WIF config.

**Comment by brentschmaltz** [comment]
We support config using the 3.0.x releases. 

As for why the change happed, validation using a SecurityToken is problematic when signatures are involved. The original design was a result of the additional complexity of validating the signature of a SAML token as it the C14N transformation. For performance reasons, the signing token was required during deserialization to check the signature.

The current design splits deserialization from signature validation.
