### ISSUE TITLE
Signature with proper kid is still considered as invalid signature when no keys are provided in IssuerSigningKeyResolver

### ISSUE THREAD

**Issue by fabicz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#940]
We have custom `IssuerSigningKeyResolver`, that checks repository of keys based on `kid` passed in 3rd param. If there is no key found it returns empty list - that sounds right to me to do this pre-mapping.

Unfortunately the `ValidateSignature` always returns `SecurityTokenInvalidSignatureException` exception in such case while I would expect to get `SecurityTokenSignatureKeyNotFoundException`.

I think the condition for `SecurityTokenSignatureKeyNotFoundException` to be thrown unnecessary checks `keysAttempted.Length > 0`. I think it's enough that signature is valid based on previous checks. As long as the `kid` is part of valid JWT header and we didn't matched any keys, it should throw `SecurityTokenSignatureKeyNotFoundException`.

**Comment by brentschmaltz** [comment]
@fabicz that makes sense, we'll make this change in 5.2.3.

**Comment by fabicz** [comment]
I actually was doing the temporary workaround today, and realized one more thing. When the Kid doesn't exists in the headers, then actually `new SecurityTokenInvalidSignatureException(TokenLogMessages.IDX10500)` is thrown. which also doesn't sounds right to me. Could you consider this also?

I think to leave the lowest footprint possible for the client customization, If `Kid` is missing then I would expect to throw `SecurityTokenInvalidSignatureException` with some new `TokenLogMessages`. If Kid is present but not matched then `SecurityTokenSignatureKeyNotFoundException` as mentioned above.

**Comment by brentschmaltz** [comment]
@fabicz mafurman cleaned this up quite a bit.
It seems to make sense now. Let us know if it works for you.

@mafurman fyi

**Comment by fabicz** [comment]
@mafurman Thanks, the first idea to throw `SecurityTokenSignatureKeyNotFoundException` in case of no matching keys got solved.

But still my second proposal isn't there. When the JWT token header is missing `kid` claim completely then `SecurityTokenSignatureKeyNotFoundException` is throw as well. In this case I would expect to do some simple validation of the existence if `kid` rather than implementing custom `validationParameters.SignatureValidator` and throw `SecurityTokenInvalidSignatureException`. 

On the other side I can expect some other people having use case, that they don't have `kid` in the token and just try to validate set of keys one by one.

Right now I've an workaround in `validationParameters.IssuerSigningKeyResolver`
            ```
if (String.IsNullOrEmpty(kid))
            {
                throw new SecurityTokenInvalidSignatureException("Unable to validate signature, missing 'kid' in token header.");
            }
```

I don't have ultimate solution as I don't know all the use-cases. Bu i'm open to discussion.
