### ISSUE TITLE
System.FormatException at LogHelper.FormatInvariant when called from IdentityModelEventSource

### ISSUE THREAD

**Issue by aakash1906** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#949]
Added Appinsight listener to IdentityModelEventSource and set loglevel to verbose first
At GetConfigurationAsync of OpenId, there was an exception at string.Format inside LogHelper.FormatInvariant inside IdentityModelEventSource- **PrepareMessage**.

**Comment by aakash1906** [comment]
Raised a pull request to fix the same.

**Comment by brentschmaltz** [comment]
@aakash1906 thanks for the fix. 
We are pushing into dev, can you package up the fix in dev?
We use master as a place holder.

**Comment by aakash1906** [comment]
Have raised a pull request to dev with that fix. Please review

**Comment by brentschmaltz** [comment]
I like the fix, loggers should never fault.
Thanks.

**Comment by aakash1906** [comment]
Thanks for closing this.!
