### ISSUE TITLE
Unable to find Microsoft.IdentityModel.JsonWebTokens package

### ISSUE THREAD

**Issue by sbebrys** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#965]
In package System.IdentityModel.Tokens.Jwt ver. 5.2.4 dependency to  Microsoft.IdentityModel.JsonWebTokens cannot be resolve, because this package isn't in nuget.org.
Maybe yours build and release flow has incorrect order?

**Comment by brentschmaltz** [comment]
@sbebrys something happened with the signature so nuget is hiding the package. I am investigating.

**Comment by brentschmaltz** [comment]
@sbebrys this should be fixed now.
