### ISSUE TITLE
WsFederation Token Encryption (Certificate)

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#966]
_From @qubicaamf on June 19, 2018 8:44_

Hi,
As you can read from [WsFederation authentication doc](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1):

> [Microsoft.AspNetCore.Authentication.WsFederation](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.WsFederation) lacks support for token encryption, so don't configure a token encryption certificate...

We need this feature because of Signle-Sing-On auth system, that we want to implement in ours **public web apps** ([Azure App Services](https://azure.microsoft.com/en-us/services/app-service/) working as relying party-trust in our scenario) and other internal (web based) products.

Do you have any plan to add this feature?

_Copied from original issue: aspnet/Security#1785_

**Comment by brentschmaltz** [comment]
@Tratcher what token types are you looking for encryption support?
We support JSON (JWE), are you looking for SAML2?

**Comment by Tratcher** [comment]
Not I, ask @qubicaamf.

**Comment by brentschmaltz** [comment]
@qubicaamf what token types are you looking for encryption support?
We support JSON (JWE), are you looking for SAML2?

**Comment by qubicaamf** [comment]
Hi @brentschmaltz, yes we are looking for SAML2.

**Comment by brentschmaltz** [comment]
@qubicaamf @Tratcher see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/734

Hopefully this makes it into 5.2.5, Aug 10th.
If not Sept / October.
