### ISSUE TITLE
NotBefore/NotAfter and timezones

### ISSUE THREAD

**Issue by PeteX** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#967]
I've been having a problem where a newly issued certificate is not accepted, because the NotBefore time has not yet been reached.  It seems to be connected with timezones.  According to [the NotBefore documentation](https://docs.microsoft.com/en-gb/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.notbefore?view=netcore-2.1), NotBefore is in local time.  [This file](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/Validators.cs#L213) seems to be responsible for checking that the NotBefore date has been reached, and it is comparing it with UtcNow.

Oddly, [X509SecurityToken.ValidFrom](https://msdn.microsoft.com/en-us/library/system.identitymodel.tokens.x509securitytoken.validfrom(v=vs.110).aspx) is specified as being in UTC, so the other check in the same file seems to be correct.

(I should add, I've checked that my computer's clock has the right time, which would be the obvious cause of problems like this!  Thank you for all your work on the framework, and I hope this report is helpful.)

**Comment by brentschmaltz** [comment]
@PeteX thanks for reporting this. I've been on vacation for a couple of weeks.
It's looks like indeed we should be using local time.

We will fix this in 5.2.5, sorry for the hassle.

**Comment by PeteX** [comment]
No worries and thanks for fixing it.

**Comment by brentschmaltz** [comment]
:shipit:
