### ISSUE TITLE
Using an expiration of JWT Tokens after Unix timestamp overflow does not work

### ISSUE THREAD

**Issue by tcs-devel** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#974]
Using JWT tokens with an expiration after the unix "year 2038 problem" does not work.

A repository to reproduce the issue can be found here: [telecomsoftware/sample-jwt-expiration-issue](https://github.com/telecomsoftware/sample-jwt-expiration-issue)

The issue seems to be in `System.IdentityModel.Tokens.Jwt/JwtPayload.cs` which tries to read the expiration as an `Int32` in `GetIntClaim()` which is causing an overflow when calling `Convert.ToInt32()`.

```
public int? Exp
{
    get { return this.GetIntClaim(JwtRegisteredClaimNames.Exp); }
}
```

...using version 5.2.4

**Comment by hypetsch** [comment]
I have just seen that there is already PR #970 which should fix this issue. So I think it can bei closed?

**Comment by brentschmaltz** [comment]
@tcs-devel @hypetsch we need to get this in a build before we can close the issue.

**Comment by GeoK** [comment]
@tcs-devel @hypetsch We are not going to address this issue at the moment, as the fix would introduce breaking changes.

I'd advise you to keep an eye on [Microsoft.IdentityModel.JsonWebTokens](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/dev/src/Microsoft.IdentityModel.JsonWebTokens) library which is designed to improve the user experience by simplifying and improving performance when creating and validating JWT tokens.
This library will address the _year 2038 problem_.
