### ISSUE TITLE
JWT validation fails when key has leading 0 byte

### ISSUE THREAD

**Issue by coeamyd** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#977]
Dear IdentityModel team,

I am currently having issues validating a jwt token with a jwk set supplied by a third party. The jwk contains an extra field with the certificate representation of the public key. Using this certificate, I can validate the JWT fine using the validator on jwt.io. However, when I use the `JwtSecurityTokenHandler`, validation fails with "IDX10511: Signature validation failed".

I have been able to narrow down on the problem using other crypto libraries. The issue is, that when decoding the "N" value (modulus) from the JWK, it has an extra leading 0 byte when compared to the Modulus from the public key. When both arrays are put into the `BigInteger` class of BouncyCastle, the value is the same, so the leading 0 does not seem to have an effect on the actual modulus.

However, when I remove the leading 0 from the "N" value, reencode it, and write back the value, validation succeeds. 

I have attached a LinqPad query which reproduces this behavior: [ValidateJWT.zip](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/2183765/ValidateJWT.zip)

Library versions used:
- System.IdentityModel.Tokens.Jwt 5.2.4
- Microsoft.IdentityMode.Protocols.OpenIdConnect 5.2.4 (for JsonWebKeySet)
- BouncyCastle 1.8.2 (for debugging only)

I know, validation still fails with the modified key, but that is due to the token having expired (`SecurityTokenExpiredException` as opposed to `SecurityTokenInvalidSignatureException`). Signature validation in particular succeeds.

My questions: Is this erroneous behavior on part of the validator, since the leading 0 does not change the actual modulus? Or is it normal in cryptography, that these leading 0 bytes should lead to errors, and the third party supplying the key needs to fix their code?

Thanks for your help!

Cheers,
Christoph

**Comment by coeamyd** [comment]
After some additional research, I have found that it _does_ seem to be best practice to remove leading 0 bytes in other crypto libraries (see examples here: [https://stackoverflow.com/questions/28154369/why-dropping-leading-all-zeros-byte-in-a-java-byte-array-before-hashing](https://stackoverflow.com/questions/28154369/why-dropping-leading-all-zeros-byte-in-a-java-byte-array-before-hashing)). The question remains, whether this should also be incorporated into the validation logic of this component or in the conversion logic when creating the byte-array from the JWK, or if it should even be part of the hashing component (which is probably the most difficult to change).

**Comment by ycrumeyrolle** [comment]
According to JWK specification of the RSA key representation: 
https://tools.ietf.org/html/rfc7518#section-6.3.1.1

>    Note that implementers have found that some cryptographic libraries
   prefix an extra zero-valued octet to the modulus representations they
   return, for instance, returning 257 octets for a 2048-bit key, rather
   than 256.  Implementations using such libraries will need to take
   care to omit the extra octet from the base64url-encoded
   representation.

The leading zero does not change the BouncyCastle BigInteger representation, but it does change the byte array representation. 
It looks to be an issue with the jwks provided by your third party.

**Comment by coeamyd** [comment]
Perfect, thanks a lot for the link. Now, I finally have a normative document to show that the other side is wrong. :-)

Then, I guess this is not an issue for this project. Sorry for the inconvenience.

Cheers and thanks for all the good work that went into this project,
Christoph
