### ISSUE TITLE
Unable to verify due key size?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#979]
Hi,

I should be able to verify this

```
{
token:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuZHJldyIsImlhdCI6MTUzMjY5Mzc5M30.8vmF__bJDs61jD-3N19EOem5Z8OvMVbTVEfv9VqjW9g',
secret:'aaa'
}
```
but got this instead

![image](https://user-images.githubusercontent.com/12871379/43320889-69a4ca10-91aa-11e8-9c72-c1ab03178647.png)

With jsonwebtoken in nodejs, it works

**Comment by brentschmaltz** [comment]
@andrew-vandenbrink best practices require a key of a minimum size in order to have high confidence that tampering has not take place. If you need to handle such cases you will need to use extensibility.
