### ISSUE TITLE
KeyVault scenarios need to support AccessTokens and Credentials.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#980]
I can see three possibilities for KeyVault scenarios.
1. the host is running in a secure cluster, no credentials.
2. the host has obtained an access token for KeyVault.
3. the host has credentials to get an access token for KeyVault.

Our current deliverable is tailored to 1. 
This issue is about supporting 2,3.
We can push implementation off till vNext, but need to make sure it will fit nicely.

**Comment by CBaud** [comment]
This is included in the current implementation of issue #936.

**Comment by CBaud** [comment]
Moving to 5.2.5 since this work is already implemented in pull request #984.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/984
