### ISSUE TITLE
Typo in JwtSecurityToken comment

### ISSUE THREAD

**Issue by Jeroenh13** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#999]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6e7a53e241e4566998d3bf365f03acd0da699a31/src/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.cs#L415

The is spelled like teh.

**Comment by brentschmaltz** [comment]
@mafurman can you touch this up? Add it to an existing item.

**Comment by mafurman** [comment]
@brentschmaltz Done! I added this fix to this PR: #991.
